.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/examples/3-options-input-fn.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/examples/3-options-input-fn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <soxr\&.h>\fP
.br
\fC#include 'examples\-common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinput_context_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBbuf_total_len\fP   15000  /* \fBIn\fP \fBsamples\fP per channel\&. */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP n, char \fBconst\fP *arg[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define buf_total_len   15000  /* \fBIn\fP \fBsamples\fP per channel\&. */"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP n, char \fBconst\fP * arg[])"

.PP
Definition at line 43 of file 3\-options\-input\-fn\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
