.TH "__MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmdeviceapi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LPARAM \fBAddPageParam\fP"
.br
.ti -1c
.RI "\fBIMMDevice\fP * \fBpEndpoint\fP"
.br
.ti -1c
.RI "\fBIMMDevice\fP * \fBpPnpInterface\fP"
.br
.ti -1c
.RI "\fBIMMDevice\fP * \fBpPnpDevnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 886 of file mmdeviceapi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "LPARAM __MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001::AddPageParam"

.PP
Definition at line 888 of file mmdeviceapi\&.h\&.
.SS "\fBIMMDevice\fP* __MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001::pEndpoint"

.PP
Definition at line 889 of file mmdeviceapi\&.h\&.
.SS "\fBIMMDevice\fP* __MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001::pPnpDevnode"

.PP
Definition at line 891 of file mmdeviceapi\&.h\&.
.SS "\fBIMMDevice\fP* __MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001::pPnpInterface"

.PP
Definition at line 890 of file mmdeviceapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
