.TH "__PaWinWdmFilter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__PaWinWdmFilter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHANDLE\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBPaWinWDMKSDeviceInfo\fP \fBdevInfo\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdeviceNode\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpinCount\fP"
.br
.ti -1c
.RI "\fBPaWinWdmPin\fP ** \fBpins\fP"
.br
.ti -1c
.RI "\fBPaWinWdmFilter\fP * \fBtopologyFilter\fP"
.br
.ti -1c
.RI "wchar_t \fBfriendlyName\fP [MAX_PATH]"
.br
.ti -1c
.RI "\fBint\fP \fBvalidPinCount\fP"
.br
.ti -1c
.RI "\fBint\fP \fBusageCount\fP"
.br
.ti -1c
.RI "\fBKSMULTIPLE_ITEM\fP * \fBconnections\fP"
.br
.ti -1c
.RI "\fBKSMULTIPLE_ITEM\fP * \fBnodes\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfilterRefCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 300 of file pa_win_wdmks\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSMULTIPLE_ITEM\fP* __PaWinWdmFilter::connections"

.PP
Definition at line 312 of file pa_win_wdmks\&.c\&.
.SS "\fBDWORD\fP __PaWinWdmFilter::deviceNode"

.PP
Definition at line 305 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWinWDMKSDeviceInfo\fP __PaWinWdmFilter::devInfo"

.PP
Definition at line 303 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmFilter::filterRefCount"

.PP
Definition at line 314 of file pa_win_wdmks\&.c\&.
.SS "wchar_t __PaWinWdmFilter::friendlyName[MAX_PATH]"

.PP
Definition at line 309 of file pa_win_wdmks\&.c\&.
.SS "\fBHANDLE\fP __PaWinWdmFilter::handle"

.PP
Definition at line 302 of file pa_win_wdmks\&.c\&.
.SS "\fBKSMULTIPLE_ITEM\fP* __PaWinWdmFilter::nodes"

.PP
Definition at line 313 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmFilter::pinCount"

.PP
Definition at line 306 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWinWdmPin\fP** __PaWinWdmFilter::pins"

.PP
Definition at line 307 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWinWdmFilter\fP* __PaWinWdmFilter::topologyFilter"

.PP
Definition at line 308 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmFilter::usageCount"

.PP
Definition at line 311 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmFilter::validPinCount"

.PP
Definition at line 310 of file pa_win_wdmks\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
