.TH "__PaWinWdmStream" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__PaWinWdmStream \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaUtilStreamRepresentation\fP \fBstreamRepresentation\fP"
.br
.ti -1c
.RI "\fBPaWDMKSSpecificStreamInfo\fP \fBhostApiStreamInfo\fP"
.br
.ti -1c
.RI "\fBPaUtilCpuLoadMeasurer\fP \fBcpuLoadMeasurer\fP"
.br
.ti -1c
.RI "\fBPaUtilBufferProcessor\fP \fBbufferProcessor\fP"
.br
.ti -1c
.RI "\fBPaUtilAllocationGroup\fP * \fBallocGroup\fP"
.br
.ti -1c
.RI "\fBPaWinWdmIOInfo\fP \fBcapture\fP"
.br
.ti -1c
.RI "\fBPaWinWdmIOInfo\fP \fBrender\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstreamStarted\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstreamActive\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstreamStop\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstreamAbort\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoldProcessPriority\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBstreamThread\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBeventAbort\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBeventStreamStart\fP [\fBStreamStart_kCnt\fP]"
.br
.ti -1c
.RI "\fBPaError\fP \fBthreadResult\fP"
.br
.ti -1c
.RI "\fBPaStreamFlags\fP \fBstreamFlags\fP"
.br
.ti -1c
.RI "\fBPaUtilRingBuffer\fP \fBringBuffer\fP"
.br
.ti -1c
.RI "char * \fBringBufferData\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuserInputChannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdeviceInputChannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuserOutputChannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdeviceOutputChannels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 371 of file pa_win_wdmks\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaUtilAllocationGroup\fP* __PaWinWdmStream::allocGroup"

.PP
Definition at line 382 of file pa_win_wdmks\&.c\&.
.SS "\fBPaUtilBufferProcessor\fP __PaWinWdmStream::bufferProcessor"

.PP
Definition at line 376 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWinWdmIOInfo\fP __PaWinWdmStream::capture"

.PP
Definition at line 383 of file pa_win_wdmks\&.c\&.
.SS "\fBPaUtilCpuLoadMeasurer\fP __PaWinWdmStream::cpuLoadMeasurer"

.PP
Definition at line 375 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::deviceInputChannels"

.PP
Definition at line 403 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::deviceOutputChannels"

.PP
Definition at line 405 of file pa_win_wdmks\&.c\&.
.SS "\fBHANDLE\fP __PaWinWdmStream::eventAbort"

.PP
Definition at line 391 of file pa_win_wdmks\&.c\&.
.SS "\fBHANDLE\fP __PaWinWdmStream::eventStreamStart[\fBStreamStart_kCnt\fP]"

.PP
Definition at line 392 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWDMKSSpecificStreamInfo\fP __PaWinWdmStream::hostApiStreamInfo"

.PP
Definition at line 374 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::oldProcessPriority"

.PP
Definition at line 389 of file pa_win_wdmks\&.c\&.
.SS "\fBPaWinWdmIOInfo\fP __PaWinWdmStream::render"

.PP
Definition at line 384 of file pa_win_wdmks\&.c\&.
.SS "\fBPaUtilRingBuffer\fP __PaWinWdmStream::ringBuffer"

.PP
Definition at line 397 of file pa_win_wdmks\&.c\&.
.SS "char* __PaWinWdmStream::ringBufferData"

.PP
Definition at line 398 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::streamAbort"

.PP
Definition at line 388 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::streamActive"

.PP
Definition at line 386 of file pa_win_wdmks\&.c\&.
.SS "\fBPaStreamFlags\fP __PaWinWdmStream::streamFlags"

.PP
Definition at line 394 of file pa_win_wdmks\&.c\&.
.SS "\fBPaUtilStreamRepresentation\fP __PaWinWdmStream::streamRepresentation"

.PP
Definition at line 373 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::streamStarted"

.PP
Definition at line 385 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::streamStop"

.PP
Definition at line 387 of file pa_win_wdmks\&.c\&.
.SS "\fBHANDLE\fP __PaWinWdmStream::streamThread"

.PP
Definition at line 390 of file pa_win_wdmks\&.c\&.
.SS "\fBPaError\fP __PaWinWdmStream::threadResult"

.PP
Definition at line 393 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::userInputChannels"

.PP
Definition at line 402 of file pa_win_wdmks\&.c\&.
.SS "\fBint\fP __PaWinWdmStream::userOutputChannels"

.PP
Definition at line 404 of file pa_win_wdmks\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
