.TH "__PaWinWDMScanDeviceInfosResults" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__PaWinWDMScanDeviceInfosResults \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaDeviceInfo\fP ** \fBdeviceInfos\fP"
.br
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBdefaultInputDevice\fP"
.br
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBdefaultOutputDevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 428 of file pa_win_wdmks\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaDeviceIndex\fP __PaWinWDMScanDeviceInfosResults::defaultInputDevice"

.PP
Definition at line 431 of file pa_win_wdmks\&.c\&.
.SS "\fBPaDeviceIndex\fP __PaWinWDMScanDeviceInfosResults::defaultOutputDevice"

.PP
Definition at line 432 of file pa_win_wdmks\&.c\&.
.SS "\fBPaDeviceInfo\fP** __PaWinWDMScanDeviceInfosResults::deviceInfos"

.PP
Definition at line 430 of file pa_win_wdmks\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
