.TH "_CC_HW_FIELD" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_CC_HW_FIELD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVBICODECFILTERING_SCANLINES\fP \fBScanlinesRequested\fP"
.br
.ti -1c
.RI "ULONG \fBfieldFlags\fP"
.br
.ti -1c
.RI "LONGLONG \fBPictureNumber\fP"
.br
.ti -1c
.RI "\fBCC_BYTE_PAIR\fP \fBLines\fP [\fBCC_MAX_HW_DECODE_LINES\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2864 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _CC_HW_FIELD::fieldFlags"

.PP
Definition at line 2866 of file ksmedia\&.h\&.
.SS "\fBCC_BYTE_PAIR\fP _CC_HW_FIELD::Lines[\fBCC_MAX_HW_DECODE_LINES\fP]"

.PP
Definition at line 2868 of file ksmedia\&.h\&.
.SS "LONGLONG _CC_HW_FIELD::PictureNumber"

.PP
Definition at line 2867 of file ksmedia\&.h\&.
.SS "\fBVBICODECFILTERING_SCANLINES\fP _CC_HW_FIELD::ScanlinesRequested"

.PP
Definition at line 2865 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
