.TH "_DDPIXELFORMAT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DDPIXELFORMAT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDWORD\fP \fBdwSize\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwFlags\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwFourCC\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwRGBBitCount\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwYUVBitCount\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwZBufferBitDepth\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwAlphaBitDepth\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwRBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwYBitMask\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwGBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwUBitMask\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwBBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwVBitMask\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwRGBAlphaBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwYUVAlphaBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwRGBZBitMask\fP"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwYUVZBitMask\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4171 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "\fBDWORD\fP _DDPIXELFORMAT::dwAlphaBitDepth"

.PP
Definition at line 4181 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwBBitMask"

.PP
Definition at line 4195 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwFlags"

.PP
Definition at line 4174 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwFourCC"

.PP
Definition at line 4175 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwGBitMask"

.PP
Definition at line 4190 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwRBitMask"

.PP
Definition at line 4185 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwRGBAlphaBitMask"

.PP
Definition at line 4200 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwRGBBitCount"

.PP
Definition at line 4178 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwRGBZBitMask"

.PP
Definition at line 4202 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwSize"

.PP
Definition at line 4173 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwUBitMask"

.PP
Definition at line 4191 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwVBitMask"

.PP
Definition at line 4196 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwYBitMask"

.PP
Definition at line 4186 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwYUVAlphaBitMask"

.PP
Definition at line 4201 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwYUVBitCount"

.PP
Definition at line 4179 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwYUVZBitMask"

.PP
Definition at line 4203 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDPIXELFORMAT::dwZBufferBitDepth"

.PP
Definition at line 4180 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
