.TH "_DDVIDEOPORTCONNECT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_DDVIDEOPORTCONNECT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDWORD\fP \fBdwSize\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwPortWidth\fP"
.br
.ti -1c
.RI "GUID \fBguidTypeID\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwFlags\fP"
.br
.ti -1c
.RI "ULONG_PTR \fBdwReserved1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4209 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDWORD\fP _DDVIDEOPORTCONNECT::dwFlags"

.PP
Definition at line 4213 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDVIDEOPORTCONNECT::dwPortWidth"

.PP
Definition at line 4211 of file ksmedia\&.h\&.
.SS "ULONG_PTR _DDVIDEOPORTCONNECT::dwReserved1"

.PP
Definition at line 4214 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP _DDVIDEOPORTCONNECT::dwSize"

.PP
Definition at line 4210 of file ksmedia\&.h\&.
.SS "GUID _DDVIDEOPORTCONNECT::guidTypeID"

.PP
Definition at line 4212 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
