.TH "_KS_COPY_MACROVISION" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_KS_COPY_MACROVISION \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBMACROVISIONLevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2300 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG _KS_COPY_MACROVISION::MACROVISIONLevel"

.PP
Definition at line 2301 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
