.TH "_LV2_Log" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LV2_Log \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_Log_Handle\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBint\fP(* \fBprintf\fP )(\fBLV2_Log_Handle\fP \fBhandle\fP, \fBLV2_URID\fP type, \fBconst\fP char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBint\fP(* \fBvprintf\fP )(\fBLV2_Log_Handle\fP \fBhandle\fP, \fBLV2_URID\fP type, \fBconst\fP char *fmt, va_list ap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log feature (LV2_LOG__log) 
.PP
Definition at line 58 of file log\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLV2_Log_Handle\fP _LV2_Log::handle"
Opaque pointer to host data\&.
.PP
This MUST be passed to methods in this struct whenever they are called\&. Otherwise, it must not be interpreted in any way\&. 
.PP
Definition at line 65 of file log\&.h\&.
.SS "\fBint\fP(* _LV2_Log::printf) (\fBLV2_Log_Handle\fP \fBhandle\fP, \fBLV2_URID\fP type, \fBconst\fP char *fmt,\&.\&.\&.)"
Log a message, passing format parameters directly\&.
.PP
The API of this function matches that of the standard C printf function, except for the addition of the first two parameters\&. This function may be called from any non-realtime context, or from any context if \fCtype\fP is \fBLV2_LOG__Trace\fP\&. 
.PP
Definition at line 76 of file log\&.h\&.
.SS "\fBint\fP(* _LV2_Log::vprintf) (\fBLV2_Log_Handle\fP \fBhandle\fP, \fBLV2_URID\fP type, \fBconst\fP char *fmt, va_list ap)"
Log a message, passing format parameters in a va_list\&.
.PP
The API of this function matches that of the standard C vprintf function, except for the addition of the first two parameters\&. This function may be called from any non-realtime context, or from any context if \fCtype\fP is \fBLV2_LOG__Trace\fP\&. 
.PP
Definition at line 89 of file log\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
