.TH "_LV2_URID_Unmap" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LV2_URID_Unmap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <urid\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_URID_Unmap_Handle\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBconst\fP char *(* \fBunmap\fP )(\fBLV2_URID_Unmap_Handle\fP \fBhandle\fP, \fBLV2_URID\fP urid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
URI Unmap Feature (LV2_URID__unmap) 
.PP
Definition at line 97 of file urid\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLV2_URID_Unmap_Handle\fP _LV2_URID_Unmap::handle"
Opaque pointer to host data\&.
.PP
This MUST be passed to \fBunmap()\fP whenever it is called\&. Otherwise, it must not be interpreted in any way\&. 
.PP
Definition at line 104 of file urid\&.h\&.
.SS "\fBconst\fP char*(* _LV2_URID_Unmap::unmap) (\fBLV2_URID_Unmap_Handle\fP \fBhandle\fP, \fBLV2_URID\fP urid)"
Get the URI for a previously mapped numeric ID\&.
.PP
Returns NULL if \fCurid\fP is not yet mapped\&. Otherwise, the corresponding URI is returned in a canonical form\&. This MAY not be the exact same string that was originally passed to \fBLV2_URID_Map::map()\fP, but it MUST be an identical URI according to the URI syntax specification (RFC3986)\&. A non-NULL return for a given \fCurid\fP will always be the same for the life of the plugin\&. Plugins that intend to perform string comparison on unmapped \fBURIs\fP SHOULD first canonicalise URI strings with a call to map_uri() followed by a call to unmap_uri()\&.
.PP
\fBParameters:\fP
.RS 4
\fIhandle\fP Must be the callback_data member of this struct\&. 
.br
\fIurid\fP The ID to be mapped back to the URI string\&. 
.RE
.PP

.PP
Definition at line 121 of file urid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
