.TH "_LV2_Options_Option" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LV2_Options_Option \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_Options_Context\fP \fBcontext\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsubject\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBvoid\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An option\&.
.PP
This is a property with a subject, also known as a triple or statement\&.
.PP
This struct is useful anywhere a statement needs to be passed where no memory ownership issues are present (since the value is a const pointer)\&.
.PP
Options can be passed to an instance via the feature LV2_OPTIONS__options with data pointed to an array of options terminated by a zeroed option, or accessed/manipulated using LV2_Options_Interface\&. 
.PP
Definition at line 79 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLV2_Options_Context\fP _LV2_Options_Option::context"
Context (type of subject)\&. 
.PP
Definition at line 80 of file options\&.h\&.
.SS "\fBLV2_URID\fP _LV2_Options_Option::key"
Key (property)\&. 
.PP
Definition at line 82 of file options\&.h\&.
.SS "\fBuint32_t\fP _LV2_Options_Option::size"
Size of value in bytes\&. 
.PP
Definition at line 83 of file options\&.h\&.
.SS "\fBuint32_t\fP _LV2_Options_Option::subject"
Subject\&. 
.PP
Definition at line 81 of file options\&.h\&.
.SS "\fBLV2_URID\fP _LV2_Options_Option::type"
Type of value (datatype)\&. 
.PP
Definition at line 84 of file options\&.h\&.
.SS "\fBconst\fP \fBvoid\fP* _LV2_Options_Option::value"
Pointer to value (object)\&. 
.PP
Definition at line 85 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
