.TH "_NABTS_BUFFER_LINE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_NABTS_BUFFER_LINE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBConfidence\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBBytes\fP [\fBNABTS_BYTES_PER_LINE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2874 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBYTE\fP _NABTS_BUFFER_LINE::Bytes[\fBNABTS_BYTES_PER_LINE\fP]"

.PP
Definition at line 2876 of file ksmedia\&.h\&.
.SS "\fBBYTE\fP _NABTS_BUFFER_LINE::Confidence"

.PP
Definition at line 2875 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
