.TH "_sbsms_::__fft< istride, ostride, 2, dir >" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::__fft< istride, ostride, 2, dir > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fft\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBi1\fP = istride, \fBo1\fP = ostride, \fBir0\fP = 0, \fBii0\fP = 1, \fBor0\fP = 0, \fBoi0\fP = 1, \fBir1\fP = i1<<1, \fBii1\fP = ir1 + 1, \fBor1\fP = o1<<1, \fBoi1\fP = or1 + 1 }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBexecute\fP (\fBt_fft\fP *_x, \fBt_fft\fP *_y, \fBint\fP step)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int istride, int ostride, int dir>
.br
class _sbsms_::__fft< istride, ostride, 2, dir >"

.PP
Definition at line 86 of file fft\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "template<int istride, int ostride, int dir> anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIi1 \fP\fP
.TP
\fB\fIo1 \fP\fP
.TP
\fB\fIir0 \fP\fP
.TP
\fB\fIii0 \fP\fP
.TP
\fB\fIor0 \fP\fP
.TP
\fB\fIoi0 \fP\fP
.TP
\fB\fIir1 \fP\fP
.TP
\fB\fIii1 \fP\fP
.TP
\fB\fIor1 \fP\fP
.TP
\fB\fIoi1 \fP\fP
.PP
Definition at line 88 of file fft\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int istride, int ostride, int dir> static \fBvoid\fP \fB_sbsms_::__fft\fP< istride, ostride, 2, dir >::execute (\fBt_fft\fP * _x, \fBt_fft\fP * _y, \fBint\fP step)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 91 of file fft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
