.TH "_sbsms_::LastFactor< N >" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::LastFactor< N > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fft\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBradix\fP = Factor<N>::value, \fBstride\fP = N / radix, \fBvalue\fP = (stride==1?radix:LastFactor<stride>::value) }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int N>
.br
class _sbsms_::LastFactor< N >"

.PP
Definition at line 30 of file fft\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "template<int N> anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIradix \fP\fP
.TP
\fB\fIstride \fP\fP
.TP
\fB\fIvalue \fP\fP
.PP
Definition at line 32 of file fft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
