.TH "_sbsms_::fft_order_< N >" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::fft_order_< N > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fft\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBint\fP \fBiterate\fP (\fBint\fP \fBk\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int N>
.br
class _sbsms_::fft_order_< N >"

.PP
Definition at line 794 of file fft\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int N> static \fBint\fP \fB_sbsms_::fft_order_\fP< \fBN\fP >::iterate (\fBint\fP k)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 796 of file fft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
