.TH "_sbsms_::SBSMSTrack" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::SBSMSTrack \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sbsms\&.h>\fP
.PP
Inherited by \fB_sbsms_::Track\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SBSMSTrack\fP ()"
.br
.ti -1c
.RI "virtual \fBSBSMSTrackPoint\fP * \fBgetSBSMSTrackPoint\fP (\fBconst\fP \fBTimeType\fP &time)=0"
.br
.ti -1c
.RI "virtual \fBTrackIndexType\fP \fBgetIndex\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBisFirst\fP (\fBconst\fP \fBTimeType\fP &synthtime)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBisLast\fP (\fBconst\fP \fBTimeType\fP &synthtime)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file sbsms\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual _sbsms_::SBSMSTrack::~SBSMSTrack ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 71 of file sbsms\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTrackIndexType\fP _sbsms_::SBSMSTrack::getIndex ()\fC [pure virtual]\fP"

.PP
Implemented in \fB_sbsms_::Track\fP\&.
.SS "virtual \fBSBSMSTrackPoint\fP* _sbsms_::SBSMSTrack::getSBSMSTrackPoint (\fBconst\fP \fBTimeType\fP & time)\fC [pure virtual]\fP"

.PP
Implemented in \fB_sbsms_::Track\fP\&.
.SS "virtual \fBbool\fP _sbsms_::SBSMSTrack::isFirst (\fBconst\fP \fBTimeType\fP & synthtime)\fC [pure virtual]\fP"

.PP
Implemented in \fB_sbsms_::Track\fP\&.
.SS "virtual \fBbool\fP _sbsms_::SBSMSTrack::isLast (\fBconst\fP \fBTimeType\fP & synthtime)\fC [pure virtual]\fP"

.PP
Implemented in \fB_sbsms_::Track\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
