.TH "_sbsms_::grain" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::grain \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grain\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~grain\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBanalyze\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsynthesize\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdownsample\fP (\fBgrain\fP *gdown)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBaudio\fP * \fBx\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgrain\fP (\fBint\fP \fBN\fP, \fBint\fP N2)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float * \fBw\fP"
.br
.ti -1c
.RI "\fBint\fP \fBN\fP"
.br
.ti -1c
.RI "float \fBsynthScale\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefCount\fP"
.br
.ti -1c
.RI "\fBfftplan\fP \fBfftPlan\fP"
.br
.ti -1c
.RI "\fBfftplan\fP \fBifftPlan\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGrainAllocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file grain\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_sbsms_::grain::~grain ()"

.PP
Definition at line 97 of file grain\&.cpp\&.
.SS "_sbsms_::grain::grain (\fBint\fP N, \fBint\fP N2)\fC [protected]\fP"

.PP
Definition at line 90 of file grain\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _sbsms_::grain::analyze ()"

.PP
Definition at line 102 of file grain\&.cpp\&.
.SS "\fBvoid\fP _sbsms_::grain::downsample (\fBgrain\fP * gdown)"

.PP
Definition at line 125 of file grain\&.cpp\&.
.SS "\fBvoid\fP _sbsms_::grain::synthesize ()"

.PP
Definition at line 115 of file grain\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBGrainAllocator\fP\fC [friend]\fP"

.PP
Definition at line 24 of file grain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfftplan\fP _sbsms_::grain::fftPlan\fC [protected]\fP"

.PP
Definition at line 31 of file grain\&.h\&.
.SS "\fBfftplan\fP _sbsms_::grain::ifftPlan\fC [protected]\fP"

.PP
Definition at line 32 of file grain\&.h\&.
.SS "\fBint\fP _sbsms_::grain::N\fC [protected]\fP"

.PP
Definition at line 28 of file grain\&.h\&.
.SS "\fBint\fP _sbsms_::grain::refCount\fC [protected]\fP"

.PP
Definition at line 30 of file grain\&.h\&.
.SS "float _sbsms_::grain::synthScale\fC [protected]\fP"

.PP
Definition at line 29 of file grain\&.h\&.
.SS "float* _sbsms_::grain::w\fC [protected]\fP"

.PP
Definition at line 27 of file grain\&.h\&.
.SS "\fBaudio\fP* _sbsms_::grain::x"

.PP
Definition at line 23 of file grain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
