.TH "_sbsms_::SBSMSImp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::SBSMSImp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSBSMSImp\fP (\fBint\fP \fBchannels\fP, \fBSBSMSQuality\fP *\fBquality\fP, \fBbool\fP bSynthesize)"
.br
.ti -1c
.RI "\fB~SBSMSImp\fP ()"
.br
.ti -1c
.RI "long \fBread\fP (\fBSBSMSInterface\fP *iface, \fBaudio\fP *\fBbuf\fP, long n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBaddRenderer\fP (\fBSBSMSRenderer\fP *renderer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremoveRenderer\fP (\fBSBSMSRenderer\fP *renderer)"
.br
.ti -1c
.RI "long \fBrenderFrame\fP (\fBSBSMSInterface\fP *iface)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSubBand\fP * \fBtop\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.ti -1c
.RI "float \fBgetInputTime\fP (\fBSBSMSInterface\fP *iface)"
.br
.ti -1c
.RI "long \fBwrite\fP (\fBSBSMSInterface\fP *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfpIn\fP"
.br
.ti -1c
.RI "FILE * \fBfpOut\fP"
.br
.ti -1c
.RI "\fBSBSMSError\fP \fBerror\fP"
.br
.ti -1c
.RI "long \fBnPrepad\fP"
.br
.ti -1c
.RI "long \fBnPrepadDone\fP"
.br
.ti -1c
.RI "long \fBnPresamplesDone\fP"
.br
.ti -1c
.RI "\fBSampleCountType\fP \fBnSamplesInputed\fP"
.br
.ti -1c
.RI "\fBSampleCountType\fP \fBnSamplesOutputed\fP"
.br
.ti -1c
.RI "\fBint\fP \fBchannels\fP"
.br
.ti -1c
.RI "\fBSBSMSQuality\fP * \fBquality\fP"
.br
.ti -1c
.RI "\fBaudio\fP * \fBina\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSBSMS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file sbsms\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_sbsms_::SBSMSImp::SBSMSImp (\fBint\fP channels, \fBSBSMSQuality\fP * quality, \fBbool\fP bSynthesize)"

.PP
Definition at line 614 of file sbsms\&.cpp\&.
.SS "_sbsms_::SBSMSImp::~SBSMSImp ()"

.PP
Definition at line 629 of file sbsms\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP _sbsms_::SBSMSImp::addRenderer (\fBSBSMSRenderer\fP * renderer)\fC [inline]\fP"

.PP
Definition at line 640 of file sbsms\&.cpp\&.
.SS "float _sbsms_::SBSMSImp::getInputTime (\fBSBSMSInterface\fP * iface)\fC [protected]\fP"

.PP
Definition at line 656 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::read (\fBSBSMSInterface\fP * iface, \fBaudio\fP * buf, long n)\fC [inline]\fP"

.PP
Definition at line 699 of file sbsms\&.cpp\&.
.SS "\fBvoid\fP _sbsms_::SBSMSImp::removeRenderer (\fBSBSMSRenderer\fP * renderer)\fC [inline]\fP"

.PP
Definition at line 646 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::renderFrame (\fBSBSMSInterface\fP * iface)\fC [inline]\fP"

.PP
Definition at line 741 of file sbsms\&.cpp\&.
.SS "\fBvoid\fP _sbsms_::SBSMSImp::reset (\fBvoid\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 604 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::write (\fBSBSMSInterface\fP * iface)\fC [protected]\fP"

.PP
Definition at line 661 of file sbsms\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSBSMS\fP\fC [friend]\fP"

.PP
Definition at line 67 of file sbsms\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP _sbsms_::SBSMSImp::channels\fC [protected]\fP"

.PP
Definition at line 80 of file sbsms\&.cpp\&.
.SS "\fBSBSMSError\fP _sbsms_::SBSMSImp::error\fC [protected]\fP"

.PP
Definition at line 74 of file sbsms\&.cpp\&.
.SS "FILE* _sbsms_::SBSMSImp::fpIn\fC [protected]\fP"

.PP
Definition at line 72 of file sbsms\&.cpp\&.
.SS "FILE* _sbsms_::SBSMSImp::fpOut\fC [protected]\fP"

.PP
Definition at line 73 of file sbsms\&.cpp\&.
.SS "\fBaudio\fP* _sbsms_::SBSMSImp::ina\fC [protected]\fP"

.PP
Definition at line 82 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::nPrepad\fC [protected]\fP"

.PP
Definition at line 75 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::nPrepadDone\fC [protected]\fP"

.PP
Definition at line 76 of file sbsms\&.cpp\&.
.SS "long _sbsms_::SBSMSImp::nPresamplesDone\fC [protected]\fP"

.PP
Definition at line 77 of file sbsms\&.cpp\&.
.SS "\fBSampleCountType\fP _sbsms_::SBSMSImp::nSamplesInputed\fC [protected]\fP"

.PP
Definition at line 78 of file sbsms\&.cpp\&.
.SS "\fBSampleCountType\fP _sbsms_::SBSMSImp::nSamplesOutputed\fC [protected]\fP"

.PP
Definition at line 79 of file sbsms\&.cpp\&.
.SS "\fBSBSMSQuality\fP* _sbsms_::SBSMSImp::quality\fC [protected]\fP"

.PP
Definition at line 81 of file sbsms\&.cpp\&.
.SS "\fBSubBand\fP* _sbsms_::SBSMSImp::top"

.PP
Definition at line 62 of file sbsms\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
