.TH "_sbsms_::_fft< k, 1, radix, dir >" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sbsms_::_fft< k, 1, radix, dir > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fft\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBexecute\fP (\fBt_fft\fP *x)"
.br
.ti -1c
.RI "static \fBvoid\fP \fBloop\fP (\fBt_fft\fP *x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int k, int radix, int dir>
.br
class _sbsms_::_fft< k, 1, radix, dir >"

.PP
Definition at line 780 of file fft\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int k, int radix, int dir> static \fBvoid\fP \fB_sbsms_::_fft\fP< \fBk\fP, 1, radix, dir >::execute (\fBt_fft\fP< \fBk\fP, 1, radix, dir > * x)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 782 of file fft\&.h\&.
.SS "template<int k, int radix, int dir> static \fBvoid\fP \fB_sbsms_::_fft\fP< \fBk\fP, 1, radix, dir >::loop (\fBt_fft\fP< \fBk\fP, 1, radix, dir > * x)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 783 of file fft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
