.TH "_VBICODECFILTERING_STATISTICS_CC" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_VBICODECFILTERING_STATISTICS_CC \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVBICODECFILTERING_STATISTICS_COMMON\fP \fBCommon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2948 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVBICODECFILTERING_STATISTICS_COMMON\fP _VBICODECFILTERING_STATISTICS_CC::Common"

.PP
Definition at line 2949 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
