.TH "AboutDialogCreditItem" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDialogCreditItem \- \fBAboutDialogCreditItem\fP is a structure used by the \fBAboutDialog\fP to hold information about one contributor to Audacity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AboutDialog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDialogCreditItem\fP (wxString &&description_, \fBint\fP role_)"
.br
.ti -1c
.RI "\fBAboutDialogCreditItem\fP (\fBconst\fP \fBAboutDialogCreditItem\fP &) \fBPROHIBITED\fP"
.br
.ti -1c
.RI "\fBAboutDialogCreditItem\fP & \fBoperator=\fP (\fBconst\fP \fBAboutDialogCreditItem\fP &) \fBPROHIBITED\fP"
.br
.ti -1c
.RI "\fBAboutDialogCreditItem\fP (\fBAboutDialogCreditItem\fP &&moveMe)"
.br
.ti -1c
.RI "\fB~AboutDialogCreditItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxString \fBdescription\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrole\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAboutDialogCreditItem\fP is a structure used by the \fBAboutDialog\fP to hold information about one contributor to Audacity\&. 
.PP
Definition at line 23 of file AboutDialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AboutDialogCreditItem::AboutDialogCreditItem (wxString && description_, \fBint\fP role_)\fC [inline]\fP"

.PP
Definition at line 27 of file AboutDialog\&.h\&.
.SS "AboutDialogCreditItem::AboutDialogCreditItem (\fBconst\fP \fBAboutDialogCreditItem\fP &)"

.SS "AboutDialogCreditItem::AboutDialogCreditItem (\fBAboutDialogCreditItem\fP && moveMe)\fC [inline]\fP"

.PP
Definition at line 41 of file AboutDialog\&.h\&.
.SS "AboutDialogCreditItem::~AboutDialogCreditItem ()\fC [inline]\fP"

.PP
Definition at line 47 of file AboutDialog\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAboutDialogCreditItem\fP& AboutDialogCreditItem::operator= (\fBconst\fP \fBAboutDialogCreditItem\fP &)"

.SH "Member Data Documentation"
.PP 
.SS "wxString AboutDialogCreditItem::description"

.PP
Definition at line 24 of file AboutDialog\&.h\&.
.SS "\fBint\fP AboutDialogCreditItem::role"

.PP
Definition at line 25 of file AboutDialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
