.TH "AButton" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AButton \- A wxButton with mouse-over behaviour\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AButton\&.h>\fP
.PP
Inherits wxWindow\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBListener\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAButtonState\fP { \fBAButtonUp\fP, \fBAButtonOver\fP, \fBAButtonDown\fP, \fBAButtonDis\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAButton\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos, \fBconst\fP wxSize &\fBsize\fP, \fBImageRoll\fP up, \fBImageRoll\fP over, \fBImageRoll\fP down, \fBImageRoll\fP dis, \fBbool\fP toggle)"
.br
.ti -1c
.RI "\fBAButton\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos, \fBconst\fP wxSize &\fBsize\fP, wxImage up, wxImage over, wxImage down, wxImage dis, \fBbool\fP toggle)"
.br
.ti -1c
.RI "virtual \fB~AButton\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBAcceptsFocus\fP () \fBconst\fP  override"
.br
.ti -1c
.RI "\fBbool\fP \fBAcceptsFocusFromKeyboard\fP () \fBconst\fP  override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetAlternateImages\fP (unsigned idx, \fBImageRoll\fP up, \fBImageRoll\fP over, \fBImageRoll\fP down, \fBImageRoll\fP dis)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetAlternateImages\fP (unsigned idx, wxImage up, wxImage over, wxImage down, wxImage dis)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetAlternateIdx\fP (unsigned idx)"
.br
.ti -1c
.RI "\fBvoid\fP \fBFollowModifierKeys\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetFocusRect\fP (wxRect &r)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsEnabled\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBDisable\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBEnable\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnabled\fP (\fBbool\fP state)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPushDown\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopUp\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnErase\fP (wxEraseEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPaint\fP (wxPaintEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSize\fP (wxSizeEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnMouseEvent\fP (wxMouseEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnCaptureLost\fP (wxMouseCaptureLostEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnKeyDown\fP (wxKeyEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSetFocus\fP (wxFocusEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnKillFocus\fP (wxFocusEvent &event)"
.br
.ti -1c
.RI "\fBbool\fP \fBWasShiftDown\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBWasControlDown\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsDown\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetButtonToggles\fP (\fBbool\fP toggler)"
.br
.ti -1c
.RI "\fBvoid\fP \fBToggle\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClick\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetShift\fP (\fBbool\fP shift)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetControl\fP (\fBbool\fP control)"
.br
.ti -1c
.RI "\fBAButtonState\fP \fBGetState\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUseDisabledAsDownHiliteImage\fP (\fBbool\fP flag)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAButtonAx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A wxButton with mouse-over behaviour\&. 

\fBAButton\fP is a custom button class for Audacity\&. The main feature it supports that a wxButton does not is mouseovers\&.
.PP
It uses an image for all of its states: up, over, down, and disabled, allowing any sort of customization you want\&. Currently it does not support transparency effects, so the image musts be rectangular and opaque\&. 
.PP
Definition at line 27 of file AButton\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAButton::AButtonState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAButtonUp \fP\fP
.TP
\fB\fIAButtonOver \fP\fP
.TP
\fB\fIAButtonDown \fP\fP
.TP
\fB\fIAButtonDis \fP\fP
.PP
Definition at line 118 of file AButton\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AButton::AButton (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos, \fBconst\fP wxSize & size, \fBImageRoll\fP up, \fBImageRoll\fP over, \fBImageRoll\fP down, \fBImageRoll\fP dis, \fBbool\fP toggle)"

.PP
Definition at line 172 of file AButton\&.cpp\&.
.SS "AButton::AButton (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos, \fBconst\fP wxSize & size, wxImage up, wxImage over, wxImage down, wxImage dis, \fBbool\fP toggle)"

.PP
Definition at line 155 of file AButton\&.cpp\&.
.SS "AButton::~AButton ()\fC [virtual]\fP"

.PP
Definition at line 188 of file AButton\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP AButton::AcceptsFocus () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 59 of file AButton\&.h\&.
.SS "\fBbool\fP AButton::AcceptsFocusFromKeyboard () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 60 of file AButton\&.h\&.
.SS "\fBvoid\fP AButton::Click ()"

.PP
Definition at line 545 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::Disable ()"

.PP
Definition at line 520 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::Enable ()"

.PP
Definition at line 513 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::FollowModifierKeys ()"

.PP
Definition at line 281 of file AButton\&.cpp\&.
.SS "\fBAButton::AButtonState\fP AButton::GetState ()"

.PP
Definition at line 293 of file AButton\&.cpp\&.
.SS "\fBbool\fP AButton::IsDown ()\fC [inline]\fP"

.PP
Definition at line 111 of file AButton\&.h\&.
.SS "\fBbool\fP AButton::IsEnabled () const\fC [inline]\fP"

.PP
Definition at line 88 of file AButton\&.h\&.
.SS "\fBvoid\fP AButton::OnCaptureLost (wxMouseCaptureLostEvent & event)"

.PP
Definition at line 455 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnErase (wxEraseEvent & event)"

.PP
Definition at line 352 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnKeyDown (wxKeyEvent & event)"

.PP
Definition at line 465 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnKillFocus (wxFocusEvent & event)"

.PP
Definition at line 497 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnMouseEvent (wxMouseEvent & event)"

.PP
Definition at line 379 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnPaint (wxPaintEvent & event)"

.PP
Definition at line 336 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnSetFocus (wxFocusEvent & event)"

.PP
Definition at line 491 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::OnSize (wxSizeEvent & event)"

.PP
Definition at line 357 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::PopUp ()"

.PP
Definition at line 535 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::PushDown ()"

.PP
Definition at line 529 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetAlternateIdx (unsigned idx)"

.PP
Definition at line 271 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetAlternateImages (unsigned idx, \fBImageRoll\fP up, \fBImageRoll\fP over, \fBImageRoll\fP down, \fBImageRoll\fP dis)"

.PP
Definition at line 257 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetAlternateImages (unsigned idx, wxImage up, wxImage over, wxImage down, wxImage dis)"

.PP
Definition at line 243 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetButtonToggles (\fBbool\fP toggler)\fC [inline]\fP"

.PP
Definition at line 112 of file AButton\&.h\&.
.SS "\fBvoid\fP AButton::SetControl (\fBbool\fP control)"

.PP
Definition at line 557 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetEnabled (\fBbool\fP state)\fC [inline]\fP"

.PP
Definition at line 91 of file AButton\&.h\&.
.SS "\fBvoid\fP AButton::SetFocusRect (wxRect & r)"

.PP
Definition at line 287 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::SetShift (\fBbool\fP shift)"

.PP
Definition at line 552 of file AButton\&.cpp\&.
.SS "\fBvoid\fP AButton::Toggle ()\fC [inline]\fP"

.PP
Definition at line 113 of file AButton\&.h\&.
.SS "\fBvoid\fP AButton::UseDisabledAsDownHiliteImage (\fBbool\fP flag)"

.PP
Definition at line 238 of file AButton\&.cpp\&.
.SS "\fBbool\fP AButton::WasControlDown ()"

.PP
Definition at line 508 of file AButton\&.cpp\&.
.SS "\fBbool\fP AButton::WasShiftDown ()"

.PP
Definition at line 503 of file AButton\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class AButtonAx\fC [friend]\fP"

.PP
Definition at line 28 of file AButton\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
