.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/src/vamp-sdk/acsymbols.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/src/vamp-sdk/acsymbols.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_5_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_4_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_3_1_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_3_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_2_1_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_2_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_1_present\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlibvampsdk_v_2_0_present\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP libvampsdk_v_2_0_present (\fBvoid\fP)"

.PP
Definition at line 11 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_1_present (\fBvoid\fP)"

.PP
Definition at line 10 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_2_1_present (\fBvoid\fP)"

.PP
Definition at line 8 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_2_present (\fBvoid\fP)"

.PP
Definition at line 9 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_3_1_present (\fBvoid\fP)"

.PP
Definition at line 6 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_3_present (\fBvoid\fP)"

.PP
Definition at line 7 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_4_present (\fBvoid\fP)"

.PP
Definition at line 5 of file acsymbols\&.c\&.
.SS "\fBvoid\fP libvampsdk_v_2_5_present (\fBvoid\fP)"

.PP
Definition at line 4 of file acsymbols\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
