.TH "add_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
add_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <add\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "\fBint\fP \fBterminate_bits\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlogical_stop_bits\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs1\fP"
.br
.ti -1c
.RI "long \fBs1_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_type\fP \fBs1_bptr\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs1_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs2\fP"
.br
.ti -1c
.RI "long \fBs2_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_type\fP \fBs2_bptr\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs2_ptr\fP"
.br
.ti -1c
.RI "struct \fBmultiseq_struct\fP * \fBmultiseq\fP"
.br
.ti -1c
.RI "long \fBs1_prepend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file add\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP add_susp_struct::logical_stop_bits"

.PP
Definition at line 8 of file add\&.h\&.
.SS "\fBboolean\fP add_susp_struct::logically_stopped"

.PP
Definition at line 9 of file add\&.h\&.
.SS "struct \fBmultiseq_struct\fP* add_susp_struct::multiseq"

.PP
Definition at line 29 of file add\&.h\&.
.SS "\fBsound_type\fP add_susp_struct::s1"

.PP
Definition at line 10 of file add\&.h\&.
.SS "\fBsample_block_type\fP add_susp_struct::s1_bptr"

.PP
Definition at line 12 of file add\&.h\&.
.SS "long add_susp_struct::s1_cnt"

.PP
Definition at line 11 of file add\&.h\&.
.SS "long add_susp_struct::s1_prepend"

.PP
Definition at line 30 of file add\&.h\&.
.SS "\fBsample_block_values_type\fP add_susp_struct::s1_ptr"

.PP
Definition at line 13 of file add\&.h\&.
.SS "\fBsound_type\fP add_susp_struct::s2"

.PP
Definition at line 14 of file add\&.h\&.
.SS "\fBsample_block_type\fP add_susp_struct::s2_bptr"

.PP
Definition at line 16 of file add\&.h\&.
.SS "long add_susp_struct::s2_cnt"

.PP
Definition at line 15 of file add\&.h\&.
.SS "\fBsample_block_values_type\fP add_susp_struct::s2_ptr"

.PP
Definition at line 17 of file add\&.h\&.
.SS "\fBboolean\fP add_susp_struct::started"

.PP
Definition at line 5 of file add\&.h\&.
.SS "\fBsnd_susp_node\fP add_susp_struct::susp"

.PP
Definition at line 4 of file add\&.h\&.
.SS "\fBint\fP add_susp_struct::terminate_bits"

.PP
Definition at line 6 of file add\&.h\&.
.SS "long add_susp_struct::terminate_cnt"

.PP
Definition at line 7 of file add\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
