.TH "AdornedRulerPanel" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdornedRulerPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ruler\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdornedRulerPanel\fP (\fBAudacityProject\fP *parent, wxWindowID id, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize, \fBViewInfo\fP *viewinfo=\fBNULL\fP)"
.br
.ti -1c
.RI "\fB~AdornedRulerPanel\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBAcceptsFocus\fP () \fBconst\fP  override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetLeftOffset\fP (\fBint\fP \fBoffset\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDrawCursor\fP (double time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDrawIndicator\fP (double time, \fBbool\fP rec)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDrawSelection\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearIndicator\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPlayRegion\fP (double playRegionStart, double playRegionEnd)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearPlayRegion\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBGetPlayRegion\fP (double *playRegionStart, double *playRegionEnd)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetProject\fP (\fBAudacityProject\fP *project)"
.br
.ti -1c
.RI "\fBvoid\fP \fBGetMaxSize\fP (wxCoord *width, wxCoord *height)"
.br
.ti -1c
.RI "\fBvoid\fP \fBInvalidateRuler\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdatePrefs\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRegenerateTooltips\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBint\fP \fBGetRulerHeight\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 277 of file Ruler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdornedRulerPanel::AdornedRulerPanel (\fBAudacityProject\fP * parent, wxWindowID id, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP, \fBViewInfo\fP * viewinfo = \fC\fBNULL\fP\fP)"

.PP
Definition at line 1677 of file Ruler\&.cpp\&.
.SS "AdornedRulerPanel::~AdornedRulerPanel ()"

.PP
Definition at line 1750 of file Ruler\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP AdornedRulerPanel::AcceptsFocus () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 288 of file Ruler\&.h\&.
.SS "\fBvoid\fP AdornedRulerPanel::ClearIndicator ()"

.PP
Definition at line 2488 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::ClearPlayRegion ()"

.PP
Definition at line 2585 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::DrawCursor (double time)"

.PP
Definition at line 2469 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::DrawIndicator (double time, \fBbool\fP rec)"

.PP
Definition at line 2495 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::DrawSelection ()"

.PP
Definition at line 2441 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::GetMaxSize (wxCoord * width, wxCoord * height)"

.PP
Definition at line 2613 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::GetPlayRegion (double * playRegionStart, double * playRegionEnd)"

.PP
Definition at line 2597 of file Ruler\&.cpp\&.
.SS "static \fBint\fP AdornedRulerPanel::GetRulerHeight ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 291 of file Ruler\&.h\&.
.SS "\fBvoid\fP AdornedRulerPanel::InvalidateRuler ()"

.PP
Definition at line 1783 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::RegenerateTooltips ()"

.PP
Definition at line 1788 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::SetLeftOffset (\fBint\fP offset)"

.PP
Definition at line 2463 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::SetPlayRegion (double playRegionStart, double playRegionEnd)"

.PP
Definition at line 2570 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP AdornedRulerPanel::SetProject (\fBAudacityProject\fP * project)\fC [inline]\fP"

.PP
Definition at line 303 of file Ruler\&.h\&.
.SS "\fBvoid\fP AdornedRulerPanel::UpdatePrefs ()"

.PP
Definition at line 1769 of file Ruler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
