.TH "AEventList" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEventList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AEEventClass \fBevclass\fP"
.br
.ti -1c
.RI "AEEventID \fBevid\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBhandler\fP"
.br
.ti -1c
.RI "long \fBrefcon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file macint\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "AEEventClass AEventList::evclass"

.PP
Definition at line 37 of file macint\&.c\&.
.SS "AEEventID AEventList::evid"

.PP
Definition at line 38 of file macint\&.c\&.
.SS "\fBvoid\fP* AEventList::handler"

.PP
Definition at line 39 of file macint\&.c\&.
.SS "long AEventList::refcon"

.PP
Definition at line 40 of file macint\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
