.TH "Alg_atoms" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alg_atoms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allegro\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlg_atoms\fP ()"
.br
.ti -1c
.RI "virtual \fB~Alg_atoms\fP ()"
.br
.ti -1c
.RI "\fBAlg_attribute\fP \fBinsert_attribute\fP (\fBAlg_attribute\fP attr)"
.br
.ti -1c
.RI "\fBAlg_attribute\fP \fBinsert_string\fP (\fBconst\fP char *\fBname\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file allegro\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alg_atoms::Alg_atoms ()\fC [inline]\fP"

.PP
Definition at line 78 of file allegro\&.h\&.
.SS "virtual Alg_atoms::~Alg_atoms ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 89 of file allegro\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAlg_attribute\fP Alg_atoms::insert_attribute (\fBAlg_attribute\fP attr)"

.PP
Definition at line 87 of file allegro\&.cpp\&.
.SS "\fBAlg_attribute\fP Alg_atoms::insert_string (\fBconst\fP char * name)"

.PP
Definition at line 99 of file allegro\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
