.TH "Alg_pending_event" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alg_pending_event \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allegro\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBcookie\fP"
.br
.ti -1c
.RI "\fBAlg_events\fP * \fBevents\fP"
.br
.ti -1c
.RI "long \fBindex\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnote_on\fP"
.br
.ti -1c
.RI "double \fBoffset\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 922 of file allegro\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* Alg_pending_event::cookie"

.PP
Definition at line 923 of file allegro\&.h\&.
.SS "\fBAlg_events\fP* Alg_pending_event::events"

.PP
Definition at line 924 of file allegro\&.h\&.
.SS "long Alg_pending_event::index"

.PP
Definition at line 925 of file allegro\&.h\&.
.SS "\fBbool\fP Alg_pending_event::note_on"

.PP
Definition at line 926 of file allegro\&.h\&.
.SS "double Alg_pending_event::offset"

.PP
Definition at line 927 of file allegro\&.h\&.
.SS "double Alg_pending_event::time"

.PP
Definition at line 928 of file allegro\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
