.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/allegrosmfrd.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/allegrosmfrd.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'assert\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'allegro\&.h'\fP
.br
\fC#include 'algsmfrd_internal\&.h'\fP
.br
\fC#include 'mfmidi\&.h'\fP
.br
\fC#include 'trace\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlg_note_list\fP"
.br
.ti -1c
.RI "class \fBAlg_midifile_reader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBAlg_note_list\fP * \fBAlg_note_list_ptr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBheapify2\fP (\fBint\fP \fBlen\fP, unsigned char *\fBs\fP)"
.br
.ti -1c
.RI "\fBAlg_error\fP \fBalg_smf_read\fP (istream &file, \fBAlg_seq_ptr\fP new_seq)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBAlg_note_list\fP * \fBAlg_note_list_ptr\fP"

.SH "Function Documentation"
.PP 
.SS "\fBAlg_error\fP alg_smf_read (istream & file, \fBAlg_seq_ptr\fP new_seq)"

.PP
Definition at line 447 of file allegrosmfrd\&.cpp\&.
.SS "char* heapify2 (\fBint\fP len, unsigned char * s)"

.PP
Definition at line 419 of file allegrosmfrd\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
