.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/grabbag/alloc.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/grabbag/alloc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'share/alloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBsafe_malloc_mul_2op_\fP (size_t size1, size_t size2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP* safe_malloc_mul_2op_ (size_t size1, size_t size2)"

.PP
Definition at line 41 of file alloc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
