.TH "allpoles_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
allpoles_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBx_snd\fP"
.br
.ti -1c
.RI "long \fBx_snd_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBx_snd_ptr\fP"
.br
.ti -1c
.RI "long \fBak_len\fP"
.br
.ti -1c
.RI "\fBLVAL\fP \fBak_array\fP"
.br
.ti -1c
.RI "double \fBgain\fP"
.br
.ti -1c
.RI "double * \fBak_coefs\fP"
.br
.ti -1c
.RI "double * \fBzk_buf\fP"
.br
.ti -1c
.RI "long \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file allpoles\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLVAL\fP allpoles_susp_struct::ak_array"

.PP
Definition at line 24 of file allpoles\&.c\&.
.SS "double* allpoles_susp_struct::ak_coefs"

.PP
Definition at line 26 of file allpoles\&.c\&.
.SS "long allpoles_susp_struct::ak_len"

.PP
Definition at line 23 of file allpoles\&.c\&.
.SS "double allpoles_susp_struct::gain"

.PP
Definition at line 25 of file allpoles\&.c\&.
.SS "long allpoles_susp_struct::index"

.PP
Definition at line 28 of file allpoles\&.c\&.
.SS "\fBboolean\fP allpoles_susp_struct::logically_stopped"

.PP
Definition at line 18 of file allpoles\&.c\&.
.SS "\fBsnd_susp_node\fP allpoles_susp_struct::susp"

.PP
Definition at line 16 of file allpoles\&.c\&.
.SS "long allpoles_susp_struct::terminate_cnt"

.PP
Definition at line 17 of file allpoles\&.c\&.
.SS "\fBsound_type\fP allpoles_susp_struct::x_snd"

.PP
Definition at line 19 of file allpoles\&.c\&.
.SS "long allpoles_susp_struct::x_snd_cnt"

.PP
Definition at line 20 of file allpoles\&.c\&.
.SS "\fBsample_block_values_type\fP allpoles_susp_struct::x_snd_ptr"

.PP
Definition at line 21 of file allpoles\&.c\&.
.SS "double* allpoles_susp_struct::zk_buf"

.PP
Definition at line 27 of file allpoles\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
