.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/amosc.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/amosc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_amosc\fP (\fBsound_type\fP input, double step, \fBrate_type\fP sr, double hz, \fBtime_type\fP t0, \fBsound_type\fP amod, double phase)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_amosc\fP (\fBsound_type\fP input, double step, \fBrate_type\fP sr, double hz, \fBtime_type\fP t0, \fBsound_type\fP amod, double phase)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_amosc (\fBsound_type\fP input, double step, \fBrate_type\fP sr, double hz, \fBtime_type\fP t0, \fBsound_type\fP amod, double phase)"

.PP
Definition at line 512 of file amosc\&.c\&.
.SS "\fBsound_type\fP snd_make_amosc (\fBsound_type\fP input, double step, \fBrate_type\fP sr, double hz, \fBtime_type\fP t0, \fBsound_type\fP amod, double phase)"

.PP
Definition at line 447 of file amosc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
