.TH "Amp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Amp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP float * \fBgain\fP"
.br
.ti -1c
.RI "\fBconst\fP float * \fBinput\fP"
.br
.ti -1c
.RI "float * \fBoutput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Every plugin defines a private structure for the plugin instance\&. All data associated with a plugin instance is stored here, and is available to every instance method\&. In this simple plugin, only port buffers need to be stored, since there is no additional instance data\&. 
.PP
Definition at line 56 of file amp\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP float* Amp::gain"

.PP
Definition at line 58 of file amp\&.c\&.
.SS "\fBconst\fP float* Amp::input"

.PP
Definition at line 59 of file amp\&.c\&.
.SS "float* Amp::output"

.PP
Definition at line 60 of file amp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
