.TH "AndValidator" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AndValidator \- Parameter must pass both of the supplied validators\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Validators\&.h>\fP
.SH "Detailed Description"
.PP 
Parameter must pass both of the supplied validators\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
