.TH "C:/_dev/OpenU/Audacity/audacity/win/wxWidgets_additions/wxWidgets-3.0.2/interface/wx/app.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/win/wxWidgets_additions/wxWidgets-3.0.2/interface/wx/app.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwxAppConsole\fP"
.br
.ti -1c
.RI "class \fBwxApp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBwxDECLARE_APP\fP(className)"
.br
.ti -1c
.RI "#define \fBwxIMPLEMENT_APP\fP(className)"
.br
.ti -1c
.RI "#define \fBwxDISABLE_DEBUG_SUPPORT\fP()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxAppDerivedClass & \fBwxGetApp\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBwxHandleFatalExceptions\fP (\fBbool\fP doIt=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBwxInitialize\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBwxUninitialize\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBwxWakeUpIdle\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBwxYield\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBwxSafeYield\fP (wxWindow *win=\fBNULL\fP, \fBbool\fP onlyIfNeeded=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBwxEntry\fP (\fBint\fP &\fBargc\fP, wxChar **\fBargv\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBwxEntry\fP (HINSTANCE hInstance, HINSTANCE hPrevInstance=\fBNULL\fP, char *pCmdLine=\fBNULL\fP, \fBint\fP nCmdShow=\fBSW_SHOWNORMAL\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwxExit\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBwxApp\fP * \fBwxTheApp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBwxApp\fP* wxTheApp"
The global pointer to the singleton \fBwxApp\fP object\&.
.PP
\fBSee also:\fP
.RS 4
\fBwxApp::GetInstance()\fP 
.RE
.PP

.PP
Definition at line 961 of file app\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
