.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/aresoncv.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/aresoncv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_aresoncv\fP (\fBsound_type\fP s1, double hz, \fBsound_type\fP bw, \fBint\fP normalization)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_aresoncv\fP (\fBsound_type\fP s1, double hz, \fBsound_type\fP bw, \fBint\fP normalization)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_aresoncv (\fBsound_type\fP s1, double hz, \fBsound_type\fP bw, \fBint\fP normalization)"

.PP
Definition at line 609 of file aresoncv\&.c\&.
.SS "\fBsound_type\fP snd_make_aresoncv (\fBsound_type\fP s1, double hz, \fBsound_type\fP bw, \fBint\fP normalization)"

.PP
Definition at line 531 of file aresoncv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
