.TH "Argument_DataFormat" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argument_DataFormat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBis_binary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__bool\fP Argument_DataFormat::is_binary"

.PP
Definition at line 131 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
