.TH "Argument_ExportPictureTo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argument_ExportPictureTo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBArgument_BlockNumber\fP * \fBblock_number_link\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 147 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBArgument_BlockNumber\fP* Argument_ExportPictureTo::block_number_link"

.PP
Definition at line 149 of file options\&.h\&.
.SS "char* Argument_ExportPictureTo::filename"

.PP
Definition at line 148 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
