.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/expat/lib/ascii.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/expat/lib/ascii.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBASCII_A\fP   0x41"
.br
.ti -1c
.RI "#define \fBASCII_B\fP   0x42"
.br
.ti -1c
.RI "#define \fBASCII_C\fP   0x43"
.br
.ti -1c
.RI "#define \fBASCII_D\fP   0x44"
.br
.ti -1c
.RI "#define \fBASCII_E\fP   0x45"
.br
.ti -1c
.RI "#define \fBASCII_F\fP   0x46"
.br
.ti -1c
.RI "#define \fBASCII_G\fP   0x47"
.br
.ti -1c
.RI "#define \fBASCII_H\fP   0x48"
.br
.ti -1c
.RI "#define \fBASCII_I\fP   0x49"
.br
.ti -1c
.RI "#define \fBASCII_J\fP   0x4A"
.br
.ti -1c
.RI "#define \fBASCII_K\fP   0x4B"
.br
.ti -1c
.RI "#define \fBASCII_L\fP   0x4C"
.br
.ti -1c
.RI "#define \fBASCII_M\fP   0x4D"
.br
.ti -1c
.RI "#define \fBASCII_N\fP   0x4E"
.br
.ti -1c
.RI "#define \fBASCII_O\fP   0x4F"
.br
.ti -1c
.RI "#define \fBASCII_P\fP   0x50"
.br
.ti -1c
.RI "#define \fBASCII_Q\fP   0x51"
.br
.ti -1c
.RI "#define \fBASCII_R\fP   0x52"
.br
.ti -1c
.RI "#define \fBASCII_S\fP   0x53"
.br
.ti -1c
.RI "#define \fBASCII_T\fP   0x54"
.br
.ti -1c
.RI "#define \fBASCII_U\fP   0x55"
.br
.ti -1c
.RI "#define \fBASCII_V\fP   0x56"
.br
.ti -1c
.RI "#define \fBASCII_W\fP   0x57"
.br
.ti -1c
.RI "#define \fBASCII_X\fP   0x58"
.br
.ti -1c
.RI "#define \fBASCII_Y\fP   0x59"
.br
.ti -1c
.RI "#define \fBASCII_Z\fP   0x5A"
.br
.ti -1c
.RI "#define \fBASCII_a\fP   0x61"
.br
.ti -1c
.RI "#define \fBASCII_b\fP   0x62"
.br
.ti -1c
.RI "#define \fBASCII_c\fP   0x63"
.br
.ti -1c
.RI "#define \fBASCII_d\fP   0x64"
.br
.ti -1c
.RI "#define \fBASCII_e\fP   0x65"
.br
.ti -1c
.RI "#define \fBASCII_f\fP   0x66"
.br
.ti -1c
.RI "#define \fBASCII_g\fP   0x67"
.br
.ti -1c
.RI "#define \fBASCII_h\fP   0x68"
.br
.ti -1c
.RI "#define \fBASCII_i\fP   0x69"
.br
.ti -1c
.RI "#define \fBASCII_j\fP   0x6A"
.br
.ti -1c
.RI "#define \fBASCII_k\fP   0x6B"
.br
.ti -1c
.RI "#define \fBASCII_l\fP   0x6C"
.br
.ti -1c
.RI "#define \fBASCII_m\fP   0x6D"
.br
.ti -1c
.RI "#define \fBASCII_n\fP   0x6E"
.br
.ti -1c
.RI "#define \fBASCII_o\fP   0x6F"
.br
.ti -1c
.RI "#define \fBASCII_p\fP   0x70"
.br
.ti -1c
.RI "#define \fBASCII_q\fP   0x71"
.br
.ti -1c
.RI "#define \fBASCII_r\fP   0x72"
.br
.ti -1c
.RI "#define \fBASCII_s\fP   0x73"
.br
.ti -1c
.RI "#define \fBASCII_t\fP   0x74"
.br
.ti -1c
.RI "#define \fBASCII_u\fP   0x75"
.br
.ti -1c
.RI "#define \fBASCII_v\fP   0x76"
.br
.ti -1c
.RI "#define \fBASCII_w\fP   0x77"
.br
.ti -1c
.RI "#define \fBASCII_x\fP   0x78"
.br
.ti -1c
.RI "#define \fBASCII_y\fP   0x79"
.br
.ti -1c
.RI "#define \fBASCII_z\fP   0x7A"
.br
.ti -1c
.RI "#define \fBASCII_0\fP   0x30"
.br
.ti -1c
.RI "#define \fBASCII_1\fP   0x31"
.br
.ti -1c
.RI "#define \fBASCII_2\fP   0x32"
.br
.ti -1c
.RI "#define \fBASCII_3\fP   0x33"
.br
.ti -1c
.RI "#define \fBASCII_4\fP   0x34"
.br
.ti -1c
.RI "#define \fBASCII_5\fP   0x35"
.br
.ti -1c
.RI "#define \fBASCII_6\fP   0x36"
.br
.ti -1c
.RI "#define \fBASCII_7\fP   0x37"
.br
.ti -1c
.RI "#define \fBASCII_8\fP   0x38"
.br
.ti -1c
.RI "#define \fBASCII_9\fP   0x39"
.br
.ti -1c
.RI "#define \fBASCII_TAB\fP   0x09"
.br
.ti -1c
.RI "#define \fBASCII_SPACE\fP   0x20"
.br
.ti -1c
.RI "#define \fBASCII_EXCL\fP   0x21"
.br
.ti -1c
.RI "#define \fBASCII_QUOT\fP   0x22"
.br
.ti -1c
.RI "#define \fBASCII_AMP\fP   0x26"
.br
.ti -1c
.RI "#define \fBASCII_APOS\fP   0x27"
.br
.ti -1c
.RI "#define \fBASCII_MINUS\fP   0x2D"
.br
.ti -1c
.RI "#define \fBASCII_PERIOD\fP   0x2E"
.br
.ti -1c
.RI "#define \fBASCII_COLON\fP   0x3A"
.br
.ti -1c
.RI "#define \fBASCII_SEMI\fP   0x3B"
.br
.ti -1c
.RI "#define \fBASCII_LT\fP   0x3C"
.br
.ti -1c
.RI "#define \fBASCII_EQUALS\fP   0x3D"
.br
.ti -1c
.RI "#define \fBASCII_GT\fP   0x3E"
.br
.ti -1c
.RI "#define \fBASCII_LSQB\fP   0x5B"
.br
.ti -1c
.RI "#define \fBASCII_RSQB\fP   0x5D"
.br
.ti -1c
.RI "#define \fBASCII_UNDERSCORE\fP   0x5F"
.br
.ti -1c
.RI "#define \fBASCII_LPAREN\fP   0x28"
.br
.ti -1c
.RI "#define \fBASCII_RPAREN\fP   0x29"
.br
.ti -1c
.RI "#define \fBASCII_FF\fP   0x0C"
.br
.ti -1c
.RI "#define \fBASCII_SLASH\fP   0x2F"
.br
.ti -1c
.RI "#define \fBASCII_HASH\fP   0x23"
.br
.ti -1c
.RI "#define \fBASCII_PIPE\fP   0x7C"
.br
.ti -1c
.RI "#define \fBASCII_COMMA\fP   0x2C"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASCII_0   0x30"

.PP
Definition at line 59 of file ascii\&.h\&.
.SS "#define ASCII_1   0x31"

.PP
Definition at line 60 of file ascii\&.h\&.
.SS "#define ASCII_2   0x32"

.PP
Definition at line 61 of file ascii\&.h\&.
.SS "#define ASCII_3   0x33"

.PP
Definition at line 62 of file ascii\&.h\&.
.SS "#define ASCII_4   0x34"

.PP
Definition at line 63 of file ascii\&.h\&.
.SS "#define ASCII_5   0x35"

.PP
Definition at line 64 of file ascii\&.h\&.
.SS "#define ASCII_6   0x36"

.PP
Definition at line 65 of file ascii\&.h\&.
.SS "#define ASCII_7   0x37"

.PP
Definition at line 66 of file ascii\&.h\&.
.SS "#define ASCII_8   0x38"

.PP
Definition at line 67 of file ascii\&.h\&.
.SS "#define ASCII_9   0x39"

.PP
Definition at line 68 of file ascii\&.h\&.
.SS "#define ASCII_A   0x41"

.PP
Definition at line 5 of file ascii\&.h\&.
.SS "#define ASCII_a   0x61"

.PP
Definition at line 32 of file ascii\&.h\&.
.SS "#define ASCII_AMP   0x26"

.PP
Definition at line 74 of file ascii\&.h\&.
.SS "#define ASCII_APOS   0x27"

.PP
Definition at line 75 of file ascii\&.h\&.
.SS "#define ASCII_B   0x42"

.PP
Definition at line 6 of file ascii\&.h\&.
.SS "#define ASCII_b   0x62"

.PP
Definition at line 33 of file ascii\&.h\&.
.SS "#define ASCII_C   0x43"

.PP
Definition at line 7 of file ascii\&.h\&.
.SS "#define ASCII_c   0x63"

.PP
Definition at line 34 of file ascii\&.h\&.
.SS "#define ASCII_COLON   0x3A"

.PP
Definition at line 78 of file ascii\&.h\&.
.SS "#define ASCII_COMMA   0x2C"

.PP
Definition at line 92 of file ascii\&.h\&.
.SS "#define ASCII_D   0x44"

.PP
Definition at line 8 of file ascii\&.h\&.
.SS "#define ASCII_d   0x64"

.PP
Definition at line 35 of file ascii\&.h\&.
.SS "#define ASCII_E   0x45"

.PP
Definition at line 9 of file ascii\&.h\&.
.SS "#define ASCII_e   0x65"

.PP
Definition at line 36 of file ascii\&.h\&.
.SS "#define ASCII_EQUALS   0x3D"

.PP
Definition at line 81 of file ascii\&.h\&.
.SS "#define ASCII_EXCL   0x21"

.PP
Definition at line 72 of file ascii\&.h\&.
.SS "#define ASCII_F   0x46"

.PP
Definition at line 10 of file ascii\&.h\&.
.SS "#define ASCII_f   0x66"

.PP
Definition at line 37 of file ascii\&.h\&.
.SS "#define ASCII_FF   0x0C"

.PP
Definition at line 88 of file ascii\&.h\&.
.SS "#define ASCII_G   0x47"

.PP
Definition at line 11 of file ascii\&.h\&.
.SS "#define ASCII_g   0x67"

.PP
Definition at line 38 of file ascii\&.h\&.
.SS "#define ASCII_GT   0x3E"

.PP
Definition at line 82 of file ascii\&.h\&.
.SS "#define ASCII_H   0x48"

.PP
Definition at line 12 of file ascii\&.h\&.
.SS "#define ASCII_h   0x68"

.PP
Definition at line 39 of file ascii\&.h\&.
.SS "#define ASCII_HASH   0x23"

.PP
Definition at line 90 of file ascii\&.h\&.
.SS "#define ASCII_I   0x49"

.PP
Definition at line 13 of file ascii\&.h\&.
.SS "#define ASCII_i   0x69"

.PP
Definition at line 40 of file ascii\&.h\&.
.SS "#define ASCII_J   0x4A"

.PP
Definition at line 14 of file ascii\&.h\&.
.SS "#define ASCII_j   0x6A"

.PP
Definition at line 41 of file ascii\&.h\&.
.SS "#define ASCII_K   0x4B"

.PP
Definition at line 15 of file ascii\&.h\&.
.SS "#define ASCII_k   0x6B"

.PP
Definition at line 42 of file ascii\&.h\&.
.SS "#define ASCII_L   0x4C"

.PP
Definition at line 16 of file ascii\&.h\&.
.SS "#define ASCII_l   0x6C"

.PP
Definition at line 43 of file ascii\&.h\&.
.SS "#define ASCII_LPAREN   0x28"

.PP
Definition at line 86 of file ascii\&.h\&.
.SS "#define ASCII_LSQB   0x5B"

.PP
Definition at line 83 of file ascii\&.h\&.
.SS "#define ASCII_LT   0x3C"

.PP
Definition at line 80 of file ascii\&.h\&.
.SS "#define ASCII_M   0x4D"

.PP
Definition at line 17 of file ascii\&.h\&.
.SS "#define ASCII_m   0x6D"

.PP
Definition at line 44 of file ascii\&.h\&.
.SS "#define ASCII_MINUS   0x2D"

.PP
Definition at line 76 of file ascii\&.h\&.
.SS "#define ASCII_N   0x4E"

.PP
Definition at line 18 of file ascii\&.h\&.
.SS "#define ASCII_n   0x6E"

.PP
Definition at line 45 of file ascii\&.h\&.
.SS "#define ASCII_O   0x4F"

.PP
Definition at line 19 of file ascii\&.h\&.
.SS "#define ASCII_o   0x6F"

.PP
Definition at line 46 of file ascii\&.h\&.
.SS "#define ASCII_P   0x50"

.PP
Definition at line 20 of file ascii\&.h\&.
.SS "#define ASCII_p   0x70"

.PP
Definition at line 47 of file ascii\&.h\&.
.SS "#define ASCII_PERIOD   0x2E"

.PP
Definition at line 77 of file ascii\&.h\&.
.SS "#define ASCII_PIPE   0x7C"

.PP
Definition at line 91 of file ascii\&.h\&.
.SS "#define ASCII_Q   0x51"

.PP
Definition at line 21 of file ascii\&.h\&.
.SS "#define ASCII_q   0x71"

.PP
Definition at line 48 of file ascii\&.h\&.
.SS "#define ASCII_QUOT   0x22"

.PP
Definition at line 73 of file ascii\&.h\&.
.SS "#define ASCII_R   0x52"

.PP
Definition at line 22 of file ascii\&.h\&.
.SS "#define ASCII_r   0x72"

.PP
Definition at line 49 of file ascii\&.h\&.
.SS "#define ASCII_RPAREN   0x29"

.PP
Definition at line 87 of file ascii\&.h\&.
.SS "#define ASCII_RSQB   0x5D"

.PP
Definition at line 84 of file ascii\&.h\&.
.SS "#define ASCII_S   0x53"

.PP
Definition at line 23 of file ascii\&.h\&.
.SS "#define ASCII_s   0x73"

.PP
Definition at line 50 of file ascii\&.h\&.
.SS "#define ASCII_SEMI   0x3B"

.PP
Definition at line 79 of file ascii\&.h\&.
.SS "#define ASCII_SLASH   0x2F"

.PP
Definition at line 89 of file ascii\&.h\&.
.SS "#define ASCII_SPACE   0x20"

.PP
Definition at line 71 of file ascii\&.h\&.
.SS "#define ASCII_T   0x54"

.PP
Definition at line 24 of file ascii\&.h\&.
.SS "#define ASCII_t   0x74"

.PP
Definition at line 51 of file ascii\&.h\&.
.SS "#define ASCII_TAB   0x09"

.PP
Definition at line 70 of file ascii\&.h\&.
.SS "#define ASCII_U   0x55"

.PP
Definition at line 25 of file ascii\&.h\&.
.SS "#define ASCII_u   0x75"

.PP
Definition at line 52 of file ascii\&.h\&.
.SS "#define ASCII_UNDERSCORE   0x5F"

.PP
Definition at line 85 of file ascii\&.h\&.
.SS "#define ASCII_V   0x56"

.PP
Definition at line 26 of file ascii\&.h\&.
.SS "#define ASCII_v   0x76"

.PP
Definition at line 53 of file ascii\&.h\&.
.SS "#define ASCII_W   0x57"

.PP
Definition at line 27 of file ascii\&.h\&.
.SS "#define ASCII_w   0x77"

.PP
Definition at line 54 of file ascii\&.h\&.
.SS "#define ASCII_X   0x58"

.PP
Definition at line 28 of file ascii\&.h\&.
.SS "#define ASCII_x   0x78"

.PP
Definition at line 55 of file ascii\&.h\&.
.SS "#define ASCII_Y   0x59"

.PP
Definition at line 29 of file ascii\&.h\&.
.SS "#define ASCII_y   0x79"

.PP
Definition at line 56 of file ascii\&.h\&.
.SS "#define ASCII_Z   0x5A"

.PP
Definition at line 30 of file ascii\&.h\&.
.SS "#define ASCII_z   0x7A"

.PP
Definition at line 57 of file ascii\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
