.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/atom/atom.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/atom/atom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLV2_Atom\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Int\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Long\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Float\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Double\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_URID\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_String\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Literal_Body\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Literal\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Tuple\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Vector_Body\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Vector\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Property_Body\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Property\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Object_Body\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Object\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Event\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Sequence_Body\fP"
.br
.ti -1c
.RI "struct \fBLV2_Atom_Sequence\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV2_ATOM_URI\fP   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/atom'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_PREFIX\fP   \fBLV2_ATOM_URI\fP '#'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Atom\fP   \fBLV2_ATOM_PREFIX\fP 'Atom'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__AtomPort\fP   \fBLV2_ATOM_PREFIX\fP 'AtomPort'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Blank\fP   \fBLV2_ATOM_PREFIX\fP 'Blank'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Bool\fP   \fBLV2_ATOM_PREFIX\fP 'Bool'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Chunk\fP   \fBLV2_ATOM_PREFIX\fP 'Chunk'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Double\fP   \fBLV2_ATOM_PREFIX\fP 'Double'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Event\fP   \fBLV2_ATOM_PREFIX\fP 'Event'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Float\fP   \fBLV2_ATOM_PREFIX\fP 'Float'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Int\fP   \fBLV2_ATOM_PREFIX\fP 'Int'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Literal\fP   \fBLV2_ATOM_PREFIX\fP 'Literal'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Long\fP   \fBLV2_ATOM_PREFIX\fP 'Long'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Number\fP   \fBLV2_ATOM_PREFIX\fP 'Number'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Object\fP   \fBLV2_ATOM_PREFIX\fP 'Object'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Path\fP   \fBLV2_ATOM_PREFIX\fP 'Path'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Property\fP   \fBLV2_ATOM_PREFIX\fP 'Property'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Resource\fP   \fBLV2_ATOM_PREFIX\fP 'Resource'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Sequence\fP   \fBLV2_ATOM_PREFIX\fP 'Sequence'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Sound\fP   \fBLV2_ATOM_PREFIX\fP 'Sound'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__String\fP   \fBLV2_ATOM_PREFIX\fP 'String'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Tuple\fP   \fBLV2_ATOM_PREFIX\fP 'Tuple'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__URI\fP   \fBLV2_ATOM_PREFIX\fP 'URI'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__URID\fP   \fBLV2_ATOM_PREFIX\fP 'URID'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__Vector\fP   \fBLV2_ATOM_PREFIX\fP 'Vector'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__atomTransfer\fP   \fBLV2_ATOM_PREFIX\fP 'atomTransfer'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__beatTime\fP   \fBLV2_ATOM_PREFIX\fP 'beatTime'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__bufferType\fP   \fBLV2_ATOM_PREFIX\fP 'bufferType'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__childType\fP   \fBLV2_ATOM_PREFIX\fP 'childType'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__eventTransfer\fP   \fBLV2_ATOM_PREFIX\fP 'eventTransfer'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__frameTime\fP   \fBLV2_ATOM_PREFIX\fP 'frameTime'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__supports\fP   \fBLV2_ATOM_PREFIX\fP 'supports'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM__timeUnit\fP   \fBLV2_ATOM_PREFIX\fP 'timeUnit'"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_REFERENCE_TYPE\fP   0"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_CONTENTS\fP(type,  atom)   ((\fBvoid\fP*)((\fBuint8_t\fP*)(atom) + sizeof(type)))"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_CONTENTS_CONST\fP(type,  atom)   ((\fBconst\fP \fBvoid\fP*)((\fBconst\fP \fBuint8_t\fP*)(atom) + sizeof(type)))"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_BODY\fP(atom)   \fBLV2_ATOM_CONTENTS\fP(\fBLV2_Atom\fP, atom)"
.br
.ti -1c
.RI "#define \fBLV2_ATOM_BODY_CONST\fP(atom)   \fBLV2_ATOM_CONTENTS_CONST\fP(\fBLV2_Atom\fP, atom)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBlv2_atom_assert_double_fits_in_64_bits\fP[((sizeof(double)<=sizeof(\fBuint64_t\fP))*2)\-1]"
.br
.ti -1c
.RI "typedef \fBLV2_Atom_Int\fP \fBLV2_Atom_Bool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
C header for the LV2 Atom extension http://lv2plug.in/ns/ext/atom\&. 
.PP
Definition in file \fBatom\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV2_ATOM__Atom   \fBLV2_ATOM_PREFIX\fP 'Atom'"

.PP
Definition at line 31 of file atom\&.h\&.
.SS "#define LV2_ATOM__AtomPort   \fBLV2_ATOM_PREFIX\fP 'AtomPort'"

.PP
Definition at line 32 of file atom\&.h\&.
.SS "#define LV2_ATOM__atomTransfer   \fBLV2_ATOM_PREFIX\fP 'atomTransfer'"

.PP
Definition at line 54 of file atom\&.h\&.
.SS "#define LV2_ATOM__beatTime   \fBLV2_ATOM_PREFIX\fP 'beatTime'"

.PP
Definition at line 55 of file atom\&.h\&.
.SS "#define LV2_ATOM__Blank   \fBLV2_ATOM_PREFIX\fP 'Blank'"

.PP
Definition at line 33 of file atom\&.h\&.
.SS "#define LV2_ATOM__Bool   \fBLV2_ATOM_PREFIX\fP 'Bool'"

.PP
Definition at line 34 of file atom\&.h\&.
.SS "#define LV2_ATOM__bufferType   \fBLV2_ATOM_PREFIX\fP 'bufferType'"

.PP
Definition at line 56 of file atom\&.h\&.
.SS "#define LV2_ATOM__childType   \fBLV2_ATOM_PREFIX\fP 'childType'"

.PP
Definition at line 57 of file atom\&.h\&.
.SS "#define LV2_ATOM__Chunk   \fBLV2_ATOM_PREFIX\fP 'Chunk'"

.PP
Definition at line 35 of file atom\&.h\&.
.SS "#define LV2_ATOM__Double   \fBLV2_ATOM_PREFIX\fP 'Double'"

.PP
Definition at line 36 of file atom\&.h\&.
.SS "#define LV2_ATOM__Event   \fBLV2_ATOM_PREFIX\fP 'Event'"

.PP
Definition at line 37 of file atom\&.h\&.
.SS "#define LV2_ATOM__eventTransfer   \fBLV2_ATOM_PREFIX\fP 'eventTransfer'"

.PP
Definition at line 58 of file atom\&.h\&.
.SS "#define LV2_ATOM__Float   \fBLV2_ATOM_PREFIX\fP 'Float'"

.PP
Definition at line 38 of file atom\&.h\&.
.SS "#define LV2_ATOM__frameTime   \fBLV2_ATOM_PREFIX\fP 'frameTime'"

.PP
Definition at line 59 of file atom\&.h\&.
.SS "#define LV2_ATOM__Int   \fBLV2_ATOM_PREFIX\fP 'Int'"

.PP
Definition at line 39 of file atom\&.h\&.
.SS "#define LV2_ATOM__Literal   \fBLV2_ATOM_PREFIX\fP 'Literal'"

.PP
Definition at line 40 of file atom\&.h\&.
.SS "#define LV2_ATOM__Long   \fBLV2_ATOM_PREFIX\fP 'Long'"

.PP
Definition at line 41 of file atom\&.h\&.
.SS "#define LV2_ATOM__Number   \fBLV2_ATOM_PREFIX\fP 'Number'"

.PP
Definition at line 42 of file atom\&.h\&.
.SS "#define LV2_ATOM__Object   \fBLV2_ATOM_PREFIX\fP 'Object'"

.PP
Definition at line 43 of file atom\&.h\&.
.SS "#define LV2_ATOM__Path   \fBLV2_ATOM_PREFIX\fP 'Path'"

.PP
Definition at line 44 of file atom\&.h\&.
.SS "#define LV2_ATOM__Property   \fBLV2_ATOM_PREFIX\fP 'Property'"

.PP
Definition at line 45 of file atom\&.h\&.
.SS "#define LV2_ATOM__Resource   \fBLV2_ATOM_PREFIX\fP 'Resource'"

.PP
Definition at line 46 of file atom\&.h\&.
.SS "#define LV2_ATOM__Sequence   \fBLV2_ATOM_PREFIX\fP 'Sequence'"

.PP
Definition at line 47 of file atom\&.h\&.
.SS "#define LV2_ATOM__Sound   \fBLV2_ATOM_PREFIX\fP 'Sound'"

.PP
Definition at line 48 of file atom\&.h\&.
.SS "#define LV2_ATOM__String   \fBLV2_ATOM_PREFIX\fP 'String'"

.PP
Definition at line 49 of file atom\&.h\&.
.SS "#define LV2_ATOM__supports   \fBLV2_ATOM_PREFIX\fP 'supports'"

.PP
Definition at line 60 of file atom\&.h\&.
.SS "#define LV2_ATOM__timeUnit   \fBLV2_ATOM_PREFIX\fP 'timeUnit'"

.PP
Definition at line 61 of file atom\&.h\&.
.SS "#define LV2_ATOM__Tuple   \fBLV2_ATOM_PREFIX\fP 'Tuple'"

.PP
Definition at line 50 of file atom\&.h\&.
.SS "#define LV2_ATOM__URI   \fBLV2_ATOM_PREFIX\fP 'URI'"

.PP
Definition at line 51 of file atom\&.h\&.
.SS "#define LV2_ATOM__URID   \fBLV2_ATOM_PREFIX\fP 'URID'"

.PP
Definition at line 52 of file atom\&.h\&.
.SS "#define LV2_ATOM__Vector   \fBLV2_ATOM_PREFIX\fP 'Vector'"

.PP
Definition at line 53 of file atom\&.h\&.
.SS "#define LV2_ATOM_BODY(atom)   \fBLV2_ATOM_CONTENTS\fP(\fBLV2_Atom\fP, atom)"
Return a pointer to the body of an Atom\&. The 'body' of an atom is the data just past the \fBLV2_Atom\fP head (i\&.e\&. the same offset for all types)\&. 
.PP
Definition at line 92 of file atom\&.h\&.
.SS "#define LV2_ATOM_BODY_CONST(atom)   \fBLV2_ATOM_CONTENTS_CONST\fP(\fBLV2_Atom\fP, atom)"
Const version of LV2_ATOM_BODY\&. 
.PP
Definition at line 97 of file atom\&.h\&.
.SS "#define LV2_ATOM_CONTENTS(type, atom)   ((\fBvoid\fP*)((\fBuint8_t\fP*)(atom) + sizeof(type)))"
Return a pointer to the contents of an Atom\&. The 'contents' of an atom is the data past the complete type-specific header\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP The type of the atom, e\&.g\&. \fBLV2_Atom_String\fP\&. 
.br
\fIatom\fP A variable-sized atom\&. 
.RE
.PP

.PP
Definition at line 79 of file atom\&.h\&.
.SS "#define LV2_ATOM_CONTENTS_CONST(type, atom)   ((\fBconst\fP \fBvoid\fP*)((\fBconst\fP \fBuint8_t\fP*)(atom) + sizeof(type)))"
Const version of LV2_ATOM_CONTENTS\&. 
.PP
Definition at line 85 of file atom\&.h\&.
.SS "#define LV2_ATOM_PREFIX   \fBLV2_ATOM_URI\fP '#'"

.PP
Definition at line 29 of file atom\&.h\&.
.SS "#define LV2_ATOM_REFERENCE_TYPE   0"

.PP
Definition at line 63 of file atom\&.h\&.
.SS "#define LV2_ATOM_URI   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/atom'"

.PP
Definition at line 28 of file atom\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef char lv2_atom_assert_double_fits_in_64_bits[((sizeof(double)<=sizeof(\fBuint64_t\fP))*2)\-1]"
This expression will fail to compile if double does not fit in 64 bits\&. 
.PP
Definition at line 71 of file atom\&.h\&.
.SS "typedef \fBLV2_Atom_Int\fP \fBLV2_Atom_Bool\fP"
An atom:Bool\&. May be cast to \fBLV2_Atom\fP\&. 
.PP
Definition at line 130 of file atom\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
