.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/attributes.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/attributes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAV_GCC_VERSION_AT_LEAST\fP(x,  y)   0"
.br
.ti -1c
.RI "#define \fBav_always_inline\fP   \fBinline\fP"
.br
.ti -1c
.RI "#define \fBav_extern_inline\fP   \fBinline\fP"
.br
.ti -1c
.RI "#define \fBav_noinline\fP"
.br
.ti -1c
.RI "#define \fBav_pure\fP"
.br
.ti -1c
.RI "#define \fBav_const\fP"
.br
.ti -1c
.RI "#define \fBav_cold\fP"
.br
.ti -1c
.RI "#define \fBav_flatten\fP"
.br
.ti -1c
.RI "#define \fBattribute_deprecated\fP"
.br
.ti -1c
.RI "#define \fBAV_NOWARN_DEPRECATED\fP(code)   code"
.br
.ti -1c
.RI "#define \fBav_unused\fP"
.br
.ti -1c
.RI "#define \fBav_used\fP"
.br
.ti -1c
.RI "#define \fBav_alias\fP"
.br
.ti -1c
.RI "#define \fBav_uninit\fP(x)   x"
.br
.ti -1c
.RI "#define \fBav_builtin_constant_p\fP(x)   0"
.br
.ti -1c
.RI "#define \fBav_printf_format\fP(fmtpos,  attrpos)"
.br
.ti -1c
.RI "#define \fBav_noreturn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Macro definitions for various function/variable attributes 
.PP
Definition in file \fBattributes\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define attribute_deprecated"

.PP
Definition at line 90 of file attributes\&.h\&.
.SS "#define \fBav_alias\fP"

.PP
Definition at line 137 of file attributes\&.h\&.
.SS "#define av_always_inline   \fBinline\fP"

.PP
Definition at line 41 of file attributes\&.h\&.
.SS "#define av_builtin_constant_p(x)   0"

.PP
Definition at line 150 of file attributes\&.h\&.
.SS "#define av_cold"

.PP
Definition at line 76 of file attributes\&.h\&.
.SS "#define av_const"

.PP
Definition at line 70 of file attributes\&.h\&.
.SS "#define av_extern_inline   \fBinline\fP"

.PP
Definition at line 49 of file attributes\&.h\&.
.SS "#define av_flatten"

.PP
Definition at line 82 of file attributes\&.h\&.
.SS "#define AV_GCC_VERSION_AT_LEAST(x, y)   0"

.PP
Definition at line 32 of file attributes\&.h\&.
.SS "#define av_noinline"

.PP
Definition at line 58 of file attributes\&.h\&.
.SS "#define av_noreturn"

.PP
Definition at line 157 of file attributes\&.h\&.
.SS "#define AV_NOWARN_DEPRECATED(code)   code"
Disable warnings about deprecated features This is useful for sections of code kept for backward compatibility and scheduled for removal\&. 
.PP
Definition at line 112 of file attributes\&.h\&.
.SS "#define av_printf_format(fmtpos, attrpos)"

.PP
Definition at line 151 of file attributes\&.h\&.
.SS "#define av_pure"

.PP
Definition at line 64 of file attributes\&.h\&.
.SS "#define av_uninit(x)   x"

.PP
Definition at line 143 of file attributes\&.h\&.
.SS "#define av_unused"

.PP
Definition at line 120 of file attributes\&.h\&.
.SS "#define av_used"
Mark a variable as used and prevent the compiler from optimizing it away\&. This is useful for variables accessed only from inline assembler without the compiler being aware\&. 
.PP
Definition at line 131 of file attributes\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
