.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/au.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/au.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAU_FMT\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDOTSND_MARKER\fP   (MAKE_MARKER ('\&.', '\fBs\fP', 'n', '\fBd\fP'))"
.br
.ti -1c
.RI "#define \fBDNSDOT_MARKER\fP   (MAKE_MARKER ('\fBd\fP', 'n', '\fBs\fP', '\&.'))"
.br
.ti -1c
.RI "#define \fBAU_DATA_OFFSET\fP   24"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBAU_ENCODING_ULAW_8\fP = 1, \fBAU_ENCODING_PCM_8\fP = 2, \fBAU_ENCODING_PCM_16\fP = 3, \fBAU_ENCODING_PCM_24\fP = 4, \fBAU_ENCODING_PCM_32\fP = 5, \fBAU_ENCODING_FLOAT\fP = 6, \fBAU_ENCODING_DOUBLE\fP = 7, \fBAU_ENCODING_INDIRECT\fP = 8, \fBAU_ENCODING_NESTED\fP = 9, \fBAU_ENCODING_DSP_CORE\fP = 10, \fBAU_ENCODING_DSP_DATA_8\fP = 11, \fBAU_ENCODING_DSP_DATA_16\fP = 12, \fBAU_ENCODING_DSP_DATA_24\fP = 13, \fBAU_ENCODING_DSP_DATA_32\fP = 14, \fBAU_ENCODING_DISPLAY\fP = 16, \fBAU_ENCODING_MULAW_SQUELCH\fP = 17, \fBAU_ENCODING_EMPHASIZED\fP = 18, \fBAU_ENCODING_NEXT\fP = 19, \fBAU_ENCODING_COMPRESSED_EMPHASIZED\fP = 20, \fBAU_ENCODING_DSP_COMMANDS\fP = 21, \fBAU_ENCODING_DSP_COMMANDS_SAMPLES\fP = 22, \fBAU_ENCODING_ADPCM_G721_32\fP = 23, \fBAU_ENCODING_ADPCM_G722\fP = 24, \fBAU_ENCODING_ADPCM_G723_24\fP = 25, \fBAU_ENCODING_ADPCM_G723_40\fP = 26, \fBAU_ENCODING_ALAW_8\fP = 27 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBau_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AU_DATA_OFFSET   24"

.PP
Definition at line 37 of file au\&.c\&.
.SS "#define DNSDOT_MARKER   (MAKE_MARKER ('\fBd\fP', 'n', '\fBs\fP', '\&.'))"

.PP
Definition at line 35 of file au\&.c\&.
.SS "#define DOTSND_MARKER   (MAKE_MARKER ('\&.', '\fBs\fP', 'n', '\fBd\fP'))"

.PP
Definition at line 34 of file au\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAU_ENCODING_ULAW_8 \fP\fP
.TP
\fB\fIAU_ENCODING_PCM_8 \fP\fP
.TP
\fB\fIAU_ENCODING_PCM_16 \fP\fP
.TP
\fB\fIAU_ENCODING_PCM_24 \fP\fP
.TP
\fB\fIAU_ENCODING_PCM_32 \fP\fP
.TP
\fB\fIAU_ENCODING_FLOAT \fP\fP
.TP
\fB\fIAU_ENCODING_DOUBLE \fP\fP
.TP
\fB\fIAU_ENCODING_INDIRECT \fP\fP
.TP
\fB\fIAU_ENCODING_NESTED \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_CORE \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_DATA_8 \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_DATA_16 \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_DATA_24 \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_DATA_32 \fP\fP
.TP
\fB\fIAU_ENCODING_DISPLAY \fP\fP
.TP
\fB\fIAU_ENCODING_MULAW_SQUELCH \fP\fP
.TP
\fB\fIAU_ENCODING_EMPHASIZED \fP\fP
.TP
\fB\fIAU_ENCODING_NEXT \fP\fP
.TP
\fB\fIAU_ENCODING_COMPRESSED_EMPHASIZED \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_COMMANDS \fP\fP
.TP
\fB\fIAU_ENCODING_DSP_COMMANDS_SAMPLES \fP\fP
.TP
\fB\fIAU_ENCODING_ADPCM_G721_32 \fP\fP
.TP
\fB\fIAU_ENCODING_ADPCM_G722 \fP\fP
.TP
\fB\fIAU_ENCODING_ADPCM_G723_24 \fP\fP
.TP
\fB\fIAU_ENCODING_ADPCM_G723_40 \fP\fP
.TP
\fB\fIAU_ENCODING_ALAW_8 \fP\fP
.PP
Definition at line 43 of file au\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP au_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 105 of file au\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
