.TH "AUControl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AUControl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AUControl\&.h>\fP
.PP
Inherits wxControl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAUControl\fP ()"
.br
.ti -1c
.RI "\fB~AUControl\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBCreate\fP (wxWindow *parent, AudioComponent comp, AudioUnit unit, \fBbool\fP custom)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateCocoa\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateGeneric\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCocoaViewResized\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSize\fP (wxSizeEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateCarbon\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreateCarbonOverlay\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCarbonViewResized\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static pascal OSStatus \fBControlEventHandlerCallback\fP (EventHandlerCallRef handler, EventRef event, \fBvoid\fP *\fBdata\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file AUControl\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AUControl::AUControl ()"

.PP
Definition at line 91 of file AUControl\&.mm\&.
.SS "AUControl::~AUControl ()"

.PP
Definition at line 107 of file AUControl\&.mm\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP AUControl::CarbonViewResized ()"

.PP
Definition at line 625 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::CocoaViewResized ()"

.PP
Definition at line 413 of file AUControl\&.mm\&.
.SS "pascal OSStatus AUControl::ControlEventHandlerCallback (EventHandlerCallRef handler, EventRef event, \fBvoid\fP * data)\fC [static]\fP"

.PP
Definition at line 618 of file AUControl\&.mm\&.
.SS "\fBbool\fP AUControl::Create (wxWindow * parent, AudioComponent comp, AudioUnit unit, \fBbool\fP custom)"

.PP
Definition at line 134 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::CreateCarbon ()"

.PP
Definition at line 452 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::CreateCarbonOverlay ()"

.PP
Definition at line 591 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::CreateCocoa ()"

.PP
Definition at line 255 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::CreateGeneric ()"

.PP
Definition at line 359 of file AUControl\&.mm\&.
.SS "\fBvoid\fP AUControl::OnSize (wxSizeEvent & evt)"

.PP
Definition at line 191 of file AUControl\&.mm\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
