.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/audiounits/AUControl.mm" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/audiounits/AUControl.mm \- 
.SH SYNOPSIS
.br
.PP
\fC#include <AudioUnit/AudioUnit\&.h>\fP
.br
\fC#include <AudioUnit/AudioComponent\&.h>\fP
.br
\fC#include <AudioUnit/AudioUnitProperties\&.h>\fP
.br
\fC#include <AudioUnit/AUCocoaUIView\&.h>\fP
.br
\fC#include <CoreAudioKit/CoreAudioKit\&.h>\fP
.br
\fC#include <AudioUnit/AudioUnitCarbonView\&.h>\fP
.br
\fC#include 'AUControl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAUView\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
