.TH "AudacityProjectCommandFunctor" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudacityProjectCommandFunctor \- \fBAudacityProjectCommandFunctor\fP, derived from \fBCommandFunctor\fP, simplifies construction of menu items\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBAudacityProjectCommandFunctor\fP, derived from \fBCommandFunctor\fP, simplifies construction of menu items\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
