.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/audio_detect.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/audio_detect.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVOTE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBaudio_detect\fP (\fBSF_PRIVATE\fP *psf, \fBAUDIO_DETECT\fP *ad, \fBconst\fP unsigned char *\fBdata\fP, \fBint\fP datalen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP audio_detect (\fBSF_PRIVATE\fP * psf, \fBAUDIO_DETECT\fP * ad, \fBconst\fP unsigned char * data, \fBint\fP datalen)"

.PP
Definition at line 45 of file audio_detect\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
