.TH "AVCodecParser" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVCodecParser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <avcodec\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBcodec_ids\fP [5]"
.br
.ti -1c
.RI "\fBint\fP \fBpriv_data_size\fP"
.br
.ti -1c
.RI "\fBint\fP(* \fBparser_init\fP )(\fBAVCodecParserContext\fP *\fBs\fP)"
.br
.ti -1c
.RI "\fBint\fP(* \fBparser_parse\fP )(\fBAVCodecParserContext\fP *\fBs\fP, \fBAVCodecContext\fP *avctx, \fBconst\fP \fBuint8_t\fP **poutbuf, \fBint\fP *poutbuf_size, \fBconst\fP \fBuint8_t\fP *\fBbuf\fP, \fBint\fP buf_size)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBparser_close\fP )(\fBAVCodecParserContext\fP *\fBs\fP)"
.br
.ti -1c
.RI "\fBint\fP(* \fBsplit\fP )(\fBAVCodecContext\fP *avctx, \fBconst\fP \fBuint8_t\fP *\fBbuf\fP, \fBint\fP buf_size)"
.br
.ti -1c
.RI "struct \fBAVCodecParser\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4163 of file avcodec\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP AVCodecParser::codec_ids[5]"

.PP
Definition at line 4164 of file avcodec\&.h\&.
.SS "struct \fBAVCodecParser\fP* AVCodecParser::next"

.PP
Definition at line 4173 of file avcodec\&.h\&.
.SS "\fBvoid\fP(* AVCodecParser::parser_close) (\fBAVCodecParserContext\fP *\fBs\fP)"

.PP
Definition at line 4171 of file avcodec\&.h\&.
.SS "\fBint\fP(* AVCodecParser::parser_init) (\fBAVCodecParserContext\fP *\fBs\fP)"

.PP
Definition at line 4166 of file avcodec\&.h\&.
.SS "\fBint\fP(* AVCodecParser::parser_parse) (\fBAVCodecParserContext\fP *\fBs\fP, \fBAVCodecContext\fP *avctx, \fBconst\fP \fBuint8_t\fP **poutbuf, \fBint\fP *poutbuf_size, \fBconst\fP \fBuint8_t\fP *\fBbuf\fP, \fBint\fP buf_size)"

.PP
Definition at line 4167 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParser::priv_data_size"

.PP
Definition at line 4165 of file avcodec\&.h\&.
.SS "\fBint\fP(* AVCodecParser::split) (\fBAVCodecContext\fP *avctx, \fBconst\fP \fBuint8_t\fP *\fBbuf\fP, \fBint\fP buf_size)"

.PP
Definition at line 4172 of file avcodec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
