.TH "AVCodecParserContext" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVCodecParserContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <avcodec\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBpriv_data\fP"
.br
.ti -1c
.RI "struct \fBAVCodecParser\fP * \fBparser\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBframe_offset\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBcur_offset\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnext_frame_offset\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpict_type\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrepeat_pict\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBpts\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBdts\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBlast_pts\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBlast_dts\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfetch_timestamp\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcur_frame_start_index\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBcur_frame_offset\fP [\fBAV_PARSER_PTS_NB\fP]"
.br
.ti -1c
.RI "\fBint64_t\fP \fBcur_frame_pts\fP [\fBAV_PARSER_PTS_NB\fP]"
.br
.ti -1c
.RI "\fBint64_t\fP \fBcur_frame_dts\fP [\fBAV_PARSER_PTS_NB\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBoffset\fP"
.br
.RI "\fIbyte offset from starting packet start \fP"
.ti -1c
.RI "\fBint64_t\fP \fBcur_frame_end\fP [\fBAV_PARSER_PTS_NB\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBkey_frame\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBconvergence_duration\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdts_sync_point\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdts_ref_dts_delta\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpts_dts_delta\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBcur_frame_pos\fP [\fBAV_PARSER_PTS_NB\fP]"
.br
.ti -1c
.RI "\fBint64_t\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBlast_pos\fP"
.br
.ti -1c
.RI "\fBint\fP \fBduration\fP"
.br
.ti -1c
.RI "enum \fBAVFieldOrder\fP \fBfield_order\fP"
.br
.ti -1c
.RI "enum \fBAVPictureStructure\fP \fBpicture_structure\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoutput_picture_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4007 of file avcodec\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP AVCodecParserContext::convergence_duration"
Time difference in stream time base units from the pts of this packet to the point at which the output from the decoder has converged independent from the availability of previous frames\&. That is, the frames are virtually identical no matter if decoding started from the very first frame or from this keyframe\&. Is AV_NOPTS_VALUE if unknown\&. This field is not the display duration of the current frame\&. This field has no meaning if the packet does not have AV_PKT_FLAG_KEY set\&.
.PP
The purpose of this field is to allow seeking in streams that have no keyframes in the conventional sense\&. It corresponds to the recovery point SEI in H\&.264 and match_time_delta in NUT\&. It is also essential for some types of subtitle streams to ensure that all subtitles are correctly displayed after seeking\&. 
.PP
Definition at line 4075 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_frame_dts[\fBAV_PARSER_PTS_NB\fP]"

.PP
Definition at line 4038 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_frame_end[\fBAV_PARSER_PTS_NB\fP]"

.PP
Definition at line 4048 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_frame_offset[\fBAV_PARSER_PTS_NB\fP]"

.PP
Definition at line 4036 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_frame_pos[\fBAV_PARSER_PTS_NB\fP]"
Position of the packet in file\&.
.PP
Analogous to cur_frame_pts/dts 
.PP
Definition at line 4123 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_frame_pts[\fBAV_PARSER_PTS_NB\fP]"

.PP
Definition at line 4037 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::cur_frame_start_index"

.PP
Definition at line 4035 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::cur_offset"

.PP
Definition at line 4011 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::dts"

.PP
Definition at line 4027 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::dts_ref_dts_delta"
Offset of the current timestamp against last timestamp sync point in units of \fBAVCodecContext\&.time_base\fP\&.
.PP
Set to INT_MIN when dts_sync_point unused\&. Otherwise, it must contain a valid timestamp offset\&.
.PP
Note that the timestamp of sync point has usually a nonzero dts_ref_dts_delta, which refers to the previous sync point\&. Offset of the next frame after timestamp sync point will be usually 1\&.
.PP
For example, this corresponds to H\&.264 cpb_removal_delay\&. 
.PP
Definition at line 4102 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::dts_sync_point"
Synchronization point for start of timestamp generation\&.
.PP
Set to >0 for sync point, 0 for no sync point and <0 for undefined (default)\&.
.PP
For example, this corresponds to presence of H\&.264 buffering period SEI message\&. 
.PP
Definition at line 4087 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::duration"
Duration of the current frame\&. For audio, this is in units of 1 / \fBAVCodecContext\&.sample_rate\fP\&. For all other types, this is in units of \fBAVCodecContext\&.time_base\fP\&. 
.PP
Definition at line 4140 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::fetch_timestamp"

.PP
Definition at line 4032 of file avcodec\&.h\&.
.SS "enum \fBAVFieldOrder\fP AVCodecParserContext::field_order"

.PP
Definition at line 4142 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::flags"

.PP
Definition at line 4040 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::frame_offset"

.PP
Definition at line 4010 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::key_frame"
Set by parser to 1 for key frames and 0 for non-key frames\&. It is initialized to -1, so if the parser doesn't set this flag, old-style fallback using AV_PICTURE_TYPE_I picture type as key frames will be used\&. 
.PP
Definition at line 4056 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::last_dts"

.PP
Definition at line 4031 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::last_pos"
Previous frame byte position\&. 
.PP
Definition at line 4133 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::last_pts"

.PP
Definition at line 4030 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::next_frame_offset"

.PP
Definition at line 4013 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::offset"

.PP
byte offset from starting packet start 
.PP
Definition at line 4047 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::output_picture_number"
Picture number incremented in presentation or output order\&. This field may be reinitialized at the first picture of a new sequence\&.
.PP
For example, this corresponds to H\&.264 PicOrderCnt\&. 
.PP
Definition at line 4160 of file avcodec\&.h\&.
.SS "struct \fBAVCodecParser\fP* AVCodecParserContext::parser"

.PP
Definition at line 4009 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::pict_type"

.PP
Definition at line 4015 of file avcodec\&.h\&.
.SS "enum \fBAVPictureStructure\fP AVCodecParserContext::picture_structure"
Indicate whether a picture is coded as a frame, top field or bottom field\&.
.PP
For example, H\&.264 field_pic_flag equal to 0 corresponds to AV_PICTURE_STRUCTURE_FRAME\&. An H\&.264 picture with field_pic_flag equal to 1 and bottom_field_flag equal to 0 corresponds to AV_PICTURE_STRUCTURE_TOP_FIELD\&. 
.PP
Definition at line 4152 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::pos"
Byte position of currently parsed frame in stream\&. 
.PP
Definition at line 4128 of file avcodec\&.h\&.
.SS "\fBvoid\fP* AVCodecParserContext::priv_data"

.PP
Definition at line 4008 of file avcodec\&.h\&.
.SS "\fBint64_t\fP AVCodecParserContext::pts"

.PP
Definition at line 4026 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::pts_dts_delta"
Presentation delay of current frame in units of \fBAVCodecContext\&.time_base\fP\&.
.PP
Set to INT_MIN when dts_sync_point unused\&. Otherwise, it must contain valid non-negative timestamp delta (presentation time of a frame must not lie in the past)\&.
.PP
This delay represents the difference between decoding and presentation time of the frame\&.
.PP
For example, this corresponds to H\&.264 dpb_output_delay\&. 
.PP
Definition at line 4116 of file avcodec\&.h\&.
.SS "\fBint\fP AVCodecParserContext::repeat_pict"
This field is used for proper frame duration computation in lavf\&. It signals, how much longer the frame duration of the current frame is compared to normal frame duration\&.
.PP
frame_duration = (1 + repeat_pict) * time_base
.PP
It is used by codecs like H\&.264 to display telecined material\&. 
.PP
Definition at line 4025 of file avcodec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
