.TH "AVFrac" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVFrac \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <avformat\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBval\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnum\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBden\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The exact value of the fractional number is: 'val + num / den'\&. num is assumed to be 0 <= num < den\&. 
.PP
Definition at line 377 of file avformat\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP AVFrac::den"

.PP
Definition at line 378 of file avformat\&.h\&.
.SS "\fBint64_t\fP AVFrac::num"

.PP
Definition at line 378 of file avformat\&.h\&.
.SS "\fBint64_t\fP AVFrac::val"

.PP
Definition at line 378 of file avformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
