.TH "AVOpenCLExternalEnv" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVOpenCLExternalEnv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opencl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "cl_platform_id \fBplatform_id\fP"
.br
.ti -1c
.RI "cl_device_type \fBdevice_type\fP"
.br
.ti -1c
.RI "cl_context \fBcontext\fP"
.br
.ti -1c
.RI "cl_device_id \fBdevice_id\fP"
.br
.ti -1c
.RI "cl_command_queue \fBcommand_queue\fP"
.br
.ti -1c
.RI "char * \fBplatform_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file opencl\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "cl_command_queue AVOpenCLExternalEnv::command_queue"

.PP
Definition at line 84 of file opencl\&.h\&.
.SS "cl_context AVOpenCLExternalEnv::context"

.PP
Definition at line 82 of file opencl\&.h\&.
.SS "cl_device_id AVOpenCLExternalEnv::device_id"

.PP
Definition at line 83 of file opencl\&.h\&.
.SS "cl_device_type AVOpenCLExternalEnv::device_type"

.PP
Definition at line 81 of file opencl\&.h\&.
.SS "cl_platform_id AVOpenCLExternalEnv::platform_id"

.PP
Definition at line 80 of file opencl\&.h\&.
.SS "char* AVOpenCLExternalEnv::platform_name"

.PP
Definition at line 85 of file opencl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
