.TH "AVProbeData" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVProbeData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <avformat\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBfilename\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbuf_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure contains the data a format has to probe a file\&. 
.PP
Definition at line 389 of file avformat\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char* AVProbeData::buf"
Buffer must have AVPROBE_PADDING_SIZE of extra allocated bytes filled with zero\&. 
.PP
Definition at line 391 of file avformat\&.h\&.
.SS "\fBint\fP AVProbeData::buf_size"
Size of buf except extra allocated bytes 
.PP
Definition at line 392 of file avformat\&.h\&.
.SS "\fBconst\fP char* AVProbeData::filename"

.PP
Definition at line 390 of file avformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
