.TH "AVTimecode" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AVTimecode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timecode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBstart\fP"
.br
.RI "\fItimecode frame start (first base frame number) \fP"
.ti -1c
.RI "\fBuint32_t\fP \fBflags\fP"
.br
.RI "\fIflags such as drop frame, +24 hours support, \&.\&.\&. \fP"
.ti -1c
.RI "\fBAVRational\fP \fBrate\fP"
.br
.RI "\fIframe rate in rational form \fP"
.ti -1c
.RI "unsigned \fBfps\fP"
.br
.RI "\fIframe per second; must be consistent with the rate field \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file timecode\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP AVTimecode::flags"

.PP
flags such as drop frame, +24 hours support, \&.\&.\&. 
.PP
Definition at line 43 of file timecode\&.h\&.
.SS "unsigned AVTimecode::fps"

.PP
frame per second; must be consistent with the rate field 
.PP
Definition at line 45 of file timecode\&.h\&.
.SS "\fBAVRational\fP AVTimecode::rate"

.PP
frame rate in rational form 
.PP
Definition at line 44 of file timecode\&.h\&.
.SS "\fBint\fP AVTimecode::start"

.PP
timecode frame start (first base frame number) 
.PP
Definition at line 42 of file timecode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
