.TH "BandedWG" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BandedWG \- Banded waveguide modeling class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BandedWG\&.h>\fP
.SH "Detailed Description"
.PP 
Banded waveguide modeling class\&. 

This class uses banded waveguide techniques to model a variety of sounds, including bowed bars, glasses, and bowls\&. For more information, see Essl, G\&. and Cook, P\&. "Banded Waveguides: Towards Physical Modelling of Bar Percussion Instruments", Proceedings of the 1999 International Computer Music Conference\&.
.PP
Control Change Numbers:
.IP "\(bu" 2
Bow Pressure = 2
.IP "\(bu" 2
Bow Motion = 4
.IP "\(bu" 2
Strike Position = 8 (not implemented)
.IP "\(bu" 2
Vibrato Frequency = 11
.IP "\(bu" 2
Gain = 1
.IP "\(bu" 2
Bow Velocity = 128
.IP "\(bu" 2
Set Striking = 64
.IP "\(bu" 2
Instrument Presets = 16
.IP "  \(bu" 4
Uniform Bar = 0
.IP "  \(bu" 4
Tuned Bar = 1
.IP "  \(bu" 4
Glass Harmonica = 2
.IP "  \(bu" 4
Tibetan Bowl = 3
.PP

.PP
.PP
by Georg Essl, 1999 - 2004\&. Modified for \fBStk\fP 4\&.0 by Gary Scavone\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
