.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/base64.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/base64.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAV_BASE64_SIZE\fP(x)   (((x)+2) / 3 * 4 + 1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBav_base64_decode\fP (\fBuint8_t\fP *\fBout\fP, \fBconst\fP char *\fBin\fP, \fBint\fP out_size)"
.br
.ti -1c
.RI "char * \fBav_base64_encode\fP (char *\fBout\fP, \fBint\fP out_size, \fBconst\fP \fBuint8_t\fP *\fBin\fP, \fBint\fP in_size)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
