.TH "BatchCommands" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BatchCommands \- Maintains the chain of commands used in batch processing\&. See also \fBBatchCommandDialog\fP and \fBBatchProcessDialog\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BatchCommands\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchCommands\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApplyChain\fP (\fBconst\fP wxString &\fBfilename\fP=wxT(''))"
.br
.ti -1c
.RI "\fBbool\fP \fBApplyCommand\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBApplyCommandInBatchMode\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBApplySpecialCommand\fP (\fBint\fP iCommand, \fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBApplyEffectCommand\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBReportAndSkip\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAbortBatch\fP ()"
.br
.ti -1c
.RI "wxString \fBBuildCleanFileName\fP (\fBconst\fP wxString &fileName, \fBconst\fP wxString &extension)"
.br
.ti -1c
.RI "\fBbool\fP \fBWriteMp3File\fP (\fBconst\fP wxString &Name, \fBint\fP bitrate)"
.br
.ti -1c
.RI "double \fBGetEndTime\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsMono\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBResetChain\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBReadChain\fP (\fBconst\fP wxString &chain)"
.br
.ti -1c
.RI "\fBbool\fP \fBWriteChain\fP (\fBconst\fP wxString &chain)"
.br
.ti -1c
.RI "\fBbool\fP \fBAddChain\fP (\fBconst\fP wxString &chain)"
.br
.ti -1c
.RI "\fBbool\fP \fBDeleteChain\fP (\fBconst\fP wxString &\fBname\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBRenameChain\fP (\fBconst\fP wxString &oldchain, \fBconst\fP wxString &newchain)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddToChain\fP (\fBconst\fP wxString &command, \fBint\fP before=\-1)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddToChain\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP, \fBint\fP before=\-1)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDeleteFromChain\fP (\fBint\fP index)"
.br
.ti -1c
.RI "wxString \fBGetCommand\fP (\fBint\fP index)"
.br
.ti -1c
.RI "wxString \fBGetParams\fP (\fBint\fP index)"
.br
.ti -1c
.RI "\fBint\fP \fBGetCount\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetWavToMp3Chain\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsFixed\fP (\fBconst\fP wxString &\fBname\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRestoreChain\fP (\fBconst\fP wxString &\fBname\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSplit\fP (\fBconst\fP wxString &\fBstr\fP, wxString &command, wxString &param)"
.br
.ti -1c
.RI "wxString \fBJoin\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &param)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static wxArrayString \fBGetNames\fP ()"
.br
.ti -1c
.RI "static wxArrayString \fBGetAllCommands\fP ()"
.br
.ti -1c
.RI "static wxString \fBGetCurrentParamsFor\fP (\fBconst\fP wxString &command)"
.br
.ti -1c
.RI "static wxString \fBPromptForParamsFor\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP, wxWindow *parent)"
.br
.ti -1c
.RI "static wxString \fBPromptForPresetFor\fP (\fBconst\fP wxString &command, \fBconst\fP wxString &\fBparams\fP, wxWindow *parent)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxArrayString \fBmCommandChain\fP"
.br
.ti -1c
.RI "wxArrayString \fBmParamsChain\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBmAbort\fP"
.br
.ti -1c
.RI "\fBExporter\fP \fBmExporter\fP"
.br
.ti -1c
.RI "wxString \fBmFileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Maintains the chain of commands used in batch processing\&. See also \fBBatchCommandDialog\fP and \fBBatchProcessDialog\fP\&. 
.PP
Definition at line 22 of file BatchCommands\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BatchCommands::BatchCommands ()"

.PP
Definition at line 70 of file BatchCommands\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP BatchCommands::AbortBatch ()"

.PP
Definition at line 713 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::AddChain (\fBconst\fP wxString & chain)"

.PP
Definition at line 220 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::AddToChain (\fBconst\fP wxString & command, \fBint\fP before = \fC\-1\fP)"

.PP
Definition at line 718 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::AddToChain (\fBconst\fP wxString & command, \fBconst\fP wxString & params, \fBint\fP before = \fC\-1\fP)"

.PP
Definition at line 723 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ApplyChain (\fBconst\fP wxString & filename = \fCwxT('')\fP)"

.PP
Definition at line 665 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ApplyCommand (\fBconst\fP wxString & command, \fBconst\fP wxString & params)"

.PP
Definition at line 620 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ApplyCommandInBatchMode (\fBconst\fP wxString & command, \fBconst\fP wxString & params)"

.PP
Definition at line 647 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ApplyEffectCommand (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & command, \fBconst\fP wxString & params)"

.PP
Definition at line 589 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ApplySpecialCommand (\fBint\fP iCommand, \fBconst\fP wxString & command, \fBconst\fP wxString & params)"

.PP
Definition at line 505 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::BuildCleanFileName (\fBconst\fP wxString & fileName, \fBconst\fP wxString & extension)"

.PP
Definition at line 414 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::DeleteChain (\fBconst\fP wxString & name)"

.PP
Definition at line 232 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::DeleteFromChain (\fBint\fP index)"

.PP
Definition at line 733 of file BatchCommands\&.cpp\&.
.SS "wxArrayString BatchCommands::GetAllCommands ()\fC [static]\fP"

.PP
Definition at line 260 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::GetCommand (\fBint\fP index)"

.PP
Definition at line 83 of file BatchCommands\&.cpp\&.
.SS "\fBint\fP BatchCommands::GetCount ()"

.PP
Definition at line 101 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::GetCurrentParamsFor (\fBconst\fP wxString & command)\fC [static]\fP"

.PP
Definition at line 309 of file BatchCommands\&.cpp\&.
.SS "double BatchCommands::GetEndTime ()"

.PP
Definition at line 365 of file BatchCommands\&.cpp\&.
.SS "wxArrayString BatchCommands::GetNames ()\fC [static]\fP"

.PP
Definition at line 772 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::GetParams (\fBint\fP index)"

.PP
Definition at line 92 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::IsFixed (\fBconst\fP wxString & name)"

.PP
Definition at line 787 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::IsMono ()"

.PP
Definition at line 384 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::Join (\fBconst\fP wxString & command, \fBconst\fP wxString & param)"

.PP
Definition at line 825 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::PromptForParamsFor (\fBconst\fP wxString & command, \fBconst\fP wxString & params, wxWindow * parent)\fC [static]\fP"

.PP
Definition at line 320 of file BatchCommands\&.cpp\&.
.SS "wxString BatchCommands::PromptForPresetFor (\fBconst\fP wxString & command, \fBconst\fP wxString & params, wxWindow * parent)\fC [static]\fP"

.PP
Definition at line 345 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ReadChain (\fBconst\fP wxString & chain)"

.PP
Definition at line 106 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::RenameChain (\fBconst\fP wxString & oldchain, \fBconst\fP wxString & newchain)"

.PP
Definition at line 241 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::ReportAndSkip (\fBconst\fP wxString & command, \fBconst\fP wxString & params)"

.PP
Definition at line 751 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::ResetChain ()"

.PP
Definition at line 743 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::RestoreChain (\fBconst\fP wxString & name)"

.PP
Definition at line 794 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::SetWavToMp3Chain ()"

.PP
Definition at line 251 of file BatchCommands\&.cpp\&.
.SS "\fBvoid\fP BatchCommands::Split (\fBconst\fP wxString & str, wxString & command, wxString & param)"

.PP
Definition at line 803 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::WriteChain (\fBconst\fP wxString & chain)"

.PP
Definition at line 169 of file BatchCommands\&.cpp\&.
.SS "\fBbool\fP BatchCommands::WriteMp3File (\fBconst\fP wxString & Name, \fBint\fP bitrate)"

.PP
Definition at line 461 of file BatchCommands\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP BatchCommands::mAbort"

.PP
Definition at line 76 of file BatchCommands\&.h\&.
.SS "wxArrayString BatchCommands::mCommandChain"

.PP
Definition at line 74 of file BatchCommands\&.h\&.
.SS "\fBExporter\fP BatchCommands::mExporter"

.PP
Definition at line 78 of file BatchCommands\&.h\&.
.SS "wxString BatchCommands::mFileName"

.PP
Definition at line 79 of file BatchCommands\&.h\&.
.SS "wxArrayString BatchCommands::mParamsChain"

.PP
Definition at line 75 of file BatchCommands\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
