.TH "BatchPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BatchPrefs \- A \fBPrefsPanel\fP that builds up a chain of effects in \fBBatchCommands\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BatchPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchPrefs\fP (wxWindow *parent)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fB~BatchPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.RI "\fISend changed values back to Prefs, and update Audacity\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP that builds up a chain of effects in \fBBatchCommands\fP\&. 
.PP
Definition at line 23 of file BatchPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BatchPrefs::BatchPrefs (wxWindow * parent)"

.PP
Constructor\&. 
.PP
Definition at line 36 of file BatchPrefs\&.cpp\&.
.SS "BatchPrefs::~BatchPrefs ()"

.PP
Definition at line 81 of file BatchPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP BatchPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Send changed values back to Prefs, and update Audacity\&. 
.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 73 of file BatchPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
