.TH "binding" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binding \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBprefix\fP * \fBprefix\fP"
.br
.ti -1c
.RI "struct \fBbinding\fP * \fBnextTagBinding\fP"
.br
.ti -1c
.RI "struct \fBbinding\fP * \fBprevPrefixBinding\fP"
.br
.ti -1c
.RI "\fBconst\fP struct \fBattribute_id\fP * \fBattId\fP"
.br
.ti -1c
.RI "\fBXML_Char\fP * \fBuri\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuriLen\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuriAlloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP struct \fBattribute_id\fP* binding::attId"

.PP
Definition at line 148 of file xmlparse\&.c\&.
.SS "struct \fBbinding\fP* binding::nextTagBinding"

.PP
Definition at line 146 of file xmlparse\&.c\&.
.SS "struct \fBprefix\fP* binding::prefix"

.PP
Definition at line 145 of file xmlparse\&.c\&.
.SS "struct \fBbinding\fP* binding::prevPrefixBinding"

.PP
Definition at line 147 of file xmlparse\&.c\&.
.SS "\fBXML_Char\fP* binding::uri"

.PP
Definition at line 149 of file xmlparse\&.c\&.
.SS "\fBint\fP binding::uriAlloc"

.PP
Definition at line 151 of file xmlparse\&.c\&.
.SS "\fBint\fP binding::uriLen"

.PP
Definition at line 150 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
