.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/binheader_writef_check.py" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/binheader_writef_check.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbinheader_writef_check\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBbinheader_writef_check\&.find_binheader_writefs\fP (\fBdata\fP)"
.br
.ti -1c
.RI "def \fBbinheader_writef_check\&.find_format_string\fP (\fBs\fP)"
.br
.ti -1c
.RI "def \fBbinheader_writef_check\&.get_param_list\fP (\fBdata\fP)"
.br
.ti -1c
.RI "def \fBbinheader_writef_check\&.handle_file\fP (fname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBbinheader_writef_check\&.errors\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
