.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/biquadfilt.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/biquadfilt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_biquadfilt\fP (\fBsound_type\fP \fBs\fP, double b0, double b1, double b2, double a1, double a2, double z1init, double z2init)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_biquadfilt\fP (\fBsound_type\fP \fBs\fP, double b0, double b1, double b2, double a1, double a2, double z1init, double z2init)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_biquadfilt (\fBsound_type\fP s, double b0, double b1, double b2, double a1, double a2, double z1init, double z2init)"

.PP
Definition at line 236 of file biquadfilt\&.c\&.
.SS "\fBsound_type\fP snd_make_biquadfilt (\fBsound_type\fP s, double b0, double b1, double b2, double a1, double a2, double z1init, double z2init)"

.PP
Definition at line 185 of file biquadfilt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
