.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/bitrate.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/bitrate.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <ogg/ogg\&.h>\fP
.br
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'codec_internal\&.h'\fP
.br
\fC#include 'os\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'bitrate\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBvorbis_bitrate_init\fP (\fBvorbis_info\fP *vi, \fBbitrate_manager_state\fP *bm)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_bitrate_clear\fP (\fBbitrate_manager_state\fP *bm)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_bitrate_managed\fP (\fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_bitrate_addblock\fP (\fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_bitrate_flushpacket\fP (\fBvorbis_dsp_state\fP *vd, \fBogg_packet\fP *op)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP vorbis_bitrate_addblock (\fBvorbis_block\fP * vb)"

.PP
Definition at line 74 of file bitrate\&.c\&.
.SS "\fBvoid\fP vorbis_bitrate_clear (\fBbitrate_manager_state\fP * bm)"

.PP
Definition at line 59 of file bitrate\&.c\&.
.SS "\fBint\fP vorbis_bitrate_flushpacket (\fBvorbis_dsp_state\fP * vd, \fBogg_packet\fP * op)"

.PP
Definition at line 230 of file bitrate\&.c\&.
.SS "\fBvoid\fP vorbis_bitrate_init (\fBvorbis_info\fP * vi, \fBbitrate_manager_state\fP * bm)"

.PP
Definition at line 29 of file bitrate\&.c\&.
.SS "\fBint\fP vorbis_bitrate_managed (\fBvorbis_block\fP * vb)"

.PP
Definition at line 64 of file bitrate\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
