.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libogg/src/bitwise.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libogg/src/bitwise.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <ogg/ogg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_INCREMENT\fP   256"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBoggpack_writeinit\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_writeinit\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBoggpack_writecheck\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBoggpackB_writecheck\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_writetrunc\fP (\fBoggpack_buffer\fP *\fBb\fP, long \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_writetrunc\fP (\fBoggpack_buffer\fP *\fBb\fP, long \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_write\fP (\fBoggpack_buffer\fP *\fBb\fP, unsigned long \fBvalue\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_write\fP (\fBoggpack_buffer\fP *\fBb\fP, unsigned long \fBvalue\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_writealign\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_writealign\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_writecopy\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBvoid\fP *source, long \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_writecopy\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBvoid\fP *source, long \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_reset\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_reset\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_writeclear\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_writeclear\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_readinit\fP (\fBoggpack_buffer\fP *\fBb\fP, unsigned char *\fBbuf\fP, \fBint\fP bytes)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_readinit\fP (\fBoggpack_buffer\fP *\fBb\fP, unsigned char *\fBbuf\fP, \fBint\fP bytes)"
.br
.ti -1c
.RI "long \fBoggpack_look\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_look\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "long \fBoggpack_look1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_look1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_adv\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_adv\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpack_adv1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoggpackB_adv1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpack_read\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_read\fP (\fBoggpack_buffer\fP *\fBb\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "long \fBoggpack_read1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_read1\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpack_bytes\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpack_bits\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_bytes\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "long \fBoggpackB_bits\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "unsigned char * \fBoggpack_get_buffer\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.ti -1c
.RI "unsigned char * \fBoggpackB_get_buffer\fP (\fBoggpack_buffer\fP *\fBb\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_INCREMENT   256"

.PP
Definition at line 26 of file bitwise\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP oggpack_adv (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 338 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_adv1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 358 of file bitwise\&.c\&.
.SS "long oggpack_bits (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 503 of file bitwise\&.c\&.
.SS "long oggpack_bytes (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 499 of file bitwise\&.c\&.
.SS "unsigned char* oggpack_get_buffer (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 515 of file bitwise\&.c\&.
.SS "long oggpack_look (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 266 of file bitwise\&.c\&.
.SS "long oggpack_look1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 328 of file bitwise\&.c\&.
.SS "long oggpack_read (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 371 of file bitwise\&.c\&.
.SS "long oggpack_read1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 457 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_readinit (\fBoggpack_buffer\fP * b, unsigned char * buf, \fBint\fP bytes)"

.PP
Definition at line 255 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_reset (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 235 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_write (\fBoggpack_buffer\fP * b, unsigned long value, \fBint\fP bits)"

.PP
Definition at line 83 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_writealign (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 168 of file bitwise\&.c\&.
.SS "\fBint\fP oggpack_writecheck (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 51 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_writeclear (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 246 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_writecopy (\fBoggpack_buffer\fP * b, \fBvoid\fP * source, long bits)"

.PP
Definition at line 227 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_writeinit (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 40 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpack_writetrunc (\fBoggpack_buffer\fP * b, long bits)"

.PP
Definition at line 60 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_adv (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 354 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_adv1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 366 of file bitwise\&.c\&.
.SS "long oggpackB_bits (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 511 of file bitwise\&.c\&.
.SS "long oggpackB_bytes (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 507 of file bitwise\&.c\&.
.SS "unsigned char* oggpackB_get_buffer (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 519 of file bitwise\&.c\&.
.SS "long oggpackB_look (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 298 of file bitwise\&.c\&.
.SS "long oggpackB_look1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 333 of file bitwise\&.c\&.
.SS "long oggpackB_read (\fBoggpack_buffer\fP * b, \fBint\fP bits)"

.PP
Definition at line 415 of file bitwise\&.c\&.
.SS "long oggpackB_read1 (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 478 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_readinit (\fBoggpack_buffer\fP * b, unsigned char * buf, \fBint\fP bytes)"

.PP
Definition at line 261 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_reset (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 242 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_write (\fBoggpack_buffer\fP * b, unsigned long value, \fBint\fP bits)"

.PP
Definition at line 126 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_writealign (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 174 of file bitwise\&.c\&.
.SS "\fBint\fP oggpackB_writecheck (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 56 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_writeclear (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 251 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_writecopy (\fBoggpack_buffer\fP * b, \fBvoid\fP * source, long bits)"

.PP
Definition at line 231 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_writeinit (\fBoggpack_buffer\fP * b)"

.PP
Definition at line 47 of file bitwise\&.c\&.
.SS "\fBvoid\fP oggpackB_writetrunc (\fBoggpack_buffer\fP * b, long bits)"

.PP
Definition at line 71 of file bitwise\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
