.TH "BlockArray" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockArray \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sequence\&.h>\fP
.PP
Inherits vector< SeqBlock >\&.
.SH "Detailed Description"
.PP 
Definition at line 55 of file Sequence\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
