.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/broadcast.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/broadcast.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SF_BROADCAST_INFO_16K * \fBbroadcast_var_alloc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBbroadcast_var_set\fP (\fBSF_PRIVATE\fP *psf, \fBconst\fP SF_BROADCAST_INFO *\fBinfo\fP, size_t datasize)"
.br
.ti -1c
.RI "\fBint\fP \fBbroadcast_var_get\fP (\fBSF_PRIVATE\fP *psf, SF_BROADCAST_INFO *\fBdata\fP, size_t datasize)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SF_BROADCAST_INFO_16K* broadcast_var_alloc (\fBvoid\fP)"

.PP
Definition at line 40 of file broadcast\&.c\&.
.SS "\fBint\fP broadcast_var_get (\fBSF_PRIVATE\fP * psf, SF_BROADCAST_INFO * data, size_t datasize)"

.PP
Definition at line 97 of file broadcast\&.c\&.
.SS "\fBint\fP broadcast_var_set (\fBSF_PRIVATE\fP * psf, \fBconst\fP SF_BROADCAST_INFO * info, size_t datasize)"

.PP
Definition at line 45 of file broadcast\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
