.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/examples Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\-single\-block\&.c\fP"
.br
.ti -1c
.RI "file \fB1a\-lsr\&.c\fP"
.br
.ti -1c
.RI "file \fB2\-stream\&.C\fP"
.br
.ti -1c
.RI "file \fB3\-options\-input\-fn\&.c\fP"
.br
.ti -1c
.RI "file \fB4\-split\-channels\&.c\fP"
.br
.ti -1c
.RI "file \fB5\-variable\-rate\&.c\fP"
.br
.ti -1c
.RI "file \fBexamples\-common\&.h\fP"
.br
.in -1c
