.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAAFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAAFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBBPMDetect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcpu_detect\&.h\fP"
.br
.ti -1c
.RI "file \fBcpu_detect_x86\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFIFOSampleBuffer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFIRFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFIRFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBmmx_optimized\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPeakFinder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPeakFinder\&.h\fP"
.br
.ti -1c
.RI "file \fBRateTransposer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRateTransposer\&.h\fP"
.br
.ti -1c
.RI "file \fBSoundTouch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsse_optimized\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTDStretch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTDStretch\&.h\fP"
.br
.in -1c
