.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbooks\fP"
.br
.ti -1c
.RI "directory \fBmodes\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanalysis\&.c\fP"
.br
.ti -1c
.RI "file \fBbackends\&.h\fP"
.br
.ti -1c
.RI "file \fBbarkmel\&.c\fP"
.br
.ti -1c
.RI "file \fBbitrate\&.c\fP"
.br
.ti -1c
.RI "file \fBbitrate\&.h\fP"
.br
.ti -1c
.RI "file \fBblock\&.c\fP"
.br
.ti -1c
.RI "file \fBcodebook\&.c\fP"
.br
.ti -1c
.RI "file \fBcodebook\&.h\fP"
.br
.ti -1c
.RI "file \fBcodec_internal\&.h\fP"
.br
.ti -1c
.RI "file \fBenvelope\&.c\fP"
.br
.ti -1c
.RI "file \fBenvelope\&.h\fP"
.br
.ti -1c
.RI "file \fBfloor0\&.c\fP"
.br
.ti -1c
.RI "file \fBfloor1\&.c\fP"
.br
.ti -1c
.RI "file \fBhighlevel\&.h\fP"
.br
.ti -1c
.RI "file \fBinfo\&.c\fP"
.br
.ti -1c
.RI "file \fBlookup\&.c\fP"
.br
.ti -1c
.RI "file \fBlookup\&.h\fP"
.br
.ti -1c
.RI "file \fBlookup_data\&.h\fP"
.br
.ti -1c
.RI "file \fBlpc\&.c\fP"
.br
.ti -1c
.RI "file \fBlpc\&.h\fP"
.br
.ti -1c
.RI "file \fBlsp\&.c\fP"
.br
.ti -1c
.RI "file \fBlsp\&.h\fP"
.br
.ti -1c
.RI "file \fBmapping0\&.c\fP"
.br
.ti -1c
.RI "file \fBmasking\&.h\fP"
.br
.ti -1c
.RI "file \fBmdct\&.c\fP"
.br
.ti -1c
.RI "file \fBmdct\&.h\fP"
.br
.ti -1c
.RI "file \fBmisc\&.h\fP"
.br
.ti -1c
.RI "file \fBos\&.h\fP"
.br
.ti -1c
.RI "file \fBpsy\&.c\fP"
.br
.ti -1c
.RI "file \fBpsy\&.h\fP"
.br
.ti -1c
.RI "file \fBpsytune\&.c\fP"
.br
.ti -1c
.RI "file \fBregistry\&.c\fP"
.br
.ti -1c
.RI "file \fBregistry\&.h\fP"
.br
.ti -1c
.RI "file \fBres0\&.c\fP"
.br
.ti -1c
.RI "file \fBscales\&.h\fP"
.br
.ti -1c
.RI "file \fBsharedbook\&.c\fP"
.br
.ti -1c
.RI "file \fBsmallft\&.c\fP"
.br
.ti -1c
.RI "file \fBsmallft\&.h\fP"
.br
.ti -1c
.RI "file \fBsynthesis\&.c\fP"
.br
.ti -1c
.RI "file \fBtone\&.c\fP"
.br
.ti -1c
.RI "file \fBvorbisenc\&.c\fP"
.br
.ti -1c
.RI "file \fBvorbisfile\&.c\fP"
.br
.ti -1c
.RI "file \fBwindow\&.c\fP"
.br
.ti -1c
.RI "file \fBwindow\&.h\fP"
.br
.in -1c
