.TH "C:/_dev/OpenU/Audacity/audacity/src/blockfile Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/blockfile Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLegacyAliasBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLegacyAliasBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBLegacyBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLegacyBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBODDecodeBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBODDecodeBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBODPCMAliasBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBODPCMAliasBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBPCMAliasBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPCMAliasBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBSilentBlockFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSilentBlockFile\&.h\fP"
.br
.ti -1c
.RI "file \fBSimpleBlockFile\&.cpp\fP"
.br
.RI "\fIImplements \fBSimpleBlockFile\fP and \fBauHeader\fP\&. \fP"
.ti -1c
.RI "file \fBSimpleBlockFile\&.h\fP"
.br
.in -1c
