.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/sbsms/src Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/sbsms/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuffer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbuffer\&.h\fP"
.br
.ti -1c
.RI "file \fBdBTable\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdBTable\&.h\fP"
.br
.ti -1c
.RI "file \fBfft\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfft\&.h\fP"
.br
.ti -1c
.RI "file \fBgrain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgrain\&.h\fP"
.br
.ti -1c
.RI "file \fBreal\&.h\fP"
.br
.ti -1c
.RI "file \fBresample\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsbsms\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsincCoeffs\&.h\fP"
.br
.ti -1c
.RI "file \fBslide\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsms\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsms\&.h\fP"
.br
.ti -1c
.RI "file \fBsse\&.h\fP"
.br
.ti -1c
.RI "file \fBsubband\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsubband\&.h\fP"
.br
.ti -1c
.RI "file \fBsynthTable\&.h\fP"
.br
.ti -1c
.RI "file \fBtrack\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtrack\&.h\fP"
.br
.ti -1c
.RI "file \fBtrackpoint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtrackpoint\&.h\fP"
.br
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.in -1c
