.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/common Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/common Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpa_allocation\&.c\fP"
.br
.RI "\fIAllocation Group implementation\&. \fP"
.ti -1c
.RI "file \fBpa_allocation\&.h\fP"
.br
.RI "\fIAllocation Group prototypes\&. An Allocation Group makes it easy to allocate multiple blocks of memory and free them all at once\&. \fP"
.ti -1c
.RI "file \fBpa_converters\&.c\fP"
.br
.RI "\fIConversion function implementations\&. \fP"
.ti -1c
.RI "file \fBpa_converters\&.h\fP"
.br
.RI "\fIConversion functions used to convert buffers of samples from one format to another\&. \fP"
.ti -1c
.RI "file \fBpa_cpuload\&.c\fP"
.br
.RI "\fIFunctions to assist in measuring the CPU utilization of a callback stream\&. Used to implement the \fBPa_GetStreamCpuLoad()\fP function\&. \fP"
.ti -1c
.RI "file \fBpa_cpuload\&.h\fP"
.br
.RI "\fIFunctions to assist in measuring the CPU utilization of a callback stream\&. Used to implement the \fBPa_GetStreamCpuLoad()\fP function\&. \fP"
.ti -1c
.RI "file \fBpa_debugprint\&.c\fP"
.br
.RI "\fIImplements log function\&. \fP"
.ti -1c
.RI "file \fBpa_debugprint\&.h\fP"
.br
.ti -1c
.RI "file \fBpa_dither\&.c\fP"
.br
.RI "\fIFunctions for generating dither noise\&. \fP"
.ti -1c
.RI "file \fBpa_dither\&.h\fP"
.br
.RI "\fIFunctions for generating dither noise\&. \fP"
.ti -1c
.RI "file \fBpa_dynload\&.c\fP"
.br
.RI "\fIdynamic library helper functions\&. \fP"
.ti -1c
.RI "file \fBpa_dynload\&.h\fP"
.br
.RI "\fIDynamic library helper functions\&. \fP"
.ti -1c
.RI "file \fBpa_endianness\&.h\fP"
.br
.RI "\fIConfigure endianness symbols for the target processor\&. \fP"
.ti -1c
.RI "file \fBpa_front\&.c\fP"
.br
.RI "\fIImplements PortAudio API functions defined in \fBportaudio\&.h\fP, checks some errors, delegates platform-specific behavior to host API implementations\&. \fP"
.ti -1c
.RI "file \fBpa_hostapi\&.h\fP"
.br
.RI "\fIInterfaces and representation structures used by pa_front\&.c to manage and communicate with host API implementations\&. \fP"
.ti -1c
.RI "file \fBpa_memorybarrier\&.h\fP"
.br
.ti -1c
.RI "file \fBpa_process\&.c\fP"
.br
.RI "\fIBuffer Processor implementation\&. \fP"
.ti -1c
.RI "file \fBpa_process\&.h\fP"
.br
.RI "\fIBuffer Processor prototypes\&. A Buffer Processor performs buffer length adaption, coordinates sample format conversion, and interleaves/deinterleaves channels\&. \fP"
.ti -1c
.RI "file \fBpa_ringbuffer\&.c\fP"
.br
.ti -1c
.RI "file \fBpa_ringbuffer\&.h\fP"
.br
.RI "\fISingle-reader single-writer lock-free ring buffer\&. \fP"
.ti -1c
.RI "file \fBpa_stream\&.c\fP"
.br
.RI "\fIStream interfaces, representation structures and helper functions used to interface between pa_front\&.c host API implementations\&. \fP"
.ti -1c
.RI "file \fBpa_stream\&.h\fP"
.br
.RI "\fIStream interfaces, representation structures and helper functions used to interface between pa_front\&.c host API implementations\&. \fP"
.ti -1c
.RI "file \fBpa_svnrevision\&.h\fP"
.br
.ti -1c
.RI "file \fBpa_trace\&.c\fP"
.br
.RI "\fIReal-time safe event trace logging facility for debugging\&. \fP"
.ti -1c
.RI "file \fBpa_trace\&.h\fP"
.br
.RI "\fIReal-time safe event trace logging facility for debugging\&. \fP"
.ti -1c
.RI "file \fBpa_types\&.h\fP"
.br
.RI "\fIDefinition of 16 and 32 bit integer types (PaInt16, PaInt32 etc) \fP"
.ti -1c
.RI "file \fBpa_util\&.h\fP"
.br
.RI "\fIPrototypes for utility functions used by PortAudio implementations\&. \fP"
.in -1c
