.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBModTrackPanelCallback\&.cpp\fP"
.br
.ti -1c
.RI "file \fBModTrackPanelCallback\&.h\fP"
.br
.ti -1c
.RI "file \fBRegistrar\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRegistrar\&.h\fP"
.br
.ti -1c
.RI "file \fBSkewedRuler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSkewedRuler\&.h\fP"
.br
.ti -1c
.RI "file \fBTrackPanel2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTrackPanel2\&.h\fP"
.br
.in -1c
