.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610 Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadd\&.c\fP"
.br
.ti -1c
.RI "file \fBcode\&.c\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBdecode\&.c\fP"
.br
.ti -1c
.RI "file \fBgsm\&.h\fP"
.br
.ti -1c
.RI "file \fBgsm610_priv\&.h\fP"
.br
.ti -1c
.RI "file \fBgsm_create\&.c\fP"
.br
.ti -1c
.RI "file \fBgsm_decode\&.c\fP"
.br
.ti -1c
.RI "file \fBgsm_destroy\&.c\fP"
.br
.ti -1c
.RI "file \fBgsm_encode\&.c\fP"
.br
.ti -1c
.RI "file \fBgsm_option\&.c\fP"
.br
.ti -1c
.RI "file \fBlong_term\&.c\fP"
.br
.ti -1c
.RI "file \fBlpc\&.c\fP"
.br
.ti -1c
.RI "file \fBpreprocess\&.c\fP"
.br
.ti -1c
.RI "file \fBrpe\&.c\fP"
.br
.ti -1c
.RI "file \fBshort_term\&.c\fP"
.br
.ti -1c
.RI "file \fBtable\&.c\fP"
.br
.in -1c
