.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/examples Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAmplitudeFollower\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAmplitudeFollower\&.h\fP"
.br
.ti -1c
.RI "file \fBFixedTempoEstimator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFixedTempoEstimator\&.h\fP"
.br
.ti -1c
.RI "file \fBPercussionOnsetDetector\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPercussionOnsetDetector\&.h\fP"
.br
.ti -1c
.RI "file \fBplugins\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPowerSpectrum\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPowerSpectrum\&.h\fP"
.br
.ti -1c
.RI "file \fBSpectralCentroid\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSpectralCentroid\&.h\fP"
.br
.ti -1c
.RI "file \fBZeroCrossing\&.cpp\fP"
.br
.ti -1c
.RI "file \fBZeroCrossing\&.h\fP"
.br
.in -1c
