.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/nyquist Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/nyquist Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLoadNyquist\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLoadNyquist\&.h\fP"
.br
.ti -1c
.RI "file \fBNyquist\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNyquist\&.h\fP"
.br
.in -1c
