.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libscorealign Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libscorealign Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcompare_transcripts\fP"
.br
.ti -1c
.RI "directory \fBfft3\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalignfiles\&.cpp\fP"
.br
.ti -1c
.RI "file \fBalignfiles\&.h\fP"
.br
.ti -1c
.RI "file \fBaudiofilereader\-snd\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudiofilereader\-snd\&.h\fP"
.br
.ti -1c
.RI "file \fBaudiofilereader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudiofilereader\&.h\fP"
.br
.ti -1c
.RI "file \fBaudioreader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudioreader\&.h\fP"
.br
.ti -1c
.RI "file \fBcomp_chroma\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcomp_chroma\&.h\fP"
.br
.ti -1c
.RI "file \fBcurvefit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcurvefit\&.h\fP"
.br
.ti -1c
.RI "file \fBgen_chroma\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgen_chroma\&.h\fP"
.br
.ti -1c
.RI "file \fBhillclimb\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhillclimb\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.ti -1c
.RI "file \fBregression\&.cpp\fP"
.br
.ti -1c
.RI "file \fBregression\&.h\fP"
.br
.ti -1c
.RI "file \fBsautils\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsautils\&.h\fP"
.br
.ti -1c
.RI "file \fBscorealign\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscorealign\&.h\fP"
.br
.ti -1c
.RI "file \fBtrace\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtrace\&.h\fP"
.br
.in -1c
