.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libmad Directory Reference" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libmad Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmsvc++\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBacconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBbit\&.c\fP"
.br
.ti -1c
.RI "file \fBbit\&.h\fP"
.br
.ti -1c
.RI "file \fBconfigmac\&.h\fP"
.br
.ti -1c
.RI "file \fBconfigunix\&.h\fP"
.br
.ti -1c
.RI "file \fBdecoder\&.c\fP"
.br
.ti -1c
.RI "file \fBdecoder\&.h\fP"
.br
.ti -1c
.RI "file \fBfixed\&.c\fP"
.br
.ti -1c
.RI "file \fBfixed\&.h\fP"
.br
.ti -1c
.RI "file \fBframe\&.c\fP"
.br
.ti -1c
.RI "file \fBframe\&.h\fP"
.br
.ti -1c
.RI "file \fBglobal\&.h\fP"
.br
.ti -1c
.RI "file \fBhuffman\&.c\fP"
.br
.ti -1c
.RI "file \fBhuffman\&.h\fP"
.br
.ti -1c
.RI "file \fBlayer12\&.c\fP"
.br
.ti -1c
.RI "file \fBlayer12\&.h\fP"
.br
.ti -1c
.RI "file \fBlayer3\&.c\fP"
.br
.ti -1c
.RI "file \fBlayer3\&.h\fP"
.br
.ti -1c
.RI "file \fBminimad\&.c\fP"
.br
.ti -1c
.RI "file \fBstream\&.c\fP"
.br
.ti -1c
.RI "file \fBstream\&.h\fP"
.br
.ti -1c
.RI "file \fBsynth\&.c\fP"
.br
.ti -1c
.RI "file \fBsynth\&.h\fP"
.br
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.c\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.in -1c
