.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Tools/c_aliases.py" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Tools/c_aliases.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwaflib\&.Tools\&.c_aliases\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.get_extensions\fP (lst)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.sniff_features\fP (kw)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.set_features\fP (kw, _type)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.program\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.shlib\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.stlib\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.c_aliases\&.objects\fP (bld, \fBk\fP, kw)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
