.TH "cache_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBvalue_ptr\fP \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBcache_struct\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 187 of file readbinaryplist\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint64_t\fP cache_struct::key"

.PP
Definition at line 188 of file readbinaryplist\&.c\&.
.SS "struct \fBcache_struct\fP* cache_struct::next"

.PP
Definition at line 190 of file readbinaryplist\&.c\&.
.SS "\fBvalue_ptr\fP cache_struct::value"

.PP
Definition at line 189 of file readbinaryplist\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
