.TH "call_args_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
call_args_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timebase\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBarg\fP [\fBMAX_CALL_ARGS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file timebase\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long call_args_struct::arg[\fBMAX_CALL_ARGS\fP]"

.PP
Definition at line 12 of file timebase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
