.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/vq/cascade.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/vq/cascade.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'bookutil\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBprocess_preprocess\fP (\fBcodebook\fP **bs, char *basename)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprocess_postprocess\fP (\fBcodebook\fP **\fBb\fP, char *basename)"
.br
.ti -1c
.RI "float \fBprocess_one\fP (\fBcodebook\fP *\fBb\fP, float *\fBa\fP, \fBint\fP dim, \fBint\fP step, \fBint\fP addmul, float \fBbase\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprocess_vector\fP (\fBcodebook\fP **bs, \fBint\fP *addmul, \fBint\fP inter, float *\fBa\fP, \fBint\fP n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprocess_usage\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBcount\fP =0\&.\fBf\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float process_one (\fBcodebook\fP * b, float * a, \fBint\fP dim, \fBint\fP step, \fBint\fP addmul, float base)"

.PP
Definition at line 37 of file cascade\&.c\&.
.SS "\fBvoid\fP process_postprocess (\fBcodebook\fP ** b, char * basename)"

.PP
Definition at line 33 of file cascade\&.c\&.
.SS "\fBvoid\fP process_preprocess (\fBcodebook\fP ** bs, char * basename)"

.PP
Definition at line 30 of file cascade\&.c\&.
.SS "\fBvoid\fP process_usage (\fBvoid\fP)"

.PP
Definition at line 84 of file cascade\&.c\&.
.SS "\fBvoid\fP process_vector (\fBcodebook\fP ** bs, \fBint\fP * addmul, \fBint\fP inter, float * a, \fBint\fP n)"

.PP
Definition at line 55 of file cascade\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "float count =0\&.\fBf\fP"

.PP
Definition at line 27 of file cascade\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
