.TH "cause_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cause_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <seq\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBseq_arg_struct\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP(* \fBroutine\fP )()"
.br
.ti -1c
.RI "struct \fBcause_struct::seq_arg_struct\fP \fBargs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file seq\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBcause_struct::seq_arg_struct\fP  cause_struct::args"

.SS "\fBint\fP(* cause_struct::routine) ()"

.PP
Definition at line 75 of file seq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
