.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/expat/tests/chardata.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/expat/tests/chardata.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minicheck\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'chardata\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBCharData_Init\fP (\fBCharData\fP *storage)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCharData_AppendString\fP (\fBCharData\fP *storage, \fBconst\fP char *\fBs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCharData_AppendXMLChars\fP (\fBCharData\fP *storage, \fBconst\fP \fBXML_Char\fP *\fBs\fP, \fBint\fP \fBlen\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBCharData_CheckString\fP (\fBCharData\fP *storage, \fBconst\fP char *expected)"
.br
.ti -1c
.RI "\fBint\fP \fBCharData_CheckXMLChars\fP (\fBCharData\fP *storage, \fBconst\fP \fBXML_Char\fP *expected)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP CharData_AppendString (\fBCharData\fP * storage, \fBconst\fP char * s)"

.PP
Definition at line 42 of file chardata\&.c\&.
.SS "\fBvoid\fP CharData_AppendXMLChars (\fBCharData\fP * storage, \fBconst\fP \fBXML_Char\fP * s, \fBint\fP len)"

.PP
Definition at line 61 of file chardata\&.c\&.
.SS "\fBint\fP CharData_CheckString (\fBCharData\fP * storage, \fBconst\fP char * expected)"

.PP
Definition at line 83 of file chardata\&.c\&.
.SS "\fBint\fP CharData_CheckXMLChars (\fBCharData\fP * storage, \fBconst\fP \fBXML_Char\fP * expected)"

.PP
Definition at line 112 of file chardata\&.c\&.
.SS "\fBvoid\fP CharData_Init (\fBCharData\fP * storage)"

.PP
Definition at line 35 of file chardata\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
