.TH "cleanup_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cleanup_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcleanup_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBcu_fn_type\fP \fBfn\fP"
.br
.ti -1c
.RI "\fBcu_parm_type\fP \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file cleanup\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcu_fn_type\fP cleanup_struct::fn"

.PP
Definition at line 8 of file cleanup\&.c\&.
.SS "struct \fBcleanup_struct\fP* cleanup_struct::next"

.PP
Definition at line 7 of file cleanup\&.c\&.
.SS "\fBcu_parm_type\fP cleanup_struct::obj"

.PP
Definition at line 9 of file cleanup\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
