.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cleanup.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cleanup.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLEANUP\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvoid\fP * \fBcu_parm_type\fP"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBcu_fn_type\fP) (\fBcu_parm_type\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcu_register\fP (\fBcu_fn_type\fP \fBfn\fP, \fBcu_parm_type\fP obj)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcu_unregister\fP (\fBvoid\fP *obj)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcu_cleanup\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEANUP"

.PP
Definition at line 9 of file cleanup\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvoid\fP(* cu_fn_type) (\fBcu_parm_type\fP)"

.PP
Definition at line 4 of file cleanup\&.h\&.
.SS "typedef \fBvoid\fP* \fBcu_parm_type\fP"

.PP
Definition at line 3 of file cleanup\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP cu_cleanup (\fBvoid\fP)"

.PP
Definition at line 46 of file cleanup\&.c\&.
.SS "\fBvoid\fP cu_register (\fBcu_fn_type\fP fn, \fBcu_parm_type\fP obj)"

.PP
Definition at line 16 of file cleanup\&.c\&.
.SS "\fBvoid\fP cu_unregister (\fBvoid\fP * obj)"

.PP
Definition at line 28 of file cleanup\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
