.TH "clock_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clock_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <seq\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtime_type\fP \fBticksize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file seq\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtime_type\fP clock_struct::ticksize"

.PP
Definition at line 18 of file seq\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
