.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cmdline.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cmdline.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'userio\&.h'\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'ctype\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsyntax_max\fP   10           /* allow \fBfor\fP 10 \fBsyntax\fP strings */"
.br
.ti -1c
.RI "#define \fBcl_OPT\fP   1"
.br
.ti -1c
.RI "#define \fBcl_SW\fP   2"
.br
.ti -1c
.RI "#define \fBcl_INIT\fP   3"
.br
.ti -1c
.RI "#define \fBcl_ARG\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBok_to_open\fP (\fBconst\fP char *\fBfilename\fP, \fBconst\fP char *mode)"
.br
.ti -1c
.RI "\fBprivate\fP char * \fBcl_search\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBint\fP \fBfind_string\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBindirect_command\fP (char *\fBfilename\fP, char *oldarg0)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBready_check\fP ()"
.br
.ti -1c
.RI "char * \fBcl_arg\fP (\fBint\fP n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcl_help\fP ()"
.br
.ti -1c
.RI "\fBboolean\fP \fBcl_init\fP (av, \fBint\fP ac)"
.br
.ti -1c
.RI "long \fBcl_int_option\fP (char *\fBname\fP, long deflt)"
.br
.ti -1c
.RI "\fBprivate\fP char * \fBcl_search\fP (char *\fBname\fP, \fBint\fP opt_sw, \fBint\fP n)"
.br
.ti -1c
.RI "char * \fBcl_option\fP (char *\fBname\fP)"
.br
.ti -1c
.RI "\fBboolean\fP \fBcl_switch\fP (char *\fBname\fP)"
.br
.ti -1c
.RI "\fBboolean\fP \fBcl_syntax\fP (char *\fBs\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBint\fP \fBfind_string\fP (char *\fBs\fP, \fBboolean\fP *abbr)"
.br
.ti -1c
.RI "\fBboolean\fP \fBget_arg\fP (FILE *file, char *arg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBprivate\fP char * \fBsyntax\fP [\fBsyntax_max\fP]"
.br
.ti -1c
.RI "\fBprivate\fP \fBint\fP \fBn_syntax\fP = 0"
.br
.ti -1c
.RI "\fBprivate\fP char ** \fBargv\fP"
.br
.ti -1c
.RI "\fBprivate\fP \fBint\fP \fBargc\fP"
.br
.ti -1c
.RI "\fBprivate\fP \fBboolean\fP \fBcl_rdy\fP = \fBFALSE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define cl_ARG   4"

.PP
Definition at line 110 of file cmdline\&.c\&.
.SS "#define cl_INIT   3"

.PP
Definition at line 109 of file cmdline\&.c\&.
.SS "#define cl_OPT   1"

.PP
Definition at line 107 of file cmdline\&.c\&.
.SS "#define cl_SW   2"

.PP
Definition at line 108 of file cmdline\&.c\&.
.SS "#define syntax_max   10           /* allow \fBfor\fP 10 \fBsyntax\fP strings */"

.PP
Definition at line 99 of file cmdline\&.c\&.
.SH "Function Documentation"
.PP 
.SS "char* cl_arg (\fBint\fP n)"

.PP
Definition at line 129 of file cmdline\&.c\&.
.SS "\fBvoid\fP cl_help ()"

.PP
Definition at line 138 of file cmdline\&.c\&.
.SS "\fBboolean\fP cl_init (av, \fBint\fP ac)"

.PP
Definition at line 197 of file cmdline\&.c\&.
.SS "long cl_int_option (char * name, long deflt)"

.PP
Definition at line 231 of file cmdline\&.c\&.
.SS "char* cl_option (char * name)"

.PP
Definition at line 324 of file cmdline\&.c\&.
.SS "\fBprivate\fP char* cl_search ()"

.SS "\fBprivate\fP char* cl_search (char * name, \fBint\fP opt_sw, \fBint\fP n)"

.PP
Definition at line 260 of file cmdline\&.c\&.
.SS "\fBboolean\fP cl_switch (char * name)"

.PP
Definition at line 338 of file cmdline\&.c\&.
.SS "\fBboolean\fP cl_syntax (char * s)"

.PP
Definition at line 346 of file cmdline\&.c\&.
.SS "\fBprivate\fP \fBint\fP find_string ()"

.SS "\fBprivate\fP \fBint\fP find_string (char * s, \fBboolean\fP * abbr)"

.PP
Definition at line 368 of file cmdline\&.c\&.
.SS "\fBboolean\fP get_arg (FILE * file, char * arg)"

.PP
Definition at line 428 of file cmdline\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP indirect_command (char * filename, char * oldarg0)"

.PP
Definition at line 446 of file cmdline\&.c\&.
.SS "\fBint\fP ok_to_open (\fBconst\fP char * filename, \fBconst\fP char * mode)"

.PP
Definition at line 58 of file security\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP ready_check ()"

.PP
Definition at line 481 of file cmdline\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBprivate\fP \fBint\fP argc"

.PP
Definition at line 103 of file cmdline\&.c\&.
.SS "\fBprivate\fP char** argv"

.PP
Definition at line 102 of file cmdline\&.c\&.
.SS "\fBprivate\fP \fBboolean\fP cl_rdy = \fBFALSE\fP"

.PP
Definition at line 105 of file cmdline\&.c\&.
.SS "\fBprivate\fP \fBint\fP n_syntax = 0"

.PP
Definition at line 101 of file cmdline\&.c\&.
.SS "\fBprivate\fP char* syntax[\fBsyntax_max\fP]"

.PP
Definition at line 100 of file cmdline\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
