.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cmtcmd.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/cmtcmd.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hash\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsymb_descr\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBvar_symb_type\fP   333"
.br
.ti -1c
.RI "#define \fBfn_symb_type\fP   555"
.br
.ti -1c
.RI "#define \fBvec_symb_type\fP   777"
.br
.ti -1c
.RI "#define \fBHASHTYPE\fP   \fBsymb_descr_node\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsymb_descr\fP \fBsymb_descr_node\fP"
.br
.ti -1c
.RI "typedef \fBint\fP(* \fBdefun_type\fP) ()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBlookup\fP (char *\fBs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdefvar\fP (char *\fBname\fP, \fBint\fP *addr)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdefvec\fP (char *\fBname\fP, \fBint\fP *addr, \fBint\fP \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdefun\fP (char *\fBname\fP, \fBdefun_type\fP addr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define fn_symb_type   555"

.PP
Definition at line 4 of file cmtcmd\&.h\&.
.SS "#define HASHTYPE   \fBsymb_descr_node\fP"

.PP
Definition at line 34 of file cmtcmd\&.h\&.
.SS "#define var_symb_type   333"

.PP
Definition at line 3 of file cmtcmd\&.h\&.
.SS "#define vec_symb_type   777"

.PP
Definition at line 5 of file cmtcmd\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint\fP(* defun_type) ()"

.PP
Definition at line 31 of file cmtcmd\&.h\&.
.SS "typedef struct \fBsymb_descr\fP  \fBsymb_descr_node\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP defun (char * name, \fBdefun_type\fP addr)"

.PP
Definition at line 32 of file cmtcmd\&.c\&.
.SS "\fBvoid\fP defvar (char * name, \fBint\fP * addr)"

.PP
Definition at line 22 of file cmtcmd\&.c\&.
.SS "\fBvoid\fP defvec (char * name, \fBint\fP * addr, \fBint\fP size)"

.PP
Definition at line 42 of file cmtcmd\&.c\&.
.SS "\fBint\fP lookup (char * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
