.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/include/vorbis/codec.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/include/vorbis/codec.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ogg/ogg\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvorbis_info\fP"
.br
.ti -1c
.RI "struct \fBvorbis_dsp_state\fP"
.br
.ti -1c
.RI "struct \fBvorbis_block\fP"
.br
.ti -1c
.RI "struct \fBalloc_chain\fP"
.br
.ti -1c
.RI "struct \fBvorbis_comment\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOV_FALSE\fP   \-1"
.br
.ti -1c
.RI "#define \fBOV_EOF\fP   \-2"
.br
.ti -1c
.RI "#define \fBOV_HOLE\fP   \-3"
.br
.ti -1c
.RI "#define \fBOV_EREAD\fP   \-128"
.br
.ti -1c
.RI "#define \fBOV_EFAULT\fP   \-129"
.br
.ti -1c
.RI "#define \fBOV_EIMPL\fP   \-130"
.br
.ti -1c
.RI "#define \fBOV_EINVAL\fP   \-131"
.br
.ti -1c
.RI "#define \fBOV_ENOTVORBIS\fP   \-132"
.br
.ti -1c
.RI "#define \fBOV_EBADHEADER\fP   \-133"
.br
.ti -1c
.RI "#define \fBOV_EVERSION\fP   \-134"
.br
.ti -1c
.RI "#define \fBOV_ENOTAUDIO\fP   \-135"
.br
.ti -1c
.RI "#define \fBOV_EBADPACKET\fP   \-136"
.br
.ti -1c
.RI "#define \fBOV_EBADLINK\fP   \-137"
.br
.ti -1c
.RI "#define \fBOV_ENOSEEK\fP   \-138"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBvorbis_info\fP \fBvorbis_info\fP"
.br
.ti -1c
.RI "typedef struct \fBvorbis_dsp_state\fP \fBvorbis_dsp_state\fP"
.br
.ti -1c
.RI "typedef struct \fBvorbis_block\fP \fBvorbis_block\fP"
.br
.ti -1c
.RI "typedef struct \fBvorbis_comment\fP \fBvorbis_comment\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBvorbis_info_init\fP (\fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_info_clear\fP (\fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_info_blocksize\fP (\fBvorbis_info\fP *vi, \fBint\fP zo)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_comment_init\fP (\fBvorbis_comment\fP *vc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_comment_add\fP (\fBvorbis_comment\fP *vc, \fBconst\fP char *comment)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_comment_add_tag\fP (\fBvorbis_comment\fP *vc, \fBconst\fP char *\fBtag\fP, \fBconst\fP char *contents)"
.br
.ti -1c
.RI "char * \fBvorbis_comment_query\fP (\fBvorbis_comment\fP *vc, \fBconst\fP char *\fBtag\fP, \fBint\fP \fBcount\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_comment_query_count\fP (\fBvorbis_comment\fP *vc, \fBconst\fP char *\fBtag\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_comment_clear\fP (\fBvorbis_comment\fP *vc)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_block_init\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_block_clear\fP (\fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvorbis_dsp_clear\fP (\fBvorbis_dsp_state\fP *v)"
.br
.ti -1c
.RI "double \fBvorbis_granule_time\fP (\fBvorbis_dsp_state\fP *v, \fBogg_int64_t\fP granulepos)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBvorbis_version_string\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_analysis_init\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_commentheader_out\fP (\fBvorbis_comment\fP *vc, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_analysis_headerout\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_comment\fP *vc, \fBogg_packet\fP *op, \fBogg_packet\fP *op_comm, \fBogg_packet\fP *op_code)"
.br
.ti -1c
.RI "float ** \fBvorbis_analysis_buffer\fP (\fBvorbis_dsp_state\fP *v, \fBint\fP vals)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_analysis_wrote\fP (\fBvorbis_dsp_state\fP *v, \fBint\fP vals)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_analysis_blockout\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_analysis\fP (\fBvorbis_block\fP *vb, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_bitrate_addblock\fP (\fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_bitrate_flushpacket\fP (\fBvorbis_dsp_state\fP *vd, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_idheader\fP (\fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_headerin\fP (\fBvorbis_info\fP *vi, \fBvorbis_comment\fP *vc, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_init\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_restart\fP (\fBvorbis_dsp_state\fP *v)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis\fP (\fBvorbis_block\fP *vb, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_trackonly\fP (\fBvorbis_block\fP *vb, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_blockin\fP (\fBvorbis_dsp_state\fP *v, \fBvorbis_block\fP *vb)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_pcmout\fP (\fBvorbis_dsp_state\fP *v, float ***pcm)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_lapout\fP (\fBvorbis_dsp_state\fP *v, float ***pcm)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_read\fP (\fBvorbis_dsp_state\fP *v, \fBint\fP \fBsamples\fP)"
.br
.ti -1c
.RI "long \fBvorbis_packet_blocksize\fP (\fBvorbis_info\fP *vi, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_halfrate\fP (\fBvorbis_info\fP *v, \fBint\fP flag)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_halfrate_p\fP (\fBvorbis_info\fP *v)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OV_EBADHEADER   \-133"

.PP
Definition at line 231 of file codec\&.h\&.
.SS "#define OV_EBADLINK   \-137"

.PP
Definition at line 235 of file codec\&.h\&.
.SS "#define OV_EBADPACKET   \-136"

.PP
Definition at line 234 of file codec\&.h\&.
.SS "#define OV_EFAULT   \-129"

.PP
Definition at line 227 of file codec\&.h\&.
.SS "#define OV_EIMPL   \-130"

.PP
Definition at line 228 of file codec\&.h\&.
.SS "#define OV_EINVAL   \-131"

.PP
Definition at line 229 of file codec\&.h\&.
.SS "#define OV_ENOSEEK   \-138"

.PP
Definition at line 236 of file codec\&.h\&.
.SS "#define OV_ENOTAUDIO   \-135"

.PP
Definition at line 233 of file codec\&.h\&.
.SS "#define OV_ENOTVORBIS   \-132"

.PP
Definition at line 230 of file codec\&.h\&.
.SS "#define OV_EOF   \-2"

.PP
Definition at line 223 of file codec\&.h\&.
.SS "#define OV_EREAD   \-128"

.PP
Definition at line 226 of file codec\&.h\&.
.SS "#define OV_EVERSION   \-134"

.PP
Definition at line 232 of file codec\&.h\&.
.SS "#define OV_FALSE   \-1"

.PP
Definition at line 222 of file codec\&.h\&.
.SS "#define OV_HOLE   \-3"

.PP
Definition at line 224 of file codec\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBvorbis_block\fP  \fBvorbis_block\fP"

.SS "typedef struct \fBvorbis_comment\fP  \fBvorbis_comment\fP"

.SS "typedef struct \fBvorbis_dsp_state\fP  \fBvorbis_dsp_state\fP"

.SS "typedef struct \fBvorbis_info\fP  \fBvorbis_info\fP"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP vorbis_analysis (\fBvorbis_block\fP * vb, \fBogg_packet\fP * op)"

.PP
Definition at line 30 of file analysis\&.c\&.
.SS "\fBint\fP vorbis_analysis_blockout (\fBvorbis_dsp_state\fP * v, \fBvorbis_block\fP * vb)"

.PP
Definition at line 524 of file block\&.c\&.
.SS "float** vorbis_analysis_buffer (\fBvorbis_dsp_state\fP * v, \fBint\fP vals)"

.PP
Definition at line 389 of file block\&.c\&.
.SS "\fBint\fP vorbis_analysis_headerout (\fBvorbis_dsp_state\fP * v, \fBvorbis_comment\fP * vc, \fBogg_packet\fP * op, \fBogg_packet\fP * op_comm, \fBogg_packet\fP * op_code)"

.PP
Definition at line 571 of file info\&.c\&.
.SS "\fBint\fP vorbis_analysis_init (\fBvorbis_dsp_state\fP * v, \fBvorbis_info\fP * vi)"

.PP
Definition at line 295 of file block\&.c\&.
.SS "\fBint\fP vorbis_analysis_wrote (\fBvorbis_dsp_state\fP * v, \fBint\fP vals)"

.PP
Definition at line 460 of file block\&.c\&.
.SS "\fBint\fP vorbis_bitrate_addblock (\fBvorbis_block\fP * vb)"

.PP
Definition at line 74 of file bitrate\&.c\&.
.SS "\fBint\fP vorbis_bitrate_flushpacket (\fBvorbis_dsp_state\fP * vd, \fBogg_packet\fP * op)"

.PP
Definition at line 230 of file bitrate\&.c\&.
.SS "\fBint\fP vorbis_block_clear (\fBvorbis_block\fP * vb)"

.PP
Definition at line 159 of file block\&.c\&.
.SS "\fBint\fP vorbis_block_init (\fBvorbis_dsp_state\fP * v, \fBvorbis_block\fP * vb)"

.PP
Definition at line 88 of file block\&.c\&.
.SS "\fBvoid\fP vorbis_comment_add (\fBvorbis_comment\fP * vc, \fBconst\fP char * comment)"

.PP
Definition at line 65 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_comment_add_tag (\fBvorbis_comment\fP * vc, \fBconst\fP char * tag, \fBconst\fP char * contents)"

.PP
Definition at line 77 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_comment_clear (\fBvorbis_comment\fP * vc)"

.PP
Definition at line 133 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_comment_init (\fBvorbis_comment\fP * vc)"

.PP
Definition at line 61 of file info\&.c\&.
.SS "char* vorbis_comment_query (\fBvorbis_comment\fP * vc, \fBconst\fP char * tag, \fBint\fP count)"

.PP
Definition at line 97 of file info\&.c\&.
.SS "\fBint\fP vorbis_comment_query_count (\fBvorbis_comment\fP * vc, \fBconst\fP char * tag)"

.PP
Definition at line 118 of file info\&.c\&.
.SS "\fBint\fP vorbis_commentheader_out (\fBvorbis_comment\fP * vc, \fBogg_packet\fP * op)"

.PP
Definition at line 547 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_dsp_clear (\fBvorbis_dsp_state\fP * v)"

.PP
Definition at line 315 of file block\&.c\&.
.SS "double vorbis_granule_time (\fBvorbis_dsp_state\fP * v, \fBogg_int64_t\fP granulepos)"

.PP
Definition at line 651 of file info\&.c\&.
.SS "\fBint\fP vorbis_info_blocksize (\fBvorbis_info\fP * vi, \fBint\fP zo)"

.PP
Definition at line 149 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_info_clear (\fBvorbis_info\fP * vi)"

.PP
Definition at line 160 of file info\&.c\&.
.SS "\fBvoid\fP vorbis_info_init (\fBvorbis_info\fP * vi)"

.PP
Definition at line 155 of file info\&.c\&.
.SS "long vorbis_packet_blocksize (\fBvorbis_info\fP * vi, \fBogg_packet\fP * op)"

.PP
Definition at line 143 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis (\fBvorbis_block\fP * vb, \fBogg_packet\fP * op)"

.PP
Definition at line 26 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_blockin (\fBvorbis_dsp_state\fP * v, \fBvorbis_block\fP * vb)"

.PP
Definition at line 721 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_halfrate (\fBvorbis_info\fP * v, \fBint\fP flag)"

.PP
Definition at line 171 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_halfrate_p (\fBvorbis_info\fP * v)"

.PP
Definition at line 181 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_headerin (\fBvorbis_info\fP * vi, \fBvorbis_comment\fP * vc, \fBogg_packet\fP * op)"

.PP
Definition at line 379 of file info\&.c\&.
.SS "\fBint\fP vorbis_synthesis_idheader (\fBogg_packet\fP * op)"

.PP
Definition at line 350 of file info\&.c\&.
.SS "\fBint\fP vorbis_synthesis_init (\fBvorbis_dsp_state\fP * v, \fBvorbis_info\fP * vi)"

.PP
Definition at line 708 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_lapout (\fBvorbis_dsp_state\fP * v, float *** pcm)"

.PP
Definition at line 963 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_pcmout (\fBvorbis_dsp_state\fP * v, float *** pcm)"

.PP
Definition at line 937 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_read (\fBvorbis_dsp_state\fP * v, \fBint\fP samples)"

.PP
Definition at line 952 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_restart (\fBvorbis_dsp_state\fP * v)"

.PP
Definition at line 685 of file block\&.c\&.
.SS "\fBint\fP vorbis_synthesis_trackonly (\fBvorbis_block\fP * vb, \fBogg_packet\fP * op)"

.PP
Definition at line 94 of file synthesis\&.c\&.
.SS "\fBconst\fP char* vorbis_version_string (\fBvoid\fP)"

.PP
Definition at line 666 of file info\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
