.TH "codebook" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
codebook \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codebook\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBdim\fP"
.br
.ti -1c
.RI "long \fBentries\fP"
.br
.ti -1c
.RI "long \fBused_entries\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBstatic_codebook\fP * \fBc\fP"
.br
.ti -1c
.RI "float * \fBvaluelist\fP"
.br
.ti -1c
.RI "\fBogg_uint32_t\fP * \fBcodelist\fP"
.br
.ti -1c
.RI "\fBint\fP * \fBdec_index\fP"
.br
.ti -1c
.RI "char * \fBdec_codelengths\fP"
.br
.ti -1c
.RI "\fBogg_uint32_t\fP * \fBdec_firsttable\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdec_firsttablen\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdec_maxlength\fP"
.br
.ti -1c
.RI "\fBint\fP \fBquantvals\fP"
.br
.ti -1c
.RI "\fBint\fP \fBminval\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdelta\fP"
.br
.ti -1c
.RI "\fBstatic_codebook\fP * \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file codebook\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBstatic_codebook\fP* codebook::c"

.PP
Definition at line 62 of file codebook\&.h\&.
.SS "\fBstatic_codebook\fP* codebook::c"

.PP
Definition at line 62 of file localcodebook\&.h\&.
.SS "\fBogg_uint32_t\fP * codebook::codelist"

.PP
Definition at line 68 of file codebook\&.h\&.
.SS "char * codebook::dec_codelengths"

.PP
Definition at line 71 of file codebook\&.h\&.
.SS "\fBogg_uint32_t\fP * codebook::dec_firsttable"

.PP
Definition at line 72 of file codebook\&.h\&.
.SS "\fBint\fP codebook::dec_firsttablen"

.PP
Definition at line 73 of file codebook\&.h\&.
.SS "\fBint\fP * codebook::dec_index"

.PP
Definition at line 70 of file codebook\&.h\&.
.SS "\fBint\fP codebook::dec_maxlength"

.PP
Definition at line 74 of file codebook\&.h\&.
.SS "\fBint\fP codebook::delta"

.PP
Definition at line 79 of file codebook\&.h\&.
.SS "long codebook::dim"

.PP
Definition at line 59 of file codebook\&.h\&.
.SS "long codebook::entries"

.PP
Definition at line 60 of file codebook\&.h\&.
.SS "\fBint\fP codebook::minval"

.PP
Definition at line 78 of file codebook\&.h\&.
.SS "\fBint\fP codebook::quantvals"

.PP
Definition at line 77 of file codebook\&.h\&.
.SS "long codebook::used_entries"

.PP
Definition at line 61 of file codebook\&.h\&.
.SS "float * codebook::valuelist"

.PP
Definition at line 67 of file codebook\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
