.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/java/c/src/com_portaudio_PortAudio.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/java/c/src/com_portaudio_PortAudio.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'com_portaudio_PortAudio\&.h'\fP
.br
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'jpa_tools\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getVersion\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jstring JNICALL \fBJava_com_portaudio_PortAudio_getVersionText\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT \fBvoid\fP JNICALL \fBJava_com_portaudio_PortAudio_initialize\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT \fBvoid\fP JNICALL \fBJava_com_portaudio_PortAudio_terminate\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getDeviceCount\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT \fBvoid\fP JNICALL \fBJava_com_portaudio_PortAudio_getDeviceInfo\fP (JNIEnv *env, jclass clazz, jint index, jobject deviceInfo)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getHostApiCount\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_hostApiTypeIdToHostApiIndex\fP (JNIEnv *env, jclass clazz, jint hostApiType)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_hostApiDeviceIndexToDeviceIndex\fP (JNIEnv *env, jclass clazz, jint hostApiIndex, jint apiDeviceIndex)"
.br
.ti -1c
.RI "JNIEXPORT \fBvoid\fP JNICALL \fBJava_com_portaudio_PortAudio_getHostApiInfo\fP (JNIEnv *env, jclass clazz, jint index, jobject hostApiInfo)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getDefaultInputDevice\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getDefaultOutputDevice\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_getDefaultHostApi\fP (JNIEnv *env, jclass clazz)"
.br
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_com_portaudio_PortAudio_isFormatSupported\fP (JNIEnv *env, jclass clazz, jobject inParams, jobject outParams, jint sampleRate)"
.br
.ti -1c
.RI "JNIEXPORT \fBvoid\fP JNICALL \fBJava_com_portaudio_PortAudio_openStream\fP (JNIEnv *env, jclass clazz, jobject blockingStream, jobject inParams, jobject outParams, jint sampleRate, jint framesPerBuffer, jint flags)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getDefaultHostApi (JNIEnv * env, jclass clazz)"

.PP
Definition at line 226 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getDefaultInputDevice (JNIEnv * env, jclass clazz)"

.PP
Definition at line 202 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getDefaultOutputDevice (JNIEnv * env, jclass clazz)"

.PP
Definition at line 214 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getDeviceCount (JNIEnv * env, jclass clazz)"

.PP
Definition at line 95 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT \fBvoid\fP JNICALL Java_com_portaudio_PortAudio_getDeviceInfo (JNIEnv * env, jclass clazz, jint index, jobject deviceInfo)"

.PP
Definition at line 107 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getHostApiCount (JNIEnv * env, jclass clazz)"

.PP
Definition at line 138 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT \fBvoid\fP JNICALL Java_com_portaudio_PortAudio_getHostApiInfo (JNIEnv * env, jclass clazz, jint index, jobject hostApiInfo)"

.PP
Definition at line 174 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_getVersion (JNIEnv * env, jclass clazz)"

.PP
Definition at line 49 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jstring JNICALL Java_com_portaudio_PortAudio_getVersionText (JNIEnv * env, jclass clazz)"

.PP
Definition at line 60 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_hostApiDeviceIndexToDeviceIndex (JNIEnv * env, jclass clazz, jint hostApiIndex, jint apiDeviceIndex)"

.PP
Definition at line 162 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_hostApiTypeIdToHostApiIndex (JNIEnv * env, jclass clazz, jint hostApiType)"

.PP
Definition at line 151 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT \fBvoid\fP JNICALL Java_com_portaudio_PortAudio_initialize (JNIEnv * env, jclass clazz)"

.PP
Definition at line 71 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT jint JNICALL Java_com_portaudio_PortAudio_isFormatSupported (JNIEnv * env, jclass clazz, jobject inParams, jobject outParams, jint sampleRate)"

.PP
Definition at line 238 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT \fBvoid\fP JNICALL Java_com_portaudio_PortAudio_openStream (JNIEnv * env, jclass clazz, jobject blockingStream, jobject inParams, jobject outParams, jint sampleRate, jint framesPerBuffer, jint flags)"

.PP
Definition at line 256 of file com_portaudio_PortAudio\&.c\&.
.SS "JNIEXPORT \fBvoid\fP JNICALL Java_com_portaudio_PortAudio_terminate (JNIEnv * env, jclass clazz)"

.PP
Definition at line 83 of file com_portaudio_PortAudio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
