.TH "CommandLineOptions" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandLineOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBpreserve_modtime\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBprefix_with_filename\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fButf8_convert\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBuse_padding\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBcued_seekpoints\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBshow_long_help\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBshow_version\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBapplication_data_format_is_hexdump\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBOperation\fP * \fBoperations\fP"
.br
.ti -1c
.RI "   unsigned \fBnum_operations\fP"
.br
.ti -1c
.RI "   unsigned \fBcapacity\fP"
.br
.ti -1c
.RI "} \fBops\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      unsigned \fBnum_shorthand_ops\fP"
.br
.ti -1c
.RI "      unsigned \fBnum_major_ops\fP"
.br
.ti -1c
.RI "      \fBFLAC__bool\fP \fBhas_block_type\fP"
.br
.ti -1c
.RI "      \fBFLAC__bool\fP \fBhas_except_block_type\fP"
.br
.ti -1c
.RI "   } \fBchecks\fP"
.br
.ti -1c
.RI "   \fBArgument\fP * \fBarguments\fP"
.br
.ti -1c
.RI "   unsigned \fBnum_arguments\fP"
.br
.ti -1c
.RI "   unsigned \fBcapacity\fP"
.br
.ti -1c
.RI "} \fBargs\fP"
.br
.ti -1c
.RI "unsigned \fBnum_files\fP"
.br
.ti -1c
.RI "char ** \fBfilenames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 183 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__bool\fP CommandLineOptions::application_data_format_is_hexdump"

.PP
Definition at line 191 of file options\&.h\&.
.SS "struct { \&.\&.\&. }   CommandLineOptions::args"

.SS "\fBArgument\fP* CommandLineOptions::arguments"

.PP
Definition at line 204 of file options\&.h\&.
.SS "unsigned CommandLineOptions::capacity"

.PP
Definition at line 195 of file options\&.h\&.
.SS "struct { \&.\&.\&. }   CommandLineOptions::checks"

.SS "\fBFLAC__bool\fP CommandLineOptions::cued_seekpoints"

.PP
Definition at line 188 of file options\&.h\&.
.SS "char** CommandLineOptions::filenames"

.PP
Definition at line 209 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::has_block_type"

.PP
Definition at line 201 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::has_except_block_type"

.PP
Definition at line 202 of file options\&.h\&.
.SS "unsigned CommandLineOptions::num_arguments"

.PP
Definition at line 205 of file options\&.h\&.
.SS "unsigned CommandLineOptions::num_files"

.PP
Definition at line 208 of file options\&.h\&.
.SS "unsigned CommandLineOptions::num_major_ops"

.PP
Definition at line 200 of file options\&.h\&.
.SS "unsigned CommandLineOptions::num_operations"

.PP
Definition at line 194 of file options\&.h\&.
.SS "unsigned CommandLineOptions::num_shorthand_ops"

.PP
Definition at line 199 of file options\&.h\&.
.SS "\fBOperation\fP* CommandLineOptions::operations"

.PP
Definition at line 193 of file options\&.h\&.
.SS "struct { \&.\&.\&. }   CommandLineOptions::ops"

.SS "\fBFLAC__bool\fP CommandLineOptions::prefix_with_filename"

.PP
Definition at line 185 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::preserve_modtime"

.PP
Definition at line 184 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::show_long_help"

.PP
Definition at line 189 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::show_version"

.PP
Definition at line 190 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::use_padding"

.PP
Definition at line 187 of file options\&.h\&.
.SS "\fBFLAC__bool\fP CommandLineOptions::utf8_convert"

.PP
Definition at line 186 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
