.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/tests/command_test.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/tests/command_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <sndfile\&.h>\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_LEN\fP   (1<<10)"
.br
.ti -1c
.RI "#define \fBLOG_BUFFER_SIZE\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, char *\fBargv\fP[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_LEN   (1<<10)"

.PP
Definition at line 36 of file command_test\&.c\&.
.SS "#define LOG_BUFFER_SIZE   1024"

.PP
Definition at line 37 of file command_test\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, char * argv[])"

.PP
Definition at line 63 of file command_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
