.TH "CommandHandler" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandHandler \- Contains methods for applying commands that are passed to it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandHandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandHandler\fP (\fBAudacityApp\fP &app)"
.br
.ti -1c
.RI "\fB~CommandHandler\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetProject\fP (\fBAudacityProject\fP *proj)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnReceiveCommand\fP (\fBAppCommandEvent\fP &event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains methods for applying commands that are passed to it\&. 
.PP
Definition at line 24 of file CommandHandler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CommandHandler::CommandHandler (\fBAudacityApp\fP & app)"

.PP
Definition at line 26 of file CommandHandler\&.cpp\&.
.SS "CommandHandler::~CommandHandler ()"

.PP
Definition at line 30 of file CommandHandler\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CommandHandler::OnReceiveCommand (\fBAppCommandEvent\fP & event)"

.PP
Definition at line 41 of file CommandHandler\&.cpp\&.
.SS "\fBvoid\fP CommandHandler::SetProject (\fBAudacityProject\fP * proj)"

.PP
Definition at line 35 of file CommandHandler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
