.TH "CommandType" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandType \- Base class for containing data common to all commands of a given type\&. Also acts as a factory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandType\&.h>\fP
.PP
Inherited by \fBBatchEvalCommandType\fP, \fBCompareAudioCommandType\fP, \fBExecMenuCommandType\fP, \fBExportCommandType\fP, \fBGetAllMenuCommandsType\fP, \fBGetPreferenceCommandType\fP, \fBGetProjectInfoCommandType\fP, \fBGetTrackInfoCommandType\fP, \fBHelpCommandType\fP, \fBImportCommandType\fP, \fBMessageCommandType\fP, \fBOpenProjectCommandType\fP, \fBSaveProjectCommandType\fP, \fBScreenshotCommandType\fP, \fBSelectCommandType\fP, \fBSetPreferenceCommandType\fP, \fBSetProjectInfoCommandType\fP, and \fBSetTrackInfoCommandType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandType\fP ()"
.br
.ti -1c
.RI "virtual \fB~CommandType\fP ()"
.br
.ti -1c
.RI "wxString \fBGetName\fP ()"
.br
.ti -1c
.RI "\fBCommandSignature\fP & \fBGetSignature\fP ()"
.br
.ti -1c
.RI "wxString \fBDescribe\fP ()"
.br
.ti -1c
.RI "virtual wxString \fBBuildName\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBBuildSignature\fP (\fBCommandSignature\fP &signature)=0"
.br
.RI "\fIPostcondition: signature is a 'signature' map containing parameter\&. \fP"
.ti -1c
.RI "virtual \fBCommand\fP * \fBCreate\fP (\fBCommandOutputTarget\fP *\fBtarget\fP)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for containing data common to all commands of a given type\&. Also acts as a factory\&. 
.PP
Definition at line 26 of file CommandType\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CommandType::CommandType ()"

.PP
Definition at line 25 of file CommandType\&.cpp\&.
.SS "CommandType::~CommandType ()\fC [virtual]\fP"

.PP
Definition at line 29 of file CommandType\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual wxString CommandType::BuildName ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSetPreferenceCommandType\fP, \fBExportCommandType\fP, \fBSaveProjectCommandType\fP, \fBBatchEvalCommandType\fP, \fBGetPreferenceCommandType\fP, \fBMessageCommandType\fP, \fBExecMenuCommandType\fP, \fBGetAllMenuCommandsType\fP, \fBScreenshotCommandType\fP, \fBSetProjectInfoCommandType\fP, \fBCompareAudioCommandType\fP, \fBHelpCommandType\fP, \fBImportCommandType\fP, \fBOpenProjectCommandType\fP, \fBGetProjectInfoCommandType\fP, \fBGetTrackInfoCommandType\fP, \fBSelectCommandType\fP, and \fBSetTrackInfoCommandType\fP\&.
.SS "virtual \fBvoid\fP CommandType::BuildSignature (\fBCommandSignature\fP & signature)\fC [pure virtual]\fP"

.PP
Postcondition: signature is a 'signature' map containing parameter\&. 
.PP
Implemented in \fBSetPreferenceCommandType\fP, \fBExportCommandType\fP, \fBSaveProjectCommandType\fP, \fBBatchEvalCommandType\fP, \fBGetPreferenceCommandType\fP, \fBMessageCommandType\fP, \fBExecMenuCommandType\fP, \fBGetAllMenuCommandsType\fP, \fBScreenshotCommandType\fP, \fBSetProjectInfoCommandType\fP, \fBCompareAudioCommandType\fP, \fBHelpCommandType\fP, \fBImportCommandType\fP, \fBOpenProjectCommandType\fP, \fBGetProjectInfoCommandType\fP, \fBGetTrackInfoCommandType\fP, \fBSelectCommandType\fP, and \fBSetTrackInfoCommandType\fP\&.
.SS "virtual \fBCommand\fP* CommandType::Create (\fBCommandOutputTarget\fP * target)\fC [pure virtual]\fP"

.PP
Implemented in \fBSetPreferenceCommandType\fP, \fBExportCommandType\fP, \fBSaveProjectCommandType\fP, \fBBatchEvalCommandType\fP, \fBGetPreferenceCommandType\fP, \fBMessageCommandType\fP, \fBExecMenuCommandType\fP, \fBGetAllMenuCommandsType\fP, \fBScreenshotCommandType\fP, \fBSetProjectInfoCommandType\fP, \fBCompareAudioCommandType\fP, \fBHelpCommandType\fP, \fBImportCommandType\fP, \fBOpenProjectCommandType\fP, \fBGetProjectInfoCommandType\fP, \fBGetTrackInfoCommandType\fP, \fBSelectCommandType\fP, and \fBSetTrackInfoCommandType\fP\&.
.SS "wxString CommandType::Describe ()"

.PP
Definition at line 60 of file CommandType\&.cpp\&.
.SS "wxString CommandType::GetName ()"

.PP
Definition at line 41 of file CommandType\&.cpp\&.
.SS "\fBCommandSignature\fP & CommandType::GetSignature ()"

.PP
Definition at line 50 of file CommandType\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
