.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/compose.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/compose.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_compose\fP (\fBsound_type\fP \fBf\fP, \fBsound_type\fP g)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_compose\fP (\fBsound_type\fP \fBf\fP, \fBsound_type\fP g)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_compose (\fBsound_type\fP f, \fBsound_type\fP g)"

.PP
Definition at line 302 of file compose\&.c\&.
.SS "\fBsound_type\fP snd_make_compose (\fBsound_type\fP f, \fBsound_type\fP g)"

.PP
Definition at line 243 of file compose\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
