.TH "compression_setting_t" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compression_setting_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcompression_setting_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBFLAC__bool\fP \fBt_bool\fP"
.br
.ti -1c
.RI "   unsigned \fBt_unsigned\fP"
.br
.ti -1c
.RI "   \fBconst\fP char * \fBt_string\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file encode\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__bool\fP compression_setting_t::t_bool"

.PP
Definition at line 53 of file encode\&.h\&.
.SS "\fBconst\fP char* compression_setting_t::t_string"

.PP
Definition at line 55 of file encode\&.h\&.
.SS "unsigned compression_setting_t::t_unsigned"

.PP
Definition at line 54 of file encode\&.h\&.
.SS "\fBcompression_setting_type_t\fP compression_setting_t::type"

.PP
Definition at line 51 of file encode\&.h\&.
.SS "union { \&.\&.\&. }   compression_setting_t::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
