.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/compat.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/compat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'id3tag\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBid3_compat\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint\fP \fBid3_compat_func_t\fP(struct \fBid3_frame\fP *, char \fBconst\fP *, \fBid3_byte_t\fP \fBconst\fP *, \fBid3_length_t\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBid3_compat\fP \fBconst\fP * \fBid3_compat_lookup\fP (register char \fBconst\fP *, register unsigned \fBint\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBid3_compat_fixup\fP (struct \fBid3_tag\fP *)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint\fP id3_compat_func_t(struct \fBid3_frame\fP *, char \fBconst\fP *, \fBid3_byte_t\fP \fBconst\fP *, \fBid3_length_t\fP)"

.PP
Definition at line 27 of file compat\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP id3_compat_fixup (struct \fBid3_tag\fP *)"

.PP
Definition at line 405 of file compat\&.c\&.
.SS "struct \fBid3_compat\fP \fBconst\fP* id3_compat_lookup (register char \fBconst\fP *, register unsigned int)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
