.TH "C:/_dev/OpenU/Audacity/audacity/mac/config/i386/lib-src/libogg/include/ogg/config_types.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/mac/config/i386/lib-src/libogg/include/ogg/config_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBINCLUDE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBINCLUDE_SYS_TYPES_H\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint16_t\fP \fBogg_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBuint16_t\fP \fBogg_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBint32_t\fP \fBogg_int32_t\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP \fBogg_uint32_t\fP"
.br
.ti -1c
.RI "typedef \fBint64_t\fP \fBogg_int64_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INCLUDE_INTTYPES_H   1"

.PP
Definition at line 5 of file config_types\&.h\&.
.SS "#define INCLUDE_STDINT_H   1"

.PP
Definition at line 6 of file config_types\&.h\&.
.SS "#define INCLUDE_SYS_TYPES_H   1"

.PP
Definition at line 7 of file config_types\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint16_t\fP \fBogg_int16_t\fP"

.PP
Definition at line 19 of file config_types\&.h\&.
.SS "typedef \fBint32_t\fP \fBogg_int32_t\fP"

.PP
Definition at line 21 of file config_types\&.h\&.
.SS "typedef \fBint64_t\fP \fBogg_int64_t\fP"

.PP
Definition at line 23 of file config_types\&.h\&.
.SS "typedef \fBuint16_t\fP \fBogg_uint16_t\fP"

.PP
Definition at line 20 of file config_types\&.h\&.
.SS "typedef \fBuint32_t\fP \fBogg_uint32_t\fP"

.PP
Definition at line 22 of file config_types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
