.TH "CONTENT_SCAFFOLD" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONTENT_SCAFFOLD \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBXML_Content_Type\fP \fBtype\fP"
.br
.ti -1c
.RI "enum \fBXML_Content_Quant\fP \fBquant\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfirstchild\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlastchild\fP"
.br
.ti -1c
.RI "\fBint\fP \fBchildcnt\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnextsib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP CONTENT_SCAFFOLD::childcnt"

.PP
Definition at line 211 of file xmlparse\&.c\&.
.SS "\fBint\fP CONTENT_SCAFFOLD::firstchild"

.PP
Definition at line 209 of file xmlparse\&.c\&.
.SS "\fBint\fP CONTENT_SCAFFOLD::lastchild"

.PP
Definition at line 210 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* CONTENT_SCAFFOLD::name"

.PP
Definition at line 208 of file xmlparse\&.c\&.
.SS "\fBint\fP CONTENT_SCAFFOLD::nextsib"

.PP
Definition at line 212 of file xmlparse\&.c\&.
.SS "enum \fBXML_Content_Quant\fP CONTENT_SCAFFOLD::quant"

.PP
Definition at line 207 of file xmlparse\&.c\&.
.SS "enum \fBXML_Content_Type\fP CONTENT_SCAFFOLD::type"

.PP
Definition at line 206 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
