.TH "C:/_dev/OpenU/Audacity/audacity/src/CrossFade.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/CrossFade.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CrossFade\&.h'\fP
.br
\fC#include 'SampleFormat\&.h'\fP
.br
\fC#include 'Resample\&.h'\fP
.br
\fC#include 'WaveClip\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
