.TH "DEFAULT_ATTRIBUTE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEFAULT_ATTRIBUTE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBATTRIBUTE_ID\fP * \fBid\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBisCdata\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 241 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBATTRIBUTE_ID\fP* DEFAULT_ATTRIBUTE::id"

.PP
Definition at line 242 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP DEFAULT_ATTRIBUTE::isCdata"

.PP
Definition at line 243 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* DEFAULT_ATTRIBUTE::value"

.PP
Definition at line 244 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
