.TH "Delay" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Delay \- STK non-interpolating delay line class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Delay\&.h>\fP
.SH "Detailed Description"
.PP 
STK non-interpolating delay line class\&. 

This protected \fBFilter\fP subclass implements a non-interpolating digital delay-line\&. A fixed maximum length of 4095 and a delay of zero is set using the default constructor\&. Alternatively, the delay and maximum length can be set during instantiation with an overloaded constructor\&.
.PP
A non-interpolating delay line is typically used in fixed delay-length applications, such as for reverberation\&.
.PP
by Perry R\&. Cook and Gary P\&. Scavone, 1995 - 2005\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
