.TH "DeviceManager" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeviceManager \- A singleton that manages the audio devices known to Audacity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DeviceManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBRescan\fP ()"
.br
.ti -1c
.RI "\fBDeviceSourceMap\fP * \fBGetDefaultOutputDevice\fP (\fBint\fP hostIndex)"
.br
.ti -1c
.RI "\fBDeviceSourceMap\fP * \fBGetDefaultInputDevice\fP (\fBint\fP hostIndex)"
.br
.ti -1c
.RI "\fBconst\fP std::vector< \fBDeviceSourceMap\fP > & \fBGetInputDeviceMaps\fP ()"
.br
.ti -1c
.RI "\fBconst\fP std::vector< \fBDeviceSourceMap\fP > & \fBGetOutputDeviceMaps\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDeviceManager\fP * \fBInstance\fP ()"
.br
.RI "\fIGets the singleton instance\&. \fP"
.ti -1c
.RI "static \fBvoid\fP \fBDestroy\fP ()"
.br
.RI "\fIReleases memory assosiated with the singleton\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceManager\fP ()"
.br
.ti -1c
.RI "virtual \fB~DeviceManager\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBDeviceSourceMap\fP * \fBGetDefaultDevice\fP (\fBint\fP hostIndex, \fBint\fP isInput)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBm_inited\fP"
.br
.ti -1c
.RI "std::vector< \fBDeviceSourceMap\fP > \fBmInputDeviceSourceMaps\fP"
.br
.ti -1c
.RI "std::vector< \fBDeviceSourceMap\fP > \fBmOutputDeviceSourceMaps\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBDeviceManager\fP \fBdm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A singleton that manages the audio devices known to Audacity\&. 
.PP
Definition at line 43 of file DeviceManager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DeviceManager::DeviceManager ()\fC [protected]\fP"

.PP
Definition at line 316 of file DeviceManager\&.cpp\&.
.SS "DeviceManager::~DeviceManager ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 326 of file DeviceManager\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP DeviceManager::Destroy ()\fC [static]\fP"

.PP
Releases memory assosiated with the singleton\&. 
.PP
Definition at line 51 of file DeviceManager\&.cpp\&.
.SS "\fBDeviceSourceMap\fP * DeviceManager::GetDefaultDevice (\fBint\fP hostIndex, \fBint\fP isInput)\fC [protected]\fP"

.PP
Definition at line 80 of file DeviceManager\&.cpp\&.
.SS "\fBDeviceSourceMap\fP * DeviceManager::GetDefaultInputDevice (\fBint\fP hostIndex)"

.PP
Definition at line 104 of file DeviceManager\&.cpp\&.
.SS "\fBDeviceSourceMap\fP * DeviceManager::GetDefaultOutputDevice (\fBint\fP hostIndex)"

.PP
Definition at line 100 of file DeviceManager\&.cpp\&.
.SS "\fBconst\fP std::vector< \fBDeviceSourceMap\fP > & DeviceManager::GetInputDeviceMaps ()"

.PP
Definition at line 56 of file DeviceManager\&.cpp\&.
.SS "\fBconst\fP std::vector< \fBDeviceSourceMap\fP > & DeviceManager::GetOutputDeviceMaps ()"

.PP
Definition at line 62 of file DeviceManager\&.cpp\&.
.SS "\fBvoid\fP DeviceManager::Init ()\fC [protected]\fP"
Does an initial scan\&. Called by GetInputDeviceMaps and GetOutputDeviceMaps when needed\&. 
.PP
Definition at line 331 of file DeviceManager\&.cpp\&.
.SS "\fBDeviceManager\fP * DeviceManager::Instance ()\fC [static]\fP"

.PP
Gets the singleton instance\&. 
.PP
Definition at line 45 of file DeviceManager\&.cpp\&.
.SS "\fBvoid\fP DeviceManager::Rescan ()"
Gets a NEW list of devices by terminating and restarting portaudio Assumes that \fBDeviceManager\fP is only used on the main thread\&. 
.PP
Definition at line 257 of file DeviceManager\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDeviceManager\fP DeviceManager::dm\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 89 of file DeviceManager\&.h\&.
.SS "\fBbool\fP DeviceManager::m_inited\fC [protected]\fP"

.PP
Definition at line 84 of file DeviceManager\&.h\&.
.SS "std::vector<\fBDeviceSourceMap\fP> DeviceManager::mInputDeviceSourceMaps\fC [protected]\fP"

.PP
Definition at line 86 of file DeviceManager\&.h\&.
.SS "std::vector<\fBDeviceSourceMap\fP> DeviceManager::mOutputDeviceSourceMaps\fC [protected]\fP"

.PP
Definition at line 87 of file DeviceManager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
