.TH "DeviceToolBar" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeviceToolBar \- A toobar to allow easier changing of input and output devices \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DeviceToolBar\&.h>\fP
.PP
Inherits \fBToolBar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceToolBar\fP ()"
.br
.RI "\fIMethods for \fBDeviceToolBar\fP\&. \fP"
.ti -1c
.RI "virtual \fB~DeviceToolBar\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreate\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdatePrefs\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBDeinitChildren\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopulate\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBRepaint\fP (wxDC *WXUNUSED(dc)) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBEnableDisableButtons\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBLayout\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnFocus\fP (wxFocusEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnCaptureKey\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnChoice\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBint\fP \fBGetInitialWidth\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBGetMinToolbarWidth\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBShowInputDialog\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBShowOutputDialog\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBShowHostDialog\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBShowChannelsDialog\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRefillCombos\fP ()"
.br
.ti -1c
.RI "\fBDECLARE_CLASS\fP (\fBDeviceToolBar\fP)"
.br
.ti -1c
.RI "\fBDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A toobar to allow easier changing of input and output devices \&. 
.PP
Definition at line 24 of file DeviceToolBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DeviceToolBar::DeviceToolBar ()"

.PP
Methods for \fBDeviceToolBar\fP\&. 
.PP
Definition at line 61 of file DeviceToolBar\&.cpp\&.
.SS "DeviceToolBar::~DeviceToolBar ()\fC [virtual]\fP"

.PP
Definition at line 68 of file DeviceToolBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP DeviceToolBar::Create (wxWindow * parent)\fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 74 of file DeviceToolBar\&.cpp\&.
.SS "DeviceToolBar::DECLARE_CLASS (\fBDeviceToolBar\fP)"

.SS "DeviceToolBar::DECLARE_EVENT_TABLE ()"

.SS "\fBvoid\fP DeviceToolBar::DeinitChildren ()"

.PP
Definition at line 84 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::EnableDisableButtons ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 322 of file DeviceToolBar\&.cpp\&.
.SS "\fBint\fP DeviceToolBar::GetInitialWidth ()\fC [inline]\fP, \fC [virtual]\fP"
When the prefs don't exist this value is used\&. It should be small enough to work on tiny screens 
.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 47 of file DeviceToolBar\&.h\&.
.SS "\fBint\fP DeviceToolBar::GetMinToolbarWidth ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 48 of file DeviceToolBar\&.h\&.
.SS "\fBbool\fP DeviceToolBar::Layout ()\fC [override]\fP"

.PP
Definition at line 367 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::OnCaptureKey (wxCommandEvent & event)"

.PP
Definition at line 200 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::OnChoice (wxCommandEvent & event)"

.PP
Definition at line 720 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::OnFocus (wxFocusEvent & event)"

.PP
Definition at line 186 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::Populate ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 92 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::RefillCombos ()"

.PP
Definition at line 177 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::Repaint (wxDC * WXUNUSEDdc)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 37 of file DeviceToolBar\&.h\&.
.SS "\fBvoid\fP DeviceToolBar::ShowChannelsDialog ()"

.PP
Definition at line 778 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::ShowHostDialog ()"

.PP
Definition at line 774 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::ShowInputDialog ()"

.PP
Definition at line 766 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::ShowOutputDialog ()"

.PP
Definition at line 770 of file DeviceToolBar\&.cpp\&.
.SS "\fBvoid\fP DeviceToolBar::UpdatePrefs ()\fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 220 of file DeviceToolBar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
