.TH "Diags" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diags \- Processing of the macros for recording bad events or performance monitoring\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Processing of the macros for recording bad events or performance monitoring\&. 

The idea of these macros is that we can include them in release code at no risk\&. They
.PP
a) have almost zero performance impact\&. b) will not flood the log with events\&.
.PP
This is achieved by a countdown which stops recording in the log when the countdown is finished\&. The countdwon continues to count down so that we track how many times the event happens\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
