.TH "DigitInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DigitInfo \- \fBDigitInfo\fP is a class used in \fBNumericTextCtrl\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDigitInfo\fP (\fBint\fP _field, \fBint\fP _index, \fBint\fP _pos, wxRect _box)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBfield\fP"
.br
.ti -1c
.RI "\fBint\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpos\fP"
.br
.ti -1c
.RI "wxRect \fBdigitBox\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDigitInfo\fP is a class used in \fBNumericTextCtrl\fP\&. 
.PP
Definition at line 252 of file NumericTextCtrl\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DigitInfo::DigitInfo (\fBint\fP _field, \fBint\fP _index, \fBint\fP _pos, wxRect _box)\fC [inline]\fP"

.PP
Definition at line 255 of file NumericTextCtrl\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "wxRect DigitInfo::digitBox"

.PP
Definition at line 265 of file NumericTextCtrl\&.cpp\&.
.SS "\fBint\fP DigitInfo::field"

.PP
Definition at line 262 of file NumericTextCtrl\&.cpp\&.
.SS "\fBint\fP DigitInfo::index"

.PP
Definition at line 263 of file NumericTextCtrl\&.cpp\&.
.SS "\fBint\fP DigitInfo::pos"

.PP
Definition at line 264 of file NumericTextCtrl\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
