.TH "DirectoriesPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectoriesPrefs \- A \fBPrefsPanel\fP used to select directories\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DirectoriesPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectoriesPrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fB~DirectoriesPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBValidate\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP used to select directories\&. 
.PP
Definition at line 21 of file DirectoriesPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DirectoriesPrefs::DirectoriesPrefs (wxWindow * parent)"

.PP
Definition at line 51 of file DirectoriesPrefs\&.cpp\&.
.SS "DirectoriesPrefs::~DirectoriesPrefs ()"

.PP
Definition at line 59 of file DirectoriesPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP DirectoriesPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 259 of file DirectoriesPrefs\&.cpp\&.
.SS "\fBbool\fP DirectoriesPrefs::Validate ()\fC [override]\fP"

.PP
Definition at line 202 of file DirectoriesPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
