.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/downproto.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/downproto.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'downproto\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdown_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBdown_susp_struct\fP \fBdown_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBdown_susp_struct\fP * \fBdown_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdown_free\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_n_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_s_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_i_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_r_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_toss_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_mark\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdown_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_down\fP (\fBrate_type\fP sr, \fBsound_type\fP \fBs\fP)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_down\fP (\fBrate_type\fP sr, \fBsound_type\fP \fBs\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBdown_susp_struct\fP  \fBdown_susp_node\fP"

.SS "typedef struct \fBdown_susp_struct\fP * \fBdown_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP down_free ()"

.SS "\fBvoid\fP down_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 456 of file downproto\&.c\&.
.SS "\fBvoid\fP down_i_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 210 of file downproto\&.c\&.
.SS "\fBvoid\fP down_mark (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 449 of file downproto\&.c\&.
.SS "\fBvoid\fP down_n_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 35 of file downproto\&.c\&.
.SS "\fBvoid\fP down_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 464 of file downproto\&.c\&.
.SS "\fBvoid\fP down_r_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 317 of file downproto\&.c\&.
.SS "\fBvoid\fP down_s_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 122 of file downproto\&.c\&.
.SS "\fBvoid\fP down_toss_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 428 of file downproto\&.c\&.
.SS "\fBsound_type\fP snd_down (\fBrate_type\fP sr, \fBsound_type\fP s)"

.PP
Definition at line 536 of file downproto\&.c\&.
.SS "\fBsound_type\fP snd_make_down (\fBrate_type\fP sr, \fBsound_type\fP s)"

.PP
Definition at line 473 of file downproto\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
