.TH "EffectUIClientInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectUIClientInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EffectInterface\&.h>\fP
.PP
Inherited by \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~EffectUIClientInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSetHostUI\fP (\fBEffectUIHostInterface\fP *host)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBIsGraphicalUI\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBPopulateUI\fP (wxWindow *parent)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBValidateUI\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBHideUI\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBCloseUI\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBCanExportPresets\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBExportPresets\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBImportPresets\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBHasOptions\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBShowOptions\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file EffectInterface\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual EffectUIClientInterface::~EffectUIClientInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 168 of file EffectInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBbool\fP EffectUIClientInterface::CanExportPresets ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::CloseUI ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, \fBEffectEqualization\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBvoid\fP EffectUIClientInterface::ExportPresets ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::HasOptions ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::HideUI ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBvoid\fP EffectUIClientInterface::ImportPresets ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::IsGraphicalUI ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::PopulateUI (wxWindow * parent)\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, \fBEffectEqualization\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBvoid\fP EffectUIClientInterface::SetHostUI (\fBEffectUIHostInterface\fP * host)\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBvoid\fP EffectUIClientInterface::ShowOptions ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, and \fBLadspaEffect\fP\&.
.SS "virtual \fBbool\fP EffectUIClientInterface::ValidateUI ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEffect\fP, \fBLadspaEffect\fP, and \fBEffectEqualization\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
