.TH "EffectNoiseReduction::Worker" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectNoiseReduction::Worker \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBEffectNoiseReduction::Settings\fP \fBSettings\fP"
.br
.ti -1c
.RI "typedef \fBEffectNoiseReduction::Statistics\fP \fBStatistics\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorker\fP (\fBconst\fP \fBSettings\fP &settings, double sampleRate)"
.br
.ti -1c
.RI "\fB~Worker\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBProcess\fP (\fBEffectNoiseReduction\fP &effect, \fBStatistics\fP &statistics, \fBTrackFactory\fP &factory, \fBSelectedTrackListOfKindIterator\fP &iter, double \fBmT0\fP, double \fBmT1\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 247 of file NoiseReduction\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBEffectNoiseReduction::Settings\fP \fBEffectNoiseReduction::Worker::Settings\fP"

.PP
Definition at line 250 of file NoiseReduction\&.cpp\&.
.SS "typedef \fBEffectNoiseReduction::Statistics\fP \fBEffectNoiseReduction::Worker::Statistics\fP"

.PP
Definition at line 251 of file NoiseReduction\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EffectNoiseReduction::Worker::Worker (\fBconst\fP \fBSettings\fP & settings, double sampleRate)"

.PP
Definition at line 722 of file NoiseReduction\&.cpp\&.
.SS "EffectNoiseReduction::Worker::~Worker ()"

.PP
Definition at line 641 of file NoiseReduction\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP EffectNoiseReduction::Worker::Process (\fBEffectNoiseReduction\fP & effect, \fBStatistics\fP & statistics, \fBTrackFactory\fP & factory, \fBSelectedTrackListOfKindIterator\fP & iter, double mT0, double mT1)"

.PP
Definition at line 649 of file NoiseReduction\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
