.TH "EffectFindClipping" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectFindClipping \- Locates clipping and inserts labels when found\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FindClipping\&.h>\fP
.PP
Inherits \fBEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectFindClipping\fP ()"
.br
.ti -1c
.RI "virtual \fB~EffectFindClipping\fP ()"
.br
.ti -1c
.RI "wxString \fBGetSymbol\fP () override"
.br
.ti -1c
.RI "wxString \fBGetDescription\fP () override"
.br
.ti -1c
.RI "\fBEffectType\fP \fBGetType\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBProcess\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopulateOrExchange\fP (\fBShuttleGui\fP &\fBS\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBTransferDataToWindow\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBTransferDataFromWindow\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Locates clipping and inserts labels when found\&. 
.PP
Definition at line 25 of file FindClipping\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EffectFindClipping::EffectFindClipping ()"

.PP
Definition at line 43 of file FindClipping\&.cpp\&.
.SS "EffectFindClipping::~EffectFindClipping ()\fC [virtual]\fP"

.PP
Definition at line 49 of file FindClipping\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP EffectFindClipping::GetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 74 of file FindClipping\&.cpp\&.
.SS "wxString EffectFindClipping::GetDescription ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 60 of file FindClipping\&.cpp\&.
.SS "wxString EffectFindClipping::GetSymbol ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 55 of file FindClipping\&.cpp\&.
.SS "\fBEffectType\fP EffectFindClipping::GetType ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 67 of file FindClipping\&.cpp\&.
.SS "\fBvoid\fP EffectFindClipping::PopulateOrExchange (\fBShuttleGui\fP & S)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 226 of file FindClipping\&.cpp\&.
.SS "\fBbool\fP EffectFindClipping::Process ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 95 of file FindClipping\&.cpp\&.
.SS "\fBbool\fP EffectFindClipping::SetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 82 of file FindClipping\&.cpp\&.
.SS "\fBbool\fP EffectFindClipping::TransferDataFromWindow ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 253 of file FindClipping\&.cpp\&.
.SS "\fBbool\fP EffectFindClipping::TransferDataToWindow ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 245 of file FindClipping\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
