.TH "Effect" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Effect \- STK abstract effects parent class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Effect\&.h>\fP
.PP
Inherits wxEvtHandler, \fBEffectClientInterface\fP, \fBEffectUIClientInterface\fP, and \fBEffectHostInterface\fP\&.
.PP
Inherited by \fBEffectAmplify\fP, \fBEffectAutoDuck\fP, \fBEffectBassTreble\fP, \fBEffectChangeSpeed\fP, \fBEffectClickRemoval\fP, \fBEffectDtmf\fP, \fBEffectEcho\fP, \fBEffectEqualization\fP, \fBEffectFade\fP, \fBEffectFindClipping\fP, \fBEffectInvert\fP, \fBEffectLeveller\fP, \fBEffectNoise\fP, \fBEffectNoiseReduction\fP, \fBEffectNormalize\fP, \fBEffectPaulstretch\fP, \fBEffectPhaser\fP, \fBEffectRepair\fP, \fBEffectRepeat\fP, \fBEffectReverb\fP, \fBEffectReverse\fP, \fBEffectScienFilter\fP, \fBEffectSimpleMono\fP, \fBEffectStereoToMono\fP, \fBEffectToneGen\fP, \fBEffectTruncSilence\fP, \fBEffectTwoPassSimpleMono\fP, \fBEffectWahwah\fP, \fBGenerator\fP, and \fBNyquistEffect\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddedAnalysisTrack\fP"
.br
.ti -1c
.RI "class \fBModifiedAnalysisTrack\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffect\fP ()"
.br
.ti -1c
.RI "virtual \fB~Effect\fP ()"
.br
.ti -1c
.RI "wxString \fBGetPath\fP () override"
.br
.ti -1c
.RI "wxString \fBGetSymbol\fP () override"
.br
.ti -1c
.RI "wxString \fBGetName\fP () override"
.br
.ti -1c
.RI "wxString \fBGetVendor\fP () override"
.br
.ti -1c
.RI "wxString \fBGetVersion\fP () override"
.br
.ti -1c
.RI "wxString \fBGetDescription\fP () override"
.br
.ti -1c
.RI "\fBEffectType\fP \fBGetType\fP () override"
.br
.ti -1c
.RI "wxString \fBGetFamily\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBIsInteractive\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBIsDefault\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBIsLegacy\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBSupportsRealtime\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBSupportsAutomation\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetHost\fP (\fBEffectHostInterface\fP *host) override"
.br
.ti -1c
.RI "\fBint\fP \fBGetAudioInCount\fP () override"
.br
.ti -1c
.RI "\fBint\fP \fBGetAudioOutCount\fP () override"
.br
.ti -1c
.RI "\fBint\fP \fBGetMidiInCount\fP () override"
.br
.ti -1c
.RI "\fBint\fP \fBGetMidiOutCount\fP () override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBGetLatency\fP () override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBGetTailSize\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSampleRate\fP (\fBsampleCount\fP \fBrate\fP) override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBSetBlockSize\fP (\fBsampleCount\fP maxBlockSize) override"
.br
.ti -1c
.RI "\fBbool\fP \fBIsReady\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBProcessInitialize\fP (\fBsampleCount\fP totalLen, \fBChannelNames\fP chanMap=\fBNULL\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBProcessFinalize\fP () override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBProcessBlock\fP (float **inBlock, float **outBlock, \fBsampleCount\fP blockLen) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeInitialize\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeAddProcessor\fP (\fBint\fP numChannels, float sampleRate) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeFinalize\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeSuspend\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeResume\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeProcessStart\fP () override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBRealtimeProcess\fP (\fBint\fP group, float **inbuf, float **outbuf, \fBsampleCount\fP numSamples) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeProcessEnd\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBShowInterface\fP (wxWindow *parent, \fBbool\fP forceModal=\fBfalse\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadUserPreset\fP (\fBconst\fP wxString &\fBname\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSaveUserPreset\fP (\fBconst\fP wxString &\fBname\fP) override"
.br
.ti -1c
.RI "wxArrayString \fBGetFactoryPresets\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadFactoryPreset\fP (\fBint\fP id) override"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadFactoryDefaults\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetHostUI\fP (\fBEffectUIHostInterface\fP *host) override"
.br
.ti -1c
.RI "\fBbool\fP \fBPopulateUI\fP (wxWindow *parent) override"
.br
.ti -1c
.RI "\fBbool\fP \fBIsGraphicalUI\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBValidateUI\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBHideUI\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBCloseUI\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBCanExportPresets\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBExportPresets\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBImportPresets\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBHasOptions\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBShowOptions\fP () override"
.br
.ti -1c
.RI "double \fBGetDefaultDuration\fP () override"
.br
.ti -1c
.RI "double \fBGetDuration\fP () override"
.br
.ti -1c
.RI "wxString \fBGetDurationFormat\fP () override"
.br
.ti -1c
.RI "virtual wxString \fBGetSelectionFormat\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetDuration\fP (double duration) override"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBPreview\fP () override"
.br
.ti -1c
.RI "wxDialog * \fBCreateUI\fP (wxWindow *parent, \fBEffectUIClientInterface\fP *client) override"
.br
.ti -1c
.RI "wxString \fBGetUserPresetsGroup\fP (\fBconst\fP wxString &\fBname\fP) override"
.br
.ti -1c
.RI "wxString \fBGetCurrentSettingsGroup\fP () override"
.br
.ti -1c
.RI "wxString \fBGetFactoryDefaultsGroup\fP () override"
.br
.ti -1c
.RI "virtual wxString \fBGetSavedStateGroup\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBHasSharedConfigGroup\fP (\fBconst\fP wxString &group) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfigSubgroups\fP (\fBconst\fP wxString &group, wxArrayString &subgroups) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, wxString &\fBvalue\fP, \fBconst\fP wxString &defval=wxEmptyString) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBint\fP &\fBvalue\fP, \fBint\fP defval=0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBbool\fP &\fBvalue\fP, \fBbool\fP defval=\fBfalse\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, float &\fBvalue\fP, float defval=0\&.0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, double &\fBvalue\fP, double defval=0\&.0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBsampleCount\fP &\fBvalue\fP, \fBsampleCount\fP defval=0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP wxString &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBint\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBbool\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP float &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP double &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBsampleCount\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRemoveSharedConfigSubgroup\fP (\fBconst\fP wxString &group) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRemoveSharedConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key) override"
.br
.ti -1c
.RI "\fBbool\fP \fBHasPrivateConfigGroup\fP (\fBconst\fP wxString &group) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfigSubgroups\fP (\fBconst\fP wxString &group, wxArrayString &subgroups) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, wxString &\fBvalue\fP, \fBconst\fP wxString &defval=wxEmptyString) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBint\fP &\fBvalue\fP, \fBint\fP defval=0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBbool\fP &\fBvalue\fP, \fBbool\fP defval=\fBfalse\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, float &\fBvalue\fP, float defval=0\&.0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, double &\fBvalue\fP, double defval=0\&.0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBsampleCount\fP &\fBvalue\fP, \fBsampleCount\fP defval=0) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP wxString &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBint\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBbool\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP float &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP double &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBsampleCount\fP &\fBvalue\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRemovePrivateConfigSubgroup\fP (\fBconst\fP wxString &group) override"
.br
.ti -1c
.RI "\fBbool\fP \fBRemovePrivateConfig\fP (\fBconst\fP wxString &group, \fBconst\fP wxString &key) override"
.br
.ti -1c
.RI "virtual \fBPluginID\fP \fBGetID\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBStartup\fP (\fBEffectClientInterface\fP *client)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBStartup\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetAutomationParameters\fP (wxString &parms)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetAutomationParameters\fP (\fBconst\fP wxString &parms)"
.br
.ti -1c
.RI "virtual wxArrayString \fBGetUserPresets\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBHasCurrentSettings\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBHasFactoryDefaults\fP ()"
.br
.ti -1c
.RI "virtual wxString \fBGetPreset\fP (wxWindow *parent, \fBconst\fP wxString &parms)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBIsBatchProcessing\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBSetBatchProcessing\fP (\fBbool\fP \fBstart\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPresetParameters\fP (\fBconst\fP wxArrayString *Names, \fBconst\fP wxArrayString *Values)"
.br
.ti -1c
.RI "\fBbool\fP \fBDoEffect\fP (wxWindow *parent, double projectRate, \fBTrackList\fP *list, \fBTrackFactory\fP *factory, \fBSelectedRegion\fP *selectedRegion, \fBbool\fP shouldPrompt=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBRealtimeAddProcessor\fP (\fBint\fP group, \fBint\fP chans, float \fBrate\fP)"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBRealtimeProcess\fP (\fBint\fP group, \fBint\fP chans, float **inbuf, float **outbuf, \fBsampleCount\fP numSamples)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsRealtimeActive\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBIsHidden\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBbool\fP \fBInit\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBPromptUser\fP (wxWindow *parent)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBCheckWhetherSkipEffect\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBProcess\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBProcessPass\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBInitPass1\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBInitPass2\fP ()"
.br
.ti -1c
.RI "virtual \fBint\fP \fBGetPass\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBEnd\fP ()"
.br
.ti -1c
.RI "virtual double \fBCalcPreviewInputLength\fP (double previewLength)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBPreview\fP (\fBbool\fP dryOnly)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBPopulateOrExchange\fP (\fBShuttleGui\fP &\fBS\fP)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBTransferDataToWindow\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBTransferDataFromWindow\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBEnableApply\fP (\fBbool\fP enable=\fBtrue\fP)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBEnablePreview\fP (\fBbool\fP enable=\fBtrue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBEnableDebug\fP (\fBbool\fP enable=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBTotalProgress\fP (double frac)"
.br
.ti -1c
.RI "\fBbool\fP \fBTrackProgress\fP (\fBint\fP whichTrack, double frac, \fBconst\fP wxString &=wxEmptyString)"
.br
.ti -1c
.RI "\fBbool\fP \fBTrackGroupProgress\fP (\fBint\fP whichGroup, double frac, \fBconst\fP wxString &=wxEmptyString)"
.br
.ti -1c
.RI "\fBint\fP \fBGetNumWaveTracks\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBGetNumWaveGroups\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBGetSamples\fP (\fBWaveTrack\fP *track, \fBsampleCount\fP *\fBstart\fP, \fBsampleCount\fP *\fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetTimeWarper\fP (\fBTimeWarper\fP *warper)"
.br
.ti -1c
.RI "\fBTimeWarper\fP * \fBGetTimeWarper\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetLinearEffectFlag\fP (\fBbool\fP linearEffectFlag)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPreviewFullSelectionFlag\fP (\fBbool\fP previewDurationFlag)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsPreviewing\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBIncludeNotSelectedPreviewTracks\fP (\fBbool\fP includeNotSelected)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyInputTracks\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCopyInputTracks\fP (\fBint\fP trackType)"
.br
.ti -1c
.RI "std::shared_ptr< \fBAddedAnalysisTrack\fP > \fBAddAnalysisTrack\fP (\fBconst\fP wxString &\fBname\fP=wxString())"
.br
.ti -1c
.RI "\fBModifiedAnalysisTrack\fP \fBModifyAnalysisTrack\fP (\fBconst\fP \fBLabelTrack\fP *pOrigTrack, \fBconst\fP wxString &\fBname\fP=wxString())"
.br
.ti -1c
.RI "\fBvoid\fP \fBReplaceProcessedTracks\fP (\fBconst\fP \fBbool\fP bGoodResult)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddToOutputTracks\fP (\fBTrack\fP *\fBt\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBProgressDialog\fP * \fBmProgress\fP"
.br
.ti -1c
.RI "double \fBmProjectRate\fP"
.br
.ti -1c
.RI "double \fBmSampleRate\fP"
.br
.ti -1c
.RI "\fBTrackFactory\fP * \fBmFactory\fP"
.br
.ti -1c
.RI "\fBTrackList\fP * \fBmTracks\fP"
.br
.ti -1c
.RI "\fBTrackList\fP * \fBmOutputTracks\fP"
.br
.ti -1c
.RI "double \fBmT0\fP"
.br
.ti -1c
.RI "double \fBmT1\fP"
.br
.ti -1c
.RI "double \fBmF0\fP"
.br
.ti -1c
.RI "double \fBmF1\fP"
.br
.ti -1c
.RI "\fBTimeWarper\fP * \fBmWarper\fP"
.br
.ti -1c
.RI "wxArrayString \fBmPresetNames\fP"
.br
.ti -1c
.RI "wxArrayString \fBmPresetValues\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmPass\fP"
.br
.ti -1c
.RI "wxDialog * \fBmUIDialog\fP"
.br
.ti -1c
.RI "wxWindow * \fBmUIParent\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmUIResultID\fP"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBmSampleCnt\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmOutputTracksType\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEffectManager\fP"
.br
.ti -1c
.RI "class \fBEffectRack\fP"
.br
.ti -1c
.RI "class \fBEffectUIHost\fP"
.br
.ti -1c
.RI "class \fBEffectPresetsDialog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
STK abstract effects parent class\&. 

Base class for many of the effects in Audacity\&.
.PP
This class provides common functionality for STK effects subclasses\&.
.PP
by Perry R\&. Cook and Gary P\&. Scavone, 1995 - 2005\&. 
.PP
Definition at line 58 of file Effect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Effect::Effect ()"

.PP
Definition at line 88 of file Effect\&.cpp\&.
.SS "Effect::~Effect ()\fC [virtual]\fP"

.PP
Definition at line 137 of file Effect\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "auto Effect::AddAnalysisTrack (\fBconst\fP wxString & name = \fCwxString()\fP)\fC [protected]\fP"

.PP
Definition at line 2165 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::AddToOutputTracks (\fBTrack\fP * t)\fC [protected]\fP"

.PP
Definition at line 2128 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 773 of file Effect\&.cpp\&.
.SS "double Effect::CalcPreviewInputLength (double previewLength)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectTruncSilence\fP, \fBEffectChangeSpeed\fP, and \fBEffectPaulstretch\fP\&.
.PP
Definition at line 2332 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::CanExportPresets ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 704 of file Effect\&.cpp\&.
.SS "virtual \fBbool\fP Effect::CheckWhetherSkipEffect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBNyquistEffect\fP, \fBEffectChangeSpeed\fP, \fBEffectClickRemoval\fP, \fBEffectNormalize\fP, and \fBEffectNoiseReduction\fP\&.
.PP
Definition at line 280 of file Effect\&.h\&.
.SS "\fBbool\fP Effect::CloseUI ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP\&.
.PP
Definition at line 694 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::CopyInputTracks ()\fC [protected]\fP"

.PP
Definition at line 2096 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::CopyInputTracks (\fBint\fP trackType)\fC [protected]\fP"

.PP
Definition at line 2101 of file Effect\&.cpp\&.
.SS "wxDialog * Effect::CreateUI (wxWindow * parent, \fBEffectUIClientInterface\fP * client)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 786 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::DoEffect (wxWindow * parent, double projectRate, \fBTrackList\fP * list, \fBTrackFactory\fP * factory, \fBSelectedRegion\fP * selectedRegion, \fBbool\fP shouldPrompt = \fC\fBtrue\fP\fP)"

.PP
Definition at line 1168 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::EnableApply (\fBbool\fP enable = \fC\fBtrue\fP\fP)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1928 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::EnableDebug (\fBbool\fP enable = \fC\fBtrue\fP\fP)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1998 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::EnablePreview (\fBbool\fP enable = \fC\fBtrue\fP\fP)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1959 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::End ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectAutoDuck\fP\&.
.PP
Definition at line 1909 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::ExportPresets ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 709 of file Effect\&.cpp\&.
.SS "\fBint\fP Effect::GetAudioInCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectInvert\fP, \fBEffectLeveller\fP, \fBEffectFade\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 299 of file Effect\&.cpp\&.
.SS "\fBint\fP Effect::GetAudioOutCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectToneGen\fP, \fBEffectNoise\fP, \fBEffectInvert\fP, \fBEffectLeveller\fP, \fBEffectFade\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 309 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectToneGen\fP, \fBEffectNoise\fP, \fBEffectNormalize\fP, \fBEffectLeveller\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, and \fBEffectPaulstretch\fP\&.
.PP
Definition at line 576 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetAutomationParameters (wxString & parms)\fC [virtual]\fP"

.PP
Definition at line 1032 of file Effect\&.cpp\&.
.SS "wxString Effect::GetCurrentSettingsGroup ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 811 of file Effect\&.cpp\&.
.SS "double Effect::GetDefaultDuration ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 728 of file Effect\&.cpp\&.
.SS "wxString Effect::GetDescription ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectNoise\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectNoiseReduction\fP, \fBEffectSilence\fP, \fBEffectLeveller\fP, \fBEffectInvert\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, \fBEffectPaulstretch\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 217 of file Effect\&.cpp\&.
.SS "double Effect::GetDuration ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 733 of file Effect\&.cpp\&.
.SS "wxString Effect::GetDurationFormat ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 743 of file Effect\&.cpp\&.
.SS "wxString Effect::GetFactoryDefaultsGroup ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 816 of file Effect\&.cpp\&.
.SS "wxArrayString Effect::GetFactoryPresets ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectReverb\fP\&.
.PP
Definition at line 628 of file Effect\&.cpp\&.
.SS "wxString Effect::GetFamily ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 227 of file Effect\&.cpp\&.
.SS "\fBPluginID\fP Effect::GetID ()\fC [virtual]\fP"

.PP
Definition at line 989 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::GetLatency ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 361 of file Effect\&.cpp\&.
.SS "\fBint\fP Effect::GetMidiInCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 319 of file Effect\&.cpp\&.
.SS "\fBint\fP Effect::GetMidiOutCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 329 of file Effect\&.cpp\&.
.SS "wxString Effect::GetName ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 187 of file Effect\&.cpp\&.
.SS "\fBint\fP Effect::GetNumWaveGroups ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 326 of file Effect\&.h\&.
.SS "\fBint\fP Effect::GetNumWaveTracks ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 324 of file Effect\&.h\&.
.SS "\fBint\fP Effect::GetPass ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1279 of file Effect\&.cpp\&.
.SS "wxString Effect::GetPath ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 167 of file Effect\&.cpp\&.
.SS "wxString Effect::GetPreset (wxWindow * parent, \fBconst\fP wxString & parms)\fC [virtual]\fP"

.PP
Definition at line 1122 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, wxString & value, \fBconst\fP wxString & defval = \fCwxEmptyString\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 917 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBint\fP & value, \fBint\fP defval = \fC0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 922 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBbool\fP & value, \fBbool\fP defval = \fC\fBfalse\fP\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 927 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, float & value, float defval = \fC0\&.0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 932 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, double & value, double defval = \fC0\&.0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 937 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBsampleCount\fP & value, \fBsampleCount\fP defval = \fC0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 942 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetPrivateConfigSubgroups (\fBconst\fP wxString & group, wxArrayString & subgroups)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 912 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::GetSamples (\fBWaveTrack\fP * track, \fBsampleCount\fP * start, \fBsampleCount\fP * len)\fC [protected]\fP"

.PP
Definition at line 2043 of file Effect\&.cpp\&.
.SS "wxString Effect::GetSavedStateGroup ()\fC [virtual]\fP"

.PP
Definition at line 821 of file Effect\&.cpp\&.
.SS "wxString Effect::GetSelectionFormat ()\fC [virtual]\fP"

.PP
Definition at line 748 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, wxString & value, \fBconst\fP wxString & defval = \fCwxEmptyString\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 837 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBint\fP & value, \fBint\fP defval = \fC0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 842 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBbool\fP & value, \fBbool\fP defval = \fC\fBfalse\fP\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 847 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, float & value, float defval = \fC0\&.0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 852 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, double & value, double defval = \fC0\&.0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 857 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBsampleCount\fP & value, \fBsampleCount\fP defval = \fC0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 862 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::GetSharedConfigSubgroups (\fBconst\fP wxString & group, wxArrayString & subgroups)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 832 of file Effect\&.cpp\&.
.SS "wxString Effect::GetSymbol ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectNoise\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectNoiseReduction\fP, \fBEffectSilence\fP, \fBEffectLeveller\fP, \fBEffectInvert\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, \fBEffectPaulstretch\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 177 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::GetTailSize ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 371 of file Effect\&.cpp\&.
.SS "\fBTimeWarper\fP * Effect::GetTimeWarper ()\fC [protected]\fP"

.PP
Definition at line 2084 of file Effect\&.cpp\&.
.SS "\fBEffectType\fP Effect::GetType ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectNoise\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectNoiseReduction\fP, \fBEffectSilence\fP, \fBEffectLeveller\fP, \fBEffectInvert\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, \fBEffectPaulstretch\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 157 of file Effect\&.cpp\&.
.SS "wxArrayString Effect::GetUserPresets ()\fC [virtual]\fP"

.PP
Definition at line 1101 of file Effect\&.cpp\&.
.SS "wxString Effect::GetUserPresetsGroup (\fBconst\fP wxString & name)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 800 of file Effect\&.cpp\&.
.SS "wxString Effect::GetVendor ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 197 of file Effect\&.cpp\&.
.SS "wxString Effect::GetVersion ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 207 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HasCurrentSettings ()\fC [virtual]\fP"

.PP
Definition at line 1112 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HasFactoryDefaults ()\fC [virtual]\fP"

.PP
Definition at line 1117 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HasOptions ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 717 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HasPrivateConfigGroup (\fBconst\fP wxString & group)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 907 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HasSharedConfigGroup (\fBconst\fP wxString & group)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 827 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::HideUI ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 689 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::ImportPresets ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 713 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::IncludeNotSelectedPreviewTracks (\fBbool\fP includeNotSelected)\fC [protected]\fP"

.PP
Definition at line 2014 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::Init ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectScienFilter\fP, \fBEffectAmplify\fP, \fBEffectChangeSpeed\fP, \fBEffectDtmf\fP, \fBEffectAutoDuck\fP, \fBEffectNoiseReduction\fP, and \fBGenerator\fP\&.
.PP
Definition at line 1268 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::InitPass1 ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectCompressor\fP, \fBEffectBassTreble\fP, and \fBEffectTwoPassSimpleMono\fP\&.
.PP
Definition at line 1284 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::InitPass2 ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectCompressor\fP, \fBEffectBassTreble\fP, and \fBEffectTwoPassSimpleMono\fP\&.
.PP
Definition at line 1289 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsBatchProcessing ()\fC [virtual]\fP"

.PP
Definition at line 1139 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsDefault ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 247 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsGraphicalUI ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 679 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsHidden ()\fC [virtual]\fP"

.PP
Reimplemented in \fBEffectStereoToMono\fP\&.
.PP
Definition at line 2525 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsInteractive ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP, \fBEffectInvert\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, and \fBEffectStereoToMono\fP\&.
.PP
Definition at line 237 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsLegacy ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Definition at line 257 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsPreviewing ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 344 of file Effect\&.h\&.
.SS "\fBbool\fP Effect::IsReady ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 381 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::IsRealtimeActive ()"

.PP
Definition at line 2520 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::LoadFactoryDefaults ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP\&.
.PP
Definition at line 648 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::LoadFactoryPreset (\fBint\fP id)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectReverb\fP\&.
.PP
Definition at line 638 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::LoadUserPreset (\fBconst\fP wxString & name)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 596 of file Effect\&.cpp\&.
.SS "auto Effect::ModifyAnalysisTrack (\fBconst\fP \fBLabelTrack\fP * pOrigTrack, \fBconst\fP wxString & name = \fCwxString()\fP)\fC [protected]\fP"

.PP
Definition at line 2217 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::PopulateOrExchange (\fBShuttleGui\fP & S)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectTruncSilence\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectAmplify\fP, \fBEffectBassTreble\fP, \fBEffectChangeSpeed\fP, \fBEffectAutoDuck\fP, \fBEffectDtmf\fP, \fBEffectClickRemoval\fP, \fBEffectCompressor\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectEcho\fP, \fBEffectNoise\fP, \fBEffectLeveller\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectPaulstretch\fP, and \fBEffectSilence\fP\&.
.PP
Definition at line 1913 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::PopulateUI (wxWindow * parent)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP\&.
.PP
Definition at line 664 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::Preview ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 781 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::Preview (\fBbool\fP dryOnly)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectAmplify\fP\&.
.PP
Definition at line 2530 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::Process ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectTruncSilence\fP, \fBEffectChangeSpeed\fP, \fBEffectAutoDuck\fP, \fBEffectClickRemoval\fP, \fBGenerator\fP, \fBEffectNormalize\fP, \fBEffectFindClipping\fP, \fBEffectNoiseReduction\fP, \fBEffectRepeat\fP, \fBEffectPaulstretch\fP, \fBEffectStereoToMono\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectSimpleMono\fP, and \fBEffectTwoPassSimpleMono\fP\&.
.PP
Definition at line 1294 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::ProcessBlock (float ** inBlock, float ** outBlock, \fBsampleCount\fP blockLen)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectToneGen\fP, \fBEffectNoise\fP, \fBEffectFade\fP, \fBEffectInvert\fP, and \fBEffectLeveller\fP\&.
.PP
Definition at line 411 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::ProcessFinalize ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectReverb\fP\&.
.PP
Definition at line 401 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::ProcessInitialize (\fBsampleCount\fP totalLen, \fBChannelNames\fP chanMap = \fC\fBNULL\fP\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectToneGen\fP, and \fBEffectFade\fP\&.
.PP
Definition at line 391 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::ProcessPass ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1320 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::PromptUser (wxWindow * parent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectNoiseReduction\fP\&.
.PP
Definition at line 1274 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeAddProcessor (\fBint\fP numChannels, float sampleRate)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, and \fBEffectWahwah\fP\&.
.PP
Definition at line 434 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeAddProcessor (\fBint\fP group, \fBint\fP chans, float rate)"

.PP
Definition at line 2340 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeFinalize ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, and \fBEffectWahwah\fP\&.
.PP
Definition at line 444 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeInitialize ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, and \fBEffectWahwah\fP\&.
.PP
Definition at line 421 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::RealtimeProcess (\fBint\fP group, float ** inbuf, float ** outbuf, \fBsampleCount\fP numSamples)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, and \fBEffectWahwah\fP\&.
.PP
Definition at line 508 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::RealtimeProcess (\fBint\fP group, \fBint\fP chans, float ** inbuf, float ** outbuf, \fBsampleCount\fP numSamples)"

.PP
Definition at line 2405 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeProcessEnd ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 521 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeProcessStart ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 498 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeResume ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 476 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RealtimeSuspend ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 454 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RemovePrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 982 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RemovePrivateConfigSubgroup (\fBconst\fP wxString & group)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 977 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RemoveSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 902 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::RemoveSharedConfigSubgroup (\fBconst\fP wxString & group)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 897 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::ReplaceProcessedTracks (\fBconst\fP \fBbool\fP bGoodResult)\fC [protected]\fP"

.PP
Definition at line 2224 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SaveUserPreset (\fBconst\fP wxString & name)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 612 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectToneGen\fP, \fBEffectNoise\fP, \fBEffectNormalize\fP, \fBEffectLeveller\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, and \fBEffectPaulstretch\fP\&.
.PP
Definition at line 586 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetAutomationParameters (\fBconst\fP wxString & parms)\fC [virtual]\fP"

.PP
Definition at line 1049 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetBatchProcessing (\fBbool\fP start)\fC [virtual]\fP"

.PP
Definition at line 1144 of file Effect\&.cpp\&.
.SS "\fBsampleCount\fP Effect::SetBlockSize (\fBsampleCount\fP maxBlockSize)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 349 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetDuration (double duration)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectHostInterface\fP\&.
.PP
Definition at line 753 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetHost (\fBEffectHostInterface\fP * host)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 289 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetHostUI (\fBEffectUIHostInterface\fP * host)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 660 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetLinearEffectFlag (\fBbool\fP linearEffectFlag)\fC [protected]\fP"

.PP
Definition at line 2003 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetPresetParameters (\fBconst\fP wxArrayString * Names, \fBconst\fP wxArrayString * Values)\fC [inline]\fP"

.PP
Definition at line 234 of file Effect\&.h\&.
.SS "\fBvoid\fP Effect::SetPreviewFullSelectionFlag (\fBbool\fP previewDurationFlag)\fC [protected]\fP"

.PP
Definition at line 2008 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP wxString & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 947 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBint\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 952 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBbool\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 957 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP float & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 962 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP double & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 967 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetPrivateConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBsampleCount\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 972 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetSampleRate (\fBsampleCount\fP rate)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Definition at line 339 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP wxString & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 867 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBint\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 872 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBbool\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 877 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP float & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 882 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP double & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 887 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SetSharedConfig (\fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBsampleCount\fP & value)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBConfigClientInterface\fP\&.
.PP
Definition at line 892 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::SetTimeWarper (\fBTimeWarper\fP * warper)\fC [protected]\fP"

.PP
Definition at line 2072 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::ShowInterface (wxWindow * parent, \fBbool\fP forceModal = \fC\fBfalse\fP\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectClientInterface\fP\&.
.PP
Reimplemented in \fBNyquistEffect\fP\&.
.PP
Definition at line 531 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::ShowOptions ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Definition at line 722 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::Startup (\fBEffectClientInterface\fP * client)\fC [virtual]\fP"

.PP
Definition at line 999 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::Startup ()\fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectChangeSpeed\fP, \fBEffectDtmf\fP, \fBEffectBassTreble\fP, \fBEffectClickRemoval\fP, \fBEffectCompressor\fP, \fBEffectAutoDuck\fP, \fBEffectNoise\fP, \fBEffectNormalize\fP, and \fBEffectLeveller\fP\&.
.PP
Definition at line 1027 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SupportsAutomation ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Definition at line 277 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::SupportsRealtime ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectIdentInterface\fP\&.
.PP
Reimplemented in \fBEffectPhaser\fP, and \fBEffectWahwah\fP\&.
.PP
Definition at line 267 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::TotalProgress (double frac)\fC [protected]\fP"

.PP
Definition at line 2019 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::TrackGroupProgress (\fBint\fP whichGroup, double frac, \fBconst\fP wxString & msg = \fCwxEmptyString\fP)\fC [protected]\fP"

.PP
Definition at line 2035 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::TrackProgress (\fBint\fP whichTrack, double frac, \fBconst\fP wxString & msg = \fCwxEmptyString\fP)\fC [protected]\fP"

.PP
Definition at line 2027 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::TransferDataFromWindow ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectTruncSilence\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectAmplify\fP, \fBEffectBassTreble\fP, \fBEffectAutoDuck\fP, \fBEffectChangeSpeed\fP, \fBEffectClickRemoval\fP, \fBEffectDtmf\fP, \fBEffectCompressor\fP, \fBEffectNormalize\fP, \fBEffectToneGen\fP, \fBEffectEcho\fP, \fBEffectNoise\fP, \fBEffectLeveller\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectPaulstretch\fP, and \fBEffectSilence\fP\&.
.PP
Definition at line 1923 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::TransferDataToWindow ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBEffectEqualization\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectTruncSilence\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectChangeSpeed\fP, \fBEffectAmplify\fP, \fBEffectBassTreble\fP, \fBEffectDtmf\fP, \fBEffectAutoDuck\fP, \fBEffectClickRemoval\fP, \fBEffectCompressor\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectEcho\fP, \fBEffectNoise\fP, \fBEffectLeveller\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBEffectPaulstretch\fP, and \fBEffectSilence\fP\&.
.PP
Definition at line 1918 of file Effect\&.cpp\&.
.SS "\fBbool\fP Effect::ValidateUI ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBEffectUIClientInterface\fP\&.
.PP
Reimplemented in \fBEffectEqualization\fP\&.
.PP
Definition at line 684 of file Effect\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBEffectManager\fP\fC [friend]\fP"

.PP
Definition at line 530 of file Effect\&.h\&.
.SS "friend class \fBEffectPresetsDialog\fP\fC [friend]\fP"

.PP
Definition at line 533 of file Effect\&.h\&.
.SS "friend class EffectRack\fC [friend]\fP"

.PP
Definition at line 531 of file Effect\&.h\&.
.SS "friend class \fBEffectUIHost\fP\fC [friend]\fP"

.PP
Definition at line 532 of file Effect\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Effect::mF0\fC [protected]\fP"

.PP
Definition at line 444 of file Effect\&.h\&.
.SS "double Effect::mF1\fC [protected]\fP"

.PP
Definition at line 445 of file Effect\&.h\&.
.SS "\fBTrackFactory\fP* Effect::mFactory\fC [protected]\fP"

.PP
Definition at line 438 of file Effect\&.h\&.
.SS "\fBTrackList\fP* Effect::mOutputTracks\fC [protected]\fP"

.PP
Definition at line 440 of file Effect\&.h\&.
.SS "\fBint\fP Effect::mOutputTracksType\fC [protected]\fP"

.PP
Definition at line 460 of file Effect\&.h\&.
.SS "\fBint\fP Effect::mPass\fC [protected]\fP"

.PP
Definition at line 450 of file Effect\&.h\&.
.SS "wxArrayString Effect::mPresetNames\fC [protected]\fP"

.PP
Definition at line 448 of file Effect\&.h\&.
.SS "wxArrayString Effect::mPresetValues\fC [protected]\fP"

.PP
Definition at line 449 of file Effect\&.h\&.
.SS "\fBProgressDialog\fP* Effect::mProgress\fC [protected]\fP"

.PP
Definition at line 434 of file Effect\&.h\&.
.SS "double Effect::mProjectRate\fC [protected]\fP"

.PP
Definition at line 435 of file Effect\&.h\&.
.SS "\fBsampleCount\fP Effect::mSampleCnt\fC [protected]\fP"

.PP
Definition at line 457 of file Effect\&.h\&.
.SS "double Effect::mSampleRate\fC [protected]\fP"

.PP
Definition at line 437 of file Effect\&.h\&.
.SS "double Effect::mT0\fC [protected]\fP"

.PP
Definition at line 441 of file Effect\&.h\&.
.SS "double Effect::mT1\fC [protected]\fP"

.PP
Definition at line 442 of file Effect\&.h\&.
.SS "\fBTrackList\fP* Effect::mTracks\fC [protected]\fP"

.PP
Definition at line 439 of file Effect\&.h\&.
.SS "wxDialog* Effect::mUIDialog\fC [protected]\fP"

.PP
Definition at line 453 of file Effect\&.h\&.
.SS "wxWindow* Effect::mUIParent\fC [protected]\fP"

.PP
Definition at line 454 of file Effect\&.h\&.
.SS "\fBint\fP Effect::mUIResultID\fC [protected]\fP"

.PP
Definition at line 455 of file Effect\&.h\&.
.SS "\fBTimeWarper\fP* Effect::mWarper\fC [protected]\fP"

.PP
Definition at line 447 of file Effect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
