.TH "EffectNoiseReduction::Statistics" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectNoiseReduction::Statistics \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatistics\fP (\fBint\fP spectrumSize, double \fBrate\fP, \fBint\fP windowTypes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmRate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmWindowSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmWindowTypes\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmTotalWindows\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmTrackWindows\fP"
.br
.ti -1c
.RI "\fBFloatVector\fP \fBmSums\fP"
.br
.ti -1c
.RI "\fBFloatVector\fP \fBmMeans\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 159 of file NoiseReduction\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EffectNoiseReduction::Statistics::Statistics (\fBint\fP spectrumSize, double rate, \fBint\fP windowTypes)\fC [inline]\fP"

.PP
Definition at line 162 of file NoiseReduction\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFloatVector\fP EffectNoiseReduction::Statistics::mMeans"

.PP
Definition at line 184 of file NoiseReduction\&.cpp\&.
.SS "double EffectNoiseReduction::Statistics::mRate"

.PP
Definition at line 177 of file NoiseReduction\&.cpp\&.
.SS "\fBFloatVector\fP EffectNoiseReduction::Statistics::mSums"

.PP
Definition at line 183 of file NoiseReduction\&.cpp\&.
.SS "\fBint\fP EffectNoiseReduction::Statistics::mTotalWindows"

.PP
Definition at line 181 of file NoiseReduction\&.cpp\&.
.SS "\fBint\fP EffectNoiseReduction::Statistics::mTrackWindows"

.PP
Definition at line 182 of file NoiseReduction\&.cpp\&.
.SS "\fBint\fP EffectNoiseReduction::Statistics::mWindowSize"

.PP
Definition at line 178 of file NoiseReduction\&.cpp\&.
.SS "\fBint\fP EffectNoiseReduction::Statistics::mWindowTypes"

.PP
Definition at line 179 of file NoiseReduction\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
