.TH "EffectLeveller" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectLeveller \- An \fBEffect\fP that aims to selectively make softer sounds louder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Leveller\&.h>\fP
.PP
Inherits \fBEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectLeveller\fP ()"
.br
.ti -1c
.RI "virtual \fB~EffectLeveller\fP ()"
.br
.ti -1c
.RI "wxString \fBGetSymbol\fP () override"
.br
.ti -1c
.RI "wxString \fBGetDescription\fP () override"
.br
.ti -1c
.RI "\fBEffectType\fP \fBGetType\fP () override"
.br
.ti -1c
.RI "\fBint\fP \fBGetAudioInCount\fP () override"
.br
.ti -1c
.RI "\fBint\fP \fBGetAudioOutCount\fP () override"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBProcessBlock\fP (float **inBlock, float **outBlock, \fBsampleCount\fP blockLen) override"
.br
.ti -1c
.RI "\fBbool\fP \fBGetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBSetAutomationParameters\fP (\fBEffectAutomationParameters\fP &parms) override"
.br
.ti -1c
.RI "\fBbool\fP \fBStartup\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopulateOrExchange\fP (\fBShuttleGui\fP &\fBS\fP) override"
.br
.ti -1c
.RI "\fBbool\fP \fBTransferDataToWindow\fP () override"
.br
.ti -1c
.RI "\fBbool\fP \fBTransferDataFromWindow\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBEffect\fP that aims to selectively make softer sounds louder\&. 
.PP
Definition at line 23 of file Leveller\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EffectLeveller::EffectLeveller ()"

.PP
Definition at line 59 of file Leveller\&.cpp\&.
.SS "EffectLeveller::~EffectLeveller ()\fC [virtual]\fP"

.PP
Definition at line 70 of file Leveller\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP EffectLeveller::GetAudioInCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 95 of file Leveller\&.cpp\&.
.SS "\fBint\fP EffectLeveller::GetAudioOutCount ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 100 of file Leveller\&.cpp\&.
.SS "\fBbool\fP EffectLeveller::GetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 123 of file Leveller\&.cpp\&.
.SS "wxString EffectLeveller::GetDescription ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 81 of file Leveller\&.cpp\&.
.SS "wxString EffectLeveller::GetSymbol ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 76 of file Leveller\&.cpp\&.
.SS "\fBEffectType\fP EffectLeveller::GetType ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 88 of file Leveller\&.cpp\&.
.SS "\fBvoid\fP EffectLeveller::PopulateOrExchange (\fBShuttleGui\fP & S)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 199 of file Leveller\&.cpp\&.
.SS "\fBsampleCount\fP EffectLeveller::ProcessBlock (float ** inBlock, float ** outBlock, \fBsampleCount\fP blockLen)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 105 of file Leveller\&.cpp\&.
.SS "\fBbool\fP EffectLeveller::SetAutomationParameters (\fBEffectAutomationParameters\fP & parms)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 131 of file Leveller\&.cpp\&.
.SS "\fBbool\fP EffectLeveller::Startup ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 163 of file Leveller\&.cpp\&.
.SS "\fBbool\fP EffectLeveller::TransferDataFromWindow ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 242 of file Leveller\&.cpp\&.
.SS "\fBbool\fP EffectLeveller::TransferDataToWindow ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBEffect\fP\&.
.PP
Definition at line 232 of file Leveller\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
