.TH "EgScopeUI" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EgScopeUI \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_Atom_Forge\fP \fBforge\fP"
.br
.ti -1c
.RI "\fBLV2_URID_Map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBScoLV2URIs\fP \fBuris\fP"
.br
.ti -1c
.RI "\fBLV2UI_Write_Function\fP \fBwrite\fP"
.br
.ti -1c
.RI "\fBLV2UI_Controller\fP \fBcontroller\fP"
.br
.ti -1c
.RI "GtkWidget * \fBhbox\fP"
.br
.ti -1c
.RI "GtkWidget * \fBvbox\fP"
.br
.ti -1c
.RI "GtkWidget * \fBsep\fP [2]"
.br
.ti -1c
.RI "GtkWidget * \fBdarea\fP"
.br
.ti -1c
.RI "GtkWidget * \fBbtn_pause\fP"
.br
.ti -1c
.RI "GtkWidget * \fBlbl_speed\fP"
.br
.ti -1c
.RI "GtkWidget * \fBlbl_amp\fP"
.br
.ti -1c
.RI "GtkWidget * \fBspb_speed\fP"
.br
.ti -1c
.RI "GtkWidget * \fBspb_amp\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBspb_speed_adj\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBspb_amp_adj\fP"
.br
.ti -1c
.RI "\fBScoChan\fP \fBchn\fP [2]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBstride\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBn_channels\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBpaused\fP"
.br
.ti -1c
.RI "float \fBrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file examploscope_ui\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "GtkWidget* EgScopeUI::btn_pause"

.PP
Definition at line 61 of file examploscope_ui\&.c\&.
.SS "\fBScoChan\fP EgScopeUI::chn[2]"

.PP
Definition at line 69 of file examploscope_ui\&.c\&.
.SS "\fBLV2UI_Controller\fP EgScopeUI::controller"

.PP
Definition at line 55 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::darea"

.PP
Definition at line 60 of file examploscope_ui\&.c\&.
.SS "\fBLV2_Atom_Forge\fP EgScopeUI::forge"

.PP
Definition at line 50 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::hbox"

.PP
Definition at line 57 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::lbl_amp"

.PP
Definition at line 63 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::lbl_speed"

.PP
Definition at line 62 of file examploscope_ui\&.c\&.
.SS "\fBLV2_URID_Map\fP* EgScopeUI::map"

.PP
Definition at line 51 of file examploscope_ui\&.c\&.
.SS "\fBuint32_t\fP EgScopeUI::n_channels"

.PP
Definition at line 71 of file examploscope_ui\&.c\&.
.SS "\fBbool\fP EgScopeUI::paused"

.PP
Definition at line 72 of file examploscope_ui\&.c\&.
.SS "float EgScopeUI::rate"

.PP
Definition at line 73 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::sep[2]"

.PP
Definition at line 59 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::spb_amp"

.PP
Definition at line 65 of file examploscope_ui\&.c\&.
.SS "GtkAdjustment* EgScopeUI::spb_amp_adj"

.PP
Definition at line 67 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::spb_speed"

.PP
Definition at line 64 of file examploscope_ui\&.c\&.
.SS "GtkAdjustment* EgScopeUI::spb_speed_adj"

.PP
Definition at line 66 of file examploscope_ui\&.c\&.
.SS "\fBuint32_t\fP EgScopeUI::stride"

.PP
Definition at line 70 of file examploscope_ui\&.c\&.
.SS "\fBScoLV2URIs\fP EgScopeUI::uris"

.PP
Definition at line 52 of file examploscope_ui\&.c\&.
.SS "GtkWidget* EgScopeUI::vbox"

.PP
Definition at line 58 of file examploscope_ui\&.c\&.
.SS "\fBLV2UI_Write_Function\fP EgScopeUI::write"

.PP
Definition at line 54 of file examploscope_ui\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
