.TH "encoder_client_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder_client_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file file_utils_flac\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "FILE* encoder_client_struct::file"

.PP
Definition at line 52 of file file_utils_flac\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
