.TH "encode_options_t" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encode_options_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encode\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fButils__SkipUntilSpecification\fP \fBskip_specification\fP"
.br
.ti -1c
.RI "\fButils__SkipUntilSpecification\fP \fBuntil_specification\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBverify\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBlax\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpadding\fP"
.br
.ti -1c
.RI "size_t \fBnum_compression_settings\fP"
.br
.ti -1c
.RI "\fBcompression_setting_t\fP \fBcompression_settings\fP [64]"
.br
.ti -1c
.RI "char * \fBrequested_seek_points\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnum_requested_seek_points\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBcuesheet_filename\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBtreat_warnings_as_errors\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBcontinue_through_decode_errors\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBcued_seekpoints\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBchannel_map_none\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBis_first_file\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBis_last_file\fP"
.br
.ti -1c
.RI "\fBFLAC__int32\fP ** \fBalign_reservoir\fP"
.br
.ti -1c
.RI "unsigned * \fBalign_reservoir_samples\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBreplay_gain\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBignore_chunk_sizes\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBsector_align\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBerror_on_compression_fail\fP"
.br
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP * \fBvorbis_comment\fP"
.br
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP * \fBpictures\fP [64]"
.br
.ti -1c
.RI "unsigned \fBnum_pictures\fP"
.br
.ti -1c
.RI "\fBFileFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBFLAC__bool\fP \fBis_big_endian\fP"
.br
.ti -1c
.RI "      \fBFLAC__bool\fP \fBis_unsigned_samples\fP"
.br
.ti -1c
.RI "      unsigned \fBchannels\fP"
.br
.ti -1c
.RI "      unsigned \fBbps\fP"
.br
.ti -1c
.RI "      unsigned \fBsample_rate\fP"
.br
.ti -1c
.RI "   } \fBraw\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBforeign_metadata_t\fP * \fBforeign_metadata\fP"
.br
.ti -1c
.RI "   } \fBiff\fP"
.br
.ti -1c
.RI "} \fBformat_options\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBFLAC__bool\fP \fBdisable_constant_subframes\fP"
.br
.ti -1c
.RI "   \fBFLAC__bool\fP \fBdisable_fixed_subframes\fP"
.br
.ti -1c
.RI "   \fBFLAC__bool\fP \fBdisable_verbatim_subframes\fP"
.br
.ti -1c
.RI "   \fBFLAC__bool\fP \fBdo_md5\fP"
.br
.ti -1c
.RI "} \fBdebug\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file encode\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__int32\fP** encode_options_t::align_reservoir"

.PP
Definition at line 82 of file encode\&.h\&.
.SS "unsigned* encode_options_t::align_reservoir_samples"

.PP
Definition at line 83 of file encode\&.h\&.
.SS "unsigned encode_options_t::bps"

.PP
Definition at line 99 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::channel_map_none"

.PP
Definition at line 77 of file encode\&.h\&.
.SS "unsigned encode_options_t::channels"

.PP
Definition at line 98 of file encode\&.h\&.
.SS "\fBcompression_setting_t\fP encode_options_t::compression_settings[64]"

.PP
Definition at line 70 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::continue_through_decode_errors"

.PP
Definition at line 75 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::cued_seekpoints"

.PP
Definition at line 76 of file encode\&.h\&.
.SS "\fBconst\fP char* encode_options_t::cuesheet_filename"

.PP
Definition at line 73 of file encode\&.h\&.
.SS "struct { \&.\&.\&. }   encode_options_t::debug"

.SS "\fBFLAC__bool\fP encode_options_t::disable_constant_subframes"

.PP
Definition at line 108 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::disable_fixed_subframes"

.PP
Definition at line 109 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::disable_verbatim_subframes"

.PP
Definition at line 110 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::do_md5"

.PP
Definition at line 111 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::error_on_compression_fail"

.PP
Definition at line 87 of file encode\&.h\&.
.SS "\fBforeign_metadata_t\fP* encode_options_t::foreign_metadata"

.PP
Definition at line 103 of file encode\&.h\&.
.SS "\fBFileFormat\fP encode_options_t::format"

.PP
Definition at line 93 of file encode\&.h\&.
.SS "union { \&.\&.\&. }   encode_options_t::format_options"

.SS "struct { \&.\&.\&. }   encode_options_t::iff"

.SS "\fBFLAC__bool\fP encode_options_t::ignore_chunk_sizes"

.PP
Definition at line 85 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::is_big_endian"

.PP
Definition at line 96 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::is_first_file"

.PP
Definition at line 80 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::is_last_file"

.PP
Definition at line 81 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::is_unsigned_samples"

.PP
Definition at line 97 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::lax"

.PP
Definition at line 67 of file encode\&.h\&.
.SS "size_t encode_options_t::num_compression_settings"

.PP
Definition at line 69 of file encode\&.h\&.
.SS "unsigned encode_options_t::num_pictures"

.PP
Definition at line 91 of file encode\&.h\&.
.SS "\fBint\fP encode_options_t::num_requested_seek_points"

.PP
Definition at line 72 of file encode\&.h\&.
.SS "\fBint\fP encode_options_t::padding"

.PP
Definition at line 68 of file encode\&.h\&.
.SS "\fBFLAC__StreamMetadata\fP* encode_options_t::pictures[64]"

.PP
Definition at line 90 of file encode\&.h\&.
.SS "struct { \&.\&.\&. }   encode_options_t::raw"

.SS "\fBFLAC__bool\fP encode_options_t::replay_gain"

.PP
Definition at line 84 of file encode\&.h\&.
.SS "char* encode_options_t::requested_seek_points"

.PP
Definition at line 71 of file encode\&.h\&.
.SS "unsigned encode_options_t::sample_rate"

.PP
Definition at line 100 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::sector_align"

.PP
Definition at line 86 of file encode\&.h\&.
.SS "\fButils__SkipUntilSpecification\fP encode_options_t::skip_specification"

.PP
Definition at line 60 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::treat_warnings_as_errors"

.PP
Definition at line 74 of file encode\&.h\&.
.SS "\fButils__SkipUntilSpecification\fP encode_options_t::until_specification"

.PP
Definition at line 61 of file encode\&.h\&.
.SS "\fBFLAC__bool\fP encode_options_t::verify"

.PP
Definition at line 62 of file encode\&.h\&.
.SS "\fBFLAC__StreamMetadata\fP* encode_options_t::vorbis_comment"

.PP
Definition at line 89 of file encode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
