.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/envelope.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/envelope.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <ogg/ogg\&.h>\fP
.br
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'codec_internal\&.h'\fP
.br
\fC#include 'os\&.h'\fP
.br
\fC#include 'scales\&.h'\fP
.br
\fC#include 'envelope\&.h'\fP
.br
\fC#include 'mdct\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_ve_envelope_init\fP (\fBenvelope_lookup\fP *e, \fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_ve_envelope_clear\fP (\fBenvelope_lookup\fP *e)"
.br
.ti -1c
.RI "long \fB_ve_envelope_search\fP (\fBvorbis_dsp_state\fP *v)"
.br
.ti -1c
.RI "\fBint\fP \fB_ve_envelope_mark\fP (\fBvorbis_dsp_state\fP *v)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_ve_envelope_shift\fP (\fBenvelope_lookup\fP *e, long shift)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP _ve_envelope_clear (\fBenvelope_lookup\fP * e)"

.PP
Definition at line 76 of file envelope\&.c\&.
.SS "\fBvoid\fP _ve_envelope_init (\fBenvelope_lookup\fP * e, \fBvorbis_info\fP * vi)"

.PP
Definition at line 32 of file envelope\&.c\&.
.SS "\fBint\fP _ve_envelope_mark (\fBvorbis_dsp_state\fP * v)"

.PP
Definition at line 330 of file envelope\&.c\&.
.SS "long _ve_envelope_search (\fBvorbis_dsp_state\fP * v)"

.PP
Definition at line 216 of file envelope\&.c\&.
.SS "\fBvoid\fP _ve_envelope_shift (\fBenvelope_lookup\fP * e, long shift)"

.PP
Definition at line 356 of file envelope\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
