.TH "eqbandvvv_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eqbandvvv_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBinput\fP"
.br
.ti -1c
.RI "long \fBinput_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBinput_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBhz\fP"
.br
.ti -1c
.RI "long \fBhz_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBhz_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBhz_x1_sample\fP"
.br
.ti -1c
.RI "double \fBhz_pHaSe\fP"
.br
.ti -1c
.RI "double \fBhz_pHaSe_iNcR\fP"
.br
.ti -1c
.RI "double \fBoutput_per_hz\fP"
.br
.ti -1c
.RI "long \fBhz_n\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBgain\fP"
.br
.ti -1c
.RI "long \fBgain_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBgain_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBgain_x1_sample\fP"
.br
.ti -1c
.RI "double \fBgain_pHaSe\fP"
.br
.ti -1c
.RI "double \fBgain_pHaSe_iNcR\fP"
.br
.ti -1c
.RI "double \fBoutput_per_gain\fP"
.br
.ti -1c
.RI "long \fBgain_n\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBwidth\fP"
.br
.ti -1c
.RI "long \fBwidth_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBwidth_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBwidth_x1_sample\fP"
.br
.ti -1c
.RI "double \fBwidth_pHaSe\fP"
.br
.ti -1c
.RI "double \fBwidth_pHaSe_iNcR\fP"
.br
.ti -1c
.RI "double \fBoutput_per_width\fP"
.br
.ti -1c
.RI "long \fBwidth_n\fP"
.br
.ti -1c
.RI "double \fBinp_scale\fP"
.br
.ti -1c
.RI "double \fBw1\fP"
.br
.ti -1c
.RI "double \fBsw\fP"
.br
.ti -1c
.RI "double \fBcw\fP"
.br
.ti -1c
.RI "double \fBJ\fP"
.br
.ti -1c
.RI "double \fBgg\fP"
.br
.ti -1c
.RI "double \fBb0\fP"
.br
.ti -1c
.RI "double \fBb1\fP"
.br
.ti -1c
.RI "double \fBb2\fP"
.br
.ti -1c
.RI "double \fBa0\fP"
.br
.ti -1c
.RI "double \fBa1\fP"
.br
.ti -1c
.RI "double \fBa2\fP"
.br
.ti -1c
.RI "double \fBz1\fP"
.br
.ti -1c
.RI "double \fBz2\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBrecompute\fP"
.br
.ti -1c
.RI "double \fBinp_period\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file eqbandvvv\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "double eqbandvvv_susp_struct::a0"

.PP
Definition at line 69 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::a1"

.PP
Definition at line 70 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::a2"

.PP
Definition at line 71 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::b0"

.PP
Definition at line 66 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::b1"

.PP
Definition at line 67 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::b2"

.PP
Definition at line 68 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::cw"

.PP
Definition at line 63 of file eqbandvvv\&.c\&.
.SS "\fBsound_type\fP eqbandvvv_susp_struct::gain"

.PP
Definition at line 35 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::gain_cnt"

.PP
Definition at line 36 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::gain_n"

.PP
Definition at line 46 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::gain_pHaSe"

.PP
Definition at line 41 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::gain_pHaSe_iNcR"

.PP
Definition at line 42 of file eqbandvvv\&.c\&.
.SS "\fBsample_block_values_type\fP eqbandvvv_susp_struct::gain_ptr"

.PP
Definition at line 37 of file eqbandvvv\&.c\&.
.SS "\fBsample_type\fP eqbandvvv_susp_struct::gain_x1_sample"

.PP
Definition at line 40 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::gg"

.PP
Definition at line 65 of file eqbandvvv\&.c\&.
.SS "\fBsound_type\fP eqbandvvv_susp_struct::hz"

.PP
Definition at line 23 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::hz_cnt"

.PP
Definition at line 24 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::hz_n"

.PP
Definition at line 34 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::hz_pHaSe"

.PP
Definition at line 29 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::hz_pHaSe_iNcR"

.PP
Definition at line 30 of file eqbandvvv\&.c\&.
.SS "\fBsample_block_values_type\fP eqbandvvv_susp_struct::hz_ptr"

.PP
Definition at line 25 of file eqbandvvv\&.c\&.
.SS "\fBsample_type\fP eqbandvvv_susp_struct::hz_x1_sample"

.PP
Definition at line 28 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::inp_period"

.PP
Definition at line 75 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::inp_scale"

.PP
Definition at line 60 of file eqbandvvv\&.c\&.
.SS "\fBsound_type\fP eqbandvvv_susp_struct::input"

.PP
Definition at line 20 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::input_cnt"

.PP
Definition at line 21 of file eqbandvvv\&.c\&.
.SS "\fBsample_block_values_type\fP eqbandvvv_susp_struct::input_ptr"

.PP
Definition at line 22 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::J"

.PP
Definition at line 64 of file eqbandvvv\&.c\&.
.SS "\fBboolean\fP eqbandvvv_susp_struct::logically_stopped"

.PP
Definition at line 19 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::output_per_gain"

.PP
Definition at line 45 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::output_per_hz"

.PP
Definition at line 33 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::output_per_width"

.PP
Definition at line 57 of file eqbandvvv\&.c\&.
.SS "\fBboolean\fP eqbandvvv_susp_struct::recompute"

.PP
Definition at line 74 of file eqbandvvv\&.c\&.
.SS "\fBboolean\fP eqbandvvv_susp_struct::started"

.PP
Definition at line 17 of file eqbandvvv\&.c\&.
.SS "\fBsnd_susp_node\fP eqbandvvv_susp_struct::susp"

.PP
Definition at line 16 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::sw"

.PP
Definition at line 62 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::terminate_cnt"

.PP
Definition at line 18 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::w1"

.PP
Definition at line 61 of file eqbandvvv\&.c\&.
.SS "\fBsound_type\fP eqbandvvv_susp_struct::width"

.PP
Definition at line 47 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::width_cnt"

.PP
Definition at line 48 of file eqbandvvv\&.c\&.
.SS "long eqbandvvv_susp_struct::width_n"

.PP
Definition at line 58 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::width_pHaSe"

.PP
Definition at line 53 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::width_pHaSe_iNcR"

.PP
Definition at line 54 of file eqbandvvv\&.c\&.
.SS "\fBsample_block_values_type\fP eqbandvvv_susp_struct::width_ptr"

.PP
Definition at line 49 of file eqbandvvv\&.c\&.
.SS "\fBsample_type\fP eqbandvvv_susp_struct::width_x1_sample"

.PP
Definition at line 52 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::z1"

.PP
Definition at line 72 of file eqbandvvv\&.c\&.
.SS "double eqbandvvv_susp_struct::z2"

.PP
Definition at line 73 of file eqbandvvv\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
