.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/event/event.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/event/event.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLV2_Event\fP"
.br
.ti -1c
.RI "struct \fBLV2_Event_Buffer\fP"
.br
.ti -1c
.RI "struct \fBLV2_Event_Feature\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV2_EVENT_URI\fP   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/event'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT_PREFIX\fP   \fBLV2_EVENT_URI\fP '#'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__Event\fP   \fBLV2_EVENT_PREFIX\fP 'Event'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__EventPort\fP   \fBLV2_EVENT_PREFIX\fP 'EventPort'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__FrameStamp\fP   \fBLV2_EVENT_PREFIX\fP 'FrameStamp'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__TimeStamp\fP   \fBLV2_EVENT_PREFIX\fP 'TimeStamp'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__generatesTimeStamp\fP   \fBLV2_EVENT_PREFIX\fP 'generatesTimeStamp'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__generic\fP   \fBLV2_EVENT_PREFIX\fP 'generic'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__inheritsEvent\fP   \fBLV2_EVENT_PREFIX\fP 'inheritsEvent'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__inheritsTimeStamp\fP   \fBLV2_EVENT_PREFIX\fP 'inheritsTimeStamp'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__supportsEvent\fP   \fBLV2_EVENT_PREFIX\fP 'supportsEvent'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT__supportsTimeStamp\fP   \fBLV2_EVENT_PREFIX\fP 'supportsTimeStamp'"
.br
.ti -1c
.RI "#define \fBLV2_EVENT_AUDIO_STAMP\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvoid\fP * \fBLV2_Event_Callback_Data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
C API for the LV2 Event extension http://lv2plug.in/ns/ext/event\&.
.PP
This extension is a generic transport mechanism for time stamped events of any type (e\&.g\&. MIDI, OSC, ramps, etc)\&. Each port can transport mixed events of any type; the type of events and timestamps are defined by a URI which is mapped to an integer by the host for performance reasons\&.
.PP
This extension requires the host to support the LV2 URI Map extension\&. Any host which supports this extension MUST guarantee that any call to the LV2 URI Map uri_to_id function with the URI of this extension as the 'map' argument returns a value within the range of uint16_t\&. 
.PP
Definition in file \fBevent\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV2_EVENT__Event   \fBLV2_EVENT_PREFIX\fP 'Event'"

.PP
Definition at line 39 of file event\&.h\&.
.SS "#define LV2_EVENT__EventPort   \fBLV2_EVENT_PREFIX\fP 'EventPort'"

.PP
Definition at line 40 of file event\&.h\&.
.SS "#define LV2_EVENT__FrameStamp   \fBLV2_EVENT_PREFIX\fP 'FrameStamp'"

.PP
Definition at line 41 of file event\&.h\&.
.SS "#define LV2_EVENT__generatesTimeStamp   \fBLV2_EVENT_PREFIX\fP 'generatesTimeStamp'"

.PP
Definition at line 43 of file event\&.h\&.
.SS "#define LV2_EVENT__generic   \fBLV2_EVENT_PREFIX\fP 'generic'"

.PP
Definition at line 44 of file event\&.h\&.
.SS "#define LV2_EVENT__inheritsEvent   \fBLV2_EVENT_PREFIX\fP 'inheritsEvent'"

.PP
Definition at line 45 of file event\&.h\&.
.SS "#define LV2_EVENT__inheritsTimeStamp   \fBLV2_EVENT_PREFIX\fP 'inheritsTimeStamp'"

.PP
Definition at line 46 of file event\&.h\&.
.SS "#define LV2_EVENT__supportsEvent   \fBLV2_EVENT_PREFIX\fP 'supportsEvent'"

.PP
Definition at line 47 of file event\&.h\&.
.SS "#define LV2_EVENT__supportsTimeStamp   \fBLV2_EVENT_PREFIX\fP 'supportsTimeStamp'"

.PP
Definition at line 48 of file event\&.h\&.
.SS "#define LV2_EVENT__TimeStamp   \fBLV2_EVENT_PREFIX\fP 'TimeStamp'"

.PP
Definition at line 42 of file event\&.h\&.
.SS "#define LV2_EVENT_AUDIO_STAMP   0"

.PP
Definition at line 50 of file event\&.h\&.
.SS "#define LV2_EVENT_PREFIX   \fBLV2_EVENT_URI\fP '#'"

.PP
Definition at line 37 of file event\&.h\&.
.SS "#define LV2_EVENT_URI   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/event'"

.PP
Definition at line 36 of file event\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvoid\fP* \fBLV2_Event_Callback_Data\fP"
Opaque pointer to host data\&. 
.PP
Definition at line 221 of file event\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
