.TH "exp_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exp_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBin\fP"
.br
.ti -1c
.RI "long \fBin_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBin_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file exp\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsound_type\fP exp_susp_struct::in"

.PP
Definition at line 19 of file exp\&.c\&.
.SS "long exp_susp_struct::in_cnt"

.PP
Definition at line 20 of file exp\&.c\&.
.SS "\fBsample_block_values_type\fP exp_susp_struct::in_ptr"

.PP
Definition at line 21 of file exp\&.c\&.
.SS "\fBboolean\fP exp_susp_struct::logically_stopped"

.PP
Definition at line 18 of file exp\&.c\&.
.SS "\fBsnd_susp_node\fP exp_susp_struct::susp"

.PP
Definition at line 16 of file exp\&.c\&.
.SS "long exp_susp_struct::terminate_cnt"

.PP
Definition at line 17 of file exp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
