.TH "C:/_dev/OpenU/Audacity/audacity/src/Experimental.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/Experimental.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/defs\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXPERIMENTAL_FULL_WASAPI\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCIENCE_FILTERS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_KEY_VIEW\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SYNC_LOCK\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_EFFECT_MANAGEMENT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SPECTRAL_EDITING\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_USE_REALFFTF\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_MODULE_PREFS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_REALTIME_AUDACITY_EFFECTS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_NOISE_REDUCTION\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_NYQUIST_SPLIT_CONTROL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SUPPORT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_BASIC\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SMOOTH_SCROLL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCROLLING_LIMITS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_TWO_TONE_TIME_RULER\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_CRASH_REPORT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS\fP"
.br
.ti -1c
.RI "#define \fB__EXPERIMENTAL__\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_FULL_WASAPI\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCIENCE_FILTERS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_KEY_VIEW\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SYNC_LOCK\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_EFFECT_MANAGEMENT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SPECTRAL_EDITING\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_USE_REALFFTF\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_MODULE_PREFS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_REALTIME_AUDACITY_EFFECTS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_NOISE_REDUCTION\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_NYQUIST_SPLIT_CONTROL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SUPPORT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_BASIC\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SMOOTH_SCROLL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_SCROLLING_LIMITS\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_TWO_TONE_TIME_RULER\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_CRASH_REPORT\fP"
.br
.ti -1c
.RI "#define \fBEXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __EXPERIMENTAL__"

.PP
Definition at line 32 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_CRASH_REPORT"

.PP
Definition at line 195 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_CRASH_REPORT"

.SS "#define EXPERIMENTAL_EFFECT_MANAGEMENT"

.PP
Definition at line 80 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_EFFECT_MANAGEMENT"

.SS "#define EXPERIMENTAL_FULL_WASAPI"

.PP
Definition at line 40 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_FULL_WASAPI"

.SS "#define EXPERIMENTAL_KEY_VIEW"

.SS "#define EXPERIMENTAL_KEY_VIEW"

.PP
Definition at line 47 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_MODULE_PREFS"

.PP
Definition at line 150 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_MODULE_PREFS"

.SS "#define EXPERIMENTAL_NOISE_REDUCTION"

.PP
Definition at line 165 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_NOISE_REDUCTION"

.SS "#define EXPERIMENTAL_NYQUIST_SPLIT_CONTROL"

.PP
Definition at line 168 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_NYQUIST_SPLIT_CONTROL"

.SS "#define EXPERIMENTAL_REALTIME_AUDACITY_EFFECTS"

.PP
Definition at line 153 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_REALTIME_AUDACITY_EFFECTS"

.SS "#define EXPERIMENTAL_SCIENCE_FILTERS"

.PP
Definition at line 43 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SCIENCE_FILTERS"

.SS "#define EXPERIMENTAL_SCROLLING_LIMITS"

.PP
Definition at line 186 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SCROLLING_LIMITS"

.SS "#define EXPERIMENTAL_SCRUBBING_BASIC"

.SS "#define EXPERIMENTAL_SCRUBBING_BASIC"

.PP
Definition at line 175 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SCRUBBING_SCROLL_WHEEL"

.SS "#define EXPERIMENTAL_SCRUBBING_SCROLL_WHEEL"

.PP
Definition at line 178 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SCRUBBING_SMOOTH_SCROLL"

.SS "#define EXPERIMENTAL_SCRUBBING_SMOOTH_SCROLL"

.PP
Definition at line 177 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SCRUBBING_SUPPORT"

.SS "#define EXPERIMENTAL_SCRUBBING_SUPPORT"

.PP
Definition at line 172 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SPECTRAL_EDITING"

.PP
Definition at line 106 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_SPECTRAL_EDITING"

.SS "#define EXPERIMENTAL_SYNC_LOCK"

.SS "#define EXPERIMENTAL_SYNC_LOCK"

.PP
Definition at line 50 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_TWO_TONE_TIME_RULER"

.PP
Definition at line 191 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_TWO_TONE_TIME_RULER"

.SS "#define EXPERIMENTAL_USE_REALFFTF"

.PP
Definition at line 113 of file Project\&.h\&.
.SS "#define EXPERIMENTAL_USE_REALFFTF"

.SS "#define EXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS"

.SS "#define EXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS"

.PP
Definition at line 203 of file Project\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
