.TH "C:/_dev/OpenU/Audacity/audacity/src/export/ExportMP2.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/export/ExportMP2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include 'ExportMP2\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
