.TH "Exporter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exporter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Export\&.h>\fP
.PP
Inherits wxEvtHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExporter\fP ()"
.br
.ti -1c
.RI "virtual \fB~Exporter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetFileDialogTitle\fP (\fBconst\fP wxString &DialogTitle)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRegisterPlugin\fP (\fBExportPlugin\fP *plugin)"
.br
.ti -1c
.RI "\fBbool\fP \fBProcess\fP (\fBAudacityProject\fP *project, \fBbool\fP selectedOnly, double t0, double t1)"
.br
.ti -1c
.RI "\fBbool\fP \fBProcess\fP (\fBAudacityProject\fP *project, \fBint\fP numChannels, \fBconst\fP wxChar *type, \fBconst\fP wxString &\fBfilename\fP, \fBbool\fP selectedOnly, double t0, double t1)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDisplayOptions\fP (\fBint\fP index)"
.br
.ti -1c
.RI "\fBint\fP \fBFindFormatIndex\fP (\fBint\fP exportindex)"
.br
.ti -1c
.RI "\fBconst\fP ExportPluginArray \fBGetPlugins\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file Export\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Exporter::Exporter ()"

.PP
Definition at line 270 of file Export\&.cpp\&.
.SS "Exporter::~Exporter ()\fC [virtual]\fP"

.PP
Definition at line 300 of file Export\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Exporter::DisplayOptions (\fBint\fP index)"

.PP
Definition at line 712 of file Export\&.cpp\&.
.SS "\fBint\fP Exporter::FindFormatIndex (\fBint\fP exportindex)"

.PP
Definition at line 318 of file Export\&.cpp\&.
.SS "\fBconst\fP ExportPluginArray Exporter::GetPlugins ()"

.PP
Definition at line 337 of file Export\&.cpp\&.
.SS "\fBbool\fP Exporter::Process (\fBAudacityProject\fP * project, \fBbool\fP selectedOnly, double t0, double t1)"

.PP
Definition at line 342 of file Export\&.cpp\&.
.SS "\fBbool\fP Exporter::Process (\fBAudacityProject\fP * project, \fBint\fP numChannels, \fBconst\fP wxChar * type, \fBconst\fP wxString & filename, \fBbool\fP selectedOnly, double t0, double t1)"

.PP
Definition at line 389 of file Export\&.cpp\&.
.SS "\fBvoid\fP Exporter::RegisterPlugin (\fBExportPlugin\fP * plugin)"

.PP
Definition at line 332 of file Export\&.cpp\&.
.SS "\fBvoid\fP Exporter::SetFileDialogTitle (\fBconst\fP wxString & DialogTitle)"

.PP
Definition at line 312 of file Export\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
