.TH "ExportPlugin" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExportPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Export\&.h>\fP
.PP
Inherited by \fBExportCL\fP, \fBExportMP3\fP, and \fBExportPCM\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportPlugin\fP ()"
.br
.ti -1c
.RI "virtual \fB~ExportPlugin\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBDestroy\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBAddFormat\fP ()"
.br
.RI "\fIAdd a NEW entry to the list of formats this plug-in can export\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBSetFormat\fP (\fBconst\fP wxString &\fBformat\fP, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetDescription\fP (\fBconst\fP wxString &description, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddExtension\fP (\fBconst\fP wxString &extension, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetExtensions\fP (\fBconst\fP wxArrayString &extensions, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetMask\fP (\fBconst\fP wxString &\fBmask\fP, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetMaxChannels\fP (\fBint\fP maxchannels, \fBint\fP index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCanMetaData\fP (\fBbool\fP canmetadata, \fBint\fP index)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBGetFormatCount\fP ()"
.br
.ti -1c
.RI "virtual wxString \fBGetFormat\fP (\fBint\fP index)"
.br
.ti -1c
.RI "virtual wxString \fBGetDescription\fP (\fBint\fP index)"
.br
.ti -1c
.RI "virtual wxString \fBGetExtension\fP (\fBint\fP index=0)"
.br
.RI "\fIReturn the (first) file name extension for the sub-format\&. \fP"
.ti -1c
.RI "virtual wxArrayString \fBGetExtensions\fP (\fBint\fP index=0)"
.br
.RI "\fIReturn all the file name extensions used for the sub-format\&. \fP"
.ti -1c
.RI "virtual wxString \fBGetMask\fP (\fBint\fP index)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBGetMaxChannels\fP (\fBint\fP index)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetCanMetaData\fP (\fBint\fP index)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBIsExtension\fP (\fBconst\fP wxString &ext, \fBint\fP index)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBDisplayOptions\fP (wxWindow *parent, \fBint\fP \fBformat\fP=0)"
.br
.ti -1c
.RI "virtual wxWindow * \fBOptionsCreate\fP (wxWindow *parent, \fBint\fP \fBformat\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBCheckFileName\fP (wxFileName &\fBfilename\fP, \fBint\fP \fBformat\fP=0)"
.br
.ti -1c
.RI "virtual \fBint\fP \fBExport\fP (\fBAudacityProject\fP *project, \fBint\fP channels, \fBconst\fP wxString &fName, \fBbool\fP selectedOnly, double t0, double t1, \fBMixerSpec\fP *mixerSpec=\fBNULL\fP, \fBconst\fP \fBTags\fP *metadata=\fBNULL\fP, \fBint\fP subformat=0)=0"
.br
.RI "\fIcalled to export audio into a file\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMixer\fP * \fBCreateMixer\fP (\fBconst\fP \fBWaveTrackConstArray\fP &inputTracks, \fBconst\fP \fBTimeTrack\fP *timeTrack, double startTime, double stopTime, \fBint\fP numOutChannels, \fBint\fP outBufferSize, \fBbool\fP outInterleaved, double outRate, \fBsampleFormat\fP outFormat, \fBbool\fP highQuality=\fBtrue\fP, \fBMixerSpec\fP *mixerSpec=\fBNULL\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file Export\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExportPlugin::ExportPlugin ()"

.PP
Definition at line 81 of file Export\&.cpp\&.
.SS "ExportPlugin::~ExportPlugin ()\fC [virtual]\fP"

.PP
Definition at line 86 of file Export\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ExportPlugin::AddExtension (\fBconst\fP wxString & extension, \fBint\fP index)"

.PP
Definition at line 134 of file Export\&.cpp\&.
.SS "\fBint\fP ExportPlugin::AddFormat ()"

.PP
Add a NEW entry to the list of formats this plug-in can export\&. To configure the format use SetFormat, SetCanMetaData etc with the index of the format\&. 
.PP
\fBReturns:\fP
.RS 4
The number of formats currently set up\&. This is one more than the index of the newly added format\&. 
.RE
.PP

.PP
Definition at line 103 of file Export\&.cpp\&.
.SS "\fBbool\fP ExportPlugin::CheckFileName (wxFileName & filename, \fBint\fP format = \fC0\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBExportMP3\fP, and \fBExportPCM\fP\&.
.PP
Definition at line 91 of file Export\&.cpp\&.
.SS "\fBMixer\fP * ExportPlugin::CreateMixer (\fBconst\fP \fBWaveTrackConstArray\fP & inputTracks, \fBconst\fP \fBTimeTrack\fP * timeTrack, double startTime, double stopTime, \fBint\fP numOutChannels, \fBint\fP outBufferSize, \fBbool\fP outInterleaved, double outRate, \fBsampleFormat\fP outFormat, \fBbool\fP highQuality = \fC\fBtrue\fP\fP, \fBMixerSpec\fP * mixerSpec = \fC\fBNULL\fP\fP)\fC [protected]\fP"

.PP
Definition at line 246 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::Destroy ()\fC [virtual]\fP"

.PP
Reimplemented in \fBExportMP3\fP, \fBExportPCM\fP, and \fBExportCL\fP\&.
.PP
Definition at line 115 of file Export\&.cpp\&.
.SS "\fBbool\fP ExportPlugin::DisplayOptions (wxWindow * parent, \fBint\fP format = \fC0\fP)\fC [virtual]\fP"

.PP
Definition at line 221 of file Export\&.cpp\&.
.SS "virtual \fBint\fP ExportPlugin::Export (\fBAudacityProject\fP * project, \fBint\fP channels, \fBconst\fP wxString & fName, \fBbool\fP selectedOnly, double t0, double t1, \fBMixerSpec\fP * mixerSpec = \fC\fBNULL\fP\fP, \fBconst\fP \fBTags\fP * metadata = \fC\fBNULL\fP\fP, \fBint\fP subformat = \fC0\fP)\fC [pure virtual]\fP"

.PP
called to export audio into a file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIselectedOnly\fP Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported\&. 
.br
\fImetadata\fP A \fBTags\fP object that will over-ride the one in *project and be used to tag the file that is exported\&. 
.br
\fIsubformat\fP Control which of the multiple formats this exporter is capable of exporting should be used\&. Used where a single export plug-in handles a number of related formats, but they have separate entries in the \fBFormat\fP drop-down list box\&. For example, the options to export to 'Other PCM', 'AIFF 16 Bit' and 'WAV 16 Bit' are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively\&. 
.RE
.PP

.PP
Implemented in \fBExportMP3\fP, \fBExportPCM\fP, and \fBExportCL\fP\&.
.SS "\fBbool\fP ExportPlugin::GetCanMetaData (\fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 202 of file Export\&.cpp\&.
.SS "wxString ExportPlugin::GetDescription (\fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 164 of file Export\&.cpp\&.
.SS "wxString ExportPlugin::GetExtension (\fBint\fP index = \fC0\fP)\fC [virtual]\fP"

.PP
Return the (first) file name extension for the sub-format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP The sub-format for which the extension is wanted 
.RE
.PP

.PP
Reimplemented in \fBExportPCM\fP\&.
.PP
Definition at line 169 of file Export\&.cpp\&.
.SS "wxArrayString ExportPlugin::GetExtensions (\fBint\fP index = \fC0\fP)\fC [virtual]\fP"

.PP
Return all the file name extensions used for the sub-format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP the sub-format for which the extension is required 
.RE
.PP

.PP
Definition at line 174 of file Export\&.cpp\&.
.SS "wxString ExportPlugin::GetFormat (\fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 159 of file Export\&.cpp\&.
.SS "\fBint\fP ExportPlugin::GetFormatCount ()\fC [virtual]\fP"

.PP
Definition at line 110 of file Export\&.cpp\&.
.SS "wxString ExportPlugin::GetMask (\fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 179 of file Export\&.cpp\&.
.SS "\fBint\fP ExportPlugin::GetMaxChannels (\fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 197 of file Export\&.cpp\&.
.SS "\fBbool\fP ExportPlugin::IsExtension (\fBconst\fP wxString & ext, \fBint\fP index)\fC [virtual]\fP"

.PP
Definition at line 207 of file Export\&.cpp\&.
.SS "wxWindow * ExportPlugin::OptionsCreate (wxWindow * parent, \fBint\fP format)\fC [pure virtual]\fP"

.PP
Implemented in \fBExportMP3\fP, \fBExportPCM\fP, and \fBExportCL\fP\&.
.PP
Definition at line 226 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetCanMetaData (\fBbool\fP canmetadata, \fBint\fP index)"

.PP
Definition at line 154 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetDescription (\fBconst\fP wxString & description, \fBint\fP index)"

.PP
Definition at line 129 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetExtensions (\fBconst\fP wxArrayString & extensions, \fBint\fP index)"

.PP
Definition at line 139 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetFormat (\fBconst\fP wxString & format, \fBint\fP index)"

.PP
\fBParameters:\fP
.RS 4
\fIindex\fP The plugin to set the format for (range 0 to one less than the count of formats) 
.RE
.PP

.PP
Definition at line 124 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetMask (\fBconst\fP wxString & mask, \fBint\fP index)"

.PP
Definition at line 144 of file Export\&.cpp\&.
.SS "\fBvoid\fP ExportPlugin::SetMaxChannels (\fBint\fP maxchannels, \fBint\fP index)"

.PP
Definition at line 149 of file Export\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
