.TH "ExportMP3" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExportMP3 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExportPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportMP3\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBDestroy\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBCheckFileName\fP (wxFileName &\fBfilename\fP, \fBint\fP \fBformat\fP)"
.br
.ti -1c
.RI "wxWindow * \fBOptionsCreate\fP (wxWindow *parent, \fBint\fP \fBformat\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBExport\fP (\fBAudacityProject\fP *project, \fBint\fP channels, \fBconst\fP wxString &fName, \fBbool\fP selectedOnly, double t0, double t1, \fBMixerSpec\fP *mixerSpec=\fBNULL\fP, \fBconst\fP \fBTags\fP *metadata=\fBNULL\fP, \fBint\fP subformat=0) override"
.br
.RI "\fIcalled to export audio into a file\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1554 of file ExportMP3\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExportMP3::ExportMP3 ()"

.PP
Definition at line 1586 of file ExportMP3\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP ExportMP3::CheckFileName (wxFileName & filename, \fBint\fP format)\fC [virtual]\fP"

.PP
Reimplemented from \fBExportPlugin\fP\&.
.PP
Definition at line 1603 of file ExportMP3\&.cpp\&.
.SS "\fBvoid\fP ExportMP3::Destroy ()\fC [virtual]\fP"

.PP
Reimplemented from \fBExportPlugin\fP\&.
.PP
Definition at line 1598 of file ExportMP3\&.cpp\&.
.SS "\fBint\fP ExportMP3::Export (\fBAudacityProject\fP * project, \fBint\fP channels, \fBconst\fP wxString & fName, \fBbool\fP selectedOnly, double t0, double t1, \fBMixerSpec\fP * mixerSpec = \fC\fBNULL\fP\fP, \fBconst\fP \fBTags\fP * metadata = \fC\fBNULL\fP\fP, \fBint\fP subformat = \fC0\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
called to export audio into a file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIselectedOnly\fP Set to true if all tracks should be mixed, to false if only the selected tracks should be mixed and exported\&. 
.br
\fImetadata\fP A \fBTags\fP object that will over-ride the one in *project and be used to tag the file that is exported\&. 
.br
\fIsubformat\fP Control which of the multiple formats this exporter is capable of exporting should be used\&. Used where a single export plug-in handles a number of related formats, but they have separate entries in the \fBFormat\fP drop-down list box\&. For example, the options to export to 'Other PCM', 'AIFF 16 Bit' and 'WAV 16 Bit' are all the same libsndfile export plug-in, but with subformat set to 0, 1, and 2 respectively\&. 
.RE
.PP

.PP
Implements \fBExportPlugin\fP\&.
.PP
Definition at line 1620 of file ExportMP3\&.cpp\&.
.SS "wxWindow * ExportMP3::OptionsCreate (wxWindow * parent, \fBint\fP format)\fC [virtual]\fP"

.PP
Implements \fBExportPlugin\fP\&.
.PP
Definition at line 1868 of file ExportMP3\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
