.TH "C:/_dev/OpenU/Audacity/audacity/src/export/ExportPCM.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/export/ExportPCM.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include 'ExportPCM\&.h'\fP
.br
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/choice\&.h>\fP
.br
\fC#include <wx/dynlib\&.h>\fP
.br
\fC#include <wx/filename\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/timer\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/progdlg\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/window\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include '\&.\&./FileFormats\&.h'\fP
.br
\fC#include '\&.\&./Internat\&.h'\fP
.br
\fC#include '\&.\&./Mix\&.h'\fP
.br
\fC#include '\&.\&./Prefs\&.h'\fP
.br
\fC#include '\&.\&./Project\&.h'\fP
.br
\fC#include '\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include '\&.\&./Tags\&.h'\fP
.br
\fC#include '\&.\&./Track\&.h'\fP
.br
\fC#include '\&.\&./ondemand/ODManager\&.h'\fP
.br
\fC#include 'Export\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExportPCMOptions\fP"
.br
.ti -1c
.RI "class \fBExportPCM\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBID_HEADER_CHOICE\fP   7102"
.br
.ti -1c
.RI "#define \fBID_ENCODING_CHOICE\fP   7103"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBExportPlugin\fP * \fBNew_ExportPCM\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBint\fP \fBformat\fP"
.br
.ti -1c
.RI "   \fBconst\fP wxChar * \fBname\fP"
.br
.ti -1c
.RI "   \fBconst\fP wxChar * \fBdesc\fP"
.br
.ti -1c
.RI "} \fBkFormats\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ID_ENCODING_CHOICE   7103"

.PP
Definition at line 93 of file ExportPCM\&.cpp\&.
.SS "#define ID_HEADER_CHOICE   7102"

.PP
Definition at line 92 of file ExportPCM\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBExportPlugin\fP* New_ExportPCM ()"
The only part of this class which is publically accessible is the factory method \fBNew_ExportPCM()\fP which creates a NEW \fBExportPCM\fP object and returns a pointer to it\&. The rest of the class declaration is in \fBExportPCM\&.cpp\fP 
.PP
Definition at line 918 of file ExportPCM\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP wxChar* desc"

.PP
Definition at line 57 of file ExportPCM\&.cpp\&.
.SS "\fBint\fP format"

.PP
Definition at line 55 of file ExportPCM\&.cpp\&.
.SS "struct { \&.\&.\&. }  kFormats[]"
\fBInitial value:\fP
.PP
.nf
=
{
   { SF_FORMAT_AIFF | SF_FORMAT_PCM_16,   wxT("AIFF"),   XO("AIFF (Apple) signed 16-bit PCM")    },
   { SF_FORMAT_WAV | SF_FORMAT_PCM_16,    wxT("WAV"),    XO("WAV (Microsoft) signed 16-bit PCM") },
   { SF_FORMAT_WAV | SF_FORMAT_FLOAT,     wxT("WAVFLT"), XO("WAV (Microsoft) 32-bit float PCM")  },

}
.fi
.SS "\fBconst\fP wxChar* \fBname\fP"

.PP
Definition at line 56 of file ExportPCM\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
