.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/extern.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/extern.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'extern\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxtype_desc\fP \fBcreate_desc\fP (char *type_name, \fBvoid\fP(*fm)(\fBvoid\fP *), \fBvoid\fP(*pm)(\fBvoid\fP *, \fBvoid\fP *), \fBvoid\fP(*sm)(FILE *, \fBvoid\fP *), unsigned char *(*rm)(FILE *), \fBvoid\fP(*mm)(\fBvoid\fP *))"
.br
.ti -1c
.RI "\fBLVAL\fP \fBcvextern\fP (\fBxtype_desc\fP typeptr, unsigned char *instptr)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBexttype\fP (\fBLVAL\fP x)"
.br
.ti -1c
.RI "\fBint\fP \fBexttypep\fP (\fBLVAL\fP x, \fBLVAL\fP type_sym)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinval_caches\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBextindex\fP = 0"
.br
.ti -1c
.RI "struct \fBxtype_desc_struct\fP \fBdesc_table\fP [\fBNTYPES\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBxtype_desc\fP create_desc (char * type_name, \fBvoid\fP(*)(\fBvoid\fP *) fm, \fBvoid\fP(*)(\fBvoid\fP *, \fBvoid\fP *) pm, \fBvoid\fP(*)(FILE *, \fBvoid\fP *) sm, unsigned char *(*)(FILE *) rm, \fBvoid\fP(*)(\fBvoid\fP *) mm)"

.PP
Definition at line 57 of file extern\&.c\&.
.SS "\fBLVAL\fP cvextern (\fBxtype_desc\fP typeptr, unsigned char * instptr)"

.PP
Definition at line 81 of file extern\&.c\&.
.SS "\fBLVAL\fP exttype (\fBLVAL\fP x)"

.PP
Definition at line 95 of file extern\&.c\&.
.SS "\fBint\fP exttypep (\fBLVAL\fP x, \fBLVAL\fP type_sym)"

.PP
Definition at line 109 of file extern\&.c\&.
.SS "\fBvoid\fP inval_caches (\fBvoid\fP)"

.PP
Definition at line 123 of file extern\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBxtype_desc_struct\fP desc_table[\fBNTYPES\fP]"

.PP
Definition at line 52 of file extern\&.c\&.
.SS "\fBint\fP extindex = 0"

.PP
Definition at line 50 of file extern\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
