.TH "ExtImportItem" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtImportItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Import\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxArrayString \fBfilters\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdivider\fP"
.br
.ti -1c
.RI "ImportPluginPtrArray \fBfilter_objects\fP"
.br
.ti -1c
.RI "wxArrayString \fBextensions\fP"
.br
.ti -1c
.RI "wxArrayString \fBmime_types\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file Import\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP ExtImportItem::divider"
The index of first unused filter in  array 0 - divider is at the top of the list (in the list control it will be the highest item), all filters are unused -1 - divider is at the bottom of the list (in the list control it will be the lowest item), all filters are used 
.PP
Definition at line 66 of file Import\&.h\&.
.SS "wxArrayString ExtImportItem::extensions"
File extensions\&. Each one is a string with simple wildcards, i\&.e\&. '*\&.wav'\&. 
.PP
Definition at line 77 of file Import\&.h\&.
.SS "ImportPluginPtrArray ExtImportItem::filter_objects"
Array of pointers to import plugins (members of FormatList) 
.PP
Definition at line 71 of file Import\&.h\&.
.SS "wxArrayString ExtImportItem::filters"
Unique string ID exists for each filter, it is not translateable and can be stored in config\&. This ID is matched internally with a translated name of a filter\&. Unknown IDs will be presented and saved as-is\&. Unused filters will not be used for matching files, unless forced\&. 
.PP
Definition at line 57 of file Import\&.h\&.
.SS "wxArrayString ExtImportItem::mime_types"
Mime-types\&. Each one is a string in form of 'foo/bar-baz' or something like that\&. 
.PP
Definition at line 83 of file Import\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
