.TH "ExtImportPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtImportPrefs \- A \fBPrefsPanel\fP used to select extended import filter options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExtImportPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtImportPrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fB~ExtImportPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPluginKeyDown\fP (wxListEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPluginBeginDrag\fP (wxListEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleTableKeyDown\fP (wxKeyEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleTableSelect\fP (wxGridEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleTableEdit\fP (wxGridEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleTableSelectRange\fP (wxGridRangeSelectEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleTableCellClick\fP (wxGridEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnAddRule\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnDelRule\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleMoveUp\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnRuleMoveDown\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnFilterMoveUp\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnFilterMoveDown\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnNavKey\fP (wxNavigationKeyEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSwapRows\fP (\fBint\fP row1, \fBint\fP row2)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSwapPluginRows\fP (\fBint\fP row1, \fBint\fP row2)"
.br
.ti -1c
.RI "\fBGrid\fP * \fBGetRuleTable\fP ()"
.br
.ti -1c
.RI "wxListCtrl * \fBGetPluginList\fP ()"
.br
.ti -1c
.RI "wxWindow * \fBGetDragFocus\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP used to select extended import filter options\&. 
.PP
Definition at line 45 of file ExtImportPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExtImportPrefs::ExtImportPrefs (wxWindow * parent)"

.PP
Definition at line 58 of file ExtImportPrefs\&.cpp\&.
.SS "ExtImportPrefs::~ExtImportPrefs ()"

.PP
Definition at line 72 of file ExtImportPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP ExtImportPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 173 of file ExtImportPrefs\&.cpp\&.
.SS "wxWindow* ExtImportPrefs::GetDragFocus ()\fC [inline]\fP"

.PP
Definition at line 74 of file ExtImportPrefs\&.h\&.
.SS "wxListCtrl* ExtImportPrefs::GetPluginList ()\fC [inline]\fP"

.PP
Definition at line 72 of file ExtImportPrefs\&.h\&.
.SS "\fBGrid\fP* ExtImportPrefs::GetRuleTable ()\fC [inline]\fP"

.PP
Definition at line 71 of file ExtImportPrefs\&.h\&.
.SS "\fBvoid\fP ExtImportPrefs::OnAddRule (wxCommandEvent & event)"

.PP
Definition at line 556 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnDelRule (wxCommandEvent & event)"

.PP
Definition at line 568 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnFilterMoveDown (wxCommandEvent & event)"

.PP
Definition at line 616 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnFilterMoveUp (wxCommandEvent & event)"

.PP
Definition at line 611 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnNavKey (wxNavigationKeyEvent & event)"

.SS "\fBvoid\fP ExtImportPrefs::OnPluginBeginDrag (wxListEvent & event)"

.PP
Definition at line 313 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnPluginKeyDown (wxListEvent & event)"

.PP
Definition at line 181 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleMoveDown (wxCommandEvent & event)"

.PP
Definition at line 596 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleMoveUp (wxCommandEvent & event)"

.PP
Definition at line 591 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleTableCellClick (wxGridEvent & event)"

.PP
Definition at line 622 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleTableEdit (wxGridEvent & event)"

.PP
Definition at line 451 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleTableKeyDown (wxKeyEvent & event)"

.PP
Definition at line 333 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleTableSelect (wxGridEvent & event)"

.PP
Definition at line 369 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::OnRuleTableSelectRange (wxGridRangeSelectEvent & event)"

.PP
Definition at line 383 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::SwapPluginRows (\fBint\fP row1, \fBint\fP row2)"

.PP
Definition at line 198 of file ExtImportPrefs\&.cpp\&.
.SS "\fBvoid\fP ExtImportPrefs::SwapRows (\fBint\fP row1, \fBint\fP row2)"

.PP
Definition at line 287 of file ExtImportPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
