.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/Fade.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/Fade.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'Effect\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffectFade\fP"
.br
.RI "\fIAn \fBEffect\fP that reduces the volume to zero over achosen interval\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFADEIN_PLUGIN_SYMBOL\fP   \fBXO\fP('Fade \fBIn\fP')"
.br
.ti -1c
.RI "#define \fBFADEOUT_PLUGIN_SYMBOL\fP   \fBXO\fP('Fade \fBOut\fP')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FADEIN_PLUGIN_SYMBOL   \fBXO\fP('Fade \fBIn\fP')"

.PP
Definition at line 18 of file Fade\&.h\&.
.SS "#define FADEOUT_PLUGIN_SYMBOL   \fBXO\fP('Fade \fBOut\fP')"

.PP
Definition at line 19 of file Fade\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
