.TH "C:/_dev/OpenU/Audacity/audacity/win/LADSPA_plugins-win/glibc_includes/features.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/win/LADSPA_plugins-win/glibc_includes/features.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/cdefs\&.h>\fP
.br
\fC#include <gnu/stubs\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__KERNEL_STRICT_NAMES\fP"
.br
.ti -1c
.RI "#define \fB__USE_ANSI\fP   1"
.br
.ti -1c
.RI "#define \fB__GNUC_PREREQ\fP(maj,  \fBmin\fP)   0"
.br
.ti -1c
.RI "#define \fB_BSD_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_SVID_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_POSIX_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_POSIX_C_SOURCE\fP   200112L"
.br
.ti -1c
.RI "#define \fB__USE_POSIX\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX2\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX199309\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX199506\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_XOPEN2K\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_MISC\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_BSD\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_SVID\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_FORTIFY_LEVEL\fP   0"
.br
.ti -1c
.RI "#define \fB__STDC_IEC_559__\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_IEC_559_COMPLEX__\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_ISO_10646__\fP   200009L"
.br
.ti -1c
.RI "#define \fB__GNU_LIBRARY__\fP   6"
.br
.ti -1c
.RI "#define \fB__GLIBC__\fP   2"
.br
.ti -1c
.RI "#define \fB__GLIBC_MINOR__\fP   4"
.br
.ti -1c
.RI "#define \fB__GLIBC_PREREQ\fP(maj,  \fBmin\fP)   ((\fB__GLIBC__\fP << 16) + \fB__GLIBC_MINOR__\fP >= ((maj) << 16) + (\fBmin\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __GLIBC__   2"

.PP
Definition at line 306 of file features\&.h\&.
.SS "#define __GLIBC_MINOR__   4"

.PP
Definition at line 307 of file features\&.h\&.
.SS "#define __GLIBC_PREREQ(maj, \fBmin\fP)   ((\fB__GLIBC__\fP << 16) + \fB__GLIBC_MINOR__\fP >= ((maj) << 16) + (\fBmin\fP))"

.PP
Definition at line 309 of file features\&.h\&.
.SS "#define __GNU_LIBRARY__   6"

.PP
Definition at line 302 of file features\&.h\&.
.SS "#define __GNUC_PREREQ(maj, \fBmin\fP)   0"

.PP
Definition at line 135 of file features\&.h\&.
.SS "#define __KERNEL_STRICT_NAMES"

.PP
Definition at line 118 of file features\&.h\&.
.SS "#define __STDC_IEC_559__   1"

.PP
Definition at line 289 of file features\&.h\&.
.SS "#define __STDC_IEC_559_COMPLEX__   1"

.PP
Definition at line 290 of file features\&.h\&.
.SS "#define __STDC_ISO_10646__   200009L"

.PP
Definition at line 293 of file features\&.h\&.
.SS "#define __USE_ANSI   1"

.PP
Definition at line 122 of file features\&.h\&.
.SS "#define __USE_BSD   1"

.PP
Definition at line 258 of file features\&.h\&.
.SS "#define __USE_FORTIFY_LEVEL   0"

.PP
Definition at line 285 of file features\&.h\&.
.SS "#define __USE_MISC   1"

.PP
Definition at line 254 of file features\&.h\&.
.SS "#define __USE_POSIX   1"

.PP
Definition at line 203 of file features\&.h\&.
.SS "#define __USE_POSIX199309   1"

.PP
Definition at line 211 of file features\&.h\&.
.SS "#define __USE_POSIX199506   1"

.PP
Definition at line 215 of file features\&.h\&.
.SS "#define __USE_POSIX2   1"

.PP
Definition at line 207 of file features\&.h\&.
.SS "#define __USE_SVID   1"

.PP
Definition at line 262 of file features\&.h\&.
.SS "#define __USE_XOPEN2K   1"

.PP
Definition at line 219 of file features\&.h\&.
.SS "#define _BSD_SOURCE   1"

.PP
Definition at line 175 of file features\&.h\&.
.SS "#define _POSIX_C_SOURCE   200112L"

.PP
Definition at line 198 of file features\&.h\&.
.SS "#define _POSIX_SOURCE   1"

.PP
Definition at line 192 of file features\&.h\&.
.SS "#define _SVID_SOURCE   1"

.PP
Definition at line 176 of file features\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
