.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/ffilterkit.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/ffilterkit.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'stdefs\&.h'\fP
.br
\fC#include 'fresample\&.h'\fP
.br
\fC#include 'ffilterkit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfast_float\fP \fBFilterUp\fP (float Imp[], float ImpD[], \fBint\fP Nwing, \fBboolean\fP Interp, float *Xp, double Ph, \fBint\fP Inc)"
.br
.ti -1c
.RI "\fBfast_float\fP \fBFilterUD\fP (float Imp[], float ImpD[], \fBint\fP Nwing, \fBboolean\fP Interp, float *Xp, double Ph, \fBint\fP Inc, double dhb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfast_float\fP FilterUD (float Imp[], float ImpD[], \fBint\fP Nwing, \fBboolean\fP Interp, float * Xp, double Ph, \fBint\fP Inc, double dhb)"

.PP
Definition at line 78 of file ffilterkit\&.c\&.
.SS "\fBfast_float\fP FilterUp (float Imp[], float ImpD[], \fBint\fP Nwing, \fBboolean\fP Interp, float * Xp, double Ph, \fBint\fP Inc)"

.PP
Definition at line 26 of file ffilterkit\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
