.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/ffts/Timing-code/fftTiming.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/ffts/Timing-code/fftTiming.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fp\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'fftlib\&.h'\fP
.br
\fC#include 'fftext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBComplex\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNSIZES\fP   3		/* \fBthe\fP number \fBof\fP different \fBffts\fP sizes to time */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBfour1\fP (float \fBdata\fP[], unsigned long nn, \fBint\fP isign)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NSIZES   3		/* \fBthe\fP number \fBof\fP different \fBffts\fP sizes to time */"

.PP
Definition at line 15 of file fftTiming\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP four1 (float data[], unsigned long nn, \fBint\fP isign)"

.SS "\fBvoid\fP main (\fBvoid\fP)"

.PP
Definition at line 22 of file fftTiming\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
