.TH "fftw_plan_node_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fftw_plan_node_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fftw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBfftw_node_type\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_notw_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBconst\fP \fBfftw_codelet_desc\fP * \fBcodelet_desc\fP"
.br
.ti -1c
.RI "   } \fBnotw\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle\fP * \fBtw\fP"
.br
.ti -1c
.RI "      struct \fBfftw_plan_node_struct\fP * \fBrecurse\fP"
.br
.ti -1c
.RI "      \fBconst\fP \fBfftw_codelet_desc\fP * \fBcodelet_desc\fP"
.br
.ti -1c
.RI "   } \fBtwiddle\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_generic_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle\fP * \fBtw\fP"
.br
.ti -1c
.RI "      struct \fBfftw_plan_node_struct\fP * \fBrecurse\fP"
.br
.ti -1c
.RI "   } \fBgeneric\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_rader_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBfftw_rader_data\fP * \fBrader_data\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle\fP * \fBtw\fP"
.br
.ti -1c
.RI "      struct \fBfftw_plan_node_struct\fP * \fBrecurse\fP"
.br
.ti -1c
.RI "   } \fBrader\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_real2hc_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBconst\fP \fBfftw_codelet_desc\fP * \fBcodelet_desc\fP"
.br
.ti -1c
.RI "   } \fBreal2hc\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_hc2real_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBconst\fP \fBfftw_codelet_desc\fP * \fBcodelet_desc\fP"
.br
.ti -1c
.RI "   } \fBhc2real\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_direction\fP \fBdir\fP"
.br
.ti -1c
.RI "      \fBfftw_hc2hc_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle\fP * \fBtw\fP"
.br
.ti -1c
.RI "      struct \fBfftw_plan_node_struct\fP * \fBrecurse\fP"
.br
.ti -1c
.RI "      \fBconst\fP \fBfftw_codelet_desc\fP * \fBcodelet_desc\fP"
.br
.ti -1c
.RI "   } \fBhc2hc\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBint\fP \fBsize\fP"
.br
.ti -1c
.RI "      \fBfftw_direction\fP \fBdir\fP"
.br
.ti -1c
.RI "      \fBfftw_rgeneric_codelet\fP * \fBcodelet\fP"
.br
.ti -1c
.RI "      \fBfftw_twiddle\fP * \fBtw\fP"
.br
.ti -1c
.RI "      struct \fBfftw_plan_node_struct\fP * \fBrecurse\fP"
.br
.ti -1c
.RI "   } \fBrgeneric\fP"
.br
.ti -1c
.RI "} \fBnodeu\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefcnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 187 of file fftw\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfftw_notw_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 194 of file fftw\&.h\&.
.SS "\fBfftw_twiddle_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 201 of file fftw\&.h\&.
.SS "\fBfftw_generic_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 210 of file fftw\&.h\&.
.SS "\fBfftw_rader_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 218 of file fftw\&.h\&.
.SS "\fBfftw_real2hc_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 227 of file fftw\&.h\&.
.SS "\fBfftw_hc2real_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 234 of file fftw\&.h\&.
.SS "\fBfftw_hc2hc_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 242 of file fftw\&.h\&.
.SS "\fBfftw_rgeneric_codelet\fP* fftw_plan_node_struct::codelet"

.PP
Definition at line 252 of file fftw\&.h\&.
.SS "\fBconst\fP \fBfftw_codelet_desc\fP* fftw_plan_node_struct::codelet_desc"

.PP
Definition at line 195 of file fftw\&.h\&.
.SS "\fBfftw_direction\fP fftw_plan_node_struct::dir"

.PP
Definition at line 241 of file fftw\&.h\&.
.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::generic"

.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::hc2hc"

.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::hc2real"

.SS "union { \&.\&.\&. }   fftw_plan_node_struct::nodeu"

.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::notw"

.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::rader"

.SS "\fBfftw_rader_data\fP* fftw_plan_node_struct::rader_data"

.PP
Definition at line 219 of file fftw\&.h\&.
.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::real2hc"

.SS "struct \fBfftw_plan_node_struct\fP* fftw_plan_node_struct::recurse"

.PP
Definition at line 203 of file fftw\&.h\&.
.SS "\fBint\fP fftw_plan_node_struct::refcnt"

.PP
Definition at line 258 of file fftw\&.h\&.
.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::rgeneric"

.SS "\fBint\fP fftw_plan_node_struct::size"

.PP
Definition at line 193 of file fftw\&.h\&.
.SS "\fBfftw_twiddle\fP* fftw_plan_node_struct::tw"

.PP
Definition at line 202 of file fftw\&.h\&.
.SS "struct { \&.\&.\&. }   fftw_plan_node_struct::twiddle"

.SS "enum \fBfftw_node_type\fP fftw_plan_node_struct::type"

.PP
Definition at line 188 of file fftw\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
