.TH "fftw_iodim_do_not_use_me" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fftw_iodim_do_not_use_me \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fftw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBn\fP"
.br
.ti -1c
.RI "\fBint\fP \fBis\fP"
.br
.ti -1c
.RI "\fBint\fP \fBos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file fftw3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP fftw_iodim_do_not_use_me::is"

.PP
Definition at line 103 of file fftw3\&.h\&.
.SS "\fBint\fP fftw_iodim_do_not_use_me::n"

.PP
Definition at line 102 of file fftw3\&.h\&.
.SS "\fBint\fP fftw_iodim_do_not_use_me::os"

.PP
Definition at line 104 of file fftw3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
