.TH "C:/_dev/OpenU/Audacity/audacity/win/LADSPA_plugins-win/fftw3.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/win/LADSPA_plugins-win/fftw3.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfftw_iodim_do_not_use_me\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFFTW_DEFINE_COMPLEX\fP(R,  C)   typedef R C[2]"
.br
.ti -1c
.RI "#define \fBFFTW_CONCAT\fP(\fBprefix\fP,  \fBname\fP)   \fBprefix\fP ## \fBname\fP"
.br
.ti -1c
.RI "#define \fBFFTW_MANGLE_DOUBLE\fP(\fBname\fP)   \fBFFTW_CONCAT\fP(fftw_, \fBname\fP)"
.br
.ti -1c
.RI "#define \fBFFTW_MANGLE_FLOAT\fP(\fBname\fP)   \fBFFTW_CONCAT\fP(fftwf_, \fBname\fP)"
.br
.ti -1c
.RI "#define \fBFFTW_MANGLE_LONG_DOUBLE\fP(\fBname\fP)   \fBFFTW_CONCAT\fP(fftwl_, \fBname\fP)"
.br
.ti -1c
.RI "#define \fBFFTW_DLL\fP"
.br
.ti -1c
.RI "#define \fBFFTW_EXTERN\fP   extern"
.br
.ti -1c
.RI "#define \fBFFTW_DEFINE_API\fP(X,  R,  C)  "
.br
.ti -1c
.RI "#define \fBFFTW_FORWARD\fP   (\-1)"
.br
.ti -1c
.RI "#define \fBFFTW_BACKWARD\fP   (+1)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_TIMELIMIT\fP   (\-1\&.0)"
.br
.ti -1c
.RI "#define \fBFFTW_MEASURE\fP   (0U)"
.br
.ti -1c
.RI "#define \fBFFTW_DESTROY_INPUT\fP   (1U << 0)"
.br
.ti -1c
.RI "#define \fBFFTW_UNALIGNED\fP   (1U << 1)"
.br
.ti -1c
.RI "#define \fBFFTW_CONSERVE_MEMORY\fP   (1U << 2)"
.br
.ti -1c
.RI "#define \fBFFTW_EXHAUSTIVE\fP   (1U << 3) /* NO_EXHAUSTIVE is default */"
.br
.ti -1c
.RI "#define \fBFFTW_PRESERVE_INPUT\fP   (1U << 4) /* cancels FFTW_DESTROY_INPUT */"
.br
.ti -1c
.RI "#define \fBFFTW_PATIENT\fP   (1U << 5) /* IMPATIENT is default */"
.br
.ti -1c
.RI "#define \fBFFTW_ESTIMATE\fP   (1U << 6)"
.br
.ti -1c
.RI "#define \fBFFTW_ESTIMATE_PATIENT\fP   (1U << 7)"
.br
.ti -1c
.RI "#define \fBFFTW_BELIEVE_PCOST\fP   (1U << 8)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_DFT_R2HC\fP   (1U << 9)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_NONTHREADED\fP   (1U << 10)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_BUFFERING\fP   (1U << 11)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_INDIRECT_OP\fP   (1U << 12)"
.br
.ti -1c
.RI "#define \fBFFTW_ALLOW_LARGE_GENERIC\fP   (1U << 13) /* NO_LARGE_GENERIC is default */"
.br
.ti -1c
.RI "#define \fBFFTW_NO_RANK_SPLITS\fP   (1U << 14)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_VRANK_SPLITS\fP   (1U << 15)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_VRECURSE\fP   (1U << 16)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_SIMD\fP   (1U << 17)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_SLOW\fP   (1U << 18)"
.br
.ti -1c
.RI "#define \fBFFTW_NO_FIXED_RADIX_LARGE_N\fP   (1U << 19)"
.br
.ti -1c
.RI "#define \fBFFTW_ALLOW_PRUNING\fP   (1U << 20)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBfftw_r2r_kind_do_not_use_me\fP { \fBFFTW_R2HC\fP =0, \fBFFTW_HC2R\fP =1, \fBFFTW_DHT\fP =2, \fBFFTW_REDFT00\fP =3, \fBFFTW_REDFT01\fP =4, \fBFFTW_REDFT10\fP =5, \fBFFTW_REDFT11\fP =6, \fBFFTW_RODFT00\fP =7, \fBFFTW_RODFT01\fP =8, \fBFFTW_RODFT10\fP =9, \fBFFTW_RODFT11\fP =10 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FFTW_ALLOW_LARGE_GENERIC   (1U << 13) /* NO_LARGE_GENERIC is default */"

.PP
Definition at line 320 of file fftw3\&.h\&.
.SS "#define FFTW_ALLOW_PRUNING   (1U << 20)"

.PP
Definition at line 327 of file fftw3\&.h\&.
.SS "#define FFTW_BACKWARD   (+1)"

.PP
Definition at line 299 of file fftw3\&.h\&.
.SS "#define FFTW_BELIEVE_PCOST   (1U << 8)"

.PP
Definition at line 315 of file fftw3\&.h\&.
.SS "#define FFTW_CONCAT(\fBprefix\fP, \fBname\fP)   \fBprefix\fP ## \fBname\fP"

.PP
Definition at line 70 of file fftw3\&.h\&.
.SS "#define FFTW_CONSERVE_MEMORY   (1U << 2)"

.PP
Definition at line 307 of file fftw3\&.h\&.
.SS "#define FFTW_DEFINE_API(X, R, C)"

.PP
Definition at line 116 of file fftw3\&.h\&.
.SS "#define FFTW_DEFINE_COMPLEX(R, C)   typedef R C[2]"

.PP
Definition at line 67 of file fftw3\&.h\&.
.SS "#define FFTW_DESTROY_INPUT   (1U << 0)"

.PP
Definition at line 305 of file fftw3\&.h\&.
.SS "#define FFTW_DLL"

.PP
Definition at line 77 of file fftw3\&.h\&.
.SS "#define FFTW_ESTIMATE   (1U << 6)"

.PP
Definition at line 311 of file fftw3\&.h\&.
.SS "#define FFTW_ESTIMATE_PATIENT   (1U << 7)"

.PP
Definition at line 314 of file fftw3\&.h\&.
.SS "#define FFTW_EXHAUSTIVE   (1U << 3) /* NO_EXHAUSTIVE is default */"

.PP
Definition at line 308 of file fftw3\&.h\&.
.SS "#define FFTW_EXTERN   extern"

.PP
Definition at line 92 of file fftw3\&.h\&.
.SS "#define FFTW_FORWARD   (\-1)"

.PP
Definition at line 298 of file fftw3\&.h\&.
.SS "#define FFTW_MANGLE_DOUBLE(\fBname\fP)   \fBFFTW_CONCAT\fP(fftw_, \fBname\fP)"

.PP
Definition at line 71 of file fftw3\&.h\&.
.SS "#define FFTW_MANGLE_FLOAT(\fBname\fP)   \fBFFTW_CONCAT\fP(fftwf_, \fBname\fP)"

.PP
Definition at line 72 of file fftw3\&.h\&.
.SS "#define FFTW_MANGLE_LONG_DOUBLE(\fBname\fP)   \fBFFTW_CONCAT\fP(fftwl_, \fBname\fP)"

.PP
Definition at line 73 of file fftw3\&.h\&.
.SS "#define FFTW_MEASURE   (0U)"

.PP
Definition at line 304 of file fftw3\&.h\&.
.SS "#define FFTW_NO_BUFFERING   (1U << 11)"

.PP
Definition at line 318 of file fftw3\&.h\&.
.SS "#define FFTW_NO_DFT_R2HC   (1U << 9)"

.PP
Definition at line 316 of file fftw3\&.h\&.
.SS "#define FFTW_NO_FIXED_RADIX_LARGE_N   (1U << 19)"

.PP
Definition at line 326 of file fftw3\&.h\&.
.SS "#define FFTW_NO_INDIRECT_OP   (1U << 12)"

.PP
Definition at line 319 of file fftw3\&.h\&.
.SS "#define FFTW_NO_NONTHREADED   (1U << 10)"

.PP
Definition at line 317 of file fftw3\&.h\&.
.SS "#define FFTW_NO_RANK_SPLITS   (1U << 14)"

.PP
Definition at line 321 of file fftw3\&.h\&.
.SS "#define FFTW_NO_SIMD   (1U << 17)"

.PP
Definition at line 324 of file fftw3\&.h\&.
.SS "#define FFTW_NO_SLOW   (1U << 18)"

.PP
Definition at line 325 of file fftw3\&.h\&.
.SS "#define FFTW_NO_TIMELIMIT   (\-1\&.0)"

.PP
Definition at line 301 of file fftw3\&.h\&.
.SS "#define FFTW_NO_VRANK_SPLITS   (1U << 15)"

.PP
Definition at line 322 of file fftw3\&.h\&.
.SS "#define FFTW_NO_VRECURSE   (1U << 16)"

.PP
Definition at line 323 of file fftw3\&.h\&.
.SS "#define FFTW_PATIENT   (1U << 5) /* IMPATIENT is default */"

.PP
Definition at line 310 of file fftw3\&.h\&.
.SS "#define FFTW_PRESERVE_INPUT   (1U << 4) /* cancels FFTW_DESTROY_INPUT */"

.PP
Definition at line 309 of file fftw3\&.h\&.
.SS "#define FFTW_UNALIGNED   (1U << 1)"

.PP
Definition at line 306 of file fftw3\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBfftw_r2r_kind_do_not_use_me\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFFTW_R2HC \fP\fP
.TP
\fB\fIFFTW_HC2R \fP\fP
.TP
\fB\fIFFTW_DHT \fP\fP
.TP
\fB\fIFFTW_REDFT00 \fP\fP
.TP
\fB\fIFFTW_REDFT01 \fP\fP
.TP
\fB\fIFFTW_REDFT10 \fP\fP
.TP
\fB\fIFFTW_REDFT11 \fP\fP
.TP
\fB\fIFFTW_RODFT00 \fP\fP
.TP
\fB\fIFFTW_RODFT01 \fP\fP
.TP
\fB\fIFFTW_RODFT10 \fP\fP
.TP
\fB\fIFFTW_RODFT11 \fP\fP
.PP
Definition at line 95 of file fftw3\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
