.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/field.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/field.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'id3tag\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBid3_field_init\fP (union \fBid3_field\fP *, enum \fBid3_field_type\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBid3_field_finish\fP (union \fBid3_field\fP *)"
.br
.ti -1c
.RI "\fBint\fP \fBid3_field_parse\fP (union \fBid3_field\fP *, \fBid3_byte_t\fP \fBconst\fP **, \fBid3_length_t\fP, enum \fBid3_field_textencoding\fP *)"
.br
.ti -1c
.RI "\fBid3_length_t\fP \fBid3_field_render\fP (union \fBid3_field\fP \fBconst\fP *, \fBid3_byte_t\fP **, enum \fBid3_field_textencoding\fP *, \fBint\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP id3_field_finish (union \fBid3_field\fP *)"

.PP
Definition at line 103 of file field\&.c\&.
.SS "\fBvoid\fP id3_field_init (union \fBid3_field\fP *, enum id3_field_type)"

.PP
Definition at line 47 of file field\&.c\&.
.SS "\fBint\fP id3_field_parse (union \fBid3_field\fP *, \fBid3_byte_t\fP \fBconst\fP **, \fBid3_length_t\fP, enum \fBid3_field_textencoding\fP *)"

.PP
Definition at line 173 of file field\&.c\&.
.SS "\fBid3_length_t\fP id3_field_render (union \fBid3_field\fP \fBconst\fP *, \fBid3_byte_t\fP **, enum \fBid3_field_textencoding\fP *, \fBint\fP)"

.PP
Definition at line 337 of file field\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
