.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/win/FileDialogPrivate.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/win/FileDialogPrivate.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include <wx/modalhook\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileDialog\fP"
.br
.RI "\fIDialog used to present platform specific 'Save As' dialog with custom controls\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
