.TH "FileWvIn" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileWvIn \- STK audio file input class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileWvIn\&.h>\fP
.SH "Detailed Description"
.PP 
STK audio file input class\&. 

This class inherits from \fBWvIn\fP\&. It provides a 'tick-level' interface to the \fBFileRead\fP class\&. It also provides variable-rate 'playback' functionality\&. Audio file support is provided by the \fBFileRead\fP class\&. Linear interpolation is used for fractional 'read
rates'\&.
.PP
\fBFileWvIn\fP supports multi-channel data\&. It is important to distinguish the \fBtick()\fP methods, which return samples produced by averaging across sample frames, from the tickFrame() methods, which return references to multi-channel sample frames\&.
.PP
\fBFileWvIn\fP will either load the entire content of an audio file into local memory or incrementally read file data from disk in chunks\&. This behavior is controlled by the optional constructor arguments \fIchunkThreshold\fP and \fIchunkSize\fP\&. File sizes greater than \fIchunkThreshold\fP (in sample frames) will be read incrementally in chunks of \fIchunkSize\fP each (also in sample frames)\&.
.PP
When the file end is reached, subsequent calls to the \fBtick()\fP functions return zero-valued data and isFinished() returns \fItrue\fP\&.
.PP
See the \fBFileRead\fP class for a description of the supported audio file formats\&.
.PP
by Perry R\&. Cook and Gary P\&. Scavone, 1995 - 2005\&.
.PP
This class inherits from \fBWvIn\fP\&. It provides a 'tick-level' interface to the \fBFileRead\fP class\&. It also provides variable-rate 'playback' functionality\&. Audio file support is provided by the \fBFileRead\fP class\&. Linear interpolation is used for fractional 'read
rates'\&.
.PP
\fBFileWvIn\fP supports multi-channel data\&. It is important to distinguish the \fBtick()\fP methods, which return samples produced by averaging across sample frames, from the tickFrame() methods, which return references to multi-channel sample frames\&.
.PP
\fBFileWvIn\fP will either load the entire content of an audio file into local memory or incrementally read file data from disk in chunks\&. This behavior is controlled by the optional constructor arguments \fIchunkThreshold\fP and \fIchunkSize\fP\&. File sizes greater than \fIchunkThreshold\fP (in sample frames) will be read incrementally in chunks of \fIchunkSize\fP each (also in sample frames)\&.
.PP
When the end of a file is reached, subsequent calls to the \fBtick()\fP functions return zero-valued data\&.
.PP
See the \fBFileRead\fP class for a description of the supported audio file formats\&.
.PP
by Perry R\&. Cook and Gary P\&. Scavone, 1995 - 2005\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
