.TH "filetag" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filetag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBid3_tag\fP * \fBtag\fP"
.br
.ti -1c
.RI "unsigned long \fBlocation\fP"
.br
.ti -1c
.RI "\fBid3_length_t\fP \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file file\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBid3_length_t\fP filetag::length"

.PP
Definition at line 48 of file file\&.c\&.
.SS "unsigned long filetag::location"

.PP
Definition at line 47 of file file\&.c\&.
.SS "struct \fBid3_tag\fP* filetag::tag"

.PP
Definition at line 46 of file file\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
