.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/file_io.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/file_io.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sf_unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSENSIBLE_SIZE\fP   (0x40000000)"
.br
.ti -1c
.RI "#define \fBO_BINARY\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBpsf_fopen\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_fclose\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_open_rsrc\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_get_filelen\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_close_rsrc\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_set_stdio\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpsf_set_file\fP (\fBSF_PRIVATE\fP *psf, \fBint\fP fd)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_file_valid\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_fseek\fP (\fBSF_PRIVATE\fP *psf, \fBsf_count_t\fP \fBoffset\fP, \fBint\fP whence)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_fread\fP (\fBvoid\fP *ptr, \fBsf_count_t\fP bytes, \fBsf_count_t\fP items, \fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_fwrite\fP (\fBconst\fP \fBvoid\fP *ptr, \fBsf_count_t\fP bytes, \fBsf_count_t\fP items, \fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_ftell\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBpsf_fgets\fP (char *\fBbuffer\fP, \fBsf_count_t\fP bufsize, \fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_is_pipe\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBint\fP \fBpsf_ftruncate\fP (\fBSF_PRIVATE\fP *psf, \fBsf_count_t\fP \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpsf_init_files\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpsf_use_rsrc\fP (\fBSF_PRIVATE\fP *psf, \fBint\fP on_off)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpsf_fsync\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define O_BINARY   0"

.PP
Definition at line 64 of file file_io\&.c\&.
.SS "#define SENSIBLE_SIZE   (0x40000000)"

.PP
Definition at line 56 of file file_io\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP psf_close_rsrc (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 216 of file file_io\&.c\&.
.SS "\fBint\fP psf_fclose (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 98 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_fgets (char * buffer, \fBsf_count_t\fP bufsize, \fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 431 of file file_io\&.c\&.
.SS "\fBint\fP psf_file_valid (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 254 of file file_io\&.c\&.
.SS "\fBint\fP psf_fopen (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 80 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_fread (\fBvoid\fP * ptr, \fBsf_count_t\fP bytes, \fBsf_count_t\fP items, \fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 316 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_fseek (\fBSF_PRIVATE\fP * psf, \fBsf_count_t\fP offset, \fBint\fP whence)"

.PP
Definition at line 259 of file file_io\&.c\&.
.SS "\fBvoid\fP psf_fsync (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 589 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_ftell (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 398 of file file_io\&.c\&.
.SS "\fBint\fP psf_ftruncate (\fBSF_PRIVATE\fP * psf, \fBsf_count_t\fP len)"

.PP
Definition at line 492 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_fwrite (\fBconst\fP \fBvoid\fP * ptr, \fBsf_count_t\fP bytes, \fBsf_count_t\fP items, \fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 357 of file file_io\&.c\&.
.SS "\fBsf_count_t\fP psf_get_filelen (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 171 of file file_io\&.c\&.
.SS "\fBvoid\fP psf_init_files (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 511 of file file_io\&.c\&.
.SS "\fBint\fP psf_is_pipe (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 456 of file file_io\&.c\&.
.SS "\fBint\fP psf_open_rsrc (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 118 of file file_io\&.c\&.
.SS "\fBvoid\fP psf_set_file (\fBSF_PRIVATE\fP * psf, \fBint\fP fd)"

.PP
Definition at line 249 of file file_io\&.c\&.
.SS "\fBint\fP psf_set_stdio (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 223 of file file_io\&.c\&.
.SS "\fBvoid\fP psf_use_rsrc (\fBSF_PRIVATE\fP * psf, \fBint\fP on_off)"

.PP
Definition at line 518 of file file_io\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
