.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/win/FileDialogPrivate.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/win/FileDialogPrivate.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'wx/wxprec\&.h'\fP
.br
\fC#include <wx/msw/wrapcdlg\&.h>\fP
.br
\fC#include <wx/msw/missing\&.h>\fP
.br
\fC#include <wx/utils\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/filefn\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/log\&.h>\fP
.br
\fC#include <wx/app\&.h>\fP
.br
\fC#include <wx/math\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <wx/dynlib\&.h>\fP
.br
\fC#include <wx/filename\&.h>\fP
.br
\fC#include <wx/scopeguard\&.h>\fP
.br
\fC#include <wx/tokenzr\&.h>\fP
.br
\fC#include <wx/modalhook\&.h>\fP
.br
\fC#include '\&.\&./FileDialog\&.h'\fP
.br
\fC#include <shlobj\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwxOPENFILENAME\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBwxMAXPATH\fP   1024"
.br
.ti -1c
.RI "#define \fBwxMAXFILE\fP   1024"
.br
.ti -1c
.RI "#define \fBwxMAXEXT\fP   5"
.br
.ti -1c
.RI "#define \fBWM_GETISHELLBROWSER\fP   WM_USER + 7"
.br
.ti -1c
.RI "#define \fBwxTRY_SMALLER_OPENFILENAME\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WM_GETISHELLBROWSER   WM_USER + 7"

.PP
Definition at line 453 of file FileDialogPrivate\&.cpp\&.
.SS "#define wxMAXEXT   5"

.PP
Definition at line 66 of file FileDialogPrivate\&.cpp\&.
.SS "#define wxMAXFILE   1024"

.PP
Definition at line 64 of file FileDialogPrivate\&.cpp\&.
.SS "#define wxMAXPATH   1024"

.PP
Definition at line 61 of file FileDialogPrivate\&.cpp\&.
.SS "#define wxTRY_SMALLER_OPENFILENAME"

.PP
Definition at line 802 of file FileDialogPrivate\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
