.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/FileDialog.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/FileDialog/FileDialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FileDialog\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "wxString \fBFileSelector\fP (\fBconst\fP wxString &title, \fBconst\fP wxString &defaultDir, \fBconst\fP wxString &defaultFileName, \fBconst\fP wxString &defaultExtension, \fBconst\fP wxString &\fBfilter\fP, \fBint\fP flags, wxWindow *parent, \fBint\fP x, \fBint\fP y)"
.br
.ti -1c
.RI "wxString \fBFileSelectorEx\fP (\fBconst\fP wxString &title, \fBconst\fP wxString &defaultDir, \fBconst\fP wxString &defaultFileName, \fBint\fP *defaultFilterIndex, \fBconst\fP wxString &\fBfilter\fP, \fBint\fP flags, wxWindow *parent, \fBint\fP x, \fBint\fP y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "wxString FileSelector (\fBconst\fP wxString & title, \fBconst\fP wxString & defaultDir, \fBconst\fP wxString & defaultFileName, \fBconst\fP wxString & defaultExtension, \fBconst\fP wxString & filter, \fBint\fP flags, wxWindow * parent, \fBint\fP x, \fBint\fP y)"

.PP
Definition at line 61 of file FileDialog\&.cpp\&.
.SS "wxString FileSelectorEx (\fBconst\fP wxString & title, \fBconst\fP wxString & defaultDir, \fBconst\fP wxString & defaultFileName, \fBint\fP * defaultFilterIndex, \fBconst\fP wxString & filter, \fBint\fP flags, wxWindow * parent, \fBint\fP x, \fBint\fP y)"

.PP
Definition at line 125 of file FileDialog\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
