.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_mac/finddefault.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_mac/finddefault.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'portmidi\&.h'\fP
.br
\fC#include 'pmutil\&.h'\fP
.br
\fC#include 'pminternal\&.h'\fP
.br
\fC#include 'pmmacosxcm\&.h'\fP
.br
\fC#include 'readbinaryplist\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPmDeviceID\fP \fBfind_default_device\fP (char *path, \fBint\fP input, \fBPmDeviceID\fP id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPmDeviceID\fP find_default_device (char * path, \fBint\fP input, \fBPmDeviceID\fP id)"

.PP
Definition at line 20 of file finddefault\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
