.TH "FixedTempoEstimator::D" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedTempoEstimator::D \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBD\fP (float inputSampleRate)"
.br
.ti -1c
.RI "\fB~D\fP ()"
.br
.ti -1c
.RI "size_t \fBgetPreferredStepSize\fP () \fBconst\fP "
.br
.ti -1c
.RI "size_t \fBgetPreferredBlockSize\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBParameterList\fP \fBgetParameterDescriptors\fP () \fBconst\fP "
.br
.ti -1c
.RI "float \fBgetParameter\fP (\fBstring\fP id) \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetParameter\fP (\fBstring\fP id, float \fBvalue\fP)"
.br
.ti -1c
.RI "\fBOutputList\fP \fBgetOutputDescriptors\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBinitialise\fP (size_t channels, size_t stepSize, size_t blockSize)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.ti -1c
.RI "\fBFeatureSet\fP \fBprocess\fP (\fBconst\fP float *\fBconst\fP *, \fBRealTime\fP)"
.br
.ti -1c
.RI "\fBFeatureSet\fP \fBgetRemainingFeatures\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file FixedTempoEstimator\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FixedTempoEstimator::D::D (float inputSampleRate)"

.PP
Definition at line 99 of file FixedTempoEstimator\&.cpp\&.
.SS "FixedTempoEstimator::D::~D ()"

.PP
Definition at line 115 of file FixedTempoEstimator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFixedTempoEstimator::OutputList\fP FixedTempoEstimator::D::getOutputDescriptors () const"

.PP
Definition at line 190 of file FixedTempoEstimator\&.cpp\&.
.SS "float FixedTempoEstimator::D::getParameter (\fBstring\fP id) const"

.PP
Definition at line 159 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBFixedTempoEstimator::ParameterList\fP FixedTempoEstimator::D::getParameterDescriptors () const"

.PP
Definition at line 125 of file FixedTempoEstimator\&.cpp\&.
.SS "size_t FixedTempoEstimator::D::getPreferredBlockSize () const\fC [inline]\fP"

.PP
Definition at line 58 of file FixedTempoEstimator\&.cpp\&.
.SS "size_t FixedTempoEstimator::D::getPreferredStepSize () const\fC [inline]\fP"

.PP
Definition at line 57 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBFixedTempoEstimator::FeatureSet\fP FixedTempoEstimator::D::getRemainingFeatures ()"

.PP
Definition at line 352 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBbool\fP FixedTempoEstimator::D::initialise (size_t channels, size_t stepSize, size_t blockSize)"

.PP
Definition at line 252 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBFixedTempoEstimator::FeatureSet\fP FixedTempoEstimator::D::process (\fBconst\fP float *\fBconst\fP * inputBuffers, \fBRealTime\fP ts)"

.PP
Definition at line 303 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBvoid\fP FixedTempoEstimator::D::reset (\fBvoid\fP)"

.PP
Definition at line 276 of file FixedTempoEstimator\&.cpp\&.
.SS "\fBvoid\fP FixedTempoEstimator::D::setParameter (\fBstring\fP id, float value)"

.PP
Definition at line 172 of file FixedTempoEstimator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
