.TH "FLAC::Metadata::CueSheet::Track" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC::Metadata::CueSheet::Track \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <metadata\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrack\fP ()"
.br
.ti -1c
.RI "\fBTrack\fP (\fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Track\fP *track)"
.br
.ti -1c
.RI "\fBTrack\fP (\fBconst\fP \fBTrack\fP &track)"
.br
.ti -1c
.RI "\fBTrack\fP & \fBoperator=\fP (\fBconst\fP \fBTrack\fP &track)"
.br
.ti -1c
.RI "virtual \fB~Track\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBis_valid\fP () \fBconst\fP "
.br
.RI "\fIReturns \fCtrue\fP iff object was properly constructed\&. \fP"
.ti -1c
.RI "\fBFLAC__uint64\fP \fBget_offset\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBFLAC__byte\fP \fBget_number\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP char * \fBget_isrc\fP () \fBconst\fP "
.br
.ti -1c
.RI "unsigned \fBget_type\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBget_pre_emphasis\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBFLAC__byte\fP \fBget_num_indices\fP () \fBconst\fP "
.br
.ti -1c
.RI "::\fBFLAC__StreamMetadata_CueSheet_Index\fP \fBget_index\fP (unsigned \fBi\fP) \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Track\fP * \fBget_track\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBset_offset\fP (\fBFLAC__uint64\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_number\fP (\fBFLAC__byte\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_isrc\fP (\fBconst\fP char \fBvalue\fP[12])"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_type\fP (unsigned \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_pre_emphasis\fP (\fBbool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_index\fP (unsigned \fBi\fP, \fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Index\fP &index)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "::\fBFLAC__StreamMetadata_CueSheet_Track\fP * \fBobject_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience class for encapsulating a cue sheet track\&.
.PP
Always check \fBis_valid()\fP after the constructor or operator= to make sure memory was properly allocated\&. 
.PP
Definition at line 724 of file metadata\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FLAC::Metadata::CueSheet::Track::Track ()"

.PP
Definition at line 961 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::CueSheet::Track::Track (\fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Track\fP * track)"

.PP
Definition at line 965 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::CueSheet::Track::Track (\fBconst\fP \fBTrack\fP & track)"

.PP
Definition at line 969 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::CueSheet::Track::~Track ()\fC [virtual]\fP"

.PP
Definition at line 981 of file metadata\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata_CueSheet_Index\fP FLAC::Metadata::CueSheet::Track::get_index (unsigned i) const"

.PP
Definition at line 992 of file metadata\&.cpp\&.
.SS "\fBconst\fP char* FLAC::Metadata::CueSheet::Track::get_isrc () const\fC [inline]\fP"

.PP
Definition at line 740 of file metadata\&.h\&.
.SS "\fBFLAC__byte\fP FLAC::Metadata::CueSheet::Track::get_num_indices () const\fC [inline]\fP"

.PP
Definition at line 744 of file metadata\&.h\&.
.SS "\fBFLAC__byte\fP FLAC::Metadata::CueSheet::Track::get_number () const\fC [inline]\fP"

.PP
Definition at line 739 of file metadata\&.h\&.
.SS "\fBFLAC__uint64\fP FLAC::Metadata::CueSheet::Track::get_offset () const\fC [inline]\fP"

.PP
Definition at line 738 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::CueSheet::Track::get_pre_emphasis () const\fC [inline]\fP"

.PP
Definition at line 742 of file metadata\&.h\&.
.SS "\fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Track\fP* FLAC::Metadata::CueSheet::Track::get_track () const\fC [inline]\fP"

.PP
Definition at line 747 of file metadata\&.h\&.
.SS "unsigned FLAC::Metadata::CueSheet::Track::get_type () const\fC [inline]\fP"

.PP
Definition at line 741 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::CueSheet::Track::is_valid () const\fC [virtual]\fP"

.PP
Returns \fCtrue\fP iff object was properly constructed\&. 
.PP
Definition at line 987 of file metadata\&.cpp\&.
.SS "\fBCueSheet::Track\fP & FLAC::Metadata::CueSheet::Track::operator= (\fBconst\fP \fBTrack\fP & track)"

.PP
Definition at line 973 of file metadata\&.cpp\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_index (unsigned i, \fBconst\fP ::\fBFLAC__StreamMetadata_CueSheet_Index\fP & index)"

.PP
Definition at line 1014 of file metadata\&.cpp\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_isrc (\fBconst\fP char value[12])"

.PP
Definition at line 999 of file metadata\&.cpp\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_number (\fBFLAC__byte\fP value)\fC [inline]\fP"

.PP
Definition at line 750 of file metadata\&.h\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_offset (\fBFLAC__uint64\fP value)\fC [inline]\fP"

.PP
Definition at line 749 of file metadata\&.h\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_pre_emphasis (\fBbool\fP value)\fC [inline]\fP"

.PP
Definition at line 753 of file metadata\&.h\&.
.SS "\fBvoid\fP FLAC::Metadata::CueSheet::Track::set_type (unsigned value)"

.PP
Definition at line 1007 of file metadata\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "::\fBFLAC__StreamMetadata_CueSheet_Track\fP* FLAC::Metadata::CueSheet::Track::object_\fC [protected]\fP"

.PP
Definition at line 726 of file metadata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
