.TH "FLAC__StreamDecoder" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__StreamDecoder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream_decoder\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBFLAC__StreamDecoderProtected\fP * \fBprotected_\fP"
.br
.ti -1c
.RI "struct \fBFLAC__StreamDecoderPrivate\fP * \fBprivate_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The opaque structure definition for the stream decoder type\&. See the \fBstream decoder module \fP for a detailed description\&. 
.PP
Definition at line 463 of file stream_decoder\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBFLAC__StreamDecoderPrivate\fP* FLAC__StreamDecoder::private_"

.PP
Definition at line 465 of file stream_decoder\&.h\&.
.SS "struct \fBFLAC__StreamDecoderProtected\fP* FLAC__StreamDecoder::protected_"

.PP
Definition at line 464 of file stream_decoder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
