.TH "FLAC__StreamEncoder" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__StreamEncoder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream_encoder\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBFLAC__StreamEncoderProtected\fP * \fBprotected_\fP"
.br
.ti -1c
.RI "struct \fBFLAC__StreamEncoderPrivate\fP * \fBprivate_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The opaque structure definition for the stream encoder type\&. See the \fBstream encoder module \fP for a detailed description\&. 
.PP
Definition at line 465 of file stream_encoder\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBFLAC__StreamEncoderPrivate\fP* FLAC__StreamEncoder::private_"

.PP
Definition at line 467 of file stream_encoder\&.h\&.
.SS "struct \fBFLAC__StreamEncoderProtected\fP* FLAC__StreamEncoder::protected_"

.PP
Definition at line 466 of file stream_encoder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
