.TH "FLAC::Metadata::Prototype" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC::Metadata::Prototype \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <metadata\&.h>\fP
.PP
Inherited by \fBFLAC::Metadata::Application\fP, \fBFLAC::Metadata::CueSheet\fP, \fBFLAC::Metadata::Padding\fP, \fBFLAC::Metadata::Picture\fP, \fBFLAC::Metadata::SeekTable\fP, \fBFLAC::Metadata::StreamInfo\fP, \fBFLAC::Metadata::Unknown\fP, and \fBFLAC::Metadata::VorbisComment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Prototype\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBis_valid\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBget_is_last\fP () \fBconst\fP "
.br
.ti -1c
.RI "::\fBFLAC__MetadataType\fP \fBget_type\fP () \fBconst\fP "
.br
.ti -1c
.RI "unsigned \fBget_length\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBset_is_last\fP (\fBbool\fP)"
.br
.ti -1c
.RI "\fBoperator const ::FLAC__StreamMetadata *\fP () \fBconst\fP "
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBPrototype\fP &) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *) \fBconst\fP "
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBPrototype\fP &) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *) \fBconst\fP "
.br
.in -1c
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPrototype\fP (\fBconst\fP \fBPrototype\fP &)"
.br
.ti -1c
.RI "\fBPrototype\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &)"
.br
.ti -1c
.RI "\fBPrototype\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *)"
.br
.ti -1c
.RI "\fBPrototype\fP (::\fBFLAC__StreamMetadata\fP *object, \fBbool\fP copy)"
.br
.ti -1c
.RI "\fBPrototype\fP & \fBassign_object\fP (::\fBFLAC__StreamMetadata\fP *object, \fBbool\fP copy)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBclear\fP ()"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBPrototype\fP & \fBoperator=\fP (\fBconst\fP \fBPrototype\fP &)"
.br
.ti -1c
.RI "\fBPrototype\fP & \fBoperator=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &)"
.br
.ti -1c
.RI "\fBPrototype\fP & \fBoperator=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *)"
.br
.in -1c
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "::\fBFLAC__StreamMetadata\fP * \fBobject_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSimpleIterator\fP"
.br
.ti -1c
.RI "class \fBIterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for all metadata block types\&. See the \fBoverview \fP for more\&. 
.PP
Definition at line 109 of file metadata\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FLAC::Metadata::Prototype::Prototype (::\fBFLAC__StreamMetadata\fP * object, \fBbool\fP copy)\fC [protected]\fP"
Constructs an object with copy control\&. When \fIcopy\fP is \fCtrue\fP, behaves identically to \fBFLAC::Metadata::Prototype::Prototype(const ::FLAC__StreamMetadata *object)\fP\&. When \fIcopy\fP is \fCfalse\fP, the instance takes ownership of the pointer and the \fBFLAC__StreamMetadata\fP object will be freed by the destructor\&.
.PP
.PP
.nf
object != NULL 
.fi
.PP
 
.PP
Definition at line 149 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::Prototype::~Prototype ()\fC [virtual]\fP"
Deletes the underlying \fBFLAC__StreamMetadata\fP object\&. 
.PP
Definition at line 156 of file metadata\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPrototype\fP & FLAC::Metadata::Prototype::assign_object (::\fBFLAC__StreamMetadata\fP * object, \fBbool\fP copy)\fC [protected]\fP"
Assigns an object with copy control\&. See \fBPrototype(::FLAC__StreamMetadata *object, bool copy)\fP\&. 
.PP
Definition at line 194 of file metadata\&.cpp\&.
.SS "\fBvoid\fP FLAC::Metadata::Prototype::clear ()\fC [protected]\fP, \fC [virtual]\fP"
Deletes the underlying \fBFLAC__StreamMetadata\fP object\&. 
.PP
Definition at line 161 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::Prototype::get_is_last () const"
Returns \fCtrue\fP if this block is the last block in a stream, else \fCfalse\fP\&.
.PP
.PP
.nf
is_valid() 
.fi
.PP
 
.PP
Definition at line 203 of file metadata\&.cpp\&.
.SS "unsigned FLAC::Metadata::Prototype::get_length () const"
Returns the stream length of the metadata block\&.
.PP
\fBNote:\fP
.RS 4
The length does not include the metadata block header, per spec\&.
.RE
.PP
.PP
.nf
is_valid() 
.fi
.PP
 
.PP
Definition at line 215 of file metadata\&.cpp\&.
.SS "\fBFLAC__MetadataType\fP FLAC::Metadata::Prototype::get_type () const"
Returns the type of the block\&.
.PP
.PP
.nf
is_valid() 
.fi
.PP
 
.PP
Definition at line 209 of file metadata\&.cpp\&.
.SS "\fBPrototype\fP & FLAC::Metadata::Prototype::operator= (\fBconst\fP \fBPrototype\fP & object)\fC [protected]\fP"
Assign from another object\&. Always performs a deep copy\&. 
.PP
Definition at line 168 of file metadata\&.cpp\&.
.SS "\fBPrototype\fP & FLAC::Metadata::Prototype::operator= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP & object)\fC [protected]\fP"

.PP
Definition at line 177 of file metadata\&.cpp\&.
.SS "\fBPrototype\fP & FLAC::Metadata::Prototype::operator= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * object)\fC [protected]\fP"

.PP
Definition at line 185 of file metadata\&.cpp\&.
.SS "\fBvoid\fP FLAC::Metadata::Prototype::set_is_last (\fBbool\fP value)"
Sets the 'is_last' flag for the block\&. When using the iterators it is not necessary to set this flag; they will do it for you\&.
.PP
.PP
.nf
is_valid() 
.fi
.PP
 
.PP
Definition at line 221 of file metadata\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBIterator\fP\fC [friend]\fP"

.PP
Definition at line 170 of file metadata\&.h\&.
.SS "friend class \fBSimpleIterator\fP\fC [friend]\fP"

.PP
Definition at line 169 of file metadata\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "::\fBFLAC__StreamMetadata\fP* FLAC::Metadata::Prototype::object_\fC [protected]\fP"

.PP
Definition at line 148 of file metadata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
