.TH "FLAC::Metadata::Unknown" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC::Metadata::Unknown \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <metadata\&.h>\fP
.PP
Inherits \fBFLAC::Metadata::Prototype\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnknown\fP ()"
.br
.ti -1c
.RI "\fBUnknown\fP (::\fBFLAC__StreamMetadata\fP *object, \fBbool\fP copy)"
.br
.ti -1c
.RI "\fB~Unknown\fP ()"
.br
.ti -1c
.RI "\fBUnknown\fP & \fBassign\fP (::\fBFLAC__StreamMetadata\fP *object, \fBbool\fP copy)"
.br
.ti -1c
.RI "\fBconst\fP \fBFLAC__byte\fP * \fBget_data\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBset_data\fP (\fBconst\fP \fBFLAC__byte\fP *\fBdata\fP, unsigned \fBlength\fP)"
.br
.RI "\fIThis form always copies \fIdata\fP\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBset_data\fP (\fBFLAC__byte\fP *\fBdata\fP, unsigned \fBlength\fP, \fBbool\fP copy)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBUnknown\fP (\fBconst\fP \fBUnknown\fP &object)"
.br
.ti -1c
.RI "\fBUnknown\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &object)"
.br
.ti -1c
.RI "\fBUnknown\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *object)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBUnknown\fP & \fBoperator=\fP (\fBconst\fP \fBUnknown\fP &object)"
.br
.ti -1c
.RI "\fBUnknown\fP & \fBoperator=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &object)"
.br
.ti -1c
.RI "\fBUnknown\fP & \fBoperator=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *object)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBUnknown\fP &object) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &object) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *object) \fBconst\fP "
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBUnknown\fP &object) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP &object) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *object) \fBconst\fP "
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Opaque metadata block for storing unknown types\&. This should not be used unless you know what you are doing; it is currently used only internally to support forward compatibility of metadata blocks\&. See the \fBoverview \fP for more, 
.PP
Definition at line 937 of file metadata\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FLAC::Metadata::Unknown::Unknown ()"

.PP
Definition at line 1299 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::Unknown::Unknown (\fBconst\fP \fBUnknown\fP & object)\fC [inline]\fP"
Constructs a copy of the given object\&. This form always performs a deep copy\&. 
.PP
Definition at line 945 of file metadata\&.h\&.
.SS "FLAC::Metadata::Unknown::Unknown (\fBconst\fP ::\fBFLAC__StreamMetadata\fP & object)\fC [inline]\fP"

.PP
Definition at line 946 of file metadata\&.h\&.
.SS "FLAC::Metadata::Unknown::Unknown (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * object)\fC [inline]\fP"

.PP
Definition at line 947 of file metadata\&.h\&.
.SS "FLAC::Metadata::Unknown::Unknown (::\fBFLAC__StreamMetadata\fP * object, \fBbool\fP copy)\fC [inline]\fP"
Constructs an object with copy control\&. See \fBPrototype(::FLAC__StreamMetadata *object, bool copy)\fP\&. 
.PP
Definition at line 953 of file metadata\&.h\&.
.SS "FLAC::Metadata::Unknown::~Unknown ()"

.PP
Definition at line 1303 of file metadata\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBUnknown\fP& FLAC::Metadata::Unknown::assign (::\fBFLAC__StreamMetadata\fP * object, \fBbool\fP copy)\fC [inline]\fP"
Assigns an object with copy control\&. See \fBPrototype::assign_object(::FLAC__StreamMetadata *object, bool copy)\fP\&. 
.PP
Definition at line 967 of file metadata\&.h\&.
.SS "\fBconst\fP \fBFLAC__byte\fP * FLAC::Metadata::Unknown::get_data () const"

.PP
Definition at line 1306 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator!= (\fBconst\fP \fBUnknown\fP & object) const\fC [inline]\fP"
Check for inequality, performing a deep compare by following pointers\&. 
.PP
Definition at line 978 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator!= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP & object) const\fC [inline]\fP"

.PP
Definition at line 979 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator!= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * object) const\fC [inline]\fP"

.PP
Definition at line 980 of file metadata\&.h\&.
.SS "\fBUnknown\fP& FLAC::Metadata::Unknown::operator= (\fBconst\fP \fBUnknown\fP & object)\fC [inline]\fP"
Assign from another object\&. Always performs a deep copy\&. 
.PP
Definition at line 959 of file metadata\&.h\&.
.SS "\fBUnknown\fP& FLAC::Metadata::Unknown::operator= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP & object)\fC [inline]\fP"

.PP
Definition at line 960 of file metadata\&.h\&.
.SS "\fBUnknown\fP& FLAC::Metadata::Unknown::operator= (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * object)\fC [inline]\fP"

.PP
Definition at line 961 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator== (\fBconst\fP \fBUnknown\fP & object) const\fC [inline]\fP"
Check for equality, performing a deep compare by following pointers\&. 
.PP
Definition at line 971 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator== (\fBconst\fP ::\fBFLAC__StreamMetadata\fP & object) const\fC [inline]\fP"

.PP
Definition at line 972 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::operator== (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * object) const\fC [inline]\fP"

.PP
Definition at line 973 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::set_data (\fBconst\fP \fBFLAC__byte\fP * data, unsigned length)"

.PP
This form always copies \fIdata\fP\&. 
.PP
Definition at line 1312 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::Unknown::set_data (\fBFLAC__byte\fP * data, unsigned length, \fBbool\fP copy)"

.PP
Definition at line 1318 of file metadata\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
