.TH "FLAC::Metadata::VorbisComment::Entry" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC::Metadata::VorbisComment::Entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <metadata\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntry\fP ()"
.br
.ti -1c
.RI "\fBEntry\fP (\fBconst\fP char *field, unsigned field_length)"
.br
.ti -1c
.RI "\fBEntry\fP (\fBconst\fP char *field)"
.br
.ti -1c
.RI "\fBEntry\fP (\fBconst\fP char *field_name, \fBconst\fP char *field_value, unsigned field_value_length)"
.br
.ti -1c
.RI "\fBEntry\fP (\fBconst\fP char *field_name, \fBconst\fP char *field_value)"
.br
.ti -1c
.RI "\fBEntry\fP (\fBconst\fP \fBEntry\fP &entry)"
.br
.ti -1c
.RI "\fBEntry\fP & \fBoperator=\fP (\fBconst\fP \fBEntry\fP &entry)"
.br
.ti -1c
.RI "virtual \fB~Entry\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBis_valid\fP () \fBconst\fP "
.br
.RI "\fIReturns \fCtrue\fP iff object was properly constructed\&. \fP"
.ti -1c
.RI "unsigned \fBget_field_length\fP () \fBconst\fP "
.br
.ti -1c
.RI "unsigned \fBget_field_name_length\fP () \fBconst\fP "
.br
.ti -1c
.RI "unsigned \fBget_field_value_length\fP () \fBconst\fP "
.br
.ti -1c
.RI "::\fBFLAC__StreamMetadata_VorbisComment_Entry\fP \fBget_entry\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP char * \fBget_field\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP char * \fBget_field_name\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP char * \fBget_field_value\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBset_field\fP (\fBconst\fP char *field, unsigned field_length)"
.br
.ti -1c
.RI "\fBbool\fP \fBset_field\fP (\fBconst\fP char *field)"
.br
.ti -1c
.RI "\fBbool\fP \fBset_field_name\fP (\fBconst\fP char *field_name)"
.br
.ti -1c
.RI "\fBbool\fP \fBset_field_value\fP (\fBconst\fP char *field_value, unsigned field_value_length)"
.br
.ti -1c
.RI "\fBbool\fP \fBset_field_value\fP (\fBconst\fP char *field_value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBis_valid_\fP"
.br
.ti -1c
.RI "::\fBFLAC__StreamMetadata_VorbisComment_Entry\fP \fBentry_\fP"
.br
.ti -1c
.RI "char * \fBfield_name_\fP"
.br
.ti -1c
.RI "unsigned \fBfield_name_length_\fP"
.br
.ti -1c
.RI "char * \fBfield_value_\fP"
.br
.ti -1c
.RI "unsigned \fBfield_value_length_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience class for encapsulating Vorbis comment entries\&. An entry is a vendor string or a comment field\&. In the case of a vendor string, the field name is undefined; only the field value is relevant\&.
.PP
A \fIfield\fP as used in the methods refers to an entire 'NAME=VALUE' string; for convenience the string is NUL-terminated\&. A length field is required in the unlikely event that the value contains contain embedded NULs\&.
.PP
A \fIfield_name\fP is what is on the left side of the first '=' in the \fIfield\fP\&. By definition it is ASCII and so is NUL-terminated and does not require a length to describe it\&. \fIfield_name\fP is undefined for a vendor string entry\&.
.PP
A \fIfield_value\fP is what is on the right side of the first '=' in the \fIfield\fP\&. By definition, this may contain embedded NULs and so a \fIfield_value_length\fP is required to describe it\&. However in practice, embedded NULs are not known to be used, so it is generally safe to treat field values as NUL- terminated UTF-8 strings\&.
.PP
Always check \fBis_valid()\fP after the constructor or operator= to make sure memory was properly allocated and that the \fBEntry\fP conforms to the Vorbis comment specification\&. 
.PP
Definition at line 580 of file metadata\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FLAC::Metadata::VorbisComment::Entry::Entry ()"

.PP
Definition at line 526 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::Entry (\fBconst\fP char * field, unsigned field_length)"

.PP
Definition at line 537 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::Entry (\fBconst\fP char * field)"

.PP
Definition at line 549 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::Entry (\fBconst\fP char * field_name, \fBconst\fP char * field_value, unsigned field_value_length)"

.PP
Definition at line 561 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::Entry (\fBconst\fP char * field_name, \fBconst\fP char * field_value)"

.PP
Definition at line 573 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::Entry (\fBconst\fP \fBEntry\fP & entry)"

.PP
Definition at line 585 of file metadata\&.cpp\&.
.SS "FLAC::Metadata::VorbisComment::Entry::~Entry ()\fC [virtual]\fP"

.PP
Definition at line 606 of file metadata\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata_VorbisComment_Entry\fP FLAC::Metadata::VorbisComment::Entry::get_entry () const"

.PP
Definition at line 634 of file metadata\&.cpp\&.
.SS "\fBconst\fP char * FLAC::Metadata::VorbisComment::Entry::get_field () const"

.PP
Definition at line 640 of file metadata\&.cpp\&.
.SS "unsigned FLAC::Metadata::VorbisComment::Entry::get_field_length () const"

.PP
Definition at line 616 of file metadata\&.cpp\&.
.SS "\fBconst\fP char * FLAC::Metadata::VorbisComment::Entry::get_field_name () const"

.PP
Definition at line 646 of file metadata\&.cpp\&.
.SS "unsigned FLAC::Metadata::VorbisComment::Entry::get_field_name_length () const"

.PP
Definition at line 622 of file metadata\&.cpp\&.
.SS "\fBconst\fP char * FLAC::Metadata::VorbisComment::Entry::get_field_value () const"

.PP
Definition at line 652 of file metadata\&.cpp\&.
.SS "unsigned FLAC::Metadata::VorbisComment::Entry::get_field_value_length () const"

.PP
Definition at line 628 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::is_valid () const\fC [virtual]\fP"

.PP
Returns \fCtrue\fP iff object was properly constructed\&. 
.PP
Definition at line 611 of file metadata\&.cpp\&.
.SS "\fBVorbisComment::Entry\fP & FLAC::Metadata::VorbisComment::Entry::operator= (\fBconst\fP \fBEntry\fP & entry)"

.PP
Definition at line 598 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::set_field (\fBconst\fP char * field, unsigned field_length)"

.PP
Definition at line 658 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::set_field (\fBconst\fP char * field)"

.PP
Definition at line 681 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::set_field_name (\fBconst\fP char * field_name)"

.PP
Definition at line 686 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::set_field_value (\fBconst\fP char * field_value, unsigned field_value_length)"

.PP
Definition at line 707 of file metadata\&.cpp\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::set_field_value (\fBconst\fP char * field_value)"

.PP
Definition at line 730 of file metadata\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "::\fBFLAC__StreamMetadata_VorbisComment_Entry\fP FLAC::Metadata::VorbisComment::Entry::entry_\fC [protected]\fP"

.PP
Definition at line 614 of file metadata\&.h\&.
.SS "char* FLAC::Metadata::VorbisComment::Entry::field_name_\fC [protected]\fP"

.PP
Definition at line 615 of file metadata\&.h\&.
.SS "unsigned FLAC::Metadata::VorbisComment::Entry::field_name_length_\fC [protected]\fP"

.PP
Definition at line 616 of file metadata\&.h\&.
.SS "char* FLAC::Metadata::VorbisComment::Entry::field_value_\fC [protected]\fP"

.PP
Definition at line 617 of file metadata\&.h\&.
.SS "unsigned FLAC::Metadata::VorbisComment::Entry::field_value_length_\fC [protected]\fP"

.PP
Definition at line 618 of file metadata\&.h\&.
.SS "\fBbool\fP FLAC::Metadata::VorbisComment::Entry::is_valid_\fC [protected]\fP"

.PP
Definition at line 613 of file metadata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
