.TH "FLAC__StreamMetadata_Picture" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__StreamMetadata_Picture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__StreamMetadata_Picture_Type\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBmime_type\fP"
.br
.ti -1c
.RI "\fBFLAC__byte\fP * \fBdescription\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBdepth\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBcolors\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBdata_length\fP"
.br
.ti -1c
.RI "\fBFLAC__byte\fP * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFLAC\fP PICTURE structure\&. (See the \fCformat specification\fP for the full description of each field\&.) 
.PP
Definition at line 769 of file format\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_Picture::colors"
For indexed palettes (like GIF), picture's number of colors (the number of palette entries), or \fC0\fP for non-indexed (i\&.e\&. 2^depth)\&. 
.PP
Definition at line 800 of file format\&.h\&.
.SS "\fBFLAC__byte\fP* FLAC__StreamMetadata_Picture::data"
Binary picture data\&. 
.PP
Definition at line 808 of file format\&.h\&.
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_Picture::data_length"
Length of binary picture data in bytes\&. 
.PP
Definition at line 805 of file format\&.h\&.
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_Picture::depth"
Picture's color depth in bits-per-pixel\&. 
.PP
Definition at line 797 of file format\&.h\&.
.SS "\fBFLAC__byte\fP* FLAC__StreamMetadata_Picture::description"
Picture's description in UTF-8, NUL terminated\&. In file storage, the description is stored as a 32-bit length followed by the UTF-8 string with no NUL terminator, but is converted to a plain C string in this structure for convenience\&. 
.PP
Definition at line 784 of file format\&.h\&.
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_Picture::height"
Picture's height in pixels\&. 
.PP
Definition at line 794 of file format\&.h\&.
.SS "char* FLAC__StreamMetadata_Picture::mime_type"
Picture data's MIME type, in ASCII printable characters 0x20-0x7e, NUL terminated\&. For best compatibility with players, use picture data of MIME type \fCimage/jpeg\fP or \fCimage/png\fP\&. A MIME type of '-->' is also allowed, in which case the picture data should be a complete URL\&. In file storage, the MIME type is stored as a 32-bit length followed by the ASCII string with no NUL terminator, but is converted to a plain C string in this structure for convenience\&. 
.PP
Definition at line 773 of file format\&.h\&.
.SS "\fBFLAC__StreamMetadata_Picture_Type\fP FLAC__StreamMetadata_Picture::type"
The kind of picture stored\&. 
.PP
Definition at line 770 of file format\&.h\&.
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_Picture::width"
Picture's width in pixels\&. 
.PP
Definition at line 791 of file format\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
