.TH "FLAC__StreamMetadata_VorbisComment_Entry" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__StreamMetadata_VorbisComment_Entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__uint32\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBFLAC__byte\fP * \fBentry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vorbis comment entry structure used in VORBIS_COMMENT blocks\&. (c\&.f\&. \fCformat specification\fP)
.PP
For convenience, the APIs maintain a trailing NUL character at the end of \fIentry\fP which is not counted toward \fIlength\fP, i\&.e\&. 
.PP
.nf
strlen(entry) == length 

.fi
.PP
 
.PP
Definition at line 624 of file format\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__byte\fP* FLAC__StreamMetadata_VorbisComment_Entry::entry"

.PP
Definition at line 626 of file format\&.h\&.
.SS "\fBFLAC__uint32\fP FLAC__StreamMetadata_VorbisComment_Entry::length"

.PP
Definition at line 625 of file format\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
