.TH "FLAC__StreamMetadata_CueSheet_Track" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__StreamMetadata_CueSheet_Track \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__uint64\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBFLAC__byte\fP \fBnumber\fP"
.br
.ti -1c
.RI "char \fBisrc\fP [13]"
.br
.ti -1c
.RI "unsigned \fBtype\fP:1"
.br
.ti -1c
.RI "unsigned \fBpre_emphasis\fP:1"
.br
.ti -1c
.RI "\fBFLAC__byte\fP \fBnum_indices\fP"
.br
.ti -1c
.RI "\fBFLAC__StreamMetadata_CueSheet_Index\fP * \fBindices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFLAC\fP CUESHEET track structure\&. (See the \fCformat specification\fP for the full description of each field\&.) 
.PP
Definition at line 666 of file format\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata_CueSheet_Index\fP* FLAC__StreamMetadata_CueSheet_Track::indices"
NULL if num_indices == 0, else pointer to array of index points\&. 
.PP
Definition at line 685 of file format\&.h\&.
.SS "char FLAC__StreamMetadata_CueSheet_Track::isrc[13]"
\fBTrack\fP ISRC\&. This is a 12-digit alphanumeric code plus a trailing \fCNUL\fP byte 
.PP
Definition at line 673 of file format\&.h\&.
.SS "\fBFLAC__byte\fP FLAC__StreamMetadata_CueSheet_Track::num_indices"
The number of track index points\&. 
.PP
Definition at line 682 of file format\&.h\&.
.SS "\fBFLAC__byte\fP FLAC__StreamMetadata_CueSheet_Track::number"
The track number\&. 
.PP
Definition at line 670 of file format\&.h\&.
.SS "\fBFLAC__uint64\fP FLAC__StreamMetadata_CueSheet_Track::offset"
\fBTrack\fP offset in samples, relative to the beginning of the \fBFLAC\fP audio stream\&. 
.PP
Definition at line 667 of file format\&.h\&.
.SS "unsigned FLAC__StreamMetadata_CueSheet_Track::pre_emphasis"
The pre-emphasis flag: 0 for no pre-emphasis, 1 for pre-emphasis\&. 
.PP
Definition at line 679 of file format\&.h\&.
.SS "unsigned FLAC__StreamMetadata_CueSheet_Track::type"
The track type: 0 for audio, 1 for non-audio\&. 
.PP
Definition at line 676 of file format\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
