.TH "FLAC__BitReader" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAC__BitReader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "unsigned \fBcapacity\fP"
.br
.ti -1c
.RI "unsigned \fBwords\fP"
.br
.ti -1c
.RI "unsigned \fBbytes\fP"
.br
.ti -1c
.RI "unsigned \fBconsumed_words\fP"
.br
.ti -1c
.RI "unsigned \fBconsumed_bits\fP"
.br
.ti -1c
.RI "unsigned \fBread_crc16\fP"
.br
.ti -1c
.RI "unsigned \fBcrc16_align\fP"
.br
.ti -1c
.RI "\fBFLAC__BitReaderReadCallback\fP \fBread_callback\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBclient_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file bitreader\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP* FLAC__BitReader::buffer"

.PP
Definition at line 80 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::bytes"

.PP
Definition at line 83 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::capacity"

.PP
Definition at line 81 of file bitreader\&.c\&.
.SS "\fBvoid\fP* FLAC__BitReader::client_data"

.PP
Definition at line 89 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::consumed_bits"

.PP
Definition at line 85 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::consumed_words"

.PP
Definition at line 84 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::crc16_align"

.PP
Definition at line 87 of file bitreader\&.c\&.
.SS "\fBFLAC__BitReaderReadCallback\fP FLAC__BitReader::read_callback"

.PP
Definition at line 88 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::read_crc16"

.PP
Definition at line 86 of file bitreader\&.c\&.
.SS "unsigned FLAC__BitReader::words"

.PP
Definition at line 82 of file bitreader\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
