.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/libFLAC/float.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/libFLAC/float.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FLAC/assert\&.h'\fP
.br
\fC#include 'share/compat\&.h'\fP
.br
\fC#include 'private/float\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
