.TH "flute_all_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flute_all_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBbreath_env\fP"
.br
.ti -1c
.RI "long \fBbreath_env_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBbreath_env_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBfreq_env\fP"
.br
.ti -1c
.RI "long \fBfreq_env_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBfreq_env_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBjet_delay\fP"
.br
.ti -1c
.RI "long \fBjet_delay_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBjet_delay_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBnoise_env\fP"
.br
.ti -1c
.RI "long \fBnoise_env_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBnoise_env_ptr\fP"
.br
.ti -1c
.RI "struct \fBinstr\fP * \fBmyflute\fP"
.br
.ti -1c
.RI "double \fBfrequency\fP"
.br
.ti -1c
.RI "float \fBbreath_scale\fP"
.br
.ti -1c
.RI "float \fBjet_scale\fP"
.br
.ti -1c
.RI "float \fBnoise_scale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file instrfluteall\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsound_type\fP flute_all_susp_struct::breath_env"

.PP
Definition at line 18 of file instrfluteall\&.c\&.
.SS "long flute_all_susp_struct::breath_env_cnt"

.PP
Definition at line 19 of file instrfluteall\&.c\&.
.SS "\fBsample_block_values_type\fP flute_all_susp_struct::breath_env_ptr"

.PP
Definition at line 20 of file instrfluteall\&.c\&.
.SS "float flute_all_susp_struct::breath_scale"

.PP
Definition at line 33 of file instrfluteall\&.c\&.
.SS "\fBsound_type\fP flute_all_susp_struct::freq_env"

.PP
Definition at line 21 of file instrfluteall\&.c\&.
.SS "long flute_all_susp_struct::freq_env_cnt"

.PP
Definition at line 22 of file instrfluteall\&.c\&.
.SS "\fBsample_block_values_type\fP flute_all_susp_struct::freq_env_ptr"

.PP
Definition at line 23 of file instrfluteall\&.c\&.
.SS "double flute_all_susp_struct::frequency"

.PP
Definition at line 32 of file instrfluteall\&.c\&.
.SS "\fBsound_type\fP flute_all_susp_struct::jet_delay"

.PP
Definition at line 24 of file instrfluteall\&.c\&.
.SS "long flute_all_susp_struct::jet_delay_cnt"

.PP
Definition at line 25 of file instrfluteall\&.c\&.
.SS "\fBsample_block_values_type\fP flute_all_susp_struct::jet_delay_ptr"

.PP
Definition at line 26 of file instrfluteall\&.c\&.
.SS "float flute_all_susp_struct::jet_scale"

.PP
Definition at line 34 of file instrfluteall\&.c\&.
.SS "struct \fBinstr\fP* flute_all_susp_struct::myflute"

.PP
Definition at line 31 of file instrfluteall\&.c\&.
.SS "\fBsound_type\fP flute_all_susp_struct::noise_env"

.PP
Definition at line 27 of file instrfluteall\&.c\&.
.SS "long flute_all_susp_struct::noise_env_cnt"

.PP
Definition at line 28 of file instrfluteall\&.c\&.
.SS "\fBsample_block_values_type\fP flute_all_susp_struct::noise_env_ptr"

.PP
Definition at line 29 of file instrfluteall\&.c\&.
.SS "float flute_all_susp_struct::noise_scale"

.PP
Definition at line 35 of file instrfluteall\&.c\&.
.SS "\fBsnd_susp_node\fP flute_all_susp_struct::susp"

.PP
Definition at line 16 of file instrfluteall\&.c\&.
.SS "long flute_all_susp_struct::terminate_cnt"

.PP
Definition at line 17 of file instrfluteall\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
