.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/fmfb.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/fmfb.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_fmfb\fP (\fBtime_type\fP t0, double hz, \fBrate_type\fP sr, double index, \fBtime_type\fP \fBd\fP)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_fmfb\fP (\fBtime_type\fP t0, double hz, \fBrate_type\fP sr, double index, \fBtime_type\fP \fBd\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_fmfb (\fBtime_type\fP t0, double hz, \fBrate_type\fP sr, double index, \fBtime_type\fP d)"

.PP
Definition at line 139 of file fmfb\&.c\&.
.SS "\fBsound_type\fP snd_make_fmfb (\fBtime_type\fP t0, double hz, \fBrate_type\fP sr, double index, \fBtime_type\fP d)"

.PP
Definition at line 111 of file fmfb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
