.TH "foreign_block_t" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
foreign_block_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <foreign_metadata\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__off_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBFLAC__uint32\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file foreign_metadata\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__off_t\fP foreign_block_t::offset"

.PP
Definition at line 41 of file foreign_metadata\&.h\&.
.SS "\fBFLAC__uint32\fP foreign_block_t::size"

.PP
Definition at line 49 of file foreign_metadata\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
