.TH "FreqWindow" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreqWindow \- Displays a spectrum plot of the waveform\&. Has options for selecting parameters of the plot\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FreqWindow\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFreqWindow\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxString &title, \fBconst\fP wxPoint &pos)"
.br
.ti -1c
.RI "virtual \fB~FreqWindow\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBShow\fP (\fBbool\fP show=\fBtrue\fP) override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFreqPlot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Displays a spectrum plot of the waveform\&. Has options for selecting parameters of the plot\&. 

Has a feature that finds peaks and reports their value as you move the mouse around\&. 
.PP
Definition at line 126 of file FreqWindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FreqWindow::FreqWindow (wxWindow * parent, wxWindowID id, \fBconst\fP wxString & title, \fBconst\fP wxPoint & pos)"

.PP
Definition at line 187 of file FreqWindow\&.cpp\&.
.SS "FreqWindow::~FreqWindow ()\fC [virtual]\fP"

.PP
Definition at line 516 of file FreqWindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP FreqWindow::Show (\fBbool\fP show = \fC\fBtrue\fP\fP)\fC [override]\fP"

.PP
Definition at line 526 of file FreqWindow\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBFreqPlot\fP\fC [friend]\fP"

.PP
Definition at line 220 of file FreqWindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
