.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libscorealign/gen_chroma.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libscorealign/gen_chroma.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHROMA_BIN_COUNT\fP   12"
.br
.ti -1c
.RI "#define \fBAREF1\fP(chrom_energy,  row)   ((chrom_energy) + (row) * (\fBCHROMA_BIN_COUNT\fP + 1))"
.br
.ti -1c
.RI "#define \fBAREF2\fP(chrom_energy,  row,  column)   \fBAREF1\fP(chrom_energy, row)[column]"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBis_midi_file\fP (char *\fBfilename\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AREF1(chrom_energy, row)   ((chrom_energy) + (row) * (\fBCHROMA_BIN_COUNT\fP + 1))"

.PP
Definition at line 6 of file gen_chroma\&.h\&.
.SS "#define AREF2(chrom_energy, row, column)   \fBAREF1\fP(chrom_energy, row)[column]"

.PP
Definition at line 10 of file gen_chroma\&.h\&.
.SS "#define CHROMA_BIN_COUNT   12"

.PP
Definition at line 1 of file gen_chroma\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP is_midi_file (char * filename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
