.TH "GeometricInputRateTimeWarper" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeometricInputRateTimeWarper \- TimeScale - rate varies geometrically with input\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TimeWarper\&.h>\fP
.SH "Detailed Description"
.PP 
TimeScale - rate varies geometrically with input\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
