.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/share/getopt.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/share/getopt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBshare__option\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBshare__no_argument\fP   0"
.br
.ti -1c
.RI "#define \fBshare__required_argument\fP   1"
.br
.ti -1c
.RI "#define \fBshare__optional_argument\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBshare__getopt\fP (\fBint\fP \fBargc\fP, char *\fBconst\fP *\fBargv\fP, \fBconst\fP char *shortopts)"
.br
.ti -1c
.RI "\fBint\fP \fBshare__getopt_long\fP (\fBint\fP \fBargc\fP, char *\fBconst\fP *\fBargv\fP, \fBconst\fP char *shortopts, \fBconst\fP struct \fBshare__option\fP *longopts, \fBint\fP *longind)"
.br
.ti -1c
.RI "\fBint\fP \fBshare__getopt_long_only\fP (\fBint\fP \fBargc\fP, char *\fBconst\fP *\fBargv\fP, \fBconst\fP char *shortopts, \fBconst\fP struct \fBshare__option\fP *longopts, \fBint\fP *longind)"
.br
.ti -1c
.RI "\fBint\fP \fBshare___getopt_internal\fP (\fBint\fP \fBargc\fP, char *\fBconst\fP *\fBargv\fP, \fBconst\fP char *shortopts, \fBconst\fP struct \fBshare__option\fP *longopts, \fBint\fP *longind, \fBint\fP long_only)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBshare__optarg\fP"
.br
.ti -1c
.RI "\fBint\fP \fBshare__optind\fP"
.br
.ti -1c
.RI "\fBint\fP \fBshare__opterr\fP"
.br
.ti -1c
.RI "\fBint\fP \fBshare__optopt\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define share__no_argument   0"

.PP
Definition at line 114 of file getopt\&.h\&.
.SS "#define share__optional_argument   2"

.PP
Definition at line 116 of file getopt\&.h\&.
.SS "#define share__required_argument   1"

.PP
Definition at line 115 of file getopt\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP share___getopt_internal (\fBint\fP argc, char *\fBconst\fP * argv, \fBconst\fP char * shortopts, \fBconst\fP struct \fBshare__option\fP * longopts, \fBint\fP * longind, \fBint\fP long_only)"

.PP
Definition at line 524 of file getopt\&.c\&.
.SS "\fBint\fP share__getopt (\fBint\fP argc, char *\fBconst\fP * argv, \fBconst\fP char * shortopts)"

.PP
Definition at line 980 of file getopt\&.c\&.
.SS "\fBint\fP share__getopt_long (\fBint\fP argc, char *\fBconst\fP * argv, \fBconst\fP char * shortopts, \fBconst\fP struct \fBshare__option\fP * longopts, \fBint\fP * longind)"

.PP
Definition at line 83 of file getopt1\&.c\&.
.SS "\fBint\fP share__getopt_long_only (\fBint\fP argc, char *\fBconst\fP * argv, \fBconst\fP char * shortopts, \fBconst\fP struct \fBshare__option\fP * longopts, \fBint\fP * longind)"

.PP
Definition at line 99 of file getopt1\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char* share__optarg"

.PP
Definition at line 128 of file getopt\&.c\&.
.SS "\fBint\fP share__opterr"

.PP
Definition at line 163 of file getopt\&.c\&.
.SS "\fBint\fP share__optind"

.PP
Definition at line 143 of file getopt\&.c\&.
.SS "\fBint\fP share__optopt"

.PP
Definition at line 169 of file getopt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
