.TH "GlobalPrefsDialog" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlobalPrefsDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PrefsDialog\&.h>\fP
.PP
Inherits \fBPrefsDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalPrefsDialog\fP (wxWindow *parent, \fBFactories\fP &factories=\fBDefaultFactories\fP())"
.br
.ti -1c
.RI "virtual \fB~GlobalPrefsDialog\fP ()"
.br
.ti -1c
.RI "long \fBGetPreferredPage\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSavePreferredPage\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 89 of file PrefsDialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GlobalPrefsDialog::GlobalPrefsDialog (wxWindow * parent, \fBFactories\fP & factories = \fC\fBDefaultFactories\fP()\fP)"

.PP
Definition at line 471 of file PrefsDialog\&.cpp\&.
.SS "GlobalPrefsDialog::~GlobalPrefsDialog ()\fC [virtual]\fP"

.PP
Definition at line 476 of file PrefsDialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "long GlobalPrefsDialog::GetPreferredPage ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsDialog\fP\&.
.PP
Definition at line 480 of file PrefsDialog\&.cpp\&.
.SS "\fBvoid\fP GlobalPrefsDialog::SavePreferredPage ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsDialog\fP\&.
.PP
Definition at line 486 of file PrefsDialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
