.TH "gp_args_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gp_args_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBarg\fP [\fBMAX_GPRINTF_ARGS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 842 of file userio\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "long gp_args_struct::arg[\fBMAX_GPRINTF_ARGS\fP]"

.PP
Definition at line 843 of file userio\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
