.TH "GrabberEvent" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GrabberEvent \- \fBGrabber\fP Class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grabber\&.h>\fP
.PP
Inherits wxCommandEvent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrabberEvent\fP (wxEventType type=wxEVT_NULL, wxWindowID winid=0, \fBconst\fP wxPoint &pt=wxDefaultPosition)"
.br
.ti -1c
.RI "\fBGrabberEvent\fP (\fBconst\fP \fBGrabberEvent\fP &event)"
.br
.ti -1c
.RI "\fBconst\fP wxPoint & \fBGetPosition\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPosition\fP (\fBconst\fP wxPoint &pos)"
.br
.ti -1c
.RI "wxEvent * \fBClone\fP () \fBconst\fP  override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxPoint \fBmPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGrabber\fP Class\&. 
.PP
Definition at line 42 of file Grabber\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GrabberEvent::GrabberEvent (wxEventType type = \fCwxEVT_NULL\fP, wxWindowID winid = \fC0\fP, \fBconst\fP wxPoint & pt = \fCwxDefaultPosition\fP)\fC [inline]\fP"

.PP
Definition at line 46 of file Grabber\&.h\&.
.SS "GrabberEvent::GrabberEvent (\fBconst\fP \fBGrabberEvent\fP & event)\fC [inline]\fP"

.PP
Definition at line 54 of file Grabber\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "wxEvent* GrabberEvent::Clone () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 71 of file Grabber\&.h\&.
.SS "\fBconst\fP wxPoint& GrabberEvent::GetPosition () const\fC [inline]\fP"

.PP
Definition at line 61 of file Grabber\&.h\&.
.SS "\fBvoid\fP GrabberEvent::SetPosition (\fBconst\fP wxPoint & pos)\fC [inline]\fP"

.PP
Definition at line 66 of file Grabber\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wxPoint GrabberEvent::mPos\fC [protected]\fP"

.PP
Definition at line 78 of file Grabber\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
