.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/sbsms/src/grain.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/sbsms/src/grain.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fft\&.h'\fP
.br
\fC#include 'sbsms\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_sbsms_::grain\fP"
.br
.ti -1c
.RI "class \fB_sbsms_::GrainAllocator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fB_sbsms_\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_sbsms_::windowType\fP { \fB_sbsms_::hann\fP, \fB_sbsms_::hannpoisson\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
