.TH "C:/_dev/OpenU/Audacity/audacity/src/widgets/Grid.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/widgets/Grid.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/choice\&.h>\fP
.br
\fC#include <wx/dc\&.h>\fP
.br
\fC#include <wx/grid\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/settings\&.h>\fP
.br
\fC#include <wx/toplevel\&.h>\fP
.br
\fC#include 'Grid\&.h'\fP
.br
\fC#include 'NumericTextCtrl\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
