.TH "Grid" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grid \- Supplies an accessible grid based on wxGrid\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grid\&.h>\fP
.PP
Inherits wxGrid\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrid\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize, long style=wxWANTS_CHARS|wxBORDER, \fBconst\fP wxString &\fBname\fP=wxPanelNameStr)"
.br
.ti -1c
.RI "\fB~Grid\fP ()"
.br
.ti -1c
.RI "\fBDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBOnSetFocus\fP (wxFocusEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSelectCell\fP (wxGridEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnKeyDown\fP (wxKeyEvent &event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Supplies an accessible grid based on wxGrid\&. 
.PP
Definition at line 184 of file Grid\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Grid::Grid (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP, long style = \fCwxWANTS_CHARS | wxBORDER\fP, \fBconst\fP wxString & name = \fCwxPanelNameStr\fP)"

.PP
Definition at line 380 of file Grid\&.cpp\&.
.SS "Grid::~Grid ()"

.PP
Definition at line 402 of file Grid\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "Grid::DECLARE_EVENT_TABLE ()"

.SS "\fBvoid\fP Grid::OnKeyDown (wxKeyEvent & event)\fC [protected]\fP"

.PP
Definition at line 432 of file Grid\&.cpp\&.
.SS "\fBvoid\fP Grid::OnSelectCell (wxGridEvent & event)\fC [protected]\fP"

.PP
Definition at line 423 of file Grid\&.cpp\&.
.SS "\fBvoid\fP Grid::OnSetFocus (wxFocusEvent & event)\fC [protected]\fP"

.PP
Definition at line 414 of file Grid\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
