.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610/gsm.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610/gsm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGSM_MAGIC\fP   0xD		  	/* 13 kbit/s RPE\-LTP */"
.br
.ti -1c
.RI "#define \fBGSM_PATCHLEVEL\fP   10"
.br
.ti -1c
.RI "#define \fBGSM_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBGSM_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBGSM_OPT_VERBOSE\fP   1"
.br
.ti -1c
.RI "#define \fBGSM_OPT_FAST\fP   2"
.br
.ti -1c
.RI "#define \fBGSM_OPT_LTP_CUT\fP   3"
.br
.ti -1c
.RI "#define \fBGSM_OPT_WAV49\fP   4"
.br
.ti -1c
.RI "#define \fBGSM_OPT_FRAME_INDEX\fP   5"
.br
.ti -1c
.RI "#define \fBGSM_OPT_FRAME_CHAIN\fP   6"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBgsm_state\fP * \fBgsm\fP"
.br
.ti -1c
.RI "typedef short \fBgsm_signal\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBgsm_byte\fP"
.br
.ti -1c
.RI "typedef \fBgsm_byte\fP \fBgsm_frame\fP[33]"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgsm\fP \fBgsm_create\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgsm_init\fP (\fBgsm\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgsm_destroy\fP (\fBgsm\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBgsm_print\fP (FILE *, \fBgsm\fP, \fBgsm_byte\fP *)"
.br
.ti -1c
.RI "\fBint\fP \fBgsm_option\fP (\fBgsm\fP, \fBint\fP, \fBint\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgsm_encode\fP (\fBgsm\fP, \fBgsm_signal\fP *, \fBgsm_byte\fP *)"
.br
.ti -1c
.RI "\fBint\fP \fBgsm_decode\fP (\fBgsm\fP, \fBgsm_byte\fP *, \fBgsm_signal\fP *)"
.br
.ti -1c
.RI "\fBint\fP \fBgsm_explode\fP (\fBgsm\fP, \fBgsm_byte\fP *, \fBgsm_signal\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgsm_implode\fP (\fBgsm\fP, \fBgsm_signal\fP *, \fBgsm_byte\fP *)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GSM_MAGIC   0xD		  	/* 13 kbit/s RPE\-LTP */"

.PP
Definition at line 21 of file gsm\&.h\&.
.SS "#define GSM_MAJOR   1"

.PP
Definition at line 25 of file gsm\&.h\&.
.SS "#define GSM_MINOR   0"

.PP
Definition at line 24 of file gsm\&.h\&.
.SS "#define GSM_OPT_FAST   2"

.PP
Definition at line 28 of file gsm\&.h\&.
.SS "#define GSM_OPT_FRAME_CHAIN   6"

.PP
Definition at line 32 of file gsm\&.h\&.
.SS "#define GSM_OPT_FRAME_INDEX   5"

.PP
Definition at line 31 of file gsm\&.h\&.
.SS "#define GSM_OPT_LTP_CUT   3"

.PP
Definition at line 29 of file gsm\&.h\&.
.SS "#define GSM_OPT_VERBOSE   1"

.PP
Definition at line 27 of file gsm\&.h\&.
.SS "#define GSM_OPT_WAV49   4"

.PP
Definition at line 30 of file gsm\&.h\&.
.SS "#define GSM_PATCHLEVEL   10"

.PP
Definition at line 23 of file gsm\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBgsm_state\fP* \fBgsm\fP"

.PP
Definition at line 16 of file gsm\&.h\&.
.SS "typedef unsigned char \fBgsm_byte\fP"

.PP
Definition at line 18 of file gsm\&.h\&.
.SS "typedef \fBgsm_byte\fP gsm_frame[33]"

.PP
Definition at line 19 of file gsm\&.h\&.
.SS "typedef short \fBgsm_signal\fP"

.PP
Definition at line 17 of file gsm\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBgsm\fP gsm_create (\fBvoid\fP)"

.PP
Definition at line 18 of file gsm_create\&.c\&.
.SS "\fBint\fP gsm_decode (\fBgsm\fP, \fBgsm_byte\fP *, \fBgsm_signal\fP *)"

.PP
Definition at line 11 of file gsm_decode\&.c\&.
.SS "\fBvoid\fP gsm_destroy (\fBgsm\fP)"

.PP
Definition at line 20 of file gsm_destroy\&.c\&.
.SS "\fBvoid\fP gsm_encode (\fBgsm\fP, \fBgsm_signal\fP *, \fBgsm_byte\fP *)"

.PP
Definition at line 10 of file gsm_encode\&.c\&.
.SS "\fBint\fP gsm_explode (\fBgsm\fP, \fBgsm_byte\fP *, \fBgsm_signal\fP *)"

.SS "\fBvoid\fP gsm_implode (\fBgsm\fP, \fBgsm_signal\fP *, \fBgsm_byte\fP *)"

.SS "\fBvoid\fP gsm_init (\fBgsm\fP)"

.PP
Definition at line 32 of file gsm_create\&.c\&.
.SS "\fBint\fP gsm_option (\fBgsm\fP, \fBint\fP, \fBint\fP *)"

.PP
Definition at line 11 of file gsm_option\&.c\&.
.SS "\fBint\fP gsm_print (FILE *, \fBgsm\fP, \fBgsm_byte\fP *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
