.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610/gsm_create.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/GSM610/gsm_create.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'gsm\&.h'\fP
.br
\fC#include 'gsm610_priv\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgsm\fP \fBgsm_create\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgsm_init\fP (\fBgsm\fP state)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgsm\fP gsm_create (\fBvoid\fP)"

.PP
Definition at line 18 of file gsm_create\&.c\&.
.SS "\fBvoid\fP gsm_init (\fBgsm\fP state)"

.PP
Definition at line 32 of file gsm_create\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
