.TH "GUIPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIPrefs \- A \fBPrefsPanel\fP for general GUI preferences\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GUIPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGUIPrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fB~GUIPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBGetRangeChoices\fP (wxArrayString *pChoices, wxArrayString *pCodes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP for general GUI preferences\&. 
.PP
Definition at line 25 of file GUIPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GUIPrefs::GUIPrefs (wxWindow * parent)"

.PP
Definition at line 34 of file GUIPrefs\&.cpp\&.
.SS "GUIPrefs::~GUIPrefs ()"

.PP
Definition at line 40 of file GUIPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP GUIPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 162 of file GUIPrefs\&.cpp\&.
.SS "\fBvoid\fP GUIPrefs::GetRangeChoices (wxArrayString * pChoices, wxArrayString * pCodes)\fC [static]\fP"

.PP
Definition at line 44 of file GUIPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
