.TH "HASH_TABLE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HASH_TABLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNAMED\fP ** \fBv\fP"
.br
.ti -1c
.RI "unsigned char \fBpower\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBused\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Memory_Handling_Suite\fP * \fBmem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBXML_Memory_Handling_Suite\fP* HASH_TABLE::mem"

.PP
Definition at line 102 of file xmlparse\&.c\&.
.SS "unsigned char HASH_TABLE::power"

.PP
Definition at line 99 of file xmlparse\&.c\&.
.SS "size_t HASH_TABLE::size"

.PP
Definition at line 100 of file xmlparse\&.c\&.
.SS "size_t HASH_TABLE::used"

.PP
Definition at line 101 of file xmlparse\&.c\&.
.SS "\fBNAMED\fP** HASH_TABLE::v"

.PP
Definition at line 98 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
