.TH "C:/_dev/OpenU/Audacity/audacity/src/HelpText.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/HelpText.cpp \- Given a key, returns some html\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include 'Audacity\&.h'\fP
.br
\fC#include 'HelpText\&.h'\fP
.br
\fC#include 'FileNames\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "wxString \fBTitleText\fP (\fBconst\fP wxString &Key)"
.br
.ti -1c
.RI "wxString \fBHelpText\fP (\fBconst\fP wxString &Key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Given a key, returns some html\&. 


.PP
Definition in file \fBHelpText\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "wxString HelpText (\fBconst\fP wxString & Key)"

.PP
Definition at line 231 of file HelpText\&.cpp\&.
.SS "wxString TitleText (\fBconst\fP wxString & Key)"

.PP
Definition at line 116 of file HelpText\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
