.TH "HistoryWindow" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HistoryWindow \- Works with \fBUndoManager\fP to allow user to see descriptions of and undo previous commands\&. Also allows you to selectively clear the undo memory so as to free up space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HistoryWindow\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryWindow\fP (\fBAudacityProject\fP *parent, \fBUndoManager\fP *manager)"
.br
.ti -1c
.RI "\fB~HistoryWindow\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateDisplay\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Works with \fBUndoManager\fP to allow user to see descriptions of and undo previous commands\&. Also allows you to selectively clear the undo memory so as to free up space\&. 
.PP
Definition at line 26 of file HistoryWindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HistoryWindow::HistoryWindow (\fBAudacityProject\fP * parent, \fBUndoManager\fP * manager)"

.PP
Definition at line 55 of file HistoryWindow\&.cpp\&.
.SS "HistoryWindow::~HistoryWindow ()"

.PP
Definition at line 147 of file HistoryWindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP HistoryWindow::UpdateDisplay ()"

.PP
Definition at line 174 of file HistoryWindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
