.TH "C:/_dev/OpenU/Audacity/audacity/src/HistoryWindow.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/HistoryWindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Audacity\&.h'\fP
.br
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/dialog\&.h>\fP
.br
\fC#include <wx/event\&.h>\fP
.br
\fC#include <wx/imaglist\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/listctrl\&.h>\fP
.br
\fC#include <wx/settings\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include 'AudioIO\&.h'\fP
.br
\fC#include '\&.\&./images/Arrow\&.xpm'\fP
.br
\fC#include '\&.\&./images/Empty9x16\&.xpm'\fP
.br
\fC#include 'HistoryWindow\&.h'\fP
.br
\fC#include 'UndoManager\&.h'\fP
.br
\fC#include 'Project\&.h'\fP
.br
\fC#include 'ShuttleGui\&.h'\fP
.br
\fC#include 'Track\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBID_AVAIL\fP = 1000, \fBID_TOTAL\fP, \fBID_LEVELS\fP, \fBID_DISCARD\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIID_AVAIL \fP\fP
.TP
\fB\fIID_TOTAL \fP\fP
.TP
\fB\fIID_LEVELS \fP\fP
.TP
\fB\fIID_DISCARD \fP\fP
.PP
Definition at line 41 of file HistoryWindow\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
