.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/htk.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/htk.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSFE_HTK_BAD_FILE_LEN\fP   1666"
.br
.ti -1c
.RI "#define \fBSFE_HTK_NOT_WAVEFORM\fP   1667"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBhtk_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SFE_HTK_BAD_FILE_LEN   1666"

.PP
Definition at line 34 of file htk\&.c\&.
.SS "#define SFE_HTK_NOT_WAVEFORM   1667"

.PP
Definition at line 35 of file htk\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP htk_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 51 of file htk\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
