.TH "HtmlTextHelpDialog" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HtmlTextHelpDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ErrorDialog\&.h>\fP
.PP
Inherits \fBBrowserFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHtmlTextHelpDialog\fP ()"
.br
.ti -1c
.RI "virtual \fB~HtmlTextHelpDialog\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 44 of file ErrorDialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HtmlTextHelpDialog::HtmlTextHelpDialog ()\fC [inline]\fP"

.PP
Definition at line 47 of file ErrorDialog\&.h\&.
.SS "virtual HtmlTextHelpDialog::~HtmlTextHelpDialog ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 53 of file ErrorDialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
