.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libmad/huffman.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libmad/huffman.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.h'\fP
.br
\fC#include 'huffman\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPTR\fP(offs,  \fBbits\fP)   { { 0, \fBbits\fP, offs } }"
.br
.ti -1c
.RI "#define \fBV\fP(v,  w,  x,  y,  hlen)"
.br
.ti -1c
.RI "#define \fBPTR\fP(offs,  \fBbits\fP)   { { 0, \fBbits\fP, offs } }"
.br
.ti -1c
.RI "#define \fBV\fP(x,  y,  hlen)   { { 1, hlen, (x << 0) | (y << 4) } }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "union \fBhuffquad\fP \fBconst\fP *\fBconst\fP \fBmad_huff_quad_table\fP [2] = { hufftabA, hufftabB }"
.br
.ti -1c
.RI "struct \fBhufftable\fP \fBconst\fP \fBmad_huff_pair_table\fP [32]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PTR(offs, \fBbits\fP)   { { 0, \fBbits\fP, offs } }"

.PP
Definition at line 120 of file huffman\&.c\&.
.SS "#define PTR(offs, \fBbits\fP)   { { 0, \fBbits\fP, offs } }"

.PP
Definition at line 120 of file huffman\&.c\&.
.SS "#define V(v, w, x, y, hlen)"
\fBValue:\fP
.PP
.nf
{ { 1, hlen, (v <<  0) | (w <<  1) |  \
                                             (x <<  2) | (y <<  3) } }
.fi
.PP
Definition at line 124 of file huffman\&.c\&.
.SS "#define V(x, y, hlen)   { { 1, hlen, (x << 0) | (y << 4) } }"

.PP
Definition at line 124 of file huffman\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBhufftable\fP \fBconst\fP mad_huff_pair_table[32]"

.PP
Definition at line 3076 of file huffman\&.c\&.
.SS "union \fBhuffquad\fP \fBconst\fP* \fBconst\fP mad_huff_quad_table[2] = { hufftabA, hufftabB }"

.PP
Definition at line 3074 of file huffman\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
