.TH "HwDevInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HwDevInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBalsaName\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBint\fP \fBisPlug\fP"
.br
.ti -1c
.RI "\fBint\fP \fBhasPlayback\fP"
.br
.ti -1c
.RI "\fBint\fP \fBhasCapture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 984 of file pa_linux_alsa\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char* HwDevInfo::alsaName"

.PP
Definition at line 986 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP HwDevInfo::hasCapture"

.PP
Definition at line 990 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP HwDevInfo::hasPlayback"

.PP
Definition at line 989 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP HwDevInfo::isPlug"

.PP
Definition at line 988 of file pa_linux_alsa\&.c\&.
.SS "char* HwDevInfo::name"

.PP
Definition at line 987 of file pa_linux_alsa\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
