.TH "IAudioMuteVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IAudioMuteVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <devicetopology\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIAudioMute\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIAudioMute\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIAudioMute\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetMute)(\fBIAudioMute\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetMute)(\fBIAudioMute\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBBOOL\fP \fBbMuted\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBBOOL\fP \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.ti -1c
.RI "\fB__out\fP \fBBOOL\fP * \fBpbMuted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1313 of file devicetopology\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IAudioMuteVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IAudioMuteVtbl::HRESULT (STDMETHODCALLTYPE * SetMute)"

.SS "IAudioMuteVtbl::HRESULT (STDMETHODCALLTYPE * GetMute)"

.SS "IAudioMuteVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IAudioMuteVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBBOOL\fP IAudioMuteVtbl::bMuted"

.PP
Definition at line 1332 of file devicetopology\&.h\&.
.SS "\fB__out\fP \fBBOOL\fP* IAudioMuteVtbl::pbMuted"

.PP
Definition at line 1339 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBBOOL\fP \fB__in_opt\fP \fBLPCGUID\fP IAudioMuteVtbl::pguidEventContext"

.PP
Definition at line 1332 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IAudioMuteVtbl::ppvObject"

.PP
Definition at line 1319 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IAudioMuteVtbl::riid"

.PP
Definition at line 1319 of file devicetopology\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
