.TH "IAudioBassVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IAudioBassVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <devicetopology\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIAudioBass\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIAudioBass\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetChannelCount)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetLevelRange)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetLevel)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevel)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevelUniform)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevelAllChannels)(\fBIAudioBass\fP *This"
.br
.ti -1c
.RI "\fB__in_ecount\fP (\fBcChannels\fP) float aLevelsDB[]"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__out\fP \fBUINT\fP * \fBpcChannels\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fBnChannel\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float * \fBpfMinLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float * \fBpfMaxLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float \fB__out\fP float * \fBpfStepping\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float * \fBpfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__in\fP float \fBfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.ti -1c
.RI "\fB__in\fP float \fBfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBULONG\fP \fBcChannels\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBULONG\fP \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1400 of file devicetopology\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "IAudioBassVtbl::__in_ecount (\fBcChannels\fP)"

.SS "BEGIN_INTERFACE IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * GetChannelCount)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * GetLevelRange)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * GetLevel)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * SetLevel)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * SetLevelUniform)"

.SS "IAudioBassVtbl::HRESULT (STDMETHODCALLTYPE * SetLevelAllChannels)"

.SS "IAudioBassVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IAudioBassVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBULONG\fP IAudioBassVtbl::cChannels"

.PP
Definition at line 1460 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__in\fP float IAudioBassVtbl::fLevelDB"

.PP
Definition at line 1442 of file devicetopology\&.h\&.
.SS "\fB__in\fP float IAudioBassVtbl::fLevelDB"

.PP
Definition at line 1451 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP IAudioBassVtbl::nChannel"

.PP
Definition at line 1424 of file devicetopology\&.h\&.
.SS "\fB__out\fP \fBUINT\fP* IAudioBassVtbl::pcChannels"

.PP
Definition at line 1419 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float* IAudioBassVtbl::pfLevelDB"

.PP
Definition at line 1435 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float* IAudioBassVtbl::pfMaxLevelDB"

.PP
Definition at line 1424 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float* IAudioBassVtbl::pfMinLevelDB"

.PP
Definition at line 1424 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float \fB__out\fP float* IAudioBassVtbl::pfStepping"

.PP
Definition at line 1424 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP IAudioBassVtbl::pguidEventContext"

.PP
Definition at line 1442 of file devicetopology\&.h\&.
.SS "\fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP IAudioBassVtbl::pguidEventContext"

.PP
Definition at line 1451 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBULONG\fP \fB__in_opt\fP \fBLPCGUID\fP IAudioBassVtbl::pguidEventContext"

.PP
Definition at line 1460 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IAudioBassVtbl::ppvObject"

.PP
Definition at line 1406 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IAudioBassVtbl::riid"

.PP
Definition at line 1406 of file devicetopology\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
