.TH "IAudioClientVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IAudioClientVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <audioclient\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIAudioClient\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIAudioClient\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Initialize)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetBufferSize)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetStreamLatency)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetCurrentPadding)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *IsFormatSupported)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetMixFormat)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDevicePeriod)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Start)(\fBIAudioClient\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Stop)(\fBIAudioClient\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Reset)(\fBIAudioClient\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetEventHandle)(\fBIAudioClient\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetService)(\fBIAudioClient\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fBShareMode\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fBStreamFlags\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fBhnsBufferDuration\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP \fBhnsPeriodicity\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBconst\fP WAVEFORMATEX * \fBpFormat\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBconst\fP WAVEFORMATEX \fB__in_opt\fP \fBLPCGUID\fP \fBAudioSessionGuid\fP"
.br
.ti -1c
.RI "\fB__out\fP UINT32 * \fBpNumBufferFrames\fP"
.br
.ti -1c
.RI "\fB__out\fP \fBREFERENCE_TIME\fP * \fBphnsLatency\fP"
.br
.ti -1c
.RI "\fB__out\fP UINT32 * \fBpNumPaddingFrames\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBconst\fP WAVEFORMATEX * \fBpFormat\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBconst\fP WAVEFORMATEX \fB__out_opt\fP WAVEFORMATEX ** \fBppClosestMatch\fP"
.br
.ti -1c
.RI "\fB__out\fP WAVEFORMATEX ** \fBppDeviceFormat\fP"
.br
.ti -1c
.RI "\fB__out_opt\fP \fBREFERENCE_TIME\fP * \fBphnsDefaultDevicePeriod\fP"
.br
.ti -1c
.RI "\fB__out_opt\fP \fBREFERENCE_TIME\fP \fB__out_opt\fP \fBREFERENCE_TIME\fP * \fBphnsMinimumDevicePeriod\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBeventHandle\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fB__out\fP \fBvoid\fP ** \fBppv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 218 of file audioclient\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * Initialize)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetBufferSize)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetStreamLatency)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetCurrentPadding)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * IsFormatSupported)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetMixFormat)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetDevicePeriod)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * Start)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * Stop)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * Reset)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * SetEventHandle)"

.SS "IAudioClientVtbl::HRESULT (STDMETHODCALLTYPE * GetService)"

.SS "IAudioClientVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IAudioClientVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBconst\fP WAVEFORMATEX \fB__in_opt\fP \fBLPCGUID\fP IAudioClientVtbl::AudioSessionGuid"

.PP
Definition at line 237 of file audioclient\&.h\&.
.SS "\fBHANDLE\fP IAudioClientVtbl::eventHandle"

.PP
Definition at line 296 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP IAudioClientVtbl::hnsBufferDuration"

.PP
Definition at line 237 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP IAudioClientVtbl::hnsPeriodicity"

.PP
Definition at line 237 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBREFERENCE_TIME\fP \fB__in\fP \fBconst\fP WAVEFORMATEX* IAudioClientVtbl::pFormat"

.PP
Definition at line 237 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBconst\fP WAVEFORMATEX* IAudioClientVtbl::pFormat"

.PP
Definition at line 267 of file audioclient\&.h\&.
.SS "\fB__out_opt\fP \fBREFERENCE_TIME\fP* IAudioClientVtbl::phnsDefaultDevicePeriod"

.PP
Definition at line 281 of file audioclient\&.h\&.
.SS "\fB__out\fP \fBREFERENCE_TIME\fP* IAudioClientVtbl::phnsLatency"

.PP
Definition at line 257 of file audioclient\&.h\&.
.SS "\fB__out_opt\fP \fBREFERENCE_TIME\fP \fB__out_opt\fP \fBREFERENCE_TIME\fP* IAudioClientVtbl::phnsMinimumDevicePeriod"

.PP
Definition at line 281 of file audioclient\&.h\&.
.SS "\fB__out\fP UINT32* IAudioClientVtbl::pNumBufferFrames"

.PP
Definition at line 252 of file audioclient\&.h\&.
.SS "\fB__out\fP UINT32* IAudioClientVtbl::pNumPaddingFrames"

.PP
Definition at line 262 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBconst\fP WAVEFORMATEX \fB__out_opt\fP WAVEFORMATEX** IAudioClientVtbl::ppClosestMatch"

.PP
Definition at line 267 of file audioclient\&.h\&.
.SS "\fB__out\fP WAVEFORMATEX** IAudioClientVtbl::ppDeviceFormat"

.PP
Definition at line 276 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBREFIID\fP \fB__out\fP \fBvoid\fP** IAudioClientVtbl::ppv"

.PP
Definition at line 301 of file audioclient\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IAudioClientVtbl::ppvObject"

.PP
Definition at line 224 of file audioclient\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IAudioClientVtbl::riid"

.PP
Definition at line 224 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBREFIID\fP IAudioClientVtbl::riid"

.PP
Definition at line 301 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP IAudioClientVtbl::ShareMode"

.PP
Definition at line 237 of file audioclient\&.h\&.
.SS "\fB__in\fP \fBAUDCLNT_SHAREMODE\fP \fB__in\fP \fBDWORD\fP IAudioClientVtbl::StreamFlags"

.PP
Definition at line 237 of file audioclient\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
