.TH "id3_file" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
id3_file \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBiofile\fP"
.br
.ti -1c
.RI "enum \fBid3_file_mode\fP \fBmode\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "\fBint\fP \fBflags\fP"
.br
.ti -1c
.RI "struct \fBid3_tag\fP * \fBprimary\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBntags\fP"
.br
.ti -1c
.RI "struct \fBfiletag\fP * \fBtags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file file\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP id3_file::flags"

.PP
Definition at line 56 of file file\&.c\&.
.SS "FILE* id3_file::iofile"

.PP
Definition at line 52 of file file\&.c\&.
.SS "enum \fBid3_file_mode\fP id3_file::mode"

.PP
Definition at line 53 of file file\&.c\&.
.SS "unsigned \fBint\fP id3_file::ntags"

.PP
Definition at line 60 of file file\&.c\&.
.SS "char* id3_file::path"

.PP
Definition at line 54 of file file\&.c\&.
.SS "struct \fBid3_tag\fP* id3_file::primary"

.PP
Definition at line 58 of file file\&.c\&.
.SS "struct \fBfiletag\fP* id3_file::tags"

.PP
Definition at line 61 of file file\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
