.TH "id3_field" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
id3_field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <id3tag\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   signed long \fBvalue\fP"
.br
.ti -1c
.RI "} \fBnumber\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   \fBid3_latin1_t\fP * \fBptr\fP"
.br
.ti -1c
.RI "} \fBlatin1\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   unsigned \fBint\fP \fBnstrings\fP"
.br
.ti -1c
.RI "   \fBid3_latin1_t\fP ** \fBstrings\fP"
.br
.ti -1c
.RI "} \fBlatin1list\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   \fBid3_ucs4_t\fP * \fBptr\fP"
.br
.ti -1c
.RI "} \fBstring\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   unsigned \fBint\fP \fBnstrings\fP"
.br
.ti -1c
.RI "   \fBid3_ucs4_t\fP ** \fBstrings\fP"
.br
.ti -1c
.RI "} \fBstringlist\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   char \fBvalue\fP [9]"
.br
.ti -1c
.RI "} \fBimmediate\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   enum \fBid3_field_type\fP \fBtype\fP"
.br
.ti -1c
.RI "   \fBid3_byte_t\fP * \fBdata\fP"
.br
.ti -1c
.RI "   \fBid3_length_t\fP \fBlength\fP"
.br
.ti -1c
.RI "} \fBbinary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file id3tag\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. }   id3_field::binary"

.SS "\fBid3_byte_t\fP* id3_field::data"

.PP
Definition at line 238 of file id3tag\&.h\&.
.SS "struct { \&.\&.\&. }   id3_field::immediate"

.SS "struct { \&.\&.\&. }   id3_field::latin1"

.SS "struct { \&.\&.\&. }   id3_field::latin1list"

.SS "\fBid3_length_t\fP id3_field::length"

.PP
Definition at line 239 of file id3tag\&.h\&.
.SS "unsigned \fBint\fP id3_field::nstrings"

.PP
Definition at line 220 of file id3tag\&.h\&.
.SS "struct { \&.\&.\&. }   id3_field::number"

.SS "\fBid3_latin1_t\fP* id3_field::ptr"

.PP
Definition at line 216 of file id3tag\&.h\&.
.SS "\fBid3_ucs4_t\fP* id3_field::ptr"

.PP
Definition at line 225 of file id3tag\&.h\&.
.SS "struct { \&.\&.\&. }   id3_field::string"

.SS "struct { \&.\&.\&. }   id3_field::stringlist"

.SS "\fBid3_latin1_t\fP** id3_field::strings"

.PP
Definition at line 221 of file id3tag\&.h\&.
.SS "\fBid3_ucs4_t\fP** id3_field::strings"

.PP
Definition at line 230 of file id3tag\&.h\&.
.SS "enum \fBid3_field_type\fP id3_field::type"

.PP
Definition at line 209 of file id3tag\&.h\&.
.SS "signed long id3_field::value"

.PP
Definition at line 212 of file id3tag\&.h\&.
.SS "char id3_field::value[9]"

.PP
Definition at line 234 of file id3tag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
