.TH "id3_frame" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
id3_frame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <id3tag\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBid\fP [5]"
.br
.ti -1c
.RI "char \fBconst\fP * \fBdescription\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBrefcount\fP"
.br
.ti -1c
.RI "\fBint\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgroup_id\fP"
.br
.ti -1c
.RI "\fBint\fP \fBencryption_method\fP"
.br
.ti -1c
.RI "\fBid3_byte_t\fP * \fBencoded\fP"
.br
.ti -1c
.RI "\fBid3_length_t\fP \fBencoded_length\fP"
.br
.ti -1c
.RI "\fBid3_length_t\fP \fBdecoded_length\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBnfields\fP"
.br
.ti -1c
.RI "union \fBid3_field\fP * \fBfields\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 148 of file id3tag\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBid3_length_t\fP id3_frame::decoded_length"

.PP
Definition at line 157 of file id3tag\&.h\&.
.SS "char \fBconst\fP* id3_frame::description"

.PP
Definition at line 150 of file id3tag\&.h\&.
.SS "\fBid3_byte_t\fP* id3_frame::encoded"

.PP
Definition at line 155 of file id3tag\&.h\&.
.SS "\fBid3_length_t\fP id3_frame::encoded_length"

.PP
Definition at line 156 of file id3tag\&.h\&.
.SS "\fBint\fP id3_frame::encryption_method"

.PP
Definition at line 154 of file id3tag\&.h\&.
.SS "union \fBid3_field\fP* id3_frame::fields"

.PP
Definition at line 159 of file id3tag\&.h\&.
.SS "\fBint\fP id3_frame::flags"

.PP
Definition at line 152 of file id3tag\&.h\&.
.SS "\fBint\fP id3_frame::group_id"

.PP
Definition at line 153 of file id3tag\&.h\&.
.SS "char id3_frame::id[5]"

.PP
Definition at line 149 of file id3tag\&.h\&.
.SS "unsigned \fBint\fP id3_frame::nfields"

.PP
Definition at line 158 of file id3tag\&.h\&.
.SS "unsigned \fBint\fP id3_frame::refcount"

.PP
Definition at line 151 of file id3tag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
