.TH "IDelayedPropertyStoreFactoryVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDelayedPropertyStoreFactoryVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propsys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIDelayedPropertyStoreFactory\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIDelayedPropertyStoreFactory\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIDelayedPropertyStoreFactory\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyStore)(\fBIDelayedPropertyStoreFactory\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyStoreForKeys)(\fBIDelayedPropertyStoreFactory\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDelayedPropertyStore)(\fBIDelayedPropertyStoreFactory\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown * \fBpUnkFactory\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP * \fBrgKeys\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBcKeys\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP \fBflags\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP \fBdwStoreId\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2916 of file propsys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IDelayedPropertyStoreFactoryVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IDelayedPropertyStoreFactoryVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyStore)"

.SS "IDelayedPropertyStoreFactoryVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyStoreForKeys)"

.SS "IDelayedPropertyStoreFactoryVtbl::HRESULT (STDMETHODCALLTYPE * GetDelayedPropertyStore)"

.SS "IDelayedPropertyStoreFactoryVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IDelayedPropertyStoreFactoryVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP IDelayedPropertyStoreFactoryVtbl::cKeys"

.PP
Definition at line 2941 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP IDelayedPropertyStoreFactoryVtbl::dwStoreId"

.PP
Definition at line 2949 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP IDelayedPropertyStoreFactoryVtbl::flags"

.PP
Definition at line 2934 of file propsys\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP IDelayedPropertyStoreFactoryVtbl::flags"

.PP
Definition at line 2941 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IDelayedPropertyStoreFactoryVtbl::ppv"

.PP
Definition at line 2934 of file propsys\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IDelayedPropertyStoreFactoryVtbl::ppv"

.PP
Definition at line 2941 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IDelayedPropertyStoreFactoryVtbl::ppv"

.PP
Definition at line 2949 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IDelayedPropertyStoreFactoryVtbl::ppvObject"

.PP
Definition at line 2922 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown* IDelayedPropertyStoreFactoryVtbl::pUnkFactory"

.PP
Definition at line 2934 of file propsys\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP* IDelayedPropertyStoreFactoryVtbl::rgKeys"

.PP
Definition at line 2941 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP IDelayedPropertyStoreFactoryVtbl::riid"

.PP
Definition at line 2922 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in_opt\fP IUnknown \fB__RPC__in\fP \fBREFIID\fP IDelayedPropertyStoreFactoryVtbl::riid"

.PP
Definition at line 2934 of file propsys\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBconst\fP \fBPROPERTYKEY\fP \fBUINT\fP \fBGETPROPERTYSTOREFLAGS\fP \fB__RPC__in\fP \fBREFIID\fP IDelayedPropertyStoreFactoryVtbl::riid"

.PP
Definition at line 2941 of file propsys\&.h\&.
.SS "\fBGETPROPERTYSTOREFLAGS\fP \fBDWORD\fP \fB__RPC__in\fP \fBREFIID\fP IDelayedPropertyStoreFactoryVtbl::riid"

.PP
Definition at line 2949 of file propsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
