.TH "IdentInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdentInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IdentInterface\&.h>\fP
.PP
Inherited by \fBEffectIdentInterface\fP, \fBImporterInterface\fP, and \fBModuleInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IdentInterface\fP ()"
.br
.ti -1c
.RI "virtual wxString \fBGetPath\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetSymbol\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetName\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetVendor\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetVersion\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetDescription\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file IdentInterface\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IdentInterface::~IdentInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 50 of file IdentInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual wxString IdentInterface::GetDescription ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBEffectEqualization\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBLadspaEffect\fP, \fBEffectReverb\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectCompressor\fP, \fBEffectAutoDuck\fP, \fBEffectClickRemoval\fP, \fBEffectAmplify\fP, \fBEffectChangeSpeed\fP, \fBEffectDtmf\fP, \fBEffectBassTreble\fP, \fBEffectToneGen\fP, \fBBuiltinEffectsModule\fP, \fBEffectNormalize\fP, \fBEffectNoise\fP, \fBEffectEcho\fP, \fBEffectFindClipping\fP, \fBNyquistEffectsModule\fP, \fBEffectRepeat\fP, \fBEffectNoiseReduction\fP, \fBEffectSilence\fP, \fBEffectLeveller\fP, \fBEffectInvert\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, \fBEffectPaulstretch\fP, and \fBEffectStereoToMono\fP\&.
.SS "virtual wxString IdentInterface::GetName ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBLadspaEffect\fP, \fBBuiltinEffectsModule\fP, and \fBNyquistEffectsModule\fP\&.
.SS "virtual wxString IdentInterface::GetPath ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBLadspaEffect\fP, \fBBuiltinEffectsModule\fP, and \fBNyquistEffectsModule\fP\&.
.SS "virtual wxString IdentInterface::GetSymbol ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBEffectEqualization\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBEffectPhaser\fP, \fBEffectWahwah\fP, \fBEffectReverb\fP, \fBLadspaEffect\fP, \fBEffectScienFilter\fP, \fBEffectTruncSilence\fP, \fBEffectCompressor\fP, \fBEffectAutoDuck\fP, \fBEffectClickRemoval\fP, \fBEffectAmplify\fP, \fBEffectChangeSpeed\fP, \fBEffectDtmf\fP, \fBEffectBassTreble\fP, \fBEffectToneGen\fP, \fBEffectNormalize\fP, \fBEffectNoise\fP, \fBEffectEcho\fP, \fBEffectFindClipping\fP, \fBEffectRepeat\fP, \fBBuiltinEffectsModule\fP, \fBEffectNoiseReduction\fP, \fBEffectSilence\fP, \fBEffectLeveller\fP, \fBEffectInvert\fP, \fBNyquistEffectsModule\fP, \fBEffectRepair\fP, \fBEffectReverse\fP, \fBEffectFade\fP, \fBEffectPaulstretch\fP, and \fBEffectStereoToMono\fP\&.
.SS "virtual wxString IdentInterface::GetVendor ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBLadspaEffect\fP, \fBBuiltinEffectsModule\fP, and \fBNyquistEffectsModule\fP\&.
.SS "virtual wxString IdentInterface::GetVersion ()\fC [pure virtual]\fP"

.PP
Implemented in \fBLadspaEffectsModule\fP, \fBLV2EffectsModule\fP, \fBEffect\fP, \fBNyquistEffect\fP, \fBLadspaEffect\fP, \fBBuiltinEffectsModule\fP, and \fBNyquistEffectsModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
