.TH "IIntervalVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IIntervalVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structuredquery\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIInterval\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIInterval\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIInterval\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetLimits)(\fBIInterval\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP * \fBpilkLower\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP * \fBppropvarLower\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP \fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP * \fBpilkUpper\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP \fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP * \fBppropvarUpper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1301 of file structuredquery\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IIntervalVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IIntervalVtbl::HRESULT (STDMETHODCALLTYPE * GetLimits)"

.SS "IIntervalVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IIntervalVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP* IIntervalVtbl::pilkLower"

.PP
Definition at line 1319 of file structuredquery\&.h\&.
.SS "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP \fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP* IIntervalVtbl::pilkUpper"

.PP
Definition at line 1319 of file structuredquery\&.h\&.
.SS "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP* IIntervalVtbl::ppropvarLower"

.PP
Definition at line 1319 of file structuredquery\&.h\&.
.SS "\fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP \fB__RPC__out\fP \fBINTERVAL_LIMIT_KIND\fP \fB__RPC__out\fP \fBPROPVARIANT\fP* IIntervalVtbl::ppropvarUpper"

.PP
Definition at line 1319 of file structuredquery\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IIntervalVtbl::ppvObject"

.PP
Definition at line 1307 of file structuredquery\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP IIntervalVtbl::riid"

.PP
Definition at line 1307 of file structuredquery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
