.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/ima_oki_adpcm.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/ima_oki_adpcm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'ima_oki_adpcm\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIN_SAMPLE\fP   \-0x8000"
.br
.ti -1c
.RI "#define \fBMAX_SAMPLE\fP   0x7fff"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBima_oki_adpcm_init\fP (\fBIMA_OKI_ADPCM\fP *state, \fBIMA_OKI_ADPCM_TYPE\fP type)"
.br
.ti -1c
.RI "\fBint\fP \fBadpcm_decode\fP (\fBIMA_OKI_ADPCM\fP *state, \fBint\fP code)"
.br
.ti -1c
.RI "\fBint\fP \fBadpcm_encode\fP (\fBIMA_OKI_ADPCM\fP *state, \fBint\fP sample)"
.br
.ti -1c
.RI "\fBvoid\fP \fBima_oki_adpcm_decode_block\fP (\fBIMA_OKI_ADPCM\fP *state)"
.br
.ti -1c
.RI "\fBvoid\fP \fBima_oki_adpcm_encode_block\fP (\fBIMA_OKI_ADPCM\fP *state)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_SAMPLE   0x7fff"

.PP
Definition at line 32 of file ima_oki_adpcm\&.c\&.
.SS "#define MIN_SAMPLE   \-0x8000"

.PP
Definition at line 31 of file ima_oki_adpcm\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP adpcm_decode (\fBIMA_OKI_ADPCM\fP * state, \fBint\fP code)"

.PP
Definition at line 73 of file ima_oki_adpcm\&.c\&.
.SS "\fBint\fP adpcm_encode (\fBIMA_OKI_ADPCM\fP * state, \fBint\fP sample)"

.PP
Definition at line 102 of file ima_oki_adpcm\&.c\&.
.SS "\fBvoid\fP ima_oki_adpcm_decode_block (\fBIMA_OKI_ADPCM\fP * state)"

.PP
Definition at line 121 of file ima_oki_adpcm\&.c\&.
.SS "\fBvoid\fP ima_oki_adpcm_encode_block (\fBIMA_OKI_ADPCM\fP * state)"

.PP
Definition at line 136 of file ima_oki_adpcm\&.c\&.
.SS "\fBvoid\fP ima_oki_adpcm_init (\fBIMA_OKI_ADPCM\fP * state, \fBIMA_OKI_ADPCM_TYPE\fP type)"

.PP
Definition at line 54 of file ima_oki_adpcm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
