.TH "IMA_OKI_ADPCM" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMA_OKI_ADPCM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ima_oki_adpcm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlast_output\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstep_index\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmax_step_index\fP"
.br
.ti -1c
.RI "\fBint\fP \fBconst\fP * \fBsteps\fP"
.br
.ti -1c
.RI "\fBint\fP \fBerrors\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcode_count\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpcm_count\fP"
.br
.ti -1c
.RI "unsigned char \fBcodes\fP [\fBIMA_OKI_ADPCM_CODE_LEN\fP]"
.br
.ti -1c
.RI "short \fBpcm\fP [\fBIMA_OKI_ADPCM_PCM_LEN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file ima_oki_adpcm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP IMA_OKI_ADPCM::code_count"

.PP
Definition at line 37 of file ima_oki_adpcm\&.h\&.
.SS "unsigned char IMA_OKI_ADPCM::codes[\fBIMA_OKI_ADPCM_CODE_LEN\fP]"

.PP
Definition at line 39 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::errors"

.PP
Definition at line 36 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::last_output"

.PP
Definition at line 30 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::mask"

.PP
Definition at line 29 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::max_step_index"

.PP
Definition at line 32 of file ima_oki_adpcm\&.h\&.
.SS "short IMA_OKI_ADPCM::pcm[\fBIMA_OKI_ADPCM_PCM_LEN\fP]"

.PP
Definition at line 40 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::pcm_count"

.PP
Definition at line 37 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP IMA_OKI_ADPCM::step_index"

.PP
Definition at line 31 of file ima_oki_adpcm\&.h\&.
.SS "\fBint\fP \fBconst\fP* IMA_OKI_ADPCM::steps"

.PP
Definition at line 33 of file ima_oki_adpcm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
