.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/imgutils.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/imgutils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'avutil\&.h'\fP
.br
\fC#include 'pixdesc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBav_image_fill_max_pixsteps\fP (\fBint\fP max_pixsteps[4], \fBint\fP max_pixstep_comps[4], \fBconst\fP \fBAVPixFmtDescriptor\fP *pixdesc)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_get_linesize\fP (enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width, \fBint\fP plane)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_fill_linesizes\fP (\fBint\fP linesizes[4], enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_fill_pointers\fP (\fBuint8_t\fP *\fBdata\fP[4], enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP height, \fBuint8_t\fP *ptr, \fBconst\fP \fBint\fP linesizes[4])"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_alloc\fP (\fBuint8_t\fP *pointers[4], \fBint\fP linesizes[4], \fBint\fP w, \fBint\fP h, enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP align)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_image_copy_plane\fP (\fBuint8_t\fP *dst, \fBint\fP dst_linesize, \fBconst\fP \fBuint8_t\fP *src, \fBint\fP src_linesize, \fBint\fP bytewidth, \fBint\fP height)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_image_copy\fP (\fBuint8_t\fP *dst_data[4], \fBint\fP dst_linesizes[4], \fBconst\fP \fBuint8_t\fP *src_data[4], \fBconst\fP \fBint\fP src_linesizes[4], enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width, \fBint\fP height)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_fill_arrays\fP (\fBuint8_t\fP *dst_data[4], \fBint\fP dst_linesize[4], \fBconst\fP \fBuint8_t\fP *src, enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width, \fBint\fP height, \fBint\fP align)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_get_buffer_size\fP (enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width, \fBint\fP height, \fBint\fP align)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_copy_to_buffer\fP (\fBuint8_t\fP *dst, \fBint\fP dst_size, \fBconst\fP \fBuint8_t\fP *\fBconst\fP src_data[4], \fBconst\fP \fBint\fP src_linesize[4], enum \fBAVPixelFormat\fP pix_fmt, \fBint\fP width, \fBint\fP height, \fBint\fP align)"
.br
.ti -1c
.RI "\fBint\fP \fBav_image_check_size\fP (unsigned \fBint\fP w, unsigned \fBint\fP h, \fBint\fP log_offset, \fBvoid\fP *log_ctx)"
.br
.ti -1c
.RI "\fBint\fP \fBavpriv_set_systematic_pal2\fP (\fBuint32_t\fP pal[256], enum \fBAVPixelFormat\fP pix_fmt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
misc image utilities 
.PP
Definition in file \fBimgutils\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
