.TH "IMMDeviceEnumeratorVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMMDeviceEnumeratorVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmdeviceapi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIMMDeviceEnumerator\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIMMDeviceEnumerator\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIMMDeviceEnumerator\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *EnumAudioEndpoints)(\fBIMMDeviceEnumerator\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDefaultAudioEndpoint)(\fBIMMDeviceEnumerator\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDevice)(\fBIMMDeviceEnumerator\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *RegisterEndpointNotificationCallback)(\fBIMMDeviceEnumerator\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *UnregisterEndpointNotificationCallback)(\fBIMMDeviceEnumerator\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBEDataFlow\fP \fBdataFlow\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBDWORD\fP \fBdwStateMask\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBDWORD\fP \fB__out\fP \fBIMMDeviceCollection\fP ** \fBppDevices\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBERole\fP \fBrole\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBERole\fP \fB__out\fP \fBIMMDevice\fP ** \fBppEndpoint\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBLPCWSTR\fP \fBpwstrId\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBLPCWSTR\fP \fB__out\fP \fBIMMDevice\fP ** \fBppDevice\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBIMMNotificationClient\fP * \fBpClient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 690 of file mmdeviceapi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * EnumAudioEndpoints)"

.SS "IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * GetDefaultAudioEndpoint)"

.SS "IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * GetDevice)"

.SS "IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * RegisterEndpointNotificationCallback)"

.SS "IMMDeviceEnumeratorVtbl::HRESULT (STDMETHODCALLTYPE * UnregisterEndpointNotificationCallback)"

.SS "IMMDeviceEnumeratorVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IMMDeviceEnumeratorVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBEDataFlow\fP IMMDeviceEnumeratorVtbl::dataFlow"

.PP
Definition at line 709 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBDWORD\fP IMMDeviceEnumeratorVtbl::dwStateMask"

.PP
Definition at line 709 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBIMMNotificationClient\fP * IMMDeviceEnumeratorVtbl::pClient"

.PP
Definition at line 734 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBLPCWSTR\fP \fB__out\fP \fBIMMDevice\fP** IMMDeviceEnumeratorVtbl::ppDevice"

.PP
Definition at line 727 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBDWORD\fP \fB__out\fP \fBIMMDeviceCollection\fP** IMMDeviceEnumeratorVtbl::ppDevices"

.PP
Definition at line 709 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBERole\fP \fB__out\fP \fBIMMDevice\fP** IMMDeviceEnumeratorVtbl::ppEndpoint"

.PP
Definition at line 718 of file mmdeviceapi\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IMMDeviceEnumeratorVtbl::ppvObject"

.PP
Definition at line 696 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBLPCWSTR\fP IMMDeviceEnumeratorVtbl::pwstrId"

.PP
Definition at line 727 of file mmdeviceapi\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IMMDeviceEnumeratorVtbl::riid"

.PP
Definition at line 696 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBEDataFlow\fP \fB__in\fP \fBERole\fP IMMDeviceEnumeratorVtbl::role"

.PP
Definition at line 718 of file mmdeviceapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
