.TH "IMMDeviceActivatorVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMMDeviceActivatorVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mmdeviceapi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIMMDeviceActivator\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIMMDeviceActivator\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIMMDeviceActivator\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Activate)(\fBIMMDeviceActivator\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fBiid\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP * \fBpDevice\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP \fB__in_opt\fP \fBPROPVARIANT\fP * \fBpActivationParams\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP \fB__in_opt\fP \fBPROPVARIANT\fP \fB__out\fP \fBvoid\fP ** \fBppInterface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 819 of file mmdeviceapi\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IMMDeviceActivatorVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IMMDeviceActivatorVtbl::HRESULT (STDMETHODCALLTYPE * Activate)"

.SS "IMMDeviceActivatorVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IMMDeviceActivatorVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBREFIID\fP IMMDeviceActivatorVtbl::iid"

.PP
Definition at line 838 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP \fB__in_opt\fP \fBPROPVARIANT\fP* IMMDeviceActivatorVtbl::pActivationParams"

.PP
Definition at line 838 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP* IMMDeviceActivatorVtbl::pDevice"

.PP
Definition at line 838 of file mmdeviceapi\&.h\&.
.SS "\fB__in\fP \fBREFIID\fP \fB__in\fP \fBIMMDevice\fP \fB__in_opt\fP \fBPROPVARIANT\fP \fB__out\fP \fBvoid\fP** IMMDeviceActivatorVtbl::ppInterface"

.PP
Definition at line 838 of file mmdeviceapi\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IMMDeviceActivatorVtbl::ppvObject"

.PP
Definition at line 825 of file mmdeviceapi\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IMMDeviceActivatorVtbl::riid"

.PP
Definition at line 825 of file mmdeviceapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
