.TH "ImportExportPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportExportPrefs \- A \fBPrefsPanel\fP used to select import and export options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImportExportPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImportExportPrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fB~ImportExportPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP used to select import and export options\&. 
.PP
Definition at line 24 of file ImportExportPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImportExportPrefs::ImportExportPrefs (wxWindow * parent)"

.PP
Definition at line 27 of file ImportExportPrefs\&.cpp\&.
.SS "ImportExportPrefs::~ImportExportPrefs ()"

.PP
Definition at line 33 of file ImportExportPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP ImportExportPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 105 of file ImportExportPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
