.TH "ImportStreamDialog" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportStreamDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Import\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImportStreamDialog\fP (\fBImportFileHandle\fP *_mFile, wxWindow *parent, wxWindowID id, \fBconst\fP wxString &title, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)"
.br
.ti -1c
.RI "virtual \fB~ImportStreamDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file Import\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImportStreamDialog::ImportStreamDialog (\fBImportFileHandle\fP * _mFile, wxWindow * parent, wxWindowID id, \fBconst\fP wxString & title, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP, long style = \fCwxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER\fP)"

.PP
Definition at line 750 of file Import\&.cpp\&.
.SS "ImportStreamDialog::~ImportStreamDialog ()\fC [virtual]\fP"

.PP
Definition at line 783 of file Import\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
