.TH "ImporterInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImporterInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImporterInterface\&.h>\fP
.PP
Inherits \fBIdentInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ImporterInterface\fP ()"
.br
.ti -1c
.RI "virtual wxString \fBGetPluginStringID\fP ()=0"
.br
.ti -1c
.RI "virtual wxString \fBGetPluginFormatDescription\fP ()=0"
.br
.ti -1c
.RI "virtual wxArrayString \fBGetSupportedExtensions\fP ()=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSupportsExtension\fP (\fBconst\fP wxString &extension)=0"
.br
.ti -1c
.RI "virtual \fBImporterClientInterface\fP * \fBCreateClient\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file ImporterInterface\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ImporterInterface::~ImporterInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 60 of file ImporterInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBImporterClientInterface\fP* ImporterInterface::CreateClient ()\fC [pure virtual]\fP"

.SS "virtual wxString ImporterInterface::GetPluginFormatDescription ()\fC [pure virtual]\fP"

.SS "virtual wxString ImporterInterface::GetPluginStringID ()\fC [pure virtual]\fP"

.SS "virtual wxArrayString ImporterInterface::GetSupportedExtensions ()\fC [pure virtual]\fP"

.SS "virtual \fBbool\fP ImporterInterface::SupportsExtension (\fBconst\fP wxString & extension)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
