.TH "INamedPropertyStoreVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INamedPropertyStoreVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propsys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBINamedPropertyStore\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBINamedPropertyStore\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBINamedPropertyStore\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetNamedValue)(\fBINamedPropertyStore\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetNamedValue)(\fBINamedPropertyStore\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetNameCount)(\fBINamedPropertyStore\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetNameAt)(\fBINamedPropertyStore\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszName\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__out\fP \fBPROPVARIANT\fP * \fBppropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBDWORD\fP * \fBpdwCount\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBiProp\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fB__RPC__deref_out_opt\fP BSTR * \fBpbstrName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 577 of file propsys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE INamedPropertyStoreVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "INamedPropertyStoreVtbl::HRESULT (STDMETHODCALLTYPE * GetNamedValue)"

.SS "INamedPropertyStoreVtbl::HRESULT (STDMETHODCALLTYPE * SetNamedValue)"

.SS "INamedPropertyStoreVtbl::HRESULT (STDMETHODCALLTYPE * GetNameCount)"

.SS "INamedPropertyStoreVtbl::HRESULT (STDMETHODCALLTYPE * GetNameAt)"

.SS "INamedPropertyStoreVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "INamedPropertyStoreVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fBDWORD\fP INamedPropertyStoreVtbl::iProp"

.PP
Definition at line 609 of file propsys\&.h\&.
.SS "\fBDWORD\fP \fB__RPC__deref_out_opt\fP BSTR* INamedPropertyStoreVtbl::pbstrName"

.PP
Definition at line 609 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBDWORD\fP* INamedPropertyStoreVtbl::pdwCount"

.PP
Definition at line 605 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__out\fP \fBPROPVARIANT\fP* INamedPropertyStoreVtbl::ppropvar"

.PP
Definition at line 595 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** INamedPropertyStoreVtbl::ppvObject"

.PP
Definition at line 583 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP INamedPropertyStoreVtbl::propvar"

.PP
Definition at line 600 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP INamedPropertyStoreVtbl::pszName"

.PP
Definition at line 595 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP INamedPropertyStoreVtbl::riid"

.PP
Definition at line 583 of file propsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
