.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrbowedfreq.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrbowedfreq.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'instrbowedfreq\&.h'\fP
.br
\fC#include 'instr\&.h'\fP
.br
\fC#include 'upsample\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbowed_freq_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBbowed_freq_susp_struct\fP \fBbowed_freq_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBbowed_freq_susp_struct\fP * \fBbowed_freq_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBbowed_freq_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbowed_freq_ns_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbowed_freq_toss_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbowed_freq_mark\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbowed_freq_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_bowed_freq\fP (double freq, \fBsound_type\fP bowpress_env, \fBsound_type\fP freq_env, \fBrate_type\fP sr)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_bowed_freq\fP (double freq, \fBsound_type\fP bowpress_env, \fBsound_type\fP freq_env, \fBrate_type\fP sr)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBbowed_freq_susp_struct\fP  \fBbowed_freq_susp_node\fP"

.SS "typedef struct \fBbowed_freq_susp_struct\fP * \fBbowed_freq_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP bowed_freq_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 148 of file instrbowedfreq\&.c\&.
.SS "\fBvoid\fP bowed_freq_mark (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 140 of file instrbowedfreq\&.c\&.
.SS "\fBvoid\fP bowed_freq_ns_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 35 of file instrbowedfreq\&.c\&.
.SS "\fBvoid\fP bowed_freq_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 158 of file instrbowedfreq\&.c\&.
.SS "\fBvoid\fP bowed_freq_toss_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 111 of file instrbowedfreq\&.c\&.
.SS "\fBsound_type\fP snd_bowed_freq (double freq, \fBsound_type\fP bowpress_env, \fBsound_type\fP freq_env, \fBrate_type\fP sr)"

.PP
Definition at line 225 of file instrbowedfreq\&.c\&.
.SS "\fBsound_type\fP snd_make_bowed_freq (double freq, \fBsound_type\fP bowpress_env, \fBsound_type\fP freq_env, \fBrate_type\fP sr)"

.PP
Definition at line 171 of file instrbowedfreq\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
