.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrsaxall.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrsaxall.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSAX_CONTROL_CHANGE_CONST\fP   128"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_sax_all\fP (double freq, \fBsound_type\fP breath_env, \fBsound_type\fP freq_env, double vibrato_freq, double vibrato_gain, \fBsound_type\fP reed_stiffness, \fBsound_type\fP noise_env, \fBsound_type\fP blow_pos, \fBsound_type\fP reed_table_offset, \fBrate_type\fP sr)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_sax_all\fP (double freq, \fBsound_type\fP breath_env, \fBsound_type\fP freq_env, double vibrato_freq, double vibrato_gain, \fBsound_type\fP reed_stiffness, \fBsound_type\fP noise_env, \fBsound_type\fP blow_pos, \fBsound_type\fP reed_table_offset, \fBrate_type\fP sr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SAX_CONTROL_CHANGE_CONST   128"

.PP
Definition at line 4 of file instrsaxall\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_make_sax_all (double freq, \fBsound_type\fP breath_env, \fBsound_type\fP freq_env, double vibrato_freq, double vibrato_gain, \fBsound_type\fP reed_stiffness, \fBsound_type\fP noise_env, \fBsound_type\fP blow_pos, \fBsound_type\fP reed_table_offset, \fBrate_type\fP sr)"

.PP
Definition at line 290 of file instrsaxall\&.c\&.
.SS "\fBsound_type\fP snd_sax_all (double freq, \fBsound_type\fP breath_env, \fBsound_type\fP freq_env, double vibrato_freq, double vibrato_gain, \fBsound_type\fP reed_stiffness, \fBsound_type\fP noise_env, \fBsound_type\fP blow_pos, \fBsound_type\fP reed_table_offset, \fBrate_type\fP sr)"

.PP
Definition at line 377 of file instrsaxall\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
