.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrbanded.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrbanded.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBANDEDWG_CONTROL_CHANGE_CONST\fP   128"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_bandedwg\fP (double freq, \fBsound_type\fP bowpress_env, \fBint\fP preset, \fBrate_type\fP sr)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_bandedwg\fP (double freq, \fBsound_type\fP bowpress_env, \fBint\fP preset, \fBrate_type\fP sr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BANDEDWG_CONTROL_CHANGE_CONST   128"

.PP
Definition at line 4 of file instrbanded\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_bandedwg (double freq, \fBsound_type\fP bowpress_env, \fBint\fP preset, \fBrate_type\fP sr)"

.PP
Definition at line 186 of file instrbanded\&.c\&.
.SS "\fBsound_type\fP snd_make_bandedwg (double freq, \fBsound_type\fP bowpress_env, \fBint\fP preset, \fBrate_type\fP sr)"

.PP
Definition at line 140 of file instrbanded\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
