.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrmandolin.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/instrmandolin.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAND_CONTROL_CHANGE_CONST\fP   128"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_mandolin\fP (\fBtime_type\fP t0, double freq, \fBtime_type\fP \fBd\fP, double body_size, double detune, \fBrate_type\fP sr)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_mandolin\fP (\fBtime_type\fP t0, double freq, \fBtime_type\fP \fBd\fP, double body_size, double detune, \fBrate_type\fP sr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAND_CONTROL_CHANGE_CONST   128"

.PP
Definition at line 4 of file instrmandolin\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_make_mandolin (\fBtime_type\fP t0, double freq, \fBtime_type\fP d, double body_size, double detune, \fBrate_type\fP sr)"

.PP
Definition at line 90 of file instrmandolin\&.c\&.
.SS "\fBsound_type\fP snd_mandolin (\fBtime_type\fP t0, double freq, \fBtime_type\fP d, double body_size, double detune, \fBrate_type\fP sr)"

.PP
Definition at line 117 of file instrmandolin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
