.TH "INST_LOOP" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INST_LOOP \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBplayMode\fP"
.br
.ti -1c
.RI "unsigned short \fBbeginLoop\fP"
.br
.ti -1c
.RI "unsigned short \fBendLoop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file aiff\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short INST_LOOP::beginLoop"

.PP
Definition at line 142 of file aiff\&.c\&.
.SS "unsigned short INST_LOOP::endLoop"

.PP
Definition at line 143 of file aiff\&.c\&.
.SS "short INST_LOOP::playMode"

.PP
Definition at line 141 of file aiff\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
