.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/interleave.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/interleave.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfendian\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBINTERLEAVE_DATA\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTERLEAVE_CHANNELS\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBinterleave_init\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTERLEAVE_CHANNELS   6"

.PP
Definition at line 26 of file interleave\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP interleave_init (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 53 of file interleave\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
