.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/msinttypes/inttypes.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/msinttypes/inttypes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdint\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBimaxdiv_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRId8\fP   'd'"
.br
.ti -1c
.RI "#define \fBPRIi8\fP   'i'"
.br
.ti -1c
.RI "#define \fBPRIdLEAST8\fP   'd'"
.br
.ti -1c
.RI "#define \fBPRIiLEAST8\fP   'i'"
.br
.ti -1c
.RI "#define \fBPRIdFAST8\fP   'd'"
.br
.ti -1c
.RI "#define \fBPRIiFAST8\fP   'i'"
.br
.ti -1c
.RI "#define \fBPRId16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBPRIi16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBPRIdLEAST16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBPRIiLEAST16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBPRIdFAST16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBPRIiFAST16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBPRId32\fP   'I32d'"
.br
.ti -1c
.RI "#define \fBPRIi32\fP   'I32i'"
.br
.ti -1c
.RI "#define \fBPRIdLEAST32\fP   'I32d'"
.br
.ti -1c
.RI "#define \fBPRIiLEAST32\fP   'I32i'"
.br
.ti -1c
.RI "#define \fBPRIdFAST32\fP   'I32d'"
.br
.ti -1c
.RI "#define \fBPRIiFAST32\fP   'I32i'"
.br
.ti -1c
.RI "#define \fBPRId64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBPRIi64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBPRIdLEAST64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBPRIiLEAST64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBPRIdFAST64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBPRIiFAST64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBPRIdMAX\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBPRIiMAX\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBPRIdPTR\fP   'Id'"
.br
.ti -1c
.RI "#define \fBPRIiPTR\fP   'Ii'"
.br
.ti -1c
.RI "#define \fBPRIo8\fP   'o'"
.br
.ti -1c
.RI "#define \fBPRIu8\fP   'u'"
.br
.ti -1c
.RI "#define \fBPRIx8\fP   'x'"
.br
.ti -1c
.RI "#define \fBPRIX8\fP   'X'"
.br
.ti -1c
.RI "#define \fBPRIoLEAST8\fP   'o'"
.br
.ti -1c
.RI "#define \fBPRIuLEAST8\fP   'u'"
.br
.ti -1c
.RI "#define \fBPRIxLEAST8\fP   'x'"
.br
.ti -1c
.RI "#define \fBPRIXLEAST8\fP   'X'"
.br
.ti -1c
.RI "#define \fBPRIoFAST8\fP   'o'"
.br
.ti -1c
.RI "#define \fBPRIuFAST8\fP   'u'"
.br
.ti -1c
.RI "#define \fBPRIxFAST8\fP   'x'"
.br
.ti -1c
.RI "#define \fBPRIXFAST8\fP   'X'"
.br
.ti -1c
.RI "#define \fBPRIo16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBPRIu16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBPRIx16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBPRIX16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBPRIoLEAST16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBPRIuLEAST16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBPRIxLEAST16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBPRIXLEAST16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBPRIoFAST16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBPRIuFAST16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBPRIxFAST16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBPRIXFAST16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBPRIo32\fP   'I32o'"
.br
.ti -1c
.RI "#define \fBPRIu32\fP   'I32u'"
.br
.ti -1c
.RI "#define \fBPRIx32\fP   'I32x'"
.br
.ti -1c
.RI "#define \fBPRIX32\fP   'I32X'"
.br
.ti -1c
.RI "#define \fBPRIoLEAST32\fP   'I32o'"
.br
.ti -1c
.RI "#define \fBPRIuLEAST32\fP   'I32u'"
.br
.ti -1c
.RI "#define \fBPRIxLEAST32\fP   'I32x'"
.br
.ti -1c
.RI "#define \fBPRIXLEAST32\fP   'I32X'"
.br
.ti -1c
.RI "#define \fBPRIoFAST32\fP   'I32o'"
.br
.ti -1c
.RI "#define \fBPRIuFAST32\fP   'I32u'"
.br
.ti -1c
.RI "#define \fBPRIxFAST32\fP   'I32x'"
.br
.ti -1c
.RI "#define \fBPRIXFAST32\fP   'I32X'"
.br
.ti -1c
.RI "#define \fBPRIo64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBPRIu64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBPRIx64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBPRIX64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBPRIoLEAST64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBPRIuLEAST64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBPRIxLEAST64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBPRIXLEAST64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBPRIoFAST64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBPRIuFAST64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBPRIxFAST64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBPRIXFAST64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBPRIoMAX\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBPRIuMAX\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBPRIxMAX\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBPRIXMAX\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBPRIoPTR\fP   'Io'"
.br
.ti -1c
.RI "#define \fBPRIuPTR\fP   'Iu'"
.br
.ti -1c
.RI "#define \fBPRIxPTR\fP   'Ix'"
.br
.ti -1c
.RI "#define \fBPRIXPTR\fP   'IX'"
.br
.ti -1c
.RI "#define \fBSCNd8\fP   'd'"
.br
.ti -1c
.RI "#define \fBSCNi8\fP   'i'"
.br
.ti -1c
.RI "#define \fBSCNdLEAST8\fP   'd'"
.br
.ti -1c
.RI "#define \fBSCNiLEAST8\fP   'i'"
.br
.ti -1c
.RI "#define \fBSCNdFAST8\fP   'd'"
.br
.ti -1c
.RI "#define \fBSCNiFAST8\fP   'i'"
.br
.ti -1c
.RI "#define \fBSCNd16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBSCNi16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBSCNdLEAST16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBSCNiLEAST16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBSCNdFAST16\fP   'hd'"
.br
.ti -1c
.RI "#define \fBSCNiFAST16\fP   'hi'"
.br
.ti -1c
.RI "#define \fBSCNd32\fP   'ld'"
.br
.ti -1c
.RI "#define \fBSCNi32\fP   'li'"
.br
.ti -1c
.RI "#define \fBSCNdLEAST32\fP   'ld'"
.br
.ti -1c
.RI "#define \fBSCNiLEAST32\fP   'li'"
.br
.ti -1c
.RI "#define \fBSCNdFAST32\fP   'ld'"
.br
.ti -1c
.RI "#define \fBSCNiFAST32\fP   'li'"
.br
.ti -1c
.RI "#define \fBSCNd64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBSCNi64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBSCNdLEAST64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBSCNiLEAST64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBSCNdFAST64\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBSCNiFAST64\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBSCNdMAX\fP   'I64d'"
.br
.ti -1c
.RI "#define \fBSCNiMAX\fP   'I64i'"
.br
.ti -1c
.RI "#define \fBSCNdPTR\fP   'ld'"
.br
.ti -1c
.RI "#define \fBSCNiPTR\fP   'li'"
.br
.ti -1c
.RI "#define \fBSCNo8\fP   'o'"
.br
.ti -1c
.RI "#define \fBSCNu8\fP   'u'"
.br
.ti -1c
.RI "#define \fBSCNx8\fP   'x'"
.br
.ti -1c
.RI "#define \fBSCNX8\fP   'X'"
.br
.ti -1c
.RI "#define \fBSCNoLEAST8\fP   'o'"
.br
.ti -1c
.RI "#define \fBSCNuLEAST8\fP   'u'"
.br
.ti -1c
.RI "#define \fBSCNxLEAST8\fP   'x'"
.br
.ti -1c
.RI "#define \fBSCNXLEAST8\fP   'X'"
.br
.ti -1c
.RI "#define \fBSCNoFAST8\fP   'o'"
.br
.ti -1c
.RI "#define \fBSCNuFAST8\fP   'u'"
.br
.ti -1c
.RI "#define \fBSCNxFAST8\fP   'x'"
.br
.ti -1c
.RI "#define \fBSCNXFAST8\fP   'X'"
.br
.ti -1c
.RI "#define \fBSCNo16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBSCNu16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBSCNx16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBSCNX16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBSCNoLEAST16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBSCNuLEAST16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBSCNxLEAST16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBSCNXLEAST16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBSCNoFAST16\fP   'ho'"
.br
.ti -1c
.RI "#define \fBSCNuFAST16\fP   'hu'"
.br
.ti -1c
.RI "#define \fBSCNxFAST16\fP   'hx'"
.br
.ti -1c
.RI "#define \fBSCNXFAST16\fP   'hX'"
.br
.ti -1c
.RI "#define \fBSCNo32\fP   'lo'"
.br
.ti -1c
.RI "#define \fBSCNu32\fP   'lu'"
.br
.ti -1c
.RI "#define \fBSCNx32\fP   'lx'"
.br
.ti -1c
.RI "#define \fBSCNX32\fP   'lX'"
.br
.ti -1c
.RI "#define \fBSCNoLEAST32\fP   'lo'"
.br
.ti -1c
.RI "#define \fBSCNuLEAST32\fP   'lu'"
.br
.ti -1c
.RI "#define \fBSCNxLEAST32\fP   'lx'"
.br
.ti -1c
.RI "#define \fBSCNXLEAST32\fP   'lX'"
.br
.ti -1c
.RI "#define \fBSCNoFAST32\fP   'lo'"
.br
.ti -1c
.RI "#define \fBSCNuFAST32\fP   'lu'"
.br
.ti -1c
.RI "#define \fBSCNxFAST32\fP   'lx'"
.br
.ti -1c
.RI "#define \fBSCNXFAST32\fP   'lX'"
.br
.ti -1c
.RI "#define \fBSCNo64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBSCNu64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBSCNx64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBSCNX64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBSCNoLEAST64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBSCNuLEAST64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBSCNxLEAST64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBSCNXLEAST64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBSCNoFAST64\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBSCNuFAST64\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBSCNxFAST64\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBSCNXFAST64\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBSCNoMAX\fP   'I64o'"
.br
.ti -1c
.RI "#define \fBSCNuMAX\fP   'I64u'"
.br
.ti -1c
.RI "#define \fBSCNxMAX\fP   'I64x'"
.br
.ti -1c
.RI "#define \fBSCNXMAX\fP   'I64X'"
.br
.ti -1c
.RI "#define \fBSCNoPTR\fP   'lo'"
.br
.ti -1c
.RI "#define \fBSCNuPTR\fP   'lu'"
.br
.ti -1c
.RI "#define \fBSCNxPTR\fP   'lx'"
.br
.ti -1c
.RI "#define \fBSCNXPTR\fP   'lX'"
.br
.ti -1c
.RI "#define \fBimaxabs\fP   _abs64"
.br
.ti -1c
.RI "#define \fBstrtoimax\fP   _strtoi64"
.br
.ti -1c
.RI "#define \fBstrtoumax\fP   _strtoui64"
.br
.ti -1c
.RI "#define \fBwcstoimax\fP   _wcstoi64"
.br
.ti -1c
.RI "#define \fBwcstoumax\fP   _wcstoui64"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "_inline \fBimaxdiv_t\fP __cdecl \fBimaxdiv\fP (\fBintmax_t\fP numer, \fBintmax_t\fP denom)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define imaxabs   _abs64"

.PP
Definition at line 270 of file inttypes\&.h\&.
.SS "#define PRId16   'hd'"

.PP
Definition at line 65 of file inttypes\&.h\&.
.SS "#define PRId32   'I32d'"

.PP
Definition at line 72 of file inttypes\&.h\&.
.SS "#define PRId64   'I64d'"

.PP
Definition at line 79 of file inttypes\&.h\&.
.SS "#define PRId8   'd'"

.PP
Definition at line 58 of file inttypes\&.h\&.
.SS "#define PRIdFAST16   'hd'"

.PP
Definition at line 69 of file inttypes\&.h\&.
.SS "#define PRIdFAST32   'I32d'"

.PP
Definition at line 76 of file inttypes\&.h\&.
.SS "#define PRIdFAST64   'I64d'"

.PP
Definition at line 83 of file inttypes\&.h\&.
.SS "#define PRIdFAST8   'd'"

.PP
Definition at line 62 of file inttypes\&.h\&.
.SS "#define PRIdLEAST16   'hd'"

.PP
Definition at line 67 of file inttypes\&.h\&.
.SS "#define PRIdLEAST32   'I32d'"

.PP
Definition at line 74 of file inttypes\&.h\&.
.SS "#define PRIdLEAST64   'I64d'"

.PP
Definition at line 81 of file inttypes\&.h\&.
.SS "#define PRIdLEAST8   'd'"

.PP
Definition at line 60 of file inttypes\&.h\&.
.SS "#define PRIdMAX   'I64d'"

.PP
Definition at line 86 of file inttypes\&.h\&.
.SS "#define PRIdPTR   'Id'"

.PP
Definition at line 89 of file inttypes\&.h\&.
.SS "#define PRIi16   'hi'"

.PP
Definition at line 66 of file inttypes\&.h\&.
.SS "#define PRIi32   'I32i'"

.PP
Definition at line 73 of file inttypes\&.h\&.
.SS "#define PRIi64   'I64i'"

.PP
Definition at line 80 of file inttypes\&.h\&.
.SS "#define PRIi8   'i'"

.PP
Definition at line 59 of file inttypes\&.h\&.
.SS "#define PRIiFAST16   'hi'"

.PP
Definition at line 70 of file inttypes\&.h\&.
.SS "#define PRIiFAST32   'I32i'"

.PP
Definition at line 77 of file inttypes\&.h\&.
.SS "#define PRIiFAST64   'I64i'"

.PP
Definition at line 84 of file inttypes\&.h\&.
.SS "#define PRIiFAST8   'i'"

.PP
Definition at line 63 of file inttypes\&.h\&.
.SS "#define PRIiLEAST16   'hi'"

.PP
Definition at line 68 of file inttypes\&.h\&.
.SS "#define PRIiLEAST32   'I32i'"

.PP
Definition at line 75 of file inttypes\&.h\&.
.SS "#define PRIiLEAST64   'I64i'"

.PP
Definition at line 82 of file inttypes\&.h\&.
.SS "#define PRIiLEAST8   'i'"

.PP
Definition at line 61 of file inttypes\&.h\&.
.SS "#define PRIiMAX   'I64i'"

.PP
Definition at line 87 of file inttypes\&.h\&.
.SS "#define PRIiPTR   'Ii'"

.PP
Definition at line 90 of file inttypes\&.h\&.
.SS "#define PRIo16   'ho'"

.PP
Definition at line 106 of file inttypes\&.h\&.
.SS "#define PRIo32   'I32o'"

.PP
Definition at line 119 of file inttypes\&.h\&.
.SS "#define PRIo64   'I64o'"

.PP
Definition at line 132 of file inttypes\&.h\&.
.SS "#define PRIo8   'o'"

.PP
Definition at line 93 of file inttypes\&.h\&.
.SS "#define PRIoFAST16   'ho'"

.PP
Definition at line 114 of file inttypes\&.h\&.
.SS "#define PRIoFAST32   'I32o'"

.PP
Definition at line 127 of file inttypes\&.h\&.
.SS "#define PRIoFAST64   'I64o'"

.PP
Definition at line 140 of file inttypes\&.h\&.
.SS "#define PRIoFAST8   'o'"

.PP
Definition at line 101 of file inttypes\&.h\&.
.SS "#define PRIoLEAST16   'ho'"

.PP
Definition at line 110 of file inttypes\&.h\&.
.SS "#define PRIoLEAST32   'I32o'"

.PP
Definition at line 123 of file inttypes\&.h\&.
.SS "#define PRIoLEAST64   'I64o'"

.PP
Definition at line 136 of file inttypes\&.h\&.
.SS "#define PRIoLEAST8   'o'"

.PP
Definition at line 97 of file inttypes\&.h\&.
.SS "#define PRIoMAX   'I64o'"

.PP
Definition at line 145 of file inttypes\&.h\&.
.SS "#define PRIoPTR   'Io'"

.PP
Definition at line 150 of file inttypes\&.h\&.
.SS "#define PRIu16   'hu'"

.PP
Definition at line 107 of file inttypes\&.h\&.
.SS "#define PRIu32   'I32u'"

.PP
Definition at line 120 of file inttypes\&.h\&.
.SS "#define PRIu64   'I64u'"

.PP
Definition at line 133 of file inttypes\&.h\&.
.SS "#define PRIu8   'u'"

.PP
Definition at line 94 of file inttypes\&.h\&.
.SS "#define PRIuFAST16   'hu'"

.PP
Definition at line 115 of file inttypes\&.h\&.
.SS "#define PRIuFAST32   'I32u'"

.PP
Definition at line 128 of file inttypes\&.h\&.
.SS "#define PRIuFAST64   'I64u'"

.PP
Definition at line 141 of file inttypes\&.h\&.
.SS "#define PRIuFAST8   'u'"

.PP
Definition at line 102 of file inttypes\&.h\&.
.SS "#define PRIuLEAST16   'hu'"

.PP
Definition at line 111 of file inttypes\&.h\&.
.SS "#define PRIuLEAST32   'I32u'"

.PP
Definition at line 124 of file inttypes\&.h\&.
.SS "#define PRIuLEAST64   'I64u'"

.PP
Definition at line 137 of file inttypes\&.h\&.
.SS "#define PRIuLEAST8   'u'"

.PP
Definition at line 98 of file inttypes\&.h\&.
.SS "#define PRIuMAX   'I64u'"

.PP
Definition at line 146 of file inttypes\&.h\&.
.SS "#define PRIuPTR   'Iu'"

.PP
Definition at line 151 of file inttypes\&.h\&.
.SS "#define PRIx16   'hx'"

.PP
Definition at line 108 of file inttypes\&.h\&.
.SS "#define PRIX16   'hX'"

.PP
Definition at line 109 of file inttypes\&.h\&.
.SS "#define PRIx32   'I32x'"

.PP
Definition at line 121 of file inttypes\&.h\&.
.SS "#define PRIX32   'I32X'"

.PP
Definition at line 122 of file inttypes\&.h\&.
.SS "#define PRIx64   'I64x'"

.PP
Definition at line 134 of file inttypes\&.h\&.
.SS "#define PRIX64   'I64X'"

.PP
Definition at line 135 of file inttypes\&.h\&.
.SS "#define PRIx8   'x'"

.PP
Definition at line 95 of file inttypes\&.h\&.
.SS "#define PRIX8   'X'"

.PP
Definition at line 96 of file inttypes\&.h\&.
.SS "#define PRIxFAST16   'hx'"

.PP
Definition at line 116 of file inttypes\&.h\&.
.SS "#define PRIXFAST16   'hX'"

.PP
Definition at line 117 of file inttypes\&.h\&.
.SS "#define PRIxFAST32   'I32x'"

.PP
Definition at line 129 of file inttypes\&.h\&.
.SS "#define PRIXFAST32   'I32X'"

.PP
Definition at line 130 of file inttypes\&.h\&.
.SS "#define PRIxFAST64   'I64x'"

.PP
Definition at line 142 of file inttypes\&.h\&.
.SS "#define PRIXFAST64   'I64X'"

.PP
Definition at line 143 of file inttypes\&.h\&.
.SS "#define PRIxFAST8   'x'"

.PP
Definition at line 103 of file inttypes\&.h\&.
.SS "#define PRIXFAST8   'X'"

.PP
Definition at line 104 of file inttypes\&.h\&.
.SS "#define PRIxLEAST16   'hx'"

.PP
Definition at line 112 of file inttypes\&.h\&.
.SS "#define PRIXLEAST16   'hX'"

.PP
Definition at line 113 of file inttypes\&.h\&.
.SS "#define PRIxLEAST32   'I32x'"

.PP
Definition at line 125 of file inttypes\&.h\&.
.SS "#define PRIXLEAST32   'I32X'"

.PP
Definition at line 126 of file inttypes\&.h\&.
.SS "#define PRIxLEAST64   'I64x'"

.PP
Definition at line 138 of file inttypes\&.h\&.
.SS "#define PRIXLEAST64   'I64X'"

.PP
Definition at line 139 of file inttypes\&.h\&.
.SS "#define PRIxLEAST8   'x'"

.PP
Definition at line 99 of file inttypes\&.h\&.
.SS "#define PRIXLEAST8   'X'"

.PP
Definition at line 100 of file inttypes\&.h\&.
.SS "#define PRIxMAX   'I64x'"

.PP
Definition at line 147 of file inttypes\&.h\&.
.SS "#define PRIXMAX   'I64X'"

.PP
Definition at line 148 of file inttypes\&.h\&.
.SS "#define PRIxPTR   'Ix'"

.PP
Definition at line 152 of file inttypes\&.h\&.
.SS "#define PRIXPTR   'IX'"

.PP
Definition at line 153 of file inttypes\&.h\&.
.SS "#define SCNd16   'hd'"

.PP
Definition at line 163 of file inttypes\&.h\&.
.SS "#define SCNd32   'ld'"

.PP
Definition at line 170 of file inttypes\&.h\&.
.SS "#define SCNd64   'I64d'"

.PP
Definition at line 177 of file inttypes\&.h\&.
.SS "#define SCNd8   'd'"

.PP
Definition at line 156 of file inttypes\&.h\&.
.SS "#define SCNdFAST16   'hd'"

.PP
Definition at line 167 of file inttypes\&.h\&.
.SS "#define SCNdFAST32   'ld'"

.PP
Definition at line 174 of file inttypes\&.h\&.
.SS "#define SCNdFAST64   'I64d'"

.PP
Definition at line 181 of file inttypes\&.h\&.
.SS "#define SCNdFAST8   'd'"

.PP
Definition at line 160 of file inttypes\&.h\&.
.SS "#define SCNdLEAST16   'hd'"

.PP
Definition at line 165 of file inttypes\&.h\&.
.SS "#define SCNdLEAST32   'ld'"

.PP
Definition at line 172 of file inttypes\&.h\&.
.SS "#define SCNdLEAST64   'I64d'"

.PP
Definition at line 179 of file inttypes\&.h\&.
.SS "#define SCNdLEAST8   'd'"

.PP
Definition at line 158 of file inttypes\&.h\&.
.SS "#define SCNdMAX   'I64d'"

.PP
Definition at line 184 of file inttypes\&.h\&.
.SS "#define SCNdPTR   'ld'"

.PP
Definition at line 191 of file inttypes\&.h\&.
.SS "#define SCNi16   'hi'"

.PP
Definition at line 164 of file inttypes\&.h\&.
.SS "#define SCNi32   'li'"

.PP
Definition at line 171 of file inttypes\&.h\&.
.SS "#define SCNi64   'I64i'"

.PP
Definition at line 178 of file inttypes\&.h\&.
.SS "#define SCNi8   'i'"

.PP
Definition at line 157 of file inttypes\&.h\&.
.SS "#define SCNiFAST16   'hi'"

.PP
Definition at line 168 of file inttypes\&.h\&.
.SS "#define SCNiFAST32   'li'"

.PP
Definition at line 175 of file inttypes\&.h\&.
.SS "#define SCNiFAST64   'I64i'"

.PP
Definition at line 182 of file inttypes\&.h\&.
.SS "#define SCNiFAST8   'i'"

.PP
Definition at line 161 of file inttypes\&.h\&.
.SS "#define SCNiLEAST16   'hi'"

.PP
Definition at line 166 of file inttypes\&.h\&.
.SS "#define SCNiLEAST32   'li'"

.PP
Definition at line 173 of file inttypes\&.h\&.
.SS "#define SCNiLEAST64   'I64i'"

.PP
Definition at line 180 of file inttypes\&.h\&.
.SS "#define SCNiLEAST8   'i'"

.PP
Definition at line 159 of file inttypes\&.h\&.
.SS "#define SCNiMAX   'I64i'"

.PP
Definition at line 185 of file inttypes\&.h\&.
.SS "#define SCNiPTR   'li'"

.PP
Definition at line 192 of file inttypes\&.h\&.
.SS "#define SCNo16   'ho'"

.PP
Definition at line 209 of file inttypes\&.h\&.
.SS "#define SCNo32   'lo'"

.PP
Definition at line 222 of file inttypes\&.h\&.
.SS "#define SCNo64   'I64o'"

.PP
Definition at line 235 of file inttypes\&.h\&.
.SS "#define SCNo8   'o'"

.PP
Definition at line 196 of file inttypes\&.h\&.
.SS "#define SCNoFAST16   'ho'"

.PP
Definition at line 217 of file inttypes\&.h\&.
.SS "#define SCNoFAST32   'lo'"

.PP
Definition at line 230 of file inttypes\&.h\&.
.SS "#define SCNoFAST64   'I64o'"

.PP
Definition at line 243 of file inttypes\&.h\&.
.SS "#define SCNoFAST8   'o'"

.PP
Definition at line 204 of file inttypes\&.h\&.
.SS "#define SCNoLEAST16   'ho'"

.PP
Definition at line 213 of file inttypes\&.h\&.
.SS "#define SCNoLEAST32   'lo'"

.PP
Definition at line 226 of file inttypes\&.h\&.
.SS "#define SCNoLEAST64   'I64o'"

.PP
Definition at line 239 of file inttypes\&.h\&.
.SS "#define SCNoLEAST8   'o'"

.PP
Definition at line 200 of file inttypes\&.h\&.
.SS "#define SCNoMAX   'I64o'"

.PP
Definition at line 248 of file inttypes\&.h\&.
.SS "#define SCNoPTR   'lo'"

.PP
Definition at line 259 of file inttypes\&.h\&.
.SS "#define SCNu16   'hu'"

.PP
Definition at line 210 of file inttypes\&.h\&.
.SS "#define SCNu32   'lu'"

.PP
Definition at line 223 of file inttypes\&.h\&.
.SS "#define SCNu64   'I64u'"

.PP
Definition at line 236 of file inttypes\&.h\&.
.SS "#define SCNu8   'u'"

.PP
Definition at line 197 of file inttypes\&.h\&.
.SS "#define SCNuFAST16   'hu'"

.PP
Definition at line 218 of file inttypes\&.h\&.
.SS "#define SCNuFAST32   'lu'"

.PP
Definition at line 231 of file inttypes\&.h\&.
.SS "#define SCNuFAST64   'I64u'"

.PP
Definition at line 244 of file inttypes\&.h\&.
.SS "#define SCNuFAST8   'u'"

.PP
Definition at line 205 of file inttypes\&.h\&.
.SS "#define SCNuLEAST16   'hu'"

.PP
Definition at line 214 of file inttypes\&.h\&.
.SS "#define SCNuLEAST32   'lu'"

.PP
Definition at line 227 of file inttypes\&.h\&.
.SS "#define SCNuLEAST64   'I64u'"

.PP
Definition at line 240 of file inttypes\&.h\&.
.SS "#define SCNuLEAST8   'u'"

.PP
Definition at line 201 of file inttypes\&.h\&.
.SS "#define SCNuMAX   'I64u'"

.PP
Definition at line 249 of file inttypes\&.h\&.
.SS "#define SCNuPTR   'lu'"

.PP
Definition at line 260 of file inttypes\&.h\&.
.SS "#define SCNx16   'hx'"

.PP
Definition at line 211 of file inttypes\&.h\&.
.SS "#define SCNX16   'hX'"

.PP
Definition at line 212 of file inttypes\&.h\&.
.SS "#define SCNx32   'lx'"

.PP
Definition at line 224 of file inttypes\&.h\&.
.SS "#define SCNX32   'lX'"

.PP
Definition at line 225 of file inttypes\&.h\&.
.SS "#define SCNx64   'I64x'"

.PP
Definition at line 237 of file inttypes\&.h\&.
.SS "#define SCNX64   'I64X'"

.PP
Definition at line 238 of file inttypes\&.h\&.
.SS "#define SCNx8   'x'"

.PP
Definition at line 198 of file inttypes\&.h\&.
.SS "#define SCNX8   'X'"

.PP
Definition at line 199 of file inttypes\&.h\&.
.SS "#define SCNxFAST16   'hx'"

.PP
Definition at line 219 of file inttypes\&.h\&.
.SS "#define SCNXFAST16   'hX'"

.PP
Definition at line 220 of file inttypes\&.h\&.
.SS "#define SCNxFAST32   'lx'"

.PP
Definition at line 232 of file inttypes\&.h\&.
.SS "#define SCNXFAST32   'lX'"

.PP
Definition at line 233 of file inttypes\&.h\&.
.SS "#define SCNxFAST64   'I64x'"

.PP
Definition at line 245 of file inttypes\&.h\&.
.SS "#define SCNXFAST64   'I64X'"

.PP
Definition at line 246 of file inttypes\&.h\&.
.SS "#define SCNxFAST8   'x'"

.PP
Definition at line 206 of file inttypes\&.h\&.
.SS "#define SCNXFAST8   'X'"

.PP
Definition at line 207 of file inttypes\&.h\&.
.SS "#define SCNxLEAST16   'hx'"

.PP
Definition at line 215 of file inttypes\&.h\&.
.SS "#define SCNXLEAST16   'hX'"

.PP
Definition at line 216 of file inttypes\&.h\&.
.SS "#define SCNxLEAST32   'lx'"

.PP
Definition at line 228 of file inttypes\&.h\&.
.SS "#define SCNXLEAST32   'lX'"

.PP
Definition at line 229 of file inttypes\&.h\&.
.SS "#define SCNxLEAST64   'I64x'"

.PP
Definition at line 241 of file inttypes\&.h\&.
.SS "#define SCNXLEAST64   'I64X'"

.PP
Definition at line 242 of file inttypes\&.h\&.
.SS "#define SCNxLEAST8   'x'"

.PP
Definition at line 202 of file inttypes\&.h\&.
.SS "#define SCNXLEAST8   'X'"

.PP
Definition at line 203 of file inttypes\&.h\&.
.SS "#define SCNxMAX   'I64x'"

.PP
Definition at line 250 of file inttypes\&.h\&.
.SS "#define SCNXMAX   'I64X'"

.PP
Definition at line 251 of file inttypes\&.h\&.
.SS "#define SCNxPTR   'lx'"

.PP
Definition at line 261 of file inttypes\&.h\&.
.SS "#define SCNXPTR   'lX'"

.PP
Definition at line 262 of file inttypes\&.h\&.
.SS "#define strtoimax   _strtoi64"

.PP
Definition at line 298 of file inttypes\&.h\&.
.SS "#define strtoumax   _strtoui64"

.PP
Definition at line 299 of file inttypes\&.h\&.
.SS "#define wcstoimax   _wcstoi64"

.PP
Definition at line 302 of file inttypes\&.h\&.
.SS "#define wcstoumax   _wcstoui64"

.PP
Definition at line 303 of file inttypes\&.h\&.
.SH "Function Documentation"
.PP 
.SS "_inline \fBimaxdiv_t\fP __cdecl imaxdiv (\fBintmax_t\fP numer, \fBintmax_t\fP denom)"

.PP
Definition at line 281 of file inttypes\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
