.TH "IPartsListVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPartsListVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <devicetopology\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIPartsList\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIPartsList\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIPartsList\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetCount)(\fBIPartsList\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPart)(\fBIPartsList\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__out\fP \fBUINT\fP * \fBpCount\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fBnIndex\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP \fBIPart\fP ** \fBppPart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2339 of file devicetopology\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IPartsListVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IPartsListVtbl::HRESULT (STDMETHODCALLTYPE * GetCount)"

.SS "IPartsListVtbl::HRESULT (STDMETHODCALLTYPE * GetPart)"

.SS "IPartsListVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IPartsListVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBUINT\fP IPartsListVtbl::nIndex"

.PP
Definition at line 2363 of file devicetopology\&.h\&.
.SS "\fB__out\fP \fBUINT\fP* IPartsListVtbl::pCount"

.PP
Definition at line 2358 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP \fBIPart\fP** IPartsListVtbl::ppPart"

.PP
Definition at line 2363 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IPartsListVtbl::ppvObject"

.PP
Definition at line 2345 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IPartsListVtbl::riid"

.PP
Definition at line 2345 of file devicetopology\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
