.TH "IPerChannelDbLevelVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPerChannelDbLevelVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <devicetopology\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIPerChannelDbLevel\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIPerChannelDbLevel\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetChannelCount)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetLevelRange)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetLevel)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevel)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevelUniform)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetLevelAllChannels)(\fBIPerChannelDbLevel\fP *This"
.br
.ti -1c
.RI "\fB__in_ecount\fP (\fBcChannels\fP) float aLevelsDB[]"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__out\fP \fBUINT\fP * \fBpcChannels\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fBnChannel\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float * \fBpfMinLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float * \fBpfMaxLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float \fB__out\fP float * \fBpfStepping\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__out\fP float * \fBpfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__in\fP float \fBfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBUINT\fP \fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.ti -1c
.RI "\fB__in\fP float \fBfLevelDB\fP"
.br
.ti -1c
.RI "\fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBULONG\fP \fBcChannels\fP"
.br
.ti -1c
.RI "\fB__in\fP \fBULONG\fP \fB__in_opt\fP \fBLPCGUID\fP \fBpguidEventContext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 648 of file devicetopology\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "IPerChannelDbLevelVtbl::__in_ecount (\fBcChannels\fP)"

.SS "BEGIN_INTERFACE IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * GetChannelCount)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * GetLevelRange)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * GetLevel)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * SetLevel)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * SetLevelUniform)"

.SS "IPerChannelDbLevelVtbl::HRESULT (STDMETHODCALLTYPE * SetLevelAllChannels)"

.SS "IPerChannelDbLevelVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IPerChannelDbLevelVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__in\fP \fBULONG\fP IPerChannelDbLevelVtbl::cChannels"

.PP
Definition at line 708 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__in\fP float IPerChannelDbLevelVtbl::fLevelDB"

.PP
Definition at line 690 of file devicetopology\&.h\&.
.SS "\fB__in\fP float IPerChannelDbLevelVtbl::fLevelDB"

.PP
Definition at line 699 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP IPerChannelDbLevelVtbl::nChannel"

.PP
Definition at line 672 of file devicetopology\&.h\&.
.SS "\fB__out\fP \fBUINT\fP* IPerChannelDbLevelVtbl::pcChannels"

.PP
Definition at line 667 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float* IPerChannelDbLevelVtbl::pfLevelDB"

.PP
Definition at line 683 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float* IPerChannelDbLevelVtbl::pfMaxLevelDB"

.PP
Definition at line 672 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float* IPerChannelDbLevelVtbl::pfMinLevelDB"

.PP
Definition at line 672 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__out\fP float \fB__out\fP float \fB__out\fP float* IPerChannelDbLevelVtbl::pfStepping"

.PP
Definition at line 672 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBUINT\fP \fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP IPerChannelDbLevelVtbl::pguidEventContext"

.PP
Definition at line 690 of file devicetopology\&.h\&.
.SS "\fB__in\fP float \fB__in_opt\fP \fBLPCGUID\fP IPerChannelDbLevelVtbl::pguidEventContext"

.PP
Definition at line 699 of file devicetopology\&.h\&.
.SS "\fB__in\fP \fBULONG\fP \fB__in_opt\fP \fBLPCGUID\fP IPerChannelDbLevelVtbl::pguidEventContext"

.PP
Definition at line 708 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IPerChannelDbLevelVtbl::ppvObject"

.PP
Definition at line 654 of file devicetopology\&.h\&.
.SS "BEGIN_INTERFACE \fBREFIID\fP IPerChannelDbLevelVtbl::riid"

.PP
Definition at line 654 of file devicetopology\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
