.TH "IPropertyDescriptionAliasInfoVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPropertyDescriptionAliasInfoVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propsys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIPropertyDescriptionAliasInfo\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIPropertyDescriptionAliasInfo\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyKey)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetCanonicalName)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyType)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDisplayName)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetEditInvitation)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetTypeFlags)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetViewFlags)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDefaultColumnWidth)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDisplayType)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetColumnState)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetGroupingRange)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetRelativeDescriptionType)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetRelativeDescription)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSortDescription)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSortDescriptionLabel)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetAggregationType)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetConditionType)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetEnumTypeList)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *CoerceToCanonicalValue)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *FormatForDisplay)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *IsValueCanonical)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSortByAlias)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetAdditionalSortByAliases)(\fBIPropertyDescriptionAliasInfo\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPERTYKEY\fP * \fBpkey\fP"
.br
.ti -1c
.RI "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszName\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP VARTYPE * \fBpvartype\fP"
.br
.ti -1c
.RI "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszInvite\fP"
.br
.ti -1c
.RI "\fBPROPDESC_TYPE_FLAGS\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBPROPDESC_TYPE_FLAGS\fP \fB__RPC__out\fP \fBPROPDESC_TYPE_FLAGS\fP * \fBppdtFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_VIEW_FLAGS\fP * \fBppdvFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBUINT\fP * \fBpcxChars\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_DISPLAYTYPE\fP * \fBpdisplaytype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBSHCOLSTATEF\fP * \fBpcsFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_GROUPING_RANGE\fP * \fBpgr\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_RELATIVEDESCRIPTION_TYPE\fP * \fBprdt\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar1\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar2\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDesc1\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDesc2\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_SORTDESCRIPTION\fP * \fBpsd\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBfDescending\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDescription\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_AGGREGATION_TYPE\fP * \fBpaggtype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP * \fBpcontype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP \fB__RPC__out\fP \fBCONDITION_OPERATION\fP * \fBpopDefault\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fBPROPVARIANT\fP * \fBppropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fBpdfFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDisplay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1983 of file propsys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyKey)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetCanonicalName)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyType)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetDisplayName)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetEditInvitation)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetTypeFlags)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetViewFlags)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetDefaultColumnWidth)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetDisplayType)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetColumnState)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetGroupingRange)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetRelativeDescriptionType)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetRelativeDescription)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetSortDescription)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetSortDescriptionLabel)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetAggregationType)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetConditionType)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetEnumTypeList)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * CoerceToCanonicalValue)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * FormatForDisplay)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * IsValueCanonical)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetSortByAlias)"

.SS "IPropertyDescriptionAliasInfoVtbl::HRESULT (STDMETHODCALLTYPE * GetAdditionalSortByAliases)"

.SS "IPropertyDescriptionAliasInfoVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IPropertyDescriptionAliasInfoVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fBBOOL\fP IPropertyDescriptionAliasInfoVtbl::fDescending"

.PP
Definition at line 2061 of file propsys\&.h\&.
.SS "\fBPROPDESC_TYPE_FLAGS\fP IPropertyDescriptionAliasInfoVtbl::mask"

.PP
Definition at line 2021 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_AGGREGATION_TYPE\fP* IPropertyDescriptionAliasInfoVtbl::paggtype"

.PP
Definition at line 2066 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP* IPropertyDescriptionAliasInfoVtbl::pcontype"

.PP
Definition at line 2070 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBSHCOLSTATEF\fP* IPropertyDescriptionAliasInfoVtbl::pcsFlags"

.PP
Definition at line 2038 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBUINT\fP* IPropertyDescriptionAliasInfoVtbl::pcxChars"

.PP
Definition at line 2030 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP IPropertyDescriptionAliasInfoVtbl::pdfFlags"

.PP
Definition at line 2084 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_DISPLAYTYPE\fP* IPropertyDescriptionAliasInfoVtbl::pdisplaytype"

.PP
Definition at line 2034 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_GROUPING_RANGE\fP* IPropertyDescriptionAliasInfoVtbl::pgr"

.PP
Definition at line 2042 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPERTYKEY\fP* IPropertyDescriptionAliasInfoVtbl::pkey"

.PP
Definition at line 2001 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP \fB__RPC__out\fP \fBCONDITION_OPERATION\fP* IPropertyDescriptionAliasInfoVtbl::popDefault"

.PP
Definition at line 2070 of file propsys\&.h\&.
.SS "\fBPROPDESC_TYPE_FLAGS\fP \fB__RPC__out\fP \fBPROPDESC_TYPE_FLAGS\fP* IPropertyDescriptionAliasInfoVtbl::ppdtFlags"

.PP
Definition at line 2021 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_VIEW_FLAGS\fP* IPropertyDescriptionAliasInfoVtbl::ppdvFlags"

.PP
Definition at line 2026 of file propsys\&.h\&.
.SS "\fBPROPVARIANT\fP* IPropertyDescriptionAliasInfoVtbl::ppropvar"

.PP
Definition at line 2080 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionAliasInfoVtbl::ppszDesc1"

.PP
Definition at line 2050 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionAliasInfoVtbl::ppszDesc2"

.PP
Definition at line 2050 of file propsys\&.h\&.
.SS "\fBBOOL\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionAliasInfoVtbl::ppszDescription"

.PP
Definition at line 2061 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionAliasInfoVtbl::ppszDisplay"

.PP
Definition at line 2084 of file propsys\&.h\&.
.SS "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionAliasInfoVtbl::ppszInvite"

.PP
Definition at line 2017 of file propsys\&.h\&.
.SS "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * IPropertyDescriptionAliasInfoVtbl::ppszName"

.PP
Definition at line 2005 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** IPropertyDescriptionAliasInfoVtbl::ppv"

.PP
Definition at line 2075 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IPropertyDescriptionAliasInfoVtbl::ppvObject"

.PP
Definition at line 1989 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_RELATIVEDESCRIPTION_TYPE\fP* IPropertyDescriptionAliasInfoVtbl::prdt"

.PP
Definition at line 2046 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionAliasInfoVtbl::propvar"

.PP
Definition at line 2084 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionAliasInfoVtbl::propvar1"

.PP
Definition at line 2050 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionAliasInfoVtbl::propvar2"

.PP
Definition at line 2050 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_SORTDESCRIPTION\fP* IPropertyDescriptionAliasInfoVtbl::psd"

.PP
Definition at line 2057 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP VARTYPE* IPropertyDescriptionAliasInfoVtbl::pvartype"

.PP
Definition at line 2009 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFIID\fP IPropertyDescriptionAliasInfoVtbl::riid"

.PP
Definition at line 1989 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFIID\fP IPropertyDescriptionAliasInfoVtbl::riid"

.PP
Definition at line 2075 of file propsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
