.TH "IPropertyDescriptionVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPropertyDescriptionVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propsys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIPropertyDescription\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIPropertyDescription\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyKey)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetCanonicalName)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyType)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDisplayName)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetEditInvitation)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetTypeFlags)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetViewFlags)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDefaultColumnWidth)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetDisplayType)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetColumnState)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetGroupingRange)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetRelativeDescriptionType)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetRelativeDescription)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSortDescription)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSortDescriptionLabel)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetAggregationType)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetConditionType)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetEnumTypeList)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *CoerceToCanonicalValue)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *FormatForDisplay)(\fBIPropertyDescription\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *IsValueCanonical)(\fBIPropertyDescription\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPERTYKEY\fP * \fBpkey\fP"
.br
.ti -1c
.RI "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszName\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP VARTYPE * \fBpvartype\fP"
.br
.ti -1c
.RI "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszInvite\fP"
.br
.ti -1c
.RI "\fBPROPDESC_TYPE_FLAGS\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBPROPDESC_TYPE_FLAGS\fP \fB__RPC__out\fP \fBPROPDESC_TYPE_FLAGS\fP * \fBppdtFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_VIEW_FLAGS\fP * \fBppdvFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBUINT\fP * \fBpcxChars\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_DISPLAYTYPE\fP * \fBpdisplaytype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBSHCOLSTATEF\fP * \fBpcsFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_GROUPING_RANGE\fP * \fBpgr\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_RELATIVEDESCRIPTION_TYPE\fP * \fBprdt\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar1\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar2\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDesc1\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDesc2\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_SORTDESCRIPTION\fP * \fBpsd\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBfDescending\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDescription\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_AGGREGATION_TYPE\fP * \fBpaggtype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP * \fBpcontype\fP"
.br
.ti -1c
.RI "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP \fB__RPC__out\fP \fBCONDITION_OPERATION\fP * \fBpopDefault\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fBPROPVARIANT\fP * \fBppropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fBpdfFlags\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDisplay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1737 of file propsys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyKey)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetCanonicalName)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyType)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetDisplayName)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetEditInvitation)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetTypeFlags)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetViewFlags)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetDefaultColumnWidth)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetDisplayType)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetColumnState)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetGroupingRange)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetRelativeDescriptionType)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetRelativeDescription)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetSortDescription)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetSortDescriptionLabel)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetAggregationType)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetConditionType)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * GetEnumTypeList)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * CoerceToCanonicalValue)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * FormatForDisplay)"

.SS "IPropertyDescriptionVtbl::HRESULT (STDMETHODCALLTYPE * IsValueCanonical)"

.SS "IPropertyDescriptionVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IPropertyDescriptionVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fBBOOL\fP IPropertyDescriptionVtbl::fDescending"

.PP
Definition at line 1815 of file propsys\&.h\&.
.SS "\fBPROPDESC_TYPE_FLAGS\fP IPropertyDescriptionVtbl::mask"

.PP
Definition at line 1775 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_AGGREGATION_TYPE\fP* IPropertyDescriptionVtbl::paggtype"

.PP
Definition at line 1820 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP* IPropertyDescriptionVtbl::pcontype"

.PP
Definition at line 1824 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBSHCOLSTATEF\fP* IPropertyDescriptionVtbl::pcsFlags"

.PP
Definition at line 1792 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBUINT\fP* IPropertyDescriptionVtbl::pcxChars"

.PP
Definition at line 1784 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP IPropertyDescriptionVtbl::pdfFlags"

.PP
Definition at line 1838 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_DISPLAYTYPE\fP* IPropertyDescriptionVtbl::pdisplaytype"

.PP
Definition at line 1788 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_GROUPING_RANGE\fP* IPropertyDescriptionVtbl::pgr"

.PP
Definition at line 1796 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPERTYKEY\fP* IPropertyDescriptionVtbl::pkey"

.PP
Definition at line 1755 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_CONDITION_TYPE\fP \fB__RPC__out\fP \fBCONDITION_OPERATION\fP* IPropertyDescriptionVtbl::popDefault"

.PP
Definition at line 1824 of file propsys\&.h\&.
.SS "\fBPROPDESC_TYPE_FLAGS\fP \fB__RPC__out\fP \fBPROPDESC_TYPE_FLAGS\fP* IPropertyDescriptionVtbl::ppdtFlags"

.PP
Definition at line 1775 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_VIEW_FLAGS\fP* IPropertyDescriptionVtbl::ppdvFlags"

.PP
Definition at line 1780 of file propsys\&.h\&.
.SS "\fBPROPVARIANT\fP* IPropertyDescriptionVtbl::ppropvar"

.PP
Definition at line 1834 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionVtbl::ppszDesc1"

.PP
Definition at line 1804 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionVtbl::ppszDesc2"

.PP
Definition at line 1804 of file propsys\&.h\&.
.SS "\fBBOOL\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionVtbl::ppszDescription"

.PP
Definition at line 1815 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionVtbl::ppszDisplay"

.PP
Definition at line 1838 of file propsys\&.h\&.
.SS "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertyDescriptionVtbl::ppszInvite"

.PP
Definition at line 1771 of file propsys\&.h\&.
.SS "\fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * IPropertyDescriptionVtbl::ppszName"

.PP
Definition at line 1759 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IPropertyDescriptionVtbl::ppv"

.PP
Definition at line 1829 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IPropertyDescriptionVtbl::ppvObject"

.PP
Definition at line 1743 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_RELATIVEDESCRIPTION_TYPE\fP* IPropertyDescriptionVtbl::prdt"

.PP
Definition at line 1800 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionVtbl::propvar"

.PP
Definition at line 1838 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionVtbl::propvar1"

.PP
Definition at line 1804 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPVARIANT\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertyDescriptionVtbl::propvar2"

.PP
Definition at line 1804 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP \fBPROPDESC_SORTDESCRIPTION\fP* IPropertyDescriptionVtbl::psd"

.PP
Definition at line 1811 of file propsys\&.h\&.
.SS "\fB__RPC__out\fP VARTYPE* IPropertyDescriptionVtbl::pvartype"

.PP
Definition at line 1763 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP IPropertyDescriptionVtbl::riid"

.PP
Definition at line 1743 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFIID\fP IPropertyDescriptionVtbl::riid"

.PP
Definition at line 1829 of file propsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
