.TH "IPropertySystemVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPropertySystemVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propsys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIPropertySystem\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIPropertySystem\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyDescription)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyDescriptionByName)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetPropertyDescriptionListFromString)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *EnumeratePropertyDescriptions)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *FormatForDisplay)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__out_ecount_full_string\fP (\fBcchText\fP) \fBLPWSTR\fP pszText"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *FormatForDisplayAlloc)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *RegisterPropertySchema)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *UnregisterPropertySchema)(\fBIPropertySystem\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *RefreshPropertySchema)(\fBIPropertySystem\fP *This)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fBpropkey\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszCanonicalName\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszPropList\fP"
.br
.ti -1c
.RI "\fBPROPDESC_ENUMFILTER\fP \fBfilterOn\fP"
.br
.ti -1c
.RI "\fBPROPDESC_ENUMFILTER\fP \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "\fBPROPDESC_ENUMFILTER\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** \fBppv\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fBkey\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBpropvar\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fBpdff\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fBDWORD\fP \fBcchText\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP * \fBppszDisplay\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2568 of file propsys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP IPropertySystemVtbl::__RPC__out_ecount_full_string (\fBcchText\fP)"

.SS "BEGIN_INTERFACE IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyDescription)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyDescriptionByName)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * GetPropertyDescriptionListFromString)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * EnumeratePropertyDescriptions)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * FormatForDisplay)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * FormatForDisplayAlloc)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * RegisterPropertySchema)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * UnregisterPropertySchema)"

.SS "IPropertySystemVtbl::HRESULT (STDMETHODCALLTYPE * RefreshPropertySchema)"

.SS "IPropertySystemVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IPropertySystemVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fBDWORD\fP IPropertySystemVtbl::cchText"

.PP
Definition at line 2614 of file propsys\&.h\&.
.SS "\fBPROPDESC_ENUMFILTER\fP IPropertySystemVtbl::filterOn"

.PP
Definition at line 2604 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP IPropertySystemVtbl::key"

.PP
Definition at line 2610 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP IPropertySystemVtbl::pdff"

.PP
Definition at line 2610 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP \fBPROPDESC_FORMAT_FLAGS\fP \fB__RPC__deref_out_opt_string\fP \fBLPWSTR\fP* IPropertySystemVtbl::ppszDisplay"

.PP
Definition at line 2618 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP ** IPropertySystemVtbl::ppv"

.PP
Definition at line 2586 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IPropertySystemVtbl::ppv"

.PP
Definition at line 2592 of file propsys\&.h\&.
.SS "\fBPROPDESC_ENUMFILTER\fP \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out_opt\fP \fBvoid\fP** IPropertySystemVtbl::ppv"

.PP
Definition at line 2604 of file propsys\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IPropertySystemVtbl::ppvObject"

.PP
Definition at line 2574 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP IPropertySystemVtbl::propkey"

.PP
Definition at line 2586 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFPROPVARIANT\fP IPropertySystemVtbl::propvar"

.PP
Definition at line 2610 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP IPropertySystemVtbl::pszCanonicalName"

.PP
Definition at line 2592 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP IPropertySystemVtbl::pszPath"

.PP
Definition at line 2625 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP IPropertySystemVtbl::pszPropList"

.PP
Definition at line 2598 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP IPropertySystemVtbl::riid"

.PP
Definition at line 2574 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBREFPROPERTYKEY\fP \fB__RPC__in\fP \fBREFIID\fP IPropertySystemVtbl::riid"

.PP
Definition at line 2586 of file propsys\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBREFIID\fP IPropertySystemVtbl::riid"

.PP
Definition at line 2592 of file propsys\&.h\&.
.SS "\fBPROPDESC_ENUMFILTER\fP \fB__RPC__in\fP \fBREFIID\fP IPropertySystemVtbl::riid"

.PP
Definition at line 2604 of file propsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
