.TH "IQueryParserVtbl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IQueryParserVtbl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structuredquery\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fBHRESULT\fP (STDMETHODCALLTYPE *QueryInterface)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *AddRef)(\fBIQueryParser\fP *This)"
.br
.ti -1c
.RI "\fBULONG\fP (STDMETHODCALLTYPE *Release)(\fBIQueryParser\fP *This)"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *Parse)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *\fBSetOption\fP)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *\fBGetOption\fP)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *SetMultiOption)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *GetSchemaProvider)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *RestateToString)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *ParsePropertyValue)(\fBIQueryParser\fP *This"
.br
.ti -1c
.RI "\fBHRESULT\fP (STDMETHODCALLTYPE *RestatePropertyValueToString)(\fBIQueryParser\fP *This"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fBriid\fP"
.br
.ti -1c
.RI "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP ** \fBppvObject\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszInputString\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in_opt\fP IEnumUnknown * \fBpCustomProperties\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in_opt\fP IEnumUnknown \fB__RPC__deref_out_opt\fP \fBIQuerySolution\fP ** \fBppSolution\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP \fBoption\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP \fB__RPC__in\fP \fBconst\fP \fBPROPVARIANT\fP * \fBpOptionValue\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP \fB__RPC__out\fP \fBPROPVARIANT\fP * \fBpOptionValue\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_MULTIOPTION\fP \fBoption\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_MULTIOPTION\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fBpszOptionKey\fP"
.br
.ti -1c
.RI "\fBSTRUCTURED_QUERY_MULTIOPTION\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBconst\fP \fBPROPVARIANT\fP * \fBpOptionValue\fP"
.br
.ti -1c
.RI "\fB__RPC__deref_out_opt\fP \fBISchemaProvider\fP ** \fBppSchemaProvider\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBICondition\fP * \fBpCondition\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fBfUseEnglish\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP * \fBppszQueryString\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fBpszPropertyName\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fBpszInputString\fP"
.br
.ti -1c
.RI "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__deref_out_opt\fP \fBIQuerySolution\fP ** \fBppSolution\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP * \fBppszPropertyName\fP"
.br
.ti -1c
.RI "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP * \fBppszQueryString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 402 of file structuredquery\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "BEGIN_INTERFACE IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * QueryInterface)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * Parse)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * SetOption)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * GetOption)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * SetMultiOption)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * GetSchemaProvider)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * RestateToString)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * ParsePropertyValue)"

.SS "IQueryParserVtbl::HRESULT (STDMETHODCALLTYPE * RestatePropertyValueToString)"

.SS "IQueryParserVtbl::ULONG (STDMETHODCALLTYPE * AddRef)"

.SS "IQueryParserVtbl::ULONG (STDMETHODCALLTYPE * Release)"

.SH "Member Data Documentation"
.PP 
.SS "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP IQueryParserVtbl::fUseEnglish"

.PP
Definition at line 446 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP IQueryParserVtbl::option"

.PP
Definition at line 426 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_MULTIOPTION\fP IQueryParserVtbl::option"

.PP
Definition at line 436 of file structuredquery\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBICondition\fP * IQueryParserVtbl::pCondition"

.PP
Definition at line 446 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in_opt\fP IEnumUnknown* IQueryParserVtbl::pCustomProperties"

.PP
Definition at line 420 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP \fB__RPC__in\fP \fBconst\fP \fBPROPVARIANT\fP* IQueryParserVtbl::pOptionValue"

.PP
Definition at line 426 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_SINGLE_OPTION\fP \fB__RPC__out\fP \fBPROPVARIANT\fP* IQueryParserVtbl::pOptionValue"

.PP
Definition at line 431 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_MULTIOPTION\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBconst\fP \fBPROPVARIANT\fP* IQueryParserVtbl::pOptionValue"

.PP
Definition at line 436 of file structuredquery\&.h\&.
.SS "\fB__RPC__deref_out_opt\fP \fBISchemaProvider\fP** IQueryParserVtbl::ppSchemaProvider"

.PP
Definition at line 442 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in_opt\fP IEnumUnknown \fB__RPC__deref_out_opt\fP \fBIQuerySolution\fP** IQueryParserVtbl::ppSolution"

.PP
Definition at line 420 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__deref_out_opt\fP \fBIQuerySolution\fP** IQueryParserVtbl::ppSolution"

.PP
Definition at line 452 of file structuredquery\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP* IQueryParserVtbl::ppszPropertyName"

.PP
Definition at line 458 of file structuredquery\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP* IQueryParserVtbl::ppszQueryString"

.PP
Definition at line 446 of file structuredquery\&.h\&.
.SS "\fB__RPC__in_opt\fP \fBICondition\fP \fBBOOL\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP \fB__RPC__deref_out_opt\fP \fBLPWSTR\fP* IQueryParserVtbl::ppszQueryString"

.PP
Definition at line 458 of file structuredquery\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP \fB__RPC__deref_out\fP \fBvoid\fP** IQueryParserVtbl::ppvObject"

.PP
Definition at line 408 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP IQueryParserVtbl::pszInputString"

.PP
Definition at line 420 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP \fB__RPC__in\fP \fBLPCWSTR\fP IQueryParserVtbl::pszInputString"

.PP
Definition at line 452 of file structuredquery\&.h\&.
.SS "\fBSTRUCTURED_QUERY_MULTIOPTION\fP \fB__RPC__in\fP \fBLPCWSTR\fP IQueryParserVtbl::pszOptionKey"

.PP
Definition at line 436 of file structuredquery\&.h\&.
.SS "\fB__RPC__in\fP \fBLPCWSTR\fP IQueryParserVtbl::pszPropertyName"

.PP
Definition at line 452 of file structuredquery\&.h\&.
.SS "BEGIN_INTERFACE \fB__RPC__in\fP \fBREFIID\fP IQueryParserVtbl::riid"

.PP
Definition at line 408 of file structuredquery\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
