.TH "jportmidi.JPortMidiException" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jportmidi.JPortMidiException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJPortMidiException\fP (\fBint\fP err, String msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBerror\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file JPortMidiException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "jportmidi\&.JPortMidiException\&.JPortMidiException (\fBint\fP err, String msg)\fC [inline]\fP"

.PP
Definition at line 7 of file JPortMidiException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP jportmidi\&.JPortMidiException\&.error = 0"

.PP
Definition at line 6 of file JPortMidiException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
