.TH "C:/_dev/OpenU/Audacity/audacity/src/prefs/KeyConfigPrefs.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/prefs/KeyConfigPrefs.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include '\&.\&./Experimental\&.h'\fP
.br
\fC#include 'KeyConfigPrefs\&.h'\fP
.br
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/ffile\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/filedlg\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include '\&.\&./Prefs\&.h'\fP
.br
\fC#include '\&.\&./Project\&.h'\fP
.br
\fC#include '\&.\&./commands/CommandManager\&.h'\fP
.br
\fC#include '\&.\&./commands/Keyboard\&.h'\fP
.br
\fC#include '\&.\&./xml/XMLFileReader\&.h'\fP
.br
\fC#include '\&.\&./Internat\&.h'\fP
.br
\fC#include '\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include 'FileDialog\&.h'\fP
.br
\fC#include '\&.\&./widgets/KeyView\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAssignDefaultsButtonID\fP   17001"
.br
.ti -1c
.RI "#define \fBCurrentComboID\fP   17002"
.br
.ti -1c
.RI "#define \fBSetButtonID\fP   17003"
.br
.ti -1c
.RI "#define \fBClearButtonID\fP   17004"
.br
.ti -1c
.RI "#define \fBCommandsListID\fP   17005"
.br
.ti -1c
.RI "#define \fBExportButtonID\fP   17006"
.br
.ti -1c
.RI "#define \fBImportButtonID\fP   17007"
.br
.ti -1c
.RI "#define \fBFilterID\fP   17008"
.br
.ti -1c
.RI "#define \fBViewByTreeID\fP   17009"
.br
.ti -1c
.RI "#define \fBViewByNameID\fP   17010"
.br
.ti -1c
.RI "#define \fBViewByKeyID\fP   17011"
.br
.ti -1c
.RI "#define \fBFilterTimerID\fP   17012"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AssignDefaultsButtonID   17001"

.PP
Definition at line 51 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ClearButtonID   17004"

.PP
Definition at line 54 of file KeyConfigPrefs\&.cpp\&.
.SS "#define CommandsListID   17005"

.PP
Definition at line 55 of file KeyConfigPrefs\&.cpp\&.
.SS "#define CurrentComboID   17002"

.PP
Definition at line 52 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ExportButtonID   17006"

.PP
Definition at line 56 of file KeyConfigPrefs\&.cpp\&.
.SS "#define FilterID   17008"

.PP
Definition at line 58 of file KeyConfigPrefs\&.cpp\&.
.SS "#define FilterTimerID   17012"

.PP
Definition at line 62 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ImportButtonID   17007"

.PP
Definition at line 57 of file KeyConfigPrefs\&.cpp\&.
.SS "#define SetButtonID   17003"

.PP
Definition at line 53 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ViewByKeyID   17011"

.PP
Definition at line 61 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ViewByNameID   17010"

.PP
Definition at line 60 of file KeyConfigPrefs\&.cpp\&.
.SS "#define ViewByTreeID   17009"

.PP
Definition at line 59 of file KeyConfigPrefs\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
