.TH "KeyNode" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KeyView\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxString \fBname\fP"
.br
.ti -1c
.RI "wxString \fBcategory\fP"
.br
.ti -1c
.RI "wxString \fBprefix\fP"
.br
.ti -1c
.RI "wxString \fBlabel\fP"
.br
.ti -1c
.RI "wxString \fBkey\fP"
.br
.ti -1c
.RI "\fBint\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBint\fP \fBline\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdepth\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBiscat\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBispfx\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBisparent\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBisopen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file KeyView\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyNode::KeyNode ()\fC [inline]\fP"

.PP
Definition at line 25 of file KeyView\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wxString KeyNode::category"

.PP
Definition at line 38 of file KeyView\&.h\&.
.SS "\fBint\fP KeyNode::depth"

.PP
Definition at line 44 of file KeyView\&.h\&.
.SS "\fBint\fP KeyNode::index"

.PP
Definition at line 42 of file KeyView\&.h\&.
.SS "\fBbool\fP KeyNode::iscat"

.PP
Definition at line 45 of file KeyView\&.h\&.
.SS "\fBbool\fP KeyNode::isopen"

.PP
Definition at line 48 of file KeyView\&.h\&.
.SS "\fBbool\fP KeyNode::isparent"

.PP
Definition at line 47 of file KeyView\&.h\&.
.SS "\fBbool\fP KeyNode::ispfx"

.PP
Definition at line 46 of file KeyView\&.h\&.
.SS "wxString KeyNode::key"

.PP
Definition at line 41 of file KeyView\&.h\&.
.SS "wxString KeyNode::label"

.PP
Definition at line 40 of file KeyView\&.h\&.
.SS "\fBint\fP KeyNode::line"

.PP
Definition at line 43 of file KeyView\&.h\&.
.SS "wxString KeyNode::name"

.PP
Definition at line 37 of file KeyView\&.h\&.
.SS "wxString KeyNode::prefix"

.PP
Definition at line 39 of file KeyView\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
