.TH "KSAC3_ERROR_CONCEALMENT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSAC3_ERROR_CONCEALMENT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WINBOOL \fBfRepeatPreviousBlock\fP"
.br
.ti -1c
.RI "WINBOOL \fBfErrorInCurrentBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2134 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "WINBOOL KSAC3_ERROR_CONCEALMENT::fErrorInCurrentBlock"

.PP
Definition at line 2136 of file ksmedia\&.h\&.
.SS "WINBOOL KSAC3_ERROR_CONCEALMENT::fRepeatPreviousBlock"

.PP
Definition at line 2135 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
