.TH "KSAC3_ROOM_TYPE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSAC3_ROOM_TYPE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WINBOOL \fBfLargeRoom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2170 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "WINBOOL KSAC3_ROOM_TYPE::fLargeRoom"

.PP
Definition at line 2171 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
