.TH "KSCORRELATED_TIME" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSCORRELATED_TIME \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ks\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LONGLONG \fBTime\fP"
.br
.ti -1c
.RI "LONGLONG \fBSystemTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1769 of file ks\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "LONGLONG KSCORRELATED_TIME::SystemTime"

.PP
Definition at line 1771 of file ks\&.h\&.
.SS "LONGLONG KSCORRELATED_TIME::Time"

.PP
Definition at line 1770 of file ks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
