.TH "KSDATAFORMAT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSDATAFORMAT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ks\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   ULONG \fBFormatSize\fP"
.br
.ti -1c
.RI "   ULONG \fBFlags\fP"
.br
.ti -1c
.RI "   ULONG \fBSampleSize\fP"
.br
.ti -1c
.RI "   ULONG \fBReserved\fP"
.br
.ti -1c
.RI "   GUID \fBMajorFormat\fP"
.br
.ti -1c
.RI "   GUID \fBSubFormat\fP"
.br
.ti -1c
.RI "   GUID \fBSpecifier\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "LONGLONG \fBAlignment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 793 of file ks\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "LONGLONG KSDATAFORMAT::Alignment"

.PP
Definition at line 803 of file ks\&.h\&.
.SS "ULONG KSDATAFORMAT::Flags"

.PP
Definition at line 796 of file ks\&.h\&.
.SS "ULONG KSDATAFORMAT::FormatSize"

.PP
Definition at line 795 of file ks\&.h\&.
.SS "GUID KSDATAFORMAT::MajorFormat"

.PP
Definition at line 799 of file ks\&.h\&.
.SS "ULONG KSDATAFORMAT::Reserved"

.PP
Definition at line 798 of file ks\&.h\&.
.SS "ULONG KSDATAFORMAT::SampleSize"

.PP
Definition at line 797 of file ks\&.h\&.
.SS "GUID KSDATAFORMAT::Specifier"

.PP
Definition at line 801 of file ks\&.h\&.
.SS "GUID KSDATAFORMAT::SubFormat"

.PP
Definition at line 800 of file ks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
