.TH "KSDATARANGE_AUDIO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSDATARANGE_AUDIO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSDATARANGE\fP \fBDataRange\fP"
.br
.ti -1c
.RI "ULONG \fBMaximumChannels\fP"
.br
.ti -1c
.RI "ULONG \fBMinimumBitsPerSample\fP"
.br
.ti -1c
.RI "ULONG \fBMaximumBitsPerSample\fP"
.br
.ti -1c
.RI "ULONG \fBMinimumSampleFrequency\fP"
.br
.ti -1c
.RI "ULONG \fBMaximumSampleFrequency\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 909 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSDATARANGE\fP KSDATARANGE_AUDIO::DataRange"

.PP
Definition at line 910 of file ksmedia\&.h\&.
.SS "ULONG KSDATARANGE_AUDIO::MaximumBitsPerSample"

.PP
Definition at line 913 of file ksmedia\&.h\&.
.SS "ULONG KSDATARANGE_AUDIO::MaximumChannels"

.PP
Definition at line 911 of file ksmedia\&.h\&.
.SS "ULONG KSDATARANGE_AUDIO::MaximumSampleFrequency"

.PP
Definition at line 915 of file ksmedia\&.h\&.
.SS "ULONG KSDATARANGE_AUDIO::MinimumBitsPerSample"

.PP
Definition at line 912 of file ksmedia\&.h\&.
.SS "ULONG KSDATARANGE_AUDIO::MinimumSampleFrequency"

.PP
Definition at line 914 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
