.TH "KSDISPLAYCHANGE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSDISPLAYCHANGE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBPelsWidth\fP"
.br
.ti -1c
.RI "ULONG \fBPelsHeight\fP"
.br
.ti -1c
.RI "ULONG \fBBitsPerPel\fP"
.br
.ti -1c
.RI "WCHAR \fBDeviceID\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3981 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSDISPLAYCHANGE::BitsPerPel"

.PP
Definition at line 3984 of file ksmedia\&.h\&.
.SS "WCHAR KSDISPLAYCHANGE::DeviceID[1]"

.PP
Definition at line 3985 of file ksmedia\&.h\&.
.SS "ULONG KSDISPLAYCHANGE::PelsHeight"

.PP
Definition at line 3983 of file ksmedia\&.h\&.
.SS "ULONG KSDISPLAYCHANGE::PelsWidth"

.PP
Definition at line 3982 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
