.TH "KSDS3D_HRTF_PARAMS_MSG" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSDS3D_HRTF_PARAMS_MSG \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBSize\fP"
.br
.ti -1c
.RI "ULONG \fBEnabled\fP"
.br
.ti -1c
.RI "WINBOOL \fBSwapChannels\fP"
.br
.ti -1c
.RI "WINBOOL \fBZeroAzimuth\fP"
.br
.ti -1c
.RI "WINBOOL \fBCrossFadeOutput\fP"
.br
.ti -1c
.RI "ULONG \fBFilterSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 824 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "WINBOOL KSDS3D_HRTF_PARAMS_MSG::CrossFadeOutput"

.PP
Definition at line 829 of file ksmedia\&.h\&.
.SS "ULONG KSDS3D_HRTF_PARAMS_MSG::Enabled"

.PP
Definition at line 826 of file ksmedia\&.h\&.
.SS "ULONG KSDS3D_HRTF_PARAMS_MSG::FilterSize"

.PP
Definition at line 830 of file ksmedia\&.h\&.
.SS "ULONG KSDS3D_HRTF_PARAMS_MSG::Size"

.PP
Definition at line 825 of file ksmedia\&.h\&.
.SS "WINBOOL KSDS3D_HRTF_PARAMS_MSG::SwapChannels"

.PP
Definition at line 827 of file ksmedia\&.h\&.
.SS "WINBOOL KSDS3D_HRTF_PARAMS_MSG::ZeroAzimuth"

.PP
Definition at line 828 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
