.TH "KSDS3D_HRTF_FILTER_FORMAT_MSG" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSDS3D_HRTF_FILTER_FORMAT_MSG \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSDS3D_HRTF_FILTER_METHOD\fP \fBFilterMethod\fP"
.br
.ti -1c
.RI "\fBKSDS3D_HRTF_COEFF_FORMAT\fP \fBCoeffFormat\fP"
.br
.ti -1c
.RI "\fBKSDS3D_HRTF_FILTER_VERSION\fP \fBVersion\fP"
.br
.ti -1c
.RI "ULONG \fBReserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 866 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSDS3D_HRTF_COEFF_FORMAT\fP KSDS3D_HRTF_FILTER_FORMAT_MSG::CoeffFormat"

.PP
Definition at line 868 of file ksmedia\&.h\&.
.SS "\fBKSDS3D_HRTF_FILTER_METHOD\fP KSDS3D_HRTF_FILTER_FORMAT_MSG::FilterMethod"

.PP
Definition at line 867 of file ksmedia\&.h\&.
.SS "ULONG KSDS3D_HRTF_FILTER_FORMAT_MSG::Reserved"

.PP
Definition at line 870 of file ksmedia\&.h\&.
.SS "\fBKSDS3D_HRTF_FILTER_VERSION\fP KSDS3D_HRTF_FILTER_FORMAT_MSG::Version"

.PP
Definition at line 869 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
