.TH "KSNODEPROPERTY_AUDIO_DEV_SPECIFIC" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSNODEPROPERTY_AUDIO_DEV_SPECIFIC \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSNODEPROPERTY\fP \fBNodeProperty\fP"
.br
.ti -1c
.RI "ULONG \fBDevSpecificId\fP"
.br
.ti -1c
.RI "ULONG \fBDeviceInfo\fP"
.br
.ti -1c
.RI "ULONG \fBLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1871 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSNODEPROPERTY_AUDIO_DEV_SPECIFIC::DeviceInfo"

.PP
Definition at line 1874 of file ksmedia\&.h\&.
.SS "ULONG KSNODEPROPERTY_AUDIO_DEV_SPECIFIC::DevSpecificId"

.PP
Definition at line 1873 of file ksmedia\&.h\&.
.SS "ULONG KSNODEPROPERTY_AUDIO_DEV_SPECIFIC::Length"

.PP
Definition at line 1875 of file ksmedia\&.h\&.
.SS "\fBKSNODEPROPERTY\fP KSNODEPROPERTY_AUDIO_DEV_SPECIFIC::NodeProperty"

.PP
Definition at line 1872 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
