.TH "KSPIN_PHYSICALCONNECTION" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPIN_PHYSICALCONNECTION \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ks\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBSize\fP"
.br
.ti -1c
.RI "ULONG \fBPin\fP"
.br
.ti -1c
.RI "WCHAR \fBSymbolicLinkName\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 839 of file ks\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSPIN_PHYSICALCONNECTION::Pin"

.PP
Definition at line 841 of file ks\&.h\&.
.SS "ULONG KSPIN_PHYSICALCONNECTION::Size"

.PP
Definition at line 840 of file ks\&.h\&.
.SS "WCHAR KSPIN_PHYSICALCONNECTION::SymbolicLinkName[1]"

.PP
Definition at line 842 of file ks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
