.TH "KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSNODEPROPERTY\fP \fBNodeProperty\fP"
.br
.ti -1c
.RI "LONG \fBlOcularFocalLength\fP"
.br
.ti -1c
.RI "LONG \fBlObjectiveFocalLengthMin\fP"
.br
.ti -1c
.RI "LONG \fBlObjectiveFocalLengthMax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3535 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "LONG KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S::lObjectiveFocalLengthMax"

.PP
Definition at line 3539 of file ksmedia\&.h\&.
.SS "LONG KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S::lObjectiveFocalLengthMin"

.PP
Definition at line 3538 of file ksmedia\&.h\&.
.SS "LONG KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S::lOcularFocalLength"

.PP
Definition at line 3537 of file ksmedia\&.h\&.
.SS "\fBKSNODEPROPERTY\fP KSPROPERTY_CAMERACONTROL_NODE_FOCAL_LENGTH_S::NodeProperty"

.PP
Definition at line 3536 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
