.TH "KSPROPERTY_VIDEODECODER_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_VIDEODECODER_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSPROPERTY\fP \fBProperty\fP"
.br
.ti -1c
.RI "ULONG \fBValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3457 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSPROPERTY\fP KSPROPERTY_VIDEODECODER_S::Property"

.PP
Definition at line 3458 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_VIDEODECODER_S::Value"

.PP
Definition at line 3459 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
