.TH "KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSPROPERTY\fP \fBProperty\fP"
.br
.ti -1c
.RI "ULONG \fBStreamIndex\fP"
.br
.ti -1c
.RI "ULONG \fBRangeIndex\fP"
.br
.ti -1c
.RI "SIZE \fBDimensions\fP"
.br
.ti -1c
.RI "LONGLONG \fBCurrentActualFrameRate\fP"
.br
.ti -1c
.RI "LONGLONG \fBCurrentMaxAvailableFrameRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4083 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "LONGLONG KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::CurrentActualFrameRate"

.PP
Definition at line 4088 of file ksmedia\&.h\&.
.SS "LONGLONG KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::CurrentMaxAvailableFrameRate"

.PP
Definition at line 4089 of file ksmedia\&.h\&.
.SS "SIZE KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::Dimensions"

.PP
Definition at line 4087 of file ksmedia\&.h\&.
.SS "\fBKSPROPERTY\fP KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::Property"

.PP
Definition at line 4084 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::RangeIndex"

.PP
Definition at line 4086 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_VIDEOCONTROL_ACTUAL_FRAME_RATE_S::StreamIndex"

.PP
Definition at line 4085 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
