.TH "KSPROPERTY_CAMERACONTROL_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_CAMERACONTROL_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSPROPERTY\fP \fBProperty\fP"
.br
.ti -1c
.RI "LONG \fBValue\fP"
.br
.ti -1c
.RI "ULONG \fBFlags\fP"
.br
.ti -1c
.RI "ULONG \fBCapabilities\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3498 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSPROPERTY_CAMERACONTROL_S::Capabilities"

.PP
Definition at line 3502 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_CAMERACONTROL_S::Flags"

.PP
Definition at line 3501 of file ksmedia\&.h\&.
.SS "\fBKSPROPERTY\fP KSPROPERTY_CAMERACONTROL_S::Property"

.PP
Definition at line 3499 of file ksmedia\&.h\&.
.SS "LONG KSPROPERTY_CAMERACONTROL_S::Value"

.PP
Definition at line 3500 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
