.TH "KSPRIORITY" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPRIORITY \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ks\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBPriorityClass\fP"
.br
.ti -1c
.RI "ULONG \fBPrioritySubClass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file ks\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSPRIORITY::PriorityClass"

.PP
Definition at line 79 of file ks\&.h\&.
.SS "ULONG KSPRIORITY::PrioritySubClass"

.PP
Definition at line 80 of file ks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
