.TH "KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSPROPERTY\fP \fBProperty\fP"
.br
.ti -1c
.RI "\fBVBICODECFILTERING_STATISTICS_CC\fP \fBStatistics\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2999 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSPROPERTY\fP KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_S::Property"

.PP
Definition at line 3000 of file ksmedia\&.h\&.
.SS "\fBVBICODECFILTERING_STATISTICS_CC\fP KSPROPERTY_VBICODECFILTERING_STATISTICS_CC_S::Statistics"

.PP
Definition at line 3001 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
