.TH "KSPROPERTY_CROSSBAR_PININFO_S" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSPROPERTY_CROSSBAR_PININFO_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSPROPERTY\fP \fBProperty\fP"
.br
.ti -1c
.RI "\fBKSPIN_DATAFLOW\fP \fBDirection\fP"
.br
.ti -1c
.RI "ULONG \fBIndex\fP"
.br
.ti -1c
.RI "ULONG \fBPinType\fP"
.br
.ti -1c
.RI "ULONG \fBRelatedPinIndex\fP"
.br
.ti -1c
.RI "\fBKSPIN_MEDIUM\fP \fBMedium\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3817 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKSPIN_DATAFLOW\fP KSPROPERTY_CROSSBAR_PININFO_S::Direction"

.PP
Definition at line 3819 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_CROSSBAR_PININFO_S::Index"

.PP
Definition at line 3820 of file ksmedia\&.h\&.
.SS "\fBKSPIN_MEDIUM\fP KSPROPERTY_CROSSBAR_PININFO_S::Medium"

.PP
Definition at line 3823 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_CROSSBAR_PININFO_S::PinType"

.PP
Definition at line 3821 of file ksmedia\&.h\&.
.SS "\fBKSPROPERTY\fP KSPROPERTY_CROSSBAR_PININFO_S::Property"

.PP
Definition at line 3818 of file ksmedia\&.h\&.
.SS "ULONG KSPROPERTY_CROSSBAR_PININFO_S::RelatedPinIndex"

.PP
Definition at line 3822 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
