.TH "KSSTREAMALLOCATOR_STATUS" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSSTREAMALLOCATOR_STATUS \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ks\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSALLOCATOR_FRAMING\fP \fBFraming\fP"
.br
.ti -1c
.RI "ULONG \fBAllocatedFrames\fP"
.br
.ti -1c
.RI "ULONG \fBReserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1547 of file ks\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSSTREAMALLOCATOR_STATUS::AllocatedFrames"

.PP
Definition at line 1549 of file ks\&.h\&.
.SS "\fBKSALLOCATOR_FRAMING\fP KSSTREAMALLOCATOR_STATUS::Framing"

.PP
Definition at line 1548 of file ks\&.h\&.
.SS "ULONG KSSTREAMALLOCATOR_STATUS::Reserved"

.PP
Definition at line 1550 of file ks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
