.TH "KSWAVE_OUTPUT_CAPABILITIES" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KSWAVE_OUTPUT_CAPABILITIES \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBMaximumChannelsPerConnection\fP"
.br
.ti -1c
.RI "ULONG \fBMinimumBitsPerSample\fP"
.br
.ti -1c
.RI "ULONG \fBMaximumBitsPerSample\fP"
.br
.ti -1c
.RI "ULONG \fBMinimumSampleFrequency\fP"
.br
.ti -1c
.RI "ULONG \fBMaximumSampleFrequency\fP"
.br
.ti -1c
.RI "ULONG \fBTotalConnections\fP"
.br
.ti -1c
.RI "ULONG \fBStaticConnections\fP"
.br
.ti -1c
.RI "ULONG \fBStreamingConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActiveConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActiveStaticConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActiveStreamingConnections\fP"
.br
.ti -1c
.RI "ULONG \fBTotal3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBStatic3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBStreaming3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActive3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActiveStatic3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBActiveStreaming3DConnections\fP"
.br
.ti -1c
.RI "ULONG \fBTotalSampleMemory\fP"
.br
.ti -1c
.RI "ULONG \fBFreeSampleMemory\fP"
.br
.ti -1c
.RI "ULONG \fBLargestFreeContiguousSampleMemory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1682 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::Active3DConnections"

.PP
Definition at line 1697 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::ActiveConnections"

.PP
Definition at line 1691 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::ActiveStatic3DConnections"

.PP
Definition at line 1698 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::ActiveStaticConnections"

.PP
Definition at line 1692 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::ActiveStreaming3DConnections"

.PP
Definition at line 1699 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::ActiveStreamingConnections"

.PP
Definition at line 1693 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::FreeSampleMemory"

.PP
Definition at line 1701 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::LargestFreeContiguousSampleMemory"

.PP
Definition at line 1702 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::MaximumBitsPerSample"

.PP
Definition at line 1685 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::MaximumChannelsPerConnection"

.PP
Definition at line 1683 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::MaximumSampleFrequency"

.PP
Definition at line 1687 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::MinimumBitsPerSample"

.PP
Definition at line 1684 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::MinimumSampleFrequency"

.PP
Definition at line 1686 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::Static3DConnections"

.PP
Definition at line 1695 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::StaticConnections"

.PP
Definition at line 1689 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::Streaming3DConnections"

.PP
Definition at line 1696 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::StreamingConnections"

.PP
Definition at line 1690 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::Total3DConnections"

.PP
Definition at line 1694 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::TotalConnections"

.PP
Definition at line 1688 of file ksmedia\&.h\&.
.SS "ULONG KSWAVE_OUTPUT_CAPABILITIES::TotalSampleMemory"

.PP
Definition at line 1700 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
