.TH "LadspaEffectDialog" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LadspaEffectDialog \- Dialog used with \fBEffect\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Dialog used with \fBEffect\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
