.TH "LadspaEffectMeter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LadspaEffectMeter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLadspaEffectMeter\fP (wxWindow *parent, \fBconst\fP float &val, float \fBmin\fP, float \fBmax\fP)"
.br
.ti -1c
.RI "virtual \fB~LadspaEffectMeter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 425 of file LadspaEffect\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LadspaEffectMeter::LadspaEffectMeter (wxWindow * parent, \fBconst\fP float & val, float min, float max)"

.PP
Definition at line 453 of file LadspaEffect\&.cpp\&.
.SS "LadspaEffectMeter::~LadspaEffectMeter ()\fC [virtual]\fP"

.PP
Definition at line 464 of file LadspaEffect\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
