.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/ladspa/LadspaEffect.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/ladspa/LadspaEffect.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./Audacity\&.h'\fP
.br
\fC#include 'ladspa\&.h'\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <wx/wxprec\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/dcbuffer\&.h>\fP
.br
\fC#include <wx/dcclient\&.h>\fP
.br
\fC#include <wx/dynlib\&.h>\fP
.br
\fC#include <wx/filename\&.h>\fP
.br
\fC#include <wx/log\&.h>\fP
.br
\fC#include <wx/menu\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/slider\&.h>\fP
.br
\fC#include <wx/statbox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/tokenzr\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/scrolwin\&.h>\fP
.br
\fC#include <wx/version\&.h>\fP
.br
\fC#include 'LadspaEffect\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./Internat\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./widgets/valnum\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLadspaEffectOptionsDialog\fP"
.br
.ti -1c
.RI "class \fBLadspaEffectMeter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBID_Duration\fP = 20000, \fBID_Toggles\fP = 21000, \fBID_Sliders\fP = 22000, \fBID_Texts\fP = 23000 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDECLARE_MODULE_ENTRY\fP (AudacityModule)"
.br
.ti -1c
.RI "\fBDECLARE_BUILTIN_MODULE\fP (LadspaBuiltin)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIID_Duration \fP\fP
.TP
\fB\fIID_Toggles \fP\fP
.TP
\fB\fIID_Sliders \fP\fP
.TP
\fB\fIID_Texts \fP\fP
.PP
Definition at line 411 of file LadspaEffect\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "DECLARE_BUILTIN_MODULE (LadspaBuiltin)"

.SS "DECLARE_MODULE_ENTRY (AudacityModule)"

.PP
Definition at line 73 of file LadspaEffect\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
