.TH "lame_version_t" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lame_version_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmajor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBminor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBalpha\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbeta\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpsy_major\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpsy_minor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpsy_alpha\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpsy_beta\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBfeatures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 490 of file lame\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP lame_version_t::alpha"

.PP
Definition at line 494 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::beta"

.PP
Definition at line 495 of file lame\&.h\&.
.SS "\fBconst\fP char* lame_version_t::features"

.PP
Definition at line 504 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::major"

.PP
Definition at line 492 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::minor"

.PP
Definition at line 493 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::psy_alpha"

.PP
Definition at line 500 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::psy_beta"

.PP
Definition at line 501 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::psy_major"

.PP
Definition at line 498 of file lame\&.h\&.
.SS "\fBint\fP lame_version_t::psy_minor"

.PP
Definition at line 499 of file lame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
