.TH "lavc_codec" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lavc_codec \- Codecs
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBNative Codecs\fP"
.br
.ti -1c
.RI "\fBExternal library wrappers\fP"
.br
.ti -1c
.RI "\fBHardware Accelerators bridge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
