.TH "lavu_md5" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lavu_md5 \- MD5
.SS "Functions"

.in +1c
.ti -1c
.RI "struct AVMD5 * \fBav_md5_alloc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_md5_init\fP (struct AVMD5 *ctx)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_md5_update\fP (struct AVMD5 *ctx, \fBconst\fP \fBuint8_t\fP *src, \fBint\fP \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_md5_final\fP (struct AVMD5 *ctx, \fBuint8_t\fP *dst)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_md5_sum\fP (\fBuint8_t\fP *dst, \fBconst\fP \fBuint8_t\fP *src, \fBconst\fP \fBint\fP \fBlen\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBint\fP \fBav_md5_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "struct AVMD5* av_md5_alloc (\fBvoid\fP)"
Allocate an AVMD5 context\&. 
.SS "\fBvoid\fP av_md5_final (struct AVMD5 * ctx, \fBuint8_t\fP * dst)"
Finish hashing and output digest value\&.
.PP
\fBParameters:\fP
.RS 4
\fIctx\fP hash function context 
.br
\fIdst\fP buffer where output digest value is stored 
.RE
.PP

.SS "\fBvoid\fP av_md5_init (struct AVMD5 * ctx)"
Initialize MD5 hashing\&.
.PP
\fBParameters:\fP
.RS 4
\fIctx\fP pointer to the function context (of size av_md5_size) 
.RE
.PP

.SS "\fBvoid\fP av_md5_sum (\fBuint8_t\fP * dst, \fBconst\fP \fBuint8_t\fP * src, \fBconst\fP \fBint\fP len)"
Hash an array of data\&.
.PP
\fBParameters:\fP
.RS 4
\fIdst\fP The output buffer to write the digest into 
.br
\fIsrc\fP The data to hash 
.br
\fIlen\fP The length of the data, in bytes 
.RE
.PP

.SS "\fBvoid\fP av_md5_update (struct AVMD5 * ctx, \fBconst\fP \fBuint8_t\fP * src, \fBint\fP len)"
Update hash value\&.
.PP
\fBParameters:\fP
.RS 4
\fIctx\fP hash function context 
.br
\fIsrc\fP input data to update hash with 
.br
\fIlen\fP input data length 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP \fBint\fP av_md5_size"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
