.TH "Lilv::World" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lilv::World \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lilvmm\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorld\fP ()"
.br
.ti -1c
.RI "\fB~World\fP ()"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBnew_uri\fP (\fBconst\fP char *\fBuri\fP)"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBnew_string\fP (\fBconst\fP char *\fBstr\fP)"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBnew_int\fP (\fBint\fP val)"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBnew_float\fP (float val)"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBnew_bool\fP (\fBbool\fP val)"
.br
.ti -1c
.RI "\fBNodes\fP \fBfind_nodes\fP (\fBconst\fP \fBLilvNode\fP *subject, \fBconst\fP \fBLilvNode\fP *\fBpredicate\fP, \fBconst\fP \fBLilvNode\fP *object)"
.br
.ti -1c
.RI "\fBLILV_WRAP2_VOID\fP (world, set_option, \fBconst\fP char *, \fBuri\fP, \fBLilvNode\fP *, \fBvalue\fP)"
.br
.ti -1c
.RI "\fBLILV_WRAP0_VOID\fP (world, load_all)"
.br
.ti -1c
.RI "\fBLILV_WRAP1_VOID\fP (world, load_bundle, \fBLilvNode\fP *, bundle_uri)"
.br
.ti -1c
.RI "\fBLILV_WRAP0\fP (\fBconst\fP \fBLilvPluginClass\fP *, world, get_plugin_class)"
.br
.ti -1c
.RI "\fBLILV_WRAP0\fP (\fBconst\fP \fBLilvPluginClasses\fP *, world, get_plugin_classes)"
.br
.ti -1c
.RI "\fBLILV_WRAP0\fP (\fBconst\fP \fBPlugins\fP, world, get_all_plugins)"
.br
.ti -1c
.RI "\fBLILV_WRAP1\fP (\fBint\fP, world, load_resource, \fBconst\fP \fBLilvNode\fP *, resource)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLilvWorld\fP * \fBme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 306 of file lilvmm\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lilv::World::World ()\fC [inline]\fP"

.PP
Definition at line 307 of file lilvmm\&.hpp\&.
.SS "Lilv::World::~World ()\fC [inline]\fP"

.PP
Definition at line 308 of file lilvmm\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNodes\fP Lilv::World::find_nodes (\fBconst\fP \fBLilvNode\fP * subject, \fBconst\fP \fBLilvNode\fP * predicate, \fBconst\fP \fBLilvNode\fP * object)\fC [inline]\fP"

.PP
Definition at line 325 of file lilvmm\&.hpp\&.
.SS "Lilv::World::LILV_WRAP0 (\fBconst\fP \fBLilvPluginClass\fP *, world, get_plugin_class)"

.SS "Lilv::World::LILV_WRAP0 (\fBconst\fP \fBLilvPluginClasses\fP *, world, get_plugin_classes)"

.SS "Lilv::World::LILV_WRAP0 (\fBconst\fP \fBPlugins\fP, world, get_all_plugins)"

.SS "Lilv::World::LILV_WRAP0_VOID (world, load_all)"

.SS "Lilv::World::LILV_WRAP1 (\fBint\fP, world, load_resource, \fBconst\fP \fBLilvNode\fP *, resource)"

.SS "Lilv::World::LILV_WRAP1_VOID (world, load_bundle, \fBLilvNode\fP *, bundle_uri)"

.SS "Lilv::World::LILV_WRAP2_VOID (world, set_option, \fBconst\fP char *, \fBuri\fP, \fBLilvNode\fP *, \fBvalue\fP)"

.SS "\fBLilvNode\fP* Lilv::World::new_bool (\fBbool\fP val)\fC [inline]\fP"

.PP
Definition at line 322 of file lilvmm\&.hpp\&.
.SS "\fBLilvNode\fP* Lilv::World::new_float (float val)\fC [inline]\fP"

.PP
Definition at line 319 of file lilvmm\&.hpp\&.
.SS "\fBLilvNode\fP* Lilv::World::new_int (\fBint\fP val)\fC [inline]\fP"

.PP
Definition at line 316 of file lilvmm\&.hpp\&.
.SS "\fBLilvNode\fP* Lilv::World::new_string (\fBconst\fP char * str)\fC [inline]\fP"

.PP
Definition at line 313 of file lilvmm\&.hpp\&.
.SS "\fBLilvNode\fP* Lilv::World::new_uri (\fBconst\fP char * uri)\fC [inline]\fP"

.PP
Definition at line 310 of file lilvmm\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLilvWorld\fP* Lilv::World::me"

.PP
Definition at line 339 of file lilvmm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
