.TH "LilvNodeImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LilvNodeImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lilv_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLilvWorld\fP * \fBworld\fP"
.br
.ti -1c
.RI "\fBSordNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "\fBLilvNodeType\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBint\fP \fBint_val\fP"
.br
.ti -1c
.RI "   float \fBfloat_val\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBbool_val\fP"
.br
.ti -1c
.RI "} \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file lilv_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP LilvNodeImpl::bool_val"

.PP
Definition at line 212 of file lilv_internal\&.h\&.
.SS "float LilvNodeImpl::float_val"

.PP
Definition at line 211 of file lilv_internal\&.h\&.
.SS "\fBint\fP LilvNodeImpl::int_val"

.PP
Definition at line 210 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvNodeImpl::node"

.PP
Definition at line 207 of file lilv_internal\&.h\&.
.SS "\fBLilvNodeType\fP LilvNodeImpl::type"

.PP
Definition at line 208 of file lilv_internal\&.h\&.
.SS "union { \&.\&.\&. }   LilvNodeImpl::val"

.SS "\fBLilvWorld\fP* LilvNodeImpl::world"

.PP
Definition at line 206 of file lilv_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
