.TH "LilvWorldImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LilvWorldImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lilv_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSordWorld\fP * \fBworld\fP"
.br
.ti -1c
.RI "\fBSordModel\fP * \fBmodel\fP"
.br
.ti -1c
.RI "\fBSerdReader\fP * \fBreader\fP"
.br
.ti -1c
.RI "unsigned \fBn_read_files\fP"
.br
.ti -1c
.RI "\fBLilvPluginClass\fP * \fBlv2_plugin_class\fP"
.br
.ti -1c
.RI "\fBLilvPluginClasses\fP * \fBplugin_classes\fP"
.br
.ti -1c
.RI "\fBLilvSpec\fP * \fBspecs\fP"
.br
.ti -1c
.RI "\fBLilvPlugins\fP * \fBplugins\fP"
.br
.ti -1c
.RI "\fBLilvNodes\fP * \fBloaded_files\fP"
.br
.ti -1c
.RI "\fBZixTree\fP * \fBlibs\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBdc_replaces\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBdman_DynManifest\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBdoap_name\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_Plugin\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_Specification\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_appliesTo\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_binary\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_default\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_designation\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_extensionData\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_index\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_latency\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_maximum\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_minimum\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_name\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_optionalFeature\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_port\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_portProperty\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_reportsLatency\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_requiredFeature\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_symbol\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBlv2_prototype\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBnull_uri\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBpset_value\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_a\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_value\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdfs_Class\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdfs_label\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdfs_seeAlso\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdfs_subClassOf\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_base64Binary\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_boolean\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_decimal\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_double\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_integer\fP"
.br
.ti -1c
.RI "} \fBuris\fP"
.br
.ti -1c
.RI "\fBLilvOptions\fP \fBopt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file lilv_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSordNode\fP* LilvWorldImpl::dc_replaces"

.PP
Definition at line 156 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::dman_DynManifest"

.PP
Definition at line 157 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::doap_name"

.PP
Definition at line 158 of file lilv_internal\&.h\&.
.SS "\fBZixTree\fP* LilvWorldImpl::libs"

.PP
Definition at line 154 of file lilv_internal\&.h\&.
.SS "\fBLilvNodes\fP* LilvWorldImpl::loaded_files"

.PP
Definition at line 153 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_appliesTo"

.PP
Definition at line 161 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_binary"

.PP
Definition at line 162 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_default"

.PP
Definition at line 163 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_designation"

.PP
Definition at line 164 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_extensionData"

.PP
Definition at line 165 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_index"

.PP
Definition at line 166 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_latency"

.PP
Definition at line 167 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_maximum"

.PP
Definition at line 168 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_minimum"

.PP
Definition at line 169 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_name"

.PP
Definition at line 170 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_optionalFeature"

.PP
Definition at line 171 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_Plugin"

.PP
Definition at line 159 of file lilv_internal\&.h\&.
.SS "\fBLilvPluginClass\fP* LilvWorldImpl::lv2_plugin_class"

.PP
Definition at line 149 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_port"

.PP
Definition at line 172 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_portProperty"

.PP
Definition at line 173 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_prototype"

.PP
Definition at line 177 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_reportsLatency"

.PP
Definition at line 174 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_requiredFeature"

.PP
Definition at line 175 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_Specification"

.PP
Definition at line 160 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::lv2_symbol"

.PP
Definition at line 176 of file lilv_internal\&.h\&.
.SS "\fBSordModel\fP* LilvWorldImpl::model"

.PP
Definition at line 146 of file lilv_internal\&.h\&.
.SS "unsigned LilvWorldImpl::n_read_files"

.PP
Definition at line 148 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::null_uri"

.PP
Definition at line 178 of file lilv_internal\&.h\&.
.SS "\fBLilvOptions\fP LilvWorldImpl::opt"

.PP
Definition at line 192 of file lilv_internal\&.h\&.
.SS "\fBLilvPluginClasses\fP* LilvWorldImpl::plugin_classes"

.PP
Definition at line 150 of file lilv_internal\&.h\&.
.SS "\fBLilvPlugins\fP* LilvWorldImpl::plugins"

.PP
Definition at line 152 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::pset_value"

.PP
Definition at line 179 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdf_a"

.PP
Definition at line 180 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdf_value"

.PP
Definition at line 181 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdfs_Class"

.PP
Definition at line 182 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdfs_label"

.PP
Definition at line 183 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdfs_seeAlso"

.PP
Definition at line 184 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::rdfs_subClassOf"

.PP
Definition at line 185 of file lilv_internal\&.h\&.
.SS "\fBSerdReader\fP* LilvWorldImpl::reader"

.PP
Definition at line 147 of file lilv_internal\&.h\&.
.SS "\fBLilvSpec\fP* LilvWorldImpl::specs"

.PP
Definition at line 151 of file lilv_internal\&.h\&.
.SS "struct { \&.\&.\&. }   LilvWorldImpl::uris"

.SS "\fBSordWorld\fP* LilvWorldImpl::world"

.PP
Definition at line 145 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::xsd_base64Binary"

.PP
Definition at line 186 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::xsd_boolean"

.PP
Definition at line 187 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::xsd_decimal"

.PP
Definition at line 188 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::xsd_double"

.PP
Definition at line 189 of file lilv_internal\&.h\&.
.SS "\fBSordNode\fP* LilvWorldImpl::xsd_integer"

.PP
Definition at line 190 of file lilv_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
