.TH "LilvLib" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LilvLib \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lilv_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLilvWorld\fP * \fBworld\fP"
.br
.ti -1c
.RI "\fBLilvNode\fP * \fBuri\fP"
.br
.ti -1c
.RI "char * \fBbundle_path\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBlib\fP"
.br
.ti -1c
.RI "\fBLV2_Descriptor_Function\fP \fBlv2_descriptor\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBrefs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file lilv_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* LilvLib::bundle_path"

.PP
Definition at line 102 of file lilv_internal\&.h\&.
.SS "\fBvoid\fP* LilvLib::lib"

.PP
Definition at line 103 of file lilv_internal\&.h\&.
.SS "\fBLV2_Descriptor_Function\fP LilvLib::lv2_descriptor"

.PP
Definition at line 104 of file lilv_internal\&.h\&.
.SS "\fBuint32_t\fP LilvLib::refs"

.PP
Definition at line 108 of file lilv_internal\&.h\&.
.SS "\fBLilvNode\fP* LilvLib::uri"

.PP
Definition at line 101 of file lilv_internal\&.h\&.
.SS "\fBLilvWorld\fP* LilvLib::world"

.PP
Definition at line 100 of file lilv_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
