.TH "literasc" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
literasc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBformat_text\fP (text)"
.br
.ti -1c
.RI "def \fBformat_code\fP (lang, code)"
.br
.ti -1c
.RI "def \fBformat_c_source\fP (\fBfilename\fP, file)"
.br
.ti -1c
.RI "def \fBformat_ttl_source\fP (\fBfilename\fP, file)"
.br
.ti -1c
.RI "def \fBgen\fP (\fBout\fP, \fBfilenames\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def literasc\&.format_c_source ( filename,  file)"

.PP
Definition at line 28 of file literasc\&.py\&.
.SS "def literasc\&.format_code ( lang,  code)"

.PP
Definition at line 20 of file literasc\&.py\&.
.SS "def literasc\&.format_text ( text)"

.PP
Definition at line 16 of file literasc\&.py\&.
.SS "def literasc\&.format_ttl_source ( filename,  file)"

.PP
Definition at line 74 of file literasc\&.py\&.
.SS "def literasc\&.gen ( out,  filenames)"

.PP
Definition at line 101 of file literasc\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
