.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/local.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/local.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'samples\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'sine\&.h'\fP
.br
\fC#include 'stkinit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBlocalinit\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlocalsymbols\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint_local_gc_info\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBLVAL\fP \fBRSLT_sym\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsample_block_total\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsample_block_used\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP localinit (\fBvoid\fP)"

.PP
Definition at line 20 of file local\&.c\&.
.SS "\fBvoid\fP localsymbols (\fBvoid\fP)"

.PP
Definition at line 33 of file local\&.c\&.
.SS "\fBvoid\fP print_local_gc_info (\fBvoid\fP)"

.PP
Definition at line 46 of file local\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBLVAL\fP RSLT_sym"

.PP
Definition at line 18 of file local\&.c\&.
.SS "\fBint\fP sample_block_total"

.PP
Definition at line 18 of file falloc\&.c\&.
.SS "\fBint\fP sample_block_used"

.PP
Definition at line 16 of file falloc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
