.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/plugin_xmms/locale_hack.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/plugin_xmms/locale_hack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <locale\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtextdomain\fP(String)   (String)"
.br
.ti -1c
.RI "#define \fBgettext\fP(String)   (String)"
.br
.ti -1c
.RI "#define \fBdgettext\fP(Domain,  Message)   (Message)"
.br
.ti -1c
.RI "#define \fBdcgettext\fP(Domain,  Message,  Type)   (Message)"
.br
.ti -1c
.RI "#define \fBbindtextdomain\fP(Domain,  Directory)   (Domain)"
.br
.ti -1c
.RI "#define \fB_\fP(String)   (String)"
.br
.ti -1c
.RI "#define \fBN_\fP(String)   (String)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _(String)   (String)"

.PP
Definition at line 51 of file locale_hack\&.h\&.
.SS "#define bindtextdomain(Domain, Directory)   (Domain)"

.PP
Definition at line 50 of file locale_hack\&.h\&.
.SS "#define dcgettext(Domain, Message, Type)   (Message)"

.PP
Definition at line 49 of file locale_hack\&.h\&.
.SS "#define dgettext(Domain, Message)   (Message)"

.PP
Definition at line 48 of file locale_hack\&.h\&.
.SS "#define gettext(String)   (String)"

.PP
Definition at line 47 of file locale_hack\&.h\&.
.SS "#define N_(String)   (String)"

.PP
Definition at line 52 of file locale_hack\&.h\&.
.SS "#define textdomain(String)   (String)"

.PP
Definition at line 46 of file locale_hack\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
