.TH "LOFImportPlugin" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LOFImportPlugin \- An \fBImportPlugin\fP for LOF data\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBImportPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLOFImportPlugin\fP ()"
.br
.ti -1c
.RI "\fB~LOFImportPlugin\fP ()"
.br
.ti -1c
.RI "wxString \fBGetPluginStringID\fP ()"
.br
.ti -1c
.RI "wxString \fBGetPluginFormatDescription\fP ()"
.br
.ti -1c
.RI "\fBImportFileHandle\fP * \fBOpen\fP (\fBconst\fP wxString &Filename) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBImportPlugin\fP for LOF data\&. 
.PP
Definition at line 104 of file ImportLOF\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LOFImportPlugin::LOFImportPlugin ()\fC [inline]\fP"

.PP
Definition at line 107 of file ImportLOF\&.cpp\&.
.SS "LOFImportPlugin::~LOFImportPlugin ()\fC [inline]\fP"

.PP
Definition at line 112 of file ImportLOF\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "wxString LOFImportPlugin::GetPluginFormatDescription ()\fC [virtual]\fP"

.PP
Implements \fBImportPlugin\fP\&.
.PP
Definition at line 179 of file ImportLOF\&.cpp\&.
.SS "wxString LOFImportPlugin::GetPluginStringID ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBImportPlugin\fP\&.
.PP
Definition at line 114 of file ImportLOF\&.cpp\&.
.SS "\fBImportFileHandle\fP * LOFImportPlugin::Open (\fBconst\fP wxString & Filename)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBImportPlugin\fP\&.
.PP
Definition at line 184 of file ImportLOF\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
