.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/lpanal.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/lpanal.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBabs_max\fP (double *x, long desde, long hasta, double *x_maxptr, long *indptr)"
.br
.ti -1c
.RI "\fBvoid\fP \fBxcorr\fP (double *\fBs\fP, double *rxx, long \fBN\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBsnd_lpanal\fP (\fBLVAL\fP w, long P)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP abs_max (double * x, long desde, long hasta, double * x_maxptr, long * indptr)"

.PP
Definition at line 11 of file lpanal\&.c\&.
.SS "\fBLVAL\fP snd_lpanal (\fBLVAL\fP w, long P)"
Durbin algorithm
.PP
inicialization
.PP
recursive solve 
.PP
Definition at line 70 of file lpanal\&.c\&.
.SS "\fBvoid\fP xcorr (double * s, double * rxx, long N)"

.PP
Definition at line 31 of file lpanal\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
