.TH "LV2_Log_Logger" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LV2_Log_Logger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_Log_Log\fP * \fBlog\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBError\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBNote\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBTrace\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBWarning\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logger convenience API state\&. 
.PP
Definition at line 42 of file logger\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLV2_URID\fP LV2_Log_Logger::Error"

.PP
Definition at line 45 of file logger\&.h\&.
.SS "\fBLV2_Log_Log\fP* LV2_Log_Logger::log"

.PP
Definition at line 43 of file logger\&.h\&.
.SS "\fBLV2_URID\fP LV2_Log_Logger::Note"

.PP
Definition at line 46 of file logger\&.h\&.
.SS "\fBLV2_URID\fP LV2_Log_Logger::Trace"

.PP
Definition at line 47 of file logger\&.h\&.
.SS "\fBLV2_URID\fP LV2_Log_Logger::Warning"

.PP
Definition at line 48 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
