.TH "LV2_Atom_Property_Body" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LV2_Atom_Property_Body \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <atom\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBcontext\fP"
.br
.ti -1c
.RI "\fBLV2_Atom\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The body of an atom:\fBProperty\fP (e\&.g\&. in an atom:Object)\&. 
.PP
Definition at line 177 of file atom\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP LV2_Atom_Property_Body::context"
Context URID (may be, and generally is, 0)\&. 
.PP
Definition at line 179 of file atom\&.h\&.
.SS "\fBuint32_t\fP LV2_Atom_Property_Body::key"
Key (predicate) (mapped URI)\&. 
.PP
Definition at line 178 of file atom\&.h\&.
.SS "\fBLV2_Atom\fP LV2_Atom_Property_Body::value"
Value atom header\&. 
.PP
Definition at line 180 of file atom\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
