.TH "Lyrics" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lyrics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lyrics\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLyrics\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize)"
.br
.ti -1c
.RI "virtual \fB~Lyrics\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClear\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddLabels\fP (\fBconst\fP \fBLabelTrack\fP *pLT)"
.br
.ti -1c
.RI "\fBvoid\fP \fBFinish\fP (double finalT)"
.br
.ti -1c
.RI "\fBint\fP \fBFindSyllable\fP (long startChar)"
.br
.ti -1c
.RI "\fBint\fP \fBGetCurrentSyllableIndex\fP ()"
.br
.ti -1c
.RI "\fBSyllable\fP * \fBGetSyllable\fP (\fBint\fP nSyl)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCurrentSyllableIndex\fP (\fBint\fP nSyl)"
.br
.ti -1c
.RI "LyricsStyle \fBGetLyricsStyle\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetLyricsStyle\fP (\fBconst\fP LyricsStyle newLyricsStyle)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdate\fP (double \fBt\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnKeyEvent\fP (wxKeyEvent &event)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPaint\fP (wxPaintEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSize\fP (wxSizeEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBHandlePaint\fP (wxDC &dc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBHandlePaint_BouncingBall\fP (wxDC &dc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBHandleLayout\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file Lyrics\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lyrics::Lyrics (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP)"

.PP
Definition at line 83 of file Lyrics\&.cpp\&.
.SS "Lyrics::~Lyrics ()\fC [virtual]\fP"

.PP
Definition at line 115 of file Lyrics\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Lyrics::AddLabels (\fBconst\fP \fBLabelTrack\fP * pLT)"

.PP
Definition at line 135 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::Clear ()"

.PP
Definition at line 121 of file Lyrics\&.cpp\&.
.SS "\fBint\fP Lyrics::FindSyllable (long startChar)"

.PP
Definition at line 208 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::Finish (double finalT)"

.PP
Definition at line 190 of file Lyrics\&.cpp\&.
.SS "\fBint\fP Lyrics::GetCurrentSyllableIndex ()\fC [inline]\fP"

.PP
Definition at line 82 of file Lyrics\&.h\&.
.SS "LyricsStyle Lyrics::GetLyricsStyle ()\fC [inline]\fP"

.PP
Definition at line 86 of file Lyrics\&.h\&.
.SS "\fBSyllable\fP* Lyrics::GetSyllable (\fBint\fP nSyl)\fC [inline]\fP"

.PP
Definition at line 83 of file Lyrics\&.h\&.
.SS "\fBvoid\fP Lyrics::HandleLayout ()"

.SS "\fBvoid\fP Lyrics::HandlePaint (wxDC & dc)"

.PP
Definition at line 533 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::HandlePaint_BouncingBall (wxDC & dc)"

.PP
Definition at line 542 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::OnKeyEvent (wxKeyEvent & event)"

.PP
Definition at line 460 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::OnPaint (wxPaintEvent & evt)"

.PP
Definition at line 466 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::OnSize (wxSizeEvent & evt)"

.PP
Definition at line 497 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::SetCurrentSyllableIndex (\fBint\fP nSyl)\fC [inline]\fP"

.PP
Definition at line 84 of file Lyrics\&.h\&.
.SS "\fBvoid\fP Lyrics::SetLyricsStyle (\fBconst\fP LyricsStyle newLyricsStyle)"

.PP
Definition at line 230 of file Lyrics\&.cpp\&.
.SS "\fBvoid\fP Lyrics::Update (double t)"

.PP
Definition at line 420 of file Lyrics\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
