.TH "M68kXML_ParserStruct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
M68kXML_ParserStruct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <expat_68k\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBXML_Parser\fP \fBp\fP"
.br
.ti -1c
.RI "struct ExecIFace * \fBIExec\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBhandlerarg\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBextenthandlerarg\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBenchandlerarg\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBstartelementhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBendelementhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBchardatahandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBprocinsthandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBcommenthandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBstartcdatahandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBendcdatahandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBdefaulthandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBdefaulthandlerexp\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBextentrefhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBunknownenchandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBstartnamespacehandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBendnamespacehandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBxmldeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBstartdoctypehandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBenddoctypehandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBelementdeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBattlistdeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBentitydeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBunparseddeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBnotationdeclhandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBnotstandalonehandler\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBskippedentityhandler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file expat_68k\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* M68kXML_ParserStruct::attlistdeclhandler"

.PP
Definition at line 54 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::chardatahandler"

.PP
Definition at line 39 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::commenthandler"

.PP
Definition at line 41 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::defaulthandler"

.PP
Definition at line 44 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::defaulthandlerexp"

.PP
Definition at line 45 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::elementdeclhandler"

.PP
Definition at line 53 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::enchandlerarg"

.PP
Definition at line 36 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::endcdatahandler"

.PP
Definition at line 43 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::enddoctypehandler"

.PP
Definition at line 52 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::endelementhandler"

.PP
Definition at line 38 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::endnamespacehandler"

.PP
Definition at line 49 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::entitydeclhandler"

.PP
Definition at line 55 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::extenthandlerarg"

.PP
Definition at line 35 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::extentrefhandler"

.PP
Definition at line 46 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::handlerarg"

.PP
Definition at line 34 of file expat_68k\&.h\&.
.SS "struct ExecIFace* M68kXML_ParserStruct::IExec"

.PP
Definition at line 33 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::notationdeclhandler"

.PP
Definition at line 57 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::notstandalonehandler"

.PP
Definition at line 58 of file expat_68k\&.h\&.
.SS "\fBXML_Parser\fP M68kXML_ParserStruct::p"

.PP
Definition at line 32 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::procinsthandler"

.PP
Definition at line 40 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::skippedentityhandler"

.PP
Definition at line 59 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::startcdatahandler"

.PP
Definition at line 42 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::startdoctypehandler"

.PP
Definition at line 51 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::startelementhandler"

.PP
Definition at line 37 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::startnamespacehandler"

.PP
Definition at line 48 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::unknownenchandler"

.PP
Definition at line 47 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::unparseddeclhandler"

.PP
Definition at line 56 of file expat_68k\&.h\&.
.SS "\fBvoid\fP* M68kXML_ParserStruct::xmldeclhandler"

.PP
Definition at line 50 of file expat_68k\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
