.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/mac/MacCommandWin.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/mac/MacCommandWin.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSetSelection\fP (short \fBstart\fP, short \fBend\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmacputc\fP (\fBint\fP ch)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmacputs\fP (char *\fBs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPrepareForInput\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBInitalizeCmdWindow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateCmdWindow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBStopPasting\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDeleteRange\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBscrflush\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetScrollRect\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAdjustCursor\fP (Point theLoc, RgnHandle theRgn)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDoKeyPress\fP (EventRecord *theEvent)"
.br
.ti -1c
.RI "\fBvoid\fP \fBActivateCmdWindow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDeactivateCmdWindow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCleanupCmdWindow\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP ActivateCmdWindow (\fBvoid\fP)"

.PP
Definition at line 712 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP AdjustCursor (Point theLoc, RgnHandle theRgn)"

.PP
Definition at line 121 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP CleanupCmdWindow (\fBvoid\fP)"

.PP
Definition at line 758 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP DeactivateCmdWindow (\fBvoid\fP)"

.PP
Definition at line 719 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP DeleteRange (\fBvoid\fP)"

.PP
Definition at line 399 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP DoKeyPress (EventRecord * theEvent)"

.PP
Definition at line 233 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP InitalizeCmdWindow (\fBvoid\fP)"

.PP
Definition at line 726 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP macputc (\fBint\fP ch)"

.PP
Definition at line 634 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP macputs (char * s)"

.PP
Definition at line 654 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP PrepareForInput (\fBvoid\fP)"

.PP
Definition at line 388 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP scrflush (\fBvoid\fP)"

.PP
Definition at line 659 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP SetScrollRect (\fBvoid\fP)"

.PP
Definition at line 185 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP SetSelection (short start, short end)"

.PP
Definition at line 288 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP StopPasting (\fBvoid\fP)"

.PP
Definition at line 313 of file MacCommandWin\&.c\&.
.SS "\fBvoid\fP UpdateCmdWindow (\fBvoid\fP)"

.PP
Definition at line 677 of file MacCommandWin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
