.TH "C:/_dev/OpenU/Audacity/audacity/src/MacroMagic.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/MacroMagic.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Theme\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTHEME_EXTERNS\fP"
.br
.ti -1c
.RI "#define \fBDEFINE_IMAGE\fP(\fBname\fP,  initialiser,  textual_name)   extern AUDACITY_DLL_API \fBteBmps\fP \fBname\fP;"
.br
.ti -1c
.RI "#define \fBDEFINE_COLOUR\fP(\fBname\fP,  initialiser,  textual_name)   extern AUDACITY_DLL_API \fBint\fP \fBname\fP;"
.br
.ti -1c
.RI "#define \fBDEFINE_FONT\fP(\fBname\fP,  initialiser,  textual_name)   extern AUDACITY_DLL_API \fBint\fP \fBname\fP;"
.br
.ti -1c
.RI "#define \fBSET_THEME_FLAGS\fP(flags)"
.br
.ti -1c
.RI "#define \fBTHEME_EXTERNS\fP"
.br
.ti -1c
.RI "#define \fBDEFINE_IMAGE\fP(\fBname\fP,  initialiser,  textual_name)   theTheme\&.RegisterImage( \fBname\fP, initialiser, textual_name );"
.br
.ti -1c
.RI "#define \fBDEFINE_COLOUR\fP(\fBname\fP,  initialiser,  textual_name)   theTheme\&.RegisterColour( \fBname\fP, initialiser, textual_name );"
.br
.ti -1c
.RI "#define \fBDEFINE_FONT\fP(\fBname\fP,  initialiser,  textual_name)   theTheme\&.RegisterFont( \fBname\fP, initialiser, textual_name );"
.br
.ti -1c
.RI "#define \fBSET_THEME_FLAGS\fP(flags)   theTheme\&.SetFlags(  flags );"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file allows the same macros to do multiple duty by undefining and redefining the macros\&.
.PP
For example DEFINE_IMAGE will generate:
.PP
.IP "\(bu" 2
extern int name;
.IP "\(bu" 2
int name = -1;
.IP "\(bu" 2
RegisterImage( name, initiialiser, textual_name);
.PP
.PP
On three different passes\&. We control which by defining one of THEME_INITS or THEME_DECLARATIONS or neither of these\&.
.PP
Definition in file \fBMacroMagic\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFINE_COLOUR(\fBname\fP, initialiser, textual_name)   theTheme\&.RegisterColour( \fBname\fP, initialiser, textual_name );"

.SS "#define DEFINE_COLOUR(\fBname\fP, initialiser, textual_name)   extern AUDACITY_DLL_API \fBint\fP \fBname\fP;"

.PP
Definition at line 65 of file MacroMagic\&.h\&.
.SS "#define DEFINE_FONT(\fBname\fP, initialiser, textual_name)   theTheme\&.RegisterFont( \fBname\fP, initialiser, textual_name );"

.SS "#define DEFINE_FONT(\fBname\fP, initialiser, textual_name)   extern AUDACITY_DLL_API \fBint\fP \fBname\fP;"

.PP
Definition at line 66 of file MacroMagic\&.h\&.
.SS "#define DEFINE_IMAGE(\fBname\fP, initialiser, textual_name)   theTheme\&.RegisterImage( \fBname\fP, initialiser, textual_name );"

.SS "#define DEFINE_IMAGE(\fBname\fP, initialiser, textual_name)   extern AUDACITY_DLL_API \fBteBmps\fP \fBname\fP;"

.PP
Definition at line 64 of file MacroMagic\&.h\&.
.SS "#define SET_THEME_FLAGS(flags)   theTheme\&.SetFlags(  flags );"

.SS "#define SET_THEME_FLAGS(flags)"

.PP
Definition at line 67 of file MacroMagic\&.h\&.
.SS "#define THEME_EXTERNS"

.SS "#define THEME_EXTERNS"

.PP
Definition at line 40 of file MacroMagic\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
