.TH "mad_stream" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mad_stream \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mad\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBconst\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "unsigned char \fBconst\fP * \fBbufend\fP"
.br
.ti -1c
.RI "unsigned long \fBskiplen\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsync\fP"
.br
.ti -1c
.RI "unsigned long \fBfreerate\fP"
.br
.ti -1c
.RI "unsigned char \fBconst\fP * \fBthis_frame\fP"
.br
.ti -1c
.RI "unsigned char \fBconst\fP * \fBnext_frame\fP"
.br
.ti -1c
.RI "struct \fBmad_bitptr\fP \fBptr\fP"
.br
.ti -1c
.RI "struct \fBmad_bitptr\fP \fBanc_ptr\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBanc_bitlen\fP"
.br
.ti -1c
.RI "unsigned char(* \fBmain_data\fP )[\fBMAD_BUFFER_MDLEN\fP]"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBmd_len\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoptions\fP"
.br
.ti -1c
.RI "enum \fBmad_error\fP \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 681 of file mad\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned \fBint\fP mad_stream::anc_bitlen"

.PP
Definition at line 694 of file mad\&.h\&.
.SS "struct \fBmad_bitptr\fP mad_stream::anc_ptr"

.PP
Definition at line 693 of file mad\&.h\&.
.SS "unsigned char \fBconst\fP * mad_stream::bufend"

.PP
Definition at line 683 of file mad\&.h\&.
.SS "unsigned char \fBconst\fP * mad_stream::buffer"

.PP
Definition at line 682 of file mad\&.h\&.
.SS "enum \fBmad_error\fP mad_stream::error"

.PP
Definition at line 701 of file mad\&.h\&.
.SS "unsigned long mad_stream::freerate"

.PP
Definition at line 687 of file mad\&.h\&.
.SS "unsigned char(* mad_stream::main_data"

.PP
Definition at line 696 of file mad\&.h\&.
.SS "unsigned \fBint\fP mad_stream::md_len"

.PP
Definition at line 698 of file mad\&.h\&.
.SS "unsigned char \fBconst\fP * mad_stream::next_frame"

.PP
Definition at line 690 of file mad\&.h\&.
.SS "\fBint\fP mad_stream::options"

.PP
Definition at line 700 of file mad\&.h\&.
.SS "struct \fBmad_bitptr\fP mad_stream::ptr"

.PP
Definition at line 691 of file mad\&.h\&.
.SS "unsigned long mad_stream::skiplen"

.PP
Definition at line 684 of file mad\&.h\&.
.SS "\fBint\fP mad_stream::sync"

.PP
Definition at line 686 of file mad\&.h\&.
.SS "unsigned char \fBconst\fP * mad_stream::this_frame"

.PP
Definition at line 689 of file mad\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
