.TH "MessageBoxTarget" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageBoxTarget \- Displays messages from a command in a wxMessageBox\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandTargets\&.h>\fP
.PP
Inherits \fBCommandMessageTarget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~MessageBoxTarget\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdate\fP (\fBconst\fP wxString &message) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Displays messages from a command in a wxMessageBox\&. 
.PP
Definition at line 100 of file CommandTargets\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual MessageBoxTarget::~MessageBoxTarget ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 103 of file CommandTargets\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP MessageBoxTarget::Update (\fBconst\fP wxString & message)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBCommandMessageTarget\fP\&.
.PP
Definition at line 104 of file CommandTargets\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
