.TH "MeterUpdateMsg" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeterUpdateMsg \- Message used to update the \fBMeter\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Meter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeterUpdateMsg\fP ()"
.br
.ti -1c
.RI "\fB~MeterUpdateMsg\fP ()"
.br
.ti -1c
.RI "wxString \fBtoString\fP ()"
.br
.RI "\fIPrint out all the values in the meter update message\&. \fP"
.ti -1c
.RI "wxString \fBtoStringIfClipped\fP ()"
.br
.RI "\fIOnly print meter updates if clipping may be happening\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBnumFrames\fP"
.br
.ti -1c
.RI "float \fBpeak\fP [\fBkMaxMeterBars\fP]"
.br
.ti -1c
.RI "float \fBrms\fP [\fBkMaxMeterBars\fP]"
.br
.ti -1c
.RI "\fBbool\fP \fBclipping\fP [\fBkMaxMeterBars\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBheadPeakCount\fP [\fBkMaxMeterBars\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBtailPeakCount\fP [\fBkMaxMeterBars\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message used to update the \fBMeter\fP\&. 
.PP
Definition at line 48 of file Meter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeterUpdateMsg::MeterUpdateMsg ()\fC [inline]\fP"

.PP
Definition at line 59 of file Meter\&.h\&.
.SS "MeterUpdateMsg::~MeterUpdateMsg ()\fC [inline]\fP"

.PP
Definition at line 60 of file Meter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "wxString MeterUpdateMsg::toString ()"

.PP
Print out all the values in the meter update message\&. 
.PP
Definition at line 78 of file Meter\&.cpp\&.
.SS "wxString MeterUpdateMsg::toStringIfClipped ()"

.PP
Only print meter updates if clipping may be happening\&. 
.PP
Definition at line 95 of file Meter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP MeterUpdateMsg::clipping[\fBkMaxMeterBars\fP]"

.PP
Definition at line 54 of file Meter\&.h\&.
.SS "\fBint\fP MeterUpdateMsg::headPeakCount[\fBkMaxMeterBars\fP]"

.PP
Definition at line 55 of file Meter\&.h\&.
.SS "\fBint\fP MeterUpdateMsg::numFrames"

.PP
Definition at line 51 of file Meter\&.h\&.
.SS "float MeterUpdateMsg::peak[\fBkMaxMeterBars\fP]"

.PP
Definition at line 52 of file Meter\&.h\&.
.SS "float MeterUpdateMsg::rms[\fBkMaxMeterBars\fP]"

.PP
Definition at line 53 of file Meter\&.h\&.
.SS "\fBint\fP MeterUpdateMsg::tailPeakCount[\fBkMaxMeterBars\fP]"

.PP
Definition at line 56 of file Meter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
