.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/mfmidi.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/mfmidi.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'mfmidi\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'assert\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIDIFILE_ERROR\fP   \-1"
.br
.ti -1c
.RI "#define \fBMSGINCREMENT\fP   128"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBabort_flag\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MIDIFILE_ERROR   \-1"

.PP
Definition at line 18 of file mfmidi\&.cpp\&.
.SS "#define MSGINCREMENT   128"

.PP
Definition at line 427 of file mfmidi\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP abort_flag"

.PP
Definition at line 187 of file userio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
