.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/midierr.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/midierr.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNESTERR\fP   1 	/* nested interrupts */"
.br
.ti -1c
.RI "#define \fBBUFFOVFL\fP   2	/* input \fBbuffer\fP overflow */"
.br
.ti -1c
.RI "#define \fBCMDERR\fP   3	/* unknown command \fBfrom\fP mpu\-401 */"
.br
.ti -1c
.RI "#define \fBTIMEOUTERR\fP   4	/* \fBinterface\fP timeout */"
.br
.ti -1c
.RI "#define \fBMSGERR\fP   5	/* invalid message */"
.br
.ti -1c
.RI "#define \fBSYSEXOVFL\fP   6	/* \fBsysex\fP \fBbuffer\fP overflow */"
.br
.ti -1c
.RI "#define \fBMEMERR\fP   7	/* internal \fBout\fP \fBof\fP memory */"
.br
.ti -1c
.RI "#define \fBRECVERR\fP   8	/* receive \fBerror\fP or device \fBbuffer\fP overflow */"
.br
.ti -1c
.RI "#define \fBMIDIMGRERR\fP   9	/* \fBerror\fP reported by \fBmidi\fP manager (Macintosh) */"
.br
.ti -1c
.RI "#define \fBSYSEX_ERR\fP   ((1<<\fBRECVERR\fP) | (1<<\fBMEMERR\fP) | (1<<\fBSYSEXOVFL\fP))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmidi_show_errors\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "short \fBmidi_error_flags\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFOVFL   2	/* input \fBbuffer\fP overflow */"

.PP
Definition at line 4 of file midierr\&.h\&.
.SS "#define CMDERR   3	/* unknown command \fBfrom\fP mpu\-401 */"

.PP
Definition at line 5 of file midierr\&.h\&.
.SS "#define MEMERR   7	/* internal \fBout\fP \fBof\fP memory */"

.PP
Definition at line 9 of file midierr\&.h\&.
.SS "#define MIDIMGRERR   9	/* \fBerror\fP reported by \fBmidi\fP manager (Macintosh) */"

.PP
Definition at line 11 of file midierr\&.h\&.
.SS "#define MSGERR   5	/* invalid message */"

.PP
Definition at line 7 of file midierr\&.h\&.
.SS "#define NESTERR   1 	/* nested interrupts */"

.PP
Definition at line 3 of file midierr\&.h\&.
.SS "#define RECVERR   8	/* receive \fBerror\fP or device \fBbuffer\fP overflow */"

.PP
Definition at line 10 of file midierr\&.h\&.
.SS "#define SYSEX_ERR   ((1<<\fBRECVERR\fP) | (1<<\fBMEMERR\fP) | (1<<\fBSYSEXOVFL\fP))"

.PP
Definition at line 13 of file midierr\&.h\&.
.SS "#define SYSEXOVFL   6	/* \fBsysex\fP \fBbuffer\fP overflow */"

.PP
Definition at line 8 of file midierr\&.h\&.
.SS "#define TIMEOUTERR   4	/* \fBinterface\fP timeout */"

.PP
Definition at line 6 of file midierr\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP midi_show_errors (\fBvoid\fP)"

.PP
Definition at line 588 of file midimgr\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "short midi_error_flags"

.PP
Definition at line 207 of file midifns\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
