.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_test/midithread.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_test/midithread.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'assert\&.h'\fP
.br
\fC#include 'portmidi\&.h'\fP
.br
\fC#include 'pmutil\&.h'\fP
.br
\fC#include 'porttime\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINPUT_BUFFER_SIZE\fP   0"
.br
.ti -1c
.RI "#define \fBOUTPUT_BUFFER_SIZE\fP   100"
.br
.ti -1c
.RI "#define \fBDRIVER_INFO\fP   \fBNULL\fP"
.br
.ti -1c
.RI "#define \fBTIME_PROC\fP   \fBNULL\fP"
.br
.ti -1c
.RI "#define \fBTIME_INFO\fP   \fBNULL\fP"
.br
.ti -1c
.RI "#define \fBLATENCY\fP   0"
.br
.ti -1c
.RI "#define \fBSTRING_MAX\fP   80"
.br
.ti -1c
.RI "#define \fBQUIT_MSG\fP   1000"
.br
.ti -1c
.RI "#define \fBMONITOR_MSG\fP   1001"
.br
.ti -1c
.RI "#define \fBTHRU_MSG\fP   1002"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBprocess_midi\fP (\fBPtTimestamp\fP timestamp, \fBvoid\fP *\fBuserData\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBexit_with_message\fP (char *msg)"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBactive\fP = \fBFALSE\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmonitor\fP = \fBFALSE\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmidi_thru\fP = \fBTRUE\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtranspose\fP"
.br
.ti -1c
.RI "\fBPmStream\fP * \fBmidi_in\fP"
.br
.ti -1c
.RI "\fBPmStream\fP * \fBmidi_out\fP"
.br
.ti -1c
.RI "\fBPmQueue\fP * \fBmidi_to_main\fP"
.br
.ti -1c
.RI "\fBPmQueue\fP * \fBmain_to_midi\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DRIVER_INFO   \fBNULL\fP"

.PP
Definition at line 59 of file midithread\&.c\&.
.SS "#define INPUT_BUFFER_SIZE   0"

.PP
Definition at line 56 of file midithread\&.c\&.
.SS "#define LATENCY   0"

.PP
Definition at line 63 of file midithread\&.c\&.
.SS "#define MONITOR_MSG   1001"

.PP
Definition at line 89 of file midithread\&.c\&.
.SS "#define OUTPUT_BUFFER_SIZE   100"

.PP
Definition at line 58 of file midithread\&.c\&.
.SS "#define QUIT_MSG   1000"

.PP
Definition at line 88 of file midithread\&.c\&.
.SS "#define STRING_MAX   80"

.PP
Definition at line 65 of file midithread\&.c\&.
.SS "#define THRU_MSG   1002"

.PP
Definition at line 90 of file midithread\&.c\&.
.SS "#define TIME_INFO   \fBNULL\fP"

.PP
Definition at line 61 of file midithread\&.c\&.
.SS "#define TIME_PROC   \fBNULL\fP"

.PP
Definition at line 60 of file midithread\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP exit_with_message (char * msg)"

.PP
Definition at line 165 of file midithread\&.c\&.
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 173 of file midithread\&.c\&.
.SS "\fBvoid\fP process_midi (\fBPtTimestamp\fP timestamp, \fBvoid\fP * userData)"

.PP
Definition at line 93 of file midithread\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP active = \fBFALSE\fP"

.PP
Definition at line 72 of file midithread\&.c\&.
.SS "\fBPmQueue\fP* main_to_midi"

.PP
Definition at line 86 of file midithread\&.c\&.
.SS "\fBPmStream\fP* midi_in"

.PP
Definition at line 77 of file midithread\&.c\&.
.SS "\fBPmStream\fP* midi_out"

.PP
Definition at line 78 of file midithread\&.c\&.
.SS "\fBint\fP midi_thru = \fBTRUE\fP"

.PP
Definition at line 74 of file midithread\&.c\&.
.SS "\fBPmQueue\fP* midi_to_main"

.PP
Definition at line 85 of file midithread\&.c\&.
.SS "\fBint\fP monitor = \fBFALSE\fP"

.PP
Definition at line 73 of file midithread\&.c\&.
.SS "\fBint\fP transpose"

.PP
Definition at line 76 of file midithread\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
