.TH "MidiIOPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MidiIOPrefs \- A \fBPrefsPanel\fP used to select recording and playback devices and other settings\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP used to select recording and playback devices and other settings\&. 

Presents interface for user to select the recording device and playback device, from the list of choices that PortMidi makes available\&.
.PP
Also lets user decide whether or not to record in stereo, and whether or not to play other tracks while recording one (duplex)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
