.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/expat/tests/minicheck.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/expat/tests/minicheck.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSRunner\fP"
.br
.ti -1c
.RI "struct \fBSuite\fP"
.br
.ti -1c
.RI "struct \fBTCase\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCK_NOFORK\fP   0"
.br
.ti -1c
.RI "#define \fBCK_FORK\fP   1"
.br
.ti -1c
.RI "#define \fBCK_SILENT\fP   0"
.br
.ti -1c
.RI "#define \fBCK_NORMAL\fP   1"
.br
.ti -1c
.RI "#define \fBCK_VERBOSE\fP   2"
.br
.ti -1c
.RI "#define \fBSTART_TEST\fP(testname)"
.br
.ti -1c
.RI "#define \fBEND_TEST\fP   } }"
.br
.ti -1c
.RI "#define \fBfail\fP(msg)   \fB_fail_unless\fP(0, __FILE__, __LINE__, msg)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvoid\fP(* \fBtcase_setup_function\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBtcase_teardown_function\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBtcase_test_function\fP) (\fBvoid\fP)"
.br
.ti -1c
.RI "typedef struct \fBSRunner\fP \fBSRunner\fP"
.br
.ti -1c
.RI "typedef struct \fBSuite\fP \fBSuite\fP"
.br
.ti -1c
.RI "typedef struct \fBTCase\fP \fBTCase\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_check_set_test_info\fP (char \fBconst\fP *\fBfunction\fP, char \fBconst\fP *\fBfilename\fP, \fBint\fP \fBlineno\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_fail_unless\fP (\fBint\fP condition, \fBconst\fP char *file, \fBint\fP \fBline\fP, char *msg)"
.br
.ti -1c
.RI "\fBSuite\fP * \fBsuite_create\fP (char *\fBname\fP)"
.br
.ti -1c
.RI "\fBTCase\fP * \fBtcase_create\fP (char *\fBname\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsuite_add_tcase\fP (\fBSuite\fP *suite, \fBTCase\fP *tc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtcase_add_checked_fixture\fP (\fBTCase\fP *, \fBtcase_setup_function\fP, \fBtcase_teardown_function\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtcase_add_test\fP (\fBTCase\fP *tc, \fBtcase_test_function\fP \fBtest\fP)"
.br
.ti -1c
.RI "\fBSRunner\fP * \fBsrunner_create\fP (\fBSuite\fP *suite)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsrunner_run_all\fP (\fBSRunner\fP *runner, \fBint\fP verbosity)"
.br
.ti -1c
.RI "\fBint\fP \fBsrunner_ntests_failed\fP (\fBSRunner\fP *runner)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsrunner_free\fP (\fBSRunner\fP *runner)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CK_FORK   1"

.PP
Definition at line 15 of file minicheck\&.h\&.
.SS "#define CK_NOFORK   0"

.PP
Definition at line 14 of file minicheck\&.h\&.
.SS "#define CK_NORMAL   1"

.PP
Definition at line 18 of file minicheck\&.h\&.
.SS "#define CK_SILENT   0"

.PP
Definition at line 17 of file minicheck\&.h\&.
.SS "#define CK_VERBOSE   2"

.PP
Definition at line 19 of file minicheck\&.h\&.
.SS "#define END_TEST   } }"

.PP
Definition at line 32 of file minicheck\&.h\&.
.SS "#define fail(msg)   \fB_fail_unless\fP(0, __FILE__, __LINE__, msg)"

.PP
Definition at line 34 of file minicheck\&.h\&.
.SS "#define START_TEST(testname)"
\fBValue:\fP
.PP
.nf
static void testname(void) { \
    _check_set_test_info(__func__, __FILE__, __LINE__);   \
    {
.fi
.PP
Definition at line 29 of file minicheck\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSRunner\fP \fBSRunner\fP"

.PP
Definition at line 40 of file minicheck\&.h\&.
.SS "typedef struct \fBSuite\fP \fBSuite\fP"

.PP
Definition at line 41 of file minicheck\&.h\&.
.SS "typedef struct \fBTCase\fP \fBTCase\fP"

.PP
Definition at line 42 of file minicheck\&.h\&.
.SS "typedef \fBvoid\fP(* tcase_setup_function) (\fBvoid\fP)"

.PP
Definition at line 36 of file minicheck\&.h\&.
.SS "typedef \fBvoid\fP(* tcase_teardown_function) (\fBvoid\fP)"

.PP
Definition at line 37 of file minicheck\&.h\&.
.SS "typedef \fBvoid\fP(* tcase_test_function) (\fBvoid\fP)"

.PP
Definition at line 38 of file minicheck\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP _check_set_test_info (char \fBconst\fP * function, char \fBconst\fP * filename, \fBint\fP lineno)"

.PP
Definition at line 92 of file minicheck\&.c\&.
.SS "\fBvoid\fP _fail_unless (\fBint\fP condition, \fBconst\fP char * file, \fBint\fP line, char * msg)"

.PP
Definition at line 159 of file minicheck\&.c\&.
.SS "\fBSRunner\fP* srunner_create (\fBSuite\fP * suite)"

.PP
Definition at line 76 of file minicheck\&.c\&.
.SS "\fBvoid\fP srunner_free (\fBSRunner\fP * runner)"

.PP
Definition at line 178 of file minicheck\&.c\&.
.SS "\fBint\fP srunner_ntests_failed (\fBSRunner\fP * runner)"

.PP
Definition at line 171 of file minicheck\&.c\&.
.SS "\fBvoid\fP srunner_run_all (\fBSRunner\fP * runner, \fBint\fP verbosity)"

.PP
Definition at line 111 of file minicheck\&.c\&.
.SS "\fBvoid\fP suite_add_tcase (\fBSuite\fP * suite, \fBTCase\fP * tc)"

.PP
Definition at line 36 of file minicheck\&.c\&.
.SS "\fBSuite\fP* suite_create (char * name)"

.PP
Definition at line 16 of file minicheck\&.c\&.
.SS "\fBvoid\fP tcase_add_checked_fixture (\fBTCase\fP *, \fBtcase_setup_function\fP, \fBtcase_teardown_function\fP)"

.PP
Definition at line 47 of file minicheck\&.c\&.
.SS "\fBvoid\fP tcase_add_test (\fBTCase\fP * tc, \fBtcase_test_function\fP test)"

.PP
Definition at line 57 of file minicheck\&.c\&.
.SS "\fBTCase\fP* tcase_create (char * name)"

.PP
Definition at line 26 of file minicheck\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
