.TH "C:/_dev/OpenU/Audacity/audacity/src/Mix.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/Mix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'SampleFormat\&.h'\fP
.br
\fC#include 'Resample\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMixerSpec\fP"
.br
.RI "\fIClass used with \fBMixer\fP\&. \fP"
.ti -1c
.RI "class \fBMixer\fP"
.br
.RI "\fIFunctions for doing the mixdown of the tracks\&. \fP"
.ti -1c
.RI "class \fBMixer::WarpOptions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBMixAndRender\fP (\fBTrackList\fP *tracks, \fBTrackFactory\fP *factory, double \fBrate\fP, \fBsampleFormat\fP \fBformat\fP, double startTime, double endTime, \fBWaveTrack\fP **newLeft, \fBWaveTrack\fP **newRight)"
.br
.RI "\fIMixes together all input tracks, applying any envelopes, amplitude gain, panning, and real-time effects in the process\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBMixBuffers\fP (\fBint\fP numChannels, \fBint\fP *channelFlags, float *gains, \fBsamplePtr\fP src, \fBsamplePtr\fP *dests, \fBint\fP \fBlen\fP, \fBbool\fP interleaved)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP MixAndRender (\fBTrackList\fP * tracks, \fBTrackFactory\fP * factory, double rate, \fBsampleFormat\fP format, double startTime, double endTime, \fBWaveTrack\fP ** newLeft, \fBWaveTrack\fP ** newRight)"

.PP
Mixes together all input tracks, applying any envelopes, amplitude gain, panning, and real-time effects in the process\&. Takes one or more tracks as input; of all the \fBWaveTrack\fP s that are selected, it mixes them together, applying any envelopes, amplitude gain, panning, and real-time effects in the process\&. The resulting pair of tracks (stereo) are 'rendered' and have no effects, gain, panning, or envelopes\&. Other sorts of tracks are ignored\&. If the start and end times passed are the same this is taken as meaning no explicit time range to process, and the whole occupied length of the input tracks is processed\&. : could we not use a \fBSelectedTrackListOfKindIterator\fP here? 
.PP
Definition at line 46 of file Mix\&.cpp\&.
.SS "\fBvoid\fP MixBuffers (\fBint\fP numChannels, \fBint\fP * channelFlags, float * gains, \fBsamplePtr\fP src, \fBsamplePtr\fP * dests, \fBint\fP len, \fBbool\fP interleaved)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
