.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/wasapi/mingw-include/mmdeviceapi.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/wasapi/mingw-include/mmdeviceapi.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rpc\&.h'\fP
.br
\fC#include 'rpcndr\&.h'\fP
.br
\fC#include 'windows\&.h'\fP
.br
\fC#include 'ole2\&.h'\fP
.br
\fC#include 'unknwn\&.h'\fP
.br
\fC#include 'propsys\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtagDIRECTX_AUDIO_ACTIVATION_PARAMS\fP"
.br
.ti -1c
.RI "struct \fBIMMNotificationClientVtbl\fP"
.br
.ti -1c
.RI "struct \fBIMMDeviceVtbl\fP"
.br
.ti -1c
.RI "struct \fBIMMDeviceCollectionVtbl\fP"
.br
.ti -1c
.RI "struct \fBIMMEndpointVtbl\fP"
.br
.ti -1c
.RI "struct \fBIMMDeviceEnumeratorVtbl\fP"
.br
.ti -1c
.RI "struct \fBIMMDeviceActivatorVtbl\fP"
.br
.ti -1c
.RI "struct \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__REQUIRED_RPCNDR_H_VERSION__\fP   500"
.br
.ti -1c
.RI "#define \fB__REQUIRED_RPCSAL_H_VERSION__\fP   100"
.br
.ti -1c
.RI "#define \fB__IMMNotificationClient_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDevice_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceCollection_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMEndpoint_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceEnumerator_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceActivator_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__MMDeviceEnumerator_FWD_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fBE_NOTFOUND\fP   HRESULT_FROM_WIN32(ERROR_NOT_FOUND)"
.br
.ti -1c
.RI "#define \fBE_UNSUPPORTED_TYPE\fP   HRESULT_FROM_WIN32(ERROR_UNSUPPORTED_TYPE)"
.br
.ti -1c
.RI "#define \fBDEVICE_STATE_ACTIVE\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBDEVICE_STATE_DISABLED\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBDEVICE_STATE_NOTPRESENT\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBDEVICE_STATE_UNPLUGGED\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBDEVICE_STATEMASK_ALL\fP   0x0000000f"
.br
.ti -1c
.RI "#define \fBDEFINE_PROPERTYKEY\fP(\fBname\fP,  \fBl\fP,  w1,  w2,  b1,  b2,  b3,  b4,  b5,  b6,  b7,  b8,  pid)   \fBEXTERN_C\fP \fBconst\fP \fBPROPERTYKEY\fP \fBname\fP"
.br
.ti -1c
.RI "#define \fBENDPOINT_SYSFX_ENABLED\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBENDPOINT_SYSFX_DISABLED\fP   0x00000001"
.br
.ti -1c
.RI "#define \fB__IMMNotificationClient_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDevice_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceCollection_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMEndpoint_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceEnumerator_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__IMMDeviceActivator_INTERFACE_DEFINED__\fP"
.br
.ti -1c
.RI "#define \fB__MMDeviceAPILib_LIBRARY_DEFINED__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMNotificationClient\fP \fBIMMNotificationClient\fP"
.br
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMDevice\fP \fBIMMDevice\fP"
.br
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMDeviceCollection\fP \fBIMMDeviceCollection\fP"
.br
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMEndpoint\fP \fBIMMEndpoint\fP"
.br
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMDeviceEnumerator\fP \fBIMMDeviceEnumerator\fP"
.br
.ti -1c
.RI "typedef \fBinterface\fP \fBIMMDeviceActivator\fP \fBIMMDeviceActivator\fP"
.br
.ti -1c
.RI "typedef struct \fBMMDeviceEnumerator\fP \fBMMDeviceEnumerator\fP"
.br
.ti -1c
.RI "typedef struct \fBtagDIRECTX_AUDIO_ACTIVATION_PARAMS\fP \fBDIRECTX_AUDIO_ACTIVATION_PARAMS\fP"
.br
.ti -1c
.RI "typedef struct \fBtagDIRECTX_AUDIO_ACTIVATION_PARAMS\fP * \fBPDIRECTX_AUDIO_ACTIVATION_PARAMS\fP"
.br
.ti -1c
.RI "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001\fP \fBEDataFlow\fP"
.br
.ti -1c
.RI "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0002\fP \fBERole\fP"
.br
.ti -1c
.RI "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0003\fP \fBEndpointFormFactor\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMNotificationClientVtbl\fP \fBIMMNotificationClientVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMDeviceVtbl\fP \fBIMMDeviceVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMDeviceCollectionVtbl\fP \fBIMMDeviceCollectionVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMEndpointVtbl\fP \fBIMMEndpointVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMDeviceEnumeratorVtbl\fP \fBIMMDeviceEnumeratorVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fBIMMDeviceActivatorVtbl\fP \fBIMMDeviceActivatorVtbl\fP"
.br
.ti -1c
.RI "typedef struct \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001\fP \fBAudioExtensionParams\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001\fP { \fBeRender\fP = 0, \fBeCapture\fP = ( eRender + 1 ), \fBeAll\fP = ( eCapture + 1 ), \fBEDataFlow_enum_count\fP = ( eAll + 1 ) }"
.br
.ti -1c
.RI "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0002\fP { \fBeConsole\fP = 0, \fBeMultimedia\fP = ( eConsole + 1 ), \fBeCommunications\fP = ( eMultimedia + 1 ), \fBERole_enum_count\fP = ( eCommunications + 1 ) }"
.br
.ti -1c
.RI "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0003\fP { \fBRemoteNetworkDevice\fP = 0, \fBSpeakers\fP = ( RemoteNetworkDevice + 1 ), \fBLineLevel\fP = ( Speakers + 1 ), \fBHeadphones\fP = ( LineLevel + 1 ), \fBMicrophone\fP = ( Headphones + 1 ), \fBHeadset\fP = ( Microphone + 1 ), \fBHandset\fP = ( Headset + 1 ), \fBUnknownDigitalPassthrough\fP = ( Handset + 1 ), \fBSPDIF\fP = ( UnknownDigitalPassthrough + 1 ), \fBHDMI\fP = ( SPDIF + 1 ), \fBUnknownFormFactor\fP = ( HDMI + 1 ) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_FormFactor, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 0)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_ControlPanelPageProvider, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 1)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_Association, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 2)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_PhysicalSpeakers, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 3)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_GUID, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 4)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_Disable_SysFx, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 5)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEndpoint_FullRangeSpeakers, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 6)"
.br
.ti -1c
.RI "\fBDEFINE_PROPERTYKEY\fP (PKEY_AudioEngine_DeviceFormat, 0xf19f064d, 0x82c, 0x4e27, 0xbc, 0x73, 0x68, 0x82, 0xa1, 0xbb, 0x8e, 0x4c, 0)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_mmdeviceapi_0000_0000_v0_0_c_ifspec\fP"
.br
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_mmdeviceapi_0000_0000_v0_0_s_ifspec\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMNotificationClient\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMDevice\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMDeviceCollection\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMEndpoint\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMDeviceEnumerator\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBIID_IMMDeviceActivator\fP"
.br
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_mmdeviceapi_0000_0006_v0_0_c_ifspec\fP"
.br
.ti -1c
.RI "RPC_IF_HANDLE \fB__MIDL_itf_mmdeviceapi_0000_0006_v0_0_s_ifspec\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP IID \fBLIBID_MMDeviceAPILib\fP"
.br
.ti -1c
.RI "\fBEXTERN_C\fP \fBconst\fP CLSID \fBCLSID_MMDeviceEnumerator\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __IMMDevice_FWD_DEFINED__"

.PP
Definition at line 62 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDevice_INTERFACE_DEFINED__"

.PP
Definition at line 331 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceActivator_FWD_DEFINED__"

.PP
Definition at line 86 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceActivator_INTERFACE_DEFINED__"

.PP
Definition at line 791 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceCollection_FWD_DEFINED__"

.PP
Definition at line 68 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceCollection_INTERFACE_DEFINED__"

.PP
Definition at line 464 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceEnumerator_FWD_DEFINED__"

.PP
Definition at line 80 of file mmdeviceapi\&.h\&.
.SS "#define __IMMDeviceEnumerator_INTERFACE_DEFINED__"

.PP
Definition at line 642 of file mmdeviceapi\&.h\&.
.SS "#define __IMMEndpoint_FWD_DEFINED__"

.PP
Definition at line 74 of file mmdeviceapi\&.h\&.
.SS "#define __IMMEndpoint_INTERFACE_DEFINED__"

.PP
Definition at line 561 of file mmdeviceapi\&.h\&.
.SS "#define __IMMNotificationClient_FWD_DEFINED__"

.PP
Definition at line 56 of file mmdeviceapi\&.h\&.
.SS "#define __IMMNotificationClient_INTERFACE_DEFINED__"

.PP
Definition at line 186 of file mmdeviceapi\&.h\&.
.SS "#define __MMDeviceAPILib_LIBRARY_DEFINED__"

.PP
Definition at line 901 of file mmdeviceapi\&.h\&.
.SS "#define __MMDeviceEnumerator_FWD_DEFINED__"

.PP
Definition at line 92 of file mmdeviceapi\&.h\&.
.SS "#define __REQUIRED_RPCNDR_H_VERSION__   500"

.PP
Definition at line 22 of file mmdeviceapi\&.h\&.
.SS "#define __REQUIRED_RPCSAL_H_VERSION__   100"

.PP
Definition at line 27 of file mmdeviceapi\&.h\&.
.SS "#define DEFINE_PROPERTYKEY(\fBname\fP, \fBl\fP, w1, w2, b1, b2, b3, b4, b5, b6, b7, b8, pid)   \fBEXTERN_C\fP \fBconst\fP \fBPROPERTYKEY\fP \fBname\fP"

.PP
Definition at line 128 of file mmdeviceapi\&.h\&.
.SS "#define DEVICE_STATE_ACTIVE   0x00000001"

.PP
Definition at line 117 of file mmdeviceapi\&.h\&.
.SS "#define DEVICE_STATE_DISABLED   0x00000002"

.PP
Definition at line 118 of file mmdeviceapi\&.h\&.
.SS "#define DEVICE_STATE_NOTPRESENT   0x00000004"

.PP
Definition at line 119 of file mmdeviceapi\&.h\&.
.SS "#define DEVICE_STATE_UNPLUGGED   0x00000008"

.PP
Definition at line 120 of file mmdeviceapi\&.h\&.
.SS "#define DEVICE_STATEMASK_ALL   0x0000000f"

.PP
Definition at line 121 of file mmdeviceapi\&.h\&.
.SS "#define E_NOTFOUND   HRESULT_FROM_WIN32(ERROR_NOT_FOUND)"

.PP
Definition at line 115 of file mmdeviceapi\&.h\&.
.SS "#define E_UNSUPPORTED_TYPE   HRESULT_FROM_WIN32(ERROR_UNSUPPORTED_TYPE)"

.PP
Definition at line 116 of file mmdeviceapi\&.h\&.
.SS "#define ENDPOINT_SYSFX_DISABLED   0x00000001"

.PP
Definition at line 137 of file mmdeviceapi\&.h\&.
.SS "#define ENDPOINT_SYSFX_ENABLED   0x00000000"

.PP
Definition at line 136 of file mmdeviceapi\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0006_0001\fP 	 \fBAudioExtensionParams\fP"

.SS "typedef struct \fBtagDIRECTX_AUDIO_ACTIVATION_PARAMS\fP 	 \fBDIRECTX_AUDIO_ACTIVATION_PARAMS\fP"

.SS "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001\fP 	 \fBEDataFlow\fP"

.SS "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0003\fP 	 \fBEndpointFormFactor\fP"

.SS "typedef enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0002\fP 	 \fBERole\fP"

.SS "typedef \fBinterface\fP \fBIMMDevice\fP \fBIMMDevice\fP"

.PP
Definition at line 63 of file mmdeviceapi\&.h\&.
.SS "typedef \fBinterface\fP \fBIMMDeviceActivator\fP \fBIMMDeviceActivator\fP"

.PP
Definition at line 87 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBIMMDeviceActivatorVtbl\fP  \fBIMMDeviceActivatorVtbl\fP"

.SS "typedef \fBinterface\fP \fBIMMDeviceCollection\fP \fBIMMDeviceCollection\fP"

.PP
Definition at line 69 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBIMMDeviceCollectionVtbl\fP  \fBIMMDeviceCollectionVtbl\fP"

.SS "typedef \fBinterface\fP \fBIMMDeviceEnumerator\fP \fBIMMDeviceEnumerator\fP"

.PP
Definition at line 81 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBIMMDeviceEnumeratorVtbl\fP  \fBIMMDeviceEnumeratorVtbl\fP"

.SS "typedef struct \fBIMMDeviceVtbl\fP  \fBIMMDeviceVtbl\fP"

.SS "typedef \fBinterface\fP \fBIMMEndpoint\fP \fBIMMEndpoint\fP"

.PP
Definition at line 75 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBIMMEndpointVtbl\fP  \fBIMMEndpointVtbl\fP"

.SS "typedef \fBinterface\fP \fBIMMNotificationClient\fP \fBIMMNotificationClient\fP"

.PP
Definition at line 57 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBIMMNotificationClientVtbl\fP  \fBIMMNotificationClientVtbl\fP"

.SS "typedef struct \fBMMDeviceEnumerator\fP \fBMMDeviceEnumerator\fP"

.PP
Definition at line 97 of file mmdeviceapi\&.h\&.
.SS "typedef struct \fBtagDIRECTX_AUDIO_ACTIVATION_PARAMS\fP* \fBPDIRECTX_AUDIO_ACTIVATION_PARAMS\fP"

.PP
Definition at line 147 of file mmdeviceapi\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIeRender \fP\fP
.TP
\fB\fIeCapture \fP\fP
.TP
\fB\fIeAll \fP\fP
.TP
\fB\fIEDataFlow_enum_count \fP\fP
.PP
Definition at line 150 of file mmdeviceapi\&.h\&.
.SS "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0002\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIeConsole \fP\fP
.TP
\fB\fIeMultimedia \fP\fP
.TP
\fB\fIeCommunications \fP\fP
.TP
\fB\fIERole_enum_count \fP\fP
.PP
Definition at line 158 of file mmdeviceapi\&.h\&.
.SS "enum \fB__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0003\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRemoteNetworkDevice \fP\fP
.TP
\fB\fISpeakers \fP\fP
.TP
\fB\fILineLevel \fP\fP
.TP
\fB\fIHeadphones \fP\fP
.TP
\fB\fIMicrophone \fP\fP
.TP
\fB\fIHeadset \fP\fP
.TP
\fB\fIHandset \fP\fP
.TP
\fB\fIUnknownDigitalPassthrough \fP\fP
.TP
\fB\fISPDIF \fP\fP
.TP
\fB\fIHDMI \fP\fP
.TP
\fB\fIUnknownFormFactor \fP\fP
.PP
Definition at line 166 of file mmdeviceapi\&.h\&.
.SH "Function Documentation"
.PP 
.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_FormFactor, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 0)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_ControlPanelPageProvider, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 1)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_Association, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 2)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_PhysicalSpeakers, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 3)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_GUID, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 4)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_Disable_SysFx, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 5)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEndpoint_FullRangeSpeakers, 0x1da5d803, 0xd492, 0x4edd, 0x8c, 0x23, 0xe0, 0xc0, 0xff, 0xee, 0x7f, 0x0e, 6)"

.SS "DEFINE_PROPERTYKEY (PKEY_AudioEngine_DeviceFormat, 0xf19f064d, 0x82c, 0x4e27, 0xbc, 0x73, 0x68, 0x82, 0xa1, 0xbb, 0x8e, 0x4c, 0)"

.SH "Variable Documentation"
.PP 
.SS "RPC_IF_HANDLE __MIDL_itf_mmdeviceapi_0000_0000_v0_0_c_ifspec"

.SS "RPC_IF_HANDLE __MIDL_itf_mmdeviceapi_0000_0000_v0_0_s_ifspec"

.SS "RPC_IF_HANDLE __MIDL_itf_mmdeviceapi_0000_0006_v0_0_c_ifspec"

.SS "RPC_IF_HANDLE __MIDL_itf_mmdeviceapi_0000_0006_v0_0_s_ifspec"

.SS "\fBEXTERN_C\fP \fBconst\fP CLSID CLSID_MMDeviceEnumerator"

.PP
Definition at line 909 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMDevice"

.PP
Definition at line 337 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMDeviceActivator"

.PP
Definition at line 797 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMDeviceCollection"

.PP
Definition at line 470 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMDeviceEnumerator"

.PP
Definition at line 648 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMEndpoint"

.PP
Definition at line 567 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID IID_IMMNotificationClient"

.PP
Definition at line 192 of file mmdeviceapi\&.h\&.
.SS "\fBEXTERN_C\fP \fBconst\fP IID LIBID_MMDeviceAPILib"

.PP
Definition at line 907 of file mmdeviceapi\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
