.TH "ModulePrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModulePrefs \- A \fBPrefsPanel\fP to enable/disable certain modules\&. 'Modules' are dynamically linked libraries that modify Audacity\&. They are plug-ins with names like mnod-script-pipe that add NEW features\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModulePrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModulePrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fB~ModulePrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBint\fP \fBGetModuleStatus\fP (\fBconst\fP wxString &fname)"
.br
.ti -1c
.RI "static \fBvoid\fP \fBSetModuleStatus\fP (\fBconst\fP wxString &fname, \fBint\fP iStatus)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP to enable/disable certain modules\&. 'Modules' are dynamically linked libraries that modify Audacity\&. They are plug-ins with names like mnod-script-pipe that add NEW features\&. 
.PP
Definition at line 34 of file ModulePrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModulePrefs::ModulePrefs (wxWindow * parent)"

.PP
Definition at line 31 of file ModulePrefs\&.cpp\&.
.SS "ModulePrefs::~ModulePrefs ()"

.PP
Definition at line 37 of file ModulePrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP ModulePrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 129 of file ModulePrefs\&.cpp\&.
.SS "\fBint\fP ModulePrefs::GetModuleStatus (\fBconst\fP wxString & fname)\fC [static]\fP"

.PP
Definition at line 141 of file ModulePrefs\&.cpp\&.
.SS "\fBvoid\fP ModulePrefs::SetModuleStatus (\fBconst\fP wxString & fname, \fBint\fP iStatus)\fC [static]\fP"

.PP
Definition at line 155 of file ModulePrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
