.TH "ModuleManager" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuleManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModuleManager\&.h>\fP
.PP
Inherits \fBModuleManagerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleManager\fP ()"
.br
.ti -1c
.RI "virtual \fB~ModuleManager\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRegisterModule\fP (\fBModuleInterface\fP *module) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBInitialize\fP (\fBCommandHandler\fP &cmdHandler)"
.br
.ti -1c
.RI "\fBint\fP \fBDispatch\fP (\fBModuleDispatchTypes\fP type)"
.br
.ti -1c
.RI "\fBbool\fP \fBDiscoverProviders\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBFindAllPlugins\fP (\fBPluginIDList\fP &providers, wxArrayString &paths)"
.br
.ti -1c
.RI "wxArrayString \fBFindPluginsForProvider\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.ti -1c
.RI "\fBbool\fP \fBRegisterPlugin\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.ti -1c
.RI "\fBIdentInterface\fP * \fBCreateProviderInstance\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.ti -1c
.RI "\fBIdentInterface\fP * \fBCreateInstance\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDeleteInstance\fP (\fBconst\fP \fBPluginID\fP &provider, \fBIdentInterface\fP *instance)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsProviderValid\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsPluginValid\fP (\fBconst\fP \fBPluginID\fP &provider, \fBconst\fP wxString &path)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBModuleManager\fP & \fBGet\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBDestroy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file ModuleManager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModuleManager::ModuleManager ()"

.PP
Definition at line 203 of file ModuleManager\&.cpp\&.
.SS "ModuleManager::~ModuleManager ()\fC [virtual]\fP"

.PP
Definition at line 207 of file ModuleManager\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIdentInterface\fP * ModuleManager::CreateInstance (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 584 of file ModuleManager\&.cpp\&.
.SS "\fBIdentInterface\fP * ModuleManager::CreateProviderInstance (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 573 of file ModuleManager\&.cpp\&.
.SS "\fBvoid\fP ModuleManager::DeleteInstance (\fBconst\fP \fBPluginID\fP & provider, \fBIdentInterface\fP * instance)"

.PP
Definition at line 595 of file ModuleManager\&.cpp\&.
.SS "\fBvoid\fP ModuleManager::Destroy ()\fC [static]\fP"

.PP
Definition at line 375 of file ModuleManager\&.cpp\&.
.SS "\fBbool\fP ModuleManager::DiscoverProviders ()"

.PP
Definition at line 384 of file ModuleManager\&.cpp\&.
.SS "\fBint\fP ModuleManager::Dispatch (\fBModuleDispatchTypes\fP type)"

.PP
Definition at line 347 of file ModuleManager\&.cpp\&.
.SS "\fBvoid\fP ModuleManager::FindAllPlugins (\fBPluginIDList\fP & providers, wxArrayString & paths)"

.PP
Definition at line 517 of file ModuleManager\&.cpp\&.
.SS "wxArrayString ModuleManager::FindPluginsForProvider (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 547 of file ModuleManager\&.cpp\&.
.SS "\fBModuleManager\fP & ModuleManager::Get ()\fC [static]\fP"

.PP
Definition at line 365 of file ModuleManager\&.cpp\&.
.SS "\fBvoid\fP ModuleManager::Initialize (\fBCommandHandler\fP & cmdHandler)"

.PP
Definition at line 233 of file ModuleManager\&.cpp\&.
.SS "\fBbool\fP ModuleManager::IsPluginValid (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 624 of file ModuleManager\&.cpp\&.
.SS "\fBbool\fP ModuleManager::IsProviderValid (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 606 of file ModuleManager\&.cpp\&.
.SS "\fBvoid\fP ModuleManager::RegisterModule (\fBModuleInterface\fP * module)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBModuleManagerInterface\fP\&.
.PP
Definition at line 502 of file ModuleManager\&.cpp\&.
.SS "\fBbool\fP ModuleManager::RegisterPlugin (\fBconst\fP \fBPluginID\fP & provider, \fBconst\fP wxString & path)"

.PP
Definition at line 563 of file ModuleManager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
