.TH "ModuleManagerInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuleManagerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModuleInterface\&.h>\fP
.PP
Inherited by \fBModuleManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ModuleManagerInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBRegisterModule\fP (\fBModuleInterface\fP *module)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file ModuleInterface\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ModuleManagerInterface::~ModuleManagerInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 112 of file ModuleInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvoid\fP ModuleManagerInterface::RegisterModule (\fBModuleInterface\fP * module)\fC [pure virtual]\fP"

.PP
Implemented in \fBModuleManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
