.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/morph/morph.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/lv2/lv2plug.in/ns/ext/morph/morph.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'lv2/lv2plug\&.in/ns/lv2core/lv2\&.h'\fP
.br
\fC#include 'lv2/lv2plug\&.in/ns/ext/urid/urid\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV2_MORPH_URI\fP   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/morph'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH_PREFIX\fP   \fBLV2_MORPH_URI\fP '#'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH__AutoMorphPort\fP   \fBLV2_MORPH_PREFIX\fP 'AutoMorphPort'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH__MorphPort\fP   \fBLV2_MORPH_PREFIX\fP 'MorphPort'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH__interface\fP   \fBLV2_MORPH_PREFIX\fP 'interface'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH__supportsType\fP   \fBLV2_MORPH_PREFIX\fP 'supportsType'"
.br
.ti -1c
.RI "#define \fBLV2_MORPH__currentType\fP   \fBLV2_MORPH_PREFIX\fP 'currentType'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV2_MORPH__AutoMorphPort   \fBLV2_MORPH_PREFIX\fP 'AutoMorphPort'"

.PP
Definition at line 28 of file morph\&.h\&.
.SS "#define LV2_MORPH__currentType   \fBLV2_MORPH_PREFIX\fP 'currentType'"

.PP
Definition at line 32 of file morph\&.h\&.
.SS "#define LV2_MORPH__interface   \fBLV2_MORPH_PREFIX\fP 'interface'"

.PP
Definition at line 30 of file morph\&.h\&.
.SS "#define LV2_MORPH__MorphPort   \fBLV2_MORPH_PREFIX\fP 'MorphPort'"

.PP
Definition at line 29 of file morph\&.h\&.
.SS "#define LV2_MORPH__supportsType   \fBLV2_MORPH_PREFIX\fP 'supportsType'"

.PP
Definition at line 31 of file morph\&.h\&.
.SS "#define LV2_MORPH_PREFIX   \fBLV2_MORPH_URI\fP '#'"

.PP
Definition at line 26 of file morph\&.h\&.
.SS "#define LV2_MORPH_URI   'http://\fBlv2plug\&.in\fP/\fBns\fP/ext/morph'"

.PP
Definition at line 25 of file morph\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
