.TH "mp3data_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mp3data_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBheader_parsed\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstereo\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsamplerate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbitrate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmode_ext\fP"
.br
.ti -1c
.RI "\fBint\fP \fBframesize\fP"
.br
.ti -1c
.RI "unsigned long \fBnsamp\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtotalframes\fP"
.br
.ti -1c
.RI "\fBint\fP \fBframenum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 771 of file lame\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP mp3data_struct::bitrate"

.PP
Definition at line 776 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::framenum"

.PP
Definition at line 786 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::framesize"

.PP
Definition at line 779 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::header_parsed"

.PP
Definition at line 772 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::mode"

.PP
Definition at line 777 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::mode_ext"

.PP
Definition at line 778 of file lame\&.h\&.
.SS "unsigned long mp3data_struct::nsamp"

.PP
Definition at line 782 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::samplerate"

.PP
Definition at line 775 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::stereo"

.PP
Definition at line 774 of file lame\&.h\&.
.SS "\fBint\fP mp3data_struct::totalframes"

.PP
Definition at line 783 of file lame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
