.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/mpc2k.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/mpc2k.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADER_LENGTH\fP   42	/* Sum \fBof\fP above \fBdata\fP fields\&. */"
.br
.ti -1c
.RI "#define \fBHEADER_NAME_LEN\fP   17	/* Length \fBof\fP \fBname\fP string\&. */"
.br
.ti -1c
.RI "#define \fBSFE_MPC_NO_MARKER\fP   666"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmpc2k_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HEADER_LENGTH   42	/* Sum \fBof\fP above \fBdata\fP fields\&. */"

.PP
Definition at line 46 of file mpc2k\&.c\&.
.SS "#define HEADER_NAME_LEN   17	/* Length \fBof\fP \fBname\fP string\&. */"

.PP
Definition at line 47 of file mpc2k\&.c\&.
.SS "#define SFE_MPC_NO_MARKER   666"

.PP
Definition at line 49 of file mpc2k\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP mpc2k_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 65 of file mpc2k\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
