.TH "MS_ADPCM_WAV_FMT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MS_ADPCM_WAV_FMT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wav_w64\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBformat\fP"
.br
.ti -1c
.RI "unsigned short \fBchannels\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBsamplerate\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBbytespersec\fP"
.br
.ti -1c
.RI "unsigned short \fBblockalign\fP"
.br
.ti -1c
.RI "unsigned short \fBbitwidth\fP"
.br
.ti -1c
.RI "unsigned short \fBextrabytes\fP"
.br
.ti -1c
.RI "unsigned short \fBsamplesperblock\fP"
.br
.ti -1c
.RI "unsigned short \fBnumcoeffs\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   short \fBcoeff1\fP"
.br
.ti -1c
.RI "   short \fBcoeff2\fP"
.br
.ti -1c
.RI "} \fBcoeffs\fP [7]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 173 of file wav_w64\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short MS_ADPCM_WAV_FMT::bitwidth"

.PP
Definition at line 179 of file wav_w64\&.h\&.
.SS "unsigned short MS_ADPCM_WAV_FMT::blockalign"

.PP
Definition at line 178 of file wav_w64\&.h\&.
.SS "unsigned \fBint\fP MS_ADPCM_WAV_FMT::bytespersec"

.PP
Definition at line 177 of file wav_w64\&.h\&.
.SS "unsigned short MS_ADPCM_WAV_FMT::channels"

.PP
Definition at line 175 of file wav_w64\&.h\&.
.SS "short MS_ADPCM_WAV_FMT::coeff1"

.PP
Definition at line 184 of file wav_w64\&.h\&.
.SS "short MS_ADPCM_WAV_FMT::coeff2"

.PP
Definition at line 185 of file wav_w64\&.h\&.
.SS "struct { \&.\&.\&. } 	 MS_ADPCM_WAV_FMT::coeffs[7]"

.SS "unsigned short MS_ADPCM_WAV_FMT::extrabytes"

.PP
Definition at line 180 of file wav_w64\&.h\&.
.SS "unsigned short MS_ADPCM_WAV_FMT::format"

.PP
Definition at line 174 of file wav_w64\&.h\&.
.SS "unsigned short MS_ADPCM_WAV_FMT::numcoeffs"

.PP
Definition at line 182 of file wav_w64\&.h\&.
.SS "unsigned \fBint\fP MS_ADPCM_WAV_FMT::samplerate"

.PP
Definition at line 176 of file wav_w64\&.h\&.
.SS "unsigned short MS_ADPCM_WAV_FMT::samplesperblock"

.PP
Definition at line 181 of file wav_w64\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
