.TH "node::ninfo::xfixnum" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node::ninfo::xfixnum \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xldmem\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFIXTYPE\fP \fBxf_fixnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 179 of file xldmem\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFIXTYPE\fP node::ninfo::xfixnum::xf_fixnum"

.PP
Definition at line 180 of file xldmem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
