.TH "node::ninfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node::ninfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xldmem\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxchar\fP"
.br
.ti -1c
.RI "struct \fBxcons\fP"
.br
.ti -1c
.RI "struct \fBxextern\fP"
.br
.ti -1c
.RI "struct \fBxfixnum\fP"
.br
.ti -1c
.RI "struct \fBxflonum\fP"
.br
.ti -1c
.RI "struct \fBxstream\fP"
.br
.ti -1c
.RI "struct \fBxstring\fP"
.br
.ti -1c
.RI "struct \fBxsubr\fP"
.br
.ti -1c
.RI "struct \fBxvector\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnode::ninfo::xsubr\fP \fBn_xsubr\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xcons\fP \fBn_xcons\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xfixnum\fP \fBn_xfixnum\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xflonum\fP \fBn_xflonum\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xchar\fP \fBn_xchar\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xstring\fP \fBn_xstring\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xstream\fP \fBn_xstream\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xvector\fP \fBn_xvector\fP"
.br
.ti -1c
.RI "struct \fBnode::ninfo::xextern\fP \fBn_xextern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file xldmem\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnode::ninfo::xchar\fP  node::ninfo::n_xchar"

.SS "struct \fBnode::ninfo::xcons\fP  node::ninfo::n_xcons"

.SS "struct \fBnode::ninfo::xextern\fP  node::ninfo::n_xextern"

.SS "struct \fBnode::ninfo::xfixnum\fP  node::ninfo::n_xfixnum"

.SS "struct \fBnode::ninfo::xflonum\fP  node::ninfo::n_xflonum"

.SS "struct \fBnode::ninfo::xstream\fP  node::ninfo::n_xstream"

.SS "struct \fBnode::ninfo::xstring\fP  node::ninfo::n_xstring"

.SS "struct \fBnode::ninfo::xsubr\fP  node::ninfo::n_xsubr"

.SS "struct \fBnode::ninfo::xvector\fP  node::ninfo::n_xvector"


.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
