.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/NoiseReduction.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/NoiseReduction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include '\&.\&./Experimental\&.h'\fP
.br
\fC#include 'NoiseReduction\&.h'\fP
.br
\fC#include 'EffectManager\&.h'\fP
.br
\fC#include '\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include '\&.\&./Prefs\&.h'\fP
.br
\fC#include '\&.\&./WaveTrack\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/choice\&.h>\fP
.br
\fC#include <wx/dialog\&.h>\fP
.br
\fC#include <wx/radiobut\&.h>\fP
.br
\fC#include <wx/slider\&.h>\fP
.br
\fC#include <wx/valtext\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffectNoiseReduction::Statistics\fP"
.br
.ti -1c
.RI "class \fBEffectNoiseReduction::Settings\fP"
.br
.ti -1c
.RI "class \fBEffectNoiseReduction::Worker\fP"
.br
.ti -1c
.RI "class \fBEffectNoiseReduction::Dialog\fP"
.br
.RI "\fI\fBDialog\fP used with \fBEffectNoiseReduction\fP\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRESIDUE_CHOICE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< float > \fBFloatVector\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDiscriminationMethod\fP "
.br
.ti -1c
.RI "enum \fBWindowTypes\fP "
.br
.ti -1c
.RI "enum "
.br
.ti -1c
.RI "enum \fBNoiseReductionChoice\fP "
.br
.ti -1c
.RI "enum { \fBID_BUTTON_GETPROFILE\fP = 10001, \fBID_RADIOBUTTON_KEEPSIGNAL\fP, \fBID_RADIOBUTTON_RESIDUE\fP, \fBID_GAIN_SLIDER\fP, \fBID_GAIN_TEXT\fP, \fBID_NEW_SENSITIVITY_SLIDER\fP, \fBID_NEW_SENSITIVITY_TEXT\fP, \fBID_FREQ_SLIDER\fP, \fBID_FREQ_TEXT\fP, \fBEND_OF_BASIC_SLIDERS\fP, \fBEND_OF_SLIDERS\fP = END_OF_BASIC_SLIDERS, \fBFIRST_SLIDER\fP = ID_GAIN_SLIDER }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RESIDUE_CHOICE"

.PP
Definition at line 74 of file NoiseReduction\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<float> \fBFloatVector\fP"

.PP
Definition at line 71 of file NoiseReduction\&.cpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIID_BUTTON_GETPROFILE \fP\fP
.TP
\fB\fIID_RADIOBUTTON_KEEPSIGNAL \fP\fP
.TP
\fB\fIID_RADIOBUTTON_RESIDUE \fP\fP
.TP
\fB\fIID_GAIN_SLIDER \fP\fP
.TP
\fB\fIID_GAIN_TEXT \fP\fP
.TP
\fB\fIID_NEW_SENSITIVITY_SLIDER \fP\fP
.TP
\fB\fIID_NEW_SENSITIVITY_TEXT \fP\fP
.TP
\fB\fIID_FREQ_SLIDER \fP\fP
.TP
\fB\fIID_FREQ_TEXT \fP\fP
.TP
\fB\fIEND_OF_BASIC_SLIDERS \fP\fP
.TP
\fB\fIEND_OF_SLIDERS \fP\fP
.TP
\fB\fIFIRST_SLIDER \fP\fP
.PP
Definition at line 1349 of file NoiseReduction\&.cpp\&.
.SS "anonymous enum"

.PP
Definition at line 142 of file NoiseReduction\&.cpp\&.
.SS "enum \fBDiscriminationMethod\fP"

.PP
Definition at line 88 of file NoiseReduction\&.cpp\&.
.SS "enum \fBNoiseReductionChoice\fP"

.PP
Definition at line 147 of file NoiseReduction\&.cpp\&.
.SS "enum \fBWindowTypes\fP"

.PP
Definition at line 109 of file NoiseReduction\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
