.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/Normalize.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/Normalize.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include 'Normalize\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/valgen\&.h>\fP
.br
\fC#include '\&.\&./Internat\&.h'\fP
.br
\fC#include '\&.\&./Prefs\&.h'\fP
.br
\fC#include '\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include '\&.\&./WaveTrack\&.h'\fP
.br
\fC#include '\&.\&./widgets/valnum\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBParam\fP (Level, double, \fBXO\fP('Level'),\-1\&.0,\-145\&.0, 0\&.0, 1)"
.br
.ti -1c
.RI "\fBParam\fP (RemoveDC, \fBbool\fP, \fBXO\fP('RemoveDcOffset'), true, \fBfalse\fP, \fBtrue\fP, 1)"
.br
.ti -1c
.RI "\fBParam\fP (ApplyGain, \fBbool\fP, \fBXO\fP('ApplyGain'), true, \fBfalse\fP, \fBtrue\fP, 1)"
.br
.ti -1c
.RI "\fBParam\fP (StereoInd, \fBbool\fP, \fBXO\fP('StereoIndependent'), false, \fBfalse\fP, \fBtrue\fP, 1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Param (Level, double, \fBXO\fP('Level'), \-1\&. 0, \-145\&. 0, 0\&. 0, 1)"

.SS "Param (RemoveDC, \fBbool\fP, \fBXO\fP('RemoveDcOffset'), \fBtrue\fP, \fBfalse\fP, \fBtrue\fP, 1)"

.SS "Param (ApplyGain, \fBbool\fP, \fBXO\fP('ApplyGain'), \fBtrue\fP, \fBfalse\fP, \fBtrue\fP, 1)"

.SS "Param (StereoInd, \fBbool\fP, \fBXO\fP('StereoIndependent'), \fBfalse\fP, \fBfalse\fP, \fBtrue\fP, 1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
