.TH "C:/_dev/OpenU/Audacity/audacity/src/NoteTrack.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/NoteTrack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'Audacity\&.h'\fP
.br
\fC#include 'Experimental\&.h'\fP
.br
\fC#include 'Track\&.h'\fP
.br
\fC#include 'effects/TimeWarper\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSonifyBeginSonification\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndSonification\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginNoteBackground\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndNoteBackground\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginNoteForeground\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndNoteForeground\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginMeasures\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndMeasures\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginSerialize\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndSerialize\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginUnserialize\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndUnserialize\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginAutoSave\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndAutoSave\fP()"
.br
.ti -1c
.RI "#define \fBSonifyBeginModifyState\fP()"
.br
.ti -1c
.RI "#define \fBSonifyEndModifyState\fP()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SonifyBeginAutoSave()"

.PP
Definition at line 235 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginMeasures()"

.PP
Definition at line 229 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginModifyState()"

.PP
Definition at line 237 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginNoteBackground()"

.PP
Definition at line 225 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginNoteForeground()"

.PP
Definition at line 227 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginSerialize()"

.PP
Definition at line 231 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginSonification()"

.PP
Definition at line 223 of file NoteTrack\&.h\&.
.SS "#define SonifyBeginUnserialize()"

.PP
Definition at line 233 of file NoteTrack\&.h\&.
.SS "#define SonifyEndAutoSave()"

.PP
Definition at line 236 of file NoteTrack\&.h\&.
.SS "#define SonifyEndMeasures()"

.PP
Definition at line 230 of file NoteTrack\&.h\&.
.SS "#define SonifyEndModifyState()"

.PP
Definition at line 238 of file NoteTrack\&.h\&.
.SS "#define SonifyEndNoteBackground()"

.PP
Definition at line 226 of file NoteTrack\&.h\&.
.SS "#define SonifyEndNoteForeground()"

.PP
Definition at line 228 of file NoteTrack\&.h\&.
.SS "#define SonifyEndSerialize()"

.PP
Definition at line 232 of file NoteTrack\&.h\&.
.SS "#define SonifyEndSonification()"

.PP
Definition at line 224 of file NoteTrack\&.h\&.
.SS "#define SonifyEndUnserialize()"

.PP
Definition at line 234 of file NoteTrack\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
