.TH "NumberScale::Iterator" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumberScale::Iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NumberScale\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (\fBNumberScaleType\fP type, float step, float \fBvalue\fP, float unit)"
.br
.ti -1c
.RI "float \fBoperator*\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file NumberScale\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NumberScale::Iterator::Iterator (\fBNumberScaleType\fP type, float step, float value, float unit)\fC [inline]\fP"

.PP
Definition at line 187 of file NumberScale\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "float NumberScale::Iterator::operator* () const\fC [inline]\fP"

.PP
Definition at line 192 of file NumberScale\&.h\&.
.SS "\fBIterator\fP& NumberScale::Iterator::operator++ ()\fC [inline]\fP"

.PP
Definition at line 211 of file NumberScale\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
