.TH "C:/_dev/OpenU/Audacity/audacity/src/widgets/NumericTextCtrl.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/widgets/NumericTextCtrl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/dynarray\&.h>\fP
.br
\fC#include <wx/event\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include '\&.\&./Audacity\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumericConverter\fP"
.br
.RI "\fI\fBNumericConverter\fP provides the advanced formatting control used in the selection bar of Audacity\&. \fP"
.ti -1c
.RI "class \fBNumericTextCtrl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDECLARE_EXPORTED_EVENT_TYPE\fP (AUDACITY_DLL_API, EVT_TIMETEXTCTRL_UPDATED,\-1)"
.br
.ti -1c
.RI "\fBDECLARE_EXPORTED_EVENT_TYPE\fP (AUDACITY_DLL_API, EVT_FREQUENCYTEXTCTRL_UPDATED,\-1)"
.br
.ti -1c
.RI "\fBDECLARE_EXPORTED_EVENT_TYPE\fP (AUDACITY_DLL_API, EVT_BANDWIDTHTEXTCTRL_UPDATED,\-1)"
.br
.ti -1c
.RI "\fBWX_DECLARE_OBJARRAY\fP (\fBNumericField\fP, NumericFieldArray)"
.br
.ti -1c
.RI "\fBWX_DECLARE_OBJARRAY\fP (\fBDigitInfo\fP, DigitInfoArray)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_TIMETEXTCTRL_UPDATED, \- 1)"

.SS "DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_FREQUENCYTEXTCTRL_UPDATED, \- 1)"

.SS "DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_BANDWIDTHTEXTCTRL_UPDATED, \- 1)"

.SS "WX_DECLARE_OBJARRAY (\fBNumericField\fP, NumericFieldArray)"

.SS "WX_DECLARE_OBJARRAY (\fBDigitInfo\fP, DigitInfoArray)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
