.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/nyq-osc-server.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/nyq-osc-server.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBnosc_init\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBnosc_poll\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnosc_finish\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP nosc_finish ()"

.SS "\fBint\fP nosc_init ()"

.SS "\fBint\fP nosc_poll ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
