.TH "Nyq::OneZero" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nyq::OneZero \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OneZero\&.h>\fP
.PP
Inherits \fBNyq::Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneZero\fP ()"
.br
.RI "\fIDefault constructor creates a first-order low-pass filter\&. \fP"
.ti -1c
.RI "\fBOneZero\fP (\fBStkFloat\fP theZero)"
.br
.RI "\fIOverloaded constructor which sets the zero position during instantiation\&. \fP"
.ti -1c
.RI "\fB~OneZero\fP ()"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBclear\fP (\fBvoid\fP)"
.br
.RI "\fIClears the internal state of the filter\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetB0\fP (\fBStkFloat\fP b0)"
.br
.RI "\fISet the b[0] coefficient value\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetB1\fP (\fBStkFloat\fP b1)"
.br
.RI "\fISet the b[1] coefficient value\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetZero\fP (\fBStkFloat\fP theZero)"
.br
.RI "\fISet the zero position in the z-plane\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetGain\fP (\fBStkFloat\fP gain)"
.br
.RI "\fISet the filter gain\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBgetGain\fP (\fBvoid\fP) \fBconst\fP "
.br
.RI "\fIReturn the current filter gain\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBlastOut\fP (\fBvoid\fP) \fBconst\fP "
.br
.RI "\fIReturn the last computed output value\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBtick\fP (\fBStkFloat\fP sample)"
.br
.RI "\fIInput one sample to the filter and return one output\&. \fP"
.ti -1c
.RI "\fBStkFrames\fP & \fBtick\fP (\fBStkFrames\fP &frames, unsigned \fBint\fP channel=0)"
.br
.RI "\fITake a channel of the \fBStkFrames\fP object as inputs to the filter and replace with corresponding outputs\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file OneZero\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OneZero::OneZero ()"

.PP
Default constructor creates a first-order low-pass filter\&. 
.PP
Definition at line 19 of file OneZero\&.cpp\&.
.SS "OneZero::OneZero (\fBStkFloat\fP theZero)"

.PP
Overloaded constructor which sets the zero position during instantiation\&. 
.PP
Definition at line 26 of file OneZero\&.cpp\&.
.SS "OneZero::~OneZero (\fBvoid\fP)"

.PP
Class destructor\&. 
.PP
Definition at line 41 of file OneZero\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP OneZero::clear (\fBvoid\fP)"

.PP
Clears the internal state of the filter\&. 
.PP
Definition at line 45 of file OneZero\&.cpp\&.
.SS "\fBStkFloat\fP OneZero::getGain (\fBvoid\fP) const\fC [virtual]\fP"

.PP
Return the current filter gain\&. 
.PP
Reimplemented from \fBNyq::Filter\fP\&.
.PP
Definition at line 76 of file OneZero\&.cpp\&.
.SS "\fBStkFloat\fP OneZero::lastOut (\fBvoid\fP) const\fC [virtual]\fP"

.PP
Return the last computed output value\&. 
.PP
Reimplemented from \fBNyq::Filter\fP\&.
.PP
Definition at line 81 of file OneZero\&.cpp\&.
.SS "\fBvoid\fP OneZero::setB0 (\fBStkFloat\fP b0)"

.PP
Set the b[0] coefficient value\&. 
.PP
Definition at line 50 of file OneZero\&.cpp\&.
.SS "\fBvoid\fP OneZero::setB1 (\fBStkFloat\fP b1)"

.PP
Set the b[1] coefficient value\&. 
.PP
Definition at line 55 of file OneZero\&.cpp\&.
.SS "\fBvoid\fP OneZero::setGain (\fBStkFloat\fP gain)\fC [virtual]\fP"

.PP
Set the filter gain\&. The gain is applied at the filter input and does not affect the coefficient values\&. The default gain value is 1\&.0\&. 
.PP
Reimplemented from \fBNyq::Filter\fP\&.
.PP
Definition at line 71 of file OneZero\&.cpp\&.
.SS "\fBvoid\fP OneZero::setZero (\fBStkFloat\fP theZero)"

.PP
Set the zero position in the z-plane\&. This method sets the zero position along the real-axis of the z-plane and normalizes the coefficients for a maximum gain of one\&. A positive zero value produces a high-pass filter, while a negative zero value produces a low-pass filter\&. This method does not affect the filter \fIgain\fP value\&. 
.PP
Definition at line 60 of file OneZero\&.cpp\&.
.SS "\fBStkFloat\fP OneZero::tick (\fBStkFloat\fP sample)\fC [virtual]\fP"

.PP
Input one sample to the filter and return one output\&. 
.PP
Reimplemented from \fBNyq::Filter\fP\&.
.PP
Definition at line 86 of file OneZero\&.cpp\&.
.SS "\fBStkFrames\fP & OneZero::tick (\fBStkFrames\fP & frames, unsigned \fBint\fP channel = \fC0\fP)\fC [virtual]\fP"

.PP
Take a channel of the \fBStkFrames\fP object as inputs to the filter and replace with corresponding outputs\&. The \fCchannel\fP argument should be zero or greater (the first channel is specified by 0)\&. An \fBStkError\fP will be thrown if the \fCchannel\fP argument is equal to or greater than the number of channels in the \fBStkFrames\fP object\&. 
.PP
Reimplemented from \fBNyq::Filter\fP\&.
.PP
Definition at line 95 of file OneZero\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
