.TH "Nyq::ModalBar" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nyq::ModalBar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModalBar\&.h>\fP
.PP
Inherits \fBNyq::Modal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModalBar\fP ()"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "\fB~ModalBar\fP ()"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetStickHardness\fP (\fBStkFloat\fP hardness)"
.br
.RI "\fISet stick hardness (0\&.0 - 1\&.0)\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetStrikePosition\fP (\fBStkFloat\fP \fBposition\fP)"
.br
.RI "\fISet stick position (0\&.0 - 1\&.0)\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetPreset\fP (\fBint\fP preset)"
.br
.RI "\fISelect a bar preset (currently modulo 9)\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetModulationDepth\fP (\fBStkFloat\fP mDepth)"
.br
.RI "\fISet the modulation (vibrato) depth\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBcontrolChange\fP (\fBint\fP number, \fBStkFloat\fP \fBvalue\fP)"
.br
.RI "\fIPerform the control change specified by \fInumber\fP and \fIvalue\fP (0\&.0 - 128\&.0)\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file ModalBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModalBar::ModalBar ()"

.PP
Class constructor\&. 
.PP
Definition at line 37 of file ModalBar\&.cpp\&.
.SS "ModalBar::~ModalBar ()"

.PP
Class destructor\&. 
.PP
Definition at line 48 of file ModalBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ModalBar::controlChange (\fBint\fP number, \fBStkFloat\fP value)\fC [virtual]\fP"

.PP
Perform the control change specified by \fInumber\fP and \fIvalue\fP (0\&.0 - 128\&.0)\&. 
.PP
Implements \fBNyq::Modal\fP\&.
.PP
Definition at line 161 of file ModalBar\&.cpp\&.
.SS "\fBvoid\fP Nyq::ModalBar::setModulationDepth (\fBStkFloat\fP mDepth)"

.PP
Set the modulation (vibrato) depth\&. 
.SS "\fBvoid\fP ModalBar::setPreset (\fBint\fP preset)"

.PP
Select a bar preset (currently modulo 9)\&. 
.PP
Definition at line 97 of file ModalBar\&.cpp\&.
.SS "\fBvoid\fP ModalBar::setStickHardness (\fBStkFloat\fP hardness)"

.PP
Set stick hardness (0\&.0 - 1\&.0)\&. 
.PP
Definition at line 53 of file ModalBar\&.cpp\&.
.SS "\fBvoid\fP ModalBar::setStrikePosition (\fBStkFloat\fP position)"

.PP
Set stick position (0\&.0 - 1\&.0)\&. 
.PP
Definition at line 71 of file ModalBar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
