.TH "Nyq::Effect" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nyq::Effect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Effect\&.h>\fP
.PP
Inherits \fBNyq::Stk\fP\&.
.PP
Inherited by \fBNyq::Chorus\fP, \fBNyq::JCRev\fP, \fBNyq::NRev\fP, \fBNyq::PitShift\fP, and \fBNyq::PRCRev\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffect\fP ()"
.br
.RI "\fIClass constructor\&. \fP"
.ti -1c
.RI "virtual \fB~Effect\fP ()"
.br
.RI "\fIClass destructor\&. \fP"
.ti -1c
.RI "virtual \fBvoid\fP \fBclear\fP ()=0"
.br
.RI "\fIReset and clear all internal state\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetEffectMix\fP (\fBStkFloat\fP mix)"
.br
.RI "\fISet the mixture of input and 'effected' levels in the output (0\&.0 = input only, 1\&.0 = reverb only)\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBlastOut\fP () \fBconst\fP "
.br
.RI "\fIReturn the last output value\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBlastOutLeft\fP () \fBconst\fP "
.br
.RI "\fIReturn the last left output value\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBlastOutRight\fP () \fBconst\fP "
.br
.RI "\fIReturn the last right output value\&. \fP"
.ti -1c
.RI "\fBStkFloat\fP \fBtick\fP (\fBStkFloat\fP input)"
.br
.RI "\fITake one sample input and compute one sample of output\&. \fP"
.ti -1c
.RI "\fBStkFrames\fP & \fBtick\fP (\fBStkFrames\fP &frames, unsigned \fBint\fP channel=0)"
.br
.RI "\fITake a channel of the \fBStkFrames\fP object as inputs to the effect and replace with corresponding outputs\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBStkFloat\fP \fBcomputeSample\fP (\fBStkFloat\fP input)=0"
.br
.ti -1c
.RI "\fBbool\fP \fBisPrime\fP (\fBint\fP number)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBStkFloat\fP \fBlastOutput_\fP [2]"
.br
.ti -1c
.RI "\fBStkFloat\fP \fBeffectMix_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file Effect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Effect::Effect ()"

.PP
Class constructor\&. 
.PP
Definition at line 17 of file Effect\&.cpp\&.
.SS "Effect::~Effect ()\fC [virtual]\fP"

.PP
Class destructor\&. 
.PP
Definition at line 21 of file Effect\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvoid\fP Nyq::Effect::clear ()\fC [pure virtual]\fP"

.PP
Reset and clear all internal state\&. 
.PP
Implemented in \fBNyq::NRev\fP, \fBNyq::JCRev\fP, \fBNyq::PRCRev\fP, \fBNyq::Chorus\fP, and \fBNyq::PitShift\fP\&.
.SS "virtual \fBStkFloat\fP Nyq::Effect::computeSample (\fBStkFloat\fP input)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBNyq::NRev\fP, \fBNyq::Chorus\fP, \fBNyq::JCRev\fP, \fBNyq::PRCRev\fP, and \fBNyq::PitShift\fP\&.
.SS "\fBbool\fP Effect::isPrime (\fBint\fP number)\fC [protected]\fP"

.PP
Definition at line 89 of file Effect\&.cpp\&.
.SS "\fBStkFloat\fP Effect::lastOut (\fBvoid\fP) const"

.PP
Return the last output value\&. 
.PP
Definition at line 41 of file Effect\&.cpp\&.
.SS "\fBStkFloat\fP Effect::lastOutLeft () const"

.PP
Return the last left output value\&. 
.PP
Definition at line 46 of file Effect\&.cpp\&.
.SS "\fBStkFloat\fP Effect::lastOutRight () const"

.PP
Return the last right output value\&. 
.PP
Definition at line 51 of file Effect\&.cpp\&.
.SS "\fBvoid\fP Effect::setEffectMix (\fBStkFloat\fP mix)"

.PP
Set the mixture of input and 'effected' levels in the output (0\&.0 = input only, 1\&.0 = reverb only)\&. 
.PP
Definition at line 25 of file Effect\&.cpp\&.
.SS "\fBStkFloat\fP Effect::tick (\fBStkFloat\fP input)"

.PP
Take one sample input and compute one sample of output\&. 
.PP
Definition at line 56 of file Effect\&.cpp\&.
.SS "\fBStkFrames\fP & Effect::tick (\fBStkFrames\fP & frames, unsigned \fBint\fP channel = \fC0\fP)"

.PP
Take a channel of the \fBStkFrames\fP object as inputs to the effect and replace with corresponding outputs\&. The \fCchannel\fP argument should be zero or greater (the first channel is specified by 0)\&. An \fBStkError\fP will be thrown if the \fCchannel\fP argument is equal to or greater than the number of channels in the \fBStkFrames\fP object\&. 
.PP
Definition at line 61 of file Effect\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStkFloat\fP Nyq::Effect::effectMix_\fC [protected]\fP"

.PP
Definition at line 67 of file Effect\&.h\&.
.SS "\fBStkFloat\fP Nyq::Effect::lastOutput_[2]\fC [protected]\fP"

.PP
Definition at line 66 of file Effect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
