.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyx.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyx.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBnyx_returns_start_and_end_time\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint\fP(* \fBnyx_audio_callback\fP) (float *\fBbuffer\fP, \fBint\fP channel, long \fBstart\fP, long \fBlen\fP, long totlen, \fBvoid\fP *userdata)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBnyx_output_callback\fP) (\fBint\fP \fBc\fP, \fBvoid\fP *userdata)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBnyx_os_callback\fP) (\fBvoid\fP *userdata)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBnyx_rval\fP { \fBnyx_error\fP, \fBnyx_audio\fP, \fBnyx_int\fP, \fBnyx_double\fP, \fBnyx_string\fP, \fBnyx_labels\fP, \fBnyx_error\fP, \fBnyx_audio\fP, \fBnyx_int\fP, \fBnyx_double\fP, \fBnyx_string\fP, \fBnyx_labels\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBnyx_init\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_cleanup\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_set_xlisp_path\fP (\fBconst\fP char *path)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_capture_output\fP (\fBnyx_output_callback\fP callback, \fBvoid\fP *userdata)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_set_os_callback\fP (\fBnyx_os_callback\fP callback, \fBvoid\fP *userdata)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_stop\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_break\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_continue\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_set_audio_params\fP (double \fBrate\fP, long \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_set_input_audio\fP (\fBnyx_audio_callback\fP callback, \fBvoid\fP *userdata, \fBint\fP num_channels, long \fBlen\fP, double \fBrate\fP)"
.br
.ti -1c
.RI "char * \fBnyx_get_audio_name\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_set_audio_name\fP (\fBconst\fP char *\fBname\fP)"
.br
.ti -1c
.RI "\fBnyx_rval\fP \fBnyx_eval_expression\fP (\fBconst\fP char *expr)"
.br
.ti -1c
.RI "\fBint\fP \fBnyx_get_audio_num_channels\fP ()"
.br
.RI "\fIGet the number of channels in the Nyquist audio object\&. \fP"
.ti -1c
.RI "\fBint\fP \fBnyx_get_audio\fP (\fBnyx_audio_callback\fP callback, \fBvoid\fP *userdata)"
.br
.ti -1c
.RI "\fBint\fP \fBnyx_get_int\fP ()"
.br
.ti -1c
.RI "double \fBnyx_get_double\fP ()"
.br
.ti -1c
.RI "\fBconst\fP char * \fBnyx_get_string\fP ()"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBnyx_get_num_labels\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyx_get_label\fP (unsigned \fBint\fP index, double *\fBstart_time\fP, double *end_time, \fBconst\fP char **\fBlabel\fP)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBnyx_get_error_str\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define nyx_returns_start_and_end_time   1"

.PP
Definition at line 19 of file nyx\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint\fP(* nyx_audio_callback) (float *\fBbuffer\fP, \fBint\fP channel, long \fBstart\fP, long \fBlen\fP, long totlen, \fBvoid\fP *userdata)"

.PP
Definition at line 35 of file nyx\&.h\&.
.SS "typedef \fBvoid\fP(* nyx_os_callback) (\fBvoid\fP *userdata)"

.PP
Definition at line 44 of file nyx\&.h\&.
.SS "typedef \fBvoid\fP(* nyx_output_callback) (\fBint\fP \fBc\fP, \fBvoid\fP *userdata)"

.PP
Definition at line 41 of file nyx\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBnyx_rval\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInyx_error \fP\fP
.TP
\fB\fInyx_audio \fP\fP
.TP
\fB\fInyx_int \fP\fP
.TP
\fB\fInyx_double \fP\fP
.TP
\fB\fInyx_string \fP\fP
.TP
\fB\fInyx_labels \fP\fP
.TP
\fB\fInyx_error \fP\fP
.TP
\fB\fInyx_audio \fP\fP
.TP
\fB\fInyx_int \fP\fP
.TP
\fB\fInyx_double \fP\fP
.TP
\fB\fInyx_string \fP\fP
.TP
\fB\fInyx_labels \fP\fP
.PP
Definition at line 21 of file nyx\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP nyx_break ()"

.PP
Definition at line 1056 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_capture_output (\fBnyx_output_callback\fP callback, \fBvoid\fP * userdata)"

.PP
Definition at line 550 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_cleanup ()"

.PP
Definition at line 467 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_continue ()"

.PP
Definition at line 1062 of file nyx\&.c\&.
.SS "\fBnyx_rval\fP nyx_eval_expression (\fBconst\fP char * expr)"

.PP
Definition at line 741 of file nyx\&.c\&.
.SS "\fBint\fP nyx_get_audio (\fBnyx_audio_callback\fP callback, \fBvoid\fP * userdata)"

.PP
Definition at line 814 of file nyx\&.c\&.
.SS "char* nyx_get_audio_name ()"

.PP
Definition at line 597 of file nyx\&.c\&.
.SS "\fBint\fP nyx_get_audio_num_channels ()"

.PP
Get the number of channels in the Nyquist audio object\&. 
.PP
\fBReturns:\fP
.RS 4
The positive integer number of audio channels in the Nyquist audio object, 0 if not an audio object, -1 one if Nyquist returns an array of samples (which we can't handle) 
.RE
.PP

.PP
Definition at line 803 of file nyx\&.c\&.
.SS "double nyx_get_double ()"

.PP
Definition at line 959 of file nyx\&.c\&.
.SS "\fBconst\fP char* nyx_get_error_str ()"

.PP
Definition at line 1039 of file nyx\&.c\&.
.SS "\fBint\fP nyx_get_int ()"

.PP
Definition at line 951 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_get_label (unsigned \fBint\fP index, double * start_time, double * end_time, \fBconst\fP char ** label)"

.PP
Definition at line 991 of file nyx\&.c\&.
.SS "unsigned \fBint\fP nyx_get_num_labels ()"

.PP
Definition at line 975 of file nyx\&.c\&.
.SS "\fBconst\fP char* nyx_get_string ()"

.PP
Definition at line 967 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_init ()"

.PP
Definition at line 428 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_set_audio_name (\fBconst\fP char * name)"

.PP
Definition at line 606 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_set_audio_params (double rate, long len)"

.PP
Definition at line 556 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_set_input_audio (\fBnyx_audio_callback\fP callback, \fBvoid\fP * userdata, \fBint\fP num_channels, long len, double rate)"

.PP
Definition at line 577 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_set_os_callback (\fBnyx_os_callback\fP callback, \fBvoid\fP * userdata)"

.PP
Definition at line 1044 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_set_xlisp_path (\fBconst\fP char * path)"

.PP
Definition at line 536 of file nyx\&.c\&.
.SS "\fBvoid\fP nyx_stop ()"

.PP
Definition at line 1050 of file nyx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
