.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/octave_test.m" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/octave_test.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprintf\fP ('    Running Octave tests                     : ')"
.br
.ti -1c
.RI "\fBfflush\fP (stdout)"
.br
.ti -1c
.RI "\fBsfwrite\fP (\fBfilename\fP, \fBdata_out\fP, \fBsrate_out\fP, \fBfmt_out\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfilename\fP = 'whatever'"
.br
.ti -1c
.RI "\fBsrate_out\fP = 32000"
.br
.ti -1c
.RI "\fBfmt_out\fP = 'wav\-float'"
.br
.ti -1c
.RI "\fBt\fP = (2 * pi / \fBsrate_out\fP * (0:\fBsrate_out\fP\-1))'"
.br
.ti -1c
.RI "\fBdata_out\fP = \fBsin\fP (440\&.0 * \fBt\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "fflush (stdout)"

.SS "printf (' Running Octave tests : ')"

.SS "sfwrite (\fBfilename\fP, \fBdata_out\fP, \fBsrate_out\fP, \fBfmt_out\fP)"

.SH "Variable Documentation"
.PP 
.SS "data_out = \fBsin\fP (440\&.0 * \fBt\fP)"

.PP
Definition at line 27 of file octave_test\&.m\&.
.SS "filename = 'whatever'"

.PP
Definition at line 22 of file octave_test\&.m\&.
.SS "fmt_out = 'wav\-float'"

.PP
Definition at line 24 of file octave_test\&.m\&.
.SS "srate_out = 32000"

.PP
Definition at line 23 of file octave_test\&.m\&.
.SS "t = (2 * pi / \fBsrate_out\fP * (0:\fBsrate_out\fP\-1))'"

.PP
Definition at line 26 of file octave_test\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
