.TH "ODFlacDecoder" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ODFlacDecoder \- class to decode a particular file (one per file)\&. Saves info such as filename and length (after the header is read\&.)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ODDecodeFlacTask\&.h>\fP
.PP
Inherits \fBODFileDecoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBODFlacDecoder\fP (\fBconst\fP wxString &fileName)"
.br
.RI "\fIThis should handle unicode converted to UTF-8 on mac/linux, but OD TODO:check on windows\&. \fP"
.ti -1c
.RI "virtual \fB~ODFlacDecoder\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBDecode\fP (\fBSampleBuffer\fP &\fBdata\fP, \fBsampleFormat\fP &\fBformat\fP, \fBsampleCount\fP \fBstart\fP, \fBsampleCount\fP \fBlen\fP, unsigned \fBint\fP channel) override"
.br
.ti -1c
.RI "\fBbool\fP \fBReadHeader\fP () override"
.br
.ti -1c
.RI "\fBODFLACFile\fP * \fBGetFlacFile\fP ()"
.br
.RI "\fI\fBFLAC\fP specific file (inherited from \fBFLAC::Decoder::File\fP) \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBODFLACFile\fP"
.br
.ti -1c
.RI "class \fBFLACImportFileHandle\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
class to decode a particular file (one per file)\&. Saves info such as filename and length (after the header is read\&.) 
.PP
Definition at line 94 of file ODDecodeFlacTask\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ODFlacDecoder::ODFlacDecoder (\fBconst\fP wxString & fileName)\fC [inline]\fP"

.PP
This should handle unicode converted to UTF-8 on mac/linux, but OD TODO:check on windows\&. 
.PP
Definition at line 99 of file ODDecodeFlacTask\&.h\&.
.SS "ODFlacDecoder::~ODFlacDecoder ()\fC [virtual]\fP"

.PP
Definition at line 266 of file ODDecodeFlacTask\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP ODFlacDecoder::Decode (\fBSampleBuffer\fP & data, \fBsampleFormat\fP & format, \fBsampleCount\fP start, \fBsampleCount\fP len, unsigned \fBint\fP channel)\fC [override]\fP, \fC [virtual]\fP"
Decodes the samples for this blockfile from the real file into a float buffer\&. This is file specific, so subclasses must implement this only\&. the buffer was defined like samplePtr sampleData = NewSamples(mLen, floatSample); this->ReadData(sampleData, floatSample, 0, mLen); This class should call \fBReadHeader()\fP first, so it knows the length, and can prepare the file object if it needs to\&. 
.PP
Implements \fBODFileDecoder\fP\&.
.PP
Definition at line 169 of file ODDecodeFlacTask\&.cpp\&.
.SS "\fBODFLACFile\fP * ODFlacDecoder::GetFlacFile ()"

.PP
\fBFLAC\fP specific file (inherited from \fBFLAC::Decoder::File\fP) 
.PP
Definition at line 261 of file ODDecodeFlacTask\&.cpp\&.
.SS "\fBbool\fP ODFlacDecoder::ReadHeader ()\fC [override]\fP, \fC [virtual]\fP"
Read header\&. Subclasses must override\&. Probably should save the info somewhere\&. Ideally called once per decoding of a file\&. This complicates the task because
.PP
Read header\&. Subclasses must override\&. Probably should save the info somewhere\&. Ideally called once per decoding of a file\&. This complicates the task because returns true if the file exists and the header was read alright\&. 
.PP
Implements \fBODFileDecoder\fP\&.
.PP
Definition at line 216 of file ODDecodeFlacTask\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBFLACImportFileHandle\fP\fC [friend]\fP"

.PP
Definition at line 120 of file ODDecodeFlacTask\&.h\&.
.SS "friend class \fBODFLACFile\fP\fC [friend]\fP"

.PP
Definition at line 96 of file ODDecodeFlacTask\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
