.TH "ODFLACFile" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ODFLACFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ODDecodeFlacTask\&.h>\fP
.PP
Inherits \fBFLAC::Decoder::File\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBODFLACFile\fP (\fBODFlacDecoder\fP *decoder)"
.br
.ti -1c
.RI "\fBbool\fP \fBget_was_error\fP () \fBconst\fP "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFLAC__StreamDecoderWriteStatus\fP \fBwrite_callback\fP (\fBconst\fP \fBFLAC__Frame\fP *frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP \fBbuffer\fP[]) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBmetadata_callback\fP (\fBconst\fP \fBFLAC__StreamMetadata\fP *metadata) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBerror_callback\fP (\fBFLAC__StreamDecoderErrorStatus\fP \fBstatus\fP) override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBODFlacDecoder\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 64 of file ODDecodeFlacTask\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ODFLACFile::ODFLACFile (\fBODFlacDecoder\fP * decoder)\fC [inline]\fP"

.PP
Definition at line 67 of file ODDecodeFlacTask\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ODFLACFile::error_callback (\fBFLAC__StreamDecoderErrorStatus\fP status)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 85 of file ODDecodeFlacTask\&.cpp\&.
.SS "\fBbool\fP ODFLACFile::get_was_error () const\fC [inline]\fP"

.PP
Definition at line 75 of file ODDecodeFlacTask\&.h\&.
.SS "\fBvoid\fP ODFLACFile::metadata_callback (\fBconst\fP \fBFLAC__StreamMetadata\fP * metadata)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 45 of file ODDecodeFlacTask\&.cpp\&.
.SS "\fBFLAC__StreamDecoderWriteStatus\fP ODFLACFile::write_callback (\fBconst\fP \fBFLAC__Frame\fP * frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP buffer[])\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 109 of file ODDecodeFlacTask\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBODFlacDecoder\fP\fC [friend]\fP"

.PP
Definition at line 80 of file ODDecodeFlacTask\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
