.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/offset.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/offset.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'offset\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBoffset_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBoffset_susp_struct\fP \fBoffset_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBoffset_susp_struct\fP * \fBoffset_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBoffset_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoffset_n_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoffset_s_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoffset_toss_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoffset_mark\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoffset_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_offset\fP (\fBsound_type\fP s1, double \fBoffset\fP)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_offset\fP (\fBsound_type\fP s1, double \fBoffset\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBoffset_susp_struct\fP  \fBoffset_susp_node\fP"

.SS "typedef struct \fBoffset_susp_struct\fP * \fBoffset_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP offset_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 238 of file offset\&.c\&.
.SS "\fBvoid\fP offset_mark (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 231 of file offset\&.c\&.
.SS "\fBvoid\fP offset_n_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 27 of file offset\&.c\&.
.SS "\fBvoid\fP offset_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 246 of file offset\&.c\&.
.SS "\fBvoid\fP offset_s_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 118 of file offset\&.c\&.
.SS "\fBvoid\fP offset_toss_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 210 of file offset\&.c\&.
.SS "\fBsound_type\fP snd_make_offset (\fBsound_type\fP s1, double offset)"

.PP
Definition at line 255 of file offset\&.c\&.
.SS "\fBsound_type\fP snd_offset (\fBsound_type\fP s1, double offset)"

.PP
Definition at line 302 of file offset\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
