.TH "ogg_sync_state" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ogg_sync_state \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ogg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstorage\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfill\fP"
.br
.ti -1c
.RI "\fBint\fP \fBreturned\fP"
.br
.ti -1c
.RI "\fBint\fP \fBunsynced\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheaderbytes\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbodybytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 105 of file ogg\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP ogg_sync_state::bodybytes"

.PP
Definition at line 113 of file ogg\&.h\&.
.SS "unsigned char* ogg_sync_state::data"

.PP
Definition at line 106 of file ogg\&.h\&.
.SS "\fBint\fP ogg_sync_state::fill"

.PP
Definition at line 108 of file ogg\&.h\&.
.SS "\fBint\fP ogg_sync_state::headerbytes"

.PP
Definition at line 112 of file ogg\&.h\&.
.SS "\fBint\fP ogg_sync_state::returned"

.PP
Definition at line 109 of file ogg\&.h\&.
.SS "\fBint\fP ogg_sync_state::storage"

.PP
Definition at line 107 of file ogg\&.h\&.
.SS "\fBint\fP ogg_sync_state::unsynced"

.PP
Definition at line 111 of file ogg\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
