.TH "OGGImportPlugin" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OGGImportPlugin \- An \fBImportPlugin\fP for OGG data\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
An \fBImportPlugin\fP for OGG data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
