.TH "OggVorbis_File" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OggVorbis_File \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vorbisfile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBdatasource\fP"
.br
.ti -1c
.RI "\fBint\fP \fBseekable\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBend\fP"
.br
.ti -1c
.RI "\fBogg_sync_state\fP \fBoy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlinks\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP * \fBoffsets\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP * \fBdataoffsets\fP"
.br
.ti -1c
.RI "long * \fBserialnos\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP * \fBpcmlengths\fP"
.br
.ti -1c
.RI "\fBvorbis_info\fP * \fBvi\fP"
.br
.ti -1c
.RI "\fBvorbis_comment\fP * \fBvc\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBpcm_offset\fP"
.br
.ti -1c
.RI "\fBint\fP \fBready_state\fP"
.br
.ti -1c
.RI "long \fBcurrent_serialno\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcurrent_link\fP"
.br
.ti -1c
.RI "double \fBbittrack\fP"
.br
.ti -1c
.RI "double \fBsamptrack\fP"
.br
.ti -1c
.RI "\fBogg_stream_state\fP \fBos\fP"
.br
.ti -1c
.RI "\fBvorbis_dsp_state\fP \fBvd\fP"
.br
.ti -1c
.RI "\fBvorbis_block\fP \fBvb\fP"
.br
.ti -1c
.RI "\fBov_callbacks\fP \fBcallbacks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 111 of file vorbisfile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double OggVorbis_File::bittrack"

.PP
Definition at line 136 of file vorbisfile\&.h\&.
.SS "\fBov_callbacks\fP OggVorbis_File::callbacks"

.PP
Definition at line 144 of file vorbisfile\&.h\&.
.SS "\fBint\fP OggVorbis_File::current_link"

.PP
Definition at line 134 of file vorbisfile\&.h\&.
.SS "long OggVorbis_File::current_serialno"

.PP
Definition at line 133 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP* OggVorbis_File::dataoffsets"

.PP
Definition at line 122 of file vorbisfile\&.h\&.
.SS "\fBvoid\fP* OggVorbis_File::datasource"

.PP
Definition at line 112 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP OggVorbis_File::end"

.PP
Definition at line 115 of file vorbisfile\&.h\&.
.SS "\fBint\fP OggVorbis_File::links"

.PP
Definition at line 120 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP OggVorbis_File::offset"

.PP
Definition at line 114 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP* OggVorbis_File::offsets"

.PP
Definition at line 121 of file vorbisfile\&.h\&.
.SS "\fBogg_stream_state\fP OggVorbis_File::os"

.PP
Definition at line 139 of file vorbisfile\&.h\&.
.SS "\fBogg_sync_state\fP OggVorbis_File::oy"

.PP
Definition at line 116 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP OggVorbis_File::pcm_offset"

.PP
Definition at line 131 of file vorbisfile\&.h\&.
.SS "\fBogg_int64_t\fP* OggVorbis_File::pcmlengths"

.PP
Definition at line 124 of file vorbisfile\&.h\&.
.SS "\fBint\fP OggVorbis_File::ready_state"

.PP
Definition at line 132 of file vorbisfile\&.h\&.
.SS "double OggVorbis_File::samptrack"

.PP
Definition at line 137 of file vorbisfile\&.h\&.
.SS "\fBint\fP OggVorbis_File::seekable"

.PP
Definition at line 113 of file vorbisfile\&.h\&.
.SS "long* OggVorbis_File::serialnos"

.PP
Definition at line 123 of file vorbisfile\&.h\&.
.SS "\fBvorbis_block\fP OggVorbis_File::vb"

.PP
Definition at line 142 of file vorbisfile\&.h\&.
.SS "\fBvorbis_comment\fP* OggVorbis_File::vc"

.PP
Definition at line 128 of file vorbisfile\&.h\&.
.SS "\fBvorbis_dsp_state\fP OggVorbis_File::vd"

.PP
Definition at line 141 of file vorbisfile\&.h\&.
.SS "\fBvorbis_info\fP* OggVorbis_File::vi"

.PP
Definition at line 127 of file vorbisfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
