.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/oneshot.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/oneshot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'oneshot\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBoneshot_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBoneshot_susp_struct\fP \fBoneshot_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBoneshot_susp_struct\fP * \fBoneshot_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBoneshot_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoneshot_n_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoneshot_s_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoneshot_toss_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoneshot_mark\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoneshot_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_oneshot\fP (\fBsound_type\fP input, double level, double ontime)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_oneshot\fP (\fBsound_type\fP input, double level, double ontime)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBoneshot_susp_struct\fP  \fBoneshot_susp_node\fP"

.SS "typedef struct \fBoneshot_susp_struct\fP * \fBoneshot_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP oneshot_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 256 of file oneshot\&.c\&.
.SS "\fBvoid\fP oneshot_mark (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 249 of file oneshot\&.c\&.
.SS "\fBvoid\fP oneshot_n_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 29 of file oneshot\&.c\&.
.SS "\fBvoid\fP oneshot_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 264 of file oneshot\&.c\&.
.SS "\fBvoid\fP oneshot_s_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 128 of file oneshot\&.c\&.
.SS "\fBvoid\fP oneshot_toss_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 228 of file oneshot\&.c\&.
.SS "\fBsound_type\fP snd_make_oneshot (\fBsound_type\fP input, double level, double ontime)"

.PP
Definition at line 273 of file oneshot\&.c\&.
.SS "\fBsound_type\fP snd_oneshot (\fBsound_type\fP input, double level, double ontime)"

.PP
Definition at line 322 of file oneshot\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
