.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/metaflac/operations_shorthand_vorbiscomment.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/metaflac/operations_shorthand_vorbiscomment.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'options\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'FLAC/assert\&.h'\fP
.br
\fC#include 'share/grabbag\&.h'\fP
.br
\fC#include 'share/utf8\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'operations_shorthand\&.h'\fP
.br
\fC#include 'share/compat\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBdo_shorthand_operation__vorbis_comment\fP (\fBconst\fP char *\fBfilename\fP, \fBFLAC__bool\fP prefix_with_filename, \fBFLAC__Metadata_Chain\fP *chain, \fBconst\fP \fBOperation\fP *operation, \fBFLAC__bool\fP *needs_write, \fBFLAC__bool\fP raw)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLAC__bool\fP do_shorthand_operation__vorbis_comment (\fBconst\fP char * filename, \fBFLAC__bool\fP prefix_with_filename, \fBFLAC__Metadata_Chain\fP * chain, \fBconst\fP \fBOperation\fP * operation, \fBFLAC__bool\fP * needs_write, \fBFLAC__bool\fP raw)"

.PP
Definition at line 42 of file operations_shorthand_vorbiscomment\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
