.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/FLAC/ordinals.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/FLAC/ordinals.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint8_t\fP \fBFLAC__int8\fP"
.br
.ti -1c
.RI "typedef \fBuint8_t\fP \fBFLAC__uint8\fP"
.br
.ti -1c
.RI "typedef \fBint16_t\fP \fBFLAC__int16\fP"
.br
.ti -1c
.RI "typedef \fBint32_t\fP \fBFLAC__int32\fP"
.br
.ti -1c
.RI "typedef \fBint64_t\fP \fBFLAC__int64\fP"
.br
.ti -1c
.RI "typedef \fBuint16_t\fP \fBFLAC__uint16\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP \fBFLAC__uint32\fP"
.br
.ti -1c
.RI "typedef \fBuint64_t\fP \fBFLAC__uint64\fP"
.br
.ti -1c
.RI "typedef \fBint\fP \fBFLAC__bool\fP"
.br
.ti -1c
.RI "typedef \fBFLAC__uint8\fP \fBFLAC__byte\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define false   0"

.PP
Definition at line 83 of file ordinals\&.h\&.
.SS "#define true   1"

.PP
Definition at line 82 of file ordinals\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint\fP \fBFLAC__bool\fP"

.PP
Definition at line 70 of file ordinals\&.h\&.
.SS "typedef \fBFLAC__uint8\fP \fBFLAC__byte\fP"

.PP
Definition at line 72 of file ordinals\&.h\&.
.SS "typedef \fBint16_t\fP \fBFLAC__int16\fP"

.PP
Definition at line 61 of file ordinals\&.h\&.
.SS "typedef \fBint32_t\fP \fBFLAC__int32\fP"

.PP
Definition at line 62 of file ordinals\&.h\&.
.SS "typedef \fBint64_t\fP \fBFLAC__int64\fP"

.PP
Definition at line 63 of file ordinals\&.h\&.
.SS "typedef \fBint8_t\fP \fBFLAC__int8\fP"

.PP
Definition at line 58 of file ordinals\&.h\&.
.SS "typedef \fBuint16_t\fP \fBFLAC__uint16\fP"

.PP
Definition at line 64 of file ordinals\&.h\&.
.SS "typedef \fBuint32_t\fP \fBFLAC__uint32\fP"

.PP
Definition at line 65 of file ordinals\&.h\&.
.SS "typedef \fBuint64_t\fP \fBFLAC__uint64\fP"

.PP
Definition at line 66 of file ordinals\&.h\&.
.SS "typedef \fBuint8_t\fP \fBFLAC__uint8\fP"

.PP
Definition at line 59 of file ordinals\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
