.TH "our_metadata_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
our_metadata_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP * \fBblocks\fP [64]"
.br
.ti -1c
.RI "unsigned \fBnum_blocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file metadata_manip\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata\fP* our_metadata_struct::blocks[64]"

.PP
Definition at line 64 of file metadata_manip\&.c\&.
.SS "unsigned our_metadata_struct::num_blocks"

.PP
Definition at line 65 of file metadata_manip\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
