.TH "OurFileDecoder" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OurFileDecoder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFLAC::Decoder::File\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOurFileDecoder\fP (\fBbool\fP ignore_metadata)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBignore_metadata_\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBerror_occurred_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "::\fBFLAC__StreamDecoderWriteStatus\fP \fBwrite_callback\fP (\fBconst\fP ::\fBFLAC__Frame\fP *frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP \fBbuffer\fP[])"
.br
.RI "\fIsee FLAC__StreamDecoderWriteCallback \fP"
.ti -1c
.RI "\fBvoid\fP \fBmetadata_callback\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *metadata)"
.br
.RI "\fIsee FLAC__StreamDecoderMetadataCallback \fP"
.ti -1c
.RI "\fBvoid\fP \fBerror_callback\fP (::\fBFLAC__StreamDecoderErrorStatus\fP \fBstatus\fP)"
.br
.RI "\fIsee FLAC__StreamDecoderErrorCallback \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 59 of file metadata_manip\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OurFileDecoder::OurFileDecoder (\fBbool\fP ignore_metadata)\fC [inline]\fP"

.PP
Definition at line 61 of file metadata_manip\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP OurFileDecoder::error_callback (::\fBFLAC__StreamDecoderErrorStatus\fP status)\fC [protected]\fP, \fC [virtual]\fP"

.PP
see FLAC__StreamDecoderErrorCallback 
.PP
Implements \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 492 of file metadata_manip\&.cpp\&.
.SS "\fBvoid\fP OurFileDecoder::metadata_callback (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * metadata)\fC [protected]\fP, \fC [virtual]\fP"

.PP
see FLAC__StreamDecoderMetadataCallback 
.PP
Reimplemented from \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 467 of file metadata_manip\&.cpp\&.
.SS "\fBFLAC__StreamDecoderWriteStatus\fP OurFileDecoder::write_callback (\fBconst\fP ::\fBFLAC__Frame\fP * frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP buffer[])\fC [protected]\fP, \fC [virtual]\fP"

.PP
see FLAC__StreamDecoderWriteCallback 
.PP
Implements \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 452 of file metadata_manip\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP OurFileDecoder::error_occurred_"

.PP
Definition at line 64 of file metadata_manip\&.cpp\&.
.SS "\fBbool\fP OurFileDecoder::ignore_metadata_"

.PP
Definition at line 63 of file metadata_manip\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
