.TH "ovectl_ratemanage_arg" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovectl_ratemanage_arg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vorbisenc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmanagement_active\fP"
.br
.ti -1c
.RI "long \fBbitrate_hard_min\fP"
.br
.ti -1c
.RI "long \fBbitrate_hard_max\fP"
.br
.ti -1c
.RI "double \fBbitrate_hard_window\fP"
.br
.ti -1c
.RI "long \fBbitrate_av_lo\fP"
.br
.ti -1c
.RI "long \fBbitrate_av_hi\fP"
.br
.ti -1c
.RI "double \fBbitrate_av_window\fP"
.br
.ti -1c
.RI "double \fBbitrate_av_window_center\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDeprecated\fP
.RS 4
This is a deprecated interface\&. Please use \fBvorbis_encode_ctl()\fP with the \fBovectl_ratemanage2_arg\fP struct and \fBOV_ECTL_RATEMANAGE2_GET\fP and \fBOV_ECTL_RATEMANAGE2_SET\fP calls in new code\&.
.RE
.PP
.PP
The \fBovectl_ratemanage_arg\fP structure is used with \fBvorbis_encode_ctl()\fP and the \fBOV_ECTL_RATEMANAGE_GET\fP, \fBOV_ECTL_RATEMANAGE_SET\fP, \fBOV_ECTL_RATEMANAGE_AVG\fP, \fBOV_ECTL_RATEMANAGE_HARD\fP calls in order to query and modify specifics of the encoder's bitrate management configuration\&. 
.PP
Definition at line 233 of file vorbisenc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long ovectl_ratemanage_arg::bitrate_av_hi"
soft upper limit (in kilobits per second) above which the average bitrate tracker will start nudging the bitrate lower\&. 
.PP
Definition at line 249 of file vorbisenc\&.h\&.
.SS "long ovectl_ratemanage_arg::bitrate_av_lo"
soft lower limit (in kilobits per second) below which the average bitrate tracker will start nudging the bitrate higher\&. 
.PP
Definition at line 246 of file vorbisenc\&.h\&.
.SS "double ovectl_ratemanage_arg::bitrate_av_window"
the window period (in seconds) used to regulate the average bitrate minimum and maximum\&. 
.PP
Definition at line 252 of file vorbisenc\&.h\&.
.SS "double ovectl_ratemanage_arg::bitrate_av_window_center"
Regulates the relative centering of the average and hard windows; in libvorbis 1\&.0 and 1\&.0\&.1, the hard window regulation overlapped but followed the average window regulation\&. In libvorbis 1\&.1 a bit-reservoir interface replaces the old windowing interface; the older windowing interface is simulated and this field has no effect\&. 
.PP
Definition at line 258 of file vorbisenc\&.h\&.
.SS "long ovectl_ratemanage_arg::bitrate_hard_max"
hard upper limit (in kilobits per second) above which the stream bitrate will never be allowed for any given bitrate_hard_window seconds of time\&. 
.PP
Definition at line 240 of file vorbisenc\&.h\&.
.SS "long ovectl_ratemanage_arg::bitrate_hard_min"
hard lower limit (in kilobits per second) below which the stream bitrate will never be allowed for any given bitrate_hard_window seconds of time\&. 
.PP
Definition at line 237 of file vorbisenc\&.h\&.
.SS "double ovectl_ratemanage_arg::bitrate_hard_window"
the window period (in seconds) used to regulate the hard bitrate minimum and maximum 
.PP
Definition at line 243 of file vorbisenc\&.h\&.
.SS "\fBint\fP ovectl_ratemanage_arg::management_active"
nonzero if bitrate management is active 
.PP
Definition at line 234 of file vorbisenc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
