.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/common/pa_allocation.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/common/pa_allocation.c \- Allocation Group implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pa_allocation\&.h'\fP
.br
\fC#include 'pa_util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPaUtilAllocationGroupLink\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPA_INITIAL_LINK_COUNT_\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPaUtilAllocationGroup\fP * \fBPaUtil_CreateAllocationGroup\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPaUtil_DestroyAllocationGroup\fP (\fBPaUtilAllocationGroup\fP *group)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPaUtil_GroupAllocateMemory\fP (\fBPaUtilAllocationGroup\fP *group, long \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPaUtil_GroupFreeMemory\fP (\fBPaUtilAllocationGroup\fP *group, \fBvoid\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPaUtil_FreeAllAllocations\fP (\fBPaUtilAllocationGroup\fP *group)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allocation Group implementation\&. 


.PP
Definition in file \fBpa_allocation\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PA_INITIAL_LINK_COUNT_   16"

.PP
Definition at line 61 of file pa_allocation\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBPaUtilAllocationGroup\fP* PaUtil_CreateAllocationGroup (\fBvoid\fP)"
Create an allocation group\&. 
.PP
Definition at line 103 of file pa_allocation\&.c\&.
.SS "\fBvoid\fP PaUtil_DestroyAllocationGroup (\fBPaUtilAllocationGroup\fP * group)"
Destroy an allocation group, but not the memory allocated through the group\&. 
.PP
Definition at line 130 of file pa_allocation\&.c\&.
.SS "\fBvoid\fP PaUtil_FreeAllAllocations (\fBPaUtilAllocationGroup\fP * group)"
Free all blocks of memory which have been allocated through the allocation group\&. This function doesn't destroy the group itself\&. 
.PP
Definition at line 220 of file pa_allocation\&.c\&.
.SS "\fBvoid\fP* PaUtil_GroupAllocateMemory (\fBPaUtilAllocationGroup\fP * group, long size)"
Allocate a block of memory though an allocation group\&. 
.PP
Definition at line 146 of file pa_allocation\&.c\&.
.SS "\fBvoid\fP PaUtil_GroupFreeMemory (\fBPaUtilAllocationGroup\fP * group, \fBvoid\fP * buffer)"
Free a block of memory that was previously allocated though an allocation group\&. Calling this function is a relatively time consuming operation\&. Under normal circumstances clients should call PaUtil_FreeAllAllocations to free all allocated blocks simultaneously\&. 
.PP
\fBSee also:\fP
.RS 4
\fBPaUtil_FreeAllAllocations\fP 
.RE
.PP

.PP
Definition at line 183 of file pa_allocation\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
