.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/include/pa_asio.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/include/pa_asio.h \- ASIO-specific PortAudio API extension header file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'portaudio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPaAsioStreamInfo\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPaAsio_GetAvailableLatencyValues\fP   \fBPaAsio_GetAvailableBufferSizes\fP"
.br
.ti -1c
.RI "#define \fBpaAsioUseChannelSelectors\fP   (0x01)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPaAsioStreamInfo\fP \fBPaAsioStreamInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPaError\fP \fBPaAsio_GetAvailableBufferSizes\fP (\fBPaDeviceIndex\fP device, long *minBufferSizeFrames, long *maxBufferSizeFrames, long *preferredBufferSizeFrames, long *granularity)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAsio_ShowControlPanel\fP (\fBPaDeviceIndex\fP device, \fBvoid\fP *systemSpecific)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAsio_GetInputChannelName\fP (\fBPaDeviceIndex\fP device, \fBint\fP channelIndex, \fBconst\fP char **channelName)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAsio_GetOutputChannelName\fP (\fBPaDeviceIndex\fP device, \fBint\fP channelIndex, \fBconst\fP char **channelName)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAsio_SetStreamSampleRate\fP (\fBPaStream\fP *stream, double sampleRate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ASIO-specific PortAudio API extension header file\&. 


.PP
Definition in file \fBpa_asio\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PaAsio_GetAvailableLatencyValues   \fBPaAsio_GetAvailableBufferSizes\fP"
Backwards compatibility alias for PaAsio_GetAvailableBufferSizes
.PP
\fBSee also:\fP
.RS 4
\fBPaAsio_GetAvailableBufferSizes\fP 
.RE
.PP

.PP
Definition at line 78 of file pa_asio\&.h\&.
.SS "#define paAsioUseChannelSelectors   (0x01)"

.PP
Definition at line 123 of file pa_asio\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPaAsioStreamInfo\fP \fBPaAsioStreamInfo\fP"

.SH "Function Documentation"
.PP 
.SS "\fBPaError\fP PaAsio_GetAvailableBufferSizes (\fBPaDeviceIndex\fP device, long * minBufferSizeFrames, long * maxBufferSizeFrames, long * preferredBufferSizeFrames, long * granularity)"
Retrieve legal native buffer sizes for the specificed device, in sample frames\&.
.PP
\fBParameters:\fP
.RS 4
\fIdevice\fP The global index of the device about which the query is being made\&. 
.br
\fIminBufferSizeFrames\fP A pointer to the location which will receive the minimum buffer size value\&. 
.br
\fImaxBufferSizeFrames\fP A pointer to the location which will receive the maximum buffer size value\&. 
.br
\fIpreferredBufferSizeFrames\fP A pointer to the location which will receive the preferred buffer size value\&. 
.br
\fIgranularity\fP A pointer to the location which will receive the 'granularity'\&. This value determines the step size used to compute the legal values between minBufferSizeFrames and maxBufferSizeFrames\&. If granularity is -1 then available buffer size values are powers of two\&.
.RE
.PP
\fBSee also:\fP
.RS 4
ASIOGetBufferSize \fBin\fP \fBthe\fP ASIO SDK\&.
.RE
.PP
\fBNote:\fP
.RS 4
: this function used to be called PaAsio_GetAvailableLatencyValues\&. There is a #define that maps PaAsio_GetAvailableLatencyValues to this function for backwards compatibility\&. 
.RE
.PP

.PP
Definition at line 913 of file pa_asio\&.cpp\&.
.SS "\fBPaError\fP PaAsio_GetInputChannelName (\fBPaDeviceIndex\fP device, \fBint\fP channelIndex, \fBconst\fP char ** channelName)"
Retrieve a pointer to a string containing the name of the specified input channel\&. The string is valid until Pa_Terminate is called\&.
.PP
The string will be no longer than 32 characters including the null terminator\&. 
.PP
Definition at line 4137 of file pa_asio\&.cpp\&.
.SS "\fBPaError\fP PaAsio_GetOutputChannelName (\fBPaDeviceIndex\fP device, \fBint\fP channelIndex, \fBconst\fP char ** channelName)"
Retrieve a pointer to a string containing the name of the specified input channel\&. The string is valid until Pa_Terminate is called\&.
.PP
The string will be no longer than 32 characters including the null terminator\&. 
.PP
Definition at line 4170 of file pa_asio\&.cpp\&.
.SS "\fBPaError\fP PaAsio_SetStreamSampleRate (\fBPaStream\fP * stream, double sampleRate)"
Set the sample rate of an open paASIO stream\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP The stream to operate on\&. 
.br
\fIsampleRate\fP The new sample rate\&.
.RE
.PP
Note that this function may fail if the stream is alredy running and the ASIO driver does not support switching the sample rate of a running stream\&.
.PP
Returns paIncompatibleStreamHostApi if stream is not a paASIO stream\&. 
.PP
Definition at line 4239 of file pa_asio\&.cpp\&.
.SS "\fBPaError\fP PaAsio_ShowControlPanel (\fBPaDeviceIndex\fP device, \fBvoid\fP * systemSpecific)"
Display the ASIO control panel for the specified device\&.
.PP
\fBParameters:\fP
.RS 4
\fIdevice\fP The global index of the device whose control panel is to be displayed\&. 
.br
\fIsystemSpecific\fP On Windows, the calling application's main window handle, on Macintosh this value should be zero\&. 
.RE
.PP

.PP
Definition at line 4031 of file pa_asio\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
