.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/examples/pa_devs.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/examples/pa_devs.c \- List available devices, including device information\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'portaudio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
List available devices, including device information\&. 


.PP
\fBAuthor:\fP
.RS 4
Phil Burk http://www.softsynth.com
.RE
.PP
\fBNote:\fP
.RS 4
Define PA_USE_ASIO=0 to compile this code on Windows without ASIO support\&. 
.RE
.PP

.PP
Definition in file \fBpa_devs\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 102 of file pa_devs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
