.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/skeleton/pa_hostapi_skeleton.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/skeleton/pa_hostapi_skeleton.c \- Skeleton implementation of support for a host API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'pa_util\&.h'\fP
.br
\fC#include 'pa_allocation\&.h'\fP
.br
\fC#include 'pa_hostapi\&.h'\fP
.br
\fC#include 'pa_stream\&.h'\fP
.br
\fC#include 'pa_cpuload\&.h'\fP
.br
\fC#include 'pa_process\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPaSkeletonHostApiRepresentation\fP"
.br
.ti -1c
.RI "struct \fBPaSkeletonStream\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPA_SKELETON_SET_LAST_HOST_ERROR\fP(\fBerrorCode\fP,  errorText)   \fBPaUtil_SetLastHostErrorInfo\fP( \fBpaInDevelopment\fP, \fBerrorCode\fP, errorText )"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPaSkeletonStream\fP \fBPaSkeletonStream\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPaError\fP \fBPaSkeleton_Initialize\fP (\fBPaUtilHostApiRepresentation\fP **hostApi, \fBPaHostApiIndex\fP index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Skeleton implementation of support for a host API\&. 

This file is provided as a starting point for implementing support for a new host API\&. It provides examples of how the common code can be used\&.
.PP
\fBNote:\fP
.RS 4
IMPLEMENT ME comments are used to indicate functionality which much be customised for each implementation\&. 
.RE
.PP

.PP
Definition in file \fBpa_hostapi_skeleton\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PA_SKELETON_SET_LAST_HOST_ERROR(\fBerrorCode\fP, errorText)   \fBPaUtil_SetLastHostErrorInfo\fP( \fBpaInDevelopment\fP, \fBerrorCode\fP, errorText )"

.PP
Definition at line 108 of file pa_hostapi_skeleton\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPaSkeletonStream\fP
 \fBPaSkeletonStream\fP"

.SH "Function Documentation"
.PP 
.SS "\fBPaError\fP PaSkeleton_Initialize (\fBPaUtilHostApiRepresentation\fP ** hostApi, \fBPaHostApiIndex\fP index)"

.PP
Definition at line 126 of file pa_hostapi_skeleton\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
