.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/include/pa_linux_alsa.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/include/pa_linux_alsa.h \- ALSA-specific PortAudio API extension header file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'portaudio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPaAlsaStreamInfo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPaAlsaStreamInfo\fP \fBPaAlsaStreamInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBPaAlsa_InitializeStreamInfo\fP (\fBPaAlsaStreamInfo\fP *\fBinfo\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPaAlsa_EnableRealtimeScheduling\fP (\fBPaStream\fP *\fBs\fP, \fBint\fP enable)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAlsa_GetStreamInputCard\fP (\fBPaStream\fP *\fBs\fP, \fBint\fP *card)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAlsa_GetStreamOutputCard\fP (\fBPaStream\fP *\fBs\fP, \fBint\fP *card)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAlsa_SetNumPeriods\fP (\fBint\fP numPeriods)"
.br
.ti -1c
.RI "\fBPaError\fP \fBPaAlsa_SetRetriesBusy\fP (\fBint\fP retries)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPaAlsa_SetLibraryPathName\fP (\fBconst\fP char *pathName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ALSA-specific PortAudio API extension header file\&. 


.PP
Definition in file \fBpa_linux_alsa\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPaAlsaStreamInfo\fP
 \fBPaAlsaStreamInfo\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP PaAlsa_EnableRealtimeScheduling (\fBPaStream\fP * s, \fBint\fP enable)"
Instruct whether to enable real-time priority when starting the audio thread\&.
.PP
If this is turned on by the stream is started, the audio callback thread will be created with the FIFO scheduling policy, which is suitable for realtime operation\&. 
.PP
Definition at line 4552 of file pa_linux_alsa\&.c\&.
.SS "\fBPaError\fP PaAlsa_GetStreamInputCard (\fBPaStream\fP * s, \fBint\fP * card)"
Get the ALSA-lib card index of this stream's input device\&. 
.PP
Definition at line 4585 of file pa_linux_alsa\&.c\&.
.SS "\fBPaError\fP PaAlsa_GetStreamOutputCard (\fBPaStream\fP * s, \fBint\fP * card)"
Get the ALSA-lib card index of this stream's output device\&. 
.PP
Definition at line 4602 of file pa_linux_alsa\&.c\&.
.SS "\fBvoid\fP PaAlsa_InitializeStreamInfo (\fBPaAlsaStreamInfo\fP * info)"
Initialize host API specific structure, call this before setting relevant attributes\&. 
.PP
Definition at line 4544 of file pa_linux_alsa\&.c\&.
.SS "\fBvoid\fP PaAlsa_SetLibraryPathName (\fBconst\fP char * pathName)"
Set the path and name of ALSA library file if PortAudio is configured to load it dynamically (see PA_ALSA_DYNAMIC)\&. This setting will overwrite the default name set by PA_ALSA_PATHNAME define\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpathName\fP Full path with filename\&. Only filename can be used, but dlopen() will lookup default searchable directories (/usr/lib;/usr/local/lib) then\&. 
.RE
.PP

.PP
Definition at line 543 of file pa_linux_alsa\&.c\&.
.SS "\fBPaError\fP PaAlsa_SetNumPeriods (\fBint\fP numPeriods)"
Set the number of periods (buffer fragments) to configure devices with\&.
.PP
By default the number of periods is 4, this is the lowest number of periods that works well on the author's soundcard\&. 
.PP
\fBParameters:\fP
.RS 4
\fInumPeriods\fP The number of periods\&. 
.RE
.PP

.PP
Definition at line 590 of file pa_linux_alsa\&.c\&.
.SS "\fBPaError\fP PaAlsa_SetRetriesBusy (\fBint\fP retries)"
Set the maximum number of times to retry opening busy device (sleeping for a short interval inbetween)\&. 
.PP
Definition at line 4619 of file pa_linux_alsa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
