.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/coreaudio/pa_mac_core_internal.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/coreaudio/pa_mac_core_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CoreAudio/CoreAudio\&.h>\fP
.br
\fC#include <CoreServices/CoreServices\&.h>\fP
.br
\fC#include <AudioUnit/AudioUnit\&.h>\fP
.br
\fC#include <AudioToolbox/AudioToolbox\&.h>\fP
.br
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'pa_util\&.h'\fP
.br
\fC#include 'pa_hostapi\&.h'\fP
.br
\fC#include 'pa_stream\&.h'\fP
.br
\fC#include 'pa_allocation\&.h'\fP
.br
\fC#include 'pa_cpuload\&.h'\fP
.br
\fC#include 'pa_process\&.h'\fP
.br
\fC#include 'pa_ringbuffer\&.h'\fP
.br
\fC#include 'pa_mac_core_blocking\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPaMacAUHAL\fP"
.br
.ti -1c
.RI "struct \fBPaMacCoreDeviceProperties\fP"
.br
.ti -1c
.RI "struct \fBPaMacCoreStream\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRING_BUFFER_ADVANCE_DENOMINATOR\fP   (4)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBPaMacCoreDeviceProperties\fP \fBPaMacCoreDeviceProperties\fP"
.br
.ti -1c
.RI "typedef struct \fBPaMacCoreStream\fP \fBPaMacCoreStream\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPaError\fP \fBPaMacCore_Initialize\fP (\fBPaUtilHostApiRepresentation\fP **hostApi, \fBPaHostApiIndex\fP index)"
.br
.ti -1c
.RI "\fBPaError\fP \fBReadStream\fP (\fBPaStream\fP *stream, \fBvoid\fP *\fBbuffer\fP, unsigned long frames)"
.br
.ti -1c
.RI "\fBPaError\fP \fBWriteStream\fP (\fBPaStream\fP *stream, \fBconst\fP \fBvoid\fP *\fBbuffer\fP, unsigned long frames)"
.br
.ti -1c
.RI "signed long \fBGetStreamReadAvailable\fP (\fBPaStream\fP *stream)"
.br
.ti -1c
.RI "signed long \fBGetStreamWriteAvailable\fP (\fBPaStream\fP *stream)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RING_BUFFER_ADVANCE_DENOMINATOR   (4)"

.PP
Definition at line 93 of file pa_mac_core_internal\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBPaMacCoreDeviceProperties\fP
 \fBPaMacCoreDeviceProperties\fP"

.SS "typedef struct \fBPaMacCoreStream\fP
 \fBPaMacCoreStream\fP"

.SH "Function Documentation"
.PP 
.SS "signed long GetStreamReadAvailable (\fBPaStream\fP * stream)"

.PP
Definition at line 575 of file pa_mac_core_blocking\&.c\&.
.SS "signed long GetStreamWriteAvailable (\fBPaStream\fP * stream)"

.PP
Definition at line 585 of file pa_mac_core_blocking\&.c\&.
.SS "\fBPaError\fP PaMacCore_Initialize (\fBPaUtilHostApiRepresentation\fP ** hostApi, \fBPaHostApiIndex\fP index)"

.PP
Definition at line 718 of file pa_mac_core\&.c\&.
.SS "\fBPaError\fP ReadStream (\fBPaStream\fP * stream, \fBvoid\fP * buffer, unsigned long frames)"

.PP
\fBTodo\fP
.RS 4
REVIEW: consider what to do if the input overflows\&. do we requeue all of the buffers? should we be running a thread to make sure they are always queued? see: http://www.portaudio.com/trac/ticket/117 
.RE
.PP

.PP
Definition at line 407 of file pa_mac_core_blocking\&.c\&.
.SS "\fBPaError\fP WriteStream (\fBPaStream\fP * stream, \fBconst\fP \fBvoid\fP * buffer, unsigned long frames)"

.PP
\fBTodo\fP
.RS 4
REVIEW: consider what to do if the output underflows\&. do we requeue all the existing buffers with zeros? should we run a separate thread to keep the buffers enqueued at all times? see: http://www.portaudio.com/trac/ticket/117 
.RE
.PP

.PP
Definition at line 483 of file pa_mac_core_blocking\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
