.TH "PaAlsaStreamComponent" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaAlsaStreamComponent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaSampleFormat\fP \fBhostSampleFormat\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumUserChannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumHostChannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuserInterleaved\fP"
.br
.ti -1c
.RI "\fBint\fP \fBhostInterleaved\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcanMmap\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBnonMmapBuffer\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBnonMmapBufferSize\fP"
.br
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBdevice\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdeviceIsPlug\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuseReventFix\fP"
.br
.ti -1c
.RI "snd_pcm_t * \fBpcm\fP"
.br
.ti -1c
.RI "snd_pcm_uframes_t \fBframesPerPeriod\fP"
.br
.ti -1c
.RI "snd_pcm_uframes_t \fBalsaBufferSize\fP"
.br
.ti -1c
.RI "snd_pcm_format_t \fBnativeFormat\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBnfds\fP"
.br
.ti -1c
.RI "\fBint\fP \fBready\fP"
.br
.ti -1c
.RI "\fBvoid\fP ** \fBuserBuffers\fP"
.br
.ti -1c
.RI "snd_pcm_uframes_t \fBoffset\fP"
.br
.ti -1c
.RI "\fBStreamDirection\fP \fBstreamDir\fP"
.br
.ti -1c
.RI "snd_pcm_channel_area_t * \fBchannelAreas\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 602 of file pa_linux_alsa\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "snd_pcm_uframes_t PaAlsaStreamComponent::alsaBufferSize"

.PP
Definition at line 615 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::canMmap"

.PP
Definition at line 607 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::card"

.PP
Definition at line 624 of file pa_linux_alsa\&.c\&.
.SS "snd_pcm_channel_area_t* PaAlsaStreamComponent::channelAreas"

.PP
Definition at line 623 of file pa_linux_alsa\&.c\&.
.SS "\fBPaDeviceIndex\fP PaAlsaStreamComponent::device"

.PP
Definition at line 610 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::deviceIsPlug"

.PP
Definition at line 611 of file pa_linux_alsa\&.c\&.
.SS "snd_pcm_uframes_t PaAlsaStreamComponent::framesPerPeriod"

.PP
Definition at line 615 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::hostInterleaved"

.PP
Definition at line 606 of file pa_linux_alsa\&.c\&.
.SS "\fBPaSampleFormat\fP PaAlsaStreamComponent::hostSampleFormat"

.PP
Definition at line 604 of file pa_linux_alsa\&.c\&.
.SS "snd_pcm_format_t PaAlsaStreamComponent::nativeFormat"

.PP
Definition at line 616 of file pa_linux_alsa\&.c\&.
.SS "unsigned \fBint\fP PaAlsaStreamComponent::nfds"

.PP
Definition at line 617 of file pa_linux_alsa\&.c\&.
.SS "\fBvoid\fP* PaAlsaStreamComponent::nonMmapBuffer"

.PP
Definition at line 608 of file pa_linux_alsa\&.c\&.
.SS "unsigned \fBint\fP PaAlsaStreamComponent::nonMmapBufferSize"

.PP
Definition at line 609 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::numHostChannels"

.PP
Definition at line 605 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::numUserChannels"

.PP
Definition at line 605 of file pa_linux_alsa\&.c\&.
.SS "snd_pcm_uframes_t PaAlsaStreamComponent::offset"

.PP
Definition at line 620 of file pa_linux_alsa\&.c\&.
.SS "snd_pcm_t* PaAlsaStreamComponent::pcm"

.PP
Definition at line 614 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::ready"

.PP
Definition at line 618 of file pa_linux_alsa\&.c\&.
.SS "\fBStreamDirection\fP PaAlsaStreamComponent::streamDir"

.PP
Definition at line 621 of file pa_linux_alsa\&.c\&.
.SS "\fBvoid\fP** PaAlsaStreamComponent::userBuffers"

.PP
Definition at line 619 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::useReventFix"

.PP
Definition at line 612 of file pa_linux_alsa\&.c\&.
.SS "\fBint\fP PaAlsaStreamComponent::userInterleaved"

.PP
Definition at line 606 of file pa_linux_alsa\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
