.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/paf.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/paf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPAF_FMT\fP"
.br
.ti -1c
.RI "struct \fBPAF24_PRIVATE\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFAP_MARKER\fP   (MAKE_MARKER ('\fBf\fP', '\fBa\fP', '\fBp\fP', ' '))"
.br
.ti -1c
.RI "#define \fBPAF_MARKER\fP   (MAKE_MARKER (' ', '\fBp\fP', '\fBa\fP', '\fBf\fP'))"
.br
.ti -1c
.RI "#define \fBPAF_HEADER_LENGTH\fP   2048"
.br
.ti -1c
.RI "#define \fBPAF24_SAMPLES_PER_BLOCK\fP   10"
.br
.ti -1c
.RI "#define \fBPAF24_BLOCK_SIZE\fP   32"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBPAF_PCM_16\fP = 0, \fBPAF_PCM_24\fP = 1, \fBPAF_PCM_S8\fP = 2 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBpaf_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FAP_MARKER   (MAKE_MARKER ('\fBf\fP', '\fBa\fP', '\fBp\fP', ' '))"

.PP
Definition at line 36 of file paf\&.c\&.
.SS "#define PAF24_BLOCK_SIZE   32"

.PP
Definition at line 46 of file paf\&.c\&.
.SS "#define PAF24_SAMPLES_PER_BLOCK   10"

.PP
Definition at line 45 of file paf\&.c\&.
.SS "#define PAF_HEADER_LENGTH   2048"

.PP
Definition at line 43 of file paf\&.c\&.
.SS "#define PAF_MARKER   (MAKE_MARKER (' ', '\fBp\fP', '\fBa\fP', '\fBf\fP'))"

.PP
Definition at line 37 of file paf\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPAF_PCM_16 \fP\fP
.TP
\fB\fIPAF_PCM_24 \fP\fP
.TP
\fB\fIPAF_PCM_S8 \fP\fP
.PP
Definition at line 95 of file paf\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP paf_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 106 of file paf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
