.TH "PAF_FMT" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAF_FMT \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBint\fP \fBendianness\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsamplerate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBint\fP \fBchannels\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file paf\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP PAF_FMT::channels"

.PP
Definition at line 57 of file paf\&.c\&.
.SS "\fBint\fP PAF_FMT::endianness"

.PP
Definition at line 54 of file paf\&.c\&.
.SS "\fBint\fP PAF_FMT::format"

.PP
Definition at line 56 of file paf\&.c\&.
.SS "\fBint\fP PAF_FMT::samplerate"

.PP
Definition at line 55 of file paf\&.c\&.
.SS "\fBint\fP PAF_FMT::source"

.PP
Definition at line 58 of file paf\&.c\&.
.SS "\fBint\fP PAF_FMT::version"

.PP
Definition at line 53 of file paf\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
