.TH "PaOSSHostApiRepresentation" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaOSSHostApiRepresentation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaUtilHostApiRepresentation\fP \fBinheritedHostApiRep\fP"
.br
.ti -1c
.RI "\fBPaUtilStreamInterface\fP \fBcallbackStreamInterface\fP"
.br
.ti -1c
.RI "\fBPaUtilStreamInterface\fP \fBblockingStreamInterface\fP"
.br
.ti -1c
.RI "\fBPaUtilAllocationGroup\fP * \fBallocations\fP"
.br
.ti -1c
.RI "\fBPaHostApiIndex\fP \fBhostApiIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file pa_unix_oss\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaUtilAllocationGroup\fP* PaOSSHostApiRepresentation::allocations"

.PP
Definition at line 136 of file pa_unix_oss\&.c\&.
.SS "\fBPaUtilStreamInterface\fP PaOSSHostApiRepresentation::blockingStreamInterface"

.PP
Definition at line 134 of file pa_unix_oss\&.c\&.
.SS "\fBPaUtilStreamInterface\fP PaOSSHostApiRepresentation::callbackStreamInterface"

.PP
Definition at line 133 of file pa_unix_oss\&.c\&.
.SS "\fBPaHostApiIndex\fP PaOSSHostApiRepresentation::hostApiIndex"

.PP
Definition at line 138 of file pa_unix_oss\&.c\&.
.SS "\fBPaUtilHostApiRepresentation\fP PaOSSHostApiRepresentation::inheritedHostApiRep"

.PP
Definition at line 132 of file pa_unix_oss\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
