.TH "PaOssStreamComponent" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaOssStreamComponent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBfd\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBdevName\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuserChannelCount\fP"
.br
.ti -1c
.RI "\fBint\fP \fBhostChannelCount\fP"
.br
.ti -1c
.RI "\fBint\fP \fBuserInterleaved\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBPaSampleFormat\fP \fBuserFormat\fP"
.br
.ti -1c
.RI "\fBPaSampleFormat\fP \fBhostFormat\fP"
.br
.ti -1c
.RI "double \fBlatency\fP"
.br
.ti -1c
.RI "unsigned long \fBhostFrames\fP"
.br
.ti -1c
.RI "unsigned long \fBnumBufs\fP"
.br
.ti -1c
.RI "\fBvoid\fP ** \fBuserBuffers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Per-direction structure for \fBPaOssStream\fP\&.
.PP
Aspect StreamChannels: In case the user requests to open the same device for both capture and playback, but with different number of channels we will have to adapt between the number of user and host channels for at least one direction, since the configuration space is the same for both directions of an OSS device\&. 
.PP
Definition at line 149 of file pa_unix_oss\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* PaOssStreamComponent::buffer"

.PP
Definition at line 155 of file pa_unix_oss\&.c\&.
.SS "\fBconst\fP char* PaOssStreamComponent::devName"

.PP
Definition at line 152 of file pa_unix_oss\&.c\&.
.SS "\fBint\fP PaOssStreamComponent::fd"

.PP
Definition at line 151 of file pa_unix_oss\&.c\&.
.SS "\fBint\fP PaOssStreamComponent::hostChannelCount"

.PP
Definition at line 153 of file pa_unix_oss\&.c\&.
.SS "\fBPaSampleFormat\fP PaOssStreamComponent::hostFormat"

.PP
Definition at line 156 of file pa_unix_oss\&.c\&.
.SS "unsigned long PaOssStreamComponent::hostFrames"

.PP
Definition at line 158 of file pa_unix_oss\&.c\&.
.SS "double PaOssStreamComponent::latency"

.PP
Definition at line 157 of file pa_unix_oss\&.c\&.
.SS "unsigned long PaOssStreamComponent::numBufs"

.PP
Definition at line 158 of file pa_unix_oss\&.c\&.
.SS "\fBvoid\fP** PaOssStreamComponent::userBuffers"

.PP
Definition at line 159 of file pa_unix_oss\&.c\&.
.SS "\fBint\fP PaOssStreamComponent::userChannelCount"

.PP
Definition at line 153 of file pa_unix_oss\&.c\&.
.SS "\fBPaSampleFormat\fP PaOssStreamComponent::userFormat"

.PP
Definition at line 156 of file pa_unix_oss\&.c\&.
.SS "\fBint\fP PaOssStreamComponent::userInterleaved"

.PP
Definition at line 154 of file pa_unix_oss\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
