.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/qa/loopback/src/paqa.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/qa/loopback/src/paqa.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'qa_tools\&.h'\fP
.br
\fC#include 'paqa_tools\&.h'\fP
.br
\fC#include 'audio_analyzer\&.h'\fP
.br
\fC#include 'test_audio_analyzer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTestParameters_s\fP"
.br
.ti -1c
.RI "struct \fBLoopbackContext_s\fP"
.br
.ti -1c
.RI "struct \fBUserOptions_s\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_NUM_GENERATORS\fP   (8)"
.br
.ti -1c
.RI "#define \fBMAX_NUM_RECORDINGS\fP   (8)"
.br
.ti -1c
.RI "#define \fBMAX_BACKGROUND_NOISE_RMS\fP   (0\&.0004)"
.br
.ti -1c
.RI "#define \fBLOOPBACK_DETECTION_DURATION_SECONDS\fP   (0\&.8)"
.br
.ti -1c
.RI "#define \fBDEFAULT_FRAMES_PER_BUFFER\fP   (0)"
.br
.ti -1c
.RI "#define \fBPAQA_WAIT_STREAM_MSEC\fP   (100)"
.br
.ti -1c
.RI "#define \fBPAQA_TEST_DURATION\fP   (1\&.2)"
.br
.ti -1c
.RI "#define \fBPAQA_FLAG_TWO_STREAMS\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBPAQA_FLAG_USE_BLOCKING_IO\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBBIG_BUFFER_SIZE\fP   (sizeof(float) * 2 * 2 * 1024)"
.br
.ti -1c
.RI "#define \fBMAX_CONVERSION_SAMPLES\fP   (2 * 32 * 1024)"
.br
.ti -1c
.RI "#define \fBCONVERSION_BUFFER_SIZE\fP   (sizeof(float) * 2 * \fBMAX_CONVERSION_SAMPLES\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBTestParameters_s\fP \fBTestParameters\fP"
.br
.ti -1c
.RI "typedef struct \fBLoopbackContext_s\fP \fBLoopbackContext\fP"
.br
.ti -1c
.RI "typedef struct \fBUserOptions_s\fP \fBUserOptions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBPaQa_RunLoopbackFullDuplex\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_WaitForStream\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_RunLoopbackHalfDuplex\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_RunInputOnly\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_RunLoopbackHalfDuplexBlockingIO\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_RunLoopbackFullDuplexBlockingIO\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_RunLoopback\fP (\fBLoopbackContext\fP *loopbackContext)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_CheckForClippedLoopback\fP (\fBLoopbackContext\fP *loopbackContextPtr)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_MeasureBackgroundNoise\fP (\fBLoopbackContext\fP *loopbackContextPtr, double *rmsPtr)"
.br
.ti -1c
.RI "\fBint\fP \fBPaQa_CheckForLoopBack\fP (\fBUserOptions\fP *userOptions, \fBPaDeviceIndex\fP inputDevice, \fBPaDeviceIndex\fP outputDevice)"
.br
.ti -1c
.RI "\fBint\fP \fBTestSampleFormatConversion\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBusage\fP (\fBconst\fP char *\fBname\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, char **\fBargv\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBg_testsPassed\fP = 0"
.br
.ti -1c
.RI "\fBint\fP \fBg_testsFailed\fP = 0"
.br
.ti -1c
.RI "\fBconst\fP char * \fBs_FlagOnNames\fP []"
.br
.ti -1c
.RI "\fBconst\fP char * \fBs_FlagOffNames\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIG_BUFFER_SIZE   (sizeof(float) * 2 * 2 * 1024)"

.PP
Definition at line 144 of file paqa\&.c\&.
.SS "#define CONVERSION_BUFFER_SIZE   (sizeof(float) * 2 * \fBMAX_CONVERSION_SAMPLES\fP)"

.PP
Definition at line 148 of file paqa\&.c\&.
.SS "#define DEFAULT_FRAMES_PER_BUFFER   (0)"

.PP
Definition at line 61 of file paqa\&.c\&.
.SS "#define LOOPBACK_DETECTION_DURATION_SECONDS   (0\&.8)"

.PP
Definition at line 60 of file paqa\&.c\&.
.SS "#define MAX_BACKGROUND_NOISE_RMS   (0\&.0004)"

.PP
Definition at line 59 of file paqa\&.c\&.
.SS "#define MAX_CONVERSION_SAMPLES   (2 * 32 * 1024)"

.PP
Definition at line 147 of file paqa\&.c\&.
.SS "#define MAX_NUM_GENERATORS   (8)"

.PP
Definition at line 57 of file paqa\&.c\&.
.SS "#define MAX_NUM_RECORDINGS   (8)"

.PP
Definition at line 58 of file paqa\&.c\&.
.SS "#define PAQA_FLAG_TWO_STREAMS   (1<<0)"

.PP
Definition at line 66 of file paqa\&.c\&.
.SS "#define PAQA_FLAG_USE_BLOCKING_IO   (1<<1)"

.PP
Definition at line 68 of file paqa\&.c\&.
.SS "#define PAQA_TEST_DURATION   (1\&.2)"

.PP
Definition at line 63 of file paqa\&.c\&.
.SS "#define PAQA_WAIT_STREAM_MSEC   (100)"

.PP
Definition at line 62 of file paqa\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBLoopbackContext_s\fP  \fBLoopbackContext\fP"

.SS "typedef struct \fBTestParameters_s\fP  \fBTestParameters\fP"
Parameters that describe a single test run\&. 
.SS "typedef struct \fBUserOptions_s\fP  \fBUserOptions\fP"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, char ** argv)"

.PP
Definition at line 1455 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_CheckForClippedLoopback (\fBLoopbackContext\fP * loopbackContextPtr)"

.PP
Definition at line 1091 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_CheckForLoopBack (\fBUserOptions\fP * userOptions, \fBPaDeviceIndex\fP inputDevice, \fBPaDeviceIndex\fP outputDevice)"
Output a sine wave then try to detect it on input\&.
.PP
\fBReturns:\fP
.RS 4
1 if loopback connected, 0 if not, or negative error\&. 
.RE
.PP

.PP
Definition at line 1145 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_MeasureBackgroundNoise (\fBLoopbackContext\fP * loopbackContextPtr, double * rmsPtr)"

.PP
Definition at line 1120 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunInputOnly (\fBLoopbackContext\fP * loopbackContext)"
Open one audio streams, just for input\&. Record background level\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 425 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunLoopback (\fBLoopbackContext\fP * loopbackContext)"
Run some kind of loopback test\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 671 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunLoopbackFullDuplex (\fBLoopbackContext\fP * loopbackContext)"
Open a full duplex audio stream\&. Generate sine waves on the output channels and record the input channels\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 282 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunLoopbackFullDuplexBlockingIO (\fBLoopbackContext\fP * loopbackContext)"
Open one audio stream with non-blocking IO\&. Generate sine waves on the output channels and record the input channels\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 620 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunLoopbackHalfDuplex (\fBLoopbackContext\fP * loopbackContext)"
Open two audio streams, one for input and one for output\&. Generate sine waves on the output channels and record the input channels\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 357 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_RunLoopbackHalfDuplexBlockingIO (\fBLoopbackContext\fP * loopbackContext)"
Open two audio streams with non-blocking IO\&. Generate sine waves on the output channels and record the input channels\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or negative error\&. 
.RE
.PP

.PP
Definition at line 546 of file paqa\&.c\&.
.SS "\fBint\fP PaQa_WaitForStream (\fBLoopbackContext\fP * loopbackContext)"
Open two audio streams, one for input and one for output\&. Generate sine waves on the output channels and record the input channels\&. Then close the stream\&. 
.PP
\fBReturns:\fP
.RS 4
0 if OK or paTimedOut\&. 
.RE
.PP

.PP
Definition at line 331 of file paqa\&.c\&.
.SS "\fBint\fP TestSampleFormatConversion (\fBvoid\fP)"

.PP
Definition at line 1356 of file paqa\&.c\&.
.SS "\fBvoid\fP usage (\fBconst\fP char * name)"

.PP
Definition at line 1438 of file paqa\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP g_testsFailed = 0"

.PP
Definition at line 55 of file paqa\&.c\&.
.SS "\fBint\fP g_testsPassed = 0"
Accumulate counts for how many tests pass or fail\&. 
.PP
Definition at line 54 of file paqa\&.c\&.
.SS "\fBconst\fP char* s_FlagOffNames[]"
\fBInitial value:\fP
.PP
.nf
=
{
    "One Stream (Full Duplex)",
    "Callback"
}
.fi
.PP
Definition at line 76 of file paqa\&.c\&.
.SS "\fBconst\fP char* s_FlagOnNames[]"
\fBInitial value:\fP
.PP
.nf
=
{
    "Two Streams (Half Duplex)",
    "Blocking Read/Write"
}
.fi
.PP
Definition at line 70 of file paqa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
