.TH "PaQaAnalysisResult_s" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaQaAnalysisResult_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <audio_analyzer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBvalid\fP"
.br
.ti -1c
.RI "double \fBlatency\fP"
.br
.ti -1c
.RI "double \fBamplitudeRatio\fP"
.br
.ti -1c
.RI "double \fBpopAmplitude\fP"
.br
.ti -1c
.RI "double \fBpopPosition\fP"
.br
.ti -1c
.RI "double \fBnumDroppedFrames\fP"
.br
.ti -1c
.RI "double \fBdroppedFramesPosition\fP"
.br
.ti -1c
.RI "double \fBnumAddedFrames\fP"
.br
.ti -1c
.RI "double \fBaddedFramesPosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file audio_analyzer\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PaQaAnalysisResult_s::addedFramesPosition"

.PP
Definition at line 86 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::amplitudeRatio"

.PP
Definition at line 80 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::droppedFramesPosition"

.PP
Definition at line 84 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::latency"
Latency in samples from output to input\&. 
.PP
Definition at line 79 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::numAddedFrames"

.PP
Definition at line 85 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::numDroppedFrames"

.PP
Definition at line 83 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::popAmplitude"

.PP
Definition at line 81 of file audio_analyzer\&.h\&.
.SS "double PaQaAnalysisResult_s::popPosition"

.PP
Definition at line 82 of file audio_analyzer\&.h\&.
.SS "\fBint\fP PaQaAnalysisResult_s::valid"

.PP
Definition at line 77 of file audio_analyzer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
