.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/parse.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libid3tag/parse.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'id3tag\&.h'\fP
.br
\fC#include 'parse\&.h'\fP
.br
\fC#include 'latin1\&.h'\fP
.br
\fC#include 'utf16\&.h'\fP
.br
\fC#include 'utf8\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "signed long \fBid3_parse_int\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, unsigned \fBint\fP bytes)"
.br
.ti -1c
.RI "unsigned long \fBid3_parse_uint\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, unsigned \fBint\fP bytes)"
.br
.ti -1c
.RI "unsigned long \fBid3_parse_syncsafe\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, unsigned \fBint\fP bytes)"
.br
.ti -1c
.RI "\fBvoid\fP \fBid3_parse_immediate\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, unsigned \fBint\fP bytes, char *\fBvalue\fP)"
.br
.ti -1c
.RI "\fBid3_latin1_t\fP * \fBid3_parse_latin1\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, \fBid3_length_t\fP \fBlength\fP, \fBint\fP full)"
.br
.ti -1c
.RI "\fBid3_ucs4_t\fP * \fBid3_parse_string\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, \fBid3_length_t\fP \fBlength\fP, enum \fBid3_field_textencoding\fP \fBencoding\fP, \fBint\fP full)"
.br
.ti -1c
.RI "\fBid3_byte_t\fP * \fBid3_parse_binary\fP (\fBid3_byte_t\fP \fBconst\fP **ptr, \fBid3_length_t\fP \fBlength\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBid3_byte_t\fP* id3_parse_binary (\fBid3_byte_t\fP \fBconst\fP ** ptr, \fBid3_length_t\fP length)"

.PP
Definition at line 182 of file parse\&.c\&.
.SS "\fBvoid\fP id3_parse_immediate (\fBid3_byte_t\fP \fBconst\fP ** ptr, unsigned \fBint\fP bytes, char * value)"

.PP
Definition at line 93 of file parse\&.c\&.
.SS "signed long id3_parse_int (\fBid3_byte_t\fP \fBconst\fP ** ptr, unsigned \fBint\fP bytes)"

.PP
Definition at line 41 of file parse\&.c\&.
.SS "\fBid3_latin1_t\fP* id3_parse_latin1 (\fBid3_byte_t\fP \fBconst\fP ** ptr, \fBid3_length_t\fP length, \fBint\fP full)"

.PP
Definition at line 113 of file parse\&.c\&.
.SS "\fBid3_ucs4_t\fP* id3_parse_string (\fBid3_byte_t\fP \fBconst\fP ** ptr, \fBid3_length_t\fP length, enum \fBid3_field_textencoding\fP encoding, \fBint\fP full)"

.PP
Definition at line 148 of file parse\&.c\&.
.SS "unsigned long id3_parse_syncsafe (\fBid3_byte_t\fP \fBconst\fP ** ptr, unsigned \fBint\fP bytes)"

.PP
Definition at line 76 of file parse\&.c\&.
.SS "unsigned long id3_parse_uint (\fBid3_byte_t\fP \fBconst\fP ** ptr, unsigned \fBint\fP bytes)"

.PP
Definition at line 60 of file parse\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
