.TH "PaSkeletonHostApiRepresentation" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaSkeletonHostApiRepresentation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaUtilHostApiRepresentation\fP \fBinheritedHostApiRep\fP"
.br
.ti -1c
.RI "\fBPaUtilStreamInterface\fP \fBcallbackStreamInterface\fP"
.br
.ti -1c
.RI "\fBPaUtilStreamInterface\fP \fBblockingStreamInterface\fP"
.br
.ti -1c
.RI "\fBPaUtilAllocationGroup\fP * \fBallocations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file pa_hostapi_skeleton\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaUtilAllocationGroup\fP* PaSkeletonHostApiRepresentation::allocations"

.PP
Definition at line 119 of file pa_hostapi_skeleton\&.c\&.
.SS "\fBPaUtilStreamInterface\fP PaSkeletonHostApiRepresentation::blockingStreamInterface"

.PP
Definition at line 117 of file pa_hostapi_skeleton\&.c\&.
.SS "\fBPaUtilStreamInterface\fP PaSkeletonHostApiRepresentation::callbackStreamInterface"

.PP
Definition at line 116 of file pa_hostapi_skeleton\&.c\&.
.SS "\fBPaUtilHostApiRepresentation\fP PaSkeletonHostApiRepresentation::inheritedHostApiRep"

.PP
Definition at line 115 of file pa_hostapi_skeleton\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
