.TH "PaStreamInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaStreamInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <portaudio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBstructVersion\fP"
.br
.ti -1c
.RI "\fBPaTime\fP \fBinputLatency\fP"
.br
.ti -1c
.RI "\fBPaTime\fP \fBoutputLatency\fP"
.br
.ti -1c
.RI "double \fBsampleRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure containing unchanging information about an open stream\&. 
.PP
\fBSee also:\fP
.RS 4
\fBPa_GetStreamInfo\fP 
.RE
.PP

.PP
Definition at line 1022 of file portaudio\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaTime\fP PaStreamInfo::inputLatency"
The input latency of the stream in seconds\&. This value provides the most accurate estimate of input latency available to the implementation\&. It may differ significantly from the suggestedLatency value passed to \fBPa_OpenStream()\fP\&. The value of this field will be zero (0\&.) for output-only streams\&. 
.PP
\fBSee also:\fP
.RS 4
\fBPaTime\fP 
.RE
.PP

.PP
Definition at line 1033 of file portaudio\&.h\&.
.SS "\fBPaTime\fP PaStreamInfo::outputLatency"
The output latency of the stream in seconds\&. This value provides the most accurate estimate of output latency available to the implementation\&. It may differ significantly from the suggestedLatency value passed to \fBPa_OpenStream()\fP\&. The value of this field will be zero (0\&.) for input-only streams\&. 
.PP
\fBSee also:\fP
.RS 4
\fBPaTime\fP 
.RE
.PP

.PP
Definition at line 1041 of file portaudio\&.h\&.
.SS "double PaStreamInfo::sampleRate"
The sample rate of the stream in Hertz (samples per second)\&. In cases where the hardware sample rate is inaccurate and PortAudio is aware of it, the value of this field may be different from the sampleRate parameter passed to \fBPa_OpenStream()\fP\&. If information about the actual hardware sample rate is not available, this field will have the same value as the sampleRate parameter passed to \fBPa_OpenStream()\fP\&. 
.PP
Definition at line 1050 of file portaudio\&.h\&.
.SS "\fBint\fP PaStreamInfo::structVersion"
this is struct version 1 
.PP
Definition at line 1025 of file portaudio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
