.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/test/patest_clip.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/test/patest_clip.c \- Play a sine wave for several seconds at an amplitude that would require clipping\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'portaudio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpaTestData\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_SECONDS\fP   (4)"
.br
.ti -1c
.RI "#define \fBSAMPLE_RATE\fP   (44100)"
.br
.ti -1c
.RI "#define \fBM_PI\fP   (3\&.14159265)"
.br
.ti -1c
.RI "#define \fBTABLE_SIZE\fP   (200)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpaTestData\fP \fBpaTestData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPaError\fP \fBPlaySine\fP (\fBpaTestData\fP *\fBdata\fP, unsigned long flags, float amplitude)"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Play a sine wave for several seconds at an amplitude that would require clipping\&. 


.PP
\fBAuthor:\fP
.RS 4
Phil Burk http://www.softsynth.com 
.RE
.PP

.PP
Definition in file \fBpatest_clip\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_PI   (3\&.14159265)"

.PP
Definition at line 53 of file patest_clip\&.c\&.
.SS "#define NUM_SECONDS   (4)"

.PP
Definition at line 50 of file patest_clip\&.c\&.
.SS "#define SAMPLE_RATE   (44100)"

.PP
Definition at line 51 of file patest_clip\&.c\&.
.SS "#define TABLE_SIZE   (200)"

.PP
Definition at line 55 of file patest_clip\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpaTestData\fP
 \fBpaTestData\fP"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 99 of file patest_clip\&.c\&.
.SS "\fBPaError\fP PlaySine (\fBpaTestData\fP * data, unsigned long flags, float amplitude)"

.PP
Definition at line 144 of file patest_clip\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
