.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/test/patest_dsound_low_level_latency_params.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/test/patest_dsound_low_level_latency_params.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'pa_win_ds\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpaTestData\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_SECONDS\fP   (6)"
.br
.ti -1c
.RI "#define \fBSAMPLE_RATE\fP   (44100)"
.br
.ti -1c
.RI "#define \fBDSOUND_FRAMES_PER_HOST_BUFFER\fP   (256*2)"
.br
.ti -1c
.RI "#define \fBFRAMES_PER_BUFFER\fP   256"
.br
.ti -1c
.RI "#define \fBM_PI\fP   (3\&.14159265)"
.br
.ti -1c
.RI "#define \fBTABLE_SIZE\fP   (2048)"
.br
.ti -1c
.RI "#define \fBCHANNEL_COUNT\fP   (2)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, char *\fBargv\fP[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHANNEL_COUNT   (2)"

.PP
Definition at line 58 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define DSOUND_FRAMES_PER_HOST_BUFFER   (256*2)"

.PP
Definition at line 48 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define FRAMES_PER_BUFFER   256"

.PP
Definition at line 50 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define M_PI   (3\&.14159265)"

.PP
Definition at line 53 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define NUM_SECONDS   (6)"

.PP
Definition at line 45 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define SAMPLE_RATE   (44100)"

.PP
Definition at line 46 of file patest_dsound_low_level_latency_params\&.c\&.
.SS "#define TABLE_SIZE   (2048)"

.PP
Definition at line 56 of file patest_dsound_low_level_latency_params\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, char * argv[])"

.PP
Definition at line 103 of file patest_dsound_low_level_latency_params\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
