.TH "patest_suggested_vs_streaminfo_latency" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
patest_suggested_vs_streaminfo_latency \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBloadCsvData\fP (\fBdataFileName\fP)"
.br
.ti -1c
.RI "def \fBsetFigureTitleAndAxisLabels\fP (framesPerBufferString)"
.br
.ti -1c
.RI "def \fBsetDisplayRangeSeconds\fP (maxSeconds)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBtestExeName\fP = 'PATest\&.exe'"
.br
.ti -1c
.RI "\fBstring\fP \fBdataFileName\fP = 'patest_suggested_vs_streaminfo_latency\&.csv'"
.br
.ti -1c
.RI "\fBint\fP \fBinputDeviceIndex\fP = \-1"
.br
.ti -1c
.RI "\fBint\fP \fBoutputDeviceIndex\fP = \-1"
.br
.ti -1c
.RI "\fBint\fP \fBsampleRate\fP = 44100"
.br
.ti -1c
.RI "\fBstring\fP \fBpdfFilenameSuffix\fP = '_wmme'"
.br
.ti -1c
.RI "\fBpdfFile\fP = PdfPages('patest_suggested_vs_streaminfo_latency_' + str(\fBsampleRate\fP) + \fBpdfFilenameSuffix\fP +'\&.pdf')"
.br
.ti -1c
.RI "list \fBcompositeTestFramesPerBufferValues\fP = [0]"
.br
.ti -1c
.RI "list \fBindividualPlotFramesPerBufferValues\fP = [0,64,128,256,512]"
.br
.ti -1c
.RI "\fBbool\fP \fBisFirst\fP = True"
.br
.ti -1c
.RI "\fBstring\fP \fBcommandString\fP = \fBtestExeName\fP+' '"
.br
.ti -1c
.RI "\fBd\fP = \fBloadCsvData\fP(\fBdataFileName\fP)"
.br
.ti -1c
.RI "\fBsuggestedLatency\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBhalfDuplexOutputLatency\fP"
.br
.ti -1c
.RI "\fBhalfDuplexInputLatency\fP"
.br
.ti -1c
.RI "\fBfullDuplexOutputLatency\fP"
.br
.ti -1c
.RI "\fBfullDuplexInputLatency\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBframesPerBufferText\fP = 'paFramesPerBufferUnspecified'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Run and graph the results of patest_suggested_vs_streaminfo_latency.c

Requires matplotlib for plotting: http://matplotlib.sourceforge.net/
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def patest_suggested_vs_streaminfo_latency\&.loadCsvData ( dataFileName)"

.PP
Definition at line 25 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "def patest_suggested_vs_streaminfo_latency\&.setDisplayRangeSeconds ( maxSeconds)"

.PP
Definition at line 64 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "def patest_suggested_vs_streaminfo_latency\&.setFigureTitleAndAxisLabels ( framesPerBufferString)"

.PP
Definition at line 57 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "\fBstring\fP patest_suggested_vs_streaminfo_latency\&.commandString = \fBtestExeName\fP+' '"

.PP
Definition at line 94 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "list patest_suggested_vs_streaminfo_latency\&.compositeTestFramesPerBufferValues = [0]"

.PP
Definition at line 71 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.d = \fBloadCsvData\fP(\fBdataFileName\fP)"

.PP
Definition at line 98 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBstring\fP patest_suggested_vs_streaminfo_latency\&.dataFileName = 'patest_suggested_vs_streaminfo_latency\&.csv'"

.PP
Definition at line 15 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.framesPerBufferText = 'paFramesPerBufferUnspecified'"

.PP
Definition at line 127 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.fullDuplexInputLatency"

.PP
Definition at line 124 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.fullDuplexOutputLatency"

.PP
Definition at line 123 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.halfDuplexInputLatency"

.PP
Definition at line 122 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.halfDuplexOutputLatency"

.PP
Definition at line 121 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "list patest_suggested_vs_streaminfo_latency\&.individualPlotFramesPerBufferValues = [0,64,128,256,512]"

.PP
Definition at line 89 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBint\fP patest_suggested_vs_streaminfo_latency\&.inputDeviceIndex = \-1"

.PP
Definition at line 17 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBbool\fP patest_suggested_vs_streaminfo_latency\&.isFirst = True"

.PP
Definition at line 91 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.label"

.PP
Definition at line 110 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBint\fP patest_suggested_vs_streaminfo_latency\&.outputDeviceIndex = \-1"

.PP
Definition at line 18 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.pdfFile = PdfPages('patest_suggested_vs_streaminfo_latency_' + str(\fBsampleRate\fP) + \fBpdfFilenameSuffix\fP +'\&.pdf')"

.PP
Definition at line 22 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBstring\fP patest_suggested_vs_streaminfo_latency\&.pdfFilenameSuffix = '_wmme'"

.PP
Definition at line 20 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBint\fP patest_suggested_vs_streaminfo_latency\&.sampleRate = 44100"

.PP
Definition at line 19 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "patest_suggested_vs_streaminfo_latency\&.suggestedLatency"

.PP
Definition at line 110 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SS "\fBstring\fP patest_suggested_vs_streaminfo_latency\&.testExeName = 'PATest\&.exe'"

.PP
Definition at line 14 of file patest_suggested_vs_streaminfo_latency\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
