.TH "PaulStretch" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaulStretch \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaulStretch\fP (float rap_, \fBint\fP in_bufsize_, float samplerate_)"
.br
.ti -1c
.RI "virtual \fB~PaulStretch\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBprocess\fP (float *smps, \fBint\fP nsmps)"
.br
.ti -1c
.RI "\fBint\fP \fBget_nsamples\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBget_nsamples_for_fill\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_rap\fP (float newrap)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBin_bufsize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpoolsize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBout_bufsize\fP"
.br
.ti -1c
.RI "float * \fBout_buf\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBprocess_spectrum\fP (float *WXUNUSED(freq))"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBsamplerate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file Paulstretch\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PaulStretch::PaulStretch (float rap_, \fBint\fP in_bufsize_, float samplerate_)"

.PP
Definition at line 364 of file Paulstretch\&.cpp\&.
.SS "PaulStretch::~PaulStretch ()\fC [virtual]\fP"

.PP
Definition at line 394 of file Paulstretch\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP PaulStretch::get_nsamples ()"

.PP
Definition at line 482 of file Paulstretch\&.cpp\&.
.SS "\fBint\fP PaulStretch::get_nsamples_for_fill ()"

.PP
Definition at line 501 of file Paulstretch\&.cpp\&.
.SS "\fBvoid\fP PaulStretch::process (float * smps, \fBint\fP nsmps)"

.PP
Definition at line 412 of file Paulstretch\&.cpp\&.
.SS "\fBvoid\fP PaulStretch::process_spectrum (float * WXUNUSEDfreq)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 62 of file Paulstretch\&.cpp\&.
.SS "\fBvoid\fP PaulStretch::set_rap (float newrap)"

.PP
Definition at line 406 of file Paulstretch\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP PaulStretch::in_bufsize"

.PP
Definition at line 50 of file Paulstretch\&.cpp\&.
.SS "float* PaulStretch::out_buf"

.PP
Definition at line 54 of file Paulstretch\&.cpp\&.
.SS "\fBint\fP PaulStretch::out_bufsize"

.PP
Definition at line 53 of file Paulstretch\&.cpp\&.
.SS "\fBint\fP PaulStretch::poolsize"

.PP
Definition at line 51 of file Paulstretch\&.cpp\&.
.SS "float PaulStretch::samplerate\fC [protected]\fP"

.PP
Definition at line 62 of file Paulstretch\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
