.TH "PaUnixMutex" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaUnixMutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_unix_util\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmtx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file pa_unix_util\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "pthread_mutex_t PaUnixMutex::mtx"

.PP
Definition at line 139 of file pa_unix_util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
