.TH "PaUtilChannelDescriptor" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaUtilChannelDescriptor \- An auxilliary data structure used internally by the buffer processor to represent host input and output buffers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_process\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBdata\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBstride\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An auxilliary data structure used internally by the buffer processor to represent host input and output buffers\&. 
.PP
Definition at line 242 of file pa_process\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* PaUtilChannelDescriptor::data"

.PP
Definition at line 243 of file pa_process\&.h\&.
.SS "unsigned \fBint\fP PaUtilChannelDescriptor::stride"
stride in samples, not bytes 
.PP
Definition at line 244 of file pa_process\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
