.TH "PaUtilConverterTable" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaUtilConverterTable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_converters\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int32_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int32_Clip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int32_DitherClip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int24_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int24_Clip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int24_DitherClip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int16_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int16_Clip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int16_DitherClip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int8_Clip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_Int8_DitherClip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_UInt8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_UInt8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_UInt8_Clip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBFloat32_To_UInt8_DitherClip\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Float32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int24_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int16_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_Int8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_UInt8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt32_To_UInt8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Float32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Int32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Int16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Int16_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Int8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_Int8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_UInt8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt24_To_UInt8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_Float32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_Int32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_Int24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_Int8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_Int8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_UInt8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt16_To_UInt8_Dither\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt8_To_Float32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt8_To_Int32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt8_To_Int24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt8_To_Int16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBInt8_To_UInt8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBUInt8_To_Float32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBUInt8_To_Int32\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBUInt8_To_Int24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBUInt8_To_Int16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBUInt8_To_Int8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBCopy_8_To_8\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBCopy_16_To_16\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBCopy_24_To_24\fP"
.br
.ti -1c
.RI "\fBPaUtilConverter\fP * \fBCopy_32_To_32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The type used to store all sample conversion functions\&. 
.PP
\fBSee also:\fP
.RS 4
\fBpaConverters\fP; 
.RE
.PP

.PP
Definition at line 138 of file pa_converters\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Copy_16_To_16"

.PP
Definition at line 204 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Copy_24_To_24"

.PP
Definition at line 205 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Copy_32_To_32"

.PP
Definition at line 206 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Copy_8_To_8"

.PP
Definition at line 203 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int16"

.PP
Definition at line 149 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int16_Clip"

.PP
Definition at line 151 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int16_Dither"

.PP
Definition at line 150 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int16_DitherClip"

.PP
Definition at line 152 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int24"

.PP
Definition at line 144 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int24_Clip"

.PP
Definition at line 146 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int24_Dither"

.PP
Definition at line 145 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int24_DitherClip"

.PP
Definition at line 147 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int32"

.PP
Definition at line 139 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int32_Clip"

.PP
Definition at line 141 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int32_Dither"

.PP
Definition at line 140 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int32_DitherClip"

.PP
Definition at line 142 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int8"

.PP
Definition at line 154 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int8_Clip"

.PP
Definition at line 156 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int8_Dither"

.PP
Definition at line 155 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_Int8_DitherClip"

.PP
Definition at line 157 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_UInt8"

.PP
Definition at line 159 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_UInt8_Clip"

.PP
Definition at line 161 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_UInt8_Dither"

.PP
Definition at line 160 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Float32_To_UInt8_DitherClip"

.PP
Definition at line 162 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_Float32"

.PP
Definition at line 183 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_Int24"

.PP
Definition at line 185 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_Int32"

.PP
Definition at line 184 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_Int8"

.PP
Definition at line 186 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_Int8_Dither"

.PP
Definition at line 187 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_UInt8"

.PP
Definition at line 188 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int16_To_UInt8_Dither"

.PP
Definition at line 189 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Float32"

.PP
Definition at line 174 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Int16"

.PP
Definition at line 176 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Int16_Dither"

.PP
Definition at line 177 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Int32"

.PP
Definition at line 175 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Int8"

.PP
Definition at line 178 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_Int8_Dither"

.PP
Definition at line 179 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_UInt8"

.PP
Definition at line 180 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int24_To_UInt8_Dither"

.PP
Definition at line 181 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Float32"

.PP
Definition at line 164 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int16"

.PP
Definition at line 167 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int16_Dither"

.PP
Definition at line 168 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int24"

.PP
Definition at line 165 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int24_Dither"

.PP
Definition at line 166 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int8"

.PP
Definition at line 169 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_Int8_Dither"

.PP
Definition at line 170 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_UInt8"

.PP
Definition at line 171 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int32_To_UInt8_Dither"

.PP
Definition at line 172 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int8_To_Float32"

.PP
Definition at line 191 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int8_To_Int16"

.PP
Definition at line 194 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int8_To_Int24"

.PP
Definition at line 193 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int8_To_Int32"

.PP
Definition at line 192 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::Int8_To_UInt8"

.PP
Definition at line 195 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::UInt8_To_Float32"

.PP
Definition at line 197 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::UInt8_To_Int16"

.PP
Definition at line 200 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::UInt8_To_Int24"

.PP
Definition at line 199 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::UInt8_To_Int32"

.PP
Definition at line 198 of file pa_converters\&.h\&.
.SS "\fBPaUtilConverter\fP* PaUtilConverterTable::UInt8_To_Int8"

.PP
Definition at line 201 of file pa_converters\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
