.TH "PaWasapiJackDescription" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWasapiJackDescription \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_win_wasapi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBchannelMapping\fP"
.br
.ti -1c
.RI "unsigned long \fBcolor\fP"
.br
.ti -1c
.RI "\fBPaWasapiJackConnectionType\fP \fBconnectionType\fP"
.br
.ti -1c
.RI "\fBPaWasapiJackGeoLocation\fP \fBgeoLocation\fP"
.br
.ti -1c
.RI "\fBPaWasapiJackGenLocation\fP \fBgenLocation\fP"
.br
.ti -1c
.RI "\fBPaWasapiJackPortConnection\fP \fBportConnection\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBisConnected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 192 of file pa_win_wasapi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long PaWasapiJackDescription::channelMapping"

.PP
Definition at line 194 of file pa_win_wasapi\&.h\&.
.SS "unsigned long PaWasapiJackDescription::color"

.PP
Definition at line 195 of file pa_win_wasapi\&.h\&.
.SS "\fBPaWasapiJackConnectionType\fP PaWasapiJackDescription::connectionType"

.PP
Definition at line 196 of file pa_win_wasapi\&.h\&.
.SS "\fBPaWasapiJackGenLocation\fP PaWasapiJackDescription::genLocation"

.PP
Definition at line 198 of file pa_win_wasapi\&.h\&.
.SS "\fBPaWasapiJackGeoLocation\fP PaWasapiJackDescription::geoLocation"

.PP
Definition at line 197 of file pa_win_wasapi\&.h\&.
.SS "unsigned \fBint\fP PaWasapiJackDescription::isConnected"

.PP
Definition at line 200 of file pa_win_wasapi\&.h\&.
.SS "\fBPaWasapiJackPortConnection\fP PaWasapiJackDescription::portConnection"

.PP
Definition at line 199 of file pa_win_wasapi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
