.TH "PaWinMmeDeviceInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinMmeDeviceInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaDeviceInfo\fP \fBinheritedDeviceInfo\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwFormats\fP"
.br
.ti -1c
.RI "char \fBdeviceInputChannelCountIsKnown\fP"
.br
.ti -1c
.RI "char \fBdeviceOutputChannelCountIsKnown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 443 of file pa_win_wmme\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char PaWinMmeDeviceInfo::deviceInputChannelCountIsKnown"
< if the system returns 0xFFFF then we don't really know the number of supported channels (1=>known, 0=>unknown) 
.PP
Definition at line 447 of file pa_win_wmme\&.c\&.
.SS "char PaWinMmeDeviceInfo::deviceOutputChannelCountIsKnown"
< if the system returns 0xFFFF then we don't really know the number of supported channels (1=>known, 0=>unknown) 
.PP
Definition at line 448 of file pa_win_wmme\&.c\&.
.SS "\fBDWORD\fP PaWinMmeDeviceInfo::dwFormats"
< standard formats bitmask from the WAVEINCAPS and WAVEOUTCAPS structures 
.PP
Definition at line 446 of file pa_win_wmme\&.c\&.
.SS "\fBPaDeviceInfo\fP PaWinMmeDeviceInfo::inheritedDeviceInfo"

.PP
Definition at line 445 of file pa_win_wmme\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
