.TH "PaWinDirectSoundStreamInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinDirectSoundStreamInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_win_ds\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBsize\fP"
.br
.ti -1c
.RI "\fBPaHostApiTypeId\fP \fBhostApiType\fP"
.br
.ti -1c
.RI "unsigned long \fBversion\fP"
.br
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.ti -1c
.RI "unsigned long \fBframesPerBuffer\fP"
.br
.ti -1c
.RI "\fBPaWinWaveFormatChannelMask\fP \fBchannelMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file pa_win_ds\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPaWinWaveFormatChannelMask\fP PaWinDirectSoundStreamInfo::channelMask"
support for WAVEFORMATEXTENSIBLE channel masks\&. If flags contains paWinDirectSoundUseChannelMask this allows you to specify which speakers to address in a multichannel stream\&. Constants for channelMask are specified in \fBpa_win_waveformat\&.h\fP 
.PP
Definition at line 85 of file pa_win_ds\&.h\&.
.SS "unsigned long PaWinDirectSoundStreamInfo::flags"
enable other features of this struct 
.PP
Definition at line 64 of file pa_win_ds\&.h\&.
.SS "unsigned long PaWinDirectSoundStreamInfo::framesPerBuffer"
low-level latency setting support Sets the size of the DirectSound host buffer\&. When flags contains the paWinDirectSoundUseLowLevelLatencyParameters this size will be used instead of interpreting the generic latency parameters to \fBPa_OpenStream()\fP\&. If the flag is not set this value is ignored\&.
.PP
If the stream is a full duplex stream the implementation requires that the values of framesPerBuffer for input and output match (if both are specified)\&. 
.PP
Definition at line 76 of file pa_win_ds\&.h\&.
.SS "\fBPaHostApiTypeId\fP PaWinDirectSoundStreamInfo::hostApiType"
paDirectSound 
.PP
Definition at line 61 of file pa_win_ds\&.h\&.
.SS "unsigned long PaWinDirectSoundStreamInfo::size"
sizeof(PaWinDirectSoundStreamInfo) 
.PP
Definition at line 60 of file pa_win_ds\&.h\&.
.SS "unsigned long PaWinDirectSoundStreamInfo::version"
2 
.PP
Definition at line 62 of file pa_win_ds\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
