.TH "PaWinMmeDeviceAndChannelCount" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinMmeDeviceAndChannelCount \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_win_wmme\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBdevice\fP"
.br
.ti -1c
.RI "\fBint\fP \fBchannelCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file pa_win_wmme\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP PaWinMmeDeviceAndChannelCount::channelCount"

.PP
Definition at line 78 of file pa_win_wmme\&.h\&.
.SS "\fBPaDeviceIndex\fP PaWinMmeDeviceAndChannelCount::device"

.PP
Definition at line 77 of file pa_win_wmme\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
