.TH "PaWinDsDeviceInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinDsDeviceInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaDeviceInfo\fP \fBinheritedDeviceInfo\fP"
.br
.ti -1c
.RI "GUID \fBguid\fP"
.br
.ti -1c
.RI "GUID * \fBlpGUID\fP"
.br
.ti -1c
.RI "double \fBsampleRates\fP [3]"
.br
.ti -1c
.RI "char \fBdeviceInputChannelCountIsKnown\fP"
.br
.ti -1c
.RI "char \fBdeviceOutputChannelCountIsKnown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 221 of file pa_win_ds\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char PaWinDsDeviceInfo::deviceInputChannelCountIsKnown"
< if the system returns 0xFFFF then we don't really know the number of supported channels (1=>known, 0=>unknown) 
.PP
Definition at line 227 of file pa_win_ds\&.c\&.
.SS "char PaWinDsDeviceInfo::deviceOutputChannelCountIsKnown"
< if the system returns 0xFFFF then we don't really know the number of supported channels (1=>known, 0=>unknown) 
.PP
Definition at line 228 of file pa_win_ds\&.c\&.
.SS "GUID PaWinDsDeviceInfo::guid"

.PP
Definition at line 224 of file pa_win_ds\&.c\&.
.SS "\fBPaDeviceInfo\fP PaWinDsDeviceInfo::inheritedDeviceInfo"

.PP
Definition at line 223 of file pa_win_ds\&.c\&.
.SS "GUID* PaWinDsDeviceInfo::lpGUID"

.PP
Definition at line 225 of file pa_win_ds\&.c\&.
.SS "double PaWinDsDeviceInfo::sampleRates[3]"

.PP
Definition at line 226 of file pa_win_ds\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
