.TH "PaWinDsDSoundEntryPoints" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinDsDSoundEntryPoints \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pa_win_ds_dynlink\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DllGetClassObject)(REFCLSID"
.br
.ti -1c
.RI "\fBLPVOID\fP * \fBHRESULT\fP (\fBWINAPI\fP *DirectSoundCreate)(LPGUID"
.br
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DirectSoundEnumerateW)(LPDSENUMCALLBACKW"
.br
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DirectSoundEnumerateA)(LPDSENUMCALLBACKA"
.br
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DirectSoundCaptureCreate)(LPGUID"
.br
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DirectSoundCaptureEnumerateW)(LPDSENUMCALLBACKW"
.br
.ti -1c
.RI "\fBHRESULT\fP (\fBWINAPI\fP *DirectSoundCaptureEnumerateA)(LPDSENUMCALLBACKA"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HINSTANCE \fBhInstance_\fP"
.br
.ti -1c
.RI "\fBREFIID\fP"
.br
.ti -1c
.RI "\fBLPVOID\fP LPDIRECTSOUND \fBLPUNKNOWN\fP"
.br
.ti -1c
.RI "\fBLPVOID\fP"
.br
.ti -1c
.RI "LPDIRECTSOUNDCAPTURE \fBLPUNKNOWN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file pa_win_ds_dynlink\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DllGetClassObject)"

.SS "\fBLPVOID\fP* PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundCreate)"

.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundEnumerateW)"

.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundEnumerateA)"

.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundCaptureCreate)"

.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundCaptureEnumerateW)"

.SS "PaWinDsDSoundEntryPoints::HRESULT (\fBWINAPI\fP * DirectSoundCaptureEnumerateA)"

.SH "Member Data Documentation"
.PP 
.SS "HINSTANCE PaWinDsDSoundEntryPoints::hInstance_"

.PP
Definition at line 76 of file pa_win_ds_dynlink\&.h\&.
.SS "\fBLPVOID\fP LPDIRECTSOUND PaWinDsDSoundEntryPoints::LPUNKNOWN"

.PP
Definition at line 80 of file pa_win_ds_dynlink\&.h\&.
.SS "LPDIRECTSOUNDCAPTURE PaWinDsDSoundEntryPoints::LPUNKNOWN"

.PP
Definition at line 84 of file pa_win_ds_dynlink\&.h\&.
.SS "PaWinDsDSoundEntryPoints::LPVOID"

.PP
Definition at line 81 of file pa_win_ds_dynlink\&.h\&.
.SS "PaWinDsDSoundEntryPoints::REFIID"

.PP
Definition at line 78 of file pa_win_ds_dynlink\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
