.TH "PaWinMmeStream" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaWinMmeStream \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPaUtilStreamRepresentation\fP \fBstreamRepresentation\fP"
.br
.ti -1c
.RI "\fBPaUtilCpuLoadMeasurer\fP \fBcpuLoadMeasurer\fP"
.br
.ti -1c
.RI "\fBPaUtilBufferProcessor\fP \fBbufferProcessor\fP"
.br
.ti -1c
.RI "\fBint\fP \fBprimeStreamUsingCallback\fP"
.br
.ti -1c
.RI "\fBPaWinMmeSingleDirectionHandlesAndBuffers\fP \fBinput\fP"
.br
.ti -1c
.RI "\fBPaWinMmeSingleDirectionHandlesAndBuffers\fP \fBoutput\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBabortEvent\fP"
.br
.ti -1c
.RI "\fBHANDLE\fP \fBprocessingThread\fP"
.br
.ti -1c
.RI "\fBPA_THREAD_ID\fP \fBprocessingThreadId\fP"
.br
.ti -1c
.RI "char \fBthrottleProcessingThreadOnOverload\fP"
.br
.ti -1c
.RI "\fBint\fP \fBprocessingThreadPriority\fP"
.br
.ti -1c
.RI "\fBint\fP \fBhighThreadPriority\fP"
.br
.ti -1c
.RI "\fBint\fP \fBthrottledThreadPriority\fP"
.br
.ti -1c
.RI "unsigned long \fBthrottledSleepMsecs\fP"
.br
.ti -1c
.RI "\fBint\fP \fBisStopped\fP"
.br
.ti -1c
.RI "volatile \fBint\fP \fBisActive\fP"
.br
.ti -1c
.RI "volatile \fBint\fP \fBstopProcessing\fP"
.br
.ti -1c
.RI "volatile \fBint\fP \fBabortProcessing\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBallBuffersDurationMs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2165 of file pa_win_wmme\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHANDLE\fP PaWinMmeStream::abortEvent"

.PP
Definition at line 2177 of file pa_win_wmme\&.c\&.
.SS "volatile \fBint\fP PaWinMmeStream::abortProcessing"

.PP
Definition at line 2190 of file pa_win_wmme\&.c\&.
.SS "\fBDWORD\fP PaWinMmeStream::allBuffersDurationMs"

.PP
Definition at line 2192 of file pa_win_wmme\&.c\&.
.SS "\fBPaUtilBufferProcessor\fP PaWinMmeStream::bufferProcessor"

.PP
Definition at line 2169 of file pa_win_wmme\&.c\&.
.SS "\fBPaUtilCpuLoadMeasurer\fP PaWinMmeStream::cpuLoadMeasurer"

.PP
Definition at line 2168 of file pa_win_wmme\&.c\&.
.SS "\fBint\fP PaWinMmeStream::highThreadPriority"

.PP
Definition at line 2183 of file pa_win_wmme\&.c\&.
.SS "\fBPaWinMmeSingleDirectionHandlesAndBuffers\fP PaWinMmeStream::input"

.PP
Definition at line 2173 of file pa_win_wmme\&.c\&.
.SS "volatile \fBint\fP PaWinMmeStream::isActive"

.PP
Definition at line 2188 of file pa_win_wmme\&.c\&.
.SS "\fBint\fP PaWinMmeStream::isStopped"

.PP
Definition at line 2187 of file pa_win_wmme\&.c\&.
.SS "\fBPaWinMmeSingleDirectionHandlesAndBuffers\fP PaWinMmeStream::output"

.PP
Definition at line 2174 of file pa_win_wmme\&.c\&.
.SS "\fBint\fP PaWinMmeStream::primeStreamUsingCallback"

.PP
Definition at line 2171 of file pa_win_wmme\&.c\&.
.SS "\fBHANDLE\fP PaWinMmeStream::processingThread"

.PP
Definition at line 2178 of file pa_win_wmme\&.c\&.
.SS "\fBPA_THREAD_ID\fP PaWinMmeStream::processingThreadId"

.PP
Definition at line 2179 of file pa_win_wmme\&.c\&.
.SS "\fBint\fP PaWinMmeStream::processingThreadPriority"

.PP
Definition at line 2182 of file pa_win_wmme\&.c\&.
.SS "volatile \fBint\fP PaWinMmeStream::stopProcessing"

.PP
Definition at line 2189 of file pa_win_wmme\&.c\&.
.SS "\fBPaUtilStreamRepresentation\fP PaWinMmeStream::streamRepresentation"

.PP
Definition at line 2167 of file pa_win_wmme\&.c\&.
.SS "unsigned long PaWinMmeStream::throttledSleepMsecs"

.PP
Definition at line 2185 of file pa_win_wmme\&.c\&.
.SS "\fBint\fP PaWinMmeStream::throttledThreadPriority"

.PP
Definition at line 2184 of file pa_win_wmme\&.c\&.
.SS "char PaWinMmeStream::throttleProcessingThreadOnOverload"

.PP
Definition at line 2181 of file pa_win_wmme\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
