.TH "C:/_dev/OpenU/Audacity/audacity/src/blockfile/PCMAliasBlockFile.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/blockfile/PCMAliasBlockFile.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/file\&.h>\fP
.br
\fC#include <wx/utils\&.h>\fP
.br
\fC#include <wx/wxchar\&.h>\fP
.br
\fC#include <wx/log\&.h>\fP
.br
\fC#include <sndfile\&.h>\fP
.br
\fC#include 'PCMAliasBlockFile\&.h'\fP
.br
\fC#include '\&.\&./FileFormats\&.h'\fP
.br
\fC#include '\&.\&./Internat\&.h'\fP
.br
\fC#include '\&.\&./MemoryX\&.h'\fP
.br
\fC#include '\&.\&./ondemand/ODManager\&.h'\fP
.br
\fC#include '\&.\&./AudioIO\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAudioIO\fP * \fBgAudioIO\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBAudioIO\fP* gAudioIO"

.PP
Definition at line 329 of file AudioIO\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
