.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Tools/perl.py" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Tools/perl.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaflib\&.Tools\&.perl\&.xsubpp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwaflib\&.Tools\&.perl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.init_perlext\fP (self)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.xsubpp_file\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.check_perl_version\fP (self, minver=None)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.check_perl_module\fP (self, module)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.check_perl_ext_devel\fP (self)"
.br
.ti -1c
.RI "def \fBwaflib\&.Tools\&.perl\&.options\fP (opt)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
