.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/pffft32s.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/pffft32s.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pffft\&.c'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBvoid\fP(* \fBfn_t\fP) (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfn_t\fP \fB_soxr_rdft32s_cb\fP []"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBvoid\fP(*  fn_t) (\fBvoid\fP)"

.PP
Definition at line 14 of file pffft32s\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBfn_t\fP _soxr_rdft32s_cb[]"
\fBInitial value:\fP
.PP
.nf
= {
  (fn_t)setup,
  (fn_t)setup,
  (fn_t)pffft_destroy_setup,
  (fn_t)forward,
  (fn_t)oforward,
  (fn_t)backward,
  (fn_t)obackward,
  (fn_t)convolve,
  (fn_t)_soxr_ordered_partial_convolve_simd,
  (fn_t)multiplier,
  (fn_t)pffft_reorder_back,
}
.fi
.PP
Definition at line 15 of file pffft32s\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
