.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/grabbag/picture.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/grabbag/picture.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'share/alloc\&.h'\fP
.br
\fC#include 'share/grabbag\&.h'\fP
.br
\fC#include 'FLAC/assert\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'share/compat\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP * \fBgrabbag__picture_parse_specification\fP (\fBconst\fP char *spec, \fBconst\fP char **error_message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata\fP* grabbag__picture_parse_specification (\fBconst\fP char * spec, \fBconst\fP char ** error_message)"

.PP
Definition at line 264 of file picture\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
