.TH "PlatformCompatibility" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlatformCompatibility \- Filename Compatibility utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlatformCompatibility\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static wxString \fBGetLongFileName\fP (\fBconst\fP wxString &shortFileName)"
.br
.ti -1c
.RI "static wxString \fBGetExecutablePath\fP ()"
.br
.ti -1c
.RI "static wxString \fBConvertSlashInFileName\fP (\fBconst\fP wxString &filePath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filename Compatibility utilities\&. 


.PP
\fBSee also:\fP
.RS 4
\fBFileNames\fP 
.RE
.PP

.PP
Definition at line 25 of file PlatformCompatibility\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "wxString PlatformCompatibility::ConvertSlashInFileName (\fBconst\fP wxString & filePath)\fC [static]\fP"

.PP
Definition at line 48 of file PlatformCompatibility\&.cpp\&.
.SS "wxString PlatformCompatibility::GetExecutablePath ()\fC [static]\fP"

.PP
Definition at line 34 of file PlatformCompatibility\&.cpp\&.
.SS "wxString PlatformCompatibility::GetLongFileName (\fBconst\fP wxString & shortFileName)\fC [static]\fP"

.PP
Definition at line 27 of file PlatformCompatibility\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
