.TH "PluginManagerInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginManagerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PluginInterface\&.h>\fP
.PP
Inherited by \fBPluginManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PluginManagerInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBIsPluginRegistered\fP (\fBconst\fP wxString &path)=0"
.br
.ti -1c
.RI "virtual \fBconst\fP \fBPluginID\fP & \fBRegisterPlugin\fP (\fBModuleInterface\fP *module)=0"
.br
.ti -1c
.RI "virtual \fBconst\fP \fBPluginID\fP & \fBRegisterPlugin\fP (\fBModuleInterface\fP *provider, \fBEffectIdentInterface\fP *effect)=0"
.br
.ti -1c
.RI "virtual \fBconst\fP \fBPluginID\fP & \fBRegisterPlugin\fP (\fBModuleInterface\fP *provider, \fBImporterInterface\fP *importer)=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBFindFilesInPathList\fP (\fBconst\fP wxString &pattern, \fBconst\fP wxArrayString &pathList, wxArrayString &files, \fBbool\fP directories=\fBfalse\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfigSubgroups\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, wxArrayString &subgroups)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, wxString &\fBvalue\fP, \fBconst\fP wxString &defval=wxString())=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBint\fP &\fBvalue\fP, \fBint\fP defval=0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBbool\fP &\fBvalue\fP, \fBbool\fP defval=\fBfalse\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, float &\fBvalue\fP, float defval=0\&.0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, double &\fBvalue\fP, double defval=0\&.0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBsampleCount\fP &\fBvalue\fP, \fBsampleCount\fP defval=0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP wxString &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBint\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBbool\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP float &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP double &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBsampleCount\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBRemoveSharedConfigSubgroup\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBRemoveSharedConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfigSubgroups\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, wxArrayString &subgroups)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, wxString &\fBvalue\fP, \fBconst\fP wxString &defval=wxString())=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBint\fP &\fBvalue\fP, \fBint\fP defval=0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBbool\fP &\fBvalue\fP, \fBbool\fP defval=\fBfalse\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, float &\fBvalue\fP, float defval=0\&.0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, double &\fBvalue\fP, double defval=0\&.0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBGetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBsampleCount\fP &\fBvalue\fP, \fBsampleCount\fP defval=0)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP wxString &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBint\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBbool\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP float &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP double &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSetPrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key, \fBconst\fP \fBsampleCount\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBRemovePrivateConfigSubgroup\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBRemovePrivateConfig\fP (\fBconst\fP \fBPluginID\fP &ID, \fBconst\fP wxString &group, \fBconst\fP wxString &key)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file PluginInterface\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual PluginManagerInterface::~PluginManagerInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 57 of file PluginInterface\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvoid\fP PluginManagerInterface::FindFilesInPathList (\fBconst\fP wxString & pattern, \fBconst\fP wxArrayString & pathList, wxArrayString & files, \fBbool\fP directories = \fC\fBfalse\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, wxString & value, \fBconst\fP wxString & defval = \fCwxString()\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBint\fP & value, \fBint\fP defval = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBbool\fP & value, \fBbool\fP defval = \fC\fBfalse\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, float & value, float defval = \fC0\&.0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, double & value, double defval = \fC0\&.0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBsampleCount\fP & value, \fBsampleCount\fP defval = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetPrivateConfigSubgroups (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, wxArrayString & subgroups)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, wxString & value, \fBconst\fP wxString & defval = \fCwxString()\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBint\fP & value, \fBint\fP defval = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBbool\fP & value, \fBbool\fP defval = \fC\fBfalse\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, float & value, float defval = \fC0\&.0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, double & value, double defval = \fC0\&.0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBsampleCount\fP & value, \fBsampleCount\fP defval = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::GetSharedConfigSubgroups (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, wxArrayString & subgroups)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::IsPluginRegistered (\fBconst\fP wxString & path)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBconst\fP \fBPluginID\fP& PluginManagerInterface::RegisterPlugin (\fBModuleInterface\fP * module)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBconst\fP \fBPluginID\fP& PluginManagerInterface::RegisterPlugin (\fBModuleInterface\fP * provider, \fBEffectIdentInterface\fP * effect)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBconst\fP \fBPluginID\fP& PluginManagerInterface::RegisterPlugin (\fBModuleInterface\fP * provider, \fBImporterInterface\fP * importer)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::RemovePrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::RemovePrivateConfigSubgroup (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::RemoveSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::RemoveSharedConfigSubgroup (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP wxString & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBint\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBbool\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP float & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP double & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetPrivateConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBsampleCount\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP wxString & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBint\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBbool\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP float & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP double & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.
.SS "virtual \fBbool\fP PluginManagerInterface::SetSharedConfig (\fBconst\fP \fBPluginID\fP & ID, \fBconst\fP wxString & group, \fBconst\fP wxString & key, \fBconst\fP \fBsampleCount\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBPluginManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
