.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/src/vamp-hostsdk/PluginLoader.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvamp/src/vamp-hostsdk/PluginLoader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vamp\-hostsdk/PluginHostAdapter\&.h>\fP
.br
\fC#include <vamp\-hostsdk/PluginLoader\&.h>\fP
.br
\fC#include <vamp\-hostsdk/PluginInputDomainAdapter\&.h>\fP
.br
\fC#include <vamp\-hostsdk/PluginChannelAdapter\&.h>\fP
.br
\fC#include <vamp\-hostsdk/PluginBufferingAdapter\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <dlfcn\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVamp::HostExt::PluginLoader::Impl\fP"
.br
.ti -1c
.RI "class \fBVamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter\fP"
.br
.ti -1c
.RI "class \fBVamp::HostExt::PluginLoader::Impl::InstanceCleaner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBVamp\fP"
.br
.ti -1c
.RI " \fBVamp::HostExt\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPLUGIN_SUFFIX\fP   'so'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PLUGIN_SUFFIX   'so'"

.PP
Definition at line 62 of file PluginLoader\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
