.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_csharp/pm_managed/pm_managed.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_csharp/pm_managed/pm_managed.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'portmidi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpm_managed::MpmDeviceInfo\fP"
.br
.ti -1c
.RI "class \fBpm_managed::ManagedPortMIDI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpm_managed\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
