.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_common/pminternal.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_common/pminternal.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpm_fns_node\fP"
.br
.ti -1c
.RI "struct \fBdescriptor_node\fP"
.br
.ti -1c
.RI "struct \fBpm_internal_struct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBnone_write_flush\fP   \fBpm_fail_timestamp_fn\fP"
.br
.ti -1c
.RI "#define \fBnone_sysex\fP   \fBpm_fail_timestamp_fn\fP"
.br
.ti -1c
.RI "#define \fBnone_poll\fP   \fBpm_fail_fn\fP"
.br
.ti -1c
.RI "#define \fBsuccess_poll\fP   \fBpm_success_fn\fP"
.br
.ti -1c
.RI "#define \fBMIDI_REALTIME_MASK\fP   0xf8"
.br
.ti -1c
.RI "#define \fBis_real_time\fP(msg)   ((\fBPm_MessageStatus\fP(msg) & \fBMIDI_REALTIME_MASK\fP) == \fBMIDI_REALTIME_MASK\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_write_short_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmEvent\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_begin_sysex_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_end_sysex_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_write_byte_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, unsigned char byte, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_write_realtime_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmEvent\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_write_flush_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "typedef \fBPmTimestamp\fP(* \fBpm_synchronize_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_open_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBvoid\fP *driverInfo)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_abort_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_close_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "typedef \fBPmError\fP(* \fBpm_poll_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "typedef \fBvoid\fP(* \fBpm_host_error_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP, char *msg, unsigned \fBint\fP \fBlen\fP)"
.br
.ti -1c
.RI "typedef unsigned \fBint\fP(* \fBpm_has_host_error_fn\fP) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "typedef struct \fBpm_fns_node\fP * \fBpm_fns_type\fP"
.br
.ti -1c
.RI "typedef struct \fBdescriptor_node\fP * \fBdescriptor_type\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP(* \fBtime_get_proc_type\fP) (\fBvoid\fP *time_info)"
.br
.ti -1c
.RI "typedef struct \fBpm_internal_struct\fP \fBPmInternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBpm_alloc\fP (size_t \fBs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpm_free\fP (\fBvoid\fP *ptr)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpm_init\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpm_term\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBPmError\fP \fBnone_write_short\fP (\fBPmInternal\fP *\fBmidi\fP, \fBPmEvent\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "\fBPmError\fP \fBnone_write_byte\fP (\fBPmInternal\fP *\fBmidi\fP, unsigned char byte, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "\fBPmTimestamp\fP \fBnone_synchronize\fP (\fBPmInternal\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "\fBPmError\fP \fBpm_fail_fn\fP (\fBPmInternal\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "\fBPmError\fP \fBpm_fail_timestamp_fn\fP (\fBPmInternal\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "\fBPmError\fP \fBpm_success_fn\fP (\fBPmInternal\fP *\fBmidi\fP)"
.br
.ti -1c
.RI "\fBPmError\fP \fBpm_add_device\fP (char *interf, char *\fBname\fP, \fBint\fP input, \fBvoid\fP *descriptor, \fBpm_fns_type\fP dictionary)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpm_read_bytes\fP (\fBPmInternal\fP *\fBmidi\fP, \fBconst\fP unsigned char *\fBdata\fP, \fBint\fP \fBlen\fP, \fBPmTimestamp\fP timestamp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpm_read_short\fP (\fBPmInternal\fP *\fBmidi\fP, \fBPmEvent\fP *event)"
.br
.ti -1c
.RI "\fBint\fP \fBpm_find_default_device\fP (char *pattern, \fBint\fP is_input)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBpm_initialized\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpm_hosterror\fP"
.br
.ti -1c
.RI "char \fBpm_hosterror_text\fP [\fBPM_HOST_ERROR_MSG_LEN\fP]"
.br
.ti -1c
.RI "\fBpm_fns_node\fP \fBpm_none_dictionary\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpm_descriptor_max\fP"
.br
.ti -1c
.RI "\fBdescriptor_type\fP \fBdescriptors\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpm_descriptor_index\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define is_real_time(msg)   ((\fBPm_MessageStatus\fP(msg) & \fBMIDI_REALTIME_MASK\fP) == \fBMIDI_REALTIME_MASK\fP)"

.PP
Definition at line 170 of file pminternal\&.h\&.
.SS "#define MIDI_REALTIME_MASK   0xf8"

.PP
Definition at line 169 of file pminternal\&.h\&.
.SS "#define none_poll   \fBpm_fail_fn\fP"

.PP
Definition at line 166 of file pminternal\&.h\&.
.SS "#define none_sysex   \fBpm_fail_timestamp_fn\fP"

.PP
Definition at line 165 of file pminternal\&.h\&.
.SS "#define none_write_flush   \fBpm_fail_timestamp_fn\fP"

.PP
Definition at line 164 of file pminternal\&.h\&.
.SS "#define success_poll   \fBpm_success_fn\fP"

.PP
Definition at line 167 of file pminternal\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef  struct \fBdescriptor_node\fP * \fBdescriptor_type\fP"

.SS "typedef \fBPmError\fP(* pm_abort_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"

.PP
Definition at line 54 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_begin_sysex_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 39 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_close_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"

.PP
Definition at line 57 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_end_sysex_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 41 of file pminternal\&.h\&.
.SS "typedef  struct \fBpm_fns_node\fP * \fBpm_fns_type\fP"

.SS "typedef unsigned \fBint\fP(* pm_has_host_error_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"

.PP
Definition at line 61 of file pminternal\&.h\&.
.SS "typedef \fBvoid\fP(* pm_host_error_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, char *msg, unsigned \fBint\fP \fBlen\fP)"

.PP
Definition at line 59 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_open_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBvoid\fP *driverInfo)"

.PP
Definition at line 52 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_poll_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"

.PP
Definition at line 58 of file pminternal\&.h\&.
.SS "typedef \fBPmTimestamp\fP(* pm_synchronize_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP)"

.PP
Definition at line 49 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_write_byte_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, unsigned char byte, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 43 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_write_flush_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 47 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_write_realtime_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmEvent\fP *\fBbuffer\fP)"

.PP
Definition at line 45 of file pminternal\&.h\&.
.SS "typedef \fBPmError\fP(* pm_write_short_fn) (struct \fBpm_internal_struct\fP *\fBmidi\fP, \fBPmEvent\fP *\fBbuffer\fP)"

.PP
Definition at line 37 of file pminternal\&.h\&.
.SS "typedef struct \fBpm_internal_struct\fP  \fBPmInternal\fP"

.SS "typedef \fBuint32_t\fP(* time_get_proc_type) (\fBvoid\fP *time_info)"

.PP
Definition at line 98 of file pminternal\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBPmTimestamp\fP none_synchronize (\fBPmInternal\fP * midi)"

.PP
Definition at line 225 of file portmidi\&.c\&.
.SS "\fBPmError\fP none_write_byte (\fBPmInternal\fP * midi, unsigned char byte, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 206 of file portmidi\&.c\&.
.SS "\fBPmError\fP none_write_short (\fBPmInternal\fP * midi, \fBPmEvent\fP * buffer)"

.PP
Definition at line 197 of file portmidi\&.c\&.
.SS "\fBPmError\fP pm_add_device (char * interf, char * name, \fBint\fP input, \fBvoid\fP * descriptor, \fBpm_fns_type\fP dictionary)"

.PP
Definition at line 102 of file portmidi\&.c\&.
.SS "\fBvoid\fP* pm_alloc (size_t s)"

.PP
Definition at line 70 of file pmlinux\&.c\&.
.SS "\fBPmError\fP pm_fail_fn (\fBPmInternal\fP * midi)"

.PP
Definition at line 212 of file portmidi\&.c\&.
.SS "\fBPmError\fP pm_fail_timestamp_fn (\fBPmInternal\fP * midi, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 202 of file portmidi\&.c\&.
.SS "\fBint\fP pm_find_default_device (char * pattern, \fBint\fP is_input)"

.PP
Definition at line 142 of file portmidi\&.c\&.
.SS "\fBvoid\fP pm_free (\fBvoid\fP * ptr)"

.PP
Definition at line 72 of file pmlinux\&.c\&.
.SS "\fBvoid\fP pm_init (\fBvoid\fP)"

.PP
Definition at line 29 of file pmlinux\&.c\&.
.SS "\fBuint32_t\fP pm_read_bytes (\fBPmInternal\fP * midi, \fBconst\fP unsigned char * data, \fBint\fP len, \fBPmTimestamp\fP timestamp)"

.PP
Definition at line 1055 of file portmidi\&.c\&.
.SS "\fBvoid\fP pm_read_short (\fBPmInternal\fP * midi, \fBPmEvent\fP * event)"

.PP
Definition at line 1015 of file portmidi\&.c\&.
.SS "\fBPmError\fP pm_success_fn (\fBPmInternal\fP * midi)"

.PP
Definition at line 192 of file portmidi\&.c\&.
.SS "\fBvoid\fP pm_term (\fBvoid\fP)"

.PP
Definition at line 53 of file pmlinux\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBdescriptor_type\fP descriptors"

.PP
Definition at line 91 of file portmidi\&.c\&.
.SS "\fBint\fP pm_descriptor_index"

.PP
Definition at line 90 of file portmidi\&.c\&.
.SS "\fBint\fP pm_descriptor_max"

.PP
Definition at line 89 of file portmidi\&.c\&.
.SS "\fBint\fP pm_hosterror"

.PP
Definition at line 44 of file portmidi\&.c\&.
.SS "char pm_hosterror_text[\fBPM_HOST_ERROR_MSG_LEN\fP]"

.PP
Definition at line 45 of file portmidi\&.c\&.
.SS "\fBint\fP pm_initialized"

.PP
Definition at line 42 of file portmidi\&.c\&.
.SS "\fBpm_fns_node\fP pm_none_dictionary"

.PP
Definition at line 232 of file portmidi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
