.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_linux/pmlinuxalsa.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/pm_linux/pmlinuxalsa.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPmError\fP \fBpm_linuxalsa_init\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpm_linuxalsa_term\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPmError\fP pm_linuxalsa_init (\fBvoid\fP)"

.PP
Definition at line 723 of file pmlinuxalsa\&.c\&.
.SS "\fBvoid\fP pm_linuxalsa_term (\fBvoid\fP)"

.PP
Definition at line 781 of file pmlinuxalsa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
