.TH "portaudio::BlockingStream" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portaudio::BlockingStream \- \fBStream\fP class for blocking read/write-style input and output\&. ///\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockingStream\&.hxx>\fP
.PP
Inherits \fBportaudio::Stream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockingStream\fP ()"
.br
.ti -1c
.RI "\fBBlockingStream\fP (\fBconst\fP \fBStreamParameters\fP &parameters)"
.br
.ti -1c
.RI "\fB~BlockingStream\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBopen\fP (\fBconst\fP \fBStreamParameters\fP &parameters)"
.br
.ti -1c
.RI "\fBvoid\fP \fBread\fP (\fBvoid\fP *\fBbuffer\fP, unsigned long numFrames)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP \fBvoid\fP *\fBbuffer\fP, unsigned long numFrames)"
.br
.ti -1c
.RI "signed long \fBavailableReadSize\fP () \fBconst\fP "
.br
.ti -1c
.RI "signed long \fBavailableWriteSize\fP () \fBconst\fP "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBStream\fP class for blocking read/write-style input and output\&. ///\&. 
.PP
Definition at line 18 of file BlockingStream\&.hxx\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "portaudio::BlockingStream::BlockingStream ()"

.PP
Definition at line 13 of file BlockingStream\&.cxx\&.
.SS "portaudio::BlockingStream::BlockingStream (\fBconst\fP \fBStreamParameters\fP & parameters)"

.PP
Definition at line 17 of file BlockingStream\&.cxx\&.
.SS "portaudio::BlockingStream::~BlockingStream ()"

.PP
Definition at line 22 of file BlockingStream\&.cxx\&.
.SH "Member Function Documentation"
.PP 
.SS "signed long portaudio::BlockingStream::availableReadSize () const"

.PP
Definition at line 71 of file BlockingStream\&.cxx\&.
.SS "signed long portaudio::BlockingStream::availableWriteSize () const"

.PP
Definition at line 83 of file BlockingStream\&.cxx\&.
.SS "\fBvoid\fP portaudio::BlockingStream::open (\fBconst\fP \fBStreamParameters\fP & parameters)"

.PP
Definition at line 36 of file BlockingStream\&.cxx\&.
.SS "\fBvoid\fP portaudio::BlockingStream::read (\fBvoid\fP * buffer, unsigned long numFrames)"

.PP
Definition at line 49 of file BlockingStream\&.cxx\&.
.SS "\fBvoid\fP portaudio::BlockingStream::write (\fBconst\fP \fBvoid\fP * buffer, unsigned long numFrames)"

.PP
Definition at line 59 of file BlockingStream\&.cxx\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
