.TH "portaudio::CallbackInterface" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portaudio::CallbackInterface \- Interface for an object that's callable as a PortAudioCpp callback object (ie that implements the paCallbackFun method)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CallbackInterface\&.hxx>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~CallbackInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBint\fP \fBpaCallbackFun\fP (\fBconst\fP \fBvoid\fP *inputBuffer, \fBvoid\fP *outputBuffer, unsigned long numFrames, \fBconst\fP \fBPaStreamCallbackTimeInfo\fP *timeInfo, \fBPaStreamCallbackFlags\fP statusFlags)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for an object that's callable as a PortAudioCpp callback object (ie that implements the paCallbackFun method)\&. 
.PP
Definition at line 18 of file CallbackInterface\&.hxx\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual portaudio::CallbackInterface::~CallbackInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 21 of file CallbackInterface\&.hxx\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBint\fP portaudio::CallbackInterface::paCallbackFun (\fBconst\fP \fBvoid\fP * inputBuffer, \fBvoid\fP * outputBuffer, unsigned long numFrames, \fBconst\fP \fBPaStreamCallbackTimeInfo\fP * timeInfo, \fBPaStreamCallbackFlags\fP statusFlags)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
