.TH "portaudio::DirectionSpecificStreamParameters" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portaudio::DirectionSpecificStreamParameters \- All parameters for one direction (either in or out) of a \fBStream\fP\&. Together with parameters common to both directions, two \fBDirectionSpecificStreamParameters\fP can make up a \fBStreamParameters\fP object which contains all parameters for a \fBStream\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DirectionSpecificStreamParameters\&.hxx>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectionSpecificStreamParameters\fP ()"
.br
.RI "\fIDefault constructor -- all parameters will be uninitialized\&. ///\&. \fP"
.ti -1c
.RI "\fBDirectionSpecificStreamParameters\fP (\fBconst\fP \fBDevice\fP &\fBdevice\fP, \fBint\fP \fBnumChannels\fP, \fBSampleDataFormat\fP \fBformat\fP, \fBbool\fP interleaved, \fBPaTime\fP \fBsuggestedLatency\fP, \fBvoid\fP *\fBhostApiSpecificStreamInfo\fP)"
.br
.RI "\fIConstructor which sets all required fields\&. ///\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBsetDevice\fP (\fBconst\fP \fBDevice\fP &\fBdevice\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetNumChannels\fP (\fBint\fP \fBnumChannels\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetSampleFormat\fP (\fBSampleDataFormat\fP \fBformat\fP, \fBbool\fP interleaved=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetHostApiSpecificSampleFormat\fP (\fBPaSampleFormat\fP \fBformat\fP, \fBbool\fP interleaved=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetSuggestedLatency\fP (\fBPaTime\fP \fBlatency\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetHostApiSpecificStreamInfo\fP (\fBvoid\fP *streamInfo)"
.br
.ti -1c
.RI "\fBPaStreamParameters\fP * \fBpaStreamParameters\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBPaStreamParameters\fP * \fBpaStreamParameters\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBDevice\fP & \fBdevice\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBint\fP \fBnumChannels\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBSampleDataFormat\fP \fBsampleFormat\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBisSampleFormatInterleaved\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBisSampleFormatHostApiSpecific\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBPaSampleFormat\fP \fBhostApiSpecificSampleFormat\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBPaTime\fP \fBsuggestedLatency\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP * \fBhostApiSpecificStreamInfo\fP () \fBconst\fP "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDirectionSpecificStreamParameters\fP \fBnull\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
All parameters for one direction (either in or out) of a \fBStream\fP\&. Together with parameters common to both directions, two \fBDirectionSpecificStreamParameters\fP can make up a \fBStreamParameters\fP object which contains all parameters for a \fBStream\fP\&. 
.PP
Definition at line 32 of file DirectionSpecificStreamParameters\&.hxx\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "portaudio::DirectionSpecificStreamParameters::DirectionSpecificStreamParameters ()"

.PP
Default constructor -- all parameters will be uninitialized\&. ///\&. 
.PP
Definition at line 30 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "portaudio::DirectionSpecificStreamParameters::DirectionSpecificStreamParameters (\fBconst\fP \fBDevice\fP & device, \fBint\fP numChannels, \fBSampleDataFormat\fP format, \fBbool\fP interleaved, \fBPaTime\fP suggestedLatency, \fBvoid\fP * hostApiSpecificStreamInfo)"

.PP
Constructor which sets all required fields\&. ///\&. 
.PP
Definition at line 37 of file DirectionSpecificStreamParameters\&.cxx\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDevice\fP & portaudio::DirectionSpecificStreamParameters::device () const"

.PP
Definition at line 105 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBPaSampleFormat\fP portaudio::DirectionSpecificStreamParameters::hostApiSpecificSampleFormat () const"
Returns the host api-specific sample format, without including any paCustomFormat or paNonInterleaved flags\&. Will return 0 if the sample format is not host api-specific\&. 
.PP
Definition at line 143 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP * portaudio::DirectionSpecificStreamParameters::hostApiSpecificStreamInfo () const"

.PP
Definition at line 156 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBbool\fP portaudio::DirectionSpecificStreamParameters::isSampleFormatHostApiSpecific () const"

.PP
Definition at line 133 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBbool\fP portaudio::DirectionSpecificStreamParameters::isSampleFormatInterleaved () const"

.PP
Definition at line 128 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBDirectionSpecificStreamParameters\fP portaudio::DirectionSpecificStreamParameters::null ()\fC [static]\fP"
Returns a `nil' \fBDirectionSpecificStreamParameters\fP object\&. This can be used to specify that one direction of a \fBStream\fP is not required (i\&.e\&. when creating a half-duplex \fBStream\fP)\&. All fields of the null \fBDirectionSpecificStreamParameters\fP object are invalid except for the device and the number of channel, which are set to paNoDevice and 0 respectively\&. 
.PP
Definition at line 17 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBint\fP portaudio::DirectionSpecificStreamParameters::numChannels () const"

.PP
Definition at line 110 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBPaStreamParameters\fP * portaudio::DirectionSpecificStreamParameters::paStreamParameters ()"

.PP
Definition at line 89 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBconst\fP \fBPaStreamParameters\fP * portaudio::DirectionSpecificStreamParameters::paStreamParameters () const"

.PP
Definition at line 97 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBSampleDataFormat\fP portaudio::DirectionSpecificStreamParameters::sampleFormat () const"
Returns the (non host api-specific) sample format, without including the paNonInterleaved flag\&. If the sample format is host api-spefific, INVALID_FORMAT (0) will be returned\&. 
.PP
Definition at line 120 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setDevice (\fBconst\fP \fBDevice\fP & device)"

.PP
Definition at line 49 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setHostApiSpecificSampleFormat (\fBPaSampleFormat\fP format, \fBbool\fP interleaved = \fC\fBtrue\fP\fP)"

.PP
Definition at line 67 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setHostApiSpecificStreamInfo (\fBvoid\fP * streamInfo)"

.PP
Definition at line 82 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setNumChannels (\fBint\fP numChannels)"

.PP
Definition at line 54 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setSampleFormat (\fBSampleDataFormat\fP format, \fBbool\fP interleaved = \fC\fBtrue\fP\fP)"

.PP
Definition at line 59 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBvoid\fP portaudio::DirectionSpecificStreamParameters::setSuggestedLatency (\fBPaTime\fP latency)"

.PP
Definition at line 77 of file DirectionSpecificStreamParameters\&.cxx\&.
.SS "\fBPaTime\fP portaudio::DirectionSpecificStreamParameters::suggestedLatency () const"

.PP
Definition at line 151 of file DirectionSpecificStreamParameters\&.cxx\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
