.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/cpp/include/portaudiocpp/PortAudioCpp.hxx" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/cpp/include/portaudiocpp/PortAudioCpp.hxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'portaudiocpp/AutoSystem\&.hxx'\fP
.br
\fC#include 'portaudiocpp/BlockingStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/CallbackInterface\&.hxx'\fP
.br
\fC#include 'portaudiocpp/CallbackStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/CFunCallbackStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/CppFunCallbackStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/Device\&.hxx'\fP
.br
\fC#include 'portaudiocpp/Exception\&.hxx'\fP
.br
\fC#include 'portaudiocpp/HostApi\&.hxx'\fP
.br
\fC#include 'portaudiocpp/InterfaceCallbackStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/MemFunCallbackStream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/SampleDataFormat\&.hxx'\fP
.br
\fC#include 'portaudiocpp/DirectionSpecificStreamParameters\&.hxx'\fP
.br
\fC#include 'portaudiocpp/Stream\&.hxx'\fP
.br
\fC#include 'portaudiocpp/StreamParameters\&.hxx'\fP
.br
\fC#include 'portaudiocpp/System\&.hxx'\fP
.br
\fC#include 'portaudiocpp/SystemDeviceIterator\&.hxx'\fP
.br
\fC#include 'portaudiocpp/SystemHostApiIterator\&.hxx'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBportaudio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An include-all header file (for lazy programmers and using pre-compiled headers)\&. 
.PP
Definition in file \fBPortAudioCpp\&.hxx\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
