.TH "PrefsDialog::PrefsNode" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrefsDialog::PrefsNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PrefsDialog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrefsNode\fP (\fBPrefsPanelFactory\fP *pFactory_, \fBint\fP nChildren_=0, \fBbool\fP expanded_=\fBtrue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPrefsPanelFactory\fP *\fBCONST\fP \fBpFactory\fP"
.br
.ti -1c
.RI "\fBCONST\fP \fBint\fP \fBnChildren\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBexpanded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file PrefsDialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PrefsDialog::PrefsNode::PrefsNode (\fBPrefsPanelFactory\fP * pFactory_, \fBint\fP nChildren_ = \fC0\fP, \fBbool\fP expanded_ = \fC\fBtrue\fP\fP)\fC [inline]\fP"

.PP
Definition at line 41 of file PrefsDialog\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP PrefsDialog::PrefsNode::expanded"

.PP
Definition at line 39 of file PrefsDialog\&.h\&.
.SS "\fBCONST\fP \fBint\fP PrefsDialog::PrefsNode::nChildren"

.PP
Definition at line 38 of file PrefsDialog\&.h\&.
.SS "\fBPrefsPanelFactory\fP* \fBCONST\fP PrefsDialog::PrefsNode::pFactory"

.PP
Definition at line 37 of file PrefsDialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
