.TH "PrefsPanelFactory" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrefsPanelFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PrefsPanel\&.h>\fP
.PP
Inherited by \fBBatchPrefsFactory\fP, \fBDevicePrefsFactory\fP, \fBDirectoriesPrefsFactory\fP, \fBEffectsPrefsFactory\fP, \fBExtImportPrefsFactory\fP, \fBGUIPrefsFactory\fP, \fBImportExportPrefsFactory\fP, \fBKeyConfigPrefsFactory\fP, \fBLibraryPrefsFactory\fP, \fBModulePrefsFactory\fP, \fBMousePrefsFactory\fP, \fBPlaybackPrefsFactory\fP, \fBProjectsPrefsFactory\fP, \fBQualityPrefsFactory\fP, \fBRecordingPrefsFactory\fP, \fBSpectrumPrefsFactory\fP, \fBThemePrefsFactory\fP, \fBTracksPrefsFactory\fP, \fBWarningsPrefsFactory\fP, and \fBWaveformPrefsFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBPrefsPanel\fP * \fBCreate\fP (wxWindow *parent)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file PrefsPanel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBPrefsPanel\fP* PrefsPanelFactory::Create (wxWindow * parent)\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyConfigPrefsFactory\fP, \fBExtImportPrefsFactory\fP, \fBSpectrumPrefsFactory\fP, \fBWaveformPrefsFactory\fP, \fBDevicePrefsFactory\fP, \fBQualityPrefsFactory\fP, \fBModulePrefsFactory\fP, \fBLibraryPrefsFactory\fP, \fBGUIPrefsFactory\fP, \fBThemePrefsFactory\fP, \fBRecordingPrefsFactory\fP, \fBTracksPrefsFactory\fP, \fBDirectoriesPrefsFactory\fP, \fBMousePrefsFactory\fP, \fBBatchPrefsFactory\fP, \fBEffectsPrefsFactory\fP, \fBImportExportPrefsFactory\fP, \fBProjectsPrefsFactory\fP, \fBWarningsPrefsFactory\fP, and \fBPlaybackPrefsFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
