.TH "prefix" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prefix \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBBINDING\fP * \fBbinding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBINDING\fP* prefix::binding"

.PP
Definition at line 156 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* prefix::name"

.PP
Definition at line 155 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
