.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/share/private.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/include/share/private.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLAC_API\fP \fBFLAC__bool\fP \fBFLAC__stream_encoder_disable_constant_subframes\fP (\fBFLAC__StreamEncoder\fP *encoder, \fBFLAC__bool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBFLAC_API\fP \fBFLAC__bool\fP \fBFLAC__stream_encoder_disable_fixed_subframes\fP (\fBFLAC__StreamEncoder\fP *encoder, \fBFLAC__bool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBFLAC_API\fP \fBFLAC__bool\fP \fBFLAC__stream_encoder_disable_verbatim_subframes\fP (\fBFLAC__StreamEncoder\fP *encoder, \fBFLAC__bool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBFLAC_API\fP \fBFLAC__bool\fP \fBFLAC__stream_encoder_set_do_md5\fP (\fBFLAC__StreamEncoder\fP *encoder, \fBFLAC__bool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBFLAC_API\fP \fBFLAC__bool\fP \fBFLAC__stream_encoder_get_do_md5\fP (\fBconst\fP \fBFLAC__StreamEncoder\fP *encoder)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLAC_API\fP \fBFLAC__bool\fP FLAC__stream_encoder_disable_constant_subframes (\fBFLAC__StreamEncoder\fP * encoder, \fBFLAC__bool\fP value)"

.PP
Definition at line 1900 of file stream_encoder\&.c\&.
.SS "\fBFLAC_API\fP \fBFLAC__bool\fP FLAC__stream_encoder_disable_fixed_subframes (\fBFLAC__StreamEncoder\fP * encoder, \fBFLAC__bool\fP value)"

.PP
Definition at line 1911 of file stream_encoder\&.c\&.
.SS "\fBFLAC_API\fP \fBFLAC__bool\fP FLAC__stream_encoder_disable_verbatim_subframes (\fBFLAC__StreamEncoder\fP * encoder, \fBFLAC__bool\fP value)"

.PP
Definition at line 1922 of file stream_encoder\&.c\&.
.SS "\fBFLAC_API\fP \fBFLAC__bool\fP FLAC__stream_encoder_get_do_md5 (\fBconst\fP \fBFLAC__StreamEncoder\fP * encoder)"

.PP
Definition at line 1998 of file stream_encoder\&.c\&.
.SS "\fBFLAC_API\fP \fBFLAC__bool\fP FLAC__stream_encoder_set_do_md5 (\fBFLAC__StreamEncoder\fP * encoder, \fBFLAC__bool\fP value)"

.PP
Definition at line 1531 of file stream_encoder\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
