.TH "private_state" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
private_state \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codec_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenvelope_lookup\fP * \fBve\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow\fP [2]"
.br
.ti -1c
.RI "\fBvorbis_look_transform\fP ** \fBtransform\fP [2]"
.br
.ti -1c
.RI "\fBdrft_lookup\fP \fBfft_look\fP [2]"
.br
.ti -1c
.RI "\fBint\fP \fBmodebits\fP"
.br
.ti -1c
.RI "\fBvorbis_look_floor\fP ** \fBflr\fP"
.br
.ti -1c
.RI "\fBvorbis_look_residue\fP ** \fBresidue\fP"
.br
.ti -1c
.RI "\fBvorbis_look_psy\fP * \fBpsy\fP"
.br
.ti -1c
.RI "\fBvorbis_look_psy_global\fP * \fBpsy_g_look\fP"
.br
.ti -1c
.RI "unsigned char * \fBheader\fP"
.br
.ti -1c
.RI "unsigned char * \fBheader1\fP"
.br
.ti -1c
.RI "unsigned char * \fBheader2\fP"
.br
.ti -1c
.RI "\fBbitrate_manager_state\fP \fBbms\fP"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBsample_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file codec_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbitrate_manager_state\fP private_state::bms"

.PP
Definition at line 82 of file codec_internal\&.h\&.
.SS "\fBdrft_lookup\fP private_state::fft_look[2]"

.PP
Definition at line 66 of file codec_internal\&.h\&.
.SS "\fBvorbis_look_floor\fP** private_state::flr"

.PP
Definition at line 69 of file codec_internal\&.h\&.
.SS "unsigned char* private_state::header"

.PP
Definition at line 78 of file codec_internal\&.h\&.
.SS "unsigned char* private_state::header1"

.PP
Definition at line 79 of file codec_internal\&.h\&.
.SS "unsigned char* private_state::header2"

.PP
Definition at line 80 of file codec_internal\&.h\&.
.SS "\fBint\fP private_state::modebits"

.PP
Definition at line 68 of file codec_internal\&.h\&.
.SS "\fBvorbis_look_psy\fP* private_state::psy"

.PP
Definition at line 71 of file codec_internal\&.h\&.
.SS "\fBvorbis_look_psy_global\fP* private_state::psy_g_look"

.PP
Definition at line 72 of file codec_internal\&.h\&.
.SS "\fBvorbis_look_residue\fP** private_state::residue"

.PP
Definition at line 70 of file codec_internal\&.h\&.
.SS "\fBogg_int64_t\fP private_state::sample_count"

.PP
Definition at line 84 of file codec_internal\&.h\&.
.SS "\fBvorbis_look_transform\fP** private_state::transform[2]"

.PP
Definition at line 65 of file codec_internal\&.h\&.
.SS "\fBenvelope_lookup\fP* private_state::ve"

.PP
Definition at line 63 of file codec_internal\&.h\&.
.SS "\fBint\fP private_state::window[2]"

.PP
Definition at line 64 of file codec_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
