.TH "C:/_dev/OpenU/Audacity/audacity/src/Profiler.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/Profiler.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Profiler\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
