.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/twolame/libtwolame/psycho_1_freqtable.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/twolame/libtwolame/psycho_1_freqtable.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaskingThreshold\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_FREQTABLE_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _FREQTABLE_H"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
