.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/twolame/libtwolame/psycho_1.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/twolame/libtwolame/psycho_1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'twolame\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'mem\&.h'\fP
.br
\fC#include 'fft\&.h'\fP
.br
\fC#include 'psycho_1\&.h'\fP
.br
\fC#include 'psycho_1_critband\&.h'\fP
.br
\fC#include 'psycho_1_freqtable\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCF\fP   1073741824           /* pow(10, 0\&.1*\fBPOWERNORM\fP) */"
.br
.ti -1c
.RI "#define \fBDBM\fP   1E\-20              /* pow(10\&.0, 0\&.1*DBMIN */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBpsycho_1\fP (\fBtwolame_options\fP *glopts, short \fBbuffer\fP[2][1152], \fBFLOAT\fP \fBscale\fP[2][\fBSBLIMIT\fP], \fBFLOAT\fP ltmin[2][\fBSBLIMIT\fP])"
.br
.ti -1c
.RI "\fBvoid\fP \fBpsycho_1_deinit\fP (\fBpsycho_1_mem\fP **mem)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CF   1073741824           /* pow(10, 0\&.1*\fBPOWERNORM\fP) */"

.SS "#define DBM   1E\-20              /* pow(10\&.0, 0\&.1*DBMIN */"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP psycho_1 (\fBtwolame_options\fP * glopts, short buffer[2][1152], \fBFLOAT\fP scale[2][SBLIMIT], \fBFLOAT\fP ltmin[2][SBLIMIT])"

.PP
Definition at line 559 of file psycho_1\&.c\&.
.SS "\fBvoid\fP psycho_1_deinit (\fBpsycho_1_mem\fP ** mem)"

.PP
Definition at line 636 of file psycho_1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
