.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/porttime/ptmacosx_cf.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmidi/porttime/ptmacosx_cf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <CoreFoundation/CoreFoundation\&.h>\fP
.br
\fC#import <mach/mach\&.h>\fP
.br
\fC#import <mach/mach_error\&.h>\fP
.br
\fC#import <mach/mach_time\&.h>\fP
.br
\fC#import <mach/clock\&.h>\fP
.br
\fC#include 'porttime\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPtThreadParams\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTHREAD_IMPORTANCE\fP   30"
.br
.ti -1c
.RI "#define \fBLONG_TIME\fP   1000000000\&.0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBPt_CFTimerCallback\fP (CFRunLoopTimerRef timer, \fBvoid\fP *\fBinfo\fP)"
.br
.ti -1c
.RI "\fBPtError\fP \fBPt_Start\fP (\fBint\fP resolution, \fBPtCallback\fP *callback, \fBvoid\fP *\fBuserData\fP)"
.br
.ti -1c
.RI "\fBPtError\fP \fBPt_Stop\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBPt_Started\fP ()"
.br
.ti -1c
.RI "\fBPtTimestamp\fP \fBPt_Time\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBPt_Sleep\fP (\fBint32_t\fP duration)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LONG_TIME   1000000000\&.0"

.PP
Definition at line 16 of file ptmacosx_cf\&.c\&.
.SS "#define THREAD_IMPORTANCE   30"

.PP
Definition at line 15 of file ptmacosx_cf\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP Pt_CFTimerCallback (CFRunLoopTimerRef timer, \fBvoid\fP * info)"

.PP
Definition at line 29 of file ptmacosx_cf\&.c\&.
.SS "\fBvoid\fP Pt_Sleep (\fBint32_t\fP duration)"

.PP
Definition at line 137 of file ptmacosx_cf\&.c\&.
.SS "\fBPtError\fP Pt_Start (\fBint\fP resolution, \fBPtCallback\fP * callback, \fBvoid\fP * userData)"

.PP
Definition at line 89 of file ptmacosx_cf\&.c\&.
.SS "\fBint\fP Pt_Started ()"

.PP
Definition at line 124 of file ptmacosx_cf\&.c\&.
.SS "\fBPtError\fP Pt_Stop ()"

.PP
Definition at line 114 of file ptmacosx_cf\&.c\&.
.SS "\fBPtTimestamp\fP Pt_Time ()"

.PP
Definition at line 130 of file ptmacosx_cf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
