.TH "pvshell_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pvshell_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pvshell\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBf\fP"
.br
.ti -1c
.RI "long \fBf_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBf_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBg\fP"
.br
.ti -1c
.RI "long \fBg_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBg_ptr\fP"
.br
.ti -1c
.RI "long \fBflags\fP"
.br
.ti -1c
.RI "double \fBstate\fP [\fBPVSHELL_STATE_MAX\fP]"
.br
.ti -1c
.RI "\fBh_fn_type\fP \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file pvshell\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsound_type\fP pvshell_struct::f"

.PP
Definition at line 33 of file pvshell\&.h\&.
.SS "long pvshell_struct::f_cnt"

.PP
Definition at line 34 of file pvshell\&.h\&.
.SS "\fBsample_block_values_type\fP pvshell_struct::f_ptr"

.PP
Definition at line 35 of file pvshell\&.h\&.
.SS "long pvshell_struct::flags"

.PP
Definition at line 41 of file pvshell\&.h\&.
.SS "\fBsound_type\fP pvshell_struct::g"

.PP
Definition at line 37 of file pvshell\&.h\&.
.SS "long pvshell_struct::g_cnt"

.PP
Definition at line 38 of file pvshell\&.h\&.
.SS "\fBsample_block_values_type\fP pvshell_struct::g_ptr"

.PP
Definition at line 39 of file pvshell\&.h\&.
.SS "\fBh_fn_type\fP pvshell_struct::h"

.PP
Definition at line 47 of file pvshell\&.h\&.
.SS "double pvshell_struct::state[\fBPVSHELL_STATE_MAX\fP]"

.PP
Definition at line 44 of file pvshell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
