.TH "pvshell_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pvshell_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "\fBpvshell_node\fP \fBpvshell\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file pvshell\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBboolean\fP pvshell_susp_struct::logically_stopped"

.PP
Definition at line 37 of file pvshell\&.c\&.
.SS "\fBpvshell_node\fP pvshell_susp_struct::pvshell"

.PP
Definition at line 40 of file pvshell\&.c\&.
.SS "\fBboolean\fP pvshell_susp_struct::started"

.PP
Definition at line 38 of file pvshell\&.c\&.
.SS "\fBsnd_susp_node\fP pvshell_susp_struct::susp"

.PP
Definition at line 35 of file pvshell\&.c\&.
.SS "long pvshell_susp_struct::terminate_cnt"

.PP
Definition at line 36 of file pvshell\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
