.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portmixer/src/px_mixer.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portmixer/src/px_mixer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'portaudio\&.h'\fP
.br
\fC#include 'portmixer\&.h'\fP
.br
\fC#include 'px_mixer\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPxMixer\fP * \fBPx_OpenMixer\fP (\fBPaStream\fP *pa_stream, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_CloseMixer\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_GetNumMixers\fP (\fBPxMixer\fP *mixer)"
.br
.RI "\fIPx_GetNumMixers returns the number of mixers which could be used with the given PortAudio device\&. \fP"
.ti -1c
.RI "\fBconst\fP char * \fBPx_GetMixerName\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBPxVolume\fP \fBPx_GetMasterVolume\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetMasterVolume\fP (\fBPxMixer\fP *mixer, \fBPxVolume\fP volume)"
.br
.ti -1c
.RI "\fBPxVolume\fP \fBPx_GetPCMOutputVolume\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetPCMOutputVolume\fP (\fBPxMixer\fP *mixer, \fBPxVolume\fP volume)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_SupportsPCMOutputVolume\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_GetNumOutputVolumes\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBPx_GetOutputVolumeName\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBPxVolume\fP \fBPx_GetOutputVolume\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetOutputVolume\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP, \fBPxVolume\fP volume)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_GetNumInputSources\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBconst\fP char * \fBPx_GetInputSourceName\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_GetCurrentInputSource\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetCurrentInputSource\fP (\fBPxMixer\fP *mixer, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBPxVolume\fP \fBPx_GetInputVolume\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetInputVolume\fP (\fBPxMixer\fP *mixer, \fBPxVolume\fP volume)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_SupportsOutputBalance\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBPxBalance\fP \fBPx_GetOutputBalance\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetOutputBalance\fP (\fBPxMixer\fP *mixer, \fBPxBalance\fP balance)"
.br
.ti -1c
.RI "\fBint\fP \fBPx_SupportsPlaythrough\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBPxVolume\fP \fBPx_GetPlaythrough\fP (\fBPxMixer\fP *mixer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPx_SetPlaythrough\fP (\fBPxMixer\fP *mixer, \fBPxVolume\fP volume)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP Px_CloseMixer (\fBPxMixer\fP * mixer)"

.PP
Definition at line 187 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_GetCurrentInputSource (\fBPxMixer\fP * mixer)"

.PP
Definition at line 356 of file px_mixer\&.c\&.
.SS "\fBconst\fP char* Px_GetInputSourceName (\fBPxMixer\fP * mixer, \fBint\fP i)"

.PP
Definition at line 347 of file px_mixer\&.c\&.
.SS "\fBPxVolume\fP Px_GetInputVolume (\fBPxMixer\fP * mixer)"

.PP
Definition at line 380 of file px_mixer\&.c\&.
.SS "\fBPxVolume\fP Px_GetMasterVolume (\fBPxMixer\fP * mixer)"

.PP
Definition at line 235 of file px_mixer\&.c\&.
.SS "\fBconst\fP char* Px_GetMixerName (\fBPxMixer\fP * mixer, \fBint\fP i)"

.PP
Definition at line 217 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_GetNumInputSources (\fBPxMixer\fP * mixer)"

.PP
Definition at line 338 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_GetNumMixers (\fBPxMixer\fP * mixer)"

.PP
Px_GetNumMixers returns the number of mixers which could be used with the given PortAudio device\&. On most systems, there will be only one mixer for each device; however there may be multiple mixers for each device, or possibly multiple mixers which are independent of any particular PortAudio device\&. 
.PP
Definition at line 203 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_GetNumOutputVolumes (\fBPxMixer\fP * mixer)"

.PP
Definition at line 292 of file px_mixer\&.c\&.
.SS "\fBPxBalance\fP Px_GetOutputBalance (\fBPxMixer\fP * mixer)"

.PP
Definition at line 413 of file px_mixer\&.c\&.
.SS "\fBPxVolume\fP Px_GetOutputVolume (\fBPxMixer\fP * mixer, \fBint\fP i)"

.PP
Definition at line 314 of file px_mixer\&.c\&.
.SS "\fBconst\fP char* Px_GetOutputVolumeName (\fBPxMixer\fP * mixer, \fBint\fP i)"

.PP
Definition at line 301 of file px_mixer\&.c\&.
.SS "\fBPxVolume\fP Px_GetPCMOutputVolume (\fBPxMixer\fP * mixer)"

.PP
Definition at line 259 of file px_mixer\&.c\&.
.SS "\fBPxVolume\fP Px_GetPlaythrough (\fBPxMixer\fP * mixer)"

.PP
Definition at line 446 of file px_mixer\&.c\&.
.SS "\fBPxMixer\fP* Px_OpenMixer (\fBPaStream\fP * pa_stream, \fBint\fP i)"

.PP
Definition at line 112 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetCurrentInputSource (\fBPxMixer\fP * mixer, \fBint\fP i)"

.PP
Definition at line 365 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetInputVolume (\fBPxMixer\fP * mixer, \fBPxVolume\fP volume)"

.PP
Definition at line 389 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetMasterVolume (\fBPxMixer\fP * mixer, \fBPxVolume\fP volume)"

.PP
Definition at line 244 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetOutputBalance (\fBPxMixer\fP * mixer, \fBPxBalance\fP balance)"

.PP
Definition at line 422 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetOutputVolume (\fBPxMixer\fP * mixer, \fBint\fP i, \fBPxVolume\fP volume)"

.PP
Definition at line 323 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetPCMOutputVolume (\fBPxMixer\fP * mixer, \fBPxVolume\fP volume)"

.PP
Definition at line 268 of file px_mixer\&.c\&.
.SS "\fBvoid\fP Px_SetPlaythrough (\fBPxMixer\fP * mixer, \fBPxVolume\fP volume)"

.PP
Definition at line 455 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_SupportsOutputBalance (\fBPxMixer\fP * mixer)"

.PP
Definition at line 404 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_SupportsPCMOutputVolume (\fBPxMixer\fP * mixer)"

.PP
Definition at line 279 of file px_mixer\&.c\&.
.SS "\fBint\fP Px_SupportsPlaythrough (\fBPxMixer\fP * mixer)"

.PP
Definition at line 437 of file px_mixer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
