.TH "PxInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PxInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <px_win_common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBexample\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumMixers\fP"
.br
.ti -1c
.RI "char * \fBmixers\fP"
.br
.ti -1c
.RI "\fBPxDev\fP \fBplayback\fP"
.br
.ti -1c
.RI "\fBPxDev\fP \fBcapture\fP"
.br
.ti -1c
.RI "AudioDeviceID \fBinput\fP"
.br
.ti -1c
.RI "AudioDeviceID \fBoutput\fP"
.br
.ti -1c
.RI "UInt32 * \fBsrcids\fP"
.br
.ti -1c
.RI "char ** \fBsrcnames\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumsrcs\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmixerIndexes\fP [\fBMIXER_COUNT_MAX\fP]"
.br
.ti -1c
.RI "char \fBmixers\fP [\fBMIXER_COUNT_MAX\fP][sizeof(\fBMIXER_NAME_BASE\fP)+1]"
.br
.ti -1c
.RI "HMIXEROBJ \fBhInputMixer\fP"
.br
.ti -1c
.RI "char * \fBinName\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumInputs\fP"
.br
.ti -1c
.RI "\fBPxCtrl\fP * \fBsrc\fP"
.br
.ti -1c
.RI "HMIXEROBJ \fBhOutputMixer\fP"
.br
.ti -1c
.RI "char * \fBoutName\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnumOutputs\fP"
.br
.ti -1c
.RI "\fBPxCtrl\fP * \fBdst\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBmuxID\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBspeakerID\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBwaveID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file px_example_api\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPxDev\fP PxInfo::capture"

.PP
Definition at line 83 of file px_linux_alsa\&.c\&.
.SS "\fBPxCtrl\fP* PxInfo::dst"

.PP
Definition at line 63 of file px_win_common\&.h\&.
.SS "\fBint\fP PxInfo::example"

.PP
Definition at line 45 of file px_example_api\&.c\&.
.SS "HMIXEROBJ PxInfo::hInputMixer"

.PP
Definition at line 55 of file px_win_common\&.h\&.
.SS "HMIXEROBJ PxInfo::hOutputMixer"

.PP
Definition at line 60 of file px_win_common\&.h\&.
.SS "char* PxInfo::inName"

.PP
Definition at line 56 of file px_win_common\&.h\&.
.SS "AudioDeviceID PxInfo::input"

.PP
Definition at line 59 of file px_mac_coreaudio\&.c\&.
.SS "\fBint\fP PxInfo::mixerIndexes[\fBMIXER_COUNT_MAX\fP]"

.PP
Definition at line 87 of file px_unix_oss\&.c\&.
.SS "char* PxInfo::mixers"

.PP
Definition at line 80 of file px_linux_alsa\&.c\&.
.SS "char PxInfo::mixers[\fBMIXER_COUNT_MAX\fP][sizeof(\fBMIXER_NAME_BASE\fP)+1]"

.PP
Definition at line 88 of file px_unix_oss\&.c\&.
.SS "\fBDWORD\fP PxInfo::muxID"

.PP
Definition at line 65 of file px_win_common\&.h\&.
.SS "\fBint\fP PxInfo::numInputs"

.PP
Definition at line 57 of file px_win_common\&.h\&.
.SS "\fBint\fP PxInfo::numMixers"

.PP
Definition at line 79 of file px_linux_alsa\&.c\&.
.SS "\fBint\fP PxInfo::numOutputs"

.PP
Definition at line 62 of file px_win_common\&.h\&.
.SS "\fBint\fP PxInfo::numsrcs"

.PP
Definition at line 63 of file px_mac_coreaudio\&.c\&.
.SS "char* PxInfo::outName"

.PP
Definition at line 61 of file px_win_common\&.h\&.
.SS "AudioDeviceID PxInfo::output"

.PP
Definition at line 60 of file px_mac_coreaudio\&.c\&.
.SS "\fBPxDev\fP PxInfo::playback"

.PP
Definition at line 82 of file px_linux_alsa\&.c\&.
.SS "\fBDWORD\fP PxInfo::speakerID"

.PP
Definition at line 66 of file px_win_common\&.h\&.
.SS "\fBPxCtrl\fP* PxInfo::src"

.PP
Definition at line 58 of file px_win_common\&.h\&.
.SS "UInt32* PxInfo::srcids"

.PP
Definition at line 61 of file px_mac_coreaudio\&.c\&.
.SS "char** PxInfo::srcnames"

.PP
Definition at line 62 of file px_mac_coreaudio\&.c\&.
.SS "\fBDWORD\fP PxInfo::waveID"

.PP
Definition at line 67 of file px_win_common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
