.TH "quant_meta" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quant_meta \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vqgen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmin\fP"
.br
.ti -1c
.RI "long \fBdelta\fP"
.br
.ti -1c
.RI "\fBint\fP \fBquant\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsequencep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file vqgen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long quant_meta::delta"

.PP
Definition at line 52 of file vqgen\&.h\&.
.SS "long quant_meta::min"

.PP
Definition at line 51 of file vqgen\&.h\&.
.SS "\fBint\fP quant_meta::quant"

.PP
Definition at line 53 of file vqgen\&.h\&.
.SS "\fBint\fP quant_meta::sequencep"

.PP
Definition at line 54 of file vqgen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
