.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/rdft.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/rdft.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBORDERED_CONVOLVE\fP (\fBint\fP n, \fBvoid\fP *not_used, \fBDFT_FLOAT\fP *\fBa\fP, \fBconst\fP \fBDFT_FLOAT\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBORDERED_PARTIAL_CONVOLVE\fP (\fBint\fP n, \fBDFT_FLOAT\fP *\fBa\fP, \fBconst\fP \fBDFT_FLOAT\fP *\fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP ORDERED_CONVOLVE (\fBint\fP n, \fBvoid\fP * not_used, \fBDFT_FLOAT\fP * a, \fBconst\fP \fBDFT_FLOAT\fP * b)"

.PP
Definition at line 4 of file rdft\&.h\&.
.SS "\fBvoid\fP ORDERED_PARTIAL_CONVOLVE (\fBint\fP n, \fBDFT_FLOAT\fP * a, \fBconst\fP \fBDFT_FLOAT\fP * b)"

.PP
Definition at line 17 of file rdft\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
