.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/recip.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/recip.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'recip\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrecip_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBrecip_susp_struct\fP \fBrecip_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBrecip_susp_struct\fP * \fBrecip_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBrecip_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrecip_n_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrecip_toss_fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrecip_mark\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrecip_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_recip\fP (\fBsound_type\fP s1)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_recip\fP (\fBsound_type\fP s1)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBrecip_susp_struct\fP  \fBrecip_susp_node\fP"

.SS "typedef struct \fBrecip_susp_struct\fP * \fBrecip_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP recip_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 146 of file recip\&.c\&.
.SS "\fBvoid\fP recip_mark (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 139 of file recip\&.c\&.
.SS "\fBvoid\fP recip_n_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 27 of file recip\&.c\&.
.SS "\fBvoid\fP recip_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 154 of file recip\&.c\&.
.SS "\fBvoid\fP recip_toss_fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 118 of file recip\&.c\&.
.SS "\fBsound_type\fP snd_make_recip (\fBsound_type\fP s1)"

.PP
Definition at line 163 of file recip\&.c\&.
.SS "\fBsound_type\fP snd_recip (\fBsound_type\fP s1)"

.PP
Definition at line 201 of file recip\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
