.TH "RecordingPrefs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecordingPrefs \- A \fBPrefsPanel\fP used to select recording options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RecordingPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecordingPrefs\fP (wxWindow *parent)"
.br
.ti -1c
.RI "virtual \fB~RecordingPrefs\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBApply\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBPrefsPanel\fP used to select recording options\&. 

Presents interface for user to update the various recording options like playthrough, latency correction, and others\&. 
.PP
Definition at line 24 of file RecordingPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RecordingPrefs::RecordingPrefs (wxWindow * parent)"

.PP
Definition at line 45 of file RecordingPrefs\&.cpp\&.
.SS "RecordingPrefs::~RecordingPrefs ()\fC [virtual]\fP"

.PP
Definition at line 53 of file RecordingPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP RecordingPrefs::Apply ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanel\fP\&.
.PP
Definition at line 215 of file RecordingPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
