.TH "ReedTable" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReedTable \- STK reed table class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReedTable\&.h>\fP
.SH "Detailed Description"
.PP 
STK reed table class\&. 

This class implements a simple one breakpoint, non-linear reed function, as described by Smith (1986)\&. This function is based on a memoryless non-linear spring model of the reed (the reed mass is ignored) which saturates when the reed collides with the mouthpiece facing\&.
.PP
See McIntyre, Schumacher, & Woodhouse (1983), Smith (1986), Hirschman, Cook, Scavone, and others for more information\&.
.PP
by Perry R\&. Cook and Gary P\&. Scavone, 1995 - 2005\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
