.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/Registrar.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/Registrar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/wx\&.h>\fP
.br
\fC#include 'Registrar\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISPATCH\fP(Name)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBRegistrarDispatch\fP (\fBt_RegistrarDispatchType\fP Type)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRegistrar\fP * \fBpRegistrar\fP = \fBNULL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DISPATCH(Name)"
\fBValue:\fP
.PP
.nf
extern int Name##Dispatch( Registrar & R, t_RegistrarDispatchType Type );\
   Name##Dispatch( *pRegistrar, Type )
.fi
.PP
Definition at line 30 of file Registrar\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP RegistrarDispatch (\fBt_RegistrarDispatchType\fP Type)"

.PP
Definition at line 35 of file Registrar\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBRegistrar\fP* pRegistrar = \fBNULL\fP"

.PP
Definition at line 24 of file Registrar\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
