.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/Registrar.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/Registrar.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegistrar\fP"
.br
.RI "\fI\fBRegistrar\fP is a class that other classes register resources of various kinds with\&. It makes a system that is much more amenable to plugging in of new resources\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBt_RegistrarDispatchType\fP { \fBRegResource\fP, \fBRegArtist\fP, \fBRegDataType\fP, \fBRegCommand\fP, \fBRegMenuItem\fP, \fBRegLast\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBRegistrarDispatch\fP (\fBt_RegistrarDispatchType\fP Type)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBt_RegistrarDispatchType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRegResource \fP\fP
.TP
\fB\fIRegArtist \fP\fP
.TP
\fB\fIRegDataType \fP\fP
.TP
\fB\fIRegCommand \fP\fP
.TP
\fB\fIRegMenuItem \fP\fP
.TP
\fB\fIRegLast \fP\fP
.PP
Definition at line 16 of file Registrar\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP RegistrarDispatch (\fBt_RegistrarDispatchType\fP Type)"

.PP
Definition at line 35 of file Registrar\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
