.TH "Registrar" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Registrar \- \fBRegistrar\fP is a class that other classes register resources of various kinds with\&. It makes a system that is much more amenable to plugging in of new resources\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Registrar\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBStart\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBFinish\fP ()"
.br
.ti -1c
.RI "static \fBvoid\fP \fBShowNewPanel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP(* \fBpShowFn\fP )(\fBvoid\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRegistrar\fP is a class that other classes register resources of various kinds with\&. It makes a system that is much more amenable to plugging in of new resources\&. 
.PP
Definition at line 26 of file Registrar\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Registrar::Finish ()\fC [static]\fP"

.PP
Definition at line 65 of file Registrar\&.cpp\&.
.SS "\fBvoid\fP Registrar::ShowNewPanel ()\fC [static]\fP"

.PP
Definition at line 72 of file Registrar\&.cpp\&.
.SS "\fBvoid\fP Registrar::Start ()\fC [static]\fP"

.PP
Definition at line 51 of file Registrar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP(* Registrar::pShowFn) (\fBvoid\fP)"

.PP
Definition at line 39 of file Registrar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
