.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/Repeat.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/Repeat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/event\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include 'Effect\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffectRepeat\fP"
.br
.RI "\fIAn \fBEffect\fP that repeats audio several times over\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREPEAT_PLUGIN_SYMBOL\fP   \fBXO\fP('Repeat')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REPEAT_PLUGIN_SYMBOL   \fBXO\fP('Repeat')"

.PP
Definition at line 23 of file Repeat\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
