.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/replaygain_synthesis/replaygain_synthesis.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/share/replaygain_synthesis/replaygain_synthesis.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'share/replaygain_synthesis\&.h'\fP
.br
\fC#include 'FLAC/assert\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLAC__I64L\fP(x)   x##LL"
.br
.ti -1c
.RI "#define \fBROUND64\fP(x)     ( \fBdoubletmp\&.d\fP = (x) + \fBd\fP\->Add + (\fBFLAC__int64\fP)\fBFLAC__I64L\fP(0x001FFFFD80000000), doubletmp\&.i \- (FLAC__int64)FLAC__I64L(0x433FFFFD80000000) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBFLAC__replaygain_synthesis__init_dither_context\fP (\fBDitherContext\fP *\fBd\fP, \fBint\fP \fBbits\fP, \fBint\fP shapingtype)"
.br
.ti -1c
.RI "size_t \fBFLAC__replaygain_synthesis__apply_gain\fP (\fBFLAC__byte\fP *\fBdata_out\fP, \fBFLAC__bool\fP little_endian_data_out, \fBFLAC__bool\fP unsigned_data_out, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP input[], unsigned wide_samples, unsigned channels, \fBconst\fP unsigned source_bps, \fBconst\fP unsigned target_bps, \fBconst\fP double \fBscale\fP, \fBconst\fP \fBFLAC__bool\fP hard_limit, \fBFLAC__bool\fP do_dithering, \fBDitherContext\fP *dither_context)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FLAC__I64L(x)   x##LL"

.PP
Definition at line 47 of file replaygain_synthesis\&.c\&.
.SS "#define ROUND64(x)   ( \fBdoubletmp\&.d\fP = (x) + \fBd\fP\->Add + (\fBFLAC__int64\fP)\fBFLAC__I64L\fP(0x001FFFFD80000000), doubletmp\&.i \- (FLAC__int64)FLAC__I64L(0x433FFFFD80000000) )"

.SH "Function Documentation"
.PP 
.SS "size_t FLAC__replaygain_synthesis__apply_gain (\fBFLAC__byte\fP * data_out, \fBFLAC__bool\fP little_endian_data_out, \fBFLAC__bool\fP unsigned_data_out, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP input[], unsigned wide_samples, unsigned channels, \fBconst\fP unsigned source_bps, \fBconst\fP unsigned target_bps, \fBconst\fP double scale, \fBconst\fP \fBFLAC__bool\fP hard_limit, \fBFLAC__bool\fP do_dithering, \fBDitherContext\fP * dither_context)"

.PP
Definition at line 295 of file replaygain_synthesis\&.c\&.
.SS "\fBvoid\fP FLAC__replaygain_synthesis__init_dither_context (\fBDitherContext\fP * d, \fBint\fP bits, \fBint\fP shapingtype)"

.PP
Definition at line 202 of file replaygain_synthesis\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
