.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/modes/residue_8.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/modes/residue_8.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'backends\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
