.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/resonvv.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/resonvv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_resonvv\fP (\fBsound_type\fP s1, \fBsound_type\fP hz1, \fBsound_type\fP bw, \fBint\fP normalization)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_resonvv\fP (\fBsound_type\fP s1, \fBsound_type\fP hz1, \fBsound_type\fP bw, \fBint\fP normalization)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_make_resonvv (\fBsound_type\fP s1, \fBsound_type\fP hz1, \fBsound_type\fP bw, \fBint\fP normalization)"

.PP
Definition at line 1660 of file resonvv\&.c\&.
.SS "\fBsound_type\fP snd_resonvv (\fBsound_type\fP s1, \fBsound_type\fP hz1, \fBsound_type\fP bw, \fBint\fP normalization)"

.PP
Definition at line 1768 of file resonvv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
