.TH "resoncv_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resoncv_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs1\fP"
.br
.ti -1c
.RI "long \fBs1_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs1_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBbw\fP"
.br
.ti -1c
.RI "long \fBbw_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBbw_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBbw_x1_sample\fP"
.br
.ti -1c
.RI "double \fBbw_pHaSe\fP"
.br
.ti -1c
.RI "double \fBbw_pHaSe_iNcR\fP"
.br
.ti -1c
.RI "double \fBoutput_per_bw\fP"
.br
.ti -1c
.RI "long \fBbw_n\fP"
.br
.ti -1c
.RI "double \fBscale1\fP"
.br
.ti -1c
.RI "double \fBc3co\fP"
.br
.ti -1c
.RI "double \fBcoshz\fP"
.br
.ti -1c
.RI "double \fBc2\fP"
.br
.ti -1c
.RI "double \fBc1\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnormalization\fP"
.br
.ti -1c
.RI "double \fBy1\fP"
.br
.ti -1c
.RI "double \fBy2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file resoncv\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsound_type\fP resoncv_susp_struct::bw"

.PP
Definition at line 23 of file resoncv\&.c\&.
.SS "long resoncv_susp_struct::bw_cnt"

.PP
Definition at line 24 of file resoncv\&.c\&.
.SS "long resoncv_susp_struct::bw_n"

.PP
Definition at line 34 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::bw_pHaSe"

.PP
Definition at line 29 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::bw_pHaSe_iNcR"

.PP
Definition at line 30 of file resoncv\&.c\&.
.SS "\fBsample_block_values_type\fP resoncv_susp_struct::bw_ptr"

.PP
Definition at line 25 of file resoncv\&.c\&.
.SS "\fBsample_type\fP resoncv_susp_struct::bw_x1_sample"

.PP
Definition at line 28 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::c1"

.PP
Definition at line 40 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::c2"

.PP
Definition at line 39 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::c3co"

.PP
Definition at line 37 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::coshz"

.PP
Definition at line 38 of file resoncv\&.c\&.
.SS "\fBboolean\fP resoncv_susp_struct::logically_stopped"

.PP
Definition at line 19 of file resoncv\&.c\&.
.SS "\fBint\fP resoncv_susp_struct::normalization"

.PP
Definition at line 41 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::output_per_bw"

.PP
Definition at line 33 of file resoncv\&.c\&.
.SS "\fBsound_type\fP resoncv_susp_struct::s1"

.PP
Definition at line 20 of file resoncv\&.c\&.
.SS "long resoncv_susp_struct::s1_cnt"

.PP
Definition at line 21 of file resoncv\&.c\&.
.SS "\fBsample_block_values_type\fP resoncv_susp_struct::s1_ptr"

.PP
Definition at line 22 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::scale1"

.PP
Definition at line 36 of file resoncv\&.c\&.
.SS "\fBboolean\fP resoncv_susp_struct::started"

.PP
Definition at line 17 of file resoncv\&.c\&.
.SS "\fBsnd_susp_node\fP resoncv_susp_struct::susp"

.PP
Definition at line 16 of file resoncv\&.c\&.
.SS "long resoncv_susp_struct::terminate_cnt"

.PP
Definition at line 18 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::y1"

.PP
Definition at line 42 of file resoncv\&.c\&.
.SS "double resoncv_susp_struct::y2"

.PP
Definition at line 43 of file resoncv\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
