.TH "C:/_dev/OpenU/Audacity/audacity/src/commands/ResponseQueue.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/commands/ResponseQueue.cpp \- Contains definitions for the \fBResponseQueue\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ResponseQueue\&.h'\fP
.br
\fC#include <queue>\fP
.br
\fC#include <string>\fP
.br
\fC#include <wx/thread\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Contains definitions for the \fBResponseQueue\fP class\&. 


.PP
Definition in file \fBResponseQueue\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
