.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/ffts/Matlab-testing/rfft2dTestML.m" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/ffts/Matlab-testing/rfft2dTestML.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcd\fP (\fBpname\fP)"
.br
.ti -1c
.RI "\fBfclose\fP (\fBfidout\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "program to \fBtest\fP \fBreal\fP \fBfft\fP \fBlet\fP user select file then open \fBit\fP [fname, \fBpname\fP] = uigetfile('*\&.dr2', 'select conv file')"
.br
.ti -1c
.RI "\fBfidout\fP =fopen(fname,'r')"
.br
.ti -1c
.RI "read header \fBinfo\fP \fBN\fP =fread(\fBfidout\fP,1,'long')"
.br
.ti -1c
.RI "\fBM\fP =fread(\fBfidout\fP,1,'long')"
.br
.ti -1c
.RI "read \fBin\fP \fBdata\fP \fBstatus\fP =fseek(\fBfidout\fP,Nheader,'bof')"
.br
.ti -1c
.RI "\fBa\fP =fread(\fBfidout\fP,\fBN\fP*\fBM\fP,'float')"
.br
.ti -1c
.RI "\fBc\fP =fread(\fBfidout\fP,\fBN\fP*\fBM\fP,'float')"
.br
.ti -1c
.RI "\fBc2\fP =fft2(\fBa\fP)"
.br
.ti -1c
.RI "Remember Matlab is column major \fBorder\fP"
.br
.ti -1c
.RI "Remember Matlab is column major C is row major \fBorder\fP Matlab starts with index \fBof\fP"
.br
.ti -1c
.RI "Remember Matlab is column major C is row major \fBorder\fP Matlab starts with index \fBf\fP and \fBk\fP \fBstart\fP at check \fBthe\fP \fBreal\fP transforms \fBof\fP DC and Nyquest frequencies check \fBthe\fP four \fBreal\fP values \fBmaxerr\fP =abs(\fBreal\fP(\fBc\fP(1,1))\-\fBc2\fP(1,1))"
.br
.ti -1c
.RI "\fBf\fP = 0"
.br
.ti -1c
.RI "\fBk\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "cd (\fBpname\fP)"

.SS "fclose (\fBfidout\fP)"

.SH "Variable Documentation"
.PP 
.SS "a =fread(\fBfidout\fP,\fBN\fP*\fBM\fP,'float')"

.PP
Definition at line 13 of file rfft2dTestML\&.m\&.
.SS "c =fread(\fBfidout\fP,\fBN\fP*\fBM\fP,'float')"

.PP
Definition at line 15 of file rfft2dTestML\&.m\&.
.SS "c2 =fft2(\fBa\fP)"

.PP
Definition at line 20 of file rfft2dTestML\&.m\&.
.SS "\fBN\fP f = 0"

.PP
Definition at line 27 of file rfft2dTestML\&.m\&.
.SS "fidout =fopen(fname,'r')"

.PP
Definition at line 6 of file rfft2dTestML\&.m\&.
.SS "program to \fBtest\fP \fBreal\fP \fBfft\fP \fBlet\fP user select file then open it[fname, \fBpname\fP] = uigetfile('*\&.dr2', 'select conv file')"

.PP
Definition at line 4 of file rfft2dTestML\&.m\&.
.SS "k"
\fBInitial value:\fP
.PP
.nf
=1 to M/2-1
maxerr=max(maxerr,max(abs(c(1,M/2+2:M)-c2(N/2+1,2:M/2))))
.fi
.PP
Definition at line 32 of file rfft2dTestML\&.m\&.
.SS "M =fread(\fBfidout\fP,1,'long')"

.PP
Definition at line 10 of file rfft2dTestML\&.m\&.
.SS "\fBN\fP \fBM\fP \fBk\fP check \fBthe\fP \fBrest\fP \fBof\fP \fBthe\fP pos wavenumbers \fBof\fP DC and Nyquest frequencies maxerr =abs(\fBreal\fP(\fBc\fP(1,1))\-\fBc2\fP(1,1))"

.PP
Definition at line 27 of file rfft2dTestML\&.m\&.
.SS "read header \fBinfo\fP N =fread(\fBfidout\fP,1,'long')"

.PP
Definition at line 9 of file rfft2dTestML\&.m\&.
.SS "Remember Matlab is column major C is row major \fBorder\fP Matlab starts with index of"

.PP
Definition at line 22 of file rfft2dTestML\&.m\&.
.SS "Remember Matlab is column major order"

.PP
Definition at line 22 of file rfft2dTestML\&.m\&.
.SS "read \fBin\fP \fBdata\fP status =fseek(\fBfidout\fP,Nheader,'bof')"

.PP
Definition at line 12 of file rfft2dTestML\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
