.TH "RingBuffer" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RingBuffer \- Holds streamed audio samples\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RingBuffer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingBuffer\fP (\fBsampleFormat\fP \fBformat\fP, \fBint\fP \fBsize\fP)"
.br
.ti -1c
.RI "\fB~RingBuffer\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBAvailForPut\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBPut\fP (\fBsamplePtr\fP \fBbuffer\fP, \fBsampleFormat\fP \fBformat\fP, \fBint\fP \fBsamples\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBAvailForGet\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBGet\fP (\fBsamplePtr\fP \fBbuffer\fP, \fBsampleFormat\fP \fBformat\fP, \fBint\fP \fBsamples\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBDiscard\fP (\fBint\fP \fBsamples\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds streamed audio samples\&. 

This class is thread-safe, assuming that there is only one thread writing, and one thread reading\&. If two threads both need to read, or both need to write, they need to lock this class from outside using their own mutex\&.
.PP
AvailForPut and AvailForGet may underestimate but will never overestimate\&. 
.PP
Definition at line 16 of file RingBuffer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RingBuffer::RingBuffer (\fBsampleFormat\fP format, \fBint\fP size)"

.PP
Definition at line 27 of file RingBuffer\&.cpp\&.
.SS "RingBuffer::~RingBuffer ()"

.PP
Definition at line 36 of file RingBuffer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP RingBuffer::AvailForGet ()"

.PP
Definition at line 94 of file RingBuffer\&.cpp\&.
.SS "\fBint\fP RingBuffer::AvailForPut ()"

.PP
Definition at line 49 of file RingBuffer\&.cpp\&.
.SS "\fBint\fP RingBuffer::Discard (\fBint\fP samples)"

.PP
Definition at line 131 of file RingBuffer\&.cpp\&.
.SS "\fBint\fP RingBuffer::Get (\fBsamplePtr\fP buffer, \fBsampleFormat\fP format, \fBint\fP samples)"

.PP
Definition at line 99 of file RingBuffer\&.cpp\&.
.SS "\fBint\fP RingBuffer::Put (\fBsamplePtr\fP buffer, \fBsampleFormat\fP format, \fBint\fP samples)"

.PP
Definition at line 54 of file RingBuffer\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
