.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/rint-clip.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/rint-clip.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDITHERING\fP   0"
.br
.ti -1c
.RI "#define \fBDITHER_VARS\fP"
.br
.ti -1c
.RI "#define \fBSEED_ARG\fP"
.br
.ti -1c
.RI "#define \fBSAVE_SEED\fP"
.br
.ti -1c
.RI "#define \fBCOPY_SEED\fP"
.br
.ti -1c
.RI "#define \fBCOPY_SEED1\fP"
.br
.ti -1c
.RI "#define \fBPASS_SEED1\fP"
.br
.ti -1c
.RI "#define \fBPASS_SEED\fP"
.br
.ti -1c
.RI "#define \fB_\fP   \fBd\fP = src[\fBi\fP] + \fBDITHERING\fP, dest[\fBi\fP++] = (RINT_T)(\fBd\fP > 0? \fBd\fP+\&.5 >= \fBN\fP? ++clips, \fBN\fP\-1 : \fBd\fP+\&.5 : \fBd\fP\-\&.5 <= \-\fBN\fP\-1? ++clips, \-N:d\-\&.5),"
.br
.ti -1c
.RI "#define \fB_\fP   \fBd\fP = src[\fBi\fP] + \fBDITHERING\fP, dest[stride * \fBi\fP++] = (RINT_T)(\fBd\fP > 0? \fBd\fP+\&.5 >= \fBN\fP? ++clips, \fBN\fP\-1 : \fBd\fP+\&.5 : \fBd\fP\-\&.5 <= \-\fBN\fP\-1? ++clips, \-N:d\-\&.5),"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _   \fBd\fP = src[\fBi\fP] + \fBDITHERING\fP, dest[\fBi\fP++] = (RINT_T)(\fBd\fP > 0? \fBd\fP+\&.5 >= \fBN\fP? ++clips, \fBN\fP\-1 : \fBd\fP+\&.5 : \fBd\fP\-\&.5 <= \-\fBN\fP\-1? ++clips, \-N:d\-\&.5),"

.SS "#define _   \fBd\fP = src[\fBi\fP] + \fBDITHERING\fP, dest[stride * \fBi\fP++] = (RINT_T)(\fBd\fP > 0? \fBd\fP+\&.5 >= \fBN\fP? ++clips, \fBN\fP\-1 : \fBd\fP+\&.5 : \fBd\fP\-\&.5 <= \-\fBN\fP\-1? ++clips, \-N:d\-\&.5),"

.SS "#define COPY_SEED"

.PP
Definition at line 22 of file rint\-clip\&.h\&.
.SS "#define COPY_SEED1"

.PP
Definition at line 23 of file rint\-clip\&.h\&.
.SS "#define DITHER_VARS"

.PP
Definition at line 19 of file rint\-clip\&.h\&.
.SS "#define DITHERING   0"

.PP
Definition at line 18 of file rint\-clip\&.h\&.
.SS "#define PASS_SEED"

.PP
Definition at line 25 of file rint\-clip\&.h\&.
.SS "#define PASS_SEED1"

.PP
Definition at line 24 of file rint\-clip\&.h\&.
.SS "#define SAVE_SEED"

.PP
Definition at line 21 of file rint\-clip\&.h\&.
.SS "#define SEED_ARG"

.PP
Definition at line 20 of file rint\-clip\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
