.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/ripemd.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/ripemd.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'attributes\&.h'\fP
.br
\fC#include 'version\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct AVRIPEMD * \fBav_ripemd_alloc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBav_ripemd_init\fP (struct AVRIPEMD *\fBcontext\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_ripemd_update\fP (struct AVRIPEMD *\fBcontext\fP, \fBconst\fP \fBuint8_t\fP *\fBdata\fP, unsigned \fBint\fP \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_ripemd_final\fP (struct AVRIPEMD *\fBcontext\fP, \fBuint8_t\fP *digest)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBint\fP \fBav_ripemd_size\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
