.TH "RowData" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RowData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRowData\fP (\fBint\fP index_, \fBconst\fP wxString &title_, \fBSelectedRegion\fP selectedRegion_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBindex\fP"
.br
.ti -1c
.RI "wxString \fBtitle\fP"
.br
.ti -1c
.RI "\fBSelectedRegion\fP \fBselectedRegion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file LabelDialog\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RowData::RowData (\fBint\fP index_, \fBconst\fP wxString & title_, \fBSelectedRegion\fP selectedRegion_)\fC [inline]\fP"

.PP
Definition at line 58 of file LabelDialog\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP RowData::index"

.PP
Definition at line 62 of file LabelDialog\&.cpp\&.
.SS "\fBSelectedRegion\fP RowData::selectedRegion"

.PP
Definition at line 64 of file LabelDialog\&.cpp\&.
.SS "wxString RowData::title"

.PP
Definition at line 63 of file LabelDialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
