.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/wasapi/mingw-include/rpcsal.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/src/hostapi/wasapi/mingw-include/rpcsal.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRPC_range\fP(\fBmin\fP,  \fBmax\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in\fP"
.br
.ti -1c
.RI "#define \fB__RPC__in_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__in_opt_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_in_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__opt_in_opt_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_part\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_full_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_in\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_part\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_full_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_in_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__out\fP"
.br
.ti -1c
.RI "#define \fB__RPC__out_ecount\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__out_ecount_part\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__out_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__out_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__inout\fP"
.br
.ti -1c
.RI "#define \fB__RPC__inout_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__opt_inout\fP"
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount\fP(\fBsize\fP)                                      "
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_part\fP(\fBsize\fP,  \fBlength\fP)    "
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_full\fP(\fBsize\fP)                "
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_full_string\fP(\fBsize\fP)                "
.br
.ti -1c
.RI "#define \fB__RPC__in_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__in_ecount_opt\fP(\fBsize\fP)  "
.br
.ti -1c
.RI "#define \fB__RPC__inout_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_full_opt\fP(\fBsize\fP)      "
.br
.ti -1c
.RI "#define \fB__RPC__inout_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_opt_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_part\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_opt_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_full_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_inout_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount\fP(\fBsize\fP)      "
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_part\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_full\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_full_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_full_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_out_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_opt\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_opt_string\fP"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_opt\fP(\fBsize\fP)  "
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_part_opt\fP(\fBsize\fP,  \fBlength\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_full_opt\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC__deref_opt_inout_ecount_full_opt_string\fP(\fBsize\fP)"
.br
.ti -1c
.RI "#define \fB__RPC_full_pointer\fP"
.br
.ti -1c
.RI "#define \fB__RPC_unique_pointer\fP"
.br
.ti -1c
.RI "#define \fB__RPC_ref_pointer\fP"
.br
.ti -1c
.RI "#define \fB__RPC_string\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __RPC__deref_in"

.PP
Definition at line 23 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount(\fBsize\fP)"

.PP
Definition at line 27 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_full(\fBsize\fP)"

.PP
Definition at line 29 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 30 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 32 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 31 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_opt(\fBsize\fP)"

.PP
Definition at line 33 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_opt_string(\fBsize\fP)"

.PP
Definition at line 34 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 28 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 35 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_opt"

.PP
Definition at line 26 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_in_string"

.PP
Definition at line 24 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout"

.PP
Definition at line 77 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_full(\fBsize\fP)"

.PP
Definition at line 81 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 85 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 86 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 82 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_opt(\fBsize\fP)"

.PP
Definition at line 83 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 84 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_opt"

.PP
Definition at line 79 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_opt_string"

.PP
Definition at line 80 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_inout_string"

.PP
Definition at line 78 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_in"

.PP
Definition at line 25 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_in_opt"

.PP
Definition at line 12 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout"

.PP
Definition at line 91 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount(\fBsize\fP)"

.PP
Definition at line 93 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_full(\fBsize\fP)"

.PP
Definition at line 95 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 107 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 108 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 96 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_opt(\fBsize\fP)"

.PP
Definition at line 105 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 94 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 106 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_opt"

.PP
Definition at line 103 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_opt_string"

.PP
Definition at line 104 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_opt_inout_string"

.PP
Definition at line 92 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out"

.PP
Definition at line 66 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount(\fBsize\fP)"

.PP
Definition at line 70 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_full(\fBsize\fP)"

.PP
Definition at line 72 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 100 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 101 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 73 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_opt(\fBsize\fP)"

.PP
Definition at line 98 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 71 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 99 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_opt"

.PP
Definition at line 68 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_opt_string"

.PP
Definition at line 69 of file rpcsal\&.h\&.
.SS "#define __RPC__deref_out_string"

.PP
Definition at line 67 of file rpcsal\&.h\&.
.SS "#define __RPC__in"

.PP
Definition at line 9 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount(\fBsize\fP)"

.PP
Definition at line 14 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_full(\fBsize\fP)"

.PP
Definition at line 15 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 18 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 19 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 16 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_opt(\fBsize\fP)"

.PP
Definition at line 55 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 17 of file rpcsal\&.h\&.
.SS "#define __RPC__in_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 21 of file rpcsal\&.h\&.
.SS "#define __RPC__in_opt"

.PP
Definition at line 54 of file rpcsal\&.h\&.
.SS "#define __RPC__in_opt_string"

.PP
Definition at line 11 of file rpcsal\&.h\&.
.SS "#define __RPC__in_string"

.PP
Definition at line 10 of file rpcsal\&.h\&.
.SS "#define __RPC__inout"

.PP
Definition at line 45 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount(\fBsize\fP)"

.PP
Definition at line 48 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_full(\fBsize\fP)"

.PP
Definition at line 50 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_full_opt(\fBsize\fP)"

.PP
Definition at line 62 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_full_opt_string(\fBsize\fP)"

.PP
Definition at line 20 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 63 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 63 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_opt(\fBsize\fP)"

.PP
Definition at line 60 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 49 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_ecount_part_opt(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 61 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_opt"

.PP
Definition at line 59 of file rpcsal\&.h\&.
.SS "#define __RPC__inout_string"

.PP
Definition at line 46 of file rpcsal\&.h\&.
.SS "#define __RPC__opt_in_opt_string"

.PP
Definition at line 13 of file rpcsal\&.h\&.
.SS "#define __RPC__opt_inout"

.PP
Definition at line 47 of file rpcsal\&.h\&.
.SS "#define __RPC__out"

.PP
Definition at line 38 of file rpcsal\&.h\&.
.SS "#define __RPC__out_ecount(\fBsize\fP)"

.PP
Definition at line 39 of file rpcsal\&.h\&.
.SS "#define __RPC__out_ecount_full(\fBsize\fP)"

.PP
Definition at line 41 of file rpcsal\&.h\&.
.SS "#define __RPC__out_ecount_full_string(\fBsize\fP)"

.PP
Definition at line 42 of file rpcsal\&.h\&.
.SS "#define __RPC__out_ecount_part(\fBsize\fP, \fBlength\fP)"

.PP
Definition at line 40 of file rpcsal\&.h\&.
.SS "#define __RPC_full_pointer"

.PP
Definition at line 110 of file rpcsal\&.h\&.
.SS "#define __RPC_ref_pointer"

.PP
Definition at line 112 of file rpcsal\&.h\&.
.SS "#define __RPC_string"

.PP
Definition at line 113 of file rpcsal\&.h\&.
.SS "#define __RPC_unique_pointer"

.PP
Definition at line 111 of file rpcsal\&.h\&.
.SS "#define RPC_range(\fBmin\fP, \fBmax\fP)"

.PP
Definition at line 7 of file rpcsal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
