.TH "RulerPanel" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RulerPanel \- \fBRulerPanel\fP class allows you to work with a \fBRuler\fP like any other wxWindow\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ruler\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRulerPanel\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize)"
.br
.ti -1c
.RI "\fB~RulerPanel\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBDoSetSize\fP (\fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height, \fBint\fP sizeFlags=wxSIZE_AUTO)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnErase\fP (wxEraseEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPaint\fP (wxPaintEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSize\fP (wxSizeEvent &evt)"
.br
.ti -1c
.RI "\fBbool\fP \fBAcceptsFocus\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBAcceptsFocusFromKeyboard\fP () \fBconst\fP "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRuler\fP \fBruler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRulerPanel\fP class allows you to work with a \fBRuler\fP like any other wxWindow\&. 
.PP
Definition at line 241 of file Ruler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RulerPanel::RulerPanel (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP)"

.PP
Definition at line 1598 of file Ruler\&.cpp\&.
.SS "RulerPanel::~RulerPanel ()"

.PP
Definition at line 1605 of file Ruler\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP RulerPanel::AcceptsFocus () const\fC [inline]\fP"

.PP
Definition at line 260 of file Ruler\&.h\&.
.SS "\fBbool\fP RulerPanel::AcceptsFocusFromKeyboard () const\fC [inline]\fP"

.PP
Definition at line 262 of file Ruler\&.h\&.
.SS "\fBvoid\fP RulerPanel::DoSetSize (\fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height, \fBint\fP sizeFlags = \fCwxSIZE_AUTO\fP)"

.PP
Definition at line 1634 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP RulerPanel::OnErase (wxEraseEvent & evt)"

.PP
Definition at line 1609 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP RulerPanel::OnPaint (wxPaintEvent & evt)"

.PP
Definition at line 1614 of file Ruler\&.cpp\&.
.SS "\fBvoid\fP RulerPanel::OnSize (wxSizeEvent & evt)"

.PP
Definition at line 1625 of file Ruler\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRuler\fP RulerPanel::ruler"

.PP
Definition at line 266 of file Ruler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
