.TH "SampleBuffer" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SampleFormat\&.h>\fP
.PP
Inherited by \fBGrowableSampleBuffer\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleBuffer\fP ()"
.br
.ti -1c
.RI "\fBSampleBuffer\fP (\fBint\fP \fBcount\fP, \fBsampleFormat\fP \fBformat\fP)"
.br
.ti -1c
.RI "\fB~SampleBuffer\fP ()"
.br
.ti -1c
.RI "\fBSampleBuffer\fP & \fBAllocate\fP (\fBint\fP \fBcount\fP, \fBsampleFormat\fP \fBformat\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBsamplePtr\fP \fBptr\fP () \fBconst\fP "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file SampleFormat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SampleBuffer::SampleBuffer ()\fC [inline]\fP"

.PP
Definition at line 58 of file SampleFormat\&.h\&.
.SS "SampleBuffer::SampleBuffer (\fBint\fP count, \fBsampleFormat\fP format)\fC [inline]\fP"

.PP
Definition at line 61 of file SampleFormat\&.h\&.
.SS "SampleBuffer::~SampleBuffer ()\fC [inline]\fP"

.PP
Definition at line 64 of file SampleFormat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSampleBuffer\fP& SampleBuffer::Allocate (\fBint\fP count, \fBsampleFormat\fP format)\fC [inline]\fP"

.PP
Definition at line 70 of file SampleFormat\&.h\&.
.SS "\fBvoid\fP SampleBuffer::Free ()\fC [inline]\fP"

.PP
Definition at line 78 of file SampleFormat\&.h\&.
.SS "\fBsamplePtr\fP SampleBuffer::ptr () const\fC [inline]\fP"

.PP
Definition at line 84 of file SampleFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
