.TH "Sampler" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sampler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_URID_Map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBLV2_Worker_Schedule\fP * \fBschedule\fP"
.br
.ti -1c
.RI "\fBLV2_Log_Log\fP * \fBlog\fP"
.br
.ti -1c
.RI "\fBLV2_Atom_Forge\fP \fBforge\fP"
.br
.ti -1c
.RI "\fBLV2_Log_Logger\fP \fBlogger\fP"
.br
.ti -1c
.RI "\fBSample\fP * \fBsample\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBLV2_Atom_Sequence\fP * \fBcontrol_port\fP"
.br
.ti -1c
.RI "\fBLV2_Atom_Sequence\fP * \fBnotify_port\fP"
.br
.ti -1c
.RI "float * \fBoutput_port\fP"
.br
.ti -1c
.RI "\fBLV2_Atom_Forge_Frame\fP \fBnotify_frame\fP"
.br
.ti -1c
.RI "\fBSamplerURIs\fP \fBuris\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBframe_offset\fP"
.br
.ti -1c
.RI "\fBsf_count_t\fP \fBframe\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBplay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file sampler\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBLV2_Atom_Sequence\fP* Sampler::control_port"

.PP
Definition at line 73 of file sampler\&.c\&.
.SS "\fBLV2_Atom_Forge\fP Sampler::forge"

.PP
Definition at line 64 of file sampler\&.c\&.
.SS "\fBsf_count_t\fP Sampler::frame"

.PP
Definition at line 87 of file sampler\&.c\&.
.SS "\fBuint32_t\fP Sampler::frame_offset"

.PP
Definition at line 84 of file sampler\&.c\&.
.SS "\fBLV2_Log_Log\fP* Sampler::log"

.PP
Definition at line 61 of file sampler\&.c\&.
.SS "\fBLV2_Log_Logger\fP Sampler::logger"

.PP
Definition at line 67 of file sampler\&.c\&.
.SS "\fBLV2_URID_Map\fP* Sampler::map"

.PP
Definition at line 59 of file sampler\&.c\&.
.SS "\fBLV2_Atom_Forge_Frame\fP Sampler::notify_frame"

.PP
Definition at line 78 of file sampler\&.c\&.
.SS "\fBLV2_Atom_Sequence\fP* Sampler::notify_port"

.PP
Definition at line 74 of file sampler\&.c\&.
.SS "float* Sampler::output_port"

.PP
Definition at line 75 of file sampler\&.c\&.
.SS "\fBbool\fP Sampler::play"

.PP
Definition at line 88 of file sampler\&.c\&.
.SS "\fBSample\fP* Sampler::sample"

.PP
Definition at line 70 of file sampler\&.c\&.
.SS "\fBLV2_Worker_Schedule\fP* Sampler::schedule"

.PP
Definition at line 60 of file sampler\&.c\&.
.SS "\fBSamplerURIs\fP Sampler::uris"

.PP
Definition at line 81 of file sampler\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
