.TH "SamplerURIs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SamplerURIs \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uris\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_Blank\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_Path\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_Resource\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_Sequence\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_URID\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_eventTransfer\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBeg_applySample\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBeg_sample\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBeg_freeSample\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBmidi_Event\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBpatch_Set\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBpatch_property\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBpatch_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file uris\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLV2_URID\fP SamplerURIs::atom_Blank"

.PP
Definition at line 31 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::atom_eventTransfer"

.PP
Definition at line 36 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::atom_Path"

.PP
Definition at line 32 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::atom_Resource"

.PP
Definition at line 33 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::atom_Sequence"

.PP
Definition at line 34 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::atom_URID"

.PP
Definition at line 35 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::eg_applySample"

.PP
Definition at line 37 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::eg_freeSample"

.PP
Definition at line 39 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::eg_sample"

.PP
Definition at line 38 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::midi_Event"

.PP
Definition at line 40 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::patch_property"

.PP
Definition at line 42 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::patch_Set"

.PP
Definition at line 41 of file uris\&.h\&.
.SS "\fBLV2_URID\fP SamplerURIs::patch_value"

.PP
Definition at line 43 of file uris\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
