.TH "SamplerUI" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SamplerUI \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_Atom_Forge\fP \fBforge\fP"
.br
.ti -1c
.RI "\fBLV2_URID_Map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBSamplerURIs\fP \fBuris\fP"
.br
.ti -1c
.RI "\fBLV2UI_Write_Function\fP \fBwrite\fP"
.br
.ti -1c
.RI "\fBLV2UI_Controller\fP \fBcontroller\fP"
.br
.ti -1c
.RI "GtkWidget * \fBbox\fP"
.br
.ti -1c
.RI "GtkWidget * \fBbutton\fP"
.br
.ti -1c
.RI "GtkWidget * \fBlabel\fP"
.br
.ti -1c
.RI "GtkWidget * \fBwindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file sampler_ui\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "GtkWidget* SamplerUI::box"

.PP
Definition at line 42 of file sampler_ui\&.c\&.
.SS "GtkWidget* SamplerUI::button"

.PP
Definition at line 43 of file sampler_ui\&.c\&.
.SS "\fBLV2UI_Controller\fP SamplerUI::controller"

.PP
Definition at line 40 of file sampler_ui\&.c\&.
.SS "\fBLV2_Atom_Forge\fP SamplerUI::forge"

.PP
Definition at line 34 of file sampler_ui\&.c\&.
.SS "GtkWidget* SamplerUI::label"

.PP
Definition at line 44 of file sampler_ui\&.c\&.
.SS "\fBLV2_URID_Map\fP* SamplerUI::map"

.PP
Definition at line 36 of file sampler_ui\&.c\&.
.SS "\fBSamplerURIs\fP SamplerUI::uris"

.PP
Definition at line 37 of file sampler_ui\&.c\&.
.SS "GtkWidget* SamplerUI::window"

.PP
Definition at line 45 of file sampler_ui\&.c\&.
.SS "\fBLV2UI_Write_Function\fP SamplerUI::write"

.PP
Definition at line 39 of file sampler_ui\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
