.TH "SAProgress" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAProgress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scorealign\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSAProgress\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBset_frame_period\fP (double seconds)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBset_duration\fP (\fBint\fP index, \fBbool\fP audio_flag, double seconds)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBset_smoothing\fP (\fBbool\fP \fBs\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBset_phase\fP (\fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBset_feature_progress\fP (float seconds)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBset_matrix_progress\fP (\fBint\fP cells)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBset_smoothing_progress\fP (\fBint\fP \fBi\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBframe_period\fP"
.br
.ti -1c
.RI "\fBint\fP \fBphase\fP"
.br
.ti -1c
.RI "double \fBdurations\fP [2]"
.br
.ti -1c
.RI "\fBbool\fP \fBis_audio\fP [2]"
.br
.ti -1c
.RI "\fBbool\fP \fBsmoothing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file scorealign\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SAProgress::SAProgress ()\fC [inline]\fP"

.PP
Definition at line 18 of file scorealign\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBvoid\fP SAProgress::set_duration (\fBint\fP index, \fBbool\fP audio_flag, double seconds)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 25 of file scorealign\&.h\&.
.SS "virtual \fBbool\fP SAProgress::set_feature_progress (float seconds)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 40 of file scorealign\&.h\&.
.SS "virtual \fBvoid\fP SAProgress::set_frame_period (double seconds)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 21 of file scorealign\&.h\&.
.SS "virtual \fBbool\fP SAProgress::set_matrix_progress (\fBint\fP cells)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 43 of file scorealign\&.h\&.
.SS "virtual \fBvoid\fP SAProgress::set_phase (\fBint\fP i)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 37 of file scorealign\&.h\&.
.SS "virtual \fBvoid\fP SAProgress::set_smoothing (\fBbool\fP s)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 29 of file scorealign\&.h\&.
.SS "virtual \fBbool\fP SAProgress::set_smoothing_progress (\fBint\fP i)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 45 of file scorealign\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double SAProgress::durations[2]\fC [protected]\fP"

.PP
Definition at line 49 of file scorealign\&.h\&.
.SS "double SAProgress::frame_period\fC [protected]\fP"

.PP
Definition at line 45 of file scorealign\&.h\&.
.SS "\fBbool\fP SAProgress::is_audio[2]\fC [protected]\fP"

.PP
Definition at line 50 of file scorealign\&.h\&.
.SS "\fBint\fP SAProgress::phase\fC [protected]\fP"

.PP
Definition at line 48 of file scorealign\&.h\&.
.SS "\fBbool\fP SAProgress::smoothing\fC [protected]\fP"

.PP
Definition at line 51 of file scorealign\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
