.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/sd2.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/sd2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSD2_RSRC\fP"
.br
.ti -1c
.RI "struct \fBSTR_RSRC\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSd2f_MARKER\fP   MAKE_MARKER ('\fBS\fP', '\fBd\fP', '2', '\fBf\fP')"
.br
.ti -1c
.RI "#define \fBSd2a_MARKER\fP   MAKE_MARKER ('\fBS\fP', '\fBd\fP', '2', '\fBa\fP')"
.br
.ti -1c
.RI "#define \fBALCH_MARKER\fP   MAKE_MARKER ('\fBA\fP', 'L', 'C', 'H')"
.br
.ti -1c
.RI "#define \fBlsf1_MARKER\fP   MAKE_MARKER ('\fBl\fP', '\fBs\fP', '\fBf\fP', '1')"
.br
.ti -1c
.RI "#define \fBSTR_MARKER\fP   MAKE_MARKER ('\fBS\fP', '\fBT\fP', 'R', ' ')"
.br
.ti -1c
.RI "#define \fBsdML_MARKER\fP   MAKE_MARKER ('\fBs\fP', '\fBd\fP', '\fBM\fP', 'L')"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBRSRC_STR\fP = 111, \fBRSRC_BIN\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsd2_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ALCH_MARKER   MAKE_MARKER ('\fBA\fP', 'L', 'C', 'H')"

.PP
Definition at line 47 of file sd2\&.c\&.
.SS "#define lsf1_MARKER   MAKE_MARKER ('\fBl\fP', '\fBs\fP', '\fBf\fP', '1')"

.PP
Definition at line 48 of file sd2\&.c\&.
.SS "#define Sd2a_MARKER   MAKE_MARKER ('\fBS\fP', '\fBd\fP', '2', '\fBa\fP')"

.PP
Definition at line 46 of file sd2\&.c\&.
.SS "#define Sd2f_MARKER   MAKE_MARKER ('\fBS\fP', '\fBd\fP', '2', '\fBf\fP')"

.PP
Definition at line 45 of file sd2\&.c\&.
.SS "#define sdML_MARKER   MAKE_MARKER ('\fBs\fP', '\fBd\fP', '\fBM\fP', 'L')"

.PP
Definition at line 51 of file sd2\&.c\&.
.SS "#define STR_MARKER   MAKE_MARKER ('\fBS\fP', '\fBT\fP', 'R', ' ')"

.PP
Definition at line 50 of file sd2\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRSRC_STR \fP\fP
.TP
\fB\fIRSRC_BIN \fP\fP
.PP
Definition at line 53 of file sd2\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP sd2_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 101 of file sd2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
