.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/examples/seeking_example.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/examples/seeking_example.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'vorbis/vorbisfile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_verify\fP (\fBOggVorbis_File\fP *ov, \fBogg_int64_t\fP val, \fBogg_int64_t\fP pcmval, double timeval, \fBogg_int64_t\fP pcmlength, char *bigassbuffer)"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP _verify (\fBOggVorbis_File\fP * ov, \fBogg_int64_t\fP val, \fBogg_int64_t\fP pcmval, double timeval, \fBogg_int64_t\fP pcmlength, char * bigassbuffer)"

.PP
Definition at line 28 of file seeking_example\&.c\&.
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 89 of file seeking_example\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
