.TH "SelectionBar" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelectionBar \- (not quite a Toolbar) at foot of screen for setting and viewing the selection range\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SelectionBar\&.h>\fP
.PP
Inherits \fBToolBar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectionBar\fP ()"
.br
.ti -1c
.RI "virtual \fB~SelectionBar\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreate\fP (wxWindow *parent)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopulate\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBRepaint\fP (wxDC *WXUNUSED(dc)) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBEnableDisableButtons\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdatePrefs\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetTimes\fP (double \fBstart\fP, double \fBend\fP, double audio)"
.br
.ti -1c
.RI "double \fBGetLeftTime\fP ()"
.br
.ti -1c
.RI "double \fBGetRightTime\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetField\fP (\fBconst\fP wxChar *msg, \fBint\fP fieldNum)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSnapTo\fP (\fBint\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSelectionFormat\fP (\fBconst\fP wxString &\fBformat\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetRate\fP (double \fBrate\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetListener\fP (\fBSelectionBarListener\fP *\fBl\fP)"
.br
.ti -1c
.RI "\fBDECLARE_CLASS\fP (\fBSelectionBar\fP)"
.br
.ti -1c
.RI "\fBDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
(not quite a Toolbar) at foot of screen for setting and viewing the selection range\&. 
.PP
Definition at line 30 of file SelectionBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SelectionBar::SelectionBar ()"

.PP
Definition at line 87 of file SelectionBar\&.cpp\&.
.SS "SelectionBar::~SelectionBar ()\fC [virtual]\fP"

.PP
Definition at line 102 of file SelectionBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP SelectionBar::Create (wxWindow * parent)\fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 106 of file SelectionBar\&.cpp\&.
.SS "SelectionBar::DECLARE_CLASS (\fBSelectionBar\fP)"

.SS "SelectionBar::DECLARE_EVENT_TABLE ()"

.SS "\fBvoid\fP SelectionBar::EnableDisableButtons ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 41 of file SelectionBar\&.h\&.
.SS "double SelectionBar::GetLeftTime ()"

.PP
Definition at line 442 of file SelectionBar\&.cpp\&.
.SS "double SelectionBar::GetRightTime ()"

.PP
Definition at line 447 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::Populate ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 111 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::Repaint (wxDC * WXUNUSEDdc)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 40 of file SelectionBar\&.h\&.
.SS "\fBvoid\fP SelectionBar::SetField (\fBconst\fP wxChar * msg, \fBint\fP fieldNum)"

.PP
Definition at line 462 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::SetListener (\fBSelectionBarListener\fP * l)"

.PP
Definition at line 301 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::SetRate (double rate)"

.PP
Definition at line 487 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::SetSelectionFormat (\fBconst\fP wxString & format)"

.PP
Definition at line 478 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::SetSnapTo (\fBint\fP snap)"

.PP
Definition at line 473 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::SetTimes (double start, double end, double audio)"

.PP
Definition at line 433 of file SelectionBar\&.cpp\&.
.SS "\fBvoid\fP SelectionBar::UpdatePrefs ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 286 of file SelectionBar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
