.TH "C:/_dev/OpenU/Audacity/audacity/src/toolbars/SelectionBarListener.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/toolbars/SelectionBarListener.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSelectionBarListener\fP"
.br
.RI "\fIA parent class of \fBSelectionBar\fP, used to forward events to do with changes in the \fBSelectionBar\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
