.TH "SelectionBarListener" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SelectionBarListener \- A parent class of \fBSelectionBar\fP, used to forward events to do with changes in the \fBSelectionBar\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SelectionBarListener\&.h>\fP
.PP
Inherited by \fBAudacityProject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectionBarListener\fP ()"
.br
.ti -1c
.RI "virtual \fB~SelectionBarListener\fP ()"
.br
.ti -1c
.RI "virtual double \fBAS_GetRate\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBAS_SetRate\fP (double \fBrate\fP)=0"
.br
.ti -1c
.RI "virtual \fBint\fP \fBAS_GetSnapTo\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBAS_SetSnapTo\fP (\fBint\fP snap)=0"
.br
.ti -1c
.RI "virtual \fBconst\fP wxString & \fBAS_GetSelectionFormat\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBAS_SetSelectionFormat\fP (\fBconst\fP wxString &\fBformat\fP)=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBAS_ModifySelection\fP (double &\fBstart\fP, double &\fBend\fP, \fBbool\fP \fBdone\fP)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A parent class of \fBSelectionBar\fP, used to forward events to do with changes in the \fBSelectionBar\fP\&. 
.PP
Definition at line 16 of file SelectionBarListener\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SelectionBarListener::SelectionBarListener ()\fC [inline]\fP"

.PP
Definition at line 20 of file SelectionBarListener\&.h\&.
.SS "virtual SelectionBarListener::~SelectionBarListener ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 21 of file SelectionBarListener\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual double SelectionBarListener::AS_GetRate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBconst\fP wxString& SelectionBarListener::AS_GetSelectionFormat ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBint\fP SelectionBarListener::AS_GetSnapTo ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBvoid\fP SelectionBarListener::AS_ModifySelection (double & start, double & end, \fBbool\fP done)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBvoid\fP SelectionBarListener::AS_SetRate (double rate)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBvoid\fP SelectionBarListener::AS_SetSelectionFormat (\fBconst\fP wxString & format)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.
.SS "virtual \fBvoid\fP SelectionBarListener::AS_SetSnapTo (\fBint\fP snap)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudacityProject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
