.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/seqfnintdefs.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/seqfnintdefs.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_reset\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_insert_ctrl\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_insert_ramp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_insert_macctrl\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_insert_note\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_copy\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_create\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_next\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_get\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_read\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_read_smf\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_write\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlc_seq_write_smf\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBLVAL\fP xlc_seq_copy (\fBvoid\fP)"

.PP
Definition at line 114 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_create (\fBvoid\fP)"

.PP
Definition at line 127 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_get (\fBvoid\fP)"

.PP
Definition at line 154 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_insert_ctrl (\fBvoid\fP)"

.PP
Definition at line 42 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_insert_macctrl (\fBvoid\fP)"

.PP
Definition at line 79 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_insert_note (\fBvoid\fP)"

.PP
Definition at line 96 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_insert_ramp (\fBvoid\fP)"

.PP
Definition at line 59 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_next (\fBvoid\fP)"

.PP
Definition at line 141 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_read (\fBvoid\fP)"

.PP
Definition at line 193 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_read_smf (\fBvoid\fP)"

.PP
Definition at line 208 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_reset (\fBvoid\fP)"

.PP
Definition at line 30 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_write (\fBvoid\fP)"

.PP
Definition at line 223 of file seqfnint\&.c\&.
.SS "\fBLVAL\fP xlc_seq_write_smf (\fBvoid\fP)"

.PP
Definition at line 239 of file seqfnint\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
