.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/seqmwrite.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/seqmwrite.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'switches\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'userio\&.h'\fP
.br
\fC#include 'midicode\&.h'\fP
.br
\fC#include 'mfmidi\&.h'\fP
.br
\fC#include 'midifns\&.h'\fP
.br
\fC#include 'timebase\&.h'\fP
.br
\fC#include 'moxc\&.h'\fP
.br
\fC#include 'seq\&.h'\fP
.br
\fC#include 'seqread\&.h'\fP
.br
\fC#include 'seqmwrite\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsmf_write_seq\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_bend\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_cause_noteoff\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_ctrl\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_deltatime\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_dotrack\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_exclusive\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_noteoff\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_noteon\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_process_event\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_ramp_event\fP (\fBseq_type\fP seq, \fBevent_type\fP event, unsigned \fBint\fP \fBvalue\fP, unsigned \fBint\fP to_value, \fBint\fP increment, \fBtime_type\fP step, \fBint\fP n)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_send_macro\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_touch\fP (\fBseq_type\fP seq, \fBint\fP \fBvoice\fP, \fBint\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBwritevarlen\fP ()"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_bend\fP (\fBseq_type\fP seq, \fBint\fP \fBvoice\fP, \fBint\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_cause_noteoff\fP (\fBseq_type\fP seq, \fBtime_type\fP delay, \fBint\fP \fBvoice\fP, \fBint\fP \fBpitch\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_clock_event\fP (\fBtime_type\fP old_ticksize, \fBtime_type\fP new_ticksize)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_ctrl\fP (\fBseq_type\fP seq, \fBint\fP \fBvoice\fP, \fBint\fP ctrl_name, \fBint\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_dotrack\fP (\fBseq_type\fP seq)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_exclusive\fP (\fBint\fP \fBlength\fP, unsigned char *msg)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_msg_write\fP (\fBint\fP n, unsigned char c1, unsigned char \fBc2\fP, unsigned char c3)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_noteoff\fP (\fBseq_type\fP seq, \fBint\fP \fBvoice\fP, \fBint\fP \fBpitch\fP)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_noteon\fP (\fBseq_type\fP seq, \fBint\fP \fBvoice\fP, \fBint\fP \fBpitch\fP, \fBint\fP vel)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_process_event\fP (\fBseq_type\fP seq)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBsmfw_send_macro\fP (unsigned char *ptr, \fBint\fP \fBvoice\fP, parameter, \fBint\fP parm_num, \fBint\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBseq_write_smf\fP (\fBseq_type\fP seq, FILE *outfile)"
.br
.ti -1c
.RI "\fBprivate\fP \fBvoid\fP \fBwritevarlen\fP (long \fBvalue\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "long \fBchunk_size_marker\fP"
.br
.ti -1c
.RI "\fBint\fP \fBseti_counter\fP"
.br
.ti -1c
.RI "\fBtime_type\fP \fBa_start_time\fP"
.br
.ti -1c
.RI "long \fBlast_event\fP"
.br
.ti -1c
.RI "\fBtime_type\fP \fBlast_clock_event\fP"
.br
.ti -1c
.RI "\fBtime_type\fP \fBlast_tick_size\fP"
.br
.ti -1c
.RI "struct \fBsmf_write_seq\fP \fBsmfw_seq\fP"
.br
.ti -1c
.RI "\fBseq_type\fP \fBsequence\fP"
.br
.ti -1c
.RI "\fBtime_type\fP \fBclock_ticksize\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBclock_running\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBuse_midi_clock\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP seq_write_smf (\fBseq_type\fP seq, FILE * outfile)"

.PP
Definition at line 512 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_bend ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_bend (\fBseq_type\fP seq, \fBint\fP voice, \fBint\fP value)"

.PP
Definition at line 65 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_cause_noteoff ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_cause_noteoff (\fBseq_type\fP seq, \fBtime_type\fP delay, \fBint\fP voice, \fBint\fP pitch)"

.PP
Definition at line 84 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_clock_event (\fBtime_type\fP old_ticksize, \fBtime_type\fP new_ticksize)"

.PP
Definition at line 100 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_ctrl ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_ctrl (\fBseq_type\fP seq, \fBint\fP voice, \fBint\fP ctrl_name, \fBint\fP value)"

.PP
Definition at line 130 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_deltatime ()"

.PP
Definition at line 142 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_dotrack ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_dotrack (\fBseq_type\fP seq)"

.PP
Definition at line 162 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_exclusive ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_exclusive (\fBint\fP length, unsigned char * msg)"

.PP
Definition at line 208 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_msg_write (\fBint\fP n, unsigned char c1, unsigned char c2, unsigned char c3)"

.PP
Definition at line 225 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_noteoff ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_noteoff (\fBseq_type\fP seq, \fBint\fP voice, \fBint\fP pitch)"

.PP
Definition at line 247 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_noteon ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_noteon (\fBseq_type\fP seq, \fBint\fP voice, \fBint\fP pitch, \fBint\fP vel)"

.PP
Definition at line 262 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_process_event ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_process_event (\fBseq_type\fP seq)"

.PP
Definition at line 276 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_ramp_event (\fBseq_type\fP seq, \fBevent_type\fP event, unsigned \fBint\fP value, unsigned \fBint\fP to_value, \fBint\fP increment, \fBtime_type\fP step, \fBint\fP n)"

.PP
Definition at line 437 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_send_macro ()"

.SS "\fBprivate\fP \fBvoid\fP smfw_send_macro (unsigned char * ptr, \fBint\fP voice, parameter, \fBint\fP parm_num, \fBint\fP value)"

.PP
Definition at line 471 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP smfw_touch (\fBseq_type\fP seq, \fBint\fP voice, \fBint\fP value)"

.PP
Definition at line 503 of file seqmwrite\&.c\&.
.SS "\fBprivate\fP \fBvoid\fP writevarlen ()"

.SS "\fBprivate\fP \fBvoid\fP writevarlen (long value)"

.PP
Definition at line 633 of file seqmwrite\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBtime_type\fP a_start_time"

.SS "long chunk_size_marker"

.PP
Definition at line 26 of file seqmwrite\&.c\&.
.SS "\fBboolean\fP clock_running"

.PP
Definition at line 34 of file seq\&.c\&.
.SS "\fBtime_type\fP clock_ticksize"

.PP
Definition at line 33 of file seq\&.c\&.
.SS "\fBtime_type\fP last_clock_event"

.PP
Definition at line 31 of file seqmwrite\&.c\&.
.SS "long last_event"

.PP
Definition at line 30 of file seqmwrite\&.c\&.
.SS "\fBtime_type\fP last_tick_size"

.PP
Definition at line 32 of file seqmwrite\&.c\&.
.SS "\fBseq_type\fP sequence"

.PP
Definition at line 29 of file seq\&.c\&.
.SS "\fBint\fP seti_counter"

.PP
Definition at line 27 of file seqmwrite\&.c\&.
.SS "struct \fBsmf_write_seq\fP  smfw_seq"

.SS "\fBboolean\fP use_midi_clock"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
