.TH "SerdWriterImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerdWriterImpl \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSerdSyntax\fP \fBsyntax\fP"
.br
.ti -1c
.RI "\fBSerdStyle\fP \fBstyle\fP"
.br
.ti -1c
.RI "\fBSerdEnv\fP * \fBenv\fP"
.br
.ti -1c
.RI "\fBSerdNode\fP \fBroot_node\fP"
.br
.ti -1c
.RI "\fBSerdURI\fP \fBroot_uri\fP"
.br
.ti -1c
.RI "\fBSerdURI\fP \fBbase_uri\fP"
.br
.ti -1c
.RI "\fBSerdStack\fP \fBanon_stack\fP"
.br
.ti -1c
.RI "\fBSerdBulkSink\fP \fBbulk_sink\fP"
.br
.ti -1c
.RI "\fBSerdSink\fP \fBsink\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBstream\fP"
.br
.ti -1c
.RI "\fBSerdErrorSink\fP \fBerror_sink\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBerror_handle\fP"
.br
.ti -1c
.RI "\fBWriteContext\fP \fBcontext\fP"
.br
.ti -1c
.RI "\fBSerdNode\fP \fBlist_subj\fP"
.br
.ti -1c
.RI "unsigned \fBlist_depth\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbprefix\fP"
.br
.ti -1c
.RI "size_t \fBbprefix_len\fP"
.br
.ti -1c
.RI "unsigned \fBindent\fP"
.br
.ti -1c
.RI "\fBSep\fP \fBlast_sep\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file writer\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSerdStack\fP SerdWriterImpl::anon_stack"

.PP
Definition at line 83 of file writer\&.c\&.
.SS "\fBSerdURI\fP SerdWriterImpl::base_uri"

.PP
Definition at line 82 of file writer\&.c\&.
.SS "\fBuint8_t\fP* SerdWriterImpl::bprefix"

.PP
Definition at line 92 of file writer\&.c\&.
.SS "size_t SerdWriterImpl::bprefix_len"

.PP
Definition at line 93 of file writer\&.c\&.
.SS "\fBSerdBulkSink\fP SerdWriterImpl::bulk_sink"

.PP
Definition at line 84 of file writer\&.c\&.
.SS "\fBWriteContext\fP SerdWriterImpl::context"

.PP
Definition at line 89 of file writer\&.c\&.
.SS "\fBbool\fP SerdWriterImpl::empty"

.PP
Definition at line 96 of file writer\&.c\&.
.SS "\fBSerdEnv\fP* SerdWriterImpl::env"

.PP
Definition at line 79 of file writer\&.c\&.
.SS "\fBvoid\fP* SerdWriterImpl::error_handle"

.PP
Definition at line 88 of file writer\&.c\&.
.SS "\fBSerdErrorSink\fP SerdWriterImpl::error_sink"

.PP
Definition at line 87 of file writer\&.c\&.
.SS "unsigned SerdWriterImpl::indent"

.PP
Definition at line 94 of file writer\&.c\&.
.SS "\fBSep\fP SerdWriterImpl::last_sep"

.PP
Definition at line 95 of file writer\&.c\&.
.SS "unsigned SerdWriterImpl::list_depth"

.PP
Definition at line 91 of file writer\&.c\&.
.SS "\fBSerdNode\fP SerdWriterImpl::list_subj"

.PP
Definition at line 90 of file writer\&.c\&.
.SS "\fBSerdNode\fP SerdWriterImpl::root_node"

.PP
Definition at line 80 of file writer\&.c\&.
.SS "\fBSerdURI\fP SerdWriterImpl::root_uri"

.PP
Definition at line 81 of file writer\&.c\&.
.SS "\fBSerdSink\fP SerdWriterImpl::sink"

.PP
Definition at line 85 of file writer\&.c\&.
.SS "\fBvoid\fP* SerdWriterImpl::stream"

.PP
Definition at line 86 of file writer\&.c\&.
.SS "\fBSerdStyle\fP SerdWriterImpl::style"

.PP
Definition at line 78 of file writer\&.c\&.
.SS "\fBSerdSyntax\fP SerdWriterImpl::syntax"

.PP
Definition at line 77 of file writer\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
