.TH "C:/_dev/OpenU/Audacity/audacity/mac/config/i386/lib-src/lv2/serd/serd_config.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/mac/config/i386/lib-src/lv2/serd/serd_config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_FMAX\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POSIX_MEMALIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FILENO\fP   1"
.br
.ti -1c
.RI "#define \fBSERD_VERSION\fP   '0\&.20\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE_FILENO   1"

.PP
Definition at line 9 of file serd_config\&.h\&.
.SS "#define HAVE_FMAX   1"

.PP
Definition at line 6 of file serd_config\&.h\&.
.SS "#define HAVE_POSIX_MEMALIGN   1"

.PP
Definition at line 7 of file serd_config\&.h\&.
.SS "#define SERD_VERSION   '0\&.20\&.0'"

.PP
Definition at line 10 of file serd_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
