.TH "SerdChunk" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerdChunk \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBuint8_t\fP * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An unterminated string fragment\&. 
.PP
Definition at line 217 of file serd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBuint8_t\fP* SerdChunk::buf"
Start of chunk 
.PP
Definition at line 218 of file serd\&.h\&.
.SS "size_t SerdChunk::len"
Length of chunk in bytes 
.PP
Definition at line 219 of file serd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
