.TH "SerdNode" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerdNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBuint8_t\fP * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBn_bytes\fP"
.br
.ti -1c
.RI "size_t \fBn_chars\fP"
.br
.ti -1c
.RI "\fBSerdNodeFlags\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBSerdType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A syntactic RDF node\&. 
.PP
Definition at line 206 of file serd\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBuint8_t\fP* SerdNode::buf"
Value string 
.PP
Definition at line 207 of file serd\&.h\&.
.SS "\fBSerdNodeFlags\fP SerdNode::flags"
Node flags (e\&.g\&. string properties) 
.PP
Definition at line 210 of file serd\&.h\&.
.SS "size_t SerdNode::n_bytes"
Size in bytes (not including null) 
.PP
Definition at line 208 of file serd\&.h\&.
.SS "size_t SerdNode::n_chars"
Length in characters (not including null) 
.PP
Definition at line 209 of file serd\&.h\&.
.SS "\fBSerdType\fP SerdNode::type"
Node type 
.PP
Definition at line 211 of file serd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
