.TH "C:/_dev/OpenU/Audacity/audacity/win/wxWidgets_additions/wxWidgets-3.0.2/include/wx/msw/setup.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/win/wxWidgets_additions/wxWidgets-3.0.2/include/wx/msw/setup.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBwxUSE_GUI\fP   1"
.br
.ti -1c
.RI "#define \fBWXWIN_COMPATIBILITY_2_6\fP   0"
.br
.ti -1c
.RI "#define \fBWXWIN_COMPATIBILITY_2_8\fP   1"
.br
.ti -1c
.RI "#define \fBwxDIALOG_UNIT_COMPATIBILITY\fP   0"
.br
.ti -1c
.RI "#define \fBwxDEBUG_LEVEL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ON_FATAL_EXCEPTION\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STACKWALKER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DEBUGREPORT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DEBUG_CONTEXT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_MEMORY_TRACING\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_GLOBAL_MEMORY_OPERATORS\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_DEBUG_NEW_ALWAYS\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_UNICODE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WCHAR_T\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_EXCEPTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_EXTENDED_RTTI\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LOGWINDOW\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LOGGUI\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LOG_DIALOG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CMDLINE_PARSER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_THREADS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STREAMS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PRINTF_POS_PARAMS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COMPILER_TLS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STL\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_STD_DEFAULT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STD_CONTAINERS\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_STD_IOSTREAM\fP   \fBwxUSE_STD_DEFAULT\fP"
.br
.ti -1c
.RI "#define \fBwxUSE_STD_STRING\fP   \fBwxUSE_STD_DEFAULT\fP"
.br
.ti -1c
.RI "#define \fBwxUSE_STD_STRING_CONV_IN_WXSTRING\fP   \fBwxUSE_STL\fP"
.br
.ti -1c
.RI "#define \fBwxUSE_IOSTREAMH\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_LONGLONG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BASE64\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CONSOLE_EVENTLOOP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FFILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FSVOLUME\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STDPATHS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TEXTBUFFER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TEXTFILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_INTL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_XLOCALE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DATETIME\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TIMER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STOPWATCH\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FSWATCHER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CONFIG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CONFIG_NATIVE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DIALUP_MANAGER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DYNLIB_CLASS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DYNAMIC_LOADER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SOCKETS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_IPV6\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_FILESYSTEM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FS_ZIP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FS_ARCHIVE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FS_INET\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ARCHIVE_STREAMS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ZIPSTREAM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TARSTREAM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ZLIB\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_APPLE_IEEE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_JOYSTICK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FONTENUM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FONTMAP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MIMETYPE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROTOCOL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROTOCOL_FILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROTOCOL_FTP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROTOCOL_HTTP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_URL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_URL_NATIVE\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_VARIANT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ANY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_REGEX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SYSTEM_OPTIONS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SOUND\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MEDIACTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_XRC\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_XML\fP   \fBwxUSE_XRC\fP"
.br
.ti -1c
.RI "#define \fBwxUSE_AUI\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RIBBON\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROPGRID\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STC\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WEBVIEW\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WEBVIEW_IE\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_WEBVIEW_WEBKIT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_GRAPHICS_CONTEXT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_CAIRO\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_CONTROLS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MARKUP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_POPUPWIN\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TIPWINDOW\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ANIMATIONCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BANNERWINDOW\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BUTTON\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BMPBUTTON\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CALENDARCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CHECKBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CHECKLISTBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CHOICE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COLLPANE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COLOURPICKERCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COMBOBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COMMANDLINKBUTTON\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DATAVIEWCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DATEPICKCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DIRPICKERCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_EDITABLELISTBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FILECTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FILEPICKERCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FONTPICKERCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GAUGE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_HEADERCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_HYPERLINKCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LISTBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LISTCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RADIOBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RADIOBTN\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RICHMSGDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SCROLLBAR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SEARCHCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SLIDER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SPINBTN\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SPINCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STATBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STATLINE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STATTEXT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STATBMP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TEXTCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TIMEPICKCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TOGGLEBTN\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TREECTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TREELISTCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STATUSBAR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_NATIVE_STATUSBAR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TOOLBAR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TOOLBAR_NATIVE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_NOTEBOOK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LISTBOOK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CHOICEBOOK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TREEBOOK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TOOLBOOK\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TASKBARICON\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GRID\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MINIFRAME\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COMBOCTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ODCOMBOBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BITMAPCOMBOBOX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_REARRANGECTRL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ACCEL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ARTPROVIDER_STD\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ARTPROVIDER_TANGO\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_HOTKEY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CARET\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DISPLAY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GEOMETRY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_IMAGLIST\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_INFOBAR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MENUS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_NOTIFICATION_MESSAGE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PREFERENCES_EDITOR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RICHTOOLTIP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SASH\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SPLITTER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TOOLTIPS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_VALIDATORS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_AUTOID_MANAGEMENT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_COMMON_DIALOGS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_BUSYINFO\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CHOICEDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_COLOURDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DIRDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FILEDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FINDREPLDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FONTDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MSGDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PROGRESSDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_STARTUP_TIPS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TEXTDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_NUMBERDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SPLASH\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WIZARDDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ABOUTDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_FILE_HISTORY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_METAFILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ENH_METAFILE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WIN_METAFILES_ALWAYS\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_MDI\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DOC_VIEW_ARCHITECTURE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MDI_ARCHITECTURE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PRINTING_ARCHITECTURE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_HTML\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GLCANVAS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RICHTEXT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CLIPBOARD\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DATAOBJ\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DRAG_AND_DROP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ACCESSIBILITY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SNGLINST_CHECKER\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DRAGIMAGE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_IPC\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_HELP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MS_HTML_HELP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WXHTML_HELP\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_CONSTRAINTS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SPLINES\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_MOUSEWHEEL\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_UIACTIONSIMULATOR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_POSTSCRIPT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_AFM_FOR_POSTSCRIPT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_SVG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DC_TRANSFORM_MATRIX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_IMAGE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBPNG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBJPEG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBTIFF\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TGA\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GIF\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PNM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PCX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_IFF\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_XPM\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ICO_CUR\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PALETTE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ALL_THEMES\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_THEME_GTK\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_THEME_METAL\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_THEME_MONO\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_THEME_WIN32\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_UNICODE_MSLU\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_MFC\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_OLE\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_OLE_AUTOMATION\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_ACTIVEX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_DC_CACHEING\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_WXDIB\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_POSTSCRIPT_ARCHITECTURE_IN_MSW\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_REGKEY\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RICHEDIT\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_RICHEDIT2\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_OWNER_DRAWN\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_TASKBARICON_BALLOONS\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_UXTHEME\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_INKEDIT\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_INICONF\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_DATEPICKCTRL_GENERIC\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_TIMEPICKCTRL_GENERIC\fP   0"
.br
.ti -1c
.RI "#define \fBwxUSE_CRASHREPORT\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define wxDEBUG_LEVEL   1"

.PP
Definition at line 71 of file setup\&.h\&.
.SS "#define wxDIALOG_UNIT_COMPATIBILITY   0"

.PP
Definition at line 56 of file setup\&.h\&.
.SS "#define wxUSE_ABOUTDLG   1"

.PP
Definition at line 1251 of file setup\&.h\&.
.SS "#define wxUSE_ACCEL   1"

.PP
Definition at line 1024 of file setup\&.h\&.
.SS "#define wxUSE_ACCESSIBILITY   1"

.PP
Definition at line 1369 of file setup\&.h\&.
.SS "#define wxUSE_ACTIVEX   1"

.PP
Definition at line 1560 of file setup\&.h\&.
.SS "#define wxUSE_AFM_FOR_POSTSCRIPT   1"

.PP
Definition at line 1424 of file setup\&.h\&.
.SS "#define wxUSE_ALL_THEMES   1"

.PP
Definition at line 1493 of file setup\&.h\&.
.SS "#define wxUSE_ANIMATIONCTRL   1"

.PP
Definition at line 850 of file setup\&.h\&.
.SS "#define wxUSE_ANY   1"

.PP
Definition at line 657 of file setup\&.h\&.
.SS "#define wxUSE_APPLE_IEEE   1"

.PP
Definition at line 602 of file setup\&.h\&.
.SS "#define wxUSE_ARCHIVE_STREAMS   1"

.PP
Definition at line 583 of file setup\&.h\&.
.SS "#define wxUSE_ARTPROVIDER_STD   1"

.PP
Definition at line 1037 of file setup\&.h\&.
.SS "#define wxUSE_ARTPROVIDER_TANGO   1"

.PP
Definition at line 1047 of file setup\&.h\&.
.SS "#define wxUSE_AUI   1"

.PP
Definition at line 702 of file setup\&.h\&.
.SS "#define wxUSE_AUTOID_MANAGEMENT   0"

.PP
Definition at line 1160 of file setup\&.h\&.
.SS "#define wxUSE_BANNERWINDOW   1"

.PP
Definition at line 851 of file setup\&.h\&.
.SS "#define wxUSE_BASE64   1"

.PP
Definition at line 411 of file setup\&.h\&.
.SS "#define wxUSE_BITMAPCOMBOBOX   1"

.PP
Definition at line 1008 of file setup\&.h\&.
.SS "#define wxUSE_BMPBUTTON   1"

.PP
Definition at line 853 of file setup\&.h\&.
.SS "#define wxUSE_BUSYINFO   1"

.PP
Definition at line 1178 of file setup\&.h\&.
.SS "#define wxUSE_BUTTON   1"

.PP
Definition at line 852 of file setup\&.h\&.
.SS "#define wxUSE_CAIRO   0"

.PP
Definition at line 801 of file setup\&.h\&.
.SS "#define wxUSE_CALENDARCTRL   1"

.PP
Definition at line 854 of file setup\&.h\&.
.SS "#define wxUSE_CARET   1"

.PP
Definition at line 1058 of file setup\&.h\&.
.SS "#define wxUSE_CHECKBOX   1"

.PP
Definition at line 855 of file setup\&.h\&.
.SS "#define wxUSE_CHECKLISTBOX   1"

.PP
Definition at line 856 of file setup\&.h\&.
.SS "#define wxUSE_CHOICE   1"

.PP
Definition at line 857 of file setup\&.h\&.
.SS "#define wxUSE_CHOICEBOOK   1"

.PP
Definition at line 943 of file setup\&.h\&.
.SS "#define wxUSE_CHOICEDLG   1"

.PP
Definition at line 1185 of file setup\&.h\&.
.SS "#define wxUSE_CLIPBOARD   1"

.PP
Definition at line 1344 of file setup\&.h\&.
.SS "#define wxUSE_CMDLINE_PARSER   1"

.PP
Definition at line 226 of file setup\&.h\&.
.SS "#define wxUSE_COLLPANE   1"

.PP
Definition at line 858 of file setup\&.h\&.
.SS "#define wxUSE_COLOURDLG   1"

.PP
Definition at line 1192 of file setup\&.h\&.
.SS "#define wxUSE_COLOURPICKERCTRL   1"

.PP
Definition at line 859 of file setup\&.h\&.
.SS "#define wxUSE_COMBOBOX   1"

.PP
Definition at line 860 of file setup\&.h\&.
.SS "#define wxUSE_COMBOCTRL   1"

.PP
Definition at line 992 of file setup\&.h\&.
.SS "#define wxUSE_COMMANDLINKBUTTON   1"

.PP
Definition at line 861 of file setup\&.h\&.
.SS "#define wxUSE_COMMON_DIALOGS   1"

.PP
Definition at line 1174 of file setup\&.h\&.
.SS "#define wxUSE_COMPILER_TLS   1"

.PP
Definition at line 286 of file setup\&.h\&.
.SS "#define wxUSE_CONFIG   1"

.PP
Definition at line 519 of file setup\&.h\&.
.SS "#define wxUSE_CONFIG_NATIVE   1"

.PP
Definition at line 532 of file setup\&.h\&.
.SS "#define wxUSE_CONSOLE_EVENTLOOP   1"

.PP
Definition at line 421 of file setup\&.h\&.
.SS "#define wxUSE_CONSTRAINTS   1"

.PP
Definition at line 1404 of file setup\&.h\&.
.SS "#define wxUSE_CONTROLS   1"

.PP
Definition at line 814 of file setup\&.h\&.
.SS "#define wxUSE_CRASHREPORT   1"

.PP
Definition at line 1661 of file setup\&.h\&.
.SS "#define wxUSE_DATAOBJ   1"

.PP
Definition at line 1352 of file setup\&.h\&.
.SS "#define wxUSE_DATAVIEWCTRL   1"

.PP
Definition at line 862 of file setup\&.h\&.
.SS "#define wxUSE_DATEPICKCTRL   1"

.PP
Definition at line 863 of file setup\&.h\&.
.SS "#define wxUSE_DATEPICKCTRL_GENERIC   0"

.PP
Definition at line 1641 of file setup\&.h\&.
.SS "#define wxUSE_DATETIME   1"

.PP
Definition at line 488 of file setup\&.h\&.
.SS "#define wxUSE_DC_CACHEING   1"

.PP
Definition at line 1563 of file setup\&.h\&.
.SS "#define wxUSE_DC_TRANSFORM_MATRIX   1"

.PP
Definition at line 1438 of file setup\&.h\&.
.SS "#define wxUSE_DEBUG_CONTEXT   0"

.PP
Definition at line 126 of file setup\&.h\&.
.SS "#define wxUSE_DEBUG_NEW_ALWAYS   0"

.PP
Definition at line 158 of file setup\&.h\&.
.SS "#define wxUSE_DEBUGREPORT   1"

.PP
Definition at line 104 of file setup\&.h\&.
.SS "#define wxUSE_DIALUP_MANAGER   1"

.PP
Definition at line 541 of file setup\&.h\&.
.SS "#define wxUSE_DIRDLG   1"

.PP
Definition at line 1195 of file setup\&.h\&.
.SS "#define wxUSE_DIRPICKERCTRL   1"

.PP
Definition at line 864 of file setup\&.h\&.
.SS "#define wxUSE_DISPLAY   1"

.PP
Definition at line 1067 of file setup\&.h\&.
.SS "#define wxUSE_DOC_VIEW_ARCHITECTURE   1"

.PP
Definition at line 1295 of file setup\&.h\&.
.SS "#define wxUSE_DRAG_AND_DROP   1"

.PP
Definition at line 1361 of file setup\&.h\&.
.SS "#define wxUSE_DRAGIMAGE   1"

.PP
Definition at line 1384 of file setup\&.h\&.
.SS "#define wxUSE_DYNAMIC_LOADER   1"

.PP
Definition at line 554 of file setup\&.h\&.
.SS "#define wxUSE_DYNLIB_CLASS   1"

.PP
Definition at line 551 of file setup\&.h\&.
.SS "#define wxUSE_EDITABLELISTBOX   1"

.PP
Definition at line 865 of file setup\&.h\&.
.SS "#define wxUSE_ENH_METAFILE   1"

.PP
Definition at line 1278 of file setup\&.h\&.
.SS "#define wxUSE_EXCEPTIONS   1"

.PP
Definition at line 194 of file setup\&.h\&.
.SS "#define wxUSE_EXTENDED_RTTI   0"

.PP
Definition at line 201 of file setup\&.h\&.
.SS "#define wxUSE_FFILE   1"

.PP
Definition at line 431 of file setup\&.h\&.
.SS "#define wxUSE_FILE   1"

.PP
Definition at line 430 of file setup\&.h\&.
.SS "#define wxUSE_FILE_HISTORY   1"

.PP
Definition at line 1258 of file setup\&.h\&.
.SS "#define wxUSE_FILECTRL   1"

.PP
Definition at line 866 of file setup\&.h\&.
.SS "#define wxUSE_FILEDLG   1"

.PP
Definition at line 1204 of file setup\&.h\&.
.SS "#define wxUSE_FILEPICKERCTRL   1"

.PP
Definition at line 867 of file setup\&.h\&.
.SS "#define wxUSE_FILESYSTEM   1"

.PP
Definition at line 571 of file setup\&.h\&.
.SS "#define wxUSE_FINDREPLDLG   1"

.PP
Definition at line 1211 of file setup\&.h\&.
.SS "#define wxUSE_FONTDLG   1"

.PP
Definition at line 1218 of file setup\&.h\&.
.SS "#define wxUSE_FONTENUM   1"

.PP
Definition at line 608 of file setup\&.h\&.
.SS "#define wxUSE_FONTMAP   1"

.PP
Definition at line 611 of file setup\&.h\&.
.SS "#define wxUSE_FONTPICKERCTRL   1"

.PP
Definition at line 868 of file setup\&.h\&.
.SS "#define wxUSE_FS_ARCHIVE   1"

.PP
Definition at line 577 of file setup\&.h\&.
.SS "#define wxUSE_FS_INET   1"

.PP
Definition at line 580 of file setup\&.h\&.
.SS "#define wxUSE_FS_ZIP   1"

.PP
Definition at line 574 of file setup\&.h\&.
.SS "#define wxUSE_FSVOLUME   1"

.PP
Definition at line 438 of file setup\&.h\&.
.SS "#define wxUSE_FSWATCHER   1"

.PP
Definition at line 509 of file setup\&.h\&.
.SS "#define wxUSE_GAUGE   1"

.PP
Definition at line 869 of file setup\&.h\&.
.SS "#define wxUSE_GEOMETRY   1"

.PP
Definition at line 1070 of file setup\&.h\&.
.SS "#define wxUSE_GIF   1"

.PP
Definition at line 1468 of file setup\&.h\&.
.SS "#define wxUSE_GLCANVAS   1"

.PP
Definition at line 1325 of file setup\&.h\&.
.SS "#define wxUSE_GLOBAL_MEMORY_OPERATORS   0"

.PP
Definition at line 148 of file setup\&.h\&.
.SS "#define wxUSE_GRAPHICS_CONTEXT   0"

.PP
Definition at line 788 of file setup\&.h\&.
.SS "#define wxUSE_GRID   1"

.PP
Definition at line 976 of file setup\&.h\&.
.SS "#define wxUSE_GUI   1"

.PP
Definition at line 22 of file setup\&.h\&.
.SS "#define wxUSE_HEADERCTRL   1"

.PP
Definition at line 870 of file setup\&.h\&.
.SS "#define wxUSE_HELP   1"

.PP
Definition at line 1388 of file setup\&.h\&.
.SS "#define wxUSE_HOTKEY   1"

.PP
Definition at line 1050 of file setup\&.h\&.
.SS "#define wxUSE_HTML   1"

.PP
Definition at line 1312 of file setup\&.h\&.
.SS "#define wxUSE_HYPERLINKCTRL   1"

.PP
Definition at line 871 of file setup\&.h\&.
.SS "#define wxUSE_ICO_CUR   1"

.PP
Definition at line 1483 of file setup\&.h\&.
.SS "#define wxUSE_IFF   0"

.PP
Definition at line 1477 of file setup\&.h\&.
.SS "#define wxUSE_IMAGE   1"

.PP
Definition at line 1453 of file setup\&.h\&.
.SS "#define wxUSE_IMAGLIST   1"

.PP
Definition at line 1079 of file setup\&.h\&.
.SS "#define wxUSE_INFOBAR   1"

.PP
Definition at line 1087 of file setup\&.h\&.
.SS "#define wxUSE_INICONF   0"

.PP
Definition at line 1629 of file setup\&.h\&.
.SS "#define wxUSE_INKEDIT   0"

.PP
Definition at line 1622 of file setup\&.h\&.
.SS "#define wxUSE_INTL   1"

.PP
Definition at line 456 of file setup\&.h\&.
.SS "#define wxUSE_IOSTREAMH   0"

.PP
Definition at line 385 of file setup\&.h\&.
.SS "#define wxUSE_IPC   1"

.PP
Definition at line 1386 of file setup\&.h\&.
.SS "#define wxUSE_IPV6   0"

.PP
Definition at line 568 of file setup\&.h\&.
.SS "#define wxUSE_JOYSTICK   1"

.PP
Definition at line 605 of file setup\&.h\&.
.SS "#define wxUSE_LIBJPEG   1"

.PP
Definition at line 1459 of file setup\&.h\&.
.SS "#define wxUSE_LIBPNG   1"

.PP
Definition at line 1456 of file setup\&.h\&.
.SS "#define wxUSE_LIBTIFF   1"

.PP
Definition at line 1462 of file setup\&.h\&.
.SS "#define wxUSE_LISTBOOK   1"

.PP
Definition at line 935 of file setup\&.h\&.
.SS "#define wxUSE_LISTBOX   1"

.PP
Definition at line 872 of file setup\&.h\&.
.SS "#define wxUSE_LISTCTRL   1"

.PP
Definition at line 873 of file setup\&.h\&.
.SS "#define wxUSE_LOG   1"

.PP
Definition at line 210 of file setup\&.h\&.
.SS "#define wxUSE_LOG_DIALOG   1"

.PP
Definition at line 219 of file setup\&.h\&.
.SS "#define wxUSE_LOGGUI   1"

.PP
Definition at line 216 of file setup\&.h\&.
.SS "#define wxUSE_LOGWINDOW   1"

.PP
Definition at line 213 of file setup\&.h\&.
.SS "#define wxUSE_LONGLONG   1"

.PP
Definition at line 403 of file setup\&.h\&.
.SS "#define wxUSE_MARKUP   1"

.PP
Definition at line 823 of file setup\&.h\&.
.SS "#define wxUSE_MDI   1"

.PP
Definition at line 1292 of file setup\&.h\&.
.SS "#define wxUSE_MDI_ARCHITECTURE   1"

.PP
Definition at line 1300 of file setup\&.h\&.
.SS "#define wxUSE_MEDIACTRL   1"

.PP
Definition at line 680 of file setup\&.h\&.
.SS "#define wxUSE_MEMORY_TRACING   0"

.PP
Definition at line 137 of file setup\&.h\&.
.SS "#define wxUSE_MENUS   1"

.PP
Definition at line 1094 of file setup\&.h\&.
.SS "#define wxUSE_METAFILE   1"

.PP
Definition at line 1277 of file setup\&.h\&.
.SS "#define wxUSE_MFC   0"

.PP
Definition at line 1535 of file setup\&.h\&.
.SS "#define wxUSE_MIMETYPE   1"

.PP
Definition at line 614 of file setup\&.h\&.
.SS "#define wxUSE_MINIFRAME   1"

.PP
Definition at line 983 of file setup\&.h\&.
.SS "#define wxUSE_MOUSEWHEEL   1"

.PP
Definition at line 1410 of file setup\&.h\&.
.SS "#define wxUSE_MS_HTML_HELP   1"

.PP
Definition at line 1398 of file setup\&.h\&.
.SS "#define wxUSE_MSGDLG   1"

.PP
Definition at line 1225 of file setup\&.h\&.
.SS "#define wxUSE_NATIVE_STATUSBAR   1"

.PP
Definition at line 907 of file setup\&.h\&.
.SS "#define wxUSE_NOTEBOOK   1"

.PP
Definition at line 927 of file setup\&.h\&.
.SS "#define wxUSE_NOTIFICATION_MESSAGE   1"

.PP
Definition at line 1105 of file setup\&.h\&.
.SS "#define wxUSE_NUMBERDLG   1"

.PP
Definition at line 1237 of file setup\&.h\&.
.SS "#define wxUSE_ODCOMBOBOX   1"

.PP
Definition at line 1001 of file setup\&.h\&.
.SS "#define wxUSE_OLE   1"

.PP
Definition at line 1544 of file setup\&.h\&.
.SS "#define wxUSE_OLE_AUTOMATION   1"

.PP
Definition at line 1552 of file setup\&.h\&.
.SS "#define wxUSE_ON_FATAL_EXCEPTION   1"

.PP
Definition at line 85 of file setup\&.h\&.
.SS "#define wxUSE_OWNER_DRAWN   1"

.PP
Definition at line 1607 of file setup\&.h\&.
.SS "#define wxUSE_PALETTE   1"

.PP
Definition at line 1486 of file setup\&.h\&.
.SS "#define wxUSE_PCX   1"

.PP
Definition at line 1474 of file setup\&.h\&.
.SS "#define wxUSE_PNM   1"

.PP
Definition at line 1471 of file setup\&.h\&.
.SS "#define wxUSE_POPUPWIN   1"

.PP
Definition at line 831 of file setup\&.h\&.
.SS "#define wxUSE_POSTSCRIPT   0"

.PP
Definition at line 1421 of file setup\&.h\&.
.SS "#define wxUSE_POSTSCRIPT_ARCHITECTURE_IN_MSW   1"

.PP
Definition at line 1575 of file setup\&.h\&.
.SS "#define wxUSE_PREFERENCES_EDITOR   1"

.PP
Definition at line 1115 of file setup\&.h\&.
.SS "#define wxUSE_PRINTF_POS_PARAMS   1"

.PP
Definition at line 267 of file setup\&.h\&.
.SS "#define wxUSE_PRINTING_ARCHITECTURE   1"

.PP
Definition at line 1303 of file setup\&.h\&.
.SS "#define wxUSE_PROGRESSDLG   1"

.PP
Definition at line 1228 of file setup\&.h\&.
.SS "#define wxUSE_PROPGRID   1"

.PP
Definition at line 716 of file setup\&.h\&.
.SS "#define wxUSE_PROTOCOL   1"

.PP
Definition at line 622 of file setup\&.h\&.
.SS "#define wxUSE_PROTOCOL_FILE   1"

.PP
Definition at line 625 of file setup\&.h\&.
.SS "#define wxUSE_PROTOCOL_FTP   1"

.PP
Definition at line 626 of file setup\&.h\&.
.SS "#define wxUSE_PROTOCOL_HTTP   1"

.PP
Definition at line 627 of file setup\&.h\&.
.SS "#define wxUSE_RADIOBOX   1"

.PP
Definition at line 874 of file setup\&.h\&.
.SS "#define wxUSE_RADIOBTN   1"

.PP
Definition at line 875 of file setup\&.h\&.
.SS "#define wxUSE_REARRANGECTRL   1"

.PP
Definition at line 1017 of file setup\&.h\&.
.SS "#define wxUSE_REGEX   1"

.PP
Definition at line 667 of file setup\&.h\&.
.SS "#define wxUSE_REGKEY   1"

.PP
Definition at line 1582 of file setup\&.h\&.
.SS "#define wxUSE_RIBBON   1"

.PP
Definition at line 709 of file setup\&.h\&.
.SS "#define wxUSE_RICHEDIT   1"

.PP
Definition at line 1592 of file setup\&.h\&.
.SS "#define wxUSE_RICHEDIT2   1"

.PP
Definition at line 1599 of file setup\&.h\&.
.SS "#define wxUSE_RICHMSGDLG   1"

.PP
Definition at line 876 of file setup\&.h\&.
.SS "#define wxUSE_RICHTEXT   1"

.PP
Definition at line 1333 of file setup\&.h\&.
.SS "#define wxUSE_RICHTOOLTIP   1"

.PP
Definition at line 1123 of file setup\&.h\&.
.SS "#define wxUSE_SASH   1"

.PP
Definition at line 1130 of file setup\&.h\&.
.SS "#define wxUSE_SCROLLBAR   1"

.PP
Definition at line 877 of file setup\&.h\&.
.SS "#define wxUSE_SEARCHCTRL   1"

.PP
Definition at line 878 of file setup\&.h\&.
.SS "#define wxUSE_SLIDER   1"

.PP
Definition at line 879 of file setup\&.h\&.
.SS "#define wxUSE_SNGLINST_CHECKER   1"

.PP
Definition at line 1382 of file setup\&.h\&.
.SS "#define wxUSE_SOCKETS   1"

.PP
Definition at line 557 of file setup\&.h\&.
.SS "#define wxUSE_SOUND   1"

.PP
Definition at line 673 of file setup\&.h\&.
.SS "#define wxUSE_SPINBTN   1"

.PP
Definition at line 880 of file setup\&.h\&.
.SS "#define wxUSE_SPINCTRL   1"

.PP
Definition at line 881 of file setup\&.h\&.
.SS "#define wxUSE_SPLASH   1"

.PP
Definition at line 1240 of file setup\&.h\&.
.SS "#define wxUSE_SPLINES   1"

.PP
Definition at line 1407 of file setup\&.h\&.
.SS "#define wxUSE_SPLITTER   1"

.PP
Definition at line 1137 of file setup\&.h\&.
.SS "#define wxUSE_STACKWALKER   1"

.PP
Definition at line 94 of file setup\&.h\&.
.SS "#define wxUSE_STARTUP_TIPS   1"

.PP
Definition at line 1231 of file setup\&.h\&.
.SS "#define wxUSE_STATBMP   1"

.PP
Definition at line 885 of file setup\&.h\&.
.SS "#define wxUSE_STATBOX   1"

.PP
Definition at line 882 of file setup\&.h\&.
.SS "#define wxUSE_STATLINE   1"

.PP
Definition at line 883 of file setup\&.h\&.
.SS "#define wxUSE_STATTEXT   1"

.PP
Definition at line 884 of file setup\&.h\&.
.SS "#define wxUSE_STATUSBAR   1"

.PP
Definition at line 898 of file setup\&.h\&.
.SS "#define wxUSE_STC   1"

.PP
Definition at line 723 of file setup\&.h\&.
.SS "#define wxUSE_STD_CONTAINERS   0"

.PP
Definition at line 334 of file setup\&.h\&.
.SS "#define wxUSE_STD_DEFAULT   1"

.PP
Definition at line 315 of file setup\&.h\&.
.SS "#define wxUSE_STD_IOSTREAM   \fBwxUSE_STD_DEFAULT\fP"

.PP
Definition at line 348 of file setup\&.h\&.
.SS "#define wxUSE_STD_STRING   \fBwxUSE_STD_DEFAULT\fP"

.PP
Definition at line 359 of file setup\&.h\&.
.SS "#define wxUSE_STD_STRING_CONV_IN_WXSTRING   \fBwxUSE_STL\fP"

.PP
Definition at line 374 of file setup\&.h\&.
.SS "#define wxUSE_STDPATHS   1"

.PP
Definition at line 446 of file setup\&.h\&.
.SS "#define wxUSE_STL   0"

.PP
Definition at line 300 of file setup\&.h\&.
.SS "#define wxUSE_STOPWATCH   1"

.PP
Definition at line 502 of file setup\&.h\&.
.SS "#define wxUSE_STREAMS   1"

.PP
Definition at line 252 of file setup\&.h\&.
.SS "#define wxUSE_SVG   1"

.PP
Definition at line 1428 of file setup\&.h\&.
.SS "#define wxUSE_SYSTEM_OPTIONS   1"

.PP
Definition at line 670 of file setup\&.h\&.
.SS "#define wxUSE_TARSTREAM   1"

.PP
Definition at line 589 of file setup\&.h\&.
.SS "#define wxUSE_TASKBARICON   1"

.PP
Definition at line 967 of file setup\&.h\&.
.SS "#define wxUSE_TASKBARICON_BALLOONS   1"

.PP
Definition at line 1616 of file setup\&.h\&.
.SS "#define wxUSE_TEXTBUFFER   1"

.PP
Definition at line 449 of file setup\&.h\&.
.SS "#define wxUSE_TEXTCTRL   1"

.PP
Definition at line 886 of file setup\&.h\&.
.SS "#define wxUSE_TEXTDLG   1"

.PP
Definition at line 1234 of file setup\&.h\&.
.SS "#define wxUSE_TEXTFILE   1"

.PP
Definition at line 453 of file setup\&.h\&.
.SS "#define wxUSE_TGA   1"

.PP
Definition at line 1465 of file setup\&.h\&.
.SS "#define wxUSE_THEME_GTK   0"

.PP
Definition at line 1498 of file setup\&.h\&.
.SS "#define wxUSE_THEME_METAL   0"

.PP
Definition at line 1499 of file setup\&.h\&.
.SS "#define wxUSE_THEME_MONO   0"

.PP
Definition at line 1500 of file setup\&.h\&.
.SS "#define wxUSE_THEME_WIN32   0"

.PP
Definition at line 1501 of file setup\&.h\&.
.SS "#define wxUSE_THREADS   1"

.PP
Definition at line 241 of file setup\&.h\&.
.SS "#define wxUSE_TIMEPICKCTRL   1"

.PP
Definition at line 887 of file setup\&.h\&.
.SS "#define wxUSE_TIMEPICKCTRL_GENERIC   0"

.PP
Definition at line 1649 of file setup\&.h\&.
.SS "#define wxUSE_TIMER   1"

.PP
Definition at line 495 of file setup\&.h\&.
.SS "#define wxUSE_TIPWINDOW   1"

.PP
Definition at line 839 of file setup\&.h\&.
.SS "#define wxUSE_TOGGLEBTN   1"

.PP
Definition at line 888 of file setup\&.h\&.
.SS "#define wxUSE_TOOLBAR   1"

.PP
Definition at line 916 of file setup\&.h\&.
.SS "#define wxUSE_TOOLBAR_NATIVE   1"

.PP
Definition at line 917 of file setup\&.h\&.
.SS "#define wxUSE_TOOLBOOK   1"

.PP
Definition at line 959 of file setup\&.h\&.
.SS "#define wxUSE_TOOLTIPS   1"

.PP
Definition at line 1144 of file setup\&.h\&.
.SS "#define wxUSE_TREEBOOK   1"

.PP
Definition at line 951 of file setup\&.h\&.
.SS "#define wxUSE_TREECTRL   1"

.PP
Definition at line 889 of file setup\&.h\&.
.SS "#define wxUSE_TREELISTCTRL   1"

.PP
Definition at line 890 of file setup\&.h\&.
.SS "#define wxUSE_UIACTIONSIMULATOR   1"

.PP
Definition at line 1414 of file setup\&.h\&.
.SS "#define wxUSE_UNICODE   1"

.PP
Definition at line 170 of file setup\&.h\&.
.SS "#define wxUSE_UNICODE_MSLU   0"

.PP
Definition at line 1526 of file setup\&.h\&.
.SS "#define wxUSE_URL   1"

.PP
Definition at line 630 of file setup\&.h\&.
.SS "#define wxUSE_URL_NATIVE   0"

.PP
Definition at line 640 of file setup\&.h\&.
.SS "#define wxUSE_UXTHEME   1"

.PP
Definition at line 1619 of file setup\&.h\&.
.SS "#define wxUSE_VALIDATORS   1"

.PP
Definition at line 1147 of file setup\&.h\&.
.SS "#define wxUSE_VARIANT   1"

.PP
Definition at line 649 of file setup\&.h\&.
.SS "#define wxUSE_WCHAR_T   1"

.PP
Definition at line 174 of file setup\&.h\&.
.SS "#define wxUSE_WEBVIEW   1"

.PP
Definition at line 730 of file setup\&.h\&.
.SS "#define wxUSE_WEBVIEW_IE   0"

.PP
Definition at line 740 of file setup\&.h\&.
.SS "#define wxUSE_WEBVIEW_WEBKIT   0"

.PP
Definition at line 751 of file setup\&.h\&.
.SS "#define wxUSE_WIN_METAFILES_ALWAYS   0"

.PP
Definition at line 1279 of file setup\&.h\&.
.SS "#define wxUSE_WIZARDDLG   1"

.PP
Definition at line 1243 of file setup\&.h\&.
.SS "#define wxUSE_WXDIB   1"

.PP
Definition at line 1571 of file setup\&.h\&.
.SS "#define wxUSE_WXHTML_HELP   1"

.PP
Definition at line 1402 of file setup\&.h\&.
.SS "#define wxUSE_XLOCALE   1"

.PP
Definition at line 471 of file setup\&.h\&.
.SS "#define wxUSE_XML   \fBwxUSE_XRC\fP"

.PP
Definition at line 695 of file setup\&.h\&.
.SS "#define wxUSE_XPM   1"

.PP
Definition at line 1480 of file setup\&.h\&.
.SS "#define wxUSE_XRC   1"

.PP
Definition at line 687 of file setup\&.h\&.
.SS "#define wxUSE_ZIPSTREAM   1"

.PP
Definition at line 586 of file setup\&.h\&.
.SS "#define wxUSE_ZLIB   1"

.PP
Definition at line 593 of file setup\&.h\&.
.SS "#define WXWIN_COMPATIBILITY_2_6   0"

.PP
Definition at line 37 of file setup\&.h\&.
.SS "#define WXWIN_COMPATIBILITY_2_8   1"

.PP
Definition at line 47 of file setup\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
