.TH "SF_DITHER_INFO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SF_DITHER_INFO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sndfile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBtype\fP"
.br
.ti -1c
.RI "double \fBlevel\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 371 of file sndfile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double SF_DITHER_INFO::level"

.PP
Definition at line 373 of file sndfile\&.h\&.
.SS "\fBconst\fP char * SF_DITHER_INFO::name"

.PP
Definition at line 374 of file sndfile\&.h\&.
.SS "\fBint\fP SF_DITHER_INFO::type"

.PP
Definition at line 372 of file sndfile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
