.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/sf_unistd.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/sf_unistd.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS_IRWXU\fP   0000700	/* rwx, owner */"
.br
.ti -1c
.RI "#define \fBS_IRUSR\fP   0000400	/* read \fBpermission\fP, owner */"
.br
.ti -1c
.RI "#define \fBS_IWUSR\fP   0000200	/* write \fBpermission\fP, owner */"
.br
.ti -1c
.RI "#define \fBS_IXUSR\fP   0000100	/* execute/search \fBpermission\fP, owner */"
.br
.ti -1c
.RI "#define \fBS_IRWXG\fP   0	/* rwx, group */"
.br
.ti -1c
.RI "#define \fBS_IRGRP\fP   0	/* read \fBpermission\fP, group */"
.br
.ti -1c
.RI "#define \fBS_IWGRP\fP   0	/* write \fBpermission\fP, grougroup */"
.br
.ti -1c
.RI "#define \fBS_IXGRP\fP   0	/* execute/search \fBpermission\fP, group */"
.br
.ti -1c
.RI "#define \fBS_IRWXO\fP   0	/* rwx, other */"
.br
.ti -1c
.RI "#define \fBS_IROTH\fP   0	/* read \fBpermission\fP, other */"
.br
.ti -1c
.RI "#define \fBS_IWOTH\fP   0	/* write \fBpermission\fP, other */"
.br
.ti -1c
.RI "#define \fBS_IXOTH\fP   0	/* execute/search \fBpermission\fP, other */"
.br
.ti -1c
.RI "#define \fBS_ISFIFO\fP(mode)   (((mode) & _S_IFMT) == _S_IFIFO)"
.br
.ti -1c
.RI "#define \fBS_ISREG\fP(mode)   (((mode) & _S_IFREG) == _S_IFREG)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S_IRGRP   0	/* read \fBpermission\fP, group */"

.PP
Definition at line 39 of file sf_unistd\&.h\&.
.SS "#define S_IROTH   0	/* read \fBpermission\fP, other */"

.PP
Definition at line 45 of file sf_unistd\&.h\&.
.SS "#define S_IRUSR   0000400	/* read \fBpermission\fP, owner */"

.PP
Definition at line 26 of file sf_unistd\&.h\&.
.SS "#define S_IRWXG   0	/* rwx, group */"

.PP
Definition at line 38 of file sf_unistd\&.h\&.
.SS "#define S_IRWXO   0	/* rwx, other */"

.PP
Definition at line 44 of file sf_unistd\&.h\&.
.SS "#define S_IRWXU   0000700	/* rwx, owner */"

.PP
Definition at line 22 of file sf_unistd\&.h\&.
.SS "#define S_ISFIFO(mode)   (((mode) & _S_IFMT) == _S_IFIFO)"

.PP
Definition at line 50 of file sf_unistd\&.h\&.
.SS "#define S_ISREG(mode)   (((mode) & _S_IFREG) == _S_IFREG)"

.PP
Definition at line 54 of file sf_unistd\&.h\&.
.SS "#define S_IWGRP   0	/* write \fBpermission\fP, grougroup */"

.PP
Definition at line 40 of file sf_unistd\&.h\&.
.SS "#define S_IWOTH   0	/* write \fBpermission\fP, other */"

.PP
Definition at line 46 of file sf_unistd\&.h\&.
.SS "#define S_IWUSR   0000200	/* write \fBpermission\fP, owner */"

.PP
Definition at line 30 of file sf_unistd\&.h\&.
.SS "#define S_IXGRP   0	/* execute/search \fBpermission\fP, group */"

.PP
Definition at line 41 of file sf_unistd\&.h\&.
.SS "#define S_IXOTH   0	/* execute/search \fBpermission\fP, other */"

.PP
Definition at line 47 of file sf_unistd\&.h\&.
.SS "#define S_IXUSR   0000100	/* execute/search \fBpermission\fP, owner */"

.PP
Definition at line 34 of file sf_unistd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
