.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/sha512.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/ffmpeg/libavutil/sha512.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'attributes\&.h'\fP
.br
\fC#include 'version\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct AVSHA512 * \fBav_sha512_alloc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBav_sha512_init\fP (struct AVSHA512 *\fBcontext\fP, \fBint\fP \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_sha512_update\fP (struct AVSHA512 *\fBcontext\fP, \fBconst\fP \fBuint8_t\fP *\fBdata\fP, unsigned \fBint\fP \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBav_sha512_final\fP (struct AVSHA512 *\fBcontext\fP, \fBuint8_t\fP *digest)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBint\fP \fBav_sha512_size\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
