.TH "sideinfo::granule::channel" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sideinfo::granule::channel \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBpart2_3_length\fP"
.br
.ti -1c
.RI "unsigned short \fBbig_values\fP"
.br
.ti -1c
.RI "unsigned short \fBglobal_gain\fP"
.br
.ti -1c
.RI "unsigned short \fBscalefac_compress\fP"
.br
.ti -1c
.RI "unsigned char \fBflags\fP"
.br
.ti -1c
.RI "unsigned char \fBblock_type\fP"
.br
.ti -1c
.RI "unsigned char \fBtable_select\fP [3]"
.br
.ti -1c
.RI "unsigned char \fBsubblock_gain\fP [3]"
.br
.ti -1c
.RI "unsigned char \fBregion0_count\fP"
.br
.ti -1c
.RI "unsigned char \fBregion1_count\fP"
.br
.ti -1c
.RI "unsigned char \fBscalefac\fP [39]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file layer3\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short sideinfo::granule::channel::big_values"

.PP
Definition at line 72 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::block_type"

.PP
Definition at line 77 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::flags"

.PP
Definition at line 76 of file layer3\&.c\&.
.SS "unsigned short sideinfo::granule::channel::global_gain"

.PP
Definition at line 73 of file layer3\&.c\&.
.SS "unsigned short sideinfo::granule::channel::part2_3_length"

.PP
Definition at line 71 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::region0_count"

.PP
Definition at line 80 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::region1_count"

.PP
Definition at line 81 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::scalefac[39]"

.PP
Definition at line 84 of file layer3\&.c\&.
.SS "unsigned short sideinfo::granule::channel::scalefac_compress"

.PP
Definition at line 74 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::subblock_gain[3]"

.PP
Definition at line 79 of file layer3\&.c\&.
.SS "unsigned char sideinfo::granule::channel::table_select[3]"

.PP
Definition at line 78 of file layer3\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
