.TH "sideinfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sideinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBgranule\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fBmain_data_begin\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBprivate_bits\fP"
.br
.ti -1c
.RI "unsigned char \fBscfsi\fP [2]"
.br
.ti -1c
.RI "struct \fBsideinfo::granule\fP \fBgr\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file layer3\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBsideinfo::granule\fP  sideinfo::gr[2]"

.SS "unsigned \fBint\fP sideinfo::main_data_begin"

.PP
Definition at line 63 of file layer3\&.c\&.
.SS "unsigned \fBint\fP sideinfo::private_bits"

.PP
Definition at line 64 of file layer3\&.c\&.
.SS "unsigned char sideinfo::scfsi[2]"

.PP
Definition at line 66 of file layer3\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
