.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/Silence.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/Silence.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include 'Silence\&.h'\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include '\&.\&./ShuttleGui\&.h'\fP
.br
\fC#include '\&.\&./WaveTrack\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
