.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/simd.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsoxr/src/simd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'simd\&.h'\fP
.br
\fC#include 'simd\-dev\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIMD_ALIGNMENT\fP   (sizeof(float) * 4)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fB_soxr_simd_aligned_malloc\fP (size_t \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fB_soxr_simd_aligned_calloc\fP (size_t \fBnmemb\fP, size_t \fBsize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_soxr_simd_aligned_free\fP (\fBvoid\fP *\fBp1\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_soxr_ordered_convolve_simd\fP (\fBint\fP n, \fBvoid\fP *not_used, float *\fBa\fP, \fBconst\fP float *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_soxr_ordered_partial_convolve_simd\fP (\fBint\fP n, float *\fBa\fP, \fBconst\fP float *\fBb\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIMD_ALIGNMENT   (sizeof(float) * 4)"

.PP
Definition at line 10 of file simd\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP _soxr_ordered_convolve_simd (\fBint\fP n, \fBvoid\fP * not_used, float * a, \fBconst\fP float * b)"

.PP
Definition at line 42 of file simd\&.c\&.
.SS "\fBvoid\fP _soxr_ordered_partial_convolve_simd (\fBint\fP n, float * a, \fBconst\fP float * b)"

.PP
Definition at line 65 of file simd\&.c\&.
.SS "\fBvoid\fP* _soxr_simd_aligned_calloc (size_t nmemb, size_t size)"

.PP
Definition at line 24 of file simd\&.c\&.
.SS "\fBvoid\fP _soxr_simd_aligned_free (\fBvoid\fP * p1)"

.PP
Definition at line 34 of file simd\&.c\&.
.SS "\fBvoid\fP* _soxr_simd_aligned_malloc (size_t size)"

.PP
Definition at line 12 of file simd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
