.TH "C:/_dev/OpenU/Audacity/audacity/tests/SimpleBlockFileTest.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/tests/SimpleBlockFileTest.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'blockfile/SimpleBlockFile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleBlockFileTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 191 of file SimpleBlockFileTest\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
