.TH "SimpleBlockFileCache" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleBlockFileCache \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleBlockFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBactive\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBneedWrite\fP"
.br
.ti -1c
.RI "\fBsampleFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBsamplePtr\fP \fBsampleData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBsummaryData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file SimpleBlockFile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP SimpleBlockFileCache::active"

.PP
Definition at line 22 of file SimpleBlockFile\&.h\&.
.SS "\fBsampleFormat\fP SimpleBlockFileCache::format"

.PP
Definition at line 24 of file SimpleBlockFile\&.h\&.
.SS "\fBbool\fP SimpleBlockFileCache::needWrite"

.PP
Definition at line 23 of file SimpleBlockFile\&.h\&.
.SS "\fBsamplePtr\fP SimpleBlockFileCache::sampleData"

.PP
Definition at line 25 of file SimpleBlockFile\&.h\&.
.SS "\fBvoid\fP* SimpleBlockFileCache::summaryData"

.PP
Definition at line 26 of file SimpleBlockFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
