.TH "SinCosTable" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SinCosTable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RealFFTf48x\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSinCosTable\fP ()"
.br
.ti -1c
.RI "\fB~SinCosTable\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmSinCosTablePow\fP"
.br
.ti -1c
.RI "\fBSinCosStruct\fP * \fBmSinCosTable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file RealFFTf48x\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SinCosTable::SinCosTable ()"

.SS "SinCosTable::~SinCosTable ()\fC [inline]\fP"

.PP
Definition at line 92 of file RealFFTf48x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSinCosStruct\fP* SinCosTable::mSinCosTable"

.PP
Definition at line 90 of file RealFFTf48x\&.h\&.
.SS "\fBint\fP SinCosTable::mSinCosTablePow"

.PP
Definition at line 89 of file RealFFTf48x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
