.TH "SkewedRuler" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkewedRuler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SkewedRuler\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 18 of file SkewedRuler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
