.TH "SliderDialog" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliderDialog \- Pop up dialog used with an \fBLWSlider\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ASlider\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSliderDialog\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxString &title, wxPoint \fBposition\fP, wxSize \fBsize\fP, \fBint\fP style, float \fBvalue\fP, float \fBline\fP, float page)"
.br
.ti -1c
.RI "\fB~SliderDialog\fP ()"
.br
.ti -1c
.RI "float \fBGet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pop up dialog used with an \fBLWSlider\fP\&. 
.PP
Definition at line 320 of file ASlider\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SliderDialog::SliderDialog (wxWindow * parent, wxWindowID id, \fBconst\fP wxString & title, wxPoint position, wxSize size, \fBint\fP style, float value, float line, float page)"

.PP
Definition at line 184 of file ASlider\&.cpp\&.
.SS "SliderDialog::~SliderDialog ()"

.PP
Definition at line 224 of file ASlider\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "float SliderDialog::Get ()"

.PP
Definition at line 255 of file ASlider\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
