.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sliderdata.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sliderdata.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sliderdata\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset_slider\fP (\fBint\fP index, float \fBvalue\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBslider_array\fP [\fBSLIDERS_MAX\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP set_slider (\fBint\fP index, float value)"

.PP
Definition at line 11 of file sliderdata\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "float slider_array[\fBSLIDERS_MAX\fP]"

.PP
Definition at line 9 of file sliderdata\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
