.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/smallft.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/smallft.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'smallft\&.h'\fP
.br
\fC#include 'os\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdrft_forward\fP (\fBdrft_lookup\fP *\fBl\fP, float *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdrft_backward\fP (\fBdrft_lookup\fP *\fBl\fP, float *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdrft_init\fP (\fBdrft_lookup\fP *\fBl\fP, \fBint\fP n)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdrft_clear\fP (\fBdrft_lookup\fP *\fBl\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP drft_backward (\fBdrft_lookup\fP * l, float * data)"

.PP
Definition at line 1237 of file smallft\&.c\&.
.SS "\fBvoid\fP drft_clear (\fBdrft_lookup\fP * l)"

.PP
Definition at line 1249 of file smallft\&.c\&.
.SS "\fBvoid\fP drft_forward (\fBdrft_lookup\fP * l, float * data)"

.PP
Definition at line 1232 of file smallft\&.c\&.
.SS "\fBvoid\fP drft_init (\fBdrft_lookup\fP * l, \fBint\fP n)"

.PP
Definition at line 1242 of file smallft\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
