.TH "SnapManager" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SnapManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Snap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapManager\fP (\fBTrackList\fP *tracks, \fBconst\fP \fBZoomInfo\fP *zoomInfo, \fBconst\fP TrackClipArray *clipExclusions=\fBNULL\fP, \fBconst\fP TrackArray *trackExclusions=\fBNULL\fP, \fBbool\fP noTimeSnap=\fBfalse\fP, \fBint\fP pixelTolerance=\fBkPixelTolerance\fP)"
.br
.ti -1c
.RI "\fB~SnapManager\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBSnap\fP (\fBTrack\fP *currentTrack, double \fBt\fP, \fBbool\fP rightEdge, double *outT, \fBbool\fP *snappedPoint, \fBbool\fP *snappedTime)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static wxArrayString \fBGetSnapLabels\fP ()"
.br
.ti -1c
.RI "static wxArrayString \fBGetSnapValues\fP ()"
.br
.ti -1c
.RI "static \fBconst\fP wxString & \fBGetSnapValue\fP (\fBint\fP index)"
.br
.ti -1c
.RI "static \fBint\fP \fBGetSnapIndex\fP (\fBconst\fP wxString &\fBvalue\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file Snap\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SnapManager::SnapManager (\fBTrackList\fP * tracks, \fBconst\fP \fBZoomInfo\fP * zoomInfo, \fBconst\fP TrackClipArray * clipExclusions = \fC\fBNULL\fP\fP, \fBconst\fP TrackArray * trackExclusions = \fC\fBNULL\fP\fP, \fBbool\fP noTimeSnap = \fC\fBfalse\fP\fP, \fBint\fP pixelTolerance = \fC\fBkPixelTolerance\fP\fP)"

.PP
Definition at line 30 of file Snap\&.cpp\&.
.SS "SnapManager::~SnapManager ()"

.PP
Definition at line 58 of file Snap\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP SnapManager::GetSnapIndex (\fBconst\fP wxString & value)\fC [static]\fP"

.PP
Definition at line 383 of file Snap\&.cpp\&.
.SS "wxArrayString SnapManager::GetSnapLabels ()\fC [static]\fP"

.PP
Definition at line 349 of file Snap\&.cpp\&.
.SS "\fBconst\fP wxString & SnapManager::GetSnapValue (\fBint\fP index)\fC [static]\fP"

.PP
Definition at line 371 of file Snap\&.cpp\&.
.SS "wxArrayString SnapManager::GetSnapValues ()\fC [static]\fP"

.PP
Definition at line 360 of file Snap\&.cpp\&.
.SS "\fBbool\fP SnapManager::Snap (\fBTrack\fP * currentTrack, double t, \fBbool\fP rightEdge, double * outT, \fBbool\fP * snappedPoint, \fBbool\fP * snappedTime)"

.PP
Definition at line 313 of file Snap\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
