.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/sndfile.cc" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/sndfile.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <octave/oct\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFOUR_GIG\fP   (0x100000000LL)"
.br
.ti -1c
.RI "#define \fBBUFFER_FRAMES\fP   8192"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDEFUN_DLD\fP (sfversion, args, nargout,'\-*\- texinfo \-*\-\\n\\
@deftypefn {Loadable \fBFunction\fP} {@var{\fBversion\fP} =} sfversion ()\\n\\
@cindex Reading sound files\\n\\
Return \fBa\fP \fBstring\fP containing \fBthe\fP libsndfile version\&.\\n\\
@seealso{sfread, \fBsfwrite\fP}\\n\\
@\fBend\fP deftypefn')"
.br
.ti -1c
.RI "\fBDEFUN_DLD\fP (sfread, args, nargout,'\-*\- texinfo \-*\-\\n\\
@deftypefn {Loadable \fBFunction\fP} {@var{\fBdata\fP},@var{srate},@var{\fBformat\fP} =} sfread (@var{\fBfilename\fP})\\n\\
@cindex Reading sound files\\n\\
Read \fBa\fP sound file \fBfrom\fP disk using libsndfile\&.\\n\\
@seealso{sfversion, \fBsfwrite\fP}\\n\\
@\fBend\fP deftypefn')"
.br
.ti -1c
.RI "\fBDEFUN_DLD\fP (\fBsfwrite\fP, args, nargout,'\-*\- texinfo \-*\-\\n\\
@deftypefn {\fBFunction\fP File} \fBsfwrite\fP (@var{\fBfilename\fP},@var{\fBdata\fP},@var{srate},@var{\fBformat\fP})\\n\\
Write \fBa\fP sound file to disk using libsndfile\&.\\n\\
@seealso{sfread, sfversion}\\n\\
@\fBend\fP deftypefn\\n\\
')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_FRAMES   8192"

.PP
Definition at line 24 of file sndfile\&.cc\&.
.SS "#define FOUR_GIG   (0x100000000LL)"

.PP
Definition at line 23 of file sndfile\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "DEFUN_DLD (sfversion, args, nargout, '\-*\- texinfo \-*\-\\n\\@deftypefn {Loadable \fBFunction\fP} {@var{\fBversion\fP} =} sfversion ()\\n\\@cindex Reading sound files\\n\\Return \fBa\fP \fBstring\fP containing \fBthe\fP libsndfile version\&.\\n\\@seealso{sfread, \fBsfwrite\fP}\\n\\@\fBend\fP deftypefn')"

.PP
Definition at line 31 of file sndfile\&.cc\&.
.SS "DEFUN_DLD (sfread, args, nargout, '\-*\- texinfo \-*\-\\n\\@deftypefn {Loadable \fBFunction\fP} {@var{\fBdata\fP},@var{srate},@var{\fBformat\fP} =} sfread (@var{\fBfilename\fP})\\n\\@cindex Reading sound files\\n\\Read \fBa\fP sound file \fBfrom\fP disk using libsndfile\&.\\n\\@seealso{sfversion, \fBsfwrite\fP}\\n\\@\fBend\fP deftypefn')"

.PP
Definition at line 56 of file sndfile\&.cc\&.
.SS "DEFUN_DLD (\fBsfwrite\fP, args, nargout, '\-*\- texinfo \-*\-\\n\\@deftypefn {\fBFunction\fP File} \fBsfwrite\fP (@var{\fBfilename\fP},@var{\fBdata\fP},@var{srate},@var{\fBformat\fP})\\n\\Write \fBa\fP sound file to disk using libsndfile\&.\\n\\@seealso{sfread, sfversion}\\n\\@\fBend\fP deftypefn\\n\\')"

.PP
Definition at line 132 of file sndfile\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
