.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/regtest/sndfile-regtest.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/regtest/sndfile-regtest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sndfile\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 113 of file sndfile\-regtest\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
