.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/sndfile_save.m" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/Octave/sndfile_save.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBsndfile_save\fP (\fBfilename\fP, \fBdata\fP, \fBfs\fP) \fBif\fP nargin!"
.br
.ti -1c
.RI "\fBfunction\fP \fBerror\fP ('Need three input arguments: \fBfilename\fP, \fBdata\fP and fs\&.')"
.br
.ti -1c
.RI "\fBendif\fP \fBif\fP (!isstr(\fBfilename\fP))"
.br
.ti -1c
.RI "\fBendif\fP \fBerror\fP ('First parameter '\fBfilename\fP' is must be \fBa\fP string\&.')"
.br
.ti -1c
.RI "\fBendif\fP \fBif\fP (\fBmax\fP(\fBsize\fP(\fBfs\fP)) > 1)"
.br
.ti -1c
.RI "\fBendif\fP \fBerror\fP ('Second parameter '\fBfs\fP' must be \fBa\fP single \fBvalue\fP, not an array or matrix\&.')"
.br
.ti -1c
.RI "\fBif\fP (nr > nc)"
.br
.ti -1c
.RI "\fBeval\fP (\fBstr\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBendif\fP [nr nc] = \fBsize\fP (\fBdata\fP)"
.br
.ti -1c
.RI "\fBdata\fP = \fBdata\fP'"
.br
.ti -1c
.RI "\fBendif\fP \fBsamplerate\fP = \fBfs\fP"
.br
.ti -1c
.RI "\fBwavedata\fP = \fBdata\fP"
.br
.ti -1c
.RI "\fBstr\fP = sprintf ('save \-mat\-\fBbinary\fP %\fBs\fP \fBsamplerate\fP \fBwavedata\fP', filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP error ('Need three input arguments: filename, \fBdata\fP and fs\&.')"

.SS "\fBendif\fP error ('First parameter '\fBfilename\fP' is must be \fBa\fP string\&.')"

.SS "\fBendif\fP error ('Second parameter '\fBfs\fP' must be \fBa\fP single value, not an array or matrix\&.')"

.SS "eval (\fBstr\fP)"

.SS "\fBendif\fP if (! isstrfilename)"

.SS "\fBendif\fP if (\fBmax\fP(\fBsize\fP(\fBfs\fP)), 1)"

.SS "if (nr, nc)"

.SS "\fBfunction\fP sndfile_save (\fBfilename\fP, \fBdata\fP, \fBfs\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBdata\fP = \fBdata\fP'"

.PP
Definition at line 43 of file sndfile_save\&.m\&.
.SS "endif[nr nc] = \fBsize\fP (\fBdata\fP)"

.PP
Definition at line 40 of file sndfile_save\&.m\&.
.SS "\fBendif\fP samplerate = \fBfs\fP"

.PP
Definition at line 46 of file sndfile_save\&.m\&.
.SS "str = sprintf ('save \-mat\-\fBbinary\fP %\fBs\fP \fBsamplerate\fP \fBwavedata\fP', filename)"

.PP
Definition at line 49 of file sndfile_save\&.m\&.
.SS "wavedata = \fBdata\fP"

.PP
Definition at line 47 of file sndfile_save\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
