.TH "snding_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snding_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBsnding_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBevent_type\fP \fBevent_ptr\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpitch\fP"
.br
.ti -1c
.RI "\fBint\fP \fBchannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file seqmread\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP snding_struct::channel"

.PP
Definition at line 43 of file seqmread\&.c\&.
.SS "\fBevent_type\fP snding_struct::event_ptr"

.PP
Definition at line 41 of file seqmread\&.c\&.
.SS "struct \fBsnding_struct\fP* snding_struct::next"

.PP
Definition at line 40 of file seqmread\&.c\&.
.SS "\fBint\fP snding_struct::pitch"

.PP
Definition at line 42 of file seqmread\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
