.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sndmax.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sndmax.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'sndmax\&.h'\fP
.br
\fC#include 'extern\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBsound_max\fP (\fBLVAL\fP snd_expr, long n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double sound_max (\fBLVAL\fP snd_expr, long n)"

.PP
Definition at line 21 of file sndmax\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
