.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sndwrite.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/sndwrite.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'switches\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'userio\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'sndwrite\&.h'\fP
.br
\fC#include 'extern\&.h'\fP
.br
\fC#include 'snd\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsound_state_node\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBD\fP   \fBif\fP (0)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsound_state_node\fP * \fBsound_state_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsample_type\fP \fBsound_save_sound\fP (\fBLVAL\fP s_as_lval, long n, snd_type snd, char *\fBbuf\fP, long *ntotal, snd_type player)"
.br
.ti -1c
.RI "\fBsample_type\fP \fBsound_save_array\fP (\fBLVAL\fP \fBsa\fP, long n, snd_type snd, char *\fBbuf\fP, long *ntotal, snd_type player)"
.br
.ti -1c
.RI "unsigned char \fBst_linear_to_ulaw\fP (\fBint\fP sample)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBprepare_audio\fP (\fBLVAL\fP play, snd_type snd, snd_type player)"
.br
.ti -1c
.RI "\fBvoid\fP \fBfinish_audio\fP (snd_type player)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite_to_audio\fP (snd_type player, \fBvoid\fP *\fBbuf\fP, long buflen)"
.br
.ti -1c
.RI "double \fBsound_save\fP (\fBLVAL\fP snd_expr, long n, unsigned char *\fBfilename\fP, long \fBformat\fP, long mode, long \fBbits\fP, long swap, double *sr, long *nchans, double *duration, \fBLVAL\fP play)"
.br
.ti -1c
.RI "double \fBsound_overwrite\fP (\fBLVAL\fP snd_expr, long n, unsigned char *\fBfilename\fP, long byte_offset, long header, long mode, long \fBbits\fP, long swap, double sr, long nchans, double *duration)"
.br
.ti -1c
.RI "cvtfn_type \fBfind_cvt_to_fn\fP (snd_type snd, char *\fBbuf\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsndwrite_trace\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define D   \fBif\fP (0)"

.PP
Definition at line 43 of file sndwrite\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef  struct \fBsound_state_node\fP * \fBsound_state_type\fP"

.SH "Function Documentation"
.PP 
.SS "cvtfn_type find_cvt_to_fn (snd_type snd, char * buf)"

.PP
Definition at line 353 of file sndwrite\&.c\&.
.SS "\fBvoid\fP finish_audio (snd_type player)"

.PP
Definition at line 100 of file sndwrite\&.c\&.
.SS "\fBLVAL\fP prepare_audio (\fBLVAL\fP play, snd_type snd, snd_type player)"

.PP
Definition at line 65 of file sndwrite\&.c\&.
.SS "double sound_overwrite (\fBLVAL\fP snd_expr, long n, unsigned char * filename, long byte_offset, long header, long mode, long bits, long swap, double sr, long nchans, double * duration)"

.PP
Definition at line 229 of file sndwrite\&.c\&.
.SS "double sound_save (\fBLVAL\fP snd_expr, long n, unsigned char * filename, long format, long mode, long bits, long swap, double * sr, long * nchans, double * duration, \fBLVAL\fP play)"

.PP
Definition at line 132 of file sndwrite\&.c\&.
.SS "\fBsample_type\fP sound_save_array (\fBLVAL\fP sa, long n, snd_type snd, char * buf, long * ntotal, snd_type player)"

.PP
Definition at line 468 of file sndwrite\&.c\&.
.SS "\fBsample_type\fP sound_save_sound (\fBLVAL\fP s_as_lval, long n, snd_type snd, char * buf, long * ntotal, snd_type player)"

.PP
Definition at line 375 of file sndwrite\&.c\&.
.SS "unsigned char st_linear_to_ulaw (\fBint\fP sample)"

.SS "\fBvoid\fP write_to_audio (snd_type player, \fBvoid\fP * buf, long buflen)"

.PP
Definition at line 115 of file sndwrite\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP sndwrite_trace = 0"

.PP
Definition at line 45 of file sndwrite\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
