.TH "SordResourceMetadata" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SordResourceMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sord_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBrefs_as_obj\fP"
.br
.RI "\fIReferences as a quad object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Resource node metadata 
.PP
Definition at line 26 of file sord_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t SordResourceMetadata::refs_as_obj"

.PP
References as a quad object\&. 
.PP
Definition at line 27 of file sord_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
