.TH "Sord::Namespaces" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sord::Namespaces \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sordmm\&.hpp>\fP
.PP
Inherits \fBSord::Wrapper< SerdEnv * >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamespaces\fP ()"
.br
.ti -1c
.RI "\fB~Namespaces\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd\fP (\fBconst\fP \fBstd::string\fP &\fBname\fP, \fBconst\fP \fBstd::string\fP &\fBuri\fP)"
.br
.ti -1c
.RI "\fBstd::string\fP \fBqualify\fP (\fBstd::string\fP \fBuri\fP) \fBconst\fP "
.br
.ti -1c
.RI "\fBstd::string\fP \fBexpand\fP (\fBconst\fP \fBstd::string\fP &curie) \fBconst\fP "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSerdNode\fP \fBstring_to_node\fP (\fBSerdType\fP type, \fBconst\fP \fBstd::string\fP &\fBs\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Collection of RDF namespaces with prefixes\&. 
.PP
Definition at line 64 of file sordmm\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sord::Namespaces::Namespaces ()\fC [inline]\fP"

.PP
Definition at line 66 of file sordmm\&.hpp\&.
.SS "Sord::Namespaces::~Namespaces ()\fC [inline]\fP"

.PP
Definition at line 67 of file sordmm\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Sord::Namespaces::add (\fBconst\fP \fBstd::string\fP & name, \fBconst\fP \fBstd::string\fP & uri)\fC [inline]\fP"

.PP
Definition at line 75 of file sordmm\&.hpp\&.
.SS "\fBstd::string\fP Sord::Namespaces::expand (\fBconst\fP \fBstd::string\fP & curie) const\fC [inline]\fP"

.PP
Definition at line 94 of file sordmm\&.hpp\&.
.SS "\fBstd::string\fP Sord::Namespaces::qualify (\fBstd::string\fP uri) const\fC [inline]\fP"

.PP
Definition at line 82 of file sordmm\&.hpp\&.
.SS "static \fBSerdNode\fP Sord::Namespaces::string_to_node (\fBSerdType\fP type, \fBconst\fP \fBstd::string\fP & s)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 69 of file sordmm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
