.TH "SordIterImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SordIterImpl \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBSordModel\fP * \fBsord\fP"
.br
.RI "\fIModel being iterated over\&. \fP"
.ti -1c
.RI "\fBZixTreeIter\fP * \fBcur\fP"
.br
.RI "\fICurrent DB cursor\&. \fP"
.ti -1c
.RI "\fBSordQuad\fP \fBpat\fP"
.br
.RI "\fIPattern (in ordering order) \fP"
.ti -1c
.RI "\fBint\fP \fBordering\fP [\fBTUP_LEN\fP]"
.br
.RI "\fIStore ordering\&. \fP"
.ti -1c
.RI "\fBSearchMode\fP \fBmode\fP"
.br
.RI "\fIIteration mode\&. \fP"
.ti -1c
.RI "\fBint\fP \fBn_prefix\fP"
.br
.RI "\fIPrefix for RANGE and FILTER_RANGE\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBend\fP"
.br
.RI "\fITrue iff reached end\&. \fP"
.ti -1c
.RI "\fBbool\fP \fBskip_graphs\fP"
.br
.RI "\fIIteration should ignore graphs\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Iterator over some range of a store 
.PP
Definition at line 134 of file sord\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBZixTreeIter\fP* SordIterImpl::cur"

.PP
Current DB cursor\&. 
.PP
Definition at line 136 of file sord\&.c\&.
.SS "\fBbool\fP SordIterImpl::end"

.PP
True iff reached end\&. 
.PP
Definition at line 141 of file sord\&.c\&.
.SS "\fBSearchMode\fP SordIterImpl::mode"

.PP
Iteration mode\&. 
.PP
Definition at line 139 of file sord\&.c\&.
.SS "\fBint\fP SordIterImpl::n_prefix"

.PP
Prefix for RANGE and FILTER_RANGE\&. 
.PP
Definition at line 140 of file sord\&.c\&.
.SS "\fBint\fP SordIterImpl::ordering[\fBTUP_LEN\fP]"

.PP
Store ordering\&. 
.PP
Definition at line 138 of file sord\&.c\&.
.SS "\fBSordQuad\fP SordIterImpl::pat"

.PP
Pattern (in ordering order) 
.PP
Definition at line 137 of file sord\&.c\&.
.SS "\fBbool\fP SordIterImpl::skip_graphs"

.PP
Iteration should ignore graphs\&. 
.PP
Definition at line 142 of file sord\&.c\&.
.SS "\fBconst\fP \fBSordModel\fP* SordIterImpl::sord"

.PP
Model being iterated over\&. 
.PP
Definition at line 135 of file sord\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
