.TH "Sord::Curie" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sord::Curie \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sordmm\&.hpp>\fP
.PP
Inherits \fBSord::Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCurie\fP (\fBWorld\fP &world, \fBconst\fP \fBstd::string\fP &\fBs\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 237 of file sordmm\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sord::Curie::Curie (\fBWorld\fP & world, \fBconst\fP \fBstd::string\fP & s)\fC [inline]\fP"

.PP
Definition at line 239 of file sordmm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
