.TH "Sord::Node" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sord::Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sordmm\&.hpp>\fP
.PP
Inherits \fBSord::Wrapper< SordNode * >\fP\&.
.PP
Inherited by \fBSord::Curie\fP, \fBSord::Literal\fP, and \fBSord::URI\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBUNKNOWN\fP = 0, \fBURI\fP = SORD_URI, \fBBLANK\fP = SORD_BLANK, \fBLITERAL\fP = SORD_LITERAL }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.ti -1c
.RI "\fBNode\fP (\fBWorld\fP &world, \fBType\fP \fBt\fP, \fBconst\fP \fBstd::string\fP &\fBs\fP)"
.br
.ti -1c
.RI "\fBNode\fP (\fBWorld\fP &world)"
.br
.ti -1c
.RI "\fBNode\fP (\fBWorld\fP &world, \fBconst\fP \fBSordNode\fP *\fBnode\fP)"
.br
.ti -1c
.RI "\fBNode\fP (\fBWorld\fP &world, \fBSordNode\fP *\fBnode\fP, \fBbool\fP copy=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBNode\fP (\fBconst\fP \fBNode\fP &other)"
.br
.ti -1c
.RI "\fB~Node\fP ()"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP \fBSordNode\fP * \fBget_node\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBSordNode\fP * \fBget_node\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBSerdNode\fP * \fBto_serd_node\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBis_valid\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBconst\fP \fBNode\fP &other) \fBconst\fP "
.br
.ti -1c
.RI "\fBNode\fP & \fBoperator=\fP (\fBconst\fP \fBNode\fP &other)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBNode\fP &other) \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP \fBuint8_t\fP * \fBto_u_string\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP char * \fBto_c_string\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBstd::string\fP \fBto_string\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_literal_type\fP (\fBconst\fP char *type_uri) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_uri\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_blank\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_int\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_float\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBis_bool\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBint\fP \fBto_int\fP () \fBconst\fP "
.br
.ti -1c
.RI "float \fBto_float\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBto_bool\fP () \fBconst\fP "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNode\fP \fBblank_id\fP (\fBWorld\fP &world, \fBconst\fP \fBstd::string\fP \fBbase\fP='b')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An RDF \fBNode\fP (resource, literal, etc) 
.PP
Definition at line 139 of file sordmm\&.hpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSord::Node::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUNKNOWN \fP\fP
.TP
\fB\fIURI \fP\fP
.TP
\fB\fIBLANK \fP\fP
.TP
\fB\fILITERAL \fP\fP
.PP
Definition at line 141 of file sordmm\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sord::Node::Node ()\fC [inline]\fP"

.PP
Definition at line 148 of file sordmm\&.hpp\&.
.SS "Sord::Node::Node (\fBWorld\fP & world, \fBType\fP t, \fBconst\fP \fBstd::string\fP & s)\fC [inline]\fP"

.PP
Definition at line 274 of file sordmm\&.hpp\&.
.SS "Sord::Node::Node (\fBWorld\fP & world)\fC [inline]\fP"

.PP
Definition at line 298 of file sordmm\&.hpp\&.
.SS "Sord::Node::Node (\fBWorld\fP & world, \fBconst\fP \fBSordNode\fP * node)\fC [inline]\fP"

.PP
Definition at line 306 of file sordmm\&.hpp\&.
.SS "Sord::Node::Node (\fBWorld\fP & world, \fBSordNode\fP * node, \fBbool\fP copy = \fC\fBfalse\fP\fP)\fC [inline]\fP"

.PP
Definition at line 313 of file sordmm\&.hpp\&.
.SS "Sord::Node::Node (\fBconst\fP \fBNode\fP & other)\fC [inline]\fP"

.PP
Definition at line 320 of file sordmm\&.hpp\&.
.SS "Sord::Node::~Node ()\fC [inline]\fP"

.PP
Definition at line 332 of file sordmm\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBNode\fP Sord::Node::blank_id (\fBWorld\fP & world, \fBconst\fP \fBstd::string\fP base = \fC'b'\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 209 of file sordmm\&.hpp\&.
.SS "\fBconst\fP \fBSordNode\fP* Sord::Node::get_node () const\fC [inline]\fP"

.PP
Definition at line 161 of file sordmm\&.hpp\&.
.SS "\fBSordNode\fP* Sord::Node::get_node ()\fC [inline]\fP"

.PP
Definition at line 162 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_blank () const\fC [inline]\fP"

.PP
Definition at line 200 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_bool () const\fC [inline]\fP"

.PP
Definition at line 203 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_float () const\fC [inline]\fP"

.PP
Definition at line 202 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_int () const\fC [inline]\fP"

.PP
Definition at line 201 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_literal_type (\fBconst\fP char * type_uri) const\fC [inline]\fP"

.PP
Definition at line 358 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_uri () const\fC [inline]\fP"

.PP
Definition at line 199 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::is_valid () const\fC [inline]\fP"

.PP
Definition at line 168 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::operator< (\fBconst\fP \fBNode\fP & other) const\fC [inline]\fP"

.PP
Definition at line 170 of file sordmm\&.hpp\&.
.SS "\fBNode\fP& Sord::Node::operator= (\fBconst\fP \fBNode\fP & other)\fC [inline]\fP"

.PP
Definition at line 178 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::operator== (\fBconst\fP \fBNode\fP & other) const\fC [inline]\fP"

.PP
Definition at line 189 of file sordmm\&.hpp\&.
.SS "\fBbool\fP Sord::Node::to_bool () const\fC [inline]\fP"

.PP
Definition at line 386 of file sordmm\&.hpp\&.
.SS "\fBconst\fP char * Sord::Node::to_c_string () const\fC [inline]\fP"

.PP
Definition at line 346 of file sordmm\&.hpp\&.
.SS "float Sord::Node::to_float () const\fC [inline]\fP"

.PP
Definition at line 378 of file sordmm\&.hpp\&.
.SS "\fBint\fP Sord::Node::to_int () const\fC [inline]\fP"

.PP
Definition at line 370 of file sordmm\&.hpp\&.
.SS "\fBconst\fP \fBSerdNode\fP* Sord::Node::to_serd_node ()\fC [inline]\fP"

.PP
Definition at line 164 of file sordmm\&.hpp\&.
.SS "\fBstd::string\fP Sord::Node::to_string () const\fC [inline]\fP"

.PP
Definition at line 340 of file sordmm\&.hpp\&.
.SS "\fBconst\fP \fBuint8_t\fP * Sord::Node::to_u_string () const\fC [inline]\fP"

.PP
Definition at line 352 of file sordmm\&.hpp\&.
.SS "\fBType\fP Sord::Node::type () const\fC [inline]\fP"

.PP
Definition at line 157 of file sordmm\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
