.TH "soundtouch::AAFilter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soundtouch::AAFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AAFilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAAFilter\fP (\fBuint\fP \fBlength\fP)"
.br
.ti -1c
.RI "\fB~AAFilter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCutoffFreq\fP (double newCutoffFreq)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetLength\fP (\fBuint\fP newLength)"
.br
.RI "\fISets number of FIR filter taps, i\&.e\&. ~filter complexity\&. \fP"
.ti -1c
.RI "\fBuint\fP \fBgetLength\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBuint\fP \fBevaluate\fP (\fBSAMPLETYPE\fP *dest, \fBconst\fP \fBSAMPLETYPE\fP *src, \fBuint\fP numSamples, \fBuint\fP numChannels) \fBconst\fP "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcalculateCoeffs\fP ()"
.br
.RI "\fICalculate the FIR coefficients realizing the given cutoff-frequency\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "class \fBFIRFilter\fP * \fBpFIR\fP"
.br
.ti -1c
.RI "double \fBcutoffFreq\fP"
.br
.RI "\fILow-pass filter cut-off frequency, negative = invalid\&. \fP"
.ti -1c
.RI "\fBuint\fP \fBlength\fP"
.br
.RI "\fInum of filter taps \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file AAFilter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AAFilter::AAFilter (\fBuint\fP length)"

.PP
Definition at line 61 of file AAFilter\&.cpp\&.
.SS "AAFilter::~AAFilter ()"

.PP
Definition at line 70 of file AAFilter\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP AAFilter::calculateCoeffs ()\fC [protected]\fP"

.PP
Calculate the FIR coefficients realizing the given cutoff-frequency\&. 
.PP
Definition at line 98 of file AAFilter\&.cpp\&.
.SS "\fBuint\fP AAFilter::evaluate (\fBSAMPLETYPE\fP * dest, \fBconst\fP \fBSAMPLETYPE\fP * src, \fBuint\fP numSamples, \fBuint\fP numChannels) const"
Applies the filter to the given sequence of samples\&. Note : The amount of outputted samples is by value of 'filter length' smaller than the amount of input samples\&. 
.PP
Definition at line 175 of file AAFilter\&.cpp\&.
.SS "\fBuint\fP AAFilter::getLength () const"

.PP
Definition at line 181 of file AAFilter\&.cpp\&.
.SS "\fBvoid\fP AAFilter::setCutoffFreq (double newCutoffFreq)"
Sets new anti-alias filter cut-off edge frequency, scaled to sampling frequency (nyquist frequency = 0\&.5)\&. The filter will cut off the frequencies than that\&. 
.PP
Definition at line 80 of file AAFilter\&.cpp\&.
.SS "\fBvoid\fP AAFilter::setLength (\fBuint\fP newLength)"

.PP
Sets number of FIR filter taps, i\&.e\&. ~filter complexity\&. 
.PP
Definition at line 89 of file AAFilter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double soundtouch::AAFilter::cutoffFreq\fC [protected]\fP"

.PP
Low-pass filter cut-off frequency, negative = invalid\&. 
.PP
Definition at line 58 of file AAFilter\&.h\&.
.SS "\fBuint\fP soundtouch::AAFilter::length\fC [protected]\fP"

.PP
num of filter taps 
.PP
Definition at line 61 of file AAFilter\&.h\&.
.SS "class \fBFIRFilter\fP* soundtouch::AAFilter::pFIR\fC [protected]\fP"

.PP
Definition at line 55 of file AAFilter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
