.TH "C:/_dev/OpenU/Audacity/audacity/src/SoundActivatedRecord.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/SoundActivatedRecord.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Audacity\&.h'\fP
.br
\fC#include 'SoundActivatedRecord\&.h'\fP
.br
\fC#include 'ShuttleGui\&.h'\fP
.br
\fC#include 'ShuttlePrefs\&.h'\fP
.br
\fC#include 'Prefs\&.h'\fP
.br
\fC#include 'prefs/GUISettings\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
