.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch/SoundTouch.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch/SoundTouch.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'SoundTouch\&.h'\fP
.br
\fC#include 'TDStretch\&.h'\fP
.br
\fC#include 'RateTransposer\&.h'\fP
.br
\fC#include 'cpu_detect\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_FLOAT_EQUAL\fP(\fBa\fP,  \fBb\fP)   (fabs(\fBa\fP \- \fBb\fP) < 1e\-10)"
.br
.RI "\fItest if two floating point numbers are equal \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsoundtouch_ac_test\fP ()"
.br
.RI "\fIPrint library version string for autoconf\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEST_FLOAT_EQUAL(\fBa\fP, \fBb\fP)   (fabs(\fBa\fP \- \fBb\fP) < 1e\-10)"

.PP
test if two floating point numbers are equal 
.PP
Definition at line 86 of file SoundTouch\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP soundtouch_ac_test ()"

.PP
Print library version string for autoconf\&. 
.PP
Definition at line 90 of file SoundTouch\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
