.TH "soxr" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soxr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnum_channels\fP"
.br
.ti -1c
.RI "double \fBio_ratio\fP"
.br
.ti -1c
.RI "\fBsoxr_error_t\fP \fBerror\fP"
.br
.ti -1c
.RI "\fBsoxr_quality_spec_t\fP \fBq_spec\fP"
.br
.ti -1c
.RI "\fBsoxr_io_spec_t\fP \fBio_spec\fP"
.br
.ti -1c
.RI "\fBsoxr_runtime_spec_t\fP \fBruntime_spec\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBinput_fn_state\fP"
.br
.ti -1c
.RI "\fBsoxr_input_fn_t\fP \fBinput_fn\fP"
.br
.ti -1c
.RI "size_t \fBmax_ilen\fP"
.br
.ti -1c
.RI "\fBresampler_shared_t\fP \fBshared\fP"
.br
.ti -1c
.RI "\fBresampler_t\fP * \fBresamplers\fP"
.br
.ti -1c
.RI "\fBcontrol_block_t\fP \fBcontrol_block\fP"
.br
.ti -1c
.RI "\fBdeinterleave_t\fP \fBdeinterleave\fP"
.br
.ti -1c
.RI "\fBinterleave_t\fP \fBinterleave\fP"
.br
.ti -1c
.RI "\fBvoid\fP ** \fBchannel_ptrs\fP"
.br
.ti -1c
.RI "size_t \fBclips\fP"
.br
.ti -1c
.RI "unsigned long \fBseed\fP"
.br
.ti -1c
.RI "\fBint\fP \fBflushing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file soxr\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* * soxr::channel_ptrs"

.PP
Definition at line 62 of file soxr\&.c\&.
.SS "size_t soxr::clips"

.PP
Definition at line 63 of file soxr\&.c\&.
.SS "\fBcontrol_block_t\fP soxr::control_block"

.PP
Definition at line 58 of file soxr\&.c\&.
.SS "\fBdeinterleave_t\fP soxr::deinterleave"

.PP
Definition at line 59 of file soxr\&.c\&.
.SS "\fBsoxr_error_t\fP soxr::error"

.PP
Definition at line 47 of file soxr\&.c\&.
.SS "\fBint\fP soxr::flushing"

.PP
Definition at line 65 of file soxr\&.c\&.
.SS "\fBsoxr_input_fn_t\fP soxr::input_fn"

.PP
Definition at line 53 of file soxr\&.c\&.
.SS "\fBvoid\fP* soxr::input_fn_state"

.PP
Definition at line 52 of file soxr\&.c\&.
.SS "\fBinterleave_t\fP soxr::interleave"

.PP
Definition at line 60 of file soxr\&.c\&.
.SS "double soxr::io_ratio"

.PP
Definition at line 46 of file soxr\&.c\&.
.SS "\fBsoxr_io_spec_t\fP soxr::io_spec"

.PP
Definition at line 49 of file soxr\&.c\&.
.SS "size_t soxr::max_ilen"

.PP
Definition at line 54 of file soxr\&.c\&.
.SS "unsigned soxr::num_channels"

.PP
Definition at line 45 of file soxr\&.c\&.
.SS "\fBsoxr_quality_spec_t\fP soxr::q_spec"

.PP
Definition at line 48 of file soxr\&.c\&.
.SS "\fBresampler_t\fP* soxr::resamplers"

.PP
Definition at line 57 of file soxr\&.c\&.
.SS "\fBsoxr_runtime_spec_t\fP soxr::runtime_spec"

.PP
Definition at line 50 of file soxr\&.c\&.
.SS "unsigned long soxr::seed"

.PP
Definition at line 64 of file soxr\&.c\&.
.SS "\fBresampler_shared_t\fP soxr::shared"

.PP
Definition at line 56 of file soxr\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
