.TH "soxr_io_spec" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soxr_io_spec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soxr\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsoxr_datatype_t\fP \fBitype\fP"
.br
.ti -1c
.RI "\fBsoxr_datatype_t\fP \fBotype\fP"
.br
.ti -1c
.RI "double \fBscale\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBe\fP"
.br
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 219 of file soxr\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* soxr_io_spec::e"

.PP
Definition at line 223 of file soxr\&.h\&.
.SS "unsigned long soxr_io_spec::flags"

.PP
Definition at line 224 of file soxr\&.h\&.
.SS "\fBsoxr_datatype_t\fP soxr_io_spec::itype"

.PP
Definition at line 220 of file soxr\&.h\&.
.SS "\fBsoxr_datatype_t\fP soxr_io_spec::otype"

.PP
Definition at line 221 of file soxr\&.h\&.
.SS "double soxr_io_spec::scale"

.PP
Definition at line 222 of file soxr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
