.TH "SpectrumPrefsFactory" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpectrumPrefsFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectrumPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanelFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpectrumPrefsFactory\fP (\fBWaveTrack\fP *wt=0)"
.br
.ti -1c
.RI "\fBPrefsPanel\fP * \fBCreate\fP (wxWindow *parent) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file SpectrumPrefs\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpectrumPrefsFactory::SpectrumPrefsFactory (\fBWaveTrack\fP * wt = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 509 of file SpectrumPrefs\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPrefsPanel\fP * SpectrumPrefsFactory::Create (wxWindow * parent)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanelFactory\fP\&.
.PP
Definition at line 514 of file SpectrumPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
