.TH "C:/_dev/OpenU/Audacity/audacity/src/prefs/SpectrogramSettings.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/prefs/SpectrogramSettings.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Experimental\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpectrogramSettings\fP"
.br
.RI "\fISpectrogram settings, either for one track or as defaults\&. \fP"
.ti -1c
.RI "class \fBSpectrogramSettings::Globals\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
