.TH "SpectrogramSettings" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpectrogramSettings \- Spectrogram settings, either for one track or as defaults\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpectrogramSettings\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGlobals\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBLogMinWindowSize\fP = 3, \fBLogMaxWindowSize\fP = 15, \fBNumWindowSizes\fP = LogMaxWindowSize - LogMinWindowSize + 1 }"
.br
.ti -1c
.RI "enum \fBScaleType\fP { \fBstLinear\fP, \fBstLogarithmic\fP, \fBstMel\fP, \fBstBark\fP, \fBstErb\fP, \fBstPeriod\fP, \fBstNumScaleTypes\fP }"
.br
.ti -1c
.RI "enum \fBAlgorithm\fP { \fBalgSTFT\fP = 0, \fBalgReassignment\fP, \fBalgPitchEAC\fP, \fBalgNumAlgorithms\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpectrogramSettings\fP ()"
.br
.ti -1c
.RI "\fBSpectrogramSettings\fP (\fBconst\fP \fBSpectrogramSettings\fP &other)"
.br
.ti -1c
.RI "\fBSpectrogramSettings\fP & \fBoperator=\fP (\fBconst\fP \fBSpectrogramSettings\fP &other)"
.br
.ti -1c
.RI "\fB~SpectrogramSettings\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsDefault\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBValidate\fP (\fBbool\fP quiet)"
.br
.ti -1c
.RI "\fBvoid\fP \fBLoadPrefs\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSavePrefs\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBInvalidateCaches\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBDestroyWindows\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBCacheWindows\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBConvertToEnumeratedWindowSizes\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBConvertToActualWindowSizes\fP ()"
.br
.ti -1c
.RI "\fBNumberScale\fP \fBGetScale\fP (float \fBminFreq\fP, float \fBmaxFreq\fP, double \fBrate\fP, \fBbool\fP bins) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBSpectralSelectionEnabled\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBint\fP \fBGetFFTLength\fP () \fBconst\fP "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBconst\fP wxArrayString & \fBGetScaleNames\fP ()"
.br
.ti -1c
.RI "static \fBconst\fP wxArrayString & \fBGetAlgorithmNames\fP ()"
.br
.ti -1c
.RI "static \fBSpectrogramSettings\fP & \fBdefaults\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBminFreq\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxFreq\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrange\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgain\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfrequencyGain\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindowType\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindowSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBzeroPaddingFactor\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBisGrayscale\fP"
.br
.ti -1c
.RI "\fBScaleType\fP \fBscaleType\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBspectralSelection\fP"
.br
.ti -1c
.RI "\fBAlgorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "\fBFFTParam\fP * \fBhFFT\fP {}"
.br
.ti -1c
.RI "float * \fBwindow\fP {}"
.br
.ti -1c
.RI "float * \fBtWindow\fP {}"
.br
.ti -1c
.RI "float * \fBdWindow\fP {}"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSpectrumPrefs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Spectrogram settings, either for one track or as defaults\&. 
.PP
Definition at line 23 of file SpectrogramSettings\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILogMinWindowSize \fP\fP
.TP
\fB\fILogMaxWindowSize \fP\fP
.TP
\fB\fINumWindowSizes \fP\fP
.PP
Definition at line 44 of file SpectrogramSettings\&.h\&.
.SS "enum \fBSpectrogramSettings::Algorithm\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIalgSTFT \fP\fP
.TP
\fB\fIalgReassignment \fP\fP
.TP
\fB\fIalgPitchEAC \fP\fP
.TP
\fB\fIalgNumAlgorithms \fP\fP
.PP
Definition at line 118 of file SpectrogramSettings\&.h\&.
.SS "enum \fBSpectrogramSettings::ScaleType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIstLinear \fP\fP
.TP
\fB\fIstLogarithmic \fP\fP
.TP
\fB\fIstMel \fP\fP
.TP
\fB\fIstBark \fP\fP
.TP
\fB\fIstErb \fP\fP
.TP
\fB\fIstPeriod \fP\fP
.TP
\fB\fIstNumScaleTypes \fP\fP
.PP
Definition at line 54 of file SpectrogramSettings\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpectrogramSettings::SpectrogramSettings ()"

.PP
Definition at line 59 of file SpectrogramSettings\&.cpp\&.
.SS "SpectrogramSettings::SpectrogramSettings (\fBconst\fP \fBSpectrogramSettings\fP & other)"

.PP
Definition at line 64 of file SpectrogramSettings\&.cpp\&.
.SS "SpectrogramSettings::~SpectrogramSettings ()"

.PP
Definition at line 344 of file SpectrogramSettings\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP SpectrogramSettings::CacheWindows () const"

.PP
Definition at line 429 of file SpectrogramSettings\&.cpp\&.
.SS "\fBvoid\fP SpectrogramSettings::ConvertToActualWindowSizes ()"

.PP
Definition at line 474 of file SpectrogramSettings\&.cpp\&.
.SS "\fBvoid\fP SpectrogramSettings::ConvertToEnumeratedWindowSizes ()"

.PP
Definition at line 450 of file SpectrogramSettings\&.cpp\&.
.SS "\fBSpectrogramSettings\fP & SpectrogramSettings::defaults ()\fC [static]\fP"

.PP
Definition at line 134 of file SpectrogramSettings\&.cpp\&.
.SS "\fBvoid\fP SpectrogramSettings::DestroyWindows ()"

.PP
Definition at line 349 of file SpectrogramSettings\&.cpp\&.
.SS "\fBconst\fP wxArrayString & SpectrogramSettings::GetAlgorithmNames ()\fC [static]\fP"

.PP
Definition at line 166 of file SpectrogramSettings\&.cpp\&.
.SS "\fBint\fP SpectrogramSettings::GetFFTLength () const"

.PP
Definition at line 482 of file SpectrogramSettings\&.cpp\&.
.SS "\fBNumberScale\fP SpectrogramSettings::GetScale (float minFreq, float maxFreq, double rate, \fBbool\fP bins) const"

.PP
Definition at line 492 of file SpectrogramSettings\&.cpp\&.
.SS "\fBconst\fP wxArrayString & SpectrogramSettings::GetScaleNames ()\fC [static]\fP"

.PP
Definition at line 141 of file SpectrogramSettings\&.cpp\&.
.SS "\fBvoid\fP SpectrogramSettings::InvalidateCaches ()"

.PP
Definition at line 339 of file SpectrogramSettings\&.cpp\&.
.SS "\fBbool\fP SpectrogramSettings::IsDefault () const\fC [inline]\fP"

.PP
Definition at line 74 of file SpectrogramSettings\&.h\&.
.SS "\fBvoid\fP SpectrogramSettings::LoadPrefs ()"

.PP
Definition at line 251 of file SpectrogramSettings\&.cpp\&.
.SS "\fBSpectrogramSettings\fP & SpectrogramSettings::operator= (\fBconst\fP \fBSpectrogramSettings\fP & other)"

.PP
Definition at line 99 of file SpectrogramSettings\&.cpp\&.
.SS "\fBvoid\fP SpectrogramSettings::SavePrefs ()"

.PP
Definition at line 296 of file SpectrogramSettings\&.cpp\&.
.SS "\fBbool\fP SpectrogramSettings::SpectralSelectionEnabled () const"

.PP
Definition at line 520 of file SpectrogramSettings\&.cpp\&.
.SS "\fBbool\fP SpectrogramSettings::Validate (\fBbool\fP quiet)"

.PP
Definition at line 185 of file SpectrogramSettings\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSpectrumPrefs\fP\fC [friend]\fP"

.PP
Definition at line 25 of file SpectrogramSettings\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAlgorithm\fP SpectrogramSettings::algorithm"

.PP
Definition at line 125 of file SpectrogramSettings\&.h\&.
.SS "float* SpectrogramSettings::dWindow {}\fC [mutable]\fP"

.PP
Definition at line 147 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::frequencyGain"

.PP
Definition at line 100 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::gain"

.PP
Definition at line 99 of file SpectrogramSettings\&.h\&.
.SS "\fBFFTParam\fP* SpectrogramSettings::hFFT {}\fC [mutable]\fP"

.PP
Definition at line 142 of file SpectrogramSettings\&.h\&.
.SS "\fBbool\fP SpectrogramSettings::isGrayscale"

.PP
Definition at line 110 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::maxFreq"

.PP
Definition at line 93 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::minFreq"

.PP
Definition at line 92 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::range"

.PP
Definition at line 98 of file SpectrogramSettings\&.h\&.
.SS "\fBScaleType\fP SpectrogramSettings::scaleType"

.PP
Definition at line 112 of file SpectrogramSettings\&.h\&.
.SS "\fBbool\fP SpectrogramSettings::spectralSelection"

.PP
Definition at line 115 of file SpectrogramSettings\&.h\&.
.SS "float* SpectrogramSettings::tWindow {}\fC [mutable]\fP"

.PP
Definition at line 146 of file SpectrogramSettings\&.h\&.
.SS "float* SpectrogramSettings::window {}\fC [mutable]\fP"

.PP
Definition at line 143 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::windowSize"

.PP
Definition at line 103 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::windowType"

.PP
Definition at line 102 of file SpectrogramSettings\&.h\&.
.SS "\fBint\fP SpectrogramSettings::zeroPaddingFactor"

.PP
Definition at line 105 of file SpectrogramSettings\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
