.TH "SratomImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SratomImpl \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLV2_URID_Map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBLV2_Atom_Forge\fP \fBforge\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBatom_Event\fP"
.br
.ti -1c
.RI "\fBLV2_URID\fP \fBmidi_MidiEvent\fP"
.br
.ti -1c
.RI "unsigned \fBnext_id\fP"
.br
.ti -1c
.RI "\fBSerdNode\fP \fBbase_uri\fP"
.br
.ti -1c
.RI "\fBSerdStatementSink\fP \fBwrite_statement\fP"
.br
.ti -1c
.RI "\fBSerdEndSink\fP \fBend_anon\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBhandle\fP"
.br
.ti -1c
.RI "\fBSratomObjectMode\fP \fBobject_mode\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBpretty_numbers\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBatom_childType\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBatom_frameTime\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_first\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_rest\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_type\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBrdf_value\fP"
.br
.ti -1c
.RI "   \fBSordNode\fP * \fBxsd_base64Binary\fP"
.br
.ti -1c
.RI "} \fBnodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file sratom\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSordNode\fP* SratomImpl::atom_childType"

.PP
Definition at line 55 of file sratom\&.c\&.
.SS "\fBLV2_URID\fP SratomImpl::atom_Event"

.PP
Definition at line 45 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::atom_frameTime"

.PP
Definition at line 56 of file sratom\&.c\&.
.SS "\fBSerdNode\fP SratomImpl::base_uri"

.PP
Definition at line 48 of file sratom\&.c\&.
.SS "\fBSerdEndSink\fP SratomImpl::end_anon"

.PP
Definition at line 50 of file sratom\&.c\&.
.SS "\fBLV2_Atom_Forge\fP SratomImpl::forge"

.PP
Definition at line 44 of file sratom\&.c\&.
.SS "\fBvoid\fP* SratomImpl::handle"

.PP
Definition at line 51 of file sratom\&.c\&.
.SS "\fBLV2_URID_Map\fP* SratomImpl::map"

.PP
Definition at line 43 of file sratom\&.c\&.
.SS "\fBLV2_URID\fP SratomImpl::midi_MidiEvent"

.PP
Definition at line 46 of file sratom\&.c\&.
.SS "unsigned SratomImpl::next_id"

.PP
Definition at line 47 of file sratom\&.c\&.
.SS "struct { \&.\&.\&. }   SratomImpl::nodes"

.SS "\fBSratomObjectMode\fP SratomImpl::object_mode"

.PP
Definition at line 52 of file sratom\&.c\&.
.SS "\fBbool\fP SratomImpl::pretty_numbers"

.PP
Definition at line 53 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::rdf_first"

.PP
Definition at line 57 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::rdf_rest"

.PP
Definition at line 58 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::rdf_type"

.PP
Definition at line 59 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::rdf_value"

.PP
Definition at line 60 of file sratom\&.c\&.
.SS "\fBSerdStatementSink\fP SratomImpl::write_statement"

.PP
Definition at line 49 of file sratom\&.c\&.
.SS "\fBSordNode\fP* SratomImpl::xsd_base64Binary"

.PP
Definition at line 61 of file sratom\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
