.TH "stage" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rate\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstage_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBstage_fn_t\fP \fBfn\fP"
.br
.ti -1c
.RI "\fBfifo_t\fP \fBfifo\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpre\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpre_post\fP"
.br
.ti -1c
.RI "\fBint\fP \fBpreload\fP"
.br
.ti -1c
.RI "double \fBout_in_ratio\fP"
.br
.ti -1c
.RI "\fBrate_shared_t\fP * \fBshared\fP"
.br
.ti -1c
.RI "unsigned \fBdft_filter_num\fP"
.br
.ti -1c
.RI "\fBsample_t\fP * \fBdft_scratch\fP"
.br
.ti -1c
.RI "\fBsample_t\fP * \fBdft_out\fP"
.br
.ti -1c
.RI "\fBstep_t\fP \fBat\fP"
.br
.ti -1c
.RI "\fBstep_t\fP \fBstep\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBuse_hi_prec_clock\fP"
.br
.ti -1c
.RI "\fBint\fP \fBL\fP"
.br
.ti -1c
.RI "\fBint\fP \fBremM\fP"
.br
.ti -1c
.RI "\fBint\fP \fBn\fP"
.br
.ti -1c
.RI "\fBint\fP \fBphase_bits\fP"
.br
.ti -1c
.RI "\fBint\fP \fBblock_len\fP"
.br
.ti -1c
.RI "double \fBmult\fP"
.br
.ti -1c
.RI "double \fBphase0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file rate\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBstep_t\fP stage::at"

.PP
Definition at line 170 of file rate\&.h\&.
.SS "\fBint\fP stage::block_len"

.PP
Definition at line 173 of file rate\&.h\&.
.SS "unsigned stage::dft_filter_num"

.PP
Definition at line 166 of file rate\&.h\&.
.SS "\fBsample_t\fP * stage::dft_out"

.PP
Definition at line 167 of file rate\&.h\&.
.SS "\fBsample_t\fP* stage::dft_scratch"

.PP
Definition at line 167 of file rate\&.h\&.
.SS "\fBfifo_t\fP stage::fifo"

.PP
Definition at line 158 of file rate\&.h\&.
.SS "\fBstage_fn_t\fP stage::fn"

.PP
Definition at line 157 of file rate\&.h\&.
.SS "\fBint\fP stage::L"

.PP
Definition at line 172 of file rate\&.h\&.
.SS "double stage::mult"

.PP
Definition at line 174 of file rate\&.h\&.
.SS "\fBint\fP stage::n"

.PP
Definition at line 173 of file rate\&.h\&.
.SS "double stage::out_in_ratio"

.PP
Definition at line 162 of file rate\&.h\&.
.SS "double stage::phase0"

.PP
Definition at line 174 of file rate\&.h\&.
.SS "\fBint\fP stage::phase_bits"

.PP
Definition at line 173 of file rate\&.h\&.
.SS "\fBint\fP stage::pre"

.PP
Definition at line 159 of file rate\&.h\&.
.SS "\fBint\fP stage::pre_post"

.PP
Definition at line 160 of file rate\&.h\&.
.SS "\fBint\fP stage::preload"

.PP
Definition at line 161 of file rate\&.h\&.
.SS "\fBint\fP stage::remM"

.PP
Definition at line 172 of file rate\&.h\&.
.SS "\fBrate_shared_t\fP* stage::shared"

.PP
Definition at line 165 of file rate\&.h\&.
.SS "\fBstep_t\fP stage::step"

.PP
Definition at line 170 of file rate\&.h\&.
.SS "\fBstage_type_t\fP stage::type"

.PP
Definition at line 156 of file rate\&.h\&.
.SS "\fBbool\fP stage::use_hi_prec_clock"

.PP
Definition at line 171 of file rate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
