.TH "static_metadata_t" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static_metadata_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnum_metadata\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP * \fBneeds_delete\fP"
.br
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP ** \fBmetadata\fP"
.br
.ti -1c
.RI "\fBFLAC__StreamMetadata\fP * \fBcuesheet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1701 of file encode\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__StreamMetadata\fP* static_metadata_t::cuesheet"

.PP
Definition at line 1705 of file encode\&.c\&.
.SS "\fBFLAC__StreamMetadata\fP** static_metadata_t::metadata"

.PP
Definition at line 1704 of file encode\&.c\&.
.SS "\fBFLAC__bool\fP* static_metadata_t::needs_delete"

.PP
Definition at line 1703 of file encode\&.c\&.
.SS "unsigned static_metadata_t::num_metadata"

.PP
Definition at line 1702 of file encode\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
