.TH "static_codebook" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static_codebook \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codebook\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBdim\fP"
.br
.ti -1c
.RI "long \fBentries\fP"
.br
.ti -1c
.RI "long * \fBlengthlist\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaptype\fP"
.br
.ti -1c
.RI "long \fBq_min\fP"
.br
.ti -1c
.RI "long \fBq_delta\fP"
.br
.ti -1c
.RI "\fBint\fP \fBq_quant\fP"
.br
.ti -1c
.RI "\fBint\fP \fBq_sequencep\fP"
.br
.ti -1c
.RI "long * \fBquantlist\fP"
.br
.ti -1c
.RI "\fBint\fP \fBallocedp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file codebook\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP static_codebook::allocedp"

.PP
Definition at line 55 of file codebook\&.h\&.
.SS "long static_codebook::dim"

.PP
Definition at line 37 of file codebook\&.h\&.
.SS "long static_codebook::entries"

.PP
Definition at line 38 of file codebook\&.h\&.
.SS "long * static_codebook::lengthlist"

.PP
Definition at line 39 of file codebook\&.h\&.
.SS "\fBint\fP static_codebook::maptype"

.PP
Definition at line 42 of file codebook\&.h\&.
.SS "long static_codebook::q_delta"

.PP
Definition at line 48 of file codebook\&.h\&.
.SS "long static_codebook::q_min"

.PP
Definition at line 47 of file codebook\&.h\&.
.SS "\fBint\fP static_codebook::q_quant"

.PP
Definition at line 49 of file codebook\&.h\&.
.SS "\fBint\fP static_codebook::q_sequencep"

.PP
Definition at line 50 of file codebook\&.h\&.
.SS "long * static_codebook::quantlist"

.PP
Definition at line 52 of file codebook\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
