.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/stdefs.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqsrc/stdefs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cext\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBPI\fP   (3\&.14159265358979323846)"
.br
.ti -1c
.RI "#define \fBPI2\fP   (6\&.28318530717958647693)"
.br
.ti -1c
.RI "#define \fBD2R\fP   (0\&.01745329348)          /* (2*pi)/360 */"
.br
.ti -1c
.RI "#define \fBR2D\fP   (57\&.29577951)            /* 360/(2*pi) */"
.br
.ti -1c
.RI "#define \fBMAX\fP(x,  y)   ((x)>(y) ?(x):(y))"
.br
.ti -1c
.RI "#define \fBMIN\fP(x,  y)   ((x)<(y) ?(x):(y))"
.br
.ti -1c
.RI "#define \fBABS\fP(x)     ((x)<0   ?(\-(x)):(x))"
.br
.ti -1c
.RI "#define \fBSGN\fP(x)     ((x)<0   ?(\-1):((x)==0?(0):(1)))"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBmem_float\fP"
.br
.ti -1c
.RI "typedef double \fBfast_float\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ABS(x)   ((x)<0   ?(\-(x)):(x))"

.PP
Definition at line 30 of file stdefs\&.h\&.
.SS "#define D2R   (0\&.01745329348)          /* (2*pi)/360 */"

.PP
Definition at line 19 of file stdefs\&.h\&.
.SS "#define FALSE   0"

.PP
Definition at line 8 of file stdefs\&.h\&.
.SS "#define false   0"

.PP
Definition at line 47 of file stdefs\&.h\&.
.SS "#define MAX(x, y)   ((x)>(y) ?(x):(y))"

.PP
Definition at line 23 of file stdefs\&.h\&.
.SS "#define MIN(x, y)   ((x)<(y) ?(x):(y))"

.PP
Definition at line 26 of file stdefs\&.h\&.
.SS "#define PI   (3\&.14159265358979323846)"

.PP
Definition at line 12 of file stdefs\&.h\&.
.SS "#define PI2   (6\&.28318530717958647693)"

.PP
Definition at line 16 of file stdefs\&.h\&.
.SS "#define R2D   (57\&.29577951)            /* 360/(2*pi) */"

.PP
Definition at line 20 of file stdefs\&.h\&.
.SS "#define SGN(x)   ((x)<0   ?(\-1):((x)==0?(0):(1)))"

.PP
Definition at line 34 of file stdefs\&.h\&.
.SS "#define true   1"

.PP
Definition at line 46 of file stdefs\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef double \fBfast_float\fP"

.PP
Definition at line 38 of file stdefs\&.h\&.
.SS "typedef float \fBmem_float\fP"

.PP
Definition at line 37 of file stdefs\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
