.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/StereoToMono.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/StereoToMono.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'Effect\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffectStereoToMono\fP"
.br
.RI "\fIAn \fBEffect\fP to convert stereo to mono\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTEREOTOMONO_PLUGIN_SYMBOL\fP   \fBXO\fP('Stereo To Mono')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STEREOTOMONO_PLUGIN_SYMBOL   \fBXO\fP('Stereo To Mono')"

.PP
Definition at line 18 of file StereoToMono\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
