.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/stkchorus.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/stkchorus.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_stkchorus\fP (\fBsound_type\fP s1, double baseDelay, double depth, double freq, double mix)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_stkchorus\fP (\fBsound_type\fP s1, double baseDelay, double depth, double freq, double mix)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_make_stkchorus (\fBsound_type\fP s1, double baseDelay, double depth, double freq, double mix)"

.PP
Definition at line 167 of file stkchorus\&.c\&.
.SS "\fBsound_type\fP snd_stkchorus (\fBsound_type\fP s1, double baseDelay, double depth, double freq, double mix)"

.PP
Definition at line 213 of file stkchorus\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
