.TH "stkEffect" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stkEffect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEffect\fP * \fBeffectPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file stkint\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEffect\fP* stkEffect::effectPtr"

.PP
Definition at line 16 of file stkint\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
