.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/libFLAC/include/protected/stream_encoder.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/libFLAC/include/protected/stream_encoder.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FLAC/stream_encoder\&.h'\fP
.br
\fC#include 'private/float\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFLAC__ApodizationSpecification\fP"
.br
.ti -1c
.RI "struct \fBFLAC__StreamEncoderProtected\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLAC__MAX_APODIZATION_FUNCTIONS\fP   32"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBFLAC__StreamEncoderProtected\fP \fBFLAC__StreamEncoderProtected\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFLAC__ApodizationFunction\fP { \fBFLAC__APODIZATION_BARTLETT\fP, \fBFLAC__APODIZATION_BARTLETT_HANN\fP, \fBFLAC__APODIZATION_BLACKMAN\fP, \fBFLAC__APODIZATION_BLACKMAN_HARRIS_4TERM_92DB_SIDELOBE\fP, \fBFLAC__APODIZATION_CONNES\fP, \fBFLAC__APODIZATION_FLATTOP\fP, \fBFLAC__APODIZATION_GAUSS\fP, \fBFLAC__APODIZATION_HAMMING\fP, \fBFLAC__APODIZATION_HANN\fP, \fBFLAC__APODIZATION_KAISER_BESSEL\fP, \fBFLAC__APODIZATION_NUTTALL\fP, \fBFLAC__APODIZATION_RECTANGLE\fP, \fBFLAC__APODIZATION_TRIANGLE\fP, \fBFLAC__APODIZATION_TUKEY\fP, \fBFLAC__APODIZATION_PARTIAL_TUKEY\fP, \fBFLAC__APODIZATION_PUNCHOUT_TUKEY\fP, \fBFLAC__APODIZATION_WELCH\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FLAC__MAX_APODIZATION_FUNCTIONS   32"

.PP
Definition at line 45 of file stream_encoder\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBFLAC__StreamEncoderProtected\fP  \fBFLAC__StreamEncoderProtected\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFLAC__ApodizationFunction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFLAC__APODIZATION_BARTLETT \fP\fP
.TP
\fB\fIFLAC__APODIZATION_BARTLETT_HANN \fP\fP
.TP
\fB\fIFLAC__APODIZATION_BLACKMAN \fP\fP
.TP
\fB\fIFLAC__APODIZATION_BLACKMAN_HARRIS_4TERM_92DB_SIDELOBE \fP\fP
.TP
\fB\fIFLAC__APODIZATION_CONNES \fP\fP
.TP
\fB\fIFLAC__APODIZATION_FLATTOP \fP\fP
.TP
\fB\fIFLAC__APODIZATION_GAUSS \fP\fP
.TP
\fB\fIFLAC__APODIZATION_HAMMING \fP\fP
.TP
\fB\fIFLAC__APODIZATION_HANN \fP\fP
.TP
\fB\fIFLAC__APODIZATION_KAISER_BESSEL \fP\fP
.TP
\fB\fIFLAC__APODIZATION_NUTTALL \fP\fP
.TP
\fB\fIFLAC__APODIZATION_RECTANGLE \fP\fP
.TP
\fB\fIFLAC__APODIZATION_TRIANGLE \fP\fP
.TP
\fB\fIFLAC__APODIZATION_TUKEY \fP\fP
.TP
\fB\fIFLAC__APODIZATION_PARTIAL_TUKEY \fP\fP
.TP
\fB\fIFLAC__APODIZATION_PUNCHOUT_TUKEY \fP\fP
.TP
\fB\fIFLAC__APODIZATION_WELCH \fP\fP
.PP
Definition at line 47 of file stream_encoder\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
