.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libmad/stream.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libmad/stream.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'bit\&.h'\fP
.br
\fC#include 'stream\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmad_stream_init\fP (struct \fBmad_stream\fP *stream)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmad_stream_finish\fP (struct \fBmad_stream\fP *stream)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmad_stream_buffer\fP (struct \fBmad_stream\fP *stream, unsigned char \fBconst\fP *\fBbuffer\fP, unsigned long \fBlength\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmad_stream_skip\fP (struct \fBmad_stream\fP *stream, unsigned long \fBlength\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBmad_stream_sync\fP (struct \fBmad_stream\fP *stream)"
.br
.ti -1c
.RI "char \fBconst\fP * \fBmad_stream_errorstr\fP (struct \fBmad_stream\fP \fBconst\fP *stream)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP mad_stream_buffer (struct \fBmad_stream\fP * stream, unsigned char \fBconst\fP * buffer, unsigned long length)"

.PP
Definition at line 79 of file stream\&.c\&.
.SS "char \fBconst\fP* mad_stream_errorstr (struct \fBmad_stream\fP \fBconst\fP * stream)"

.PP
Definition at line 129 of file stream\&.c\&.
.SS "\fBvoid\fP mad_stream_finish (struct \fBmad_stream\fP * stream)"

.PP
Definition at line 64 of file stream\&.c\&.
.SS "\fBvoid\fP mad_stream_init (struct \fBmad_stream\fP * stream)"

.PP
Definition at line 37 of file stream\&.c\&.
.SS "\fBvoid\fP mad_stream_skip (struct \fBmad_stream\fP * stream, unsigned long length)"

.PP
Definition at line 97 of file stream\&.c\&.
.SS "\fBint\fP mad_stream_sync (struct \fBmad_stream\fP * stream)"

.PP
Definition at line 106 of file stream\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
