.TH "StreamDecoder" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamDecoder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFLAC::Decoder::Stream\fP, and \fBDecoderCommon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamDecoder\fP (\fBLayer\fP layer)"
.br
.ti -1c
.RI "\fB~StreamDecoder\fP ()"
.br
.ti -1c
.RI "::\fBFLAC__StreamDecoderReadStatus\fP \fBread_callback\fP (\fBFLAC__byte\fP \fBbuffer\fP[], size_t *bytes)"
.br
.RI "\fIsee FLAC__StreamDecoderReadCallback \fP"
.ti -1c
.RI "::\fBFLAC__StreamDecoderSeekStatus\fP \fBseek_callback\fP (\fBFLAC__uint64\fP absolute_byte_offset)"
.br
.ti -1c
.RI "::\fBFLAC__StreamDecoderTellStatus\fP \fBtell_callback\fP (\fBFLAC__uint64\fP *absolute_byte_offset)"
.br
.ti -1c
.RI "::\fBFLAC__StreamDecoderLengthStatus\fP \fBlength_callback\fP (\fBFLAC__uint64\fP *stream_length)"
.br
.ti -1c
.RI "\fBbool\fP \fBeof_callback\fP ()"
.br
.RI "\fIsee FLAC__StreamDecoderEofCallback \fP"
.ti -1c
.RI "::\fBFLAC__StreamDecoderWriteStatus\fP \fBwrite_callback\fP (\fBconst\fP ::\fBFLAC__Frame\fP *frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP \fBbuffer\fP[])"
.br
.RI "\fIsee FLAC__StreamDecoderWriteCallback \fP"
.ti -1c
.RI "\fBvoid\fP \fBmetadata_callback\fP (\fBconst\fP ::\fBFLAC__StreamMetadata\fP *metadata)"
.br
.RI "\fIsee FLAC__StreamDecoderMetadataCallback \fP"
.ti -1c
.RI "\fBvoid\fP \fBerror_callback\fP (::\fBFLAC__StreamDecoderErrorStatus\fP \fBstatus\fP)"
.br
.RI "\fIsee FLAC__StreamDecoderErrorCallback \fP"
.ti -1c
.RI "\fBbool\fP \fBtest_respond\fP (\fBbool\fP is_ogg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfile_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 179 of file decoders\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StreamDecoder::StreamDecoder (\fBLayer\fP layer)\fC [inline]\fP"

.PP
Definition at line 183 of file decoders\&.cpp\&.
.SS "StreamDecoder::~StreamDecoder ()\fC [inline]\fP"

.PP
Definition at line 184 of file decoders\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP StreamDecoder::eof_callback ()\fC [virtual]\fP"

.PP
see FLAC__StreamDecoderEofCallback 
.PP
Reimplemented from \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 276 of file decoders\&.cpp\&.
.SS "\fBvoid\fP StreamDecoder::error_callback (::\fBFLAC__StreamDecoderErrorStatus\fP status)\fC [virtual]\fP"

.PP
see FLAC__StreamDecoderErrorCallback 
.PP
Implements \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 299 of file decoders\&.cpp\&.
.SS "\fBFLAC__StreamDecoderLengthStatus\fP StreamDecoder::length_callback (\fBFLAC__uint64\fP * stream_length)"

.PP
Definition at line 264 of file decoders\&.cpp\&.
.SS "\fBvoid\fP StreamDecoder::metadata_callback (\fBconst\fP ::\fBFLAC__StreamMetadata\fP * metadata)\fC [virtual]\fP"

.PP
see FLAC__StreamDecoderMetadataCallback 
.PP
Reimplemented from \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 294 of file decoders\&.cpp\&.
.SS "\fBFLAC__StreamDecoderReadStatus\fP StreamDecoder::read_callback (\fBFLAC__byte\fP buffer[], size_t * bytes)\fC [virtual]\fP"

.PP
see FLAC__StreamDecoderReadCallback 
.PP
Implements \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 202 of file decoders\&.cpp\&.
.SS "\fBFLAC__StreamDecoderSeekStatus\fP StreamDecoder::seek_callback (\fBFLAC__uint64\fP absolute_byte_offset)"

.PP
Definition at line 229 of file decoders\&.cpp\&.
.SS "\fBFLAC__StreamDecoderTellStatus\fP StreamDecoder::tell_callback (\fBFLAC__uint64\fP * absolute_byte_offset)"

.PP
Definition at line 245 of file decoders\&.cpp\&.
.SS "\fBbool\fP StreamDecoder::test_respond (\fBbool\fP is_ogg)"

.PP
Definition at line 304 of file decoders\&.cpp\&.
.SS "\fBFLAC__StreamDecoderWriteStatus\fP StreamDecoder::write_callback (\fBconst\fP ::\fBFLAC__Frame\fP * frame, \fBconst\fP \fBFLAC__int32\fP *\fBconst\fP buffer[])\fC [virtual]\fP"

.PP
see FLAC__StreamDecoderWriteCallback 
.PP
Implements \fBFLAC::Decoder::Stream\fP\&.
.PP
Definition at line 287 of file decoders\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "FILE* StreamDecoder::file_"

.PP
Definition at line 181 of file decoders\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
