.TH "String_parse" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String_parse \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <strparse\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBinit\fP (\fBstd::string\fP *\fBs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBskip_space\fP ()"
.br
.ti -1c
.RI "char \fBpeek\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBget_nonspace_quoted\fP (\fBstd::string\fP &field)"
.br
.ti -1c
.RI "\fBvoid\fP \fBget_remainder\fP (\fBstd::string\fP &field)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBstd::string\fP * \fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file strparse\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP String_parse::get_nonspace_quoted (\fBstd::string\fP & field)"

.PP
Definition at line 22 of file strparse\&.cpp\&.
.SS "\fBvoid\fP String_parse::get_remainder (\fBstd::string\fP & field)"

.PP
Definition at line 76 of file strparse\&.cpp\&.
.SS "\fBvoid\fP String_parse::init (\fBstd::string\fP * s)\fC [inline]\fP"

.PP
Definition at line 7 of file strparse\&.h\&.
.SS "char String_parse::peek ()"

.PP
Definition at line 16 of file strparse\&.cpp\&.
.SS "\fBvoid\fP String_parse::skip_space ()"

.PP
Definition at line 8 of file strparse\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP String_parse::pos"

.PP
Definition at line 5 of file strparse\&.h\&.
.SS "\fBstd::string\fP* String_parse::str"

.PP
Definition at line 6 of file strparse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
