.TH "SubMenuListEntry" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubMenuListEntry \- \fBSubMenuListEntry\fP is a structure used by \fBCommandManager\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubMenuListEntry\fP (\fBconst\fP wxString &name_, wxMenu *menu_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxString \fBname\fP"
.br
.ti -1c
.RI "wxMenu * \fBmenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSubMenuListEntry\fP is a structure used by \fBCommandManager\fP\&. 
.PP
Definition at line 47 of file CommandManager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubMenuListEntry::SubMenuListEntry (\fBconst\fP wxString & name_, wxMenu * menu_)\fC [inline]\fP"

.PP
Definition at line 49 of file CommandManager\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wxMenu* SubMenuListEntry::menu"

.PP
Definition at line 54 of file CommandManager\&.h\&.
.SS "wxString SubMenuListEntry::name"

.PP
Definition at line 53 of file CommandManager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
