.TH "SuilHostImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuilHostImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <suil_internal\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSuilPortWriteFunc\fP \fBwrite_func\fP"
.br
.ti -1c
.RI "\fBSuilPortIndexFunc\fP \fBindex_func\fP"
.br
.ti -1c
.RI "\fBSuilPortSubscribeFunc\fP \fBsubscribe_func\fP"
.br
.ti -1c
.RI "\fBSuilPortUnsubscribeFunc\fP \fBunsubscribe_func\fP"
.br
.ti -1c
.RI "\fBSuilTouchFunc\fP \fBtouch_func\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBgtk_lib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file suil_internal\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* SuilHostImpl::gtk_lib"

.PP
Definition at line 51 of file suil_internal\&.h\&.
.SS "\fBSuilPortIndexFunc\fP SuilHostImpl::index_func"

.PP
Definition at line 47 of file suil_internal\&.h\&.
.SS "\fBSuilPortSubscribeFunc\fP SuilHostImpl::subscribe_func"

.PP
Definition at line 48 of file suil_internal\&.h\&.
.SS "\fBSuilTouchFunc\fP SuilHostImpl::touch_func"

.PP
Definition at line 50 of file suil_internal\&.h\&.
.SS "\fBSuilPortUnsubscribeFunc\fP SuilHostImpl::unsubscribe_func"

.PP
Definition at line 49 of file suil_internal\&.h\&.
.SS "\fBSuilPortWriteFunc\fP SuilHostImpl::write_func"

.PP
Definition at line 46 of file suil_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
