.TH "SummaryInfo" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SummaryInfo \- Works with \fBBlockFile\fP to hold info about max and min and RMS over multiple samples, which in turn allows rapid drawing when zoomed out\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockFile\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSummaryInfo\fP (\fBsampleCount\fP \fBsamples\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBfields\fP"
.br
.ti -1c
.RI "\fBsampleFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbytesPerFrame\fP"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBframes64K\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoffset64K\fP"
.br
.ti -1c
.RI "\fBsampleCount\fP \fBframes256\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoffset256\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtotalSummaryBytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Works with \fBBlockFile\fP to hold info about max and min and RMS over multiple samples, which in turn allows rapid drawing when zoomed out\&. 
.PP
Definition at line 25 of file BlockFile\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SummaryInfo::SummaryInfo (\fBsampleCount\fP samples)"

.PP
Definition at line 73 of file BlockFile\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP SummaryInfo::bytesPerFrame"

.PP
Definition at line 31 of file BlockFile\&.h\&.
.SS "\fBint\fP SummaryInfo::fields"

.PP
Definition at line 29 of file BlockFile\&.h\&.
.SS "\fBsampleFormat\fP SummaryInfo::format"

.PP
Definition at line 30 of file BlockFile\&.h\&.
.SS "\fBsampleCount\fP SummaryInfo::frames256"

.PP
Definition at line 34 of file BlockFile\&.h\&.
.SS "\fBsampleCount\fP SummaryInfo::frames64K"

.PP
Definition at line 32 of file BlockFile\&.h\&.
.SS "\fBint\fP SummaryInfo::offset256"

.PP
Definition at line 35 of file BlockFile\&.h\&.
.SS "\fBint\fP SummaryInfo::offset64K"

.PP
Definition at line 33 of file BlockFile\&.h\&.
.SS "\fBint\fP SummaryInfo::totalSummaryBytes"

.PP
Definition at line 36 of file BlockFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
