.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/svx.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/svx.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVHDR_CHUNK\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORM_MARKER\fP   (MAKE_MARKER ('\fBF\fP', 'O', 'R', '\fBM\fP'))"
.br
.ti -1c
.RI "#define \fBSVX8_MARKER\fP   (MAKE_MARKER ('8', '\fBS\fP', '\fBV\fP', 'X'))"
.br
.ti -1c
.RI "#define \fBSV16_MARKER\fP   (MAKE_MARKER ('1', '6', '\fBS\fP', '\fBV\fP'))"
.br
.ti -1c
.RI "#define \fBVHDR_MARKER\fP   (MAKE_MARKER ('\fBV\fP', 'H', '\fBD\fP', 'R'))"
.br
.ti -1c
.RI "#define \fBBODY_MARKER\fP   (MAKE_MARKER ('\fBB\fP', 'O', '\fBD\fP', 'Y'))"
.br
.ti -1c
.RI "#define \fBATAK_MARKER\fP   (MAKE_MARKER ('\fBA\fP', '\fBT\fP', '\fBA\fP', 'K'))"
.br
.ti -1c
.RI "#define \fBRLSE_MARKER\fP   (MAKE_MARKER ('R', 'L', '\fBS\fP', '\fBE\fP'))"
.br
.ti -1c
.RI "#define \fBc_MARKER\fP   (MAKE_MARKER ('(', '\fBc\fP', ')', ' '))"
.br
.ti -1c
.RI "#define \fBNAME_MARKER\fP   (MAKE_MARKER ('\fBN\fP', '\fBA\fP', '\fBM\fP', '\fBE\fP'))"
.br
.ti -1c
.RI "#define \fBAUTH_MARKER\fP   (MAKE_MARKER ('\fBA\fP', 'U', '\fBT\fP', 'H'))"
.br
.ti -1c
.RI "#define \fBANNO_MARKER\fP   (MAKE_MARKER ('\fBA\fP', '\fBN\fP', '\fBN\fP', 'O'))"
.br
.ti -1c
.RI "#define \fBCHAN_MARKER\fP   (MAKE_MARKER ('C', 'H', '\fBA\fP', '\fBN\fP'))"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBHAVE_FORM\fP = 0x01, \fBHAVE_SVX\fP = 0x02, \fBHAVE_VHDR\fP = 0x04, \fBHAVE_BODY\fP = 0x08 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsvx_open\fP (\fBSF_PRIVATE\fP *psf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANNO_MARKER   (MAKE_MARKER ('\fBA\fP', '\fBN\fP', '\fBN\fP', 'O'))"

.PP
Definition at line 47 of file svx\&.c\&.
.SS "#define ATAK_MARKER   (MAKE_MARKER ('\fBA\fP', '\fBT\fP', '\fBA\fP', 'K'))"

.PP
Definition at line 41 of file svx\&.c\&.
.SS "#define AUTH_MARKER   (MAKE_MARKER ('\fBA\fP', 'U', '\fBT\fP', 'H'))"

.PP
Definition at line 46 of file svx\&.c\&.
.SS "#define BODY_MARKER   (MAKE_MARKER ('\fBB\fP', 'O', '\fBD\fP', 'Y'))"

.PP
Definition at line 39 of file svx\&.c\&.
.SS "#define c_MARKER   (MAKE_MARKER ('(', '\fBc\fP', ')', ' '))"

.PP
Definition at line 44 of file svx\&.c\&.
.SS "#define CHAN_MARKER   (MAKE_MARKER ('C', 'H', '\fBA\fP', '\fBN\fP'))"

.PP
Definition at line 48 of file svx\&.c\&.
.SS "#define FORM_MARKER   (MAKE_MARKER ('\fBF\fP', 'O', 'R', '\fBM\fP'))"

.PP
Definition at line 35 of file svx\&.c\&.
.SS "#define NAME_MARKER   (MAKE_MARKER ('\fBN\fP', '\fBA\fP', '\fBM\fP', '\fBE\fP'))"

.PP
Definition at line 45 of file svx\&.c\&.
.SS "#define RLSE_MARKER   (MAKE_MARKER ('R', 'L', '\fBS\fP', '\fBE\fP'))"

.PP
Definition at line 42 of file svx\&.c\&.
.SS "#define SV16_MARKER   (MAKE_MARKER ('1', '6', '\fBS\fP', '\fBV\fP'))"

.PP
Definition at line 37 of file svx\&.c\&.
.SS "#define SVX8_MARKER   (MAKE_MARKER ('8', '\fBS\fP', '\fBV\fP', 'X'))"

.PP
Definition at line 36 of file svx\&.c\&.
.SS "#define VHDR_MARKER   (MAKE_MARKER ('\fBV\fP', 'H', '\fBD\fP', 'R'))"

.PP
Definition at line 38 of file svx\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHAVE_FORM \fP\fP
.TP
\fB\fIHAVE_SVX \fP\fP
.TP
\fB\fIHAVE_VHDR \fP\fP
.TP
\fB\fIHAVE_BODY \fP\fP
.PP
Definition at line 61 of file svx\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP svx_open (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 82 of file svx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
