.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/synthesis.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/synthesis.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <ogg/ogg\&.h>\fP
.br
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'codec_internal\&.h'\fP
.br
\fC#include 'registry\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'os\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis\fP (\fBvorbis_block\fP *vb, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_trackonly\fP (\fBvorbis_block\fP *vb, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "long \fBvorbis_packet_blocksize\fP (\fBvorbis_info\fP *vi, \fBogg_packet\fP *op)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_halfrate\fP (\fBvorbis_info\fP *vi, \fBint\fP flag)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_synthesis_halfrate_p\fP (\fBvorbis_info\fP *vi)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "long vorbis_packet_blocksize (\fBvorbis_info\fP * vi, \fBogg_packet\fP * op)"

.PP
Definition at line 143 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis (\fBvorbis_block\fP * vb, \fBogg_packet\fP * op)"

.PP
Definition at line 26 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_halfrate (\fBvorbis_info\fP * vi, \fBint\fP flag)"

.PP
Definition at line 171 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_halfrate_p (\fBvorbis_info\fP * vi)"

.PP
Definition at line 181 of file synthesis\&.c\&.
.SS "\fBint\fP vorbis_synthesis_trackonly (\fBvorbis_block\fP * vb, \fBogg_packet\fP * op)"

.PP
Definition at line 94 of file synthesis\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
