.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/cpp/include/portaudiocpp/SystemDeviceIterator.hxx" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portaudio-v19/bindings/cpp/include/portaudiocpp/SystemDeviceIterator.hxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iterator>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include 'portaudiocpp/System\&.hxx'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBportaudio::System::DeviceIterator\fP"
.br
.RI "\fIIterator class for iterating through all Devices in a \fBSystem\fP\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBportaudio\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
