.TH "tag" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtag\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBrawName\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrawNameLength\fP"
.br
.ti -1c
.RI "\fBTAG_NAME\fP \fBname\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "char * \fBbufEnd\fP"
.br
.ti -1c
.RI "\fBBINDING\fP * \fBbindings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 181 of file xmlparse\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBINDING\fP* tag::bindings"

.PP
Definition at line 188 of file xmlparse\&.c\&.
.SS "char* tag::buf"

.PP
Definition at line 186 of file xmlparse\&.c\&.
.SS "char* tag::bufEnd"

.PP
Definition at line 187 of file xmlparse\&.c\&.
.SS "\fBTAG_NAME\fP tag::name"

.PP
Definition at line 185 of file xmlparse\&.c\&.
.SS "struct \fBtag\fP* tag::parent"

.PP
Definition at line 182 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* tag::rawName"

.PP
Definition at line 183 of file xmlparse\&.c\&.
.SS "\fBint\fP tag::rawNameLength"

.PP
Definition at line 184 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
