.TH "tagKS_DATARANGE_MPEG2_VIDEO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagKS_DATARANGE_MPEG2_VIDEO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSDATARANGE\fP \fBDataRange\fP"
.br
.ti -1c
.RI "WINBOOL \fBbFixedSizeSamples\fP"
.br
.ti -1c
.RI "WINBOOL \fBbTemporalCompression\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBStreamDescriptionFlags\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBMemoryAllocationFlags\fP"
.br
.ti -1c
.RI "\fBKS_VIDEO_STREAM_CONFIG_CAPS\fP \fBConfigCaps\fP"
.br
.ti -1c
.RI "\fBKS_MPEGVIDEOINFO2\fP \fBVideoInfoHeader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2707 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "WINBOOL tagKS_DATARANGE_MPEG2_VIDEO::bFixedSizeSamples"

.PP
Definition at line 2709 of file ksmedia\&.h\&.
.SS "WINBOOL tagKS_DATARANGE_MPEG2_VIDEO::bTemporalCompression"

.PP
Definition at line 2710 of file ksmedia\&.h\&.
.SS "\fBKS_VIDEO_STREAM_CONFIG_CAPS\fP tagKS_DATARANGE_MPEG2_VIDEO::ConfigCaps"

.PP
Definition at line 2713 of file ksmedia\&.h\&.
.SS "\fBKSDATARANGE\fP tagKS_DATARANGE_MPEG2_VIDEO::DataRange"

.PP
Definition at line 2708 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_DATARANGE_MPEG2_VIDEO::MemoryAllocationFlags"

.PP
Definition at line 2712 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_DATARANGE_MPEG2_VIDEO::StreamDescriptionFlags"

.PP
Definition at line 2711 of file ksmedia\&.h\&.
.SS "\fBKS_MPEGVIDEOINFO2\fP tagKS_DATARANGE_MPEG2_VIDEO::VideoInfoHeader"

.PP
Definition at line 2714 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
