.TH "tagKS_DATARANGE_VIDEO_PALETTE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagKS_DATARANGE_VIDEO_PALETTE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSDATARANGE\fP \fBDataRange\fP"
.br
.ti -1c
.RI "WINBOOL \fBbFixedSizeSamples\fP"
.br
.ti -1c
.RI "WINBOOL \fBbTemporalCompression\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBStreamDescriptionFlags\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBMemoryAllocationFlags\fP"
.br
.ti -1c
.RI "\fBKS_VIDEO_STREAM_CONFIG_CAPS\fP \fBConfigCaps\fP"
.br
.ti -1c
.RI "\fBKS_VIDEOINFO\fP \fBVideoInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2717 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "WINBOOL tagKS_DATARANGE_VIDEO_PALETTE::bFixedSizeSamples"

.PP
Definition at line 2719 of file ksmedia\&.h\&.
.SS "WINBOOL tagKS_DATARANGE_VIDEO_PALETTE::bTemporalCompression"

.PP
Definition at line 2720 of file ksmedia\&.h\&.
.SS "\fBKS_VIDEO_STREAM_CONFIG_CAPS\fP tagKS_DATARANGE_VIDEO_PALETTE::ConfigCaps"

.PP
Definition at line 2723 of file ksmedia\&.h\&.
.SS "\fBKSDATARANGE\fP tagKS_DATARANGE_VIDEO_PALETTE::DataRange"

.PP
Definition at line 2718 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_DATARANGE_VIDEO_PALETTE::MemoryAllocationFlags"

.PP
Definition at line 2722 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_DATARANGE_VIDEO_PALETTE::StreamDescriptionFlags"

.PP
Definition at line 2721 of file ksmedia\&.h\&.
.SS "\fBKS_VIDEOINFO\fP tagKS_DATARANGE_VIDEO_PALETTE::VideoInfo"

.PP
Definition at line 2724 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
