.TH "tagKS_VBIINFOHEADER" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagKS_VBIINFOHEADER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ULONG \fBStartLine\fP"
.br
.ti -1c
.RI "ULONG \fBEndLine\fP"
.br
.ti -1c
.RI "ULONG \fBSamplingFrequency\fP"
.br
.ti -1c
.RI "ULONG \fBMinLineStartTime\fP"
.br
.ti -1c
.RI "ULONG \fBMaxLineStartTime\fP"
.br
.ti -1c
.RI "ULONG \fBActualLineStartTime\fP"
.br
.ti -1c
.RI "ULONG \fBActualLineEndTime\fP"
.br
.ti -1c
.RI "ULONG \fBVideoStandard\fP"
.br
.ti -1c
.RI "ULONG \fBSamplesPerLine\fP"
.br
.ti -1c
.RI "ULONG \fBStrideInBytes\fP"
.br
.ti -1c
.RI "ULONG \fBBufferSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2506 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ULONG tagKS_VBIINFOHEADER::ActualLineEndTime"

.PP
Definition at line 2513 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::ActualLineStartTime"

.PP
Definition at line 2512 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::BufferSize"

.PP
Definition at line 2517 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::EndLine"

.PP
Definition at line 2508 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::MaxLineStartTime"

.PP
Definition at line 2511 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::MinLineStartTime"

.PP
Definition at line 2510 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::SamplesPerLine"

.PP
Definition at line 2515 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::SamplingFrequency"

.PP
Definition at line 2509 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::StartLine"

.PP
Definition at line 2507 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::StrideInBytes"

.PP
Definition at line 2516 of file ksmedia\&.h\&.
.SS "ULONG tagKS_VBIINFOHEADER::VideoStandard"

.PP
Definition at line 2514 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
