.TH "tagKS_DATARANGE_ANALOGVIDEO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagKS_DATARANGE_ANALOGVIDEO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKSDATARANGE\fP \fBDataRange\fP"
.br
.ti -1c
.RI "\fBKS_ANALOGVIDEOINFO\fP \fBAnalogVideoInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2737 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKS_ANALOGVIDEOINFO\fP tagKS_DATARANGE_ANALOGVIDEO::AnalogVideoInfo"

.PP
Definition at line 2739 of file ksmedia\&.h\&.
.SS "\fBKSDATARANGE\fP tagKS_DATARANGE_ANALOGVIDEO::DataRange"

.PP
Definition at line 2738 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
