.TH "tagKS_VIDEOINFO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagKS_VIDEOINFO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RECT \fBrcSource\fP"
.br
.ti -1c
.RI "RECT \fBrcTarget\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwBitRate\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwBitErrorRate\fP"
.br
.ti -1c
.RI "\fBREFERENCE_TIME\fP \fBAvgTimePerFrame\fP"
.br
.ti -1c
.RI "\fBKS_BITMAPINFOHEADER\fP \fBbmiHeader\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBKS_RGBQUAD\fP \fBbmiColors\fP [\fBKS_iPALETTE_COLORS\fP]"
.br
.ti -1c
.RI "   \fBDWORD\fP \fBdwBitMasks\fP [\fBKS_iMASK_COLORS\fP]"
.br
.ti -1c
.RI "   \fBKS_TRUECOLORINFO\fP \fBTrueColorInfo\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2487 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "__MINGW_EXTENSION { \&.\&.\&. } "

.SS "\fBREFERENCE_TIME\fP tagKS_VIDEOINFO::AvgTimePerFrame"

.PP
Definition at line 2492 of file ksmedia\&.h\&.
.SS "\fBKS_RGBQUAD\fP tagKS_VIDEOINFO::bmiColors[\fBKS_iPALETTE_COLORS\fP]"

.PP
Definition at line 2495 of file ksmedia\&.h\&.
.SS "\fBKS_BITMAPINFOHEADER\fP tagKS_VIDEOINFO::bmiHeader"

.PP
Definition at line 2493 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_VIDEOINFO::dwBitErrorRate"

.PP
Definition at line 2491 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_VIDEOINFO::dwBitMasks[\fBKS_iMASK_COLORS\fP]"

.PP
Definition at line 2496 of file ksmedia\&.h\&.
.SS "\fBDWORD\fP tagKS_VIDEOINFO::dwBitRate"

.PP
Definition at line 2490 of file ksmedia\&.h\&.
.SS "RECT tagKS_VIDEOINFO::rcSource"

.PP
Definition at line 2488 of file ksmedia\&.h\&.
.SS "RECT tagKS_VIDEOINFO::rcTarget"

.PP
Definition at line 2489 of file ksmedia\&.h\&.
.SS "\fBKS_TRUECOLORINFO\fP tagKS_VIDEOINFO::TrueColorInfo"

.PP
Definition at line 2497 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
