.TH "tagLOGFONTA" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagLOGFONTA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shtypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LONG \fBlfHeight\fP"
.br
.ti -1c
.RI "LONG \fBlfWidth\fP"
.br
.ti -1c
.RI "LONG \fBlfEscapement\fP"
.br
.ti -1c
.RI "LONG \fBlfOrientation\fP"
.br
.ti -1c
.RI "LONG \fBlfWeight\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfItalic\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfUnderline\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfStrikeOut\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfCharSet\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfOutPrecision\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfClipPrecision\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfQuality\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBlfPitchAndFamily\fP"
.br
.ti -1c
.RI "\fBCHAR\fP \fBlfFaceName\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 384 of file shtypes\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBYTE\fP tagLOGFONTA::lfCharSet"

.PP
Definition at line 394 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfClipPrecision"

.PP
Definition at line 396 of file shtypes\&.h\&.
.SS "LONG tagLOGFONTA::lfEscapement"

.PP
Definition at line 388 of file shtypes\&.h\&.
.SS "\fBCHAR\fP tagLOGFONTA::lfFaceName[32]"

.PP
Definition at line 399 of file shtypes\&.h\&.
.SS "LONG tagLOGFONTA::lfHeight"

.PP
Definition at line 386 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfItalic"

.PP
Definition at line 391 of file shtypes\&.h\&.
.SS "LONG tagLOGFONTA::lfOrientation"

.PP
Definition at line 389 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfOutPrecision"

.PP
Definition at line 395 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfPitchAndFamily"

.PP
Definition at line 398 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfQuality"

.PP
Definition at line 397 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfStrikeOut"

.PP
Definition at line 393 of file shtypes\&.h\&.
.SS "\fBBYTE\fP tagLOGFONTA::lfUnderline"

.PP
Definition at line 392 of file shtypes\&.h\&.
.SS "LONG tagLOGFONTA::lfWeight"

.PP
Definition at line 390 of file shtypes\&.h\&.
.SS "LONG tagLOGFONTA::lfWidth"

.PP
Definition at line 387 of file shtypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
