.TH "tagSERIALIZEDPROPERTYVALUE" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagSERIALIZEDPROPERTYVALUE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <propidl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDWORD\fP \fBdwType\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBrgb\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1178 of file propidl\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDWORD\fP tagSERIALIZEDPROPERTYVALUE::dwType"

.PP
Definition at line 1180 of file propidl\&.h\&.
.SS "\fBBYTE\fP tagSERIALIZEDPROPERTYVALUE::rgb[1]"

.PP
Definition at line 1181 of file propidl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
