.TH "tagTRANSPORTSTATUS" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagTRANSPORTSTATUS \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ksmedia\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LONG \fBMode\fP"
.br
.ti -1c
.RI "LONG \fBLastError\fP"
.br
.ti -1c
.RI "LONG \fBRecordInhibit\fP"
.br
.ti -1c
.RI "LONG \fBServoLock\fP"
.br
.ti -1c
.RI "LONG \fBMediaPresent\fP"
.br
.ti -1c
.RI "LONG \fBMediaLength\fP"
.br
.ti -1c
.RI "LONG \fBMediaSize\fP"
.br
.ti -1c
.RI "LONG \fBMediaTrackCount\fP"
.br
.ti -1c
.RI "LONG \fBMediaTrackLength\fP"
.br
.ti -1c
.RI "LONG \fBMediaTrackSide\fP"
.br
.ti -1c
.RI "LONG \fBMediaType\fP"
.br
.ti -1c
.RI "LONG \fBLinkMode\fP"
.br
.ti -1c
.RI "LONG \fBNotifyOn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3620 of file ksmedia\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "LONG tagTRANSPORTSTATUS::LastError"

.PP
Definition at line 3622 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::LinkMode"

.PP
Definition at line 3632 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaLength"

.PP
Definition at line 3626 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaPresent"

.PP
Definition at line 3625 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaSize"

.PP
Definition at line 3627 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaTrackCount"

.PP
Definition at line 3628 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaTrackLength"

.PP
Definition at line 3629 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaTrackSide"

.PP
Definition at line 3630 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::MediaType"

.PP
Definition at line 3631 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::Mode"

.PP
Definition at line 3621 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::NotifyOn"

.PP
Definition at line 3633 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::RecordInhibit"

.PP
Definition at line 3623 of file ksmedia\&.h\&.
.SS "LONG tagTRANSPORTSTATUS::ServoLock"

.PP
Definition at line 3624 of file ksmedia\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
