.TH "tapv_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tapv_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs1\fP"
.br
.ti -1c
.RI "long \fBs1_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs1_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBvardelay\fP"
.br
.ti -1c
.RI "long \fBvardelay_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBvardelay_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBvardelay_x1_sample\fP"
.br
.ti -1c
.RI "double \fBvardelay_pHaSe\fP"
.br
.ti -1c
.RI "double \fBvardelay_pHaSe_iNcR\fP"
.br
.ti -1c
.RI "double \fBoutput_per_vardelay\fP"
.br
.ti -1c
.RI "long \fBvardelay_n\fP"
.br
.ti -1c
.RI "double \fBoffset\fP"
.br
.ti -1c
.RI "double \fBvdscale\fP"
.br
.ti -1c
.RI "double \fBmaxdelay\fP"
.br
.ti -1c
.RI "long \fBbufflen\fP"
.br
.ti -1c
.RI "long \fBindex\fP"
.br
.ti -1c
.RI "\fBsample_type\fP * \fBbuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file tapv\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsample_type\fP* tapv_susp_struct::buffer"

.PP
Definition at line 41 of file tapv\&.c\&.
.SS "long tapv_susp_struct::bufflen"

.PP
Definition at line 39 of file tapv\&.c\&.
.SS "long tapv_susp_struct::index"

.PP
Definition at line 40 of file tapv\&.c\&.
.SS "\fBboolean\fP tapv_susp_struct::logically_stopped"

.PP
Definition at line 19 of file tapv\&.c\&.
.SS "double tapv_susp_struct::maxdelay"

.PP
Definition at line 38 of file tapv\&.c\&.
.SS "double tapv_susp_struct::offset"

.PP
Definition at line 36 of file tapv\&.c\&.
.SS "double tapv_susp_struct::output_per_vardelay"

.PP
Definition at line 33 of file tapv\&.c\&.
.SS "\fBsound_type\fP tapv_susp_struct::s1"

.PP
Definition at line 20 of file tapv\&.c\&.
.SS "long tapv_susp_struct::s1_cnt"

.PP
Definition at line 21 of file tapv\&.c\&.
.SS "\fBsample_block_values_type\fP tapv_susp_struct::s1_ptr"

.PP
Definition at line 22 of file tapv\&.c\&.
.SS "\fBboolean\fP tapv_susp_struct::started"

.PP
Definition at line 17 of file tapv\&.c\&.
.SS "\fBsnd_susp_node\fP tapv_susp_struct::susp"

.PP
Definition at line 16 of file tapv\&.c\&.
.SS "long tapv_susp_struct::terminate_cnt"

.PP
Definition at line 18 of file tapv\&.c\&.
.SS "\fBsound_type\fP tapv_susp_struct::vardelay"

.PP
Definition at line 23 of file tapv\&.c\&.
.SS "long tapv_susp_struct::vardelay_cnt"

.PP
Definition at line 24 of file tapv\&.c\&.
.SS "long tapv_susp_struct::vardelay_n"

.PP
Definition at line 34 of file tapv\&.c\&.
.SS "double tapv_susp_struct::vardelay_pHaSe"

.PP
Definition at line 29 of file tapv\&.c\&.
.SS "double tapv_susp_struct::vardelay_pHaSe_iNcR"

.PP
Definition at line 30 of file tapv\&.c\&.
.SS "\fBsample_block_values_type\fP tapv_susp_struct::vardelay_ptr"

.PP
Definition at line 25 of file tapv\&.c\&.
.SS "\fBsample_type\fP tapv_susp_struct::vardelay_x1_sample"

.PP
Definition at line 28 of file tapv\&.c\&.
.SS "double tapv_susp_struct::vdscale"

.PP
Definition at line 37 of file tapv\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
