.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Task.py" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/suil/waflib/Task.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwaflib\&.Task\&.store_task_type\fP"
.br
.ti -1c
.RI "class \fBwaflib\&.Task\&.TaskBase\fP"
.br
.ti -1c
.RI "class \fBwaflib\&.Task\&.Task\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwaflib\&.Task\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwaflib\&.Task\&.cache_outputs\fP (cls)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.is_before\fP (t1, t2)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.set_file_constraints\fP (tasks)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.set_precedence_constraints\fP (tasks)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.funex\fP (\fBc\fP)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.compile_fun_shell\fP (\fBline\fP)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.compile_fun_noshell\fP (\fBline\fP)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.compile_fun\fP (\fBline\fP, shell=False)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.task_factory\fP (\fBname\fP, func=None, vars=None, color='GREEN', ext_in=[], ext_out=[], before=[], after=[], shell=False, \fBscan\fP=None)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.always_run\fP (cls)"
.br
.ti -1c
.RI "def \fBwaflib\&.Task\&.update_outputs\fP (cls)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
