.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch/TDStretch.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundTouch/TDStretch.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include 'STTypes\&.h'\fP
.br
\fC#include 'RateTransposer\&.h'\fP
.br
\fC#include 'FIFOSamplePipe\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsoundtouch::TDStretch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsoundtouch\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_SEQUENCE_MS\fP   \fBUSE_AUTO_SEQUENCE_LEN\fP"
.br
.ti -1c
.RI "#define \fBUSE_AUTO_SEQUENCE_LEN\fP   0"
.br
.ti -1c
.RI "#define \fBDEFAULT_SEEKWINDOW_MS\fP   \fBUSE_AUTO_SEEKWINDOW_LEN\fP"
.br
.ti -1c
.RI "#define \fBUSE_AUTO_SEEKWINDOW_LEN\fP   0"
.br
.ti -1c
.RI "#define \fBDEFAULT_OVERLAP_MS\fP   8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_OVERLAP_MS   8"
Overlap length in milliseconds\&. When the chopped sound sequences are mixed back together, to form a continuous sound stream, this parameter defines over how long period the two consecutive sequences are let to overlap each other\&.
.PP
This shouldn't be that critical parameter\&. If you reduce the DEFAULT_SEQUENCE_MS setting by a large amount, you might wish to try a smaller value on this\&.
.PP
Increasing this value increases computational burden & vice versa\&. 
.PP
Definition at line 105 of file TDStretch\&.h\&.
.SS "#define DEFAULT_SEEKWINDOW_MS   \fBUSE_AUTO_SEEKWINDOW_LEN\fP"
Seeking window default length in milliseconds for algorithm that finds the best possible overlapping location\&. This determines from how wide window the algorithm may look for an optimal joining location when mixing the sound sequences back together\&.
.PP
The bigger this window setting is, the higher the possibility to find a better mixing position will become, but at the same time large values may cause a 'drifting' artifact because consequent sequences will be taken at more uneven intervals\&.
.PP
If there's a disturbing artifact that sounds as if a constant frequency was drifting around, try reducing this setting\&.
.PP
Increasing this value increases computational burden & vice versa\&. 
.PP
Definition at line 91 of file TDStretch\&.h\&.
.SS "#define DEFAULT_SEQUENCE_MS   \fBUSE_AUTO_SEQUENCE_LEN\fP"
Default values for sound processing parameters: Notice that the default parameters are tuned for contemporary popular music processing\&. For speech processing applications these parameters suit better: #define DEFAULT_SEQUENCE_MS 40 #define DEFAULT_SEEKWINDOW_MS 15 #define DEFAULT_OVERLAP_MS 8Default length of a single processing sequence, in milliseconds\&. This determines to how long sequences the original sound is chopped in the time-stretch algorithm\&.
.PP
The larger this value is, the lesser sequences are used in processing\&. In principle a bigger value sounds better when slowing down tempo, but worse when increasing tempo and vice versa\&.
.PP
Increasing this value reduces computational burden & vice versa\&. 
.PP
Definition at line 72 of file TDStretch\&.h\&.
.SS "#define USE_AUTO_SEEKWINDOW_LEN   0"
Giving this value for the seek window length sets automatic parameter value according to tempo setting (recommended) 
.PP
Definition at line 95 of file TDStretch\&.h\&.
.SS "#define USE_AUTO_SEQUENCE_LEN   0"
Giving this value for the sequence length sets automatic parameter value according to tempo setting (recommended) 
.PP
Definition at line 76 of file TDStretch\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
