.TH "tempomap_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tempomap_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tempomap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtempochange_type\fP \fBentries\fP"
.br
.ti -1c
.RI "\fBtempochange_type\fP \fBhint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file tempomap\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtempochange_type\fP tempomap_struct::entries"

.PP
Definition at line 12 of file tempomap\&.h\&.
.SS "\fBtempochange_type\fP tempomap_struct::hint"

.PP
Definition at line 13 of file tempomap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
