.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/tempomap.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/cmt/tempomap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cext\&.h'\fP
.br
\fC#include 'midifns\&.h'\fP
.br
\fC#include 'timebase\&.h'\fP
.br
\fC#include 'moxc\&.h'\fP
.br
\fC#include 'seq\&.h'\fP
.br
\fC#include 'tempomap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtempomap_type\fP \fBtempomap_create\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBtempomap_free\fP (\fBtempomap_type\fP tm)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtempomap_insert\fP (\fBtempomap_type\fP tempomap, long beat, long \fBtempo\fP)"
.br
.ti -1c
.RI "\fBtime_type\fP \fBtempomap_lookup\fP (\fBtempomap_type\fP tempomap, long beat)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBtempomap_type\fP tempomap_create (\fBvoid\fP)"

.PP
Definition at line 20 of file tempomap\&.c\&.
.SS "\fBvoid\fP tempomap_free (\fBtempomap_type\fP tm)"

.PP
Definition at line 37 of file tempomap\&.c\&.
.SS "\fBvoid\fP tempomap_insert (\fBtempomap_type\fP tempomap, long beat, long tempo)"

.PP
Definition at line 51 of file tempomap\&.c\&.
.SS "\fBtime_type\fP tempomap_lookup (\fBtempomap_type\fP tempomap, long beat)"

.PP
Definition at line 93 of file tempomap\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
