.TH "tempochange_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tempochange_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tempomap\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtempochange_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBtime_type\fP \fBrtime\fP"
.br
.ti -1c
.RI "long \fBbeat\fP"
.br
.ti -1c
.RI "long \fBtempo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file tempomap\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long tempochange_struct::beat"

.PP
Definition at line 6 of file tempomap\&.h\&.
.SS "struct \fBtempochange_struct\fP* tempochange_struct::next"

.PP
Definition at line 4 of file tempomap\&.h\&.
.SS "\fBtime_type\fP tempochange_struct::rtime"

.PP
Definition at line 5 of file tempomap\&.h\&.
.SS "long tempochange_struct::tempo"

.PP
Definition at line 7 of file tempomap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
