.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portburn/test_portburn.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portburn/test_portburn.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'portburn\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBswap_uint16\fP(x)   ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8))"
.br
.ti -1c
.RI "#define \fBFailErr\fP(result)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, char **\fBargv\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBfilename\fP = 'clip\&.wav'"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP \fBfile_frames\fP = 166"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP \fBframe_size\fP = 588"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FailErr(result)"
\fBValue:\fP
.PP
.nf
if (result != 0) { \
      printf("Failed: %d\n", result); \
      goto end; \
   }
.fi
.PP
Definition at line 27 of file test_portburn\&.cpp\&.
.SS "#define swap_uint16(x)   ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8))"

.PP
Definition at line 24 of file test_portburn\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, char ** argv)"

.PP
Definition at line 33 of file test_portburn\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBconst\fP \fBint\fP file_frames = 166"

.PP
Definition at line 21 of file test_portburn\&.cpp\&.
.SS "\fBconst\fP char* filename = 'clip\&.wav'"

.PP
Definition at line 20 of file test_portburn\&.cpp\&.
.SS "\fBconst\fP \fBint\fP frame_size = 588"

.PP
Definition at line 22 of file test_portburn\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
