.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/test_broadcast_var.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/test_broadcast_var.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'test_main\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBCAST_MAX\fP   512"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBSF_BROADCAST_INFO_VAR\fP (\fBBCAST_MAX\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtest_broadcast_var\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BCAST_MAX   512"

.PP
Definition at line 29 of file test_broadcast_var\&.c\&.
.SH "Function Documentation"
.PP 
.SS "typedef SF_BROADCAST_INFO_VAR (\fBBCAST_MAX\fP)"

.PP
Definition at line 31 of file test_broadcast_var\&.c\&.
.SS "\fBvoid\fP test_broadcast_var (\fBvoid\fP)"

.PP
Definition at line 61 of file test_broadcast_var\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
