.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/win/wingui/textio.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/win/wingui/textio.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCR\fP   '\\n'"
.br
.ti -1c
.RI "#define \fBABORT_CHAR\fP   0x03"
.br
.ti -1c
.RI "#define \fBBREAK_CHAR\fP   0x02"
.br
.ti -1c
.RI "#define \fBCLEANUP_CHAR\fP   0x07"
.br
.ti -1c
.RI "#define \fBINFO_CHAR\fP   '\\024'"
.br
.ti -1c
.RI "#define \fBBREAK_LEVEL\fP   1"
.br
.ti -1c
.RI "#define \fBABORT_LEVEL\fP   2"
.br
.ti -1c
.RI "#define \fBGTRANS\fP   0"
.br
.ti -1c
.RI "#define \fBGERROR\fP   1"
.br
.ti -1c
.RI "#define \fBGFATAL\fP   2"
.br
.ti -1c
.RI "#define \fBGDEBUG\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBggetchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgprintf\fP (long where, char *\fBformat\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgputchar\fP (\fBint\fP \fBc\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBget_ascii\fP (char *\fBc\fP)"
.br
.ti -1c
.RI "char * \fBggets\fP (char *\fBstr\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBcheck_aborted\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBaskbool\fP (char *prompt, \fBint\fP deflt)"
.br
.ti -1c
.RI "char \fBwait_ascii\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_init\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyquist_printf\fP (\fBconst\fP char *\fBformat\fP,\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ABORT_CHAR   0x03"

.PP
Definition at line 2 of file textio\&.h\&.
.SS "#define ABORT_LEVEL   2"

.PP
Definition at line 8 of file textio\&.h\&.
.SS "#define BREAK_CHAR   0x02"

.PP
Definition at line 3 of file textio\&.h\&.
.SS "#define BREAK_LEVEL   1"

.PP
Definition at line 7 of file textio\&.h\&.
.SS "#define CLEANUP_CHAR   0x07"

.PP
Definition at line 4 of file textio\&.h\&.
.SS "#define CR   '\\n'"

.PP
Definition at line 1 of file textio\&.h\&.
.SS "#define GDEBUG   3"

.PP
Definition at line 36 of file textio\&.h\&.
.SS "#define GERROR   1"

.PP
Definition at line 34 of file textio\&.h\&.
.SS "#define GFATAL   2"

.PP
Definition at line 35 of file textio\&.h\&.
.SS "#define GTRANS   0"

.PP
Definition at line 33 of file textio\&.h\&.
.SS "#define INFO_CHAR   '\\024'"

.PP
Definition at line 5 of file textio\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP askbool (char * prompt, \fBint\fP deflt)"

.PP
Definition at line 443 of file userio\&.c\&.
.SS "\fBint\fP check_aborted ()"

.PP
Definition at line 737 of file userio\&.c\&.
.SS "\fBint\fP get_ascii (char * c)"

.PP
Definition at line 1047 of file userio\&.c\&.
.SS "\fBint\fP ggetchar (\fBvoid\fP)"

.PP
Definition at line 983 of file userio\&.c\&.
.SS "char* ggets (char * str)"

.PP
Definition at line 1003 of file userio\&.c\&.
.SS "\fBvoid\fP gprintf (long where, char * format,  \&.\&.\&.)"

.PP
Definition at line 100 of file textio\&.cpp\&.
.SS "\fBvoid\fP gputchar (\fBint\fP c)"

.PP
Definition at line 968 of file userio\&.c\&.
.SS "\fBvoid\fP io_init ()"

.PP
Definition at line 299 of file userio\&.c\&.
.SS "\fBvoid\fP nyquist_printf (\fBconst\fP char * format,  \&.\&.\&.)"

.PP
Definition at line 134 of file textio\&.cpp\&.
.SS "char wait_ascii ()"

.PP
Definition at line 1210 of file userio\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
