.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/win/wingui/textio.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/sys/win/wingui/textio.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include 'cppext\&.h'\fP
.br
\fC#include 'longque\&.h'\fP
.br
\fC#include 'textio\&.h'\fP
.br
\fC#include 'typein\&.h'\fP
.br
\fC#include 'button\&.h'\fP
.br
\fC#include 'slider\&.h'\fP
.br
\fC#include 'winmain\&.h'\fP
.br
\fC#include 'assert\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPRINTF_MESSAGE_LEN\fP   500"
.br
.ti -1c
.RI "#define \fBundefined\fP   \-1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBget_ascii\fP (char *\fBc\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBcheck_aborted\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBgprintf\fP (long where, char *\fBformat\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnyquist_printf\fP (\fBconst\fP char *\fBformat\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgputchar\fP (\fBint\fP \fBc\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBggetchar\fP ()"
.br
.ti -1c
.RI "char * \fBggets\fP (char *\fBstr\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBaskbool\fP (char *prompt, \fBint\fP deflt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBio_init\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBnext_ascii\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GPRINTF_MESSAGE_LEN   500"

.PP
Definition at line 36 of file textio\&.cpp\&.
.SS "#define undefined   \-1"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP askbool (char * prompt, \fBint\fP deflt)"

.PP
Definition at line 211 of file textio\&.cpp\&.
.SS "\fBint\fP check_aborted (\fBvoid\fP)"

.PP
Definition at line 89 of file textio\&.cpp\&.
.SS "\fBint\fP get_ascii (char * c)"

.PP
Definition at line 78 of file textio\&.cpp\&.
.SS "\fBint\fP ggetchar (\fBvoid\fP)"

.PP
Definition at line 164 of file textio\&.cpp\&.
.SS "char* ggets (char * str)"

.PP
Definition at line 175 of file textio\&.cpp\&.
.SS "\fBvoid\fP gprintf (long where, char * format,  \&.\&.\&.)"

.PP
Definition at line 100 of file textio\&.cpp\&.
.SS "\fBvoid\fP gputchar (\fBint\fP c)"

.PP
Definition at line 149 of file textio\&.cpp\&.
.SS "\fBvoid\fP io_init (\fBvoid\fP)"

.PP
Definition at line 242 of file textio\&.cpp\&.
.SS "\fBvoid\fP nyquist_printf (\fBconst\fP char * format,  \&.\&.\&.)"

.PP
Definition at line 134 of file textio\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "char* next_ascii"

.PP
Definition at line 55 of file winmain\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
