.TH "C:/_dev/OpenU/Audacity/audacity/src/TimerRecordDialog.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/TimerRecordDialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/dialog\&.h>\fP
.br
\fC#include <wx/datectrl\&.h>\fP
.br
\fC#include <wx/calctrl\&.h>\fP
.br
\fC#include <wx/timer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimerRecordDialog\fP"
.br
.RI "\fIDialog for Timer Record, i\&.e\&., timed or long recording\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
