.TH "C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolDock.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolDock.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include 'ToolBar\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolDock\fP"
.br
.RI "\fIA dynamic panel where a \fBToolBar\fP can be docked\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNoDockID\fP = 0, \fBTopDockID\fP, \fBBotDockID\fP, \fBDockCount\fP = 2 }
.RI "\fIclass \fBToolDock\fP \fP""
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
class \fBToolDock\fP 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINoDockID \fP\fP
.TP
\fB\fITopDockID \fP\fP
.TP
\fB\fIBotDockID \fP\fP
.TP
\fB\fIDockCount \fP\fP
.PP
Definition at line 40 of file ToolDock\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
