.TH "C:/_dev/OpenU/Audacity/audacity/images/ToolBarButtons.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/images/ToolBarButtons.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ToolBarImages/DockUp\&.xpm'\fP
.br
\fC#include 'ToolBarImages/DockDown\&.xpm'\fP
.br
\fC#include 'ToolBarImages/DockOver\&.xpm'\fP
.br
\fC#include 'ToolBarImages/DockUpShort\&.xpm'\fP
.br
\fC#include 'ToolBarImages/DockDownShort\&.xpm'\fP
.br
\fC#include 'ToolBarImages/DockOverShort\&.xpm'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
