.TH "ToolBarGrabber" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolBarGrabber \- Draws the grabber for an \fBExpandingToolBar\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandingToolBar\&.h>\fP
.PP
Inherits wxPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDECLARE_DYNAMIC_CLASS\fP (\fBToolBarGrabber\fP)"
.br
.ti -1c
.RI "\fBToolBarGrabber\fP (wxWindow *parent, wxWindowID id, \fBExpandingToolBar\fP *ownerToolbar, \fBconst\fP wxPoint &pos=wxDefaultPosition, \fBconst\fP wxSize &\fBsize\fP=wxDefaultSize)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnPaint\fP (wxPaintEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnSize\fP (wxSizeEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnMouse\fP (wxMouseEvent &evt)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmState\fP"
.br
.ti -1c
.RI "\fBImageRoll\fP \fBmImageRoll\fP [2]"
.br
.ti -1c
.RI "\fBExpandingToolBar\fP * \fBmOwnerToolBar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Draws the grabber for an \fBExpandingToolBar\fP\&. 
.PP
Definition at line 124 of file ExpandingToolBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ToolBarGrabber::ToolBarGrabber (wxWindow * parent, wxWindowID id, \fBExpandingToolBar\fP * ownerToolbar, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP, \fBconst\fP wxSize & size = \fCwxDefaultSize\fP)"

.PP
Definition at line 666 of file ExpandingToolBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "ToolBarGrabber::DECLARE_DYNAMIC_CLASS (\fBToolBarGrabber\fP)"

.SS "ToolBarGrabber::DECLARE_EVENT_TABLE ()\fC [protected]\fP"

.SS "\fBvoid\fP ToolBarGrabber::OnMouse (wxMouseEvent & evt)"

.PP
Definition at line 691 of file ExpandingToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolBarGrabber::OnPaint (wxPaintEvent & evt)"

.PP
Definition at line 718 of file ExpandingToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolBarGrabber::OnSize (wxSizeEvent & evt)"

.PP
Definition at line 725 of file ExpandingToolBar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBImageRoll\fP ToolBarGrabber::mImageRoll[2]\fC [protected]\fP"

.PP
Definition at line 141 of file ExpandingToolBar\&.h\&.
.SS "\fBExpandingToolBar\fP* ToolBarGrabber::mOwnerToolBar\fC [protected]\fP"

.PP
Definition at line 142 of file ExpandingToolBar\&.h\&.
.SS "\fBint\fP ToolBarGrabber::mState\fC [protected]\fP"

.PP
Definition at line 140 of file ExpandingToolBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
