.TH "C:/_dev/OpenU/Audacity/audacity/images/ToolsButtons.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/images/ToolsButtons.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ControlButtons/UpButton\&.xpm'\fP
.br
\fC#include 'ControlButtons/DownButton\&.xpm'\fP
.br
\fC#include 'ControlButtons/HiliteButton\&.xpm'\fP
.br
\fC#include 'ControlButtons/Up\&.xpm'\fP
.br
\fC#include 'ControlButtons/Down\&.xpm'\fP
.br
\fC#include 'ControlButtons/Hilite\&.xpm'\fP
.br
\fC#include 'ToolsButtons/DrawAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/Draw\&.xpm'\fP
.br
\fC#include 'ToolsButtons/EnvelopeAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/Envelope\&.xpm'\fP
.br
\fC#include 'ToolsButtons/IBeamAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/IBeam\&.xpm'\fP
.br
\fC#include 'ToolsButtons/MultiAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/Multi\&.xpm'\fP
.br
\fC#include 'ToolsButtons/TimeShiftAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/TimeShift\&.xpm'\fP
.br
\fC#include 'ToolsButtons/ZoomAlpha\&.xpm'\fP
.br
\fC#include 'ToolsButtons/Zoom\&.xpm'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
