.TH "C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolBar.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolBar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Audacity\&.h'\fP
.br
\fC#include <wx/wxprec\&.h>\fP
.br
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/gdicmn\&.h>\fP
.br
\fC#include <wx/image\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/settings\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/sysopt\&.h>\fP
.br
\fC#include <wx/window\&.h>\fP
.br
\fC#include 'ToolBar\&.h'\fP
.br
\fC#include '\&.\&./Experimental\&.h'\fP
.br
\fC#include '\&.\&./AllThemeResources\&.h'\fP
.br
\fC#include '\&.\&./AColor\&.h'\fP
.br
\fC#include '\&.\&./ImageManipulation\&.h'\fP
.br
\fC#include '\&.\&./Project\&.h'\fP
.br
\fC#include '\&.\&./Theme\&.h'\fP
.br
\fC#include '\&.\&./widgets/AButton\&.h'\fP
.br
\fC#include '\&.\&./widgets/Grabber\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolBarResizer\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRWIDTH\fP   4"
.br
.RI "\fI\fBToolBarResizer\fP\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEND_EVENT_TABLE\fP ()"
.br
.ti -1c
.RI "\fBIMPLEMENT_CLASS\fP (\fBToolBar\fP, wxPanel)"
.br
.RI "\fIMethods for \fBToolBar\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implements \fBToolBar\fP 
.PP
Definition in file \fBToolBar\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RWIDTH   4"

.PP
\fBToolBarResizer\fP\&. 
.PP
Definition at line 61 of file ToolBar\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "END_EVENT_TABLE ()"

.SS "IMPLEMENT_CLASS (\fBToolBar\fP, wxPanel)"

.PP
Methods for \fBToolBar\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
