.TH "ToolBarFrame" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolBarFrame \- A miniframe based container for ExpandingToolBars providing modeless presentation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExpandingToolBar\&.h>\fP
.PP
Inherits wxMiniFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToolBarFrame\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxString &\fBname\fP=wxEmptyString, \fBconst\fP wxPoint &pos=wxDefaultPosition)"
.br
.ti -1c
.RI "\fB~ToolBarFrame\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBFit\fP () override"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetChild\fP (\fBExpandingToolBar\fP *child)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBExpandingToolBar\fP * \fBmChild\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A miniframe based container for ExpandingToolBars providing modeless presentation\&. 
.PP
Definition at line 169 of file ExpandingToolBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ToolBarFrame::ToolBarFrame (wxWindow * parent, wxWindowID id, \fBconst\fP wxString & name = \fCwxEmptyString\fP, \fBconst\fP wxPoint & pos = \fCwxDefaultPosition\fP)"

.PP
Definition at line 791 of file ExpandingToolBar\&.cpp\&.
.SS "ToolBarFrame::~ToolBarFrame ()"

.PP
Definition at line 805 of file ExpandingToolBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ToolBarFrame::Fit ()\fC [override]\fP"

.PP
Definition at line 818 of file ExpandingToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolBarFrame::SetChild (\fBExpandingToolBar\fP * child)"

.PP
Definition at line 809 of file ExpandingToolBar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExpandingToolBar\fP* ToolBarFrame::mChild\fC [protected]\fP"

.PP
Definition at line 186 of file ExpandingToolBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
