.TH "ToolsToolBar" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolsToolBar \- A kind of \fBToolBar\fP with Tools on it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ToolsToolBar\&.h>\fP
.PP
Inherits \fBToolBar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToolsToolBar\fP ()"
.br
.ti -1c
.RI "virtual \fB~ToolsToolBar\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdatePrefs\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBOnTool\fP (wxCommandEvent &evt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCurrentTool\fP (\fBint\fP tool, \fBbool\fP show)"
.br
.ti -1c
.RI "\fBint\fP \fBGetCurrentTool\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsDown\fP (\fBint\fP tool)"
.br
.ti -1c
.RI "\fBint\fP \fBGetDownTool\fP ()"
.br
.ti -1c
.RI "\fBconst\fP wxChar * \fBGetMessageForTool\fP (\fBint\fP ToolNumber)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPopulate\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRepaint\fP (wxDC *WXUNUSED(dc)) override"
.br
.ti -1c
.RI "\fBvoid\fP \fBEnableDisableButtons\fP () override"
.br
.ti -1c
.RI "\fBDECLARE_CLASS\fP (\fBToolsToolBar\fP)"
.br
.ti -1c
.RI "\fBDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A kind of \fBToolBar\fP with Tools on it\&. 

This class, which is a child of Toolbar, creates the window containing the tool selection (ibeam, envelope, move, zoom)\&. The window can be embedded within a normal project window, or within a ToolbarFrame that is managed by a global ToolBarStub called gToolsToolBarStub\&.
.PP
All of the controls in this window were custom-written for Audacity - they are not native controls on any platform - however, it is intended that the images could be easily replaced to allow 'skinning' or just customization to match the look and feel of each platform\&.
.PP
\fBSee also:\fP
.RS 4
\fBThemability\fP 
.RE
.PP

.PP
Definition at line 47 of file ToolsToolBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ToolsToolBar::ToolsToolBar ()"

.SS "ToolsToolBar::~ToolsToolBar ()\fC [virtual]\fP"

.PP
Definition at line 125 of file ToolsToolBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "ToolsToolBar::DECLARE_CLASS (\fBToolsToolBar\fP)"

.SS "ToolsToolBar::DECLARE_EVENT_TABLE ()"

.SS "\fBvoid\fP ToolsToolBar::EnableDisableButtons ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 69 of file ToolsToolBar\&.h\&.
.SS "\fBint\fP ToolsToolBar::GetCurrentTool ()"
Gets the currently active tool In Multi-mode this might not return the multi-tool itself since the active tool may be changed by what you hover over\&. 
.PP
Definition at line 207 of file ToolsToolBar\&.cpp\&.
.SS "\fBint\fP ToolsToolBar::GetDownTool ()"

.PP
Definition at line 266 of file ToolsToolBar\&.cpp\&.
.SS "\fBconst\fP wxChar * ToolsToolBar::GetMessageForTool (\fBint\fP ToolNumber)"

.PP
Definition at line 277 of file ToolsToolBar\&.cpp\&.
.SS "\fBbool\fP ToolsToolBar::IsDown (\fBint\fP tool)"

.PP
Definition at line 261 of file ToolsToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolsToolBar::OnTool (wxCommandEvent & evt)"

.PP
Definition at line 286 of file ToolsToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolsToolBar::Populate ()\fC [virtual]\fP"

.PP
Implements \fBToolBar\fP\&.
.PP
Definition at line 186 of file ToolsToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolsToolBar::Repaint (wxDC * WXUNUSEDdc)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 68 of file ToolsToolBar\&.h\&.
.SS "\fBvoid\fP ToolsToolBar::SetCurrentTool (\fBint\fP tool, \fBbool\fP show)"
Sets the currently active tool 
.PP
\fBParameters:\fP
.RS 4
\fItool\fP - The index of the tool to be used\&. 
.br
\fIshow\fP - should we update the button display? 
.RE
.PP

.PP
Definition at line 215 of file ToolsToolBar\&.cpp\&.
.SS "\fBvoid\fP ToolsToolBar::UpdatePrefs ()\fC [virtual]\fP"

.PP
Reimplemented from \fBToolBar\fP\&.
.PP
Definition at line 166 of file ToolsToolBar\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
