.TH "C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolsToolBar.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/toolbars/ToolsToolBar.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/defs\&.h>\fP
.br
\fC#include 'ToolBar\&.h'\fP
.br
\fC#include '\&.\&./Theme\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToolsToolBar\fP"
.br
.RI "\fIA kind of \fBToolBar\fP with Tools on it\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBselectTool\fP, \fBenvelopeTool\fP, \fBdrawTool\fP, \fBzoomTool\fP, \fBslideTool\fP, \fBmultiTool\fP, \fBnumTools\fP, \fBfirstTool\fP = selectTool, \fBlastTool\fP = multiTool }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIselectTool \fP\fP
.TP
\fB\fIenvelopeTool \fP\fP
.TP
\fB\fIdrawTool \fP\fP
.TP
\fB\fIzoomTool \fP\fP
.TP
\fB\fIslideTool \fP\fP
.TP
\fB\fImultiTool \fP\fP
.TP
\fB\fInumTools \fP\fP
.TP
\fB\fIfirstTool \fP\fP
.TP
\fB\fIlastTool \fP\fP
.PP
Definition at line 34 of file ToolsToolBar\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
