.TH "TracksPrefsFactory" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracksPrefsFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TracksPrefs\&.h>\fP
.PP
Inherits \fBPrefsPanelFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrefsPanel\fP * \fBCreate\fP (wxWindow *parent) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file TracksPrefs\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPrefsPanel\fP * TracksPrefsFactory::Create (wxWindow * parent)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrefsPanelFactory\fP\&.
.PP
Definition at line 165 of file TracksPrefs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
