.TH "C:/_dev/OpenU/Audacity/audacity/src/Track.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/Track.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Audacity\&.h'\fP
.br
\fC#include 'MemoryX\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <wx/dynarray\&.h>\fP
.br
\fC#include <wx/event\&.h>\fP
.br
\fC#include <wx/gdicmn\&.h>\fP
.br
\fC#include <wx/longlong\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include 'Experimental\&.h'\fP
.br
\fC#include 'SampleFormat\&.h'\fP
.br
\fC#include 'xml/XMLTagHandler\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWaveTrackArray\fP"
.br
.ti -1c
.RI "class \fBWaveTrackConstArray\fP"
.br
.ti -1c
.RI "class \fBTrack\fP"
.br
.RI "\fIFundamental data object of Audacity, placed in the \fBTrackPanel\fP\&. Classes derived form it include the \fBWaveTrack\fP, \fBNoteTrack\fP, \fBLabelTrack\fP and \fBTimeTrack\fP\&. \fP"
.ti -1c
.RI "class \fBTrackListNode\fP"
.br
.RI "\fIUsed by \fBTrackList\fP, points to a \fBTrack\fP\&. \fP"
.ti -1c
.RI "class \fBTrackListIterator\fP"
.br
.RI "\fIAn iterator for a \fBTrackList\fP\&. \fP"
.ti -1c
.RI "class \fBTrackListConstIterator\fP"
.br
.ti -1c
.RI "class \fBTrackListCondIterator\fP"
.br
.ti -1c
.RI "class \fBTrackListOfKindIterator\fP"
.br
.ti -1c
.RI "class \fBSelectedTrackListOfKindIterator\fP"
.br
.ti -1c
.RI "class \fBVisibleTrackIterator\fP"
.br
.ti -1c
.RI "class \fBSyncLockedTracksIterator\fP"
.br
.ti -1c
.RI "class \fBTrackList\fP"
.br
.RI "\fIA list of \fBTrackListNode\fP items\&. \fP"
.ti -1c
.RI "class \fBTrackFactory\fP"
.br
.RI "\fIUsed to create a \fBWaveTrack\fP, or a \fBLabelTrack\fP\&.\&. Implementation of the functions of this class are dispersed through the different \fBTrack\fP classes\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBWX_DEFINE_USER_EXPORTED_ARRAY\fP (\fBTrack\fP *, TrackArray, class AUDACITY_DLL_API)"
.br
.ti -1c
.RI "\fBDECLARE_EXPORTED_EVENT_TYPE\fP (AUDACITY_DLL_API, EVT_TRACKLIST_RESIZED,\-1)"
.br
.RI "\fI\fBTrackList\fP is a flat linked list of tracks supporting Add, Remove, Clear, and Contains, plus serialization of the list of tracks\&. \fP"
.ti -1c
.RI "\fBDECLARE_EXPORTED_EVENT_TYPE\fP (AUDACITY_DLL_API, EVT_TRACKLIST_UPDATED,\-1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_TRACKLIST_RESIZED, \- 1)"

.PP
\fBTrackList\fP is a flat linked list of tracks supporting Add, Remove, Clear, and Contains, plus serialization of the list of tracks\&. 
.SS "DECLARE_EXPORTED_EVENT_TYPE (AUDACITY_DLL_API, EVT_TRACKLIST_UPDATED, \- 1)"

.SS "WX_DEFINE_USER_EXPORTED_ARRAY (\fBTrack\fP *, TrackArray, class AUDACITY_DLL_API)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
