.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/TrackPanel2.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/mod-track-panel/TrackPanel2.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TrackPanel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTrackPanel2\fP"
.br
.RI "\fI\fBTrackPanel2\fP is the start of the new \fBTrackPanel\fP\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTrackPanel\fP * \fBTrackPanel2Factory\fP (wxWindow *parent, wxWindowID id, \fBconst\fP wxPoint &pos, \fBconst\fP wxSize &\fBsize\fP, \fBTrackList\fP *tracks, \fBViewInfo\fP *viewInfo, \fBTrackPanelListener\fP *listener, \fBAdornedRulerPanel\fP *ruler)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBTrackPanel\fP* TrackPanel2Factory (wxWindow * parent, wxWindowID id, \fBconst\fP wxPoint & pos, \fBconst\fP wxSize & size, \fBTrackList\fP * tracks, \fBViewInfo\fP * viewInfo, \fBTrackPanelListener\fP * listener, \fBAdornedRulerPanel\fP * ruler)"

.PP
Definition at line 26 of file TrackPanel2\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
