.TH "TrackPanelAx" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackPanelAx \- Helper to \fBTrackPanel\fP to give accessibility\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TrackPanelAx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackPanelAx\fP (wxWindow *window)"
.br
.ti -1c
.RI "virtual \fB~TrackPanelAx\fP ()"
.br
.ti -1c
.RI "\fBTrack\fP * \fBGetFocus\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetFocus\fP (\fBTrack\fP *track)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsFocused\fP (\fBTrack\fP *track)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdated\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper to \fBTrackPanel\fP to give accessibility\&. 
.PP
Definition at line 23 of file TrackPanelAx\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TrackPanelAx::TrackPanelAx (wxWindow * window)"

.PP
Definition at line 33 of file TrackPanelAx\&.cpp\&.
.SS "TrackPanelAx::~TrackPanelAx ()\fC [virtual]\fP"

.PP
Definition at line 42 of file TrackPanelAx\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTrack\fP * TrackPanelAx::GetFocus ()"

.PP
Definition at line 47 of file TrackPanelAx\&.cpp\&.
.SS "\fBbool\fP TrackPanelAx::IsFocused (\fBTrack\fP * track)"

.PP
Definition at line 107 of file TrackPanelAx\&.cpp\&.
.SS "\fBvoid\fP TrackPanelAx::SetFocus (\fBTrack\fP * track)"

.PP
Definition at line 63 of file TrackPanelAx\&.cpp\&.
.SS "\fBvoid\fP TrackPanelAx::Updated ()"

.PP
Definition at line 163 of file TrackPanelAx\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
