.TH "TrackPanel::AudacityTimer" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackPanel::AudacityTimer \- Timer class dedicated to infomring the \fBTrackPanel\fP that it is time to refresh some aspect of the screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TrackPanel\&.h>\fP
.PP
Inherits wxTimer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBNotify\fP () override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTrackPanel\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer class dedicated to infomring the \fBTrackPanel\fP that it is time to refresh some aspect of the screen\&. 
.PP
Definition at line 580 of file TrackPanel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP TrackPanel::AudacityTimer::Notify ()\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 582 of file TrackPanel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTrackPanel\fP* TrackPanel::AudacityTimer::parent"

.PP
Definition at line 593 of file TrackPanel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
