.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/trace.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/portsmf/trace.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdarg\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'crtdbg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBtrace\fP (char *\fBformat\fP,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP trace (char * format,  \&.\&.\&.)"

.PP
Definition at line 13 of file trace\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
