.TH "trigger_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trigger_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBstarted\fP"
.br
.ti -1c
.RI "\fBint\fP \fBterminate_bits\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlogical_stop_bits\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBlogically_stopped\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs1\fP"
.br
.ti -1c
.RI "long \fBs1_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_type\fP \fBs1_bptr\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs1_ptr\fP"
.br
.ti -1c
.RI "\fBsound_type\fP \fBs2\fP"
.br
.ti -1c
.RI "long \fBs2_cnt\fP"
.br
.ti -1c
.RI "\fBsample_block_type\fP \fBs2_bptr\fP"
.br
.ti -1c
.RI "\fBsample_block_values_type\fP \fBs2_ptr\fP"
.br
.ti -1c
.RI "\fBsample_type\fP \fBprevious\fP"
.br
.ti -1c
.RI "\fBLVAL\fP \fBclosure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file trigger\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLVAL\fP trigger_susp_struct::closure"

.PP
Definition at line 78 of file trigger\&.c\&.
.SS "\fBint\fP trigger_susp_struct::logical_stop_bits"

.PP
Definition at line 65 of file trigger\&.c\&.
.SS "\fBboolean\fP trigger_susp_struct::logically_stopped"

.PP
Definition at line 66 of file trigger\&.c\&.
.SS "\fBsample_type\fP trigger_susp_struct::previous"

.PP
Definition at line 77 of file trigger\&.c\&.
.SS "\fBsound_type\fP trigger_susp_struct::s1"

.PP
Definition at line 67 of file trigger\&.c\&.
.SS "\fBsample_block_type\fP trigger_susp_struct::s1_bptr"

.PP
Definition at line 69 of file trigger\&.c\&.
.SS "long trigger_susp_struct::s1_cnt"

.PP
Definition at line 68 of file trigger\&.c\&.
.SS "\fBsample_block_values_type\fP trigger_susp_struct::s1_ptr"

.PP
Definition at line 70 of file trigger\&.c\&.
.SS "\fBsound_type\fP trigger_susp_struct::s2"

.PP
Definition at line 71 of file trigger\&.c\&.
.SS "\fBsample_block_type\fP trigger_susp_struct::s2_bptr"

.PP
Definition at line 73 of file trigger\&.c\&.
.SS "long trigger_susp_struct::s2_cnt"

.PP
Definition at line 72 of file trigger\&.c\&.
.SS "\fBsample_block_values_type\fP trigger_susp_struct::s2_ptr"

.PP
Definition at line 74 of file trigger\&.c\&.
.SS "\fBboolean\fP trigger_susp_struct::started"

.PP
Definition at line 62 of file trigger\&.c\&.
.SS "\fBsnd_susp_node\fP trigger_susp_struct::susp"

.PP
Definition at line 61 of file trigger\&.c\&.
.SS "\fBint\fP trigger_susp_struct::terminate_bits"

.PP
Definition at line 63 of file trigger\&.c\&.
.SS "long trigger_susp_struct::terminate_cnt"

.PP
Definition at line 64 of file trigger\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
