.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lilv/src/ui.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lilv/src/ui.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'lilv_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLilvUI\fP * \fBlilv_ui_new\fP (\fBLilvWorld\fP *world, \fBLilvNode\fP *\fBuri\fP, \fBLilvNode\fP *type_uri, \fBLilvNode\fP *binary_uri)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlilv_ui_free\fP (\fBLilvUI\fP *ui)"
.br
.ti -1c
.RI "\fBLILV_API\fP \fBconst\fP \fBLilvNode\fP * \fBlilv_ui_get_uri\fP (\fBconst\fP \fBLilvUI\fP *ui)"
.br
.ti -1c
.RI "\fBLILV_API\fP unsigned \fBlilv_ui_is_supported\fP (\fBconst\fP \fBLilvUI\fP *ui, \fBLilvUISupportedFunc\fP supported_func, \fBconst\fP \fBLilvNode\fP *container_type, \fBconst\fP \fBLilvNode\fP **ui_type)"
.br
.ti -1c
.RI "\fBLILV_API\fP \fBconst\fP \fBLilvNodes\fP * \fBlilv_ui_get_classes\fP (\fBconst\fP \fBLilvUI\fP *ui)"
.br
.ti -1c
.RI "\fBLILV_API\fP \fBbool\fP \fBlilv_ui_is_a\fP (\fBconst\fP \fBLilvUI\fP *ui, \fBconst\fP \fBLilvNode\fP *ui_class_uri)"
.br
.ti -1c
.RI "\fBLILV_API\fP \fBconst\fP \fBLilvNode\fP * \fBlilv_ui_get_bundle_uri\fP (\fBconst\fP \fBLilvUI\fP *ui)"
.br
.ti -1c
.RI "\fBLILV_API\fP \fBconst\fP \fBLilvNode\fP * \fBlilv_ui_get_binary_uri\fP (\fBconst\fP \fBLilvUI\fP *ui)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP lilv_ui_free (\fBLilvUI\fP * ui)"

.PP
Definition at line 52 of file ui\&.c\&.
.SS "\fBLilvUI\fP* lilv_ui_new (\fBLilvWorld\fP * world, \fBLilvNode\fP * uri, \fBLilvNode\fP * type_uri, \fBLilvNode\fP * binary_uri)"

.PP
Definition at line 24 of file ui\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
