.TH "UnusableImportPlugin" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnusableImportPlugin \- Used in place of a real plug in for plug ins that have not been compiled or are not available in this version of Audacity\&. Has enough information to identify the file extensions that would be used, but little else\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImportPlugin\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnusableImportPlugin\fP (\fBconst\fP wxString &formatName, wxArrayString extensions)"
.br
.ti -1c
.RI "wxString \fBGetPluginFormatDescription\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBSupportsExtension\fP (\fBconst\fP wxString &extension)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used in place of a real plug in for plug ins that have not been compiled or are not available in this version of Audacity\&. Has enough information to identify the file extensions that would be used, but little else\&. 
.PP
Definition at line 174 of file ImportPlugin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnusableImportPlugin::UnusableImportPlugin (\fBconst\fP wxString & formatName, wxArrayString extensions)\fC [inline]\fP"

.PP
Definition at line 177 of file ImportPlugin\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "wxString UnusableImportPlugin::GetPluginFormatDescription ()\fC [inline]\fP"

.PP
Definition at line 183 of file ImportPlugin\&.h\&.
.SS "\fBbool\fP UnusableImportPlugin::SupportsExtension (\fBconst\fP wxString & extension)\fC [inline]\fP"

.PP
Definition at line 188 of file ImportPlugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
