.TH "UnusableImportPluginList" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnusableImportPluginList \- An \fBUnusableImportPlugin\fP list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImportPlugin\&.h>\fP
.SH "Detailed Description"
.PP 
An \fBUnusableImportPlugin\fP list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
