.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lilv/utils/uri_table.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lilv/utils/uri_table.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBURITable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A toy URI map/unmap implementation\&.
.PP
This file contains function definitions and must only be included once\&. 
.PP
Definition in file \fBuri_table\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
