.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/plugins/eg-scope.lv2/uris.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/lv2/lv2/plugins/eg-scope.lv2/uris.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lv2/lv2plug\&.in/ns/ext/atom/atom\&.h'\fP
.br
\fC#include 'lv2/lv2plug\&.in/ns/ext/atom/forge\&.h'\fP
.br
\fC#include 'lv2/lv2plug\&.in/ns/ext/parameters/parameters\&.h'\fP
.br
\fC#include 'lv2/lv2plug\&.in/ns/ext/urid/urid\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBScoLV2URIs\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCO_URI\fP   'http://\fBlv2plug\&.in\fP/plugins/eg\-scope'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SCO_URI   'http://\fBlv2plug\&.in\fP/plugins/eg\-scope'"

.PP
Definition at line 25 of file uris\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
