.TH "UserOptions_s" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserOptions_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsampleRate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBframesPerBuffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBinputLatency\fP"
.br
.ti -1c
.RI "\fBint\fP \fBoutputLatency\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsaveBadWaves\fP"
.br
.ti -1c
.RI "\fBint\fP \fBverbose\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwaveFileCount\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBwaveFilePath\fP"
.br
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBinputDevice\fP"
.br
.ti -1c
.RI "\fBPaDeviceIndex\fP \fBoutputDevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file paqa\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP UserOptions_s::framesPerBuffer"

.PP
Definition at line 133 of file paqa\&.c\&.
.SS "\fBPaDeviceIndex\fP UserOptions_s::inputDevice"

.PP
Definition at line 140 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::inputLatency"

.PP
Definition at line 134 of file paqa\&.c\&.
.SS "\fBPaDeviceIndex\fP UserOptions_s::outputDevice"

.PP
Definition at line 141 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::outputLatency"

.PP
Definition at line 135 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::sampleRate"

.PP
Definition at line 132 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::saveBadWaves"

.PP
Definition at line 136 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::verbose"

.PP
Definition at line 137 of file paqa\&.c\&.
.SS "\fBint\fP UserOptions_s::waveFileCount"

.PP
Definition at line 138 of file paqa\&.c\&.
.SS "\fBconst\fP char* UserOptions_s::waveFilePath"

.PP
Definition at line 139 of file paqa\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
