.TH "utils__SkipUntilSpecification" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils__SkipUntilSpecification \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBis_relative\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBvalue_is_samples\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBseconds\fP"
.br
.ti -1c
.RI "   \fBFLAC__int64\fP \fBsamples\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file utils\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLAC__bool\fP utils__SkipUntilSpecification::is_relative"

.PP
Definition at line 34 of file utils\&.h\&.
.SS "\fBFLAC__int64\fP utils__SkipUntilSpecification::samples"

.PP
Definition at line 38 of file utils\&.h\&.
.SS "double utils__SkipUntilSpecification::seconds"

.PP
Definition at line 37 of file utils\&.h\&.
.SS "union { \&.\&.\&. }   utils__SkipUntilSpecification::value"

.SS "\fBFLAC__bool\fP utils__SkipUntilSpecification::value_is_samples"

.PP
Definition at line 35 of file utils\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
