.TH "utils__CueSpecification" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils__CueSpecification \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBhas_start_point\fP"
.br
.ti -1c
.RI "\fBFLAC__bool\fP \fBhas_end_point\fP"
.br
.ti -1c
.RI "unsigned \fBstart_track\fP"
.br
.ti -1c
.RI "unsigned \fBstart_index\fP"
.br
.ti -1c
.RI "unsigned \fBend_track\fP"
.br
.ti -1c
.RI "unsigned \fBend_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file utils\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned utils__CueSpecification::end_index"

.PP
Definition at line 45 of file utils\&.h\&.
.SS "unsigned utils__CueSpecification::end_track"

.PP
Definition at line 45 of file utils\&.h\&.
.SS "\fBFLAC__bool\fP utils__CueSpecification::has_end_point"

.PP
Definition at line 43 of file utils\&.h\&.
.SS "\fBFLAC__bool\fP utils__CueSpecification::has_start_point"

.PP
Definition at line 43 of file utils\&.h\&.
.SS "unsigned utils__CueSpecification::start_index"

.PP
Definition at line 44 of file utils\&.h\&.
.SS "unsigned utils__CueSpecification::start_track"

.PP
Definition at line 44 of file utils\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
