.TH "Vamp::PluginAdapter< P >" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vamp::PluginAdapter< P > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vamp\-sdk/PluginAdapter\&.h>\fP
.PP
Inherits \fBVamp::PluginAdapterBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginAdapter\fP ()"
.br
.ti -1c
.RI "virtual \fB~PluginAdapter\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPlugin\fP * \fBcreatePlugin\fP (float inputSampleRate)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename P>
.br
class Vamp::PluginAdapter< P >"
\fBPluginAdapter\fP turns a \fBPluginAdapterBase\fP into a specific wrapper for a particular plugin implementation\&.
.PP
See \fBPluginAdapterBase\fP\&. 
.PP
Definition at line 95 of file PluginAdapter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename P> \fBVamp::PluginAdapter\fP< P >::\fBPluginAdapter\fP ()\fC [inline]\fP"

.PP
Definition at line 98 of file PluginAdapter\&.h\&.
.SS "template<typename P> virtual \fBVamp::PluginAdapter\fP< P >::~\fBPluginAdapter\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 99 of file PluginAdapter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename P> \fBPlugin\fP* \fBVamp::PluginAdapter\fP< P >::createPlugin (float inputSampleRate)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBVamp::PluginAdapterBase\fP\&.
.PP
Definition at line 102 of file PluginAdapter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
