.TH "Vamp::RealTime" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vamp::RealTime \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vamp\-sdk/RealTime\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBusec\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBint\fP \fBmsec\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBRealTime\fP ()"
.br
.ti -1c
.RI "\fBRealTime\fP (\fBint\fP \fBs\fP, \fBint\fP n)"
.br
.ti -1c
.RI "\fBRealTime\fP (\fBconst\fP \fBRealTime\fP &r)"
.br
.ti -1c
.RI "\fBRealTime\fP & \fBoperator=\fP (\fBconst\fP \fBRealTime\fP &r)"
.br
.ti -1c
.RI "\fBRealTime\fP \fBoperator+\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBRealTime\fP \fBoperator\-\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBRealTime\fP \fBoperator\-\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>=\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<=\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBRealTime\fP \fBoperator/\fP (\fBint\fP \fBd\fP) \fBconst\fP "
.br
.ti -1c
.RI "double \fBoperator/\fP (\fBconst\fP \fBRealTime\fP &r) \fBconst\fP "
.br
.ti -1c
.RI "\fBstd::string\fP \fBtoString\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBstd::string\fP \fBtoText\fP (\fBbool\fP fixedDp=\fBfalse\fP) \fBconst\fP "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRealTime\fP \fBfromSeconds\fP (double \fBsec\fP)"
.br
.ti -1c
.RI "static \fBRealTime\fP \fBfromMilliseconds\fP (\fBint\fP \fBmsec\fP)"
.br
.ti -1c
.RI "static \fBRealTime\fP \fBfromTimeval\fP (\fBconst\fP struct timeval &)"
.br
.ti -1c
.RI "static long \fBrealTime2Frame\fP (\fBconst\fP \fBRealTime\fP &r, unsigned \fBint\fP sampleRate)"
.br
.ti -1c
.RI "static \fBRealTime\fP \fBframe2RealTime\fP (long frame, unsigned \fBint\fP sampleRate)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsec\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnsec\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBconst\fP \fBRealTime\fP \fBzeroTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRealTime\fP represents time values to nanosecond precision with accurate arithmetic and frame-rate conversion functions\&. 
.PP
Definition at line 66 of file RealTime\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Vamp::RealTime::RealTime ()\fC [inline]\fP"

.PP
Definition at line 74 of file RealTime\&.h\&.
.SS "Vamp::RealTime::RealTime (\fBint\fP s, \fBint\fP n)"

.PP
Definition at line 77 of file RealTime\&.cpp\&.
.SS "Vamp::RealTime::RealTime (\fBconst\fP \fBRealTime\fP & r)\fC [inline]\fP"

.PP
Definition at line 77 of file RealTime\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRealTime\fP Vamp::RealTime::frame2RealTime (long frame, unsigned \fBint\fP sampleRate)\fC [static]\fP"
Convert a sample frame at the given sample rate into a \fBRealTime\fP\&. 
.PP
Definition at line 234 of file RealTime\&.cpp\&.
.SS "\fBRealTime\fP Vamp::RealTime::fromMilliseconds (\fBint\fP msec)\fC [static]\fP"

.PP
Definition at line 99 of file RealTime\&.cpp\&.
.SS "\fBRealTime\fP Vamp::RealTime::fromSeconds (double sec)\fC [static]\fP"

.PP
Definition at line 93 of file RealTime\&.cpp\&.
.SS "\fBRealTime\fP Vamp::RealTime::fromTimeval (\fBconst\fP struct timeval & tv)\fC [static]\fP"

.PP
Definition at line 106 of file RealTime\&.cpp\&.
.SS "\fBint\fP Vamp::RealTime::msec () const\fC [inline]\fP"

.PP
Definition at line 72 of file RealTime\&.h\&.
.SS "\fBbool\fP Vamp::RealTime::operator!= (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 115 of file RealTime\&.h\&.
.SS "\fBRealTime\fP Vamp::RealTime::operator+ (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 91 of file RealTime\&.h\&.
.SS "\fBRealTime\fP Vamp::RealTime::operator\- (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 94 of file RealTime\&.h\&.
.SS "\fBRealTime\fP Vamp::RealTime::operator\- () const\fC [inline]\fP"

.PP
Definition at line 97 of file RealTime\&.h\&.
.SS "\fBRealTime\fP Vamp::RealTime::operator/ (\fBint\fP d) const"

.PP
Definition at line 205 of file RealTime\&.cpp\&.
.SS "double Vamp::RealTime::operator/ (\fBconst\fP \fBRealTime\fP & r) const"
Return the ratio of two times\&. 
.PP
Definition at line 216 of file RealTime\&.cpp\&.
.SS "\fBbool\fP Vamp::RealTime::operator< (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 101 of file RealTime\&.h\&.
.SS "\fBbool\fP Vamp::RealTime::operator<= (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 124 of file RealTime\&.h\&.
.SS "\fBRealTime\fP& Vamp::RealTime::operator= (\fBconst\fP \fBRealTime\fP & r)\fC [inline]\fP"

.PP
Definition at line 87 of file RealTime\&.h\&.
.SS "\fBbool\fP Vamp::RealTime::operator== (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 111 of file RealTime\&.h\&.
.SS "\fBbool\fP Vamp::RealTime::operator> (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 106 of file RealTime\&.h\&.
.SS "\fBbool\fP Vamp::RealTime::operator>= (\fBconst\fP \fBRealTime\fP & r) const\fC [inline]\fP"

.PP
Definition at line 119 of file RealTime\&.h\&.
.SS "long Vamp::RealTime::realTime2Frame (\fBconst\fP \fBRealTime\fP & r, unsigned \fBint\fP sampleRate)\fC [static]\fP"
Convert a \fBRealTime\fP into a sample frame at the given sample rate\&. 
.PP
Definition at line 226 of file RealTime\&.cpp\&.
.SS "\fBstd::string\fP Vamp::RealTime::toString () const"
Return a human-readable debug-type string to full precision (probably not a format to show to a user directly) 
.PP
Definition at line 137 of file RealTime\&.cpp\&.
.SS "\fBstd::string\fP Vamp::RealTime::toText (\fBbool\fP fixedDp = \fC\fBfalse\fP\fP) const"
Return a user-readable string to the nearest millisecond in a form like HH:MM:SS\&.mmm 
.PP
Definition at line 153 of file RealTime\&.cpp\&.
.SS "\fBint\fP Vamp::RealTime::usec () const\fC [inline]\fP"

.PP
Definition at line 71 of file RealTime\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP Vamp::RealTime::nsec"

.PP
Definition at line 69 of file RealTime\&.h\&.
.SS "\fBint\fP Vamp::RealTime::sec"

.PP
Definition at line 68 of file RealTime\&.h\&.
.SS "\fBconst\fP \fBRealTime\fP Vamp::RealTime::zeroTime\fC [static]\fP"

.PP
Definition at line 158 of file RealTime\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
