.TH "Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVamp::HostExt::PluginWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginDeletionNotifyAdapter\fP (\fBPlugin\fP *plugin, \fBImpl\fP *loader)"
.br
.ti -1c
.RI "virtual \fB~PluginDeletionNotifyAdapter\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBImpl\fP * \fBm_loader\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 96 of file PluginLoader\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter::PluginDeletionNotifyAdapter (\fBPlugin\fP * plugin, \fBImpl\fP * loader)"

.PP
Definition at line 679 of file PluginLoader\&.cpp\&.
.SS "Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter::~PluginDeletionNotifyAdapter ()\fC [virtual]\fP"

.PP
Definition at line 686 of file PluginLoader\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBImpl\fP* Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter::m_loader\fC [protected]\fP"

.PP
Definition at line 101 of file PluginLoader\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
