.TH "Vamp::PluginBase::ParameterDescriptor" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vamp::PluginBase::ParameterDescriptor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PluginBase\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterDescriptor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBidentifier\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBname\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBdescription\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBunit\fP"
.br
.ti -1c
.RI "float \fBminValue\fP"
.br
.ti -1c
.RI "float \fBmaxValue\fP"
.br
.ti -1c
.RI "float \fBdefaultValue\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBisQuantized\fP"
.br
.ti -1c
.RI "float \fBquantizeStep\fP"
.br
.ti -1c
.RI "std::vector< \fBstd::string\fP > \fBvalueNames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file PluginBase\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Vamp::PluginBase::ParameterDescriptor::ParameterDescriptor ()\fC [inline]\fP"

.PP
Definition at line 195 of file PluginBase\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float Vamp::PluginBase::ParameterDescriptor::defaultValue"
The default value of the parameter\&. The plugin should ensure that parameters have this value on initialisation (i\&.e\&. the host is not required to explicitly set parameters if it wants to use their default values)\&. 
.PP
Definition at line 167 of file PluginBase\&.h\&.
.SS "\fBstd::string\fP Vamp::PluginBase::ParameterDescriptor::description"
A human-readable short text describing the parameter\&. May be empty if the name has said it all already\&. 
.PP
Definition at line 144 of file PluginBase\&.h\&.
.SS "\fBstd::string\fP Vamp::PluginBase::ParameterDescriptor::identifier"
The name of the parameter, in computer-usable form\&. Should be reasonably short, and may only contain the characters [a-zA-Z0-9_-]\&. 
.PP
Definition at line 133 of file PluginBase\&.h\&.
.SS "\fBbool\fP Vamp::PluginBase::ParameterDescriptor::isQuantized"
True if the parameter values are quantized to a particular resolution\&. 
.PP
Definition at line 173 of file PluginBase\&.h\&.
.SS "float Vamp::PluginBase::ParameterDescriptor::maxValue"
The maximum value of the parameter\&. 
.PP
Definition at line 159 of file PluginBase\&.h\&.
.SS "float Vamp::PluginBase::ParameterDescriptor::minValue"
The minimum value of the parameter\&. 
.PP
Definition at line 154 of file PluginBase\&.h\&.
.SS "\fBstd::string\fP Vamp::PluginBase::ParameterDescriptor::name"
The human-readable name of the parameter\&. 
.PP
Definition at line 138 of file PluginBase\&.h\&.
.SS "float Vamp::PluginBase::ParameterDescriptor::quantizeStep"
Quantization resolution of the parameter values (e\&.g\&. 1\&.0 if they are all integers)\&. Undefined if isQuantized is false\&. 
.PP
Definition at line 180 of file PluginBase\&.h\&.
.SS "\fBstd::string\fP Vamp::PluginBase::ParameterDescriptor::unit"
The unit of the parameter, in human-readable form\&. 
.PP
Definition at line 149 of file PluginBase\&.h\&.
.SS "std::vector<\fBstd::string\fP> Vamp::PluginBase::ParameterDescriptor::valueNames"
Names for the quantized values\&. If isQuantized is true, this may either be empty or contain one string for each of the quantize steps from minValue up to maxValue inclusive\&. Undefined if isQuantized is false\&.
.PP
If these names are provided, they should be shown to the user in preference to the values themselves\&. The user may never see the actual numeric values unless they are also encoded in the names\&. 
.PP
Definition at line 193 of file PluginBase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
