.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/vorbisfile.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/lib/vorbisfile.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'vorbis/codec\&.h'\fP
.br
\fC#include 'vorbis/vorbisfile\&.h'\fP
.br
\fC#include 'os\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOV_EXCLUDE_STATIC_CALLBACKS\fP"
.br
.ti -1c
.RI "#define \fBCHUNKSIZE\fP   65536 /* greater\-than\-page\-\fBsize\fP granularity seeking */"
.br
.ti -1c
.RI "#define \fBREADSIZE\fP   2048 /* \fBa\fP smaller read \fBsize\fP is needed \fBfor\fP low\-\fBrate\fP streaming\&. */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBov_clear\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "\fBint\fP \fBov_open_callbacks\fP (\fBvoid\fP *\fBf\fP, \fBOggVorbis_File\fP *vf, \fBconst\fP char *initial, long ibytes, \fBov_callbacks\fP callbacks)"
.br
.ti -1c
.RI "\fBint\fP \fBov_open\fP (FILE *\fBf\fP, \fBOggVorbis_File\fP *vf, \fBconst\fP char *initial, long ibytes)"
.br
.ti -1c
.RI "\fBint\fP \fBov_fopen\fP (\fBconst\fP char *path, \fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "\fBint\fP \fBov_halfrate\fP (\fBOggVorbis_File\fP *vf, \fBint\fP flag)"
.br
.ti -1c
.RI "\fBint\fP \fBov_halfrate_p\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "\fBint\fP \fBov_test_callbacks\fP (\fBvoid\fP *\fBf\fP, \fBOggVorbis_File\fP *vf, \fBconst\fP char *initial, long ibytes, \fBov_callbacks\fP callbacks)"
.br
.ti -1c
.RI "\fBint\fP \fBov_test\fP (FILE *\fBf\fP, \fBOggVorbis_File\fP *vf, \fBconst\fP char *initial, long ibytes)"
.br
.ti -1c
.RI "\fBint\fP \fBov_test_open\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "long \fBov_streams\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "long \fBov_seekable\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "long \fBov_bitrate\fP (\fBOggVorbis_File\fP *vf, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "long \fBov_bitrate_instant\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "long \fBov_serialnumber\fP (\fBOggVorbis_File\fP *vf, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBov_raw_total\fP (\fBOggVorbis_File\fP *vf, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBov_pcm_total\fP (\fBOggVorbis_File\fP *vf, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "double \fBov_time_total\fP (\fBOggVorbis_File\fP *vf, \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBov_raw_seek\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_pcm_seek_page\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_pcm_seek\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_time_seek\fP (\fBOggVorbis_File\fP *vf, double seconds)"
.br
.ti -1c
.RI "\fBint\fP \fBov_time_seek_page\fP (\fBOggVorbis_File\fP *vf, double seconds)"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBov_raw_tell\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "\fBogg_int64_t\fP \fBov_pcm_tell\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "double \fBov_time_tell\fP (\fBOggVorbis_File\fP *vf)"
.br
.ti -1c
.RI "\fBvorbis_info\fP * \fBov_info\fP (\fBOggVorbis_File\fP *vf, \fBint\fP link)"
.br
.ti -1c
.RI "\fBvorbis_comment\fP * \fBov_comment\fP (\fBOggVorbis_File\fP *vf, \fBint\fP link)"
.br
.ti -1c
.RI "long \fBov_read_filter\fP (\fBOggVorbis_File\fP *vf, char *\fBbuffer\fP, \fBint\fP \fBlength\fP, \fBint\fP bigendianp, \fBint\fP \fBword\fP, \fBint\fP sgned, \fBint\fP *bitstream, \fBvoid\fP(*\fBfilter\fP)(float **pcm, long channels, long \fBsamples\fP, \fBvoid\fP *filter_param), \fBvoid\fP *filter_param)"
.br
.ti -1c
.RI "long \fBov_read\fP (\fBOggVorbis_File\fP *vf, char *\fBbuffer\fP, \fBint\fP \fBlength\fP, \fBint\fP bigendianp, \fBint\fP \fBword\fP, \fBint\fP sgned, \fBint\fP *bitstream)"
.br
.ti -1c
.RI "long \fBov_read_float\fP (\fBOggVorbis_File\fP *vf, float ***pcm_channels, \fBint\fP \fBlength\fP, \fBint\fP *bitstream)"
.br
.ti -1c
.RI "float * \fBvorbis_window\fP (\fBvorbis_dsp_state\fP *v, \fBint\fP W)"
.br
.ti -1c
.RI "\fBint\fP \fBov_crosslap\fP (\fBOggVorbis_File\fP *vf1, \fBOggVorbis_File\fP *vf2)"
.br
.ti -1c
.RI "\fBint\fP \fBov_raw_seek_lap\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_pcm_seek_lap\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_pcm_seek_page_lap\fP (\fBOggVorbis_File\fP *vf, \fBogg_int64_t\fP pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_time_seek_lap\fP (\fBOggVorbis_File\fP *vf, double pos)"
.br
.ti -1c
.RI "\fBint\fP \fBov_time_seek_page_lap\fP (\fBOggVorbis_File\fP *vf, double pos)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHUNKSIZE   65536 /* greater\-than\-page\-\fBsize\fP granularity seeking */"

.PP
Definition at line 64 of file vorbisfile\&.c\&.
.SS "#define OV_EXCLUDE_STATIC_CALLBACKS"

.PP
Definition at line 27 of file vorbisfile\&.c\&.
.SS "#define READSIZE   2048 /* \fBa\fP smaller read \fBsize\fP is needed \fBfor\fP low\-\fBrate\fP streaming\&. */"

.PP
Definition at line 65 of file vorbisfile\&.c\&.
.SH "Function Documentation"
.PP 
.SS "long ov_bitrate (\fBOggVorbis_File\fP * vf, \fBint\fP i)"

.PP
Definition at line 1101 of file vorbisfile\&.c\&.
.SS "long ov_bitrate_instant (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1143 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_clear (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 955 of file vorbisfile\&.c\&.
.SS "\fBvorbis_comment\fP* ov_comment (\fBOggVorbis_File\fP * vf, \fBint\fP link)"

.PP
Definition at line 1809 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_crosslap (\fBOggVorbis_File\fP * vf1, \fBOggVorbis_File\fP * vf2)"

.PP
Definition at line 2168 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_fopen (\fBconst\fP char * path, \fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1011 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_halfrate (\fBOggVorbis_File\fP * vf, \fBint\fP flag)"

.PP
Definition at line 1025 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_halfrate_p (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1050 of file vorbisfile\&.c\&.
.SS "\fBvorbis_info\fP* ov_info (\fBOggVorbis_File\fP * vf, \fBint\fP link)"

.PP
Definition at line 1791 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_open (FILE * f, \fBOggVorbis_File\fP * vf, \fBconst\fP char * initial, long ibytes)"

.PP
Definition at line 1000 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_open_callbacks (\fBvoid\fP * f, \fBOggVorbis_File\fP * vf, \fBconst\fP char * initial, long ibytes, \fBov_callbacks\fP callbacks)"

.PP
Definition at line 993 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_pcm_seek (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 1590 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_pcm_seek_lap (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 2274 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_pcm_seek_page (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 1404 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_pcm_seek_page_lap (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 2278 of file vorbisfile\&.c\&.
.SS "\fBogg_int64_t\fP ov_pcm_tell (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1756 of file vorbisfile\&.c\&.
.SS "\fBogg_int64_t\fP ov_pcm_total (\fBOggVorbis_File\fP * vf, \fBint\fP i)"

.PP
Definition at line 1189 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_raw_seek (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 1229 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_raw_seek_lap (\fBOggVorbis_File\fP * vf, \fBogg_int64_t\fP pos)"

.PP
Definition at line 2270 of file vorbisfile\&.c\&.
.SS "\fBogg_int64_t\fP ov_raw_tell (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1750 of file vorbisfile\&.c\&.
.SS "\fBogg_int64_t\fP ov_raw_total (\fBOggVorbis_File\fP * vf, \fBint\fP i)"

.PP
Definition at line 1170 of file vorbisfile\&.c\&.
.SS "long ov_read (\fBOggVorbis_File\fP * vf, char * buffer, \fBint\fP length, \fBint\fP bigendianp, \fBint\fP word, \fBint\fP sgned, \fBint\fP * bitstream)"

.PP
Definition at line 2007 of file vorbisfile\&.c\&.
.SS "long ov_read_filter (\fBOggVorbis_File\fP * vf, char * buffer, \fBint\fP length, \fBint\fP bigendianp, \fBint\fP word, \fBint\fP sgned, \fBint\fP * bitstream, \fBvoid\fP(*)(float **pcm, long channels, long \fBsamples\fP, \fBvoid\fP *filter_param) filter, \fBvoid\fP * filter_param)"

.PP
Definition at line 1869 of file vorbisfile\&.c\&.
.SS "long ov_read_float (\fBOggVorbis_File\fP * vf, float *** pcm_channels, \fBint\fP length, \fBint\fP * bitstream)"

.PP
Definition at line 2026 of file vorbisfile\&.c\&.
.SS "long ov_seekable (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1088 of file vorbisfile\&.c\&.
.SS "long ov_serialnumber (\fBOggVorbis_File\fP * vf, \fBint\fP i)"

.PP
Definition at line 1155 of file vorbisfile\&.c\&.
.SS "long ov_streams (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1083 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_test (FILE * f, \fBOggVorbis_File\fP * vf, \fBconst\fP char * initial, long ibytes)"

.PP
Definition at line 1066 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_test_callbacks (\fBvoid\fP * f, \fBOggVorbis_File\fP * vf, \fBconst\fP char * initial, long ibytes, \fBov_callbacks\fP callbacks)"

.PP
Definition at line 1060 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_test_open (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1077 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_time_seek (\fBOggVorbis_File\fP * vf, double seconds)"

.PP
Definition at line 1690 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_time_seek_lap (\fBOggVorbis_File\fP * vf, double pos)"

.PP
Definition at line 2331 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_time_seek_page (\fBOggVorbis_File\fP * vf, double seconds)"

.PP
Definition at line 1720 of file vorbisfile\&.c\&.
.SS "\fBint\fP ov_time_seek_page_lap (\fBOggVorbis_File\fP * vf, double pos)"

.PP
Definition at line 2335 of file vorbisfile\&.c\&.
.SS "double ov_time_tell (\fBOggVorbis_File\fP * vf)"

.PP
Definition at line 1762 of file vorbisfile\&.c\&.
.SS "double ov_time_total (\fBOggVorbis_File\fP * vf, \fBint\fP i)"

.PP
Definition at line 1208 of file vorbisfile\&.c\&.
.SS "float* vorbis_window (\fBvorbis_dsp_state\fP * v, \fBint\fP W)"

.PP
Definition at line 1038 of file block\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
