.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/examples/vorbisfile_example.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/examples/vorbisfile_example.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vorbis/codec\&.h>\fP
.br
\fC#include <vorbis/vorbisfile\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBpcmout\fP [4096]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBvoid\fP)"

.PP
Definition at line 35 of file vorbisfile_example\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char pcmout[4096]"

.PP
Definition at line 33 of file vorbisfile_example\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
