.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/flac/vorbiscomment.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libflac/src/flac/vorbiscomment.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FLAC/metadata\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLAC__bool\fP \fBflac__vorbiscomment_add\fP (\fBFLAC__StreamMetadata\fP *\fBblock\fP, \fBconst\fP char *comment, \fBFLAC__bool\fP value_from_file, \fBFLAC__bool\fP raw, \fBconst\fP char **violation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLAC__bool\fP flac__vorbiscomment_add (\fBFLAC__StreamMetadata\fP * block, \fBconst\fP char * comment, \fBFLAC__bool\fP value_from_file, \fBFLAC__bool\fP raw, \fBconst\fP char ** violation)"

.PP
Definition at line 229 of file vorbiscomment\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
