.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/include/vorbis/vorbisenc.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/include/vorbis/vorbisenc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'codec\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBovectl_ratemanage_arg\fP"
.br
.ti -1c
.RI "struct \fBovectl_ratemanage2_arg\fP"
.br
.in -1c
.SS "Macros"

.PP
.RI "\fBvorbis_encode_ctl() codes\fP"
.br
 These values are passed as the \fCnumber\fP parameter of \fBvorbis_encode_ctl()\fP\&. The type of the referent of that function's \fCarg\fP pointer depends on these codes\&. 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE2_GET\fP   0x14"
.br
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE2_SET\fP   0x15"
.br
.ti -1c
.RI "#define \fBOV_ECTL_LOWPASS_GET\fP   0x20"
.br
.ti -1c
.RI "#define \fBOV_ECTL_LOWPASS_SET\fP   0x21"
.br
.ti -1c
.RI "#define \fBOV_ECTL_IBLOCK_GET\fP   0x30"
.br
.ti -1c
.RI "#define \fBOV_ECTL_IBLOCK_SET\fP   0x31"
.br
.ti -1c
.RI "#define \fBOV_ECTL_COUPLING_GET\fP   0x40"
.br
.ti -1c
.RI "#define \fBOV_ECTL_COUPLING_SET\fP   0x41"
.br
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE_GET\fP   0x10"
.br
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE_SET\fP   0x11"
.br
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE_AVG\fP   0x12"
.br
.ti -1c
.RI "#define \fBOV_ECTL_RATEMANAGE_HARD\fP   0x13"
.br
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_init\fP (\fBvorbis_info\fP *vi, long channels, long \fBrate\fP, long max_bitrate, long nominal_bitrate, long min_bitrate)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_setup_managed\fP (\fBvorbis_info\fP *vi, long channels, long \fBrate\fP, long max_bitrate, long nominal_bitrate, long min_bitrate)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_setup_vbr\fP (\fBvorbis_info\fP *vi, long channels, long \fBrate\fP, float quality)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_init_vbr\fP (\fBvorbis_info\fP *vi, long channels, long \fBrate\fP, float base_quality)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_setup_init\fP (\fBvorbis_info\fP *vi)"
.br
.ti -1c
.RI "\fBint\fP \fBvorbis_encode_ctl\fP (\fBvorbis_info\fP *vi, \fBint\fP number, \fBvoid\fP *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Libvorbisenc is a convenient API for setting up an encoding environment using libvorbis\&. Libvorbisenc encapsulates the actions needed to set up the encoder properly\&. 
.PP
Definition in file \fBvorbisenc\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define OV_ECTL_COUPLING_GET   0x40"
Returns the current encoder coupling setting in the int pointed to by arg\&.
.PP
\fBArgument\fP: \fCint *\fP 
.PP
Definition at line 367 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_COUPLING_SET   0x41"
Enables/disables channel coupling in multichannel encoding according to arg\&.
.PP
\fBArgument\fP: \fCint *\fP
.PP
Zero disables channel coupling for multichannel inputs, nonzer enables channel coupling\&. Setting has no effect on monophonic encoding or multichannel counts that do not offer coupling\&. At present, coupling is available for stereo and 5\&.1 encoding\&. 
.PP
Definition at line 379 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_IBLOCK_GET   0x30"
Returns the current encoder impulse block setting in the double pointed to by arg\&.
.PP
\fBArgument\fP: \fCdouble *\fP 
.PP
Definition at line 348 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_IBLOCK_SET   0x31"
Sets the impulse block bias to the the value pointed to by arg\&.
.PP
\fBArgument\fP: \fCdouble *\fP
.PP
Valid range is -15\&.0 to 0\&.0 [default]\&. A negative impulse block bias will direct to encoder to use more bits when incoding short blocks that contain strong impulses, thus improving the accuracy of impulse encoding\&. 
.PP
Definition at line 359 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_LOWPASS_GET   0x20"
Returns the current encoder hard-lowpass setting (kHz) in the double pointed to by arg\&.
.PP
\fBArgument\fP: \fCdouble *\fP 
.PP
Definition at line 332 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_LOWPASS_SET   0x21"
Sets the encoder hard-lowpass to the value (kHz) pointed to by arg\&. Valid lowpass settings range from 2 to 99\&.
.PP
\fBArgument\fP: \fCdouble *\fP 
.PP
Definition at line 340 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE2_GET   0x14"
Query the current encoder bitrate management setting\&.
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage2_arg\fP *\fP
.PP
Used to query the current encoder bitrate management setting\&. Also used to initialize fields of an \fBovectl_ratemanage2_arg\fP structure for use with \fBOV_ECTL_RATEMANAGE2_SET\fP\&. 
.PP
Definition at line 313 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE2_SET   0x15"
Set the current encoder bitrate management settings\&.
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage2_arg\fP *\fP
.PP
Used to set the current encoder bitrate management settings to the values listed in the \fBovectl_ratemanage2_arg\fP\&. Passing a NULL pointer will disable bitrate management\&. 
.PP
Definition at line 324 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE_AVG   0x12"
Old interface to setting average-bitrate encoding mode\&.
.PP
Deprecated after move to bit-reservoir style management in 1\&.1 rendered this interface partially obsolete\&.
.PP
\fBDeprecated\fP
.RS 4
Please use \fBOV_ECTL_RATEMANAGE2_SET\fP instead\&.
.RE
.PP
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage_arg\fP *\fP 
.PP
Definition at line 415 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE_GET   0x10"
Old interface to querying bitrate management settings\&.
.PP
Deprecated after move to bit-reservoir style management in 1\&.1 rendered this interface partially obsolete\&.
.PP
\fBDeprecated\fP
.RS 4
Please use \fBOV_ECTL_RATEMANAGE2_GET\fP instead\&.
.RE
.PP
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage_arg\fP *\fP 
.PP
Definition at line 393 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE_HARD   0x13"
Old interface to setting bounded-bitrate encoding modes\&.
.PP
deprecated after move to bit-reservoir style management in 1\&.1 rendered this interface partially obsolete\&.
.PP
\fBDeprecated\fP
.RS 4
Please use \fBOV_ECTL_RATEMANAGE2_SET\fP instead\&.
.RE
.PP
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage_arg\fP *\fP 
.PP
Definition at line 426 of file vorbisenc\&.h\&.
.SS "#define OV_ECTL_RATEMANAGE_SET   0x11"
Old interface to modifying bitrate management settings\&.
.PP
deprecated after move to bit-reservoir style management in 1\&.1 rendered this interface partially obsolete\&.
.PP
\fBDeprecated\fP
.RS 4
Please use \fBOV_ECTL_RATEMANAGE2_SET\fP instead\&.
.RE
.PP
.PP
\fBArgument\fP: \fCstruct \fBovectl_ratemanage_arg\fP *\fP 
.PP
Definition at line 404 of file vorbisenc\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBint\fP vorbis_encode_ctl (\fBvorbis_info\fP * vi, \fBint\fP number, \fBvoid\fP * arg)"
This function implements a generic interface to miscellaneous encoder settings similar to the classic UNIX 'ioctl()' system call\&. Applications may use \fBvorbis_encode_ctl()\fP to query or set bitrate management or quality mode details by using one of several \fIrequest\fP arguments detailed below\&. \fBvorbis_encode_ctl()\fP must be called after one of \fBvorbis_encode_setup_managed()\fP or \fBvorbis_encode_setup_vbr()\fP\&. When used to modify settings, \fBvorbis_encode_ctl()\fP must be called before \fBvorbis_encode_setup_init()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&.
.br
\fInumber\fP Specifies the desired action; See \fBthe list\fPof available requests"\&.
.br
\fIarg\fP void * pointing to a data structure matching the request argument\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success\&. Any further return information (such as the result of a query) is placed into the storage pointed to by *arg\&.
.br
\fIOV_EINVAL\fP Invalid argument, or an attempt to modify a setting after calling \fBvorbis_encode_setup_init()\fP\&.
.br
\fIOV_EIMPL\fP Unimplemented or unknown request 
.RE
.PP

.PP
Definition at line 1013 of file vorbisenc\&.c\&.
.SS "\fBint\fP vorbis_encode_init (\fBvorbis_info\fP * vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate)"
This is the primary function within libvorbisenc for setting up managed bitrate modes\&.
.PP
Before this function is called, the \fBvorbis_info\fP struct should be initialized by using \fBvorbis_info_init()\fP from the libvorbis API\&. After encoding, \fBvorbis_info_clear()\fP should be called\&.
.PP
The max_bitrate, nominal_bitrate, and min_bitrate settings are used to set constraints for the encoded file\&. This function uses these settings to select the appropriate encoding mode and set it up\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&. 
.br
\fIchannels\fP The number of channels to be encoded\&. 
.br
\fIrate\fP The sampling rate of the source audio\&. 
.br
\fImax_bitrate\fP Desired maximum bitrate (limit)\&. -1 indicates unset\&. 
.br
\fInominal_bitrate\fP Desired average, or central, bitrate\&. -1 indicates unset\&. 
.br
\fImin_bitrate\fP Desired minimum bitrate\&. -1 indicates unset\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero for success, and negative values for failure\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success\&. 
.br
\fIOV_EFAULT\fP Internal logic fault; indicates a bug or heap/stack corruption\&. 
.br
\fIOV_EINVAL\fP Invalid setup request, eg, out of range argument\&. 
.br
\fIOV_EIMPL\fP Unimplemented mode; unable to comply with bitrate request\&. 
.RE
.PP

.PP
Definition at line 990 of file vorbisenc\&.c\&.
.SS "\fBint\fP vorbis_encode_init_vbr (\fBvorbis_info\fP * vi, long channels, long rate, float base_quality)"
This is the primary function within libvorbisenc for setting up variable bitrate ('quality' based) modes\&.
.PP
Before this function is called, the \fBvorbis_info\fP struct should be initialized by using \fBvorbis_info_init()\fP from the libvorbis API\&. After encoding, \fBvorbis_info_clear()\fP should be called\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&. 
.br
\fIchannels\fP The number of channels to be encoded\&. 
.br
\fIrate\fP The sampling rate of the source audio\&. 
.br
\fIbase_quality\fP Desired quality level, currently from -0\&.1 to 1\&.0 (lo to hi)\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero for success, or a negative number for failure\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success 
.br
\fIOV_EFAULT\fP Internal logic fault; indicates a bug or heap/stack corruption\&. 
.br
\fIOV_EINVAL\fP Invalid setup request, eg, out of range argument\&. 
.br
\fIOV_EIMPL\fP Unimplemented mode; unable to comply with quality level request\&. 
.RE
.PP

.PP
Definition at line 923 of file vorbisenc\&.c\&.
.SS "\fBint\fP vorbis_encode_setup_init (\fBvorbis_info\fP * vi)"
This function performs the last stage of three-step encoding setup, as described in the API overview under managed bitrate modes\&.
.PP
Before this function is called, the \fBvorbis_info\fP struct should be initialized by using \fBvorbis_info_init()\fP from the libvorbis API, one of \fBvorbis_encode_setup_managed()\fP or \fBvorbis_encode_setup_vbr()\fP called to initialize the high-level encoding setup, and \fBvorbis_encode_ctl()\fP called if necessary to make encoding setup changes\&. \fBvorbis_encode_setup_init()\fP finalizes the highlevel encoding structure into a complete encoding setup after which the application may make no further setup changes\&.
.PP
After encoding, \fBvorbis_info_clear()\fP should be called\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero for success, and negative values for failure\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success\&. 
.br
\fIOV_EFAULT\fP Internal logic fault; indicates a bug or heap/stack corruption\&.
.br
\fIOV_EINVAL\fP Attempt to use \fBvorbis_encode_setup_init()\fP without first calling one of \fBvorbis_encode_setup_managed()\fP or \fBvorbis_encode_setup_vbr()\fP to initialize the high-level encoding setup 
.RE
.PP

.PP
Definition at line 681 of file vorbisenc\&.c\&.
.SS "\fBint\fP vorbis_encode_setup_managed (\fBvorbis_info\fP * vi, long channels, long rate, long max_bitrate, long nominal_bitrate, long min_bitrate)"
This function performs step-one of a three-step bitrate-managed encode setup\&. It functions similarly to the one-step setup performed by \fBvorbis_encode_init\fP but allows an application to make further encode setup tweaks using \fBvorbis_encode_ctl\fP before finally calling \fBvorbis_encode_setup_init\fP to complete the setup process\&.
.PP
Before this function is called, the \fBvorbis_info\fP struct should be initialized by using \fBvorbis_info_init()\fP from the libvorbis API\&. After encoding, \fBvorbis_info_clear()\fP should be called\&.
.PP
The max_bitrate, nominal_bitrate, and min_bitrate settings are used to set constraints for the encoded file\&. This function uses these settings to select the appropriate encoding mode and set it up\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&. 
.br
\fIchannels\fP The number of channels to be encoded\&. 
.br
\fIrate\fP The sampling rate of the source audio\&. 
.br
\fImax_bitrate\fP Desired maximum bitrate (limit)\&. -1 indicates unset\&. 
.br
\fInominal_bitrate\fP Desired average, or central, bitrate\&. -1 indicates unset\&. 
.br
\fImin_bitrate\fP Desired minimum bitrate\&. -1 indicates unset\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero for success, and negative for failure\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success 
.br
\fIOV_EFAULT\fP Internal logic fault; indicates a bug or heap/stack corruption\&. 
.br
\fIOV_EINVAL\fP Invalid setup request, eg, out of range argument\&. 
.br
\fIOV_EIMPL\fP Unimplemented mode; unable to comply with bitrate request\&. 
.RE
.PP

.PP
Definition at line 943 of file vorbisenc\&.c\&.
.SS "\fBint\fP vorbis_encode_setup_vbr (\fBvorbis_info\fP * vi, long channels, long rate, float quality)"
This function performs step-one of a three-step variable bitrate (quality-based) encode setup\&. It functions similarly to the one-step setup performed by \fBvorbis_encode_init_vbr()\fP but allows an application to make further encode setup tweaks using \fBvorbis_encode_ctl()\fP before finally calling \fBvorbis_encode_setup_init\fP to complete the setup process\&.
.PP
Before this function is called, the \fBvorbis_info\fP struct should be initialized by using \fBvorbis_info_init()\fP from the libvorbis API\&. After encoding, \fBvorbis_info_clear()\fP should be called\&.
.PP
\fBParameters:\fP
.RS 4
\fIvi\fP Pointer to an initialized \fBvorbis_info\fP struct\&. 
.br
\fIchannels\fP The number of channels to be encoded\&. 
.br
\fIrate\fP The sampling rate of the source audio\&. 
.br
\fIquality\fP Desired quality level, currently from -0\&.1 to 1\&.0 (lo to hi)\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Zero for success, and negative values for failure\&.
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI0\fP Success 
.br
\fIOV_EFAULT\fP Internal logic fault; indicates a bug or heap/stack corruption\&. 
.br
\fIOV_EINVAL\fP Invalid setup request, eg, out of range argument\&. 
.br
\fIOV_EIMPL\fP Unimplemented mode; unable to comply with quality level request\&. 
.RE
.PP

.PP
Definition at line 902 of file vorbisenc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
