.TH "vorbis_look_psy" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vorbis_look_psy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <psy\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBn\fP"
.br
.ti -1c
.RI "struct \fBvorbis_info_psy\fP * \fBvi\fP"
.br
.ti -1c
.RI "float *** \fBtonecurves\fP"
.br
.ti -1c
.RI "float ** \fBnoiseoffset\fP"
.br
.ti -1c
.RI "float * \fBath\fP"
.br
.ti -1c
.RI "long * \fBoctave\fP"
.br
.ti -1c
.RI "long * \fBbark\fP"
.br
.ti -1c
.RI "long \fBfirstoc\fP"
.br
.ti -1c
.RI "long \fBshiftoc\fP"
.br
.ti -1c
.RI "\fBint\fP \fBeighth_octave_lines\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtotal_octave_lines\fP"
.br
.ti -1c
.RI "long \fBrate\fP"
.br
.ti -1c
.RI "float \fBm_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file psy\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float* vorbis_look_psy::ath"

.PP
Definition at line 102 of file psy\&.h\&.
.SS "long* vorbis_look_psy::bark"

.PP
Definition at line 104 of file psy\&.h\&.
.SS "\fBint\fP vorbis_look_psy::eighth_octave_lines"

.PP
Definition at line 108 of file psy\&.h\&.
.SS "long vorbis_look_psy::firstoc"

.PP
Definition at line 106 of file psy\&.h\&.
.SS "float vorbis_look_psy::m_val"

.PP
Definition at line 112 of file psy\&.h\&.
.SS "\fBint\fP vorbis_look_psy::n"

.PP
Definition at line 96 of file psy\&.h\&.
.SS "float** vorbis_look_psy::noiseoffset"

.PP
Definition at line 100 of file psy\&.h\&.
.SS "long* vorbis_look_psy::octave"

.PP
Definition at line 103 of file psy\&.h\&.
.SS "long vorbis_look_psy::rate"

.PP
Definition at line 110 of file psy\&.h\&.
.SS "long vorbis_look_psy::shiftoc"

.PP
Definition at line 107 of file psy\&.h\&.
.SS "float*** vorbis_look_psy::tonecurves"

.PP
Definition at line 99 of file psy\&.h\&.
.SS "\fBint\fP vorbis_look_psy::total_octave_lines"

.PP
Definition at line 109 of file psy\&.h\&.
.SS "struct \fBvorbis_info_psy\fP* vorbis_look_psy::vi"

.PP
Definition at line 97 of file psy\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
