.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/vq/vqgen.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libvorbis/vq/vqgen.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'vqgen\&.h'\fP
.br
\fC#include 'bookutil\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBvN\fP(\fBdata\fP,  \fBi\fP)   (\fBdata\fP+v\->elements*\fBi\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fB_dist\fP (\fBvqgen\fP *v, float *\fBa\fP, float *\fBb\fP)"
.br
.ti -1c
.RI "float * \fB_weight_null\fP (\fBvqgen\fP *v, float *\fBa\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_vqgen_seed\fP (\fBvqgen\fP *v)"
.br
.ti -1c
.RI "\fBint\fP \fBdirectdsort\fP (\fBconst\fP \fBvoid\fP *\fBa\fP, \fBconst\fP \fBvoid\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_cellmetric\fP (\fBvqgen\fP *v)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_quantize\fP (\fBvqgen\fP *v, \fBquant_meta\fP *\fBq\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_unquantize\fP (\fBvqgen\fP *v, \fBquant_meta\fP *\fBq\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_init\fP (\fBvqgen\fP *v, \fBint\fP elements, \fBint\fP aux, \fBint\fP entries, float mindist, float(*metric)(\fBvqgen\fP *, float *, float *), float *(*\fBweight\fP)(\fBvqgen\fP *, float *), \fBint\fP centroid)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_addpoint\fP (\fBvqgen\fP *v, float *\fBp\fP, float *\fBa\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBvqgen_sortmesh\fP (\fBvqgen\fP *v)"
.br
.ti -1c
.RI "float \fBvqgen_iterate\fP (\fBvqgen\fP *v, \fBint\fP biasp)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define vN(\fBdata\fP, \fBi\fP)   (\fBdata\fP+v\->elements*\fBi\fP)"

.PP
Definition at line 57 of file vqgen\&.c\&.
.SH "Function Documentation"
.PP 
.SS "float _dist (\fBvqgen\fP * v, float * a, float * b)"

.PP
Definition at line 60 of file vqgen\&.c\&.
.SS "\fBvoid\fP _vqgen_seed (\fBvqgen\fP * v)"

.PP
Definition at line 76 of file vqgen\&.c\&.
.SS "float* _weight_null (\fBvqgen\fP * v, float * a)"

.PP
Definition at line 71 of file vqgen\&.c\&.
.SS "\fBint\fP directdsort (\fBconst\fP \fBvoid\fP * a, \fBconst\fP \fBvoid\fP * b)"

.PP
Definition at line 83 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_addpoint (\fBvqgen\fP * v, float * p, float * a)"

.PP
Definition at line 270 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_cellmetric (\fBvqgen\fP * v)"

.PP
Definition at line 89 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_init (\fBvqgen\fP * v, \fBint\fP elements, \fBint\fP aux, \fBint\fP entries, float mindist, float(*)(\fBvqgen\fP *, float *, float *) metric, float *(*)(\fBvqgen\fP *, float *) weight, \fBint\fP centroid)"

.PP
Definition at line 240 of file vqgen\&.c\&.
.SS "float vqgen_iterate (\fBvqgen\fP * v, \fBint\fP biasp)"

.PP
Definition at line 333 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_quantize (\fBvqgen\fP * v, \fBquant_meta\fP * q)"

.PP
Definition at line 165 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_sortmesh (\fBvqgen\fP * v)"

.PP
Definition at line 305 of file vqgen\&.c\&.
.SS "\fBvoid\fP vqgen_unquantize (\fBvqgen\fP * v, \fBquant_meta\fP * q)"

.PP
Definition at line 224 of file vqgen\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
