.TH "VSTControlBase" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSTControlBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VSTControl\&.h>\fP
.PP
Inherits wxControl\&.
.PP
Inherited by \fBVSTControl\fP, \fBVSTControl\fP, and \fBVSTControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVSTControlBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~VSTControlBase\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBCreate\fP (wxWindow *parent, \fBVSTEffectLink\fP *link)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxWindow * \fBmParent\fP"
.br
.ti -1c
.RI "\fBVSTEffectLink\fP * \fBmLink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file VSTControl\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VSTControlBase::VSTControlBase ()\fC [inline]\fP"

.PP
Definition at line 29 of file VSTControl\&.h\&.
.SS "virtual VSTControlBase::~VSTControlBase ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 35 of file VSTControl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBbool\fP VSTControlBase::Create (wxWindow * parent, \fBVSTEffectLink\fP * link)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBVSTControl\fP, \fBVSTControl\fP, and \fBVSTControl\fP\&.
.PP
Definition at line 39 of file VSTControl\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVSTEffectLink\fP* VSTControlBase::mLink\fC [protected]\fP"

.PP
Definition at line 54 of file VSTControl\&.h\&.
.SS "wxWindow* VSTControlBase::mParent\fC [protected]\fP"

.PP
Definition at line 53 of file VSTControl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
