.TH "C:/_dev/OpenU/Audacity/audacity/src/effects/VST/VSTControlOSX.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/effects/VST/VSTControlOSX.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Carbon/Carbon\&.h>\fP
.br
\fC#include <wx/osx/private\&.h>\fP
.br
\fC#include <wx/control\&.h>\fP
.br
\fC#include 'aeffectx\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVSTControlImpl\fP"
.br
.ti -1c
.RI "class \fBVSTControl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
