.TH "VSTControlImpl" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSTControlImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VSTControlOSX\&.h>\fP
.PP
Inherits wxWidgetCocoaImpl\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVSTControlImpl\fP (wxWindowMac *peer, NSView *view)"
.br
.ti -1c
.RI "\fB~VSTControlImpl\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file VSTControlOSX\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VSTControlImpl::VSTControlImpl (wxWindowMac * peer, NSView * view)"

.PP
Definition at line 44 of file VSTControlOSX\&.mm\&.
.SS "VSTControlImpl::~VSTControlImpl ()"

.PP
Definition at line 49 of file VSTControlOSX\&.mm\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
