.TH "waflib.Tools.c_aliases" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.c_aliases \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_extensions\fP (lst)"
.br
.ti -1c
.RI "def \fBsniff_features\fP (kw)"
.br
.ti -1c
.RI "def \fBset_features\fP (kw, _type)"
.br
.ti -1c
.RI "def \fBprogram\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBshlib\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBstlib\fP (bld, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBobjects\fP (bld, \fBk\fP, kw)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.c_aliases\&.get_extensions ( lst)"

.PP
Definition at line 8 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.objects ( bld,  k,  kw)"

.PP
Definition at line 53 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.program ( bld,  k,  kw)"

.PP
Definition at line 41 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.set_features ( kw,  _type)"

.PP
Definition at line 37 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.shlib ( bld,  k,  kw)"

.PP
Definition at line 45 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.sniff_features ( kw)"

.PP
Definition at line 18 of file c_aliases\&.py\&.
.SS "def waflib\&.Tools\&.c_aliases\&.stlib ( bld,  k,  kw)"

.PP
Definition at line 49 of file c_aliases\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
