.TH "waflib.Tools.c.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.c.c \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, \fBwaflib\&.Task\&.Task\fP, and \fBwaflib\&.Task\&.Task\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBrun_str\fP = '${CC} ${ARCH_ST:ARCH} ${CFLAGS} ${CPPFLAGS} ${FRAMEWORKPATH_ST:FRAMEWORKPATH} ${CPPPATH_ST:INCPATHS} ${DEFINES_ST:DEFINES} ${CC_SRC_F}${SRC} ${CC_TGT_F}${TGT}'"
.br
.ti -1c
.RI "list \fBvars\fP = ['CCDEPS']"
.br
.ti -1c
.RI "list \fBext_in\fP = ['\&.h']"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file c\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "list waflib\&.Tools\&.c\&.c\&.ext_in = ['\&.h']\fC [static]\fP"

.PP
Definition at line 14 of file c\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c\&.c\&.run_str = '${CC} ${ARCH_ST:ARCH} ${CFLAGS} ${CPPFLAGS} ${FRAMEWORKPATH_ST:FRAMEWORKPATH} ${CPPPATH_ST:INCPATHS} ${DEFINES_ST:DEFINES} ${CC_SRC_F}${SRC} ${CC_TGT_F}${TGT}'\fC [static]\fP"

.PP
Definition at line 12 of file c\&.py\&.
.SS "list waflib\&.Tools\&.c\&.c\&.vars = ['CCDEPS']\fC [static]\fP"

.PP
Definition at line 13 of file c\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
