.TH "waflib.Scripting.Dist" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Scripting.Dist \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, \fBwaflib\&.Context\&.Context\fP, and \fBwaflib\&.Context\&.Context\fP\&.
.PP
Inherited by \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, \fBwaflib\&.Scripting\&.DistCheck\fP, and \fBwaflib\&.Scripting\&.DistCheck\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.ti -1c
.RI "def \fBexecute\fP (self)"
.br
.ti -1c
.RI "def \fBarchive\fP (self)"
.br
.ti -1c
.RI "def \fBget_tar_path\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBadd_tar_file\fP (self, x, tar)"
.br
.ti -1c
.RI "def \fBget_tar_prefix\fP (self)"
.br
.ti -1c
.RI "def \fBget_arch_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_base_name\fP (self)"
.br
.ti -1c
.RI "def \fBget_excl\fP (self)"
.br
.ti -1c
.RI "def \fBget_files\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbase_path\fP"
.br
.ti -1c
.RI "\fBalgo\fP"
.br
.ti -1c
.RI "\fBarch_name\fP"
.br
.ti -1c
.RI "\fBbase_name\fP"
.br
.ti -1c
.RI "\fBexcl\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBcmd\fP = '\fBdist\fP'"
.br
.ti -1c
.RI "\fBstring\fP \fBfun\fP = '\fBdist\fP'"
.br
.ti -1c
.RI "\fBstring\fP \fBalgo\fP = 'tar\&.bz2'"
.br
.ti -1c
.RI "dictionary \fBext_algo\fP = {}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
creates an archive containing the project source code
.fi
.PP
 
.PP
Definition at line 210 of file Scripting\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.add_tar_file ( self,  x,  tar)"

.PP
Definition at line 257 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.archive ( self)"

.PP
Definition at line 219 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.execute ( self)"

.PP
Definition at line 216 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_arch_name ( self)"

.PP
Definition at line 276 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_base_name ( self)"

.PP
Definition at line 282 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_excl ( self)"

.PP
Definition at line 290 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_files ( self)"

.PP
Definition at line 299 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_path ( self,  node)"

.PP
Definition at line 255 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SS "def waflib\&.Scripting\&.Dist\&.get_tar_prefix ( self)"

.PP
Definition at line 271 of file Scripting\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBstring\fP waflib\&.Scripting\&.Dist\&.algo = 'tar\&.bz2'\fC [static]\fP"

.PP
Definition at line 214 of file Scripting\&.py\&.
.SS "waflib\&.Scripting\&.Dist\&.algo"

.PP
Definition at line 237 of file Scripting\&.py\&.
.SS "waflib\&.Scripting\&.Dist\&.arch_name"

.PP
Definition at line 280 of file Scripting\&.py\&.
.SS "waflib\&.Scripting\&.Dist\&.base_name"

.PP
Definition at line 288 of file Scripting\&.py\&.
.SS "waflib\&.Scripting\&.Dist\&.base_path"

.PP
Definition at line 225 of file Scripting\&.py\&.
.SS "\fBstring\fP waflib\&.Scripting\&.Dist\&.cmd = '\fBdist\fP'\fC [static]\fP"

.PP
Definition at line 212 of file Scripting\&.py\&.
.SS "waflib\&.Scripting\&.Dist\&.excl"

.PP
Definition at line 294 of file Scripting\&.py\&.
.SS "dictionary waflib\&.Scripting\&.Dist\&.ext_algo = {}\fC [static]\fP"

.PP
Definition at line 215 of file Scripting\&.py\&.
.SS "\fBstring\fP waflib\&.Scripting\&.Dist\&.fun = '\fBdist\fP'\fC [static]\fP"

.PP
Definition at line 213 of file Scripting\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
