.TH "waflib.ansiterm" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.ansiterm \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnsiTerm\fP"
.br
.ti -1c
.RI "class \fBCONSOLE_CURSOR_INFO\fP"
.br
.ti -1c
.RI "class \fBCONSOLE_SCREEN_BUFFER_INFO\fP"
.br
.ti -1c
.RI "class \fBCOORD\fP"
.br
.ti -1c
.RI "class \fBSMALL_RECT\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargtypes\fP"
.br
.ti -1c
.RI "\fBrestype\fP"
.br
.ti -1c
.RI "\fBsbinfo\fP = \fBCONSOLE_SCREEN_BUFFER_INFO\fP()"
.br
.ti -1c
.RI "\fBcsinfo\fP = \fBCONSOLE_CURSOR_INFO\fP()"
.br
.ti -1c
.RI "\fBhconsole\fP = windll\&.kernel32\&.GetStdHandle(\-11)"
.br
.ti -1c
.RI "\fBint\fP \fBis_vista\fP = 6"
.br
.ti -1c
.RI "\fBto_int\fP = lambdanumber,default:numberandint(number)ordefault"
.br
.ti -1c
.RI "\fBwlock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "\fBint\fP \fBSTD_OUTPUT_HANDLE\fP = \-11"
.br
.ti -1c
.RI "\fBint\fP \fBSTD_ERROR_HANDLE\fP = \-12"
.br
.ti -1c
.RI "\fBstderr\fP"
.br
.ti -1c
.RI "\fBstdout\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "waflib\&.ansiterm\&.argtypes"

.PP
Definition at line 18 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.csinfo = \fBCONSOLE_CURSOR_INFO\fP()"

.PP
Definition at line 33 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.hconsole = windll\&.kernel32\&.GetStdHandle(\-11)"

.PP
Definition at line 34 of file ansiterm\&.py\&.
.SS "\fBint\fP waflib\&.ansiterm\&.is_vista = 6"

.PP
Definition at line 42 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.restype"

.PP
Definition at line 19 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.sbinfo = \fBCONSOLE_SCREEN_BUFFER_INFO\fP()"

.PP
Definition at line 32 of file ansiterm\&.py\&.
.SS "\fBint\fP waflib\&.ansiterm\&.STD_ERROR_HANDLE = \-12"

.PP
Definition at line 50 of file ansiterm\&.py\&.
.SS "\fBint\fP waflib\&.ansiterm\&.STD_OUTPUT_HANDLE = \-11"

.PP
Definition at line 49 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.stderr"

.PP
Definition at line 190 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.stdout"

.PP
Definition at line 190 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.to_int = lambdanumber,default:numberandint(number)ordefault"

.PP
Definition at line 47 of file ansiterm\&.py\&.
.SS "waflib\&.ansiterm\&.wlock = threading\&.Lock()"

.PP
Definition at line 48 of file ansiterm\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
