.TH "waflib.Tools.c_config" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.c_config \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcfgtask\fP"
.br
.ti -1c
.RI "class \fBtest_exec\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBparse_flags\fP (self, \fBline\fP, uselib_store, env=None, force_static=False)"
.br
.ti -1c
.RI "def \fBret_msg\fP (self, \fBf\fP, kw)"
.br
.ti -1c
.RI "def \fBvalidate_cfg\fP (self, kw)"
.br
.ti -1c
.RI "def \fBexec_cfg\fP (self, kw)"
.br
.ti -1c
.RI "def \fBcheck_cfg\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBvalidate_c\fP (self, kw)"
.br
.ti -1c
.RI "def \fBpost_check\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBcheck\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBtest_exec_fun\fP (self)"
.br
.ti -1c
.RI "def \fBrun_c_code\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBcheck_cxx\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBcheck_cc\fP (self, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBdefine\fP (self, key, val, quote=True)"
.br
.ti -1c
.RI "def \fBundefine\fP (self, key)"
.br
.ti -1c
.RI "def \fBdefine_cond\fP (self, key, val)"
.br
.ti -1c
.RI "def \fBis_defined\fP (self, key)"
.br
.ti -1c
.RI "def \fBget_define\fP (self, key)"
.br
.ti -1c
.RI "def \fBhave_define\fP (self, key)"
.br
.ti -1c
.RI "def \fBwrite_config_header\fP (self, configfile='', guard='', top=False, env=None, defines=True, headers=False, remove=True, define_prefix='')"
.br
.ti -1c
.RI "def \fBget_config_header\fP (self, defines=True, headers=False, define_prefix='')"
.br
.ti -1c
.RI "def \fBcc_add_flags\fP (conf)"
.br
.ti -1c
.RI "def \fBcxx_add_flags\fP (conf)"
.br
.ti -1c
.RI "def \fBlink_add_flags\fP (conf)"
.br
.ti -1c
.RI "def \fBcc_load_tools\fP (conf)"
.br
.ti -1c
.RI "def \fBcxx_load_tools\fP (conf)"
.br
.ti -1c
.RI "def \fBget_cc_version\fP (conf, cc, gcc=False, icc=False)"
.br
.ti -1c
.RI "def \fBget_xlc_version\fP (conf, cc)"
.br
.ti -1c
.RI "def \fBget_suncc_version\fP (conf, cc)"
.br
.ti -1c
.RI "def \fBadd_as_needed\fP (self)"
.br
.ti -1c
.RI "def \fBmulticheck\fP (self, \fBk\fP, kw)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBWAF_CONFIG_H\fP = 'config\&.h'"
.br
.ti -1c
.RI "\fBstring\fP \fBDEFKEYS\fP = 'define_key'"
.br
.ti -1c
.RI "\fBstring\fP \fBINCKEYS\fP = 'include_key'"
.br
.ti -1c
.RI "dictionary \fBcfg_ver\fP = {'atleast\-\fBversion\fP':'>=','exact\-\fBversion\fP':'==','\fBmax\fP\-\fBversion\fP':'<=',}"
.br
.ti -1c
.RI "\fBstring\fP \fBSNIP_FUNCTION\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBSNIP_TYPE\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBSNIP_EMPTY_PROGRAM\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBSNIP_FIELD\fP"
.br
.ti -1c
.RI "dictionary \fBMACRO_TO_DESTOS\fP = {'__linux__':'linux','__GNU__':'gnu','__FreeBSD__':'freebsd','__NetBSD__':'netbsd','__OpenBSD__':'openbsd','__sun':'sunos','__hpux':'hpux','__sgi':'irix','_AIX':'aix','__CYGWIN__':'cygwin','__MSYS__':'msys','_UWIN':'uwin','_WIN64':'win32','_WIN32':'win32','__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__':'darwin','__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__':'darwin','__QNX__':'qnx','__native_client__':'nacl'}"
.br
.ti -1c
.RI "dictionary \fBMACRO_TO_DEST_CPU\fP = {'__x86_64__':'x86_64','__amd64__':'x86_64','__i386__':'x86','__ia64__':'ia','__mips__':'mips','__sparc__':'sparc','__alpha__':'alpha','__aarch64__':'aarch64','__thumb__':'thumb','__arm__':'arm','__hppa__':'hppa','__powerpc__':'powerpc','__ppc__':'powerpc','__convex__':'convex','__m68k__':'m68k','__s390x__':'s390x','__s390__':'s390','__sh__':'sh',}"
.br
.ti -1c
.RI "\fBtest_bld\fP"
.br
.ti -1c
.RI "\fBkeep\fP"
.br
.ti -1c
.RI "\fBcache_global\fP"
.br
.ti -1c
.RI "\fBnocache\fP"
.br
.ti -1c
.RI "\fBreturned_tasks\fP"
.br
.ti -1c
.RI "\fBtask_sigs\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.c_config\&.add_as_needed ( self)"

.PP
Definition at line 693 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.cc_add_flags ( conf)"

.PP
Definition at line 567 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.cc_load_tools ( conf)"

.PP
Definition at line 579 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.check ( self,  k,  kw)"

.PP
Definition at line 371 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.check_cc ( self,  k,  kw)"

.PP
Definition at line 476 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.check_cfg ( self,  k,  kw)"

.PP
Definition at line 190 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.check_cxx ( self,  k,  kw)"

.PP
Definition at line 472 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.cxx_add_flags ( conf)"

.PP
Definition at line 571 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.cxx_load_tools ( conf)"

.PP
Definition at line 584 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.define ( self,  key,  val,  quote = \fCTrue\fP)"

.PP
Definition at line 480 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.define_cond ( self,  key,  val)"

.PP
Definition at line 508 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.exec_cfg ( self,  kw)"

.PP
Definition at line 138 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.get_cc_version ( conf,  cc,  gcc = \fCFalse\fP,  icc = \fCFalse\fP)"

.PP
Definition at line 589 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.get_config_header ( self,  defines = \fCTrue\fP,  headers = \fCFalse\fP,  define_prefix = \fC''\fP)"

.PP
Definition at line 553 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.get_define ( self,  key)"

.PP
Definition at line 523 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.get_suncc_version ( conf,  cc)"

.PP
Definition at line 674 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.get_xlc_version ( conf,  cc)"

.PP
Definition at line 658 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.have_define ( self,  key)"

.PP
Definition at line 531 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.is_defined ( self,  key)"

.PP
Definition at line 515 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.link_add_flags ( conf)"

.PP
Definition at line 575 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.multicheck ( self,  k,  kw)"

.PP
Definition at line 715 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.parse_flags ( self,  line,  uselib_store,  env = \fCNone\fP,  force_static = \fCFalse\fP)"

.PP
Definition at line 46 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.post_check ( self,  k,  kw)"

.PP
Definition at line 335 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.ret_msg ( self,  f,  kw)"

.PP
Definition at line 105 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.run_c_code ( self,  k,  kw)"

.PP
Definition at line 416 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.test_exec_fun ( self)"

.PP
Definition at line 411 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.undefine ( self,  key)"

.PP
Definition at line 501 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.validate_c ( self,  kw)"

.PP
Definition at line 216 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.validate_cfg ( self,  kw)"

.PP
Definition at line 110 of file c_config\&.py\&.
.SS "def waflib\&.Tools\&.c_config\&.write_config_header ( self,  configfile = \fC''\fP,  guard = \fC''\fP,  top = \fCFalse\fP,  env = \fCNone\fP,  defines = \fCTrue\fP,  headers = \fCFalse\fP,  remove = \fCTrue\fP,  define_prefix = \fC''\fP)"

.PP
Definition at line 534 of file c_config\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "waflib\&.Tools\&.c_config\&.cache_global"

.PP
Definition at line 720 of file c_config\&.py\&.
.SS "dictionary waflib\&.Tools\&.c_config\&.cfg_ver = {'atleast\-\fBversion\fP':'>=','exact\-\fBversion\fP':'==','\fBmax\fP\-\fBversion\fP':'<=',}"

.PP
Definition at line 12 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.DEFKEYS = 'define_key'"

.PP
Definition at line 10 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.INCKEYS = 'include_key'"

.PP
Definition at line 11 of file c_config\&.py\&.
.SS "waflib\&.Tools\&.c_config\&.keep"

.PP
Definition at line 719 of file c_config\&.py\&.
.SS "dictionary waflib\&.Tools\&.c_config\&.MACRO_TO_DEST_CPU = {'__x86_64__':'x86_64','__amd64__':'x86_64','__i386__':'x86','__ia64__':'ia','__mips__':'mips','__sparc__':'sparc','__alpha__':'alpha','__aarch64__':'aarch64','__thumb__':'thumb','__arm__':'arm','__hppa__':'hppa','__powerpc__':'powerpc','__ppc__':'powerpc','__convex__':'convex','__m68k__':'m68k','__s390x__':'s390x','__s390__':'s390','__sh__':'sh',}"

.PP
Definition at line 44 of file c_config\&.py\&.
.SS "dictionary waflib\&.Tools\&.c_config\&.MACRO_TO_DESTOS = {'__linux__':'linux','__GNU__':'gnu','__FreeBSD__':'freebsd','__NetBSD__':'netbsd','__OpenBSD__':'openbsd','__sun':'sunos','__hpux':'hpux','__sgi':'irix','_AIX':'aix','__CYGWIN__':'cygwin','__MSYS__':'msys','_UWIN':'uwin','_WIN64':'win32','_WIN32':'win32','__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__':'darwin','__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__':'darwin','__QNX__':'qnx','__native_client__':'nacl'}"

.PP
Definition at line 43 of file c_config\&.py\&.
.SS "waflib\&.Tools\&.c_config\&.nocache"

.PP
Definition at line 721 of file c_config\&.py\&.
.SS "waflib\&.Tools\&.c_config\&.returned_tasks"

.PP
Definition at line 722 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.SNIP_EMPTY_PROGRAM"
\fBInitial value:\fP
.PP
.nf
1 = '''
2 int main(int argc, char **argv) {
3     (void)argc; (void)argv;
4     return 0;
5 }
6 '''
.fi
.PP
Definition at line 29 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.SNIP_FIELD"
\fBInitial value:\fP
.PP
.nf
1 = '''
2 int main(int argc, char **argv) {
3     char *off;
4     (void)argc; (void)argv;
5     off = (char*) &((%(type_name)s*)0)->%(field_name)s;
6     return (size_t) off < sizeof(%(type_name)s);
7 }
8 '''
.fi
.PP
Definition at line 35 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.SNIP_FUNCTION"
\fBInitial value:\fP
.PP
.nf
1 = '''
2 int main(int argc, char **argv) {
3     void *p;
4     (void)argc; (void)argv;
5     p=(void*)(%s);
6     return 0;
7 }
8 '''
.fi
.PP
Definition at line 13 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.SNIP_TYPE"
\fBInitial value:\fP
.PP
.nf
1 = '''
2 int main(int argc, char **argv) {
3     (void)argc; (void)argv;
4     if ((%(type_name)s *) 0) return 0;
5     if (sizeof (%(type_name)s)) return 0;
6     return 1;
7 }
8 '''
.fi
.PP
Definition at line 21 of file c_config\&.py\&.
.SS "waflib\&.Tools\&.c_config\&.task_sigs"

.PP
Definition at line 723 of file c_config\&.py\&.
.SS "waflib\&.Tools\&.c_config\&.test_bld"

.PP
Definition at line 442 of file c_config\&.py\&.
.SS "\fBstring\fP waflib\&.Tools\&.c_config\&.WAF_CONFIG_H = 'config\&.h'"

.PP
Definition at line 9 of file c_config\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
