.TH "waflib.Context" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Context \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContext\fP"
.br
.ti -1c
.RI "class \fBstore_context\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcreate_context\fP (cmd_name, \fBk\fP, kw)"
.br
.ti -1c
.RI "def \fBload_module\fP (path)"
.br
.ti -1c
.RI "def \fBload_tool\fP (tool, tooldir=None)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBHEXVERSION\fP = 0x1071000"
.br
.ti -1c
.RI "\fBstring\fP \fBWAFVERSION\fP = '1\&.7\&.16'"
.br
.ti -1c
.RI "\fBstring\fP \fBWAFREVISION\fP = '73c1705078f8c9c51a33e20f221a309d5a94b5e1'"
.br
.ti -1c
.RI "\fBint\fP \fBABI\fP = 98"
.br
.ti -1c
.RI "\fBstring\fP \fBDBFILE\fP = '\&.wafpickle\-%\fBs\fP\-%\fBd\fP\-%\fBd\fP'"
.br
.ti -1c
.RI "\fBstring\fP \fBAPPNAME\fP = 'APPNAME'"
.br
.ti -1c
.RI "\fBstring\fP \fBVERSION\fP = 'VERSION'"
.br
.ti -1c
.RI "\fBstring\fP \fBTOP\fP = 'top'"
.br
.ti -1c
.RI "\fBstring\fP \fBOUT\fP = '\fBout\fP'"
.br
.ti -1c
.RI "\fBstring\fP \fBWSCRIPT_FILE\fP = 'wscript'"
.br
.ti -1c
.RI "\fBstring\fP \fBlaunch_dir\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBrun_dir\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBtop_dir\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBout_dir\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBwaf_dir\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBlocal_repo\fP = ''"
.br
.ti -1c
.RI "\fBstring\fP \fBremote_repo\fP = 'http://waf\&.googlecode\&.com/git/'"
.br
.ti -1c
.RI "list \fBremote_locs\fP = ['waflib/extras','waflib/Tools']"
.br
.ti -1c
.RI "\fBg_module\fP = None"
.br
.ti -1c
.RI "\fBint\fP \fBSTDOUT\fP = 1"
.br
.ti -1c
.RI "\fBint\fP \fBSTDERR\fP = \-1"
.br
.ti -1c
.RI "\fBint\fP \fBBOTH\fP = 0"
.br
.ti -1c
.RI "list \fBclasses\fP = []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Context\&.create_context ( cmd_name,  k,  kw)"

.PP
Definition at line 31 of file Context\&.py\&.
.SS "def waflib\&.Context\&.load_module ( path)"

.PP
Definition at line 266 of file Context\&.py\&.
.SS "def waflib\&.Context\&.load_tool ( tool,  tooldir = \fCNone\fP)"

.PP
Definition at line 282 of file Context\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint\fP waflib\&.Context\&.ABI = 98"

.PP
Definition at line 11 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.APPNAME = 'APPNAME'"

.PP
Definition at line 13 of file Context\&.py\&.
.SS "\fBint\fP waflib\&.Context\&.BOTH = 0"

.PP
Definition at line 29 of file Context\&.py\&.
.SS "list waflib\&.Context\&.classes = []"

.PP
Definition at line 30 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.DBFILE = '\&.wafpickle\-%\fBs\fP\-%\fBd\fP\-%\fBd\fP'"

.PP
Definition at line 12 of file Context\&.py\&.
.SS "waflib\&.Context\&.g_module = None"

.PP
Definition at line 26 of file Context\&.py\&.
.SS "\fBint\fP waflib\&.Context\&.HEXVERSION = 0x1071000"

.PP
Definition at line 8 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.launch_dir = ''"

.PP
Definition at line 18 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.local_repo = ''"

.PP
Definition at line 23 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.OUT = '\fBout\fP'"

.PP
Definition at line 16 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.out_dir = ''"

.PP
Definition at line 21 of file Context\&.py\&.
.SS "list waflib\&.Context\&.remote_locs = ['waflib/extras','waflib/Tools']"

.PP
Definition at line 25 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.remote_repo = 'http://waf\&.googlecode\&.com/git/'"

.PP
Definition at line 24 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.run_dir = ''"

.PP
Definition at line 19 of file Context\&.py\&.
.SS "\fBint\fP waflib\&.Context\&.STDERR = \-1"

.PP
Definition at line 28 of file Context\&.py\&.
.SS "\fBint\fP waflib\&.Context\&.STDOUT = 1"

.PP
Definition at line 27 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.TOP = 'top'"

.PP
Definition at line 15 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.top_dir = ''"

.PP
Definition at line 20 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.VERSION = 'VERSION'"

.PP
Definition at line 14 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.waf_dir = ''"

.PP
Definition at line 22 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.WAFREVISION = '73c1705078f8c9c51a33e20f221a309d5a94b5e1'"

.PP
Definition at line 10 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.WAFVERSION = '1\&.7\&.16'"

.PP
Definition at line 9 of file Context\&.py\&.
.SS "\fBstring\fP waflib\&.Context\&.WSCRIPT_FILE = 'wscript'"

.PP
Definition at line 17 of file Context\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
