.TH "waflib.fixpy2" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.fixpy2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfixdir\fP (dir)"
.br
.ti -1c
.RI "def \fBmodif\fP (dir, \fBname\fP, fun)"
.br
.ti -1c
.RI "def \fBsubst\fP (\fBk\fP)"
.br
.ti -1c
.RI "def \fBr1\fP (code)"
.br
.ti -1c
.RI "def \fBr4\fP (code)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBall_modifs\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.fixpy2\&.fixdir ( dir)"

.PP
Definition at line 7 of file fixpy2\&.py\&.
.SS "def waflib\&.fixpy2\&.modif ( dir,  name,  fun)"

.PP
Definition at line 12 of file fixpy2\&.py\&.
.SS "def waflib\&.fixpy2\&.r1 ( code)"

.PP
Definition at line 45 of file fixpy2\&.py\&.
.SS "def waflib\&.fixpy2\&.r4 ( code)"

.PP
Definition at line 51 of file fixpy2\&.py\&.
.SS "def waflib\&.fixpy2\&.subst ( k)"

.PP
Definition at line 34 of file fixpy2\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "dictionary waflib\&.fixpy2\&.all_modifs = {}"

.PP
Definition at line 6 of file fixpy2\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
