.TH "waflib.Tools.lua" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.lua \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBluac\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBadd_lua\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBconfigure\fP (conf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.lua\&.add_lua ( self,  node)"

.PP
Definition at line 8 of file lua\&.py\&.
.SS "def waflib\&.Tools\&.lua\&.configure ( conf)"

.PP
Definition at line 17 of file lua\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
