.TH "waflib.Logs.color_dict" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Logs.color_dict \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object, object, object, object, object, object, object, object, object, object, and object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__getattr__\fP (self, \fBa\fP)"
.br
.ti -1c
.RI "def \fB__call__\fP (self, \fBa\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file Logs\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__call__ ( self,  a)"

.PP
Definition at line 83 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.
.SS "def waflib\&.Logs\&.color_dict\&.__getattr__ ( self,  a)"

.PP
Definition at line 81 of file Logs\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
