.TH "waflib.Tools.cs" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfake_csshlib\fP"
.br
.ti -1c
.RI "class \fBmcs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBapply_cs\fP (self)"
.br
.ti -1c
.RI "def \fBuse_cs\fP (self)"
.br
.ti -1c
.RI "def \fBdebug_cs\fP (self)"
.br
.ti -1c
.RI "def \fBconfigure\fP (conf)"
.br
.ti -1c
.RI "def \fBoptions\fP (opt)"
.br
.ti -1c
.RI "def \fBread_csshlib\fP (self, \fBname\fP, paths=[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsource\fP"
.br
.ti -1c
.RI "\fBcs_task\fP"
.br
.ti -1c
.RI "\fBinstall_task\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.cs\&.apply_cs ( self)"

.PP
Definition at line 14 of file cs\&.py\&.
.SS "def waflib\&.Tools\&.cs\&.configure ( conf)"

.PP
Definition at line 111 of file cs\&.py\&.
.SS "def waflib\&.Tools\&.cs\&.debug_cs ( self)"

.PP
Definition at line 52 of file cs\&.py\&.
.SS "def waflib\&.Tools\&.cs\&.options ( opt)"

.PP
Definition at line 121 of file cs\&.py\&.
.SS "def waflib\&.Tools\&.cs\&.read_csshlib ( self,  name,  paths = \fC[]\fP)"

.PP
Definition at line 131 of file cs\&.py\&.
.SS "def waflib\&.Tools\&.cs\&.use_cs ( self)"

.PP
Definition at line 34 of file cs\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "waflib\&.Tools\&.cs\&.cs_task"

.PP
Definition at line 24 of file cs\&.py\&.
.SS "waflib\&.Tools\&.cs\&.install_task"

.PP
Definition at line 31 of file cs\&.py\&.
.SS "waflib\&.Tools\&.cs\&.source"

.PP
Definition at line 22 of file cs\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
