.TH "waflib.Tools.gdc" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.gdc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfind_gdc\fP (conf)"
.br
.ti -1c
.RI "def \fBcommon_flags_gdc\fP (conf)"
.br
.ti -1c
.RI "def \fBconfigure\fP (conf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.gdc\&.common_flags_gdc ( conf)"

.PP
Definition at line 15 of file gdc\&.py\&.
.SS "def waflib\&.Tools\&.gdc\&.configure ( conf)"

.PP
Definition at line 31 of file gdc\&.py\&.
.SS "def waflib\&.Tools\&.gdc\&.find_gdc ( conf)"

.PP
Definition at line 9 of file gdc\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
