.TH "waflib.Tools.d" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Tools.d \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBd\fP"
.br
.ti -1c
.RI "class \fBd_header\fP"
.br
.ti -1c
.RI "class \fBd_with_header\fP"
.br
.ti -1c
.RI "class \fBdprogram\fP"
.br
.ti -1c
.RI "class \fBdshlib\fP"
.br
.ti -1c
.RI "class \fBdstlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBd_hook\fP (self, \fBnode\fP)"
.br
.ti -1c
.RI "def \fBgenerate_header\fP (self, \fBfilename\fP)"
.br
.ti -1c
.RI "def \fBprocess_header\fP (self)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcompiled_tasks\fP"
.br
.ti -1c
.RI "\fBheader_lst\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def waflib\&.Tools\&.d\&.d_hook ( self,  node)"

.PP
Definition at line 26 of file d\&.py\&.
.SS "def waflib\&.Tools\&.d\&.generate_header ( self,  filename)"

.PP
Definition at line 43 of file d\&.py\&.
.SS "def waflib\&.Tools\&.d\&.process_header ( self)"

.PP
Definition at line 49 of file d\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "waflib\&.Tools\&.d\&.compiled_tasks"

.PP
Definition at line 34 of file d\&.py\&.
.SS "waflib\&.Tools\&.d\&.header_lst"

.PP
Definition at line 47 of file d\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
