.TH "waflib.Options" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
waflib.Options \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBopt_parser\fP"
.br
.ti -1c
.RI "class \fBOptionsContext\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBcmds\fP = 'distclean configure build install clean uninstall check dist distcheck'"
.br
.ti -1c
.RI "dictionary \fBoptions\fP = {}"
.br
.ti -1c
.RI "list \fBcommands\fP = []"
.br
.ti -1c
.RI "\fBlockfile\fP = os\&.environ\&.get('WAFLOCK','\&.lock\-waf_%s_build'%sys\&.platform)"
.br
.ti -1c
.RI "\fBcache_global\fP"
.br
.ti -1c
.RI "\fBplatform\fP = \fBUtils\&.unversioned_sys_platform\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "waflib\&.Options\&.cache_global"

.PP
Definition at line 11 of file Options\&.py\&.
.SS "\fBstring\fP waflib\&.Options\&.cmds = 'distclean configure build install clean uninstall check dist distcheck'"

.PP
Definition at line 7 of file Options\&.py\&.
.SS "list waflib\&.Options\&.commands = []"

.PP
Definition at line 9 of file Options\&.py\&.
.SS "waflib\&.Options\&.lockfile = os\&.environ\&.get('WAFLOCK','\&.lock\-waf_%s_build'%sys\&.platform)"

.PP
Definition at line 10 of file Options\&.py\&.
.SS "dictionary waflib\&.Options\&.options = {}"

.PP
Definition at line 8 of file Options\&.py\&.
.SS "waflib\&.Options\&.platform = \fBUtils\&.unversioned_sys_platform\fP()"

.PP
Definition at line 13 of file Options\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
