.TH "C:/_dev/OpenU/Audacity/audacity/src/prefs/WarningsPrefs.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/src/prefs/WarningsPrefs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/defs\&.h>\fP
.br
\fC#include <wx/window\&.h>\fP
.br
\fC#include 'PrefsPanel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWarningsPrefs\fP"
.br
.RI "\fIA \fBPrefsPanel\fP to enable/disable certain warning messages\&. \fP"
.ti -1c
.RI "class \fBWarningsPrefsFactory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
