.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/wav_w64.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libsndfile/src/wav_w64.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sfconfig\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'sndfile\&.h'\fP
.br
\fC#include 'sfendian\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'wav_w64\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBchanmap_s\fP"
.br
.ti -1c
.RI "struct \fBWAV_FORMAT_DESC\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTR\fP(x)   #x"
.br
.ti -1c
.RI "#define \fBFORMAT_TYPE\fP(x)   { x, \fBSTR\fP (x) }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBwav_w64_read_fmt_chunk\fP (\fBSF_PRIVATE\fP *psf, \fBint\fP fmtsize)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwavex_write_guid\fP (\fBSF_PRIVATE\fP *psf, \fBconst\fP \fBEXT_SUBFORMAT\fP *subformat)"
.br
.ti -1c
.RI "\fBint\fP \fBwavex_gen_channel_mask\fP (\fBconst\fP \fBint\fP *chan_map, \fBint\fP channels)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwav_w64_analyze\fP (\fBSF_PRIVATE\fP *psf)"
.br
.ti -1c
.RI "char \fBconst\fP * \fBwav_w64_format_str\fP (\fBint\fP \fBk\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBwav_w64_srate2blocksize\fP (\fBint\fP srate_chan_product)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FORMAT_TYPE(x)   { x, \fBSTR\fP (x) }"

.PP
Definition at line 529 of file wav_w64\&.c\&.
.SS "#define STR(x)   #x"

.PP
Definition at line 528 of file wav_w64\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP wav_w64_analyze (\fBSF_PRIVATE\fP * psf)"

.PP
Definition at line 464 of file wav_w64\&.c\&.
.SS "char \fBconst\fP* wav_w64_format_str (\fBint\fP k)"

.PP
Definition at line 641 of file wav_w64\&.c\&.
.SS "\fBint\fP wav_w64_read_fmt_chunk (\fBSF_PRIVATE\fP * psf, \fBint\fP fmtsize)"

.PP
Definition at line 113 of file wav_w64\&.c\&.
.SS "\fBint\fP wav_w64_srate2blocksize (\fBint\fP srate_chan_product)"

.PP
Definition at line 666 of file wav_w64\&.c\&.
.SS "\fBint\fP wavex_gen_channel_mask (\fBconst\fP \fBint\fP * chan_map, \fBint\fP channels)"

.PP
Definition at line 437 of file wav_w64\&.c\&.
.SS "\fBvoid\fP wavex_write_guid (\fBSF_PRIVATE\fP * psf, \fBconst\fP \fBEXT_SUBFORMAT\fP * subformat)"

.PP
Definition at line 428 of file wav_w64\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
