.TH "WaveTrackConstArray" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WaveTrackConstArray \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Track\&.h>\fP
.PP
Inherits vector< const WaveTrack * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWaveTrackConstArray\fP ()"
.br
.ti -1c
.RI "\fBWaveTrackConstArray\fP (std::initializer_list< value_type > tracks)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file Track\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WaveTrackConstArray::WaveTrackConstArray ()\fC [inline]\fP"

.PP
Definition at line 46 of file Track\&.h\&.
.SS "WaveTrackConstArray::WaveTrackConstArray (std::initializer_list< value_type > tracks)\fC [inline]\fP"

.PP
Definition at line 58 of file Track\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
