.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqstk/src/WaveLoop.cpp" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/nyqstk/src/WaveLoop.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'WaveLoop\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
