.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundStretch/WavFile.h" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/soundtouch/source/SoundStretch/WavFile.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWavRiff\fP"
.br
.RI "\fIWAV audio file 'riff' section header\&. \fP"
.ti -1c
.RI "struct \fBWavFormat\fP"
.br
.RI "\fIWAV audio file 'format' section header\&. \fP"
.ti -1c
.RI "struct \fBWavData\fP"
.br
.RI "\fIWAV audio file 'data' section header\&. \fP"
.ti -1c
.RI "struct \fBWavHeader\fP"
.br
.RI "\fIWAV audio file header\&. \fP"
.ti -1c
.RI "class \fBWavFileBase\fP"
.br
.RI "\fIBase class for processing WAV audio files\&. \fP"
.ti -1c
.RI "class \fBWavInFile\fP"
.br
.RI "\fIClass for reading WAV audio files\&. \fP"
.ti -1c
.RI "class \fBWavOutFile\fP"
.br
.RI "\fIClass for writing WAV audio files\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned \fBint\fP \fBuint\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned \fBint\fP \fBuint\fP"
Classes for easy reading & writing of WAV sound files\&.
.PP
For big-endian CPU, define BIG_ENDIAN during compile-time to correctly parse the WAV files with such processors\&.
.PP
Admittingly, more complete WAV reader routines may exist in public domain, but the reason for 'yet another' one is that those generic WAV reader libraries are exhaustingly large and cumbersome! Wanted to have something simpler here, i\&.e\&. something that's not already larger than rest of the SoundTouch/SoundStretch program\&.\&.\&.
.PP
Author : Copyright (c) Olli Parviainen Author e-mail : oparviai 'at' iki\&.fi SoundTouch WWW: http://www.surina.net/soundtouch 
.PP
Definition at line 53 of file WavFile\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
