.TH "WavHeader" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavHeader \- WAV audio file header\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WavFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWavRiff\fP \fBriff\fP"
.br
.ti -1c
.RI "\fBWavFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBWavData\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
WAV audio file header\&. 
.PP
Definition at line 87 of file WavFile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWavData\fP WavHeader::data"

.PP
Definition at line 91 of file WavFile\&.h\&.
.SS "\fBWavFormat\fP WavHeader::format"

.PP
Definition at line 90 of file WavFile\&.h\&.
.SS "\fBWavRiff\fP WavHeader::riff"

.PP
Definition at line 89 of file WavFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
