.TH "WavOutFile" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavOutFile \- Class for writing WAV audio files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WavFile\&.h>\fP
.PP
Inherits \fBWavFileBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWavOutFile\fP (\fBconst\fP char *fileName, \fBint\fP sampleRate, \fBint\fP \fBbits\fP, \fBint\fP channels)"
.br
.ti -1c
.RI "\fBWavOutFile\fP (FILE *file, \fBint\fP sampleRate, \fBint\fP \fBbits\fP, \fBint\fP channels)"
.br
.ti -1c
.RI "\fB~WavOutFile\fP ()"
.br
.RI "\fIDestructor: Finalizes & closes the WAV file\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP unsigned char *\fBbuffer\fP, \fBint\fP numElems)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP short *\fBbuffer\fP, \fBint\fP numElems)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP float *\fBbuffer\fP, \fBint\fP numElems)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class for writing WAV audio files\&. 
.PP
Definition at line 221 of file WavFile\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WavOutFile::WavOutFile (\fBconst\fP char * fileName, \fBint\fP sampleRate, \fBint\fP bits, \fBint\fP channels)"
Constructor: Creates a new WAV file\&. Throws a 'runtime_error' exception if file creation fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfileName\fP Filename 
.br
\fIsampleRate\fP \fBSample\fP rate (e\&.g\&. 44100 etc) 
.br
\fIbits\fP Bits per sample (8 or 16 bits) 
.br
\fIchannels\fP Number of channels (1=mono, 2=stereo) 
.RE
.PP

.PP
Definition at line 674 of file WavFile\&.cpp\&.
.SS "WavOutFile::WavOutFile (FILE * file, \fBint\fP sampleRate, \fBint\fP bits, \fBint\fP channels)"

.PP
Definition at line 692 of file WavFile\&.cpp\&.
.SS "WavOutFile::~WavOutFile ()"

.PP
Destructor: Finalizes & closes the WAV file\&. 
.PP
Definition at line 708 of file WavFile\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP WavOutFile::write (\fBconst\fP unsigned char * buffer, \fBint\fP numElems)"
Write data to WAV file\&. This function works only with 8bit samples\&. Throws a 'runtime_error' exception if writing to file fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP Pointer to sample data buffer\&. 
.br
\fInumElems\fP How many array items are to be written to file\&. 
.RE
.PP

.PP
Definition at line 793 of file WavFile\&.cpp\&.
.SS "\fBvoid\fP WavOutFile::write (\fBconst\fP short * buffer, \fBint\fP numElems)"
Write data to WAV file\&. Throws a 'runtime_error' exception if writing to file fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP Pointer to sample data buffer\&. 
.br
\fInumElems\fP How many array items are to be written to file\&. 
.RE
.PP

.PP
Definition at line 814 of file WavFile\&.cpp\&.
.SS "\fBvoid\fP WavOutFile::write (\fBconst\fP float * buffer, \fBint\fP numElems)"
Write data to WAV file in floating point format, saturating sample values to range [-1\&.\&.+1[\&. Throws a 'runtime_error' exception if writing to file fails\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP Pointer to sample data buffer\&. 
.br
\fInumElems\fP How many array items are to be written to file\&. 
.RE
.PP

.PP
Definition at line 883 of file WavFile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
