.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/white.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/tran/white.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'sound\&.h'\fP
.br
\fC#include 'falloc\&.h'\fP
.br
\fC#include 'cext\&.h'\fP
.br
\fC#include 'white\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwhite_susp_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBwhite_susp_struct\fP \fBwhite_susp_node\fP"
.br
.ti -1c
.RI "typedef struct \fBwhite_susp_struct\fP * \fBwhite_susp_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBwhite_free\fP (\fBsnd_susp_type\fP a_susp)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwhite__fetch\fP (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwhite_print_tree\fP (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_make_white\fP (\fBtime_type\fP t0, \fBrate_type\fP sr, \fBtime_type\fP \fBd\fP)"
.br
.ti -1c
.RI "\fBsound_type\fP \fBsnd_white\fP (\fBtime_type\fP t0, \fBrate_type\fP sr, \fBtime_type\fP \fBd\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBwhite_susp_struct\fP  \fBwhite_susp_node\fP"

.SS "typedef struct \fBwhite_susp_struct\fP * \fBwhite_susp_type\fP"

.SH "Function Documentation"
.PP 
.SS "\fBsound_type\fP snd_make_white (\fBtime_type\fP t0, \fBrate_type\fP sr, \fBtime_type\fP d)"

.PP
Definition at line 81 of file white\&.c\&.
.SS "\fBsound_type\fP snd_white (\fBtime_type\fP t0, \fBrate_type\fP sr, \fBtime_type\fP d)"

.PP
Definition at line 104 of file white\&.c\&.
.SS "\fBvoid\fP white__fetch (\fBsnd_susp_type\fP a_susp, \fBsnd_list_type\fP snd_list)"

.PP
Definition at line 21 of file white\&.c\&.
.SS "\fBvoid\fP white_free (\fBsnd_susp_type\fP a_susp)"

.PP
Definition at line 69 of file white\&.c\&.
.SS "\fBvoid\fP white_print_tree (\fBsnd_susp_type\fP a_susp, \fBint\fP n)"

.PP
Definition at line 76 of file white\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
