.TH "white_susp_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
white_susp_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnd_susp_node\fP \fBsusp\fP"
.br
.ti -1c
.RI "long \fBterminate_cnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file white\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsnd_susp_node\fP white_susp_struct::susp"

.PP
Definition at line 16 of file white\&.c\&.
.SS "long white_susp_struct::terminate_cnt"

.PP
Definition at line 17 of file white\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
