.TH "WriteEventsDAO" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WriteEventsDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DDiscFormat2RawCDEvents\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteEventsDAO\fP (\fBPBHandlev2\fP *h)"
.br
.ti -1c
.RI "\fB~WriteEventsDAO\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBConnect\fP (IUnknown *pConnectTo)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDisconnect\fP ()"
.br
.ti -1c
.RI "STDMETHODIMP \fBQueryInterface\fP (\fBREFIID\fP riid, LPVOID *ppv)"
.br
.ti -1c
.RI "\fBSTDMETHODIMP_\fP (ULONG) AddRef(VOID)"
.br
.ti -1c
.RI "\fBSTDMETHODIMP_\fP (ULONG) Release(VOID)"
.br
.ti -1c
.RI "STDMETHODIMP \fBGetTypeInfoCount\fP (\fBUINT\fP *pctinfo)"
.br
.ti -1c
.RI "STDMETHODIMP \fBGetTypeInfo\fP (\fBUINT\fP iTInfo, \fBLCID\fP lcid, ITypeInfo **ppTInfo)"
.br
.ti -1c
.RI "STDMETHODIMP \fBGetIDsOfNames\fP (\fBREFIID\fP riid, \fBLPOLESTR\fP *rgszNames, \fBUINT\fP cNames, \fBLCID\fP lcid, DISPID *rgDispId)"
.br
.ti -1c
.RI "STDMETHODIMP \fBInvoke\fP (DISPID dispIdMember, \fBREFIID\fP riid, \fBLCID\fP lcid, \fBWORD\fP wFlags, DISPPARAMS *pDispParams, VARIANT *pVarResult, EXCEPINFO *pExcepInfo, \fBUINT\fP *puArgErr)"
.br
.ti -1c
.RI "STDMETHODIMP \fBUpdate\fP (IDispatch *object, IDispatch *progress)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "================================================================== "
.PP
.PP
.SH "================================================================== "
.PP
.PP
================================================================== 
.PP
Definition at line 495 of file portburn_winxpv2\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WriteEventsDAO::WriteEventsDAO (\fBPBHandlev2\fP * h)\fC [inline]\fP"

.PP
Definition at line 498 of file portburn_winxpv2\&.cpp\&.
.SS "WriteEventsDAO::~WriteEventsDAO ()\fC [inline]\fP"

.PP
Definition at line 531 of file portburn_winxpv2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP WriteEventsDAO::Connect (IUnknown * pConnectTo)\fC [inline]\fP"

.PP
Definition at line 540 of file portburn_winxpv2\&.cpp\&.
.SS "\fBvoid\fP WriteEventsDAO::Disconnect ()\fC [inline]\fP"

.PP
Definition at line 564 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::GetIDsOfNames (\fBREFIID\fP riid, \fBLPOLESTR\fP * rgszNames, \fBUINT\fP cNames, \fBLCID\fP lcid, DISPID * rgDispId)\fC [inline]\fP"

.PP
Definition at line 642 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::GetTypeInfo (\fBUINT\fP iTInfo, \fBLCID\fP lcid, ITypeInfo ** ppTInfo)\fC [inline]\fP"

.PP
Definition at line 625 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::GetTypeInfoCount (\fBUINT\fP * pctinfo)\fC [inline]\fP"

.PP
Definition at line 619 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::Invoke (DISPID dispIdMember, \fBREFIID\fP riid, \fBLCID\fP lcid, \fBWORD\fP wFlags, DISPPARAMS * pDispParams, VARIANT * pVarResult, EXCEPINFO * pExcepInfo, \fBUINT\fP * puArgErr)\fC [inline]\fP"

.PP
Definition at line 647 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::QueryInterface (\fBREFIID\fP riid, LPVOID * ppv)\fC [inline]\fP"

.PP
Definition at line 584 of file portburn_winxpv2\&.cpp\&.
.SS "WriteEventsDAO::STDMETHODIMP_ (ULONG)\fC [inline]\fP"

.PP
Definition at line 601 of file portburn_winxpv2\&.cpp\&.
.SS "WriteEventsDAO::STDMETHODIMP_ (ULONG)\fC [inline]\fP"

.PP
Definition at line 606 of file portburn_winxpv2\&.cpp\&.
.SS "STDMETHODIMP WriteEventsDAO::Update (IDispatch * object, IDispatch * progress)\fC [inline]\fP"

.PP
Definition at line 668 of file portburn_winxpv2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
