.TH "wxGtkString" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wxGtkString \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwxGtkString\fP (gchar *\fBs\fP)"
.br
.ti -1c
.RI "\fB~wxGtkString\fP ()"
.br
.ti -1c
.RI "\fBconst\fP gchar * \fBc_str\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBoperator gchar *\fP () \fBconst\fP "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file FileDialogPrivate\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "wxGtkString::wxGtkString (gchar * s)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 39 of file FileDialogPrivate\&.cpp\&.
.SS "wxGtkString::~wxGtkString ()\fC [inline]\fP"

.PP
Definition at line 40 of file FileDialogPrivate\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP gchar* wxGtkString::c_str () const\fC [inline]\fP"

.PP
Definition at line 42 of file FileDialogPrivate\&.cpp\&.
.SS "wxGtkString::operator gchar * () const\fC [inline]\fP"

.PP
Definition at line 44 of file FileDialogPrivate\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
