.TH "wxMSWKeyboard" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wxMSWKeyboard \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBVKToWX\fP (WXWORD \fBvk\fP, WXLPARAM lParam, wchar_t *uc)"
.br
.ti -1c
.RI "WXWORD \fBWXToVK\fP (\fBint\fP \fBwxk\fP, \fBbool\fP *isExtended)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP wxMSWKeyboard::VKToWX (WXWORD vk, WXLPARAM lParam, wchar_t * uc)"

.PP
Definition at line 6289 of file window\&.cpp\&.
.SS "WXWORD wxMSWKeyboard::WXToVK (\fBint\fP wxk, \fBbool\fP * isExtended)"

.PP
Definition at line 6430 of file window\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
