.TH "wxPizza" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wxPizza \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <win_gtk\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBBORDER_STYLES\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (GtkWidget *widget, \fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height)"
.br
.ti -1c
.RI "\fBvoid\fP \fBput\fP (GtkWidget *widget, \fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height)"
.br
.ti -1c
.RI "\fBvoid\fP \fBscroll\fP (\fBint\fP dx, \fBint\fP dy)"
.br
.ti -1c
.RI "\fBvoid\fP \fBget_border\fP (GtkBorder &border)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GtkWidget * \fBNew\fP (long windowStyle=0)"
.br
.ti -1c
.RI "static GType \fBtype\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkFixed \fBm_fixed\fP"
.br
.ti -1c
.RI "GList * \fBm_children\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_scroll_x\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_scroll_y\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_windowStyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file win_gtk\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBORDER_STYLES \fP\fP
.PP
Definition at line 21 of file win_gtk\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP wxPizza::get_border (GtkBorder & border)"

.SS "\fBvoid\fP wxPizza::move (GtkWidget * widget, \fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height)"

.SS "static GtkWidget* wxPizza::New (long windowStyle = \fC0\fP)\fC [static]\fP"

.SS "\fBvoid\fP wxPizza::put (GtkWidget * widget, \fBint\fP x, \fBint\fP y, \fBint\fP width, \fBint\fP height)"

.SS "\fBvoid\fP wxPizza::scroll (\fBint\fP dx, \fBint\fP dy)"

.SS "static GType wxPizza::type ()\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GList* wxPizza::m_children"

.PP
Definition at line 32 of file win_gtk\&.h\&.
.SS "GtkFixed wxPizza::m_fixed"

.PP
Definition at line 31 of file win_gtk\&.h\&.
.SS "\fBint\fP wxPizza::m_scroll_x"

.PP
Definition at line 33 of file win_gtk\&.h\&.
.SS "\fBint\fP wxPizza::m_scroll_y"

.PP
Definition at line 34 of file win_gtk\&.h\&.
.SS "\fBint\fP wxPizza::m_windowStyle"

.PP
Definition at line 35 of file win_gtk\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
