.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/xlftab.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/xlftab.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'switches\&.h'\fP
.br
\fC#include 'xlisp\&.h'\fP
.br
\fC#include 'osdefs\&.h'\fP
.br
\fC#include 'localdefs\&.h'\fP
.br
\fC#include 'osptrs\&.h'\fP
.br
\fC#include 'localptrs\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS\fP   \fBSUBR\fP"
.br
.ti -1c
.RI "#define \fBF\fP   \fBFSUBR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLVAL\fP \fBxbisubr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbifsubr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmhash\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmquote\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmdquote\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmbquote\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmcomma\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBclnew\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBclisnew\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBclanswer\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBobisnew\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBobclass\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBobshow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBobisa\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmlpar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmrpar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBrmsemi\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxeval\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxapply\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfuncall\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxquote\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfunction\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbquote\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlambda\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxset\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsetq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsetf\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdefun\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdefmacro\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgensym\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmakesymbol\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxintern\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsymname\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsymvalue\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsymplist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxget\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxputprop\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremprop\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxhash\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmkarray\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxaref\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcons\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxappend\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxreverse\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlast\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnth\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnthcdr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmember\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxassoc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsubst\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsublis\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlength\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsort\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremove\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremif\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremifnot\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapcar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapl\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmaplist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrplca\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrplcd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnconc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelete\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelif\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelifnot\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxatom\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsymbolp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnumberp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxboundp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnull\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlistp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxendp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxconsp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxeql\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxequal\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcond\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBx_or\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlet\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxletstar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxif\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprog\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprogstar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprog1\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprog2\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprogn\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgo\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxreturn\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcatch\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxthrow\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxerror\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcerror\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbreak\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcleanup\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtoplevel\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcontinue\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxerrset\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbaktrace\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxevalhook\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdo\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdostar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdolist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdotimes\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxminusp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxzerop\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxplusp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxevenp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxoddp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfix\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfloat\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgcd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxadd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsub\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmul\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdiv\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrem\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmin\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmax\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxabs\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxadd1\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsub1\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlogand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlogior\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlogxor\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlognot\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsin\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcos\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtan\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxatan\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxexpt\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxexp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsqrt\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrealrand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlss\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxleq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxequ\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxneq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgtr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrcat\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsubseq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstring\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxread\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprint\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprin1\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprinc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxterpri\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxflatsize\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxflatc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxopen\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbopen\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxclose\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrdchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxpkchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxwrchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxreadline\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrdint\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxwrint\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrdfloat\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxwrfloat\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxget_env\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxload\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtranscript\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtype\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxquit\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxexit\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxpeek\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxpoke\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxaddrs\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxvector\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxblock\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrtnfrom\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtagbody\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxpsetq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxflet\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlabels\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmacrolet\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxunwindprotect\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxpp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrlss\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrleq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstreql\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrneq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrgeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrgtr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrilss\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrileq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrieql\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrineq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrigeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrigtr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxupcase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdowncase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnupcase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxndowncase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtrim\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlefttrim\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrighttrim\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxuppercasep\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlowercasep\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbothcasep\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdigitp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxalphanumericp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcharcode\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcodechar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchupcase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchdowncase\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdigitchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrlss\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrleq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchreql\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrneq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrgeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrgtr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrilss\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrileq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrieql\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrineq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrigeq\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxchrigtr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxintegerp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfloatp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstringp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxarrayp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstreamp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxobjectp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxwhen\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxunless\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxloop\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsymfunction\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfboundp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsend\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsendsuper\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprogv\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrdbyte\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxwrbyte\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxformat\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcharp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcharint\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxintchar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmkstrinput\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmkstroutput\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgetstroutput\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgetlstoutput\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgetlambda\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmacroexpand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBx1macroexpand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxinfo\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsetdir\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxbigendianp\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxtrace\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxuntrace\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxprofile\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxstrsearch\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsetupconsole\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxechoenabled\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxslider_read\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxget_user\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxfind_in_xlisp_path\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxgc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxexpand\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxalloc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmem\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLOCAL\fP \fBLVAL\fP \fBxnotimp\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFUNDEF\fP \fBfuntab\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F   \fBFSUBR\fP"

.PP
Definition at line 105 of file xlftab\&.c\&.
.SS "#define S   \fBSUBR\fP"

.PP
Definition at line 104 of file xlftab\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBLVAL\fP clanswer (\fBvoid\fP)"

.SS "\fBLVAL\fP clisnew (\fBvoid\fP)"

.SS "\fBLVAL\fP clnew (\fBvoid\fP)"

.SS "\fBLVAL\fP obclass (\fBvoid\fP)"

.SS "\fBLVAL\fP obisa (\fBvoid\fP)"

.SS "\fBLVAL\fP obisnew (\fBvoid\fP)"

.SS "\fBLVAL\fP obshow (\fBvoid\fP)"

.SS "\fBLVAL\fP rmbquote (\fBvoid\fP)"

.SS "\fBLVAL\fP rmcomma (\fBvoid\fP)"

.SS "\fBLVAL\fP rmdquote (\fBvoid\fP)"

.SS "\fBLVAL\fP rmhash (\fBvoid\fP)"

.SS "\fBLVAL\fP rmlpar (\fBvoid\fP)"

.SS "\fBLVAL\fP rmquote (\fBvoid\fP)"

.SS "\fBLVAL\fP rmrpar (\fBvoid\fP)"

.SS "\fBLVAL\fP rmsemi (\fBvoid\fP)"

.SS "\fBLVAL\fP x1macroexpand (\fBvoid\fP)"

.PP
Definition at line 73 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP x_or (\fBvoid\fP)"

.PP
Definition at line 502 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xabs (\fBvoid\fP)"

.SS "\fBLVAL\fP xadd (\fBvoid\fP)"

.SS "\fBLVAL\fP xadd1 (\fBvoid\fP)"

.SS "\fBLVAL\fP xaddrs (\fBvoid\fP)"

.SS "\fBLVAL\fP xalloc (\fBvoid\fP)"

.PP
Definition at line 626 of file xldmem\&.c\&.
.SS "\fBLVAL\fP xalphanumericp (\fBvoid\fP)"

.SS "\fBLVAL\fP xand (\fBvoid\fP)"

.PP
Definition at line 487 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xappend (\fBvoid\fP)"

.SS "\fBLVAL\fP xapply (\fBvoid\fP)"

.PP
Definition at line 26 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xaref (\fBvoid\fP)"

.PP
Definition at line 498 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xarrayp (\fBvoid\fP)"

.PP
Definition at line 165 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xassoc (\fBvoid\fP)"

.SS "\fBLVAL\fP xatan (\fBvoid\fP)"

.SS "\fBLVAL\fP xatom (\fBvoid\fP)"

.PP
Definition at line 102 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xbaktrace (\fBvoid\fP)"

.SS "\fBLVAL\fP xbifsubr (\fBvoid\fP)"

.SS "\fBLVAL\fP xbigendianp (\fBvoid\fP)"

.SS "\fBLVAL\fP xbisubr (\fBvoid\fP)"

.SS "\fBLVAL\fP xblock (\fBvoid\fP)"

.PP
Definition at line 1022 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xbopen (\fBvoid\fP)"

.PP
Definition at line 175 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xbothcasep (\fBvoid\fP)"

.SS "\fBLVAL\fP xboundp (\fBvoid\fP)"

.PP
Definition at line 192 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xbquote (\fBvoid\fP)"

.PP
Definition at line 78 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xbreak (\fBvoid\fP)"

.PP
Definition at line 585 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xcaaaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaaadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaadar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaaddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcadaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcadadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcadar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaddar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcadddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcaddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcase (\fBvoid\fP)"

.PP
Definition at line 434 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xcatch (\fBvoid\fP)"

.PP
Definition at line 1053 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xcdaaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdaadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdadar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdaddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcddaar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcddadr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcddar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdddar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcddddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcddr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcdr (\fBvoid\fP)"

.SS "\fBLVAL\fP xcerror (\fBvoid\fP)"

.PP
Definition at line 567 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xchar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcharcode (\fBvoid\fP)"

.SS "\fBLVAL\fP xcharint (\fBvoid\fP)"

.SS "\fBLVAL\fP xcharp (\fBvoid\fP)"

.PP
Definition at line 147 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xchdowncase (\fBvoid\fP)"

.SS "\fBLVAL\fP xchreql (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrgeq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrgtr (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrieql (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrigeq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrigtr (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrileq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrilss (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrineq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrleq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrlss (\fBvoid\fP)"

.SS "\fBLVAL\fP xchrneq (\fBvoid\fP)"

.SS "\fBLVAL\fP xchupcase (\fBvoid\fP)"

.SS "\fBLVAL\fP xcleanup (\fBvoid\fP)"

.PP
Definition at line 602 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xclose (\fBvoid\fP)"

.PP
Definition at line 181 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xcodechar (\fBvoid\fP)"

.SS "\fBLVAL\fP xcond (\fBvoid\fP)"

.PP
Definition at line 379 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xcons (\fBvoid\fP)"

.SS "\fBLVAL\fP xconsp (\fBvoid\fP)"

.PP
Definition at line 237 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xcontinue (\fBvoid\fP)"

.PP
Definition at line 621 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xcos (\fBvoid\fP)"

.SS "\fBLVAL\fP xdefmacro (\fBvoid\fP)"

.PP
Definition at line 360 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdefun (\fBvoid\fP)"

.PP
Definition at line 341 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdelete (\fBvoid\fP)"

.SS "\fBLVAL\fP xdelif (\fBvoid\fP)"

.SS "\fBLVAL\fP xdelifnot (\fBvoid\fP)"

.SS "\fBLVAL\fP xdigitchar (\fBvoid\fP)"

.SS "\fBLVAL\fP xdigitp (\fBvoid\fP)"

.SS "\fBLVAL\fP xdiv (\fBvoid\fP)"

.SS "\fBLVAL\fP xdo (\fBvoid\fP)"

.PP
Definition at line 846 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdolist (\fBvoid\fP)"

.PP
Definition at line 917 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdostar (\fBvoid\fP)"

.PP
Definition at line 852 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdotimes (\fBvoid\fP)"

.PP
Definition at line 972 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xdowncase (\fBvoid\fP)"

.SS "\fBLVAL\fP xechoenabled (\fBvoid\fP)"

.SS "\fBLVAL\fP xendp (\fBvoid\fP)"

.PP
Definition at line 228 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xeq (\fBvoid\fP)"

.PP
Definition at line 246 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xeql (\fBvoid\fP)"

.PP
Definition at line 260 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xequ (\fBvoid\fP)"

.SS "\fBLVAL\fP xequal (\fBvoid\fP)"

.PP
Definition at line 274 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xerror (\fBvoid\fP)"

.PP
Definition at line 552 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xerrset (\fBvoid\fP)"

.PP
Definition at line 1144 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xeval (\fBvoid\fP)"

.PP
Definition at line 13 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xevalhook (\fBvoid\fP)"

.PP
Definition at line 629 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xevenp (\fBvoid\fP)"

.SS "\fBLVAL\fP xexit (\fBvoid\fP)"

.SS "\fBLVAL\fP xexp (\fBvoid\fP)"

.SS "\fBLVAL\fP xexpand (\fBvoid\fP)"

.PP
Definition at line 602 of file xldmem\&.c\&.
.SS "\fBLVAL\fP xexpt (\fBvoid\fP)"

.SS "\fBLVAL\fP xfboundp (\fBvoid\fP)"

.PP
Definition at line 201 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xfind_in_xlisp_path (\fBvoid\fP)"

.PP
Definition at line 219 of file path\&.c\&.
.SS "\fBLVAL\fP xfix (\fBvoid\fP)"

.SS "\fBLVAL\fP xflatc (\fBvoid\fP)"

.PP
Definition at line 116 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xflatsize (\fBvoid\fP)"

.PP
Definition at line 110 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xflet (\fBvoid\fP)"

.PP
Definition at line 577 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xfloat (\fBvoid\fP)"

.SS "\fBLVAL\fP xfloatp (\fBvoid\fP)"

.PP
Definition at line 138 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xformat (\fBvoid\fP)"

.PP
Definition at line 615 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xfuncall (\fBvoid\fP)"

.PP
Definition at line 40 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xfunction (\fBvoid\fP)"

.PP
Definition at line 53 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xgc (\fBvoid\fP)"

.PP
Definition at line 589 of file xldmem\&.c\&.
.SS "\fBLVAL\fP xgcd (\fBvoid\fP)"

.SS "\fBLVAL\fP xgensym (\fBvoid\fP)"

.PP
Definition at line 305 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xgeq (\fBvoid\fP)"

.SS "\fBLVAL\fP xget (\fBvoid\fP)"

.PP
Definition at line 423 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xget_env (\fBvoid\fP)"

.SS "\fBLVAL\fP xget_user (\fBvoid\fP)"

.SS "\fBLVAL\fP xgetlambda (\fBvoid\fP)"

.PP
Definition at line 161 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xgetlstoutput (\fBvoid\fP)"

.PP
Definition at line 595 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xgetstroutput (\fBvoid\fP)"

.PP
Definition at line 586 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xgo (\fBvoid\fP)"

.PP
Definition at line 687 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xgtr (\fBvoid\fP)"

.SS "\fBLVAL\fP xhash (\fBvoid\fP)"

.PP
Definition at line 472 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xif (\fBvoid\fP)"

.PP
Definition at line 516 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xinfo (\fBvoid\fP)"

.PP
Definition at line 661 of file xldmem\&.c\&.
.SS "\fBLVAL\fP xintchar (\fBvoid\fP)"

.SS "\fBLVAL\fP xintegerp (\fBvoid\fP)"

.PP
Definition at line 129 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xintern (\fBvoid\fP)"

.PP
Definition at line 343 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xlabels (\fBvoid\fP)"

.PP
Definition at line 583 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xlambda (\fBvoid\fP)"

.PP
Definition at line 143 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xlast (\fBvoid\fP)"

.SS "\fBLVAL\fP xlefttrim (\fBvoid\fP)"

.SS "\fBLVAL\fP xlength (\fBvoid\fP)"

.SS "\fBLVAL\fP xleq (\fBvoid\fP)"

.SS "\fBLVAL\fP xlet (\fBvoid\fP)"

.PP
Definition at line 531 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xletstar (\fBvoid\fP)"

.PP
Definition at line 537 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xlist (\fBvoid\fP)"

.SS "\fBLVAL\fP xlistp (\fBvoid\fP)"

.PP
Definition at line 219 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xload (\fBvoid\fP)"

.SS "\fBLVAL\fP xlogand (\fBvoid\fP)"

.SS "\fBLVAL\fP xlogior (\fBvoid\fP)"

.SS "\fBLVAL\fP xlognot (\fBvoid\fP)"

.SS "\fBLVAL\fP xlogxor (\fBvoid\fP)"

.SS "\fBLVAL\fP xloop (\fBvoid\fP)"

.PP
Definition at line 816 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xlowercasep (\fBvoid\fP)"

.SS "\fBLVAL\fP xlss (\fBvoid\fP)"

.SS "\fBLVAL\fP xmacroexpand (\fBvoid\fP)"

.PP
Definition at line 64 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xmacrolet (\fBvoid\fP)"

.PP
Definition at line 589 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xmakesymbol (\fBvoid\fP)"

.PP
Definition at line 337 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xmapc (\fBvoid\fP)"

.SS "\fBLVAL\fP xmapcar (\fBvoid\fP)"

.SS "\fBLVAL\fP xmapl (\fBvoid\fP)"

.SS "\fBLVAL\fP xmaplist (\fBvoid\fP)"

.SS "\fBLVAL\fP xmax (\fBvoid\fP)"

.SS "\fBLVAL\fP xmem (\fBvoid\fP)"

.PP
Definition at line 647 of file xldmem\&.c\&.
.SS "\fBLVAL\fP xmember (\fBvoid\fP)"

.SS "\fBLVAL\fP xmin (\fBvoid\fP)"

.SS "\fBLVAL\fP xminusp (\fBvoid\fP)"

.SS "\fBLVAL\fP xmkarray (\fBvoid\fP)"

.PP
Definition at line 517 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xmkstrinput (\fBvoid\fP)"

.PP
Definition at line 530 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xmkstroutput (\fBvoid\fP)"

.PP
Definition at line 580 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xmul (\fBvoid\fP)"

.SS "\fBLVAL\fP xnconc (\fBvoid\fP)"

.SS "\fBLVAL\fP xndowncase (\fBvoid\fP)"

.SS "\fBLVAL\fP xneq (\fBvoid\fP)"

.SS "\fBLOCAL\fP \fBLVAL\fP xnotimp (\fBvoid\fP)"

.PP
Definition at line 509 of file xlftab\&.c\&.
.SS "\fBLVAL\fP xnth (\fBvoid\fP)"

.SS "\fBLVAL\fP xnthcdr (\fBvoid\fP)"

.SS "\fBLVAL\fP xnull (\fBvoid\fP)"

.PP
Definition at line 210 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xnumberp (\fBvoid\fP)"

.PP
Definition at line 120 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xnupcase (\fBvoid\fP)"

.SS "\fBLVAL\fP xobjectp (\fBvoid\fP)"

.PP
Definition at line 183 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xoddp (\fBvoid\fP)"

.SS "\fBLVAL\fP xopen (\fBvoid\fP)"

.PP
Definition at line 169 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xpeek (\fBvoid\fP)"

.SS "\fBLVAL\fP xpkchar (\fBvoid\fP)"

.PP
Definition at line 322 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xplusp (\fBvoid\fP)"

.SS "\fBLVAL\fP xpoke (\fBvoid\fP)"

.SS "\fBLVAL\fP xpp (\fBvoid\fP)"

.SS "\fBLVAL\fP xprin1 (\fBvoid\fP)"

.PP
Definition at line 63 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xprinc (\fBvoid\fP)"

.PP
Definition at line 69 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xprint (\fBvoid\fP)"

.PP
Definition at line 57 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xprofile (\fBvoid\fP)"

.SS "\fBLVAL\fP xprog (\fBvoid\fP)"

.PP
Definition at line 629 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xprog1 (\fBvoid\fP)"

.PP
Definition at line 730 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xprog2 (\fBvoid\fP)"

.PP
Definition at line 736 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xprogn (\fBvoid\fP)"

.PP
Definition at line 765 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xprogstar (\fBvoid\fP)"

.PP
Definition at line 635 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xprogv (\fBvoid\fP)"

.PP
Definition at line 778 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xpsetq (\fBvoid\fP)"

.PP
Definition at line 186 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xputprop (\fBvoid\fP)"

.PP
Definition at line 437 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xquit (\fBvoid\fP)"

.SS "\fBLVAL\fP xquote (\fBvoid\fP)"

.PP
Definition at line 44 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xrand (\fBvoid\fP)"

.SS "\fBLVAL\fP xrdbyte (\fBvoid\fP)"

.PP
Definition at line 308 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xrdchar (\fBvoid\fP)"

.PP
Definition at line 202 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xrdfloat (\fBvoid\fP)"

.PP
Definition at line 261 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xrdint (\fBvoid\fP)"

.PP
Definition at line 217 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xread (\fBvoid\fP)"

.PP
Definition at line 38 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xreadline (\fBvoid\fP)"

.PP
Definition at line 474 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xrealrand (\fBvoid\fP)"

.SS "\fBLVAL\fP xrem (\fBvoid\fP)"

.SS "\fBLVAL\fP xremif (\fBvoid\fP)"

.SS "\fBLVAL\fP xremifnot (\fBvoid\fP)"

.SS "\fBLVAL\fP xremove (\fBvoid\fP)"

.SS "\fBLVAL\fP xremprop (\fBvoid\fP)"

.PP
Definition at line 455 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xreturn (\fBvoid\fP)"

.PP
Definition at line 701 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xreverse (\fBvoid\fP)"

.SS "\fBLVAL\fP xrighttrim (\fBvoid\fP)"

.SS "\fBLVAL\fP xrplca (\fBvoid\fP)"

.SS "\fBLVAL\fP xrplcd (\fBvoid\fP)"

.SS "\fBLVAL\fP xrtnfrom (\fBvoid\fP)"

.PP
Definition at line 715 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xsend (\fBvoid\fP)"

.SS "\fBLVAL\fP xsendsuper (\fBvoid\fP)"

.SS "\fBLVAL\fP xset (\fBvoid\fP)"

.PP
Definition at line 288 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xsetdir (\fBvoid\fP)"

.PP
Definition at line 1213 of file nyx\&.c\&.
.SS "\fBLVAL\fP xsetf (\fBvoid\fP)"

.PP
Definition at line 212 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xsetq (\fBvoid\fP)"

.PP
Definition at line 170 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xsetupconsole (\fBvoid\fP)"

.SS "\fBLVAL\fP xsin (\fBvoid\fP)"

.SS "\fBLVAL\fP xslider_read (\fBvoid\fP)"

.SS "\fBLVAL\fP xsort (\fBvoid\fP)"

.SS "\fBLVAL\fP xsqrt (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrcat (\fBvoid\fP)"

.SS "\fBLVAL\fP xstreamp (\fBvoid\fP)"

.PP
Definition at line 174 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xstreql (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrgeq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrgtr (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrieql (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrigeq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrigtr (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrileq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrilss (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrineq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstring (\fBvoid\fP)"

.SS "\fBLVAL\fP xstringp (\fBvoid\fP)"

.PP
Definition at line 156 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xstrleq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrlss (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrneq (\fBvoid\fP)"

.SS "\fBLVAL\fP xstrsearch (\fBvoid\fP)"

.SS "\fBLVAL\fP xsub (\fBvoid\fP)"

.SS "\fBLVAL\fP xsub1 (\fBvoid\fP)"

.SS "\fBLVAL\fP xsublis (\fBvoid\fP)"

.SS "\fBLVAL\fP xsubseq (\fBvoid\fP)"

.SS "\fBLVAL\fP xsubst (\fBvoid\fP)"

.SS "\fBLVAL\fP xsymbolp (\fBvoid\fP)"

.PP
Definition at line 111 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xsymfunction (\fBvoid\fP)"

.PP
Definition at line 393 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xsymname (\fBvoid\fP)"

.PP
Definition at line 363 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xsymplist (\fBvoid\fP)"

.PP
Definition at line 410 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xsymvalue (\fBvoid\fP)"

.PP
Definition at line 376 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xtagbody (\fBvoid\fP)"

.PP
Definition at line 1046 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xtan (\fBvoid\fP)"

.SS "\fBLVAL\fP xterpri (\fBvoid\fP)"

.PP
Definition at line 75 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xthrow (\fBvoid\fP)"

.PP
Definition at line 1086 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xtoplevel (\fBvoid\fP)"

.PP
Definition at line 610 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xtrace (\fBvoid\fP)"

.PP
Definition at line 1173 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xtranscript (\fBvoid\fP)"

.SS "\fBLVAL\fP xtrim (\fBvoid\fP)"

.SS "\fBLVAL\fP xtype (\fBvoid\fP)"

.SS "\fBLVAL\fP xunless (\fBvoid\fP)"

.PP
Definition at line 420 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xuntrace (\fBvoid\fP)"

.PP
Definition at line 1195 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xunwindprotect (\fBvoid\fP)"

.PP
Definition at line 1101 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xupcase (\fBvoid\fP)"

.SS "\fBLVAL\fP xuppercasep (\fBvoid\fP)"

.SS "\fBLVAL\fP xvector (\fBvoid\fP)"

.PP
Definition at line 531 of file xlbfun\&.c\&.
.SS "\fBLVAL\fP xwhen (\fBvoid\fP)"

.PP
Definition at line 406 of file xlcont\&.c\&.
.SS "\fBLVAL\fP xwrbyte (\fBvoid\fP)"

.PP
Definition at line 361 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xwrchar (\fBvoid\fP)"

.PP
Definition at line 344 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xwrfloat (\fBvoid\fP)"

.PP
Definition at line 424 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xwrint (\fBvoid\fP)"

.PP
Definition at line 379 of file xlfio\&.c\&.
.SS "\fBLVAL\fP xzerop (\fBvoid\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBFUNDEF\fP funtab[]"

.PP
Definition at line 117 of file xlftab\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
