.TH "C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/xllist.c" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_dev/OpenU/Audacity/audacity/lib-src/libnyquist/nyquist/xlisp/xllist.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'xlisp\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBcxr\fP (char *adstr)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBnth\fP (\fBint\fP carflag)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBassoc\fP (\fBLVAL\fP expr, \fBLVAL\fP alist, \fBLVAL\fP fcn, \fBint\fP tresult)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBsubst\fP (\fBLVAL\fP to, \fBLVAL\fP \fBfrom\fP, \fBLVAL\fP expr, \fBLVAL\fP fcn, \fBint\fP tresult)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBsublis\fP (\fBLVAL\fP alist, \fBLVAL\fP expr, \fBLVAL\fP fcn, \fBint\fP tresult)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBmap\fP (\fBint\fP carflag, \fBint\fP valflag)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBremif\fP (\fBint\fP tresult)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBdelif\fP (\fBint\fP tresult)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBsortlist\fP (\fBLVAL\fP list, \fBLVAL\fP fcn)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBvoid\fP \fBsplitlist\fP (\fBLVAL\fP pivot, \fBLVAL\fP list, \fBLVAL\fP *psmaller, \fBLVAL\fP *plarger, \fBLVAL\fP fcn)"
.br
.ti -1c
.RI "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBgluelists\fP (\fBLVAL\fP smaller, \fBLVAL\fP pivot, \fBLVAL\fP larger)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcaddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcadddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdadar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdaddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddaar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddadr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcdddar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcddddr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxcons\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxappend\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxreverse\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlast\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmember\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxassoc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsubst\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsublis\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremove\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremif\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxremifnot\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBdotest1\fP (\fBLVAL\fP arg, \fBLVAL\fP fun)"
.br
.ti -1c
.RI "\fBint\fP \fBdotest2\fP (\fBLVAL\fP arg1, \fBLVAL\fP arg2, \fBLVAL\fP fun)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnth\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnthcdr\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxlength\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapcar\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmapl\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxmaplist\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrplca\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxrplcd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxnconc\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelete\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelif\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxdelifnot\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBLVAL\fP \fBxsort\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBLOCAL\fP \fBLVAL\fP assoc (\fBLVAL\fP expr, \fBLVAL\fP alist, \fBLVAL\fP fcn, \fBint\fP tresult)"

.PP
Definition at line 360 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP cxr (char * adstr)"

.PP
Definition at line 82 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP delif (\fBint\fP tresult)"

.PP
Definition at line 775 of file xllist\&.c\&.
.SS "\fBint\fP dotest1 (\fBLVAL\fP arg, \fBLVAL\fP fun)"

.PP
Definition at line 453 of file xllist\&.c\&.
.SS "\fBint\fP dotest2 (\fBLVAL\fP arg1, \fBLVAL\fP arg2, \fBLVAL\fP fun)"

.PP
Definition at line 471 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP gluelists (\fBLVAL\fP smaller, \fBLVAL\fP pivot, \fBLVAL\fP larger)"

.PP
Definition at line 911 of file xllist\&.c\&.
.SS "\fBFORWARD\fP \fBLOCAL\fP \fBLVAL\fP \fBmap\fP (\fBint\fP carflag, \fBint\fP valflag)"

.PP
Definition at line 580 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP nth (\fBint\fP carflag)"

.PP
Definition at line 502 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP remif (\fBint\fP tresult)"

.PP
Definition at line 420 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP sortlist (\fBLVAL\fP list, \fBLVAL\fP fcn)"

.PP
Definition at line 857 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBvoid\fP splitlist (\fBLVAL\fP pivot, \fBLVAL\fP list, \fBLVAL\fP * psmaller, \fBLVAL\fP * plarger, \fBLVAL\fP fcn)"

.PP
Definition at line 883 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP sublis (\fBLVAL\fP alist, \fBLVAL\fP expr, \fBLVAL\fP fcn, \fBint\fP tresult)"

.PP
Definition at line 342 of file xllist\&.c\&.
.SS "\fBLOCAL\fP \fBLVAL\fP subst (\fBLVAL\fP to, \fBLVAL\fP from, \fBLVAL\fP expr, \fBLVAL\fP fcn, \fBint\fP tresult)"

.PP
Definition at line 300 of file xllist\&.c\&.
.SS "\fBLVAL\fP xappend (\fBvoid\fP)"

.PP
Definition at line 142 of file xllist\&.c\&.
.SS "\fBLVAL\fP xassoc (\fBvoid\fP)"

.PP
Definition at line 246 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaaaar (\fBvoid\fP)"

.PP
Definition at line 64 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaaadr (\fBvoid\fP)"

.PP
Definition at line 65 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaaar (\fBvoid\fP)"

.PP
Definition at line 54 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaadar (\fBvoid\fP)"

.PP
Definition at line 66 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaaddr (\fBvoid\fP)"

.PP
Definition at line 67 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaadr (\fBvoid\fP)"

.PP
Definition at line 55 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaar (\fBvoid\fP)"

.PP
Definition at line 48 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcadaar (\fBvoid\fP)"

.PP
Definition at line 68 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcadadr (\fBvoid\fP)"

.PP
Definition at line 69 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcadar (\fBvoid\fP)"

.PP
Definition at line 56 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaddar (\fBvoid\fP)"

.PP
Definition at line 70 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcadddr (\fBvoid\fP)"

.PP
Definition at line 71 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcaddr (\fBvoid\fP)"

.PP
Definition at line 57 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcadr (\fBvoid\fP)"

.PP
Definition at line 49 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcar (\fBvoid\fP)"

.PP
Definition at line 30 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdaaar (\fBvoid\fP)"

.PP
Definition at line 72 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdaadr (\fBvoid\fP)"

.PP
Definition at line 73 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdaar (\fBvoid\fP)"

.PP
Definition at line 58 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdadar (\fBvoid\fP)"

.PP
Definition at line 74 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdaddr (\fBvoid\fP)"

.PP
Definition at line 75 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdadr (\fBvoid\fP)"

.PP
Definition at line 59 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdar (\fBvoid\fP)"

.PP
Definition at line 50 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcddaar (\fBvoid\fP)"

.PP
Definition at line 76 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcddadr (\fBvoid\fP)"

.PP
Definition at line 77 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcddar (\fBvoid\fP)"

.PP
Definition at line 60 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdddar (\fBvoid\fP)"

.PP
Definition at line 78 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcddddr (\fBvoid\fP)"

.PP
Definition at line 79 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdddr (\fBvoid\fP)"

.PP
Definition at line 61 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcddr (\fBvoid\fP)"

.PP
Definition at line 51 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcdr (\fBvoid\fP)"

.PP
Definition at line 39 of file xllist\&.c\&.
.SS "\fBLVAL\fP xcons (\fBvoid\fP)"

.PP
Definition at line 103 of file xllist\&.c\&.
.SS "\fBLVAL\fP xdelete (\fBvoid\fP)"

.PP
Definition at line 712 of file xllist\&.c\&.
.SS "\fBLVAL\fP xdelif (\fBvoid\fP)"

.PP
Definition at line 761 of file xllist\&.c\&.
.SS "\fBLVAL\fP xdelifnot (\fBvoid\fP)"

.PP
Definition at line 768 of file xllist\&.c\&.
.SS "\fBLVAL\fP xlast (\fBvoid\fP)"

.PP
Definition at line 201 of file xllist\&.c\&.
.SS "\fBLVAL\fP xlength (\fBvoid\fP)"

.PP
Definition at line 525 of file xllist\&.c\&.
.SS "\fBLVAL\fP xlist (\fBvoid\fP)"

.PP
Definition at line 117 of file xllist\&.c\&.
.SS "\fBLVAL\fP xmapc (\fBvoid\fP)"

.PP
Definition at line 556 of file xllist\&.c\&.
.SS "\fBLVAL\fP xmapcar (\fBvoid\fP)"

.PP
Definition at line 562 of file xllist\&.c\&.
.SS "\fBLVAL\fP xmapl (\fBvoid\fP)"

.PP
Definition at line 568 of file xllist\&.c\&.
.SS "\fBLVAL\fP xmaplist (\fBvoid\fP)"

.PP
Definition at line 574 of file xllist\&.c\&.
.SS "\fBLVAL\fP xmember (\fBvoid\fP)"

.PP
Definition at line 218 of file xllist\&.c\&.
.SS "\fBLVAL\fP xnconc (\fBvoid\fP)"

.PP
Definition at line 677 of file xllist\&.c\&.
.SS "\fBLVAL\fP xnth (\fBvoid\fP)"

.PP
Definition at line 490 of file xllist\&.c\&.
.SS "\fBLVAL\fP xnthcdr (\fBvoid\fP)"

.PP
Definition at line 496 of file xllist\&.c\&.
.SS "\fBLVAL\fP xremif (\fBvoid\fP)"

.PP
Definition at line 406 of file xllist\&.c\&.
.SS "\fBLVAL\fP xremifnot (\fBvoid\fP)"

.PP
Definition at line 413 of file xllist\&.c\&.
.SS "\fBLVAL\fP xremove (\fBvoid\fP)"

.PP
Definition at line 372 of file xllist\&.c\&.
.SS "\fBLVAL\fP xreverse (\fBvoid\fP)"

.PP
Definition at line 178 of file xllist\&.c\&.
.SS "\fBLVAL\fP xrplca (\fBvoid\fP)"

.PP
Definition at line 643 of file xllist\&.c\&.
.SS "\fBLVAL\fP xrplcd (\fBvoid\fP)"

.PP
Definition at line 660 of file xllist\&.c\&.
.SS "\fBLVAL\fP xsort (\fBvoid\fP)"

.PP
Definition at line 823 of file xllist\&.c\&.
.SS "\fBLVAL\fP xsublis (\fBvoid\fP)"

.PP
Definition at line 318 of file xllist\&.c\&.
.SS "\fBLVAL\fP xsubst (\fBvoid\fP)"

.PP
Definition at line 275 of file xllist\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
