.TH "XML_ParserStruct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XML_ParserStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP (\fBXMLCALL\fP *m_unknownEncodingRelease)(void *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBm_userData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_handlerArg\fP"
.br
.ti -1c
.RI "char * \fBm_buffer\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Memory_Handling_Suite\fP \fBm_mem\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_bufferPtr\fP"
.br
.ti -1c
.RI "char * \fBm_bufferEnd\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_bufferLim\fP"
.br
.ti -1c
.RI "\fBXML_Index\fP \fBm_parseEndByteIndex\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_parseEndPtr\fP"
.br
.ti -1c
.RI "\fBXML_Char\fP * \fBm_dataBuf\fP"
.br
.ti -1c
.RI "\fBXML_Char\fP * \fBm_dataBufEnd\fP"
.br
.ti -1c
.RI "\fBXML_StartElementHandler\fP \fBm_startElementHandler\fP"
.br
.ti -1c
.RI "\fBXML_EndElementHandler\fP \fBm_endElementHandler\fP"
.br
.ti -1c
.RI "\fBXML_CharacterDataHandler\fP \fBm_characterDataHandler\fP"
.br
.ti -1c
.RI "\fBXML_ProcessingInstructionHandler\fP \fBm_processingInstructionHandler\fP"
.br
.ti -1c
.RI "\fBXML_CommentHandler\fP \fBm_commentHandler\fP"
.br
.ti -1c
.RI "\fBXML_StartCdataSectionHandler\fP \fBm_startCdataSectionHandler\fP"
.br
.ti -1c
.RI "\fBXML_EndCdataSectionHandler\fP \fBm_endCdataSectionHandler\fP"
.br
.ti -1c
.RI "\fBXML_DefaultHandler\fP \fBm_defaultHandler\fP"
.br
.ti -1c
.RI "\fBXML_StartDoctypeDeclHandler\fP \fBm_startDoctypeDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_EndDoctypeDeclHandler\fP \fBm_endDoctypeDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_UnparsedEntityDeclHandler\fP \fBm_unparsedEntityDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_NotationDeclHandler\fP \fBm_notationDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_StartNamespaceDeclHandler\fP \fBm_startNamespaceDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_EndNamespaceDeclHandler\fP \fBm_endNamespaceDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_NotStandaloneHandler\fP \fBm_notStandaloneHandler\fP"
.br
.ti -1c
.RI "\fBXML_ExternalEntityRefHandler\fP \fBm_externalEntityRefHandler\fP"
.br
.ti -1c
.RI "\fBXML_Parser\fP \fBm_externalEntityRefHandlerArg\fP"
.br
.ti -1c
.RI "\fBXML_SkippedEntityHandler\fP \fBm_skippedEntityHandler\fP"
.br
.ti -1c
.RI "\fBXML_UnknownEncodingHandler\fP \fBm_unknownEncodingHandler\fP"
.br
.ti -1c
.RI "\fBXML_ElementDeclHandler\fP \fBm_elementDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_AttlistDeclHandler\fP \fBm_attlistDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_EntityDeclHandler\fP \fBm_entityDeclHandler\fP"
.br
.ti -1c
.RI "\fBXML_XmlDeclHandler\fP \fBm_xmlDeclHandler\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBENCODING\fP * \fBm_encoding\fP"
.br
.ti -1c
.RI "\fBINIT_ENCODING\fP \fBm_initEncoding\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBENCODING\fP * \fBm_internalEncoding\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_protocolEncodingName\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBm_ns\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBm_ns_triplets\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_unknownEncodingMem\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_unknownEncodingData\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_unknownEncodingHandlerData\fP"
.br
.ti -1c
.RI "\fBPROLOG_STATE\fP \fBm_prologState\fP"
.br
.ti -1c
.RI "\fBProcessor\fP * \fBm_processor\fP"
.br
.ti -1c
.RI "enum \fBXML_Error\fP \fBm_errorCode\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_eventPtr\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_eventEndPtr\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBm_positionPtr\fP"
.br
.ti -1c
.RI "\fBOPEN_INTERNAL_ENTITY\fP * \fBm_openInternalEntities\fP"
.br
.ti -1c
.RI "\fBOPEN_INTERNAL_ENTITY\fP * \fBm_freeInternalEntities\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBm_defaultExpandInternalEntities\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_tagLevel\fP"
.br
.ti -1c
.RI "\fBENTITY\fP * \fBm_declEntity\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_doctypeName\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_doctypeSysid\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_doctypePubid\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_declAttributeType\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_declNotationName\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_declNotationPublicId\fP"
.br
.ti -1c
.RI "\fBELEMENT_TYPE\fP * \fBm_declElementType\fP"
.br
.ti -1c
.RI "\fBATTRIBUTE_ID\fP * \fBm_declAttributeId\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBm_declAttributeIsCdata\fP"
.br
.ti -1c
.RI "\fBXML_Bool\fP \fBm_declAttributeIsId\fP"
.br
.ti -1c
.RI "\fBDTD\fP * \fBm_dtd\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBXML_Char\fP * \fBm_curBase\fP"
.br
.ti -1c
.RI "\fBTAG\fP * \fBm_tagStack\fP"
.br
.ti -1c
.RI "\fBTAG\fP * \fBm_freeTagList\fP"
.br
.ti -1c
.RI "\fBBINDING\fP * \fBm_inheritedBindings\fP"
.br
.ti -1c
.RI "\fBBINDING\fP * \fBm_freeBindingList\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_attsSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_nSpecifiedAtts\fP"
.br
.ti -1c
.RI "\fBint\fP \fBm_idAttIndex\fP"
.br
.ti -1c
.RI "\fBATTRIBUTE\fP * \fBm_atts\fP"
.br
.ti -1c
.RI "\fBNS_ATT\fP * \fBm_nsAtts\fP"
.br
.ti -1c
.RI "unsigned long \fBm_nsAttsVersion\fP"
.br
.ti -1c
.RI "unsigned char \fBm_nsAttsPower\fP"
.br
.ti -1c
.RI "\fBPOSITION\fP \fBm_position\fP"
.br
.ti -1c
.RI "\fBSTRING_POOL\fP \fBm_tempPool\fP"
.br
.ti -1c
.RI "\fBSTRING_POOL\fP \fBm_temp2Pool\fP"
.br
.ti -1c
.RI "char * \fBm_groupConnector\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBm_groupSize\fP"
.br
.ti -1c
.RI "\fBXML_Char\fP \fBm_namespaceSeparator\fP"
.br
.ti -1c
.RI "\fBXML_Parser\fP \fBm_parentParser\fP"
.br
.ti -1c
.RI "\fBXML_ParsingStatus\fP \fBm_parsingStatus\fP"
.br
.ti -1c
.RI "unsigned long \fBm_hash_secret_salt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 459 of file xmlparse\&.c\&.
.SH "Member Function Documentation"
.PP 
.SS "XML_ParserStruct::void (\fBXMLCALL\fP * m_unknownEncodingRelease)"

.SH "Member Data Documentation"
.PP 
.SS "\fBXML_AttlistDeclHandler\fP XML_ParserStruct::m_attlistDeclHandler"

.PP
Definition at line 496 of file xmlparse\&.c\&.
.SS "\fBATTRIBUTE\fP* XML_ParserStruct::m_atts"

.PP
Definition at line 539 of file xmlparse\&.c\&.
.SS "\fBint\fP XML_ParserStruct::m_attsSize"

.PP
Definition at line 536 of file xmlparse\&.c\&.
.SS "char* XML_ParserStruct::m_buffer"

.PP
Definition at line 464 of file xmlparse\&.c\&.
.SS "char* XML_ParserStruct::m_bufferEnd"

.PP
Definition at line 469 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_bufferLim"

.PP
Definition at line 471 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_bufferPtr"

.PP
Definition at line 467 of file xmlparse\&.c\&.
.SS "\fBXML_CharacterDataHandler\fP XML_ParserStruct::m_characterDataHandler"

.PP
Definition at line 478 of file xmlparse\&.c\&.
.SS "\fBXML_CommentHandler\fP XML_ParserStruct::m_commentHandler"

.PP
Definition at line 480 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_curBase"

.PP
Definition at line 531 of file xmlparse\&.c\&.
.SS "\fBXML_Char\fP* XML_ParserStruct::m_dataBuf"

.PP
Definition at line 474 of file xmlparse\&.c\&.
.SS "\fBXML_Char\fP* XML_ParserStruct::m_dataBufEnd"

.PP
Definition at line 475 of file xmlparse\&.c\&.
.SS "\fBATTRIBUTE_ID\fP* XML_ParserStruct::m_declAttributeId"

.PP
Definition at line 527 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP XML_ParserStruct::m_declAttributeIsCdata"

.PP
Definition at line 528 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP XML_ParserStruct::m_declAttributeIsId"

.PP
Definition at line 529 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_declAttributeType"

.PP
Definition at line 523 of file xmlparse\&.c\&.
.SS "\fBELEMENT_TYPE\fP* XML_ParserStruct::m_declElementType"

.PP
Definition at line 526 of file xmlparse\&.c\&.
.SS "\fBENTITY\fP* XML_ParserStruct::m_declEntity"

.PP
Definition at line 519 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_declNotationName"

.PP
Definition at line 524 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_declNotationPublicId"

.PP
Definition at line 525 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP XML_ParserStruct::m_defaultExpandInternalEntities"

.PP
Definition at line 517 of file xmlparse\&.c\&.
.SS "\fBXML_DefaultHandler\fP XML_ParserStruct::m_defaultHandler"

.PP
Definition at line 483 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_doctypeName"

.PP
Definition at line 520 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_doctypePubid"

.PP
Definition at line 522 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_doctypeSysid"

.PP
Definition at line 521 of file xmlparse\&.c\&.
.SS "\fBDTD\fP* XML_ParserStruct::m_dtd"

.PP
Definition at line 530 of file xmlparse\&.c\&.
.SS "\fBXML_ElementDeclHandler\fP XML_ParserStruct::m_elementDeclHandler"

.PP
Definition at line 495 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBENCODING\fP* XML_ParserStruct::m_encoding"

.PP
Definition at line 499 of file xmlparse\&.c\&.
.SS "\fBXML_EndCdataSectionHandler\fP XML_ParserStruct::m_endCdataSectionHandler"

.PP
Definition at line 482 of file xmlparse\&.c\&.
.SS "\fBXML_EndDoctypeDeclHandler\fP XML_ParserStruct::m_endDoctypeDeclHandler"

.PP
Definition at line 485 of file xmlparse\&.c\&.
.SS "\fBXML_EndElementHandler\fP XML_ParserStruct::m_endElementHandler"

.PP
Definition at line 477 of file xmlparse\&.c\&.
.SS "\fBXML_EndNamespaceDeclHandler\fP XML_ParserStruct::m_endNamespaceDeclHandler"

.PP
Definition at line 489 of file xmlparse\&.c\&.
.SS "\fBXML_EntityDeclHandler\fP XML_ParserStruct::m_entityDeclHandler"

.PP
Definition at line 497 of file xmlparse\&.c\&.
.SS "enum \fBXML_Error\fP XML_ParserStruct::m_errorCode"

.PP
Definition at line 511 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_eventEndPtr"

.PP
Definition at line 513 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_eventPtr"

.PP
Definition at line 512 of file xmlparse\&.c\&.
.SS "\fBXML_ExternalEntityRefHandler\fP XML_ParserStruct::m_externalEntityRefHandler"

.PP
Definition at line 491 of file xmlparse\&.c\&.
.SS "\fBXML_Parser\fP XML_ParserStruct::m_externalEntityRefHandlerArg"

.PP
Definition at line 492 of file xmlparse\&.c\&.
.SS "\fBBINDING\fP* XML_ParserStruct::m_freeBindingList"

.PP
Definition at line 535 of file xmlparse\&.c\&.
.SS "\fBOPEN_INTERNAL_ENTITY\fP* XML_ParserStruct::m_freeInternalEntities"

.PP
Definition at line 516 of file xmlparse\&.c\&.
.SS "\fBTAG\fP* XML_ParserStruct::m_freeTagList"

.PP
Definition at line 533 of file xmlparse\&.c\&.
.SS "char* XML_ParserStruct::m_groupConnector"

.PP
Definition at line 549 of file xmlparse\&.c\&.
.SS "unsigned \fBint\fP XML_ParserStruct::m_groupSize"

.PP
Definition at line 550 of file xmlparse\&.c\&.
.SS "\fBvoid\fP* XML_ParserStruct::m_handlerArg"

.PP
Definition at line 463 of file xmlparse\&.c\&.
.SS "unsigned long XML_ParserStruct::m_hash_secret_salt"

.PP
Definition at line 559 of file xmlparse\&.c\&.
.SS "\fBint\fP XML_ParserStruct::m_idAttIndex"

.PP
Definition at line 538 of file xmlparse\&.c\&.
.SS "\fBBINDING\fP* XML_ParserStruct::m_inheritedBindings"

.PP
Definition at line 534 of file xmlparse\&.c\&.
.SS "\fBINIT_ENCODING\fP XML_ParserStruct::m_initEncoding"

.PP
Definition at line 500 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBENCODING\fP* XML_ParserStruct::m_internalEncoding"

.PP
Definition at line 501 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Memory_Handling_Suite\fP XML_ParserStruct::m_mem"

.PP
Definition at line 465 of file xmlparse\&.c\&.
.SS "\fBXML_Char\fP XML_ParserStruct::m_namespaceSeparator"

.PP
Definition at line 551 of file xmlparse\&.c\&.
.SS "\fBXML_NotationDeclHandler\fP XML_ParserStruct::m_notationDeclHandler"

.PP
Definition at line 487 of file xmlparse\&.c\&.
.SS "\fBXML_NotStandaloneHandler\fP XML_ParserStruct::m_notStandaloneHandler"

.PP
Definition at line 490 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP XML_ParserStruct::m_ns"

.PP
Definition at line 503 of file xmlparse\&.c\&.
.SS "\fBXML_Bool\fP XML_ParserStruct::m_ns_triplets"

.PP
Definition at line 504 of file xmlparse\&.c\&.
.SS "\fBNS_ATT\fP* XML_ParserStruct::m_nsAtts"

.PP
Definition at line 540 of file xmlparse\&.c\&.
.SS "unsigned char XML_ParserStruct::m_nsAttsPower"

.PP
Definition at line 542 of file xmlparse\&.c\&.
.SS "unsigned long XML_ParserStruct::m_nsAttsVersion"

.PP
Definition at line 541 of file xmlparse\&.c\&.
.SS "\fBint\fP XML_ParserStruct::m_nSpecifiedAtts"

.PP
Definition at line 537 of file xmlparse\&.c\&.
.SS "\fBOPEN_INTERNAL_ENTITY\fP* XML_ParserStruct::m_openInternalEntities"

.PP
Definition at line 515 of file xmlparse\&.c\&.
.SS "\fBXML_Parser\fP XML_ParserStruct::m_parentParser"

.PP
Definition at line 552 of file xmlparse\&.c\&.
.SS "\fBXML_Index\fP XML_ParserStruct::m_parseEndByteIndex"

.PP
Definition at line 472 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_parseEndPtr"

.PP
Definition at line 473 of file xmlparse\&.c\&.
.SS "\fBXML_ParsingStatus\fP XML_ParserStruct::m_parsingStatus"

.PP
Definition at line 553 of file xmlparse\&.c\&.
.SS "\fBPOSITION\fP XML_ParserStruct::m_position"

.PP
Definition at line 546 of file xmlparse\&.c\&.
.SS "\fBconst\fP char* XML_ParserStruct::m_positionPtr"

.PP
Definition at line 514 of file xmlparse\&.c\&.
.SS "\fBXML_ProcessingInstructionHandler\fP XML_ParserStruct::m_processingInstructionHandler"

.PP
Definition at line 479 of file xmlparse\&.c\&.
.SS "\fBProcessor\fP* XML_ParserStruct::m_processor"

.PP
Definition at line 510 of file xmlparse\&.c\&.
.SS "\fBPROLOG_STATE\fP XML_ParserStruct::m_prologState"

.PP
Definition at line 509 of file xmlparse\&.c\&.
.SS "\fBconst\fP \fBXML_Char\fP* XML_ParserStruct::m_protocolEncodingName"

.PP
Definition at line 502 of file xmlparse\&.c\&.
.SS "\fBXML_SkippedEntityHandler\fP XML_ParserStruct::m_skippedEntityHandler"

.PP
Definition at line 493 of file xmlparse\&.c\&.
.SS "\fBXML_StartCdataSectionHandler\fP XML_ParserStruct::m_startCdataSectionHandler"

.PP
Definition at line 481 of file xmlparse\&.c\&.
.SS "\fBXML_StartDoctypeDeclHandler\fP XML_ParserStruct::m_startDoctypeDeclHandler"

.PP
Definition at line 484 of file xmlparse\&.c\&.
.SS "\fBXML_StartElementHandler\fP XML_ParserStruct::m_startElementHandler"

.PP
Definition at line 476 of file xmlparse\&.c\&.
.SS "\fBXML_StartNamespaceDeclHandler\fP XML_ParserStruct::m_startNamespaceDeclHandler"

.PP
Definition at line 488 of file xmlparse\&.c\&.
.SS "\fBint\fP XML_ParserStruct::m_tagLevel"

.PP
Definition at line 518 of file xmlparse\&.c\&.
.SS "\fBTAG\fP* XML_ParserStruct::m_tagStack"

.PP
Definition at line 532 of file xmlparse\&.c\&.
.SS "\fBSTRING_POOL\fP XML_ParserStruct::m_temp2Pool"

.PP
Definition at line 548 of file xmlparse\&.c\&.
.SS "\fBSTRING_POOL\fP XML_ParserStruct::m_tempPool"

.PP
Definition at line 547 of file xmlparse\&.c\&.
.SS "\fBvoid\fP* XML_ParserStruct::m_unknownEncodingData"

.PP
Definition at line 506 of file xmlparse\&.c\&.
.SS "\fBXML_UnknownEncodingHandler\fP XML_ParserStruct::m_unknownEncodingHandler"

.PP
Definition at line 494 of file xmlparse\&.c\&.
.SS "\fBvoid\fP* XML_ParserStruct::m_unknownEncodingHandlerData"

.PP
Definition at line 507 of file xmlparse\&.c\&.
.SS "\fBvoid\fP* XML_ParserStruct::m_unknownEncodingMem"

.PP
Definition at line 505 of file xmlparse\&.c\&.
.SS "\fBXML_UnparsedEntityDeclHandler\fP XML_ParserStruct::m_unparsedEntityDeclHandler"

.PP
Definition at line 486 of file xmlparse\&.c\&.
.SS "\fBvoid\fP* XML_ParserStruct::m_userData"

.PP
Definition at line 462 of file xmlparse\&.c\&.
.SS "\fBXML_XmlDeclHandler\fP XML_ParserStruct::m_xmlDeclHandler"

.PP
Definition at line 498 of file xmlparse\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
