.TH "XMLFileReader" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XMLFileReader \- Reads a file and passes the results through an \fBXMLTagHandler\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <XMLFileReader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXMLFileReader\fP ()"
.br
.ti -1c
.RI "\fB~XMLFileReader\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBParse\fP (\fBXMLTagHandler\fP *baseHandler, \fBconst\fP wxString &fname)"
.br
.ti -1c
.RI "wxString \fBGetErrorStr\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBvoid\fP \fBstartElement\fP (\fBvoid\fP *\fBuserData\fP, \fBconst\fP char *\fBname\fP, \fBconst\fP char **\fBatts\fP)"
.br
.ti -1c
.RI "static \fBvoid\fP \fBendElement\fP (\fBvoid\fP *\fBuserData\fP, \fBconst\fP char *\fBname\fP)"
.br
.ti -1c
.RI "static \fBvoid\fP \fBcharHandler\fP (\fBvoid\fP *\fBuserData\fP, \fBconst\fP char *\fBs\fP, \fBint\fP \fBlen\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reads a file and passes the results through an \fBXMLTagHandler\fP\&. 
.PP
Definition at line 18 of file XMLFileReader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XMLFileReader::XMLFileReader ()"

.PP
Definition at line 25 of file XMLFileReader\&.cpp\&.
.SS "XMLFileReader::~XMLFileReader ()"

.PP
Definition at line 36 of file XMLFileReader\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP XMLFileReader::charHandler (\fBvoid\fP * userData, \fBconst\fP char * s, \fBint\fP len)\fC [static]\fP"

.PP
Definition at line 124 of file XMLFileReader\&.cpp\&.
.SS "\fBvoid\fP XMLFileReader::endElement (\fBvoid\fP * userData, \fBconst\fP char * name)\fC [static]\fP"

.PP
Definition at line 112 of file XMLFileReader\&.cpp\&.
.SS "wxString XMLFileReader::GetErrorStr ()"

.PP
Definition at line 80 of file XMLFileReader\&.cpp\&.
.SS "\fBbool\fP XMLFileReader::Parse (\fBXMLTagHandler\fP * baseHandler, \fBconst\fP wxString & fname)"

.PP
Definition at line 41 of file XMLFileReader\&.cpp\&.
.SS "\fBvoid\fP XMLFileReader::startElement (\fBvoid\fP * userData, \fBconst\fP char * name, \fBconst\fP char ** atts)\fC [static]\fP"

.PP
Definition at line 86 of file XMLFileReader\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
