.TH "XMLWriter" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XMLWriter \- Base class for \fBXMLFileWriter\fP and \fBXMLStringWriter\fP that provides the general functionality for creating XML in UTF8 encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <XMLWriter\&.h>\fP
.PP
Inherited by \fBAutoSaveFile\fP, \fBXMLFileWriter\fP, and \fBXMLStringWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXMLWriter\fP ()"
.br
.ti -1c
.RI "virtual \fB~XMLWriter\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBStartTag\fP (\fBconst\fP wxString &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBEndTag\fP (\fBconst\fP wxString &\fBname\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, \fBconst\fP wxString &\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, \fBconst\fP wxChar *\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, \fBint\fP \fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, \fBbool\fP \fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, long \fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, long long \fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, size_t \fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, float \fBvalue\fP, \fBint\fP digits=\-1)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteAttr\fP (\fBconst\fP wxString &\fBname\fP, double \fBvalue\fP, \fBint\fP digits=\-1)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteData\fP (\fBconst\fP wxString &\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWriteSubTree\fP (\fBconst\fP wxString &\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBWrite\fP (\fBconst\fP wxString &\fBdata\fP)=0"
.br
.ti -1c
.RI "wxString \fBXMLEsc\fP (\fBconst\fP wxString &\fBs\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBmInTag\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmDepth\fP"
.br
.ti -1c
.RI "wxArrayString \fBmTagstack\fP"
.br
.ti -1c
.RI "wxArrayInt \fBmHasKids\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for \fBXMLFileWriter\fP and \fBXMLStringWriter\fP that provides the general functionality for creating XML in UTF8 encoding\&. 

\fBXMLWriter\fP 
.PP
Definition at line 20 of file XMLWriter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XMLWriter::XMLWriter ()"
\fBXMLWriter\fP base class 
.PP
Definition at line 57 of file XMLWriter\&.cpp\&.
.SS "XMLWriter::~XMLWriter ()\fC [virtual]\fP"

.PP
Definition at line 64 of file XMLWriter\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP XMLWriter::EndTag (\fBconst\fP wxString & name)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 90 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::StartTag (\fBconst\fP wxString & name)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 68 of file XMLWriter\&.cpp\&.
.SS "virtual \fBvoid\fP XMLWriter::Write (\fBconst\fP wxString & data)\fC [pure virtual]\fP"

.PP
Implemented in \fBXMLStringWriter\fP, \fBAutoSaveFile\fP, and \fBXMLFileWriter\fP\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, \fBconst\fP wxString & value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 119 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, \fBconst\fP wxChar * value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 126 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, \fBint\fP value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 131 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, \fBbool\fP value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 138 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, long value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 145 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, long long value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 152 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, size_t value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 159 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, float value, \fBint\fP digits = \fC\-1\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 166 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteAttr (\fBconst\fP wxString & name, double value, \fBint\fP digits = \fC\-1\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 173 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteData (\fBconst\fP wxString & value)\fC [virtual]\fP"

.PP
Reimplemented in \fBAutoSaveFile\fP\&.
.PP
Definition at line 180 of file XMLWriter\&.cpp\&.
.SS "\fBvoid\fP XMLWriter::WriteSubTree (\fBconst\fP wxString & value)\fC [virtual]\fP"

.PP
Definition at line 191 of file XMLWriter\&.cpp\&.
.SS "wxString XMLWriter::XMLEsc (\fBconst\fP wxString & s)"

.PP
Definition at line 203 of file XMLWriter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP XMLWriter::mDepth\fC [protected]\fP"

.PP
Definition at line 54 of file XMLWriter\&.h\&.
.SS "wxArrayInt XMLWriter::mHasKids\fC [protected]\fP"

.PP
Definition at line 56 of file XMLWriter\&.h\&.
.SS "\fBbool\fP XMLWriter::mInTag\fC [protected]\fP"

.PP
Definition at line 53 of file XMLWriter\&.h\&.
.SS "wxArrayString XMLWriter::mTagstack\fC [protected]\fP"

.PP
Definition at line 55 of file XMLWriter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
