.TH "xtype_desc_struct" 3 "Thu Apr 28 2016" "Audacity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xtype_desc_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xldmem\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBtype_name\fP"
.br
.ti -1c
.RI "struct \fBnode\fP * \fBtype_symbol\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBfree_meth\fP )(\fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBprint_meth\fP )(\fBvoid\fP *, \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBsave_meth\fP )(FILE *, \fBvoid\fP *)"
.br
.ti -1c
.RI "unsigned char *(* \fBrestore_meth\fP )(FILE *)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBmark_meth\fP )(\fBvoid\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file xldmem\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP(* xtype_desc_struct::free_meth) (\fBvoid\fP *)"

.PP
Definition at line 159 of file xldmem\&.h\&.
.SS "\fBvoid\fP(* xtype_desc_struct::mark_meth) (\fBvoid\fP *)"

.PP
Definition at line 163 of file xldmem\&.h\&.
.SS "\fBvoid\fP(* xtype_desc_struct::print_meth) (\fBvoid\fP *, \fBvoid\fP *)"

.PP
Definition at line 160 of file xldmem\&.h\&.
.SS "unsigned char*(* xtype_desc_struct::restore_meth) (FILE *)"

.PP
Definition at line 162 of file xldmem\&.h\&.
.SS "\fBvoid\fP(* xtype_desc_struct::save_meth) (FILE *, \fBvoid\fP *)"

.PP
Definition at line 161 of file xldmem\&.h\&.
.SS "char* xtype_desc_struct::type_name"

.PP
Definition at line 157 of file xldmem\&.h\&.
.SS "struct \fBnode\fP* xtype_desc_struct::type_symbol"

.PP
Definition at line 158 of file xldmem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Audacity from the source code\&.
